### ISSUE TITLE
techniques to improve ddc compile times

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1003]
If and when we want to improve DDC compile times:

> To get the ddc compile times down further you can use the bazel_worker package to keep DDC alive between compiles which should speed things up some. Specifically, you want to look at the BazelWorkerDriver class. This would also allow you to handle multiple requests in parallel but limited to a set number (it handles spawning multiple workers and delegating work between them).

> If you start it in --kernel mode and compile with `--reuse-compiler-result` and `--use-incremental-compiler` it will also retain the state from the previous compiles and you should see a significant speedup.

cc @jakemac53

**Comment by jakemac53** [comment]
Fwiw, this is probably something I would be willing to take on if you would like. I suspect compile times for dartpad-like apps to be in the ~50ms range based on the build_runner times for the spinning square example.

**Comment by devoncarew** [comment]
That would be much appreciated!

We compile here: https://github.com/dart-lang/dart-services/blob/master/lib/src/compiler.dart#L147

And generate the summary and framework js files here: https://github.com/dart-lang/dart-services/blob/master/tool/grind.dart#L106

I'll be OOO for a bit, but @domesticmouse and @RedBrogdon will be around in terms of coordination.
