### ISSUE TITLE
Support debugPaintSizeEnabled for flutter_web

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1005]
Display of widget boundaries could be very useful for users working through a flutter_web codelab. We should consider adding a UI toggle that would set the value of [debugPaintSizeEnabled](https://docs.flutter.io/flutter/rendering/debugPaintSizeEnabled.html) in main.

**Comment by parlough** [comment]
Closing this as part of a repository cleanup after the newest frontend landed. If anyone would still like to see this or similar debug configuration, please open a new issue with your use case(s). Thanks so much!
