### ISSUE TITLE
Support analysis server refactoring options

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1007]
The analysis server can execute refactors like "Wrap with Row..." or "Add padding...". The DartPad UI should be extended to allow users to trigger these refactors.

**Comment by johnpryan** [comment]
From what I can tell, this is a [refactoring](https://github.com/dart-lang/sdk/blob/68ad94cebec3b2f7f6e0c0285ff160aec6e0d31d/pkg/analysis_server/lib/src/services/refactoring/refactoring.dart#L239) as opposed to a a [fix](https://github.com/dart-lang/sdk/blob/68ad94cebec3b2f7f6e0c0285ff160aec6e0d31d/pkg/analysis_server/lib/src/services/correction/fix.dart) so dart-services will need to add support for returning refactorings.

Fixes can be added by including this line:

```
    keys.bind(['alt-enter'], () {
      userCodeEditor.showCompletions(onlyShowFixes: true);
    }, 'Quick fix');
```

So it may be possible to return refactorings along with the fixes as opposed to adding a new HTTP endpoint to the CommonServer class in dart-services
