### ISSUE TITLE
Confusing error message if using `main(List<String> args)`

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart-pad#1009]
I copied and pasted some code from a command-line Dart script into DartPad and accidentally used `void main(List<String> args)` instead `void main()`.  Attempting to run gave an error:

```
Uncaught exception:
TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'
```

Since there wasn't any line number indicating which `List<String>` it was referring to, this was a bit confusing.  It might be nice if we could provide a nicer error message for this case.

**Comment by eernstg** [comment]
This is a bug, cf. [the specification of arguments to main](https://github.com/dart-lang/language/blob/59c1810f871116bec4d3e7629e0b6c81712d7bd6/specification/dartLangSpec.tex#L13951).

Apparently, both dart2js and the vm pass an instance of `List<dynamic>`. The vm allows the invocation of `main` to proceed, but `dart2js` stops at a dynamic check as you report.

So you should certainly be able to declare the main function as `void main(List<String> args) {...}`, and it should not raise an error at run time.

**Comment by domesticmouse** [comment]
Should we add a lint to our analysis call that specifically prevents `void main(List<String> args)`?

**Comment by eernstg** [comment]
I don't think there's a need for such a lint. When dart-lang/sdk#36627 is done the declaration `void main(List<String> args)` will work, and there should not be a lint for correct code. Also, even though writing a `main` with no type annotations may be a very common habit, we shouldn't discourage explicitly typed code.

**Comment by RedBrogdon** [comment]
Is the `main` given by the user the actual entrypoint used in the execution iframe? There's a good bit of wrapping involved to enable exception printouts and the like:

https://github.com/dart-lang/dart-pad/blob/master/lib/services/execution_iframe.dart#L116

**Comment by RedBrogdon** [comment]
Ah, looks like @lrhn had the same thought, but quicker. There's got to be some tweak we can do to our wrapper code to get around this.

**Comment by domesticmouse** [comment]
I re-tested this issue and it no longer looks like it is a problem. Closing.
