### ISSUE TITLE
dart-services should filter the possible completions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1014]
By default, the analysis server sends all possible completions for a location, including ones that don't match any chars the user may already have typed.

This matches what most clients want - they can apply any filtering they want locally. This causes a problem however for dartpad - when used with package:flutter_web, which has a large public namespace - you get a lot of results back. That equates to a 3.2MB json payload for the client to download.

We should perform some filter in dart-services, after we get results back from the analysis server, and before we send them to clients. That could be something as simple as determining the prefix of text already typed, and filtering results to only those starting with that prefix.

**Comment by johnpryan** [comment]
I think I have a fix here: https://github.com/dart-lang/dart-services/pull/403

**Comment by domesticmouse** [comment]
@johnpryan's change is landed and the completions are now a sane size. I believe this is now done.
