### ISSUE TITLE
proposal: dark color scheme

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1017]
JSFiddle has the ability to [embed using a light or dark theme](https://docs.jsfiddle.net/embedding-fiddles). We could also take a look at this [Github-Dark](https://github.com/StylishThemes/GitHub-Dark) extension for inspiration on how to get a dark theme with Primer

**Comment by RedBrogdon** [comment]
Created #1028 to track this and other theming requests.
