### ISSUE TITLE
Auto-closing quotes are doubled-up when user closes manually

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1021]
In the playground UI, a closing quote is automatically added when the user begins a string literal. When they eventually get to the end, manually typing the closing quote causes the editor to skip over the auto-inserted one, completing the string.

In the new embed UI, however, if the user manually closes the string, CodeMirror acts as if they're starting a new literal, and inserts *another* pair of quotes.

There is likely to be some setting in use in the playground UI that just needs to be moved over.

Original user report:

> The first code example, when you type a quote (") it auto inserts the closing quote, so you get "". If you then type out the string and manually type the closing quote (instead of removing your hands from the home keys to press arrow keys to get past the auto-inserted closing quote) then it inserts another two quotes.
> 
> If you just type out the line: 'return "$x $y";' in the editor without doing anything, you end up actually getting this: 'return "$x $y";""'
> 
> It would be preferable if, when the cursor is to the left of a quote (assuming LTR language) and the previous character is not an escape character that typing a quote just moves the cursor to the right of the existing quote without adding any characters.

**Comment by killermonk** [comment]
OK, narrowed this down a little more.

This bug is caused when an interpolated variable followed by 0 or more whitespace characters is the last part of the string.

Thing strings `"$x $y"` and `"$x $y   "` will have the issue with typing the last `"` inserting another double quote, but the string `"$x $y a"` will work as expected.

**Comment by parlough** [comment]
The latest implementation of the playground and embed layout are now shared and it seems a second closing quote is not introduced in either layout.

If anyone is still experiencing this though, please open a new issue with reproduction and device/browser details. Thanks so much!
