### ISSUE TITLE
Add a "Solution" button and show solution code in a separate tab

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1023]
Based on the discussion with @RedBrogdon, we would like to show the solution. We will start adding it without changing the current layout 

1. A user clicks on the Hint button
2. Show the hint text in the flash messages, and follow by a Solution button in the same flash container
3. The user clicks on the Solution button, the separate Solution tab will appear on the right of "Your code" tab
---

Ideally, I expect the solution button will show up next to the Hint button but we have to move most action buttons to a bottom row.

```
Your code | Solution | Test Code | Output
-----------------------------------------------------------------------------
|            editor                                              
|                                                                    
-----------------------------------------------------------------------------
**Run** | Format  Reset                                 Solution    Hint
```

**Comment by johnpryan** [comment]
Discussed offline with @galeyang we found an edge case: The "hint" button needs to be enabled when the gist has a solution, but no hint. We are going to enable the "hint" button in this case and potentially study this as part of the user study.
