### ISSUE TITLE
Support demo mode by hiding "Test code", "Hint", "Solution" 

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1024]
To support the demo/playground mode like DartPad1, add logics to hide "Test code", "Hint", "Solution" when they're not available.

cc: @RedBrogdon

**Comment by RedBrogdon** [comment]
Building on what Gale's said: at the very least we should offer embedders a way two modes for the new embed UI. One would be the "code exercise" format we have now with hints, solutions, and tests. The other would be a mini-playground that just allowed the user to mess around with some code.

Ideally we'll want to look at how to include the docs pane, regular web output, and some of the other UI options offered by the previous embed UI.

**Comment by RedBrogdon** [comment]
Partially addressed by #1047.
