### ISSUE TITLE
Support line breaks in the Hint flash messages

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1025]
We might have multiple hint items so we would like to have each point properly break into separate lines.

Current:
![image](https://user-images.githubusercontent.com/5102864/56435677-32487c00-628e-11e9-9aeb-de5dfc92973f.png)

Expected: 
![image](https://user-images.githubusercontent.com/5102864/56435777-7c316200-628e-11e9-90f5-fa062a759a91.png)

cc: @RedBrogdon

**Comment by galeyang** [comment]
In the recent UX study, user wants it to be better formatted, e.g. support wrapping lines, header, bolded text.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, hints are no longer supported in DartPad. If anyone would still like this or similar features, please open a new issue for discussion, thanks!
