### ISSUE TITLE
Update to Dart 2.3.0

### ISSUE THREAD

**Issue by apaatsio** [dart-lang/dart-pad#1027]
Update to Dart 2.3.0 would be great. Currently it seems to still use Dart 2.2.0.

**Comment by devoncarew** [comment]
The current stable version of Dart is `2.2.0` - `2.3.0` is available as a dev release, but not yet released to stable.

**Comment by apaatsio** [comment]
I see. Thank you for the response.

**Comment by devoncarew** [comment]
Thanks for the issue! We can use this to track upgrading dartpad once 2.3 is stable.

**Comment by domesticmouse** [comment]
I'll take this as I already have a test dart-services running 2.3.0-dev

**Comment by RedBrogdon** [comment]
@domesticmouse You finished this one yesterday, right?

**Comment by domesticmouse** [comment]
Yup, `dart-services` is on 2.3 now.
