### ISSUE TITLE
Support theming in playground and embed UIs

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1028]
DartPad should support (at a minimum) light and dark themes for its UIs. This is both a user preference issue and a requirement for some use cases (using a projector in a workshop is easier with a dark-on-light-background UI, for example).

Ideally, we could extend this a bit further and allow people to customize colors for the embedded UI so they can better blend it into blogs and articles.

**Comment by devoncarew** [comment]
cc @dantup and @jacob314 to see if there is any theming work we can share between dartpad and devtools

(also cc @InMatrix for places where a design could help)

**Comment by DanTup** [comment]
If this is using primer, potentially it could use our primer_dark and dark_styles files, but I don't know if trying to share them might be complicated (eg. easy for us to tweak something for dev tools that would negatively affect things here).

If we want to reuse it here, we might be better improving the primer_dark we made (so it looks decent on its own), as opposed to the current state - which is it just reverses most of the colours, and then we fix it up with overrides in our custom CSS.

I believe it has a samples/docs site you can run, so when you change the CSS/colours you can see the effect on all component states. We could use that to ensure the subset of components we use are all good "out of the box", and Dart Pad could just use that (without needing our custom tweaking), which would be much simpler.
