### ISSUE TITLE
Add an "About" display

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#103]
Info to cover:

* Who made this?
* How do I send feedback or ask a question?
* How is my source code used?
* Where is my code processed?
* What is the privacy policy?

**Comment by devoncarew** [comment]
Sounds good. @sethladd, can you provide the approx. text?

**Comment by sethladd** [comment]
First cut:

*About Dart Pad*

Dart Pad is a free, open-source service to help developers learn about the Dart language and libraries. Source code entered into Dart Pad may be sent to servers running in Google Cloud Platform to be analyzed for errors/warnings, compiled to JavaScript, and returned to the browser. Learn more about Google's [privacy policy](http://www.google.com/policies/privacy/).

Made with <3 by Google.

**Comment by sethladd** [comment]
cc @lukechurch

**Comment by devoncarew** [comment]
Created https://github.com/dart-lang/dart-pad/wiki/Privacy-Policy as our privacy policy link.
