### ISSUE TITLE
New embed: Splitter for resizing web output

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1030]
We should consider adding a moveable splitter so users can resize the area available to web output in the new embed UI. This will help in cases where the output needs more width, and it could be a handy way to play with LayoutBuilder, MediaQuery, and some other things.

**Comment by devoncarew** [comment]
@johnpryan - done?

**Comment by johnpryan** [comment]
Yeah this has been fixed in #1036
