### ISSUE TITLE
New embed UI: disable format/compilation buttons when not in user code tab

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1031]
We should consider disabling the buttons for formatting and executing code when the user is not looking at the user code editor (any time the test code, output, or solution tab is active, essentially)

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, DartPad no longer supports multiple files, including the test/solution/etc, so closing this as obsolete. Also, the format and run buttons are also overlaid on top of the source frame, so when viewing just the output, they won't be visible. Thanks :D
