### ISSUE TITLE
New Embed: flutter_web should send a "first frame rendered" message out of iframe

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1032]
Right now the execute button in the new Embed UI is re-enabling when the JS from dart-services begins executing in the iframe, not when something is actually rendered by flutter web. The difference between those two times can be several seconds, which produces a jarring effect, especially for people who aren't used to it.

Ideally, the flutter_web code inside the iframe would have some mechanism to send a message saying "Hey, I've called runApp, built, and composed a frame," so that the DartPad UI can update itself accordingly.

**Comment by parlough** [comment]
Closing this to help refocus the issue tracker due to the new frontend, including this specific integration being completely rewritten. If anyone would still like to see improvements around this behavior, please open a new issue with more details. Thanks so much!
