### ISSUE TITLE
New embed: need a way to specify starting width of web output pane

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1037]
In writing the second codelab, I'm running into problems trying to fit the widgets the user is tasked with creating into the current width of the output iframe. It's possible to work around this by cleverly structuring the "app" that surrounds the user's widgets (putting them in a FittedBox, for example), but I don't want to require everyone who uses the new embed UI to be clever.

Ideally, we'd have some mechanism for setting the starting width of the web output pane. This could be a query string parameter or some kind of metadata stored in the gist/repo that's getting loaded.

**Comment by devoncarew** [comment]
A query string param could work here.

I do like the idea of the info being embedded in the gist - the snippet could then configure it's container a bit.

Perhaps in a config.yaml file?

```yaml
dartpad:
  web-output:
    width: 320px
```

Or, as a comment in the test.dart file?

```dart
// {'dartpad': {'web-output': {'width': 320}}}

// or:

// dartpad:
//   web-output:
//     width: 320px

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
  ...
```

**Comment by RedBrogdon** [comment]
I like the metadata path better, though we need some way to fix the later examples in the Flutter codelab in the short term, which points more toward a quick fix based on the query.

Since we're on the topic, though, what else might end up in a metadata file? If we move on creating a way to load a series of exercises from a single repo rather than gists -- and the tech writers will kill me if I don't push for it 😄 -- we'll need some kind of metadata at the repo level (a list of paths to exercises, if nothing else).

**Comment by devoncarew** [comment]
> we'll need some kind of metadata at the repo level...

Yeah, it's interesting to think about how to support handling lots of examples well. The kotlin examples playground has a very simple, markdown-repo format:

    https://github.com/kotlinbyexample/kotlinbyexample.github.io

Perhaps some variant of that would work for us? We'd need to be able to encode full dartpad examples in markdown code fences somehow, with metadata.

**Comment by johnpryan** [comment]
Made an initial PR on this

On the configuration piece, perhaps we could read the configuration from the gist itself?
