### ISSUE TITLE
New Embed: Need to be able to over-scroll the code editors

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1038]
With analyzer messages appearing in a popup, it's possible for the lower lines in a code exercise to be covered up. While the user can close the popup, it will return as soon as they begin typing again.

If we eventually move the analyzer messages and test results into some other control, this problem goes away. If we continue using the popups, though, we need to find some way to allow users to scroll the lowest lines of their code higher in the window than currently allowed.

A short-term workaround for this is just to dump a bunch of extra whitespace into the code exercises, but that's not a real fix.

**Comment by johnpryan** [comment]
Is this still required? Now that there's the ability to hide / show warnings I'm not sure we need it.

<img width="501" alt="Screen Shot 2019-10-04 at 10 31 45 AM" src="https://user-images.githubusercontent.com/1145719/66227587-51976200-e692-11e9-8013-5c2e07492d1e.png">

**Comment by parlough** [comment]
The [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend doesn't use this mechanism for surfacing diagnostics, so closing this as stale.

If you have other concerns about diagnostics in the new UI, please open a new issue with new information. Thanks so much!
