### ISSUE TITLE
New embed: Formatting loses scroll position

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1039]
If the user clicks the `format` button while working in their editor and the code returned from dart-services is different than the current editor contents, the new code is swapped in and the editor jumps all the way to the top.

Ideally the code would be swapped in without the change to scroll position.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/dart-pad/commit/b2594ea740a887f701dd137394c664539aa13a51 :D
