### ISSUE TITLE
code completion UI could be improved

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1041]
We should consider improving the UI for code completion. We're currently using the stock completion UI from codemirror; it expects results for what to show in terms of strings (a display string and a string to insert). The codemirror API also allows us to return arbitrary divs, so we would be able to extend it to better match the expressiveness of the IntelliJ or VS Code completion UIs.

**Comment by devoncarew** [comment]
This is more important for the flutter_web examples, as the number of completion results is much larger than for simpler examples.

**Comment by devoncarew** [comment]
Moving this forward to the flutter.dev project, but feel free to bump it further out.

**Comment by parlough** [comment]
The code completion functionality has changed a bit since this issue was made, but has some remaining UX and DX concerns. Closing this issue in favor of addressing them together in https://github.com/dart-lang/dart-pad/issues/3010. Thanks for the discussion here!
