### ISSUE TITLE
Would like more syntax highlighting in DartPad.

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dart-pad#1052]
If I were to paste some Flutter code in:
```
class BlueBox extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 50,
      height: 50,
      decoration: BoxDecoration(
        color: Colors.blue,
        border: Border.all(),
      ),
    );
  }
}
```

Note how things like Colors are not highlighted:
![image](https://user-images.githubusercontent.com/11857803/56839328-cee2bf00-6836-11e9-9f0f-cc485af6e9e4.png)

Even though when I paste the same in VSC they are:

![Screen Shot 2019-04-26 at 3 33 38 PM](https://user-images.githubusercontent.com/11857803/56839712-b1165980-6838-11e9-847e-00956859224d.png)

**Comment by RedBrogdon** [comment]
Interesting. CodeMirror appears to be giving the `cm-variable` class to more tokens than it should ("Widget," for instance), causing them all to get the same styling. This doesn't appear to be the case in the main UI.

There may be some small config issue here, or some other simple solution. In addition, @johnpryan has expressed interest in the feature request for light/dark themes (#1028), which would be a good opportunity to examine the particular color scheme in use.

**Comment by johnpryan** [comment]
small update: https://github.com/codemirror/CodeMirror/commit/85482b0377911befe59c90fc7d714f30b59c98e7 improves the highlighting by detecting classes, but we are currently waiting for a new release: https://github.com/codemirror/CodeMirror/compare/5.48.2...master
