### ISSUE TITLE
best way to switch between a mobile and desktop UI?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#106]
If we have two different entry-points for mobile and desktop UIs, what's the best way to switch between them?

Given:
- two explicit entry-points (`index.html` and `mobile.html`)

We could use:
- a separate cname (`m.dartpad.dartlang.org`)?
- explicit links in the UIs to switch between them (`view the mobile UI` / `view the desktop UI`)?
- auto-detect and redirect on the server?
- the screen size?
-the user agent / user agent library (which is bad, but perhaps the best available option)?

**Comment by devoncarew** [comment]
@lukechurch @sethladd

**Comment by sethladd** [comment]
cc @paulkinlan for advice. How do we "negotiate" which version of the app we send? We can't just do media queries in CSS.

**Comment by sethladd** [comment]
One requirement: links that we create will be shared via social channels, and viewed on any device. A desktop user should get the desktop experience and a mobile user should get the mobile experience, regardless of what link they were sent.

Redirects on mobile are painful and slow.

Asking a user to switch between the two, explicitly, is generally not ideal. The user is wondering "am I in the "best" version?"

I think that leaves server-side detection.

**Comment by PaulKinlan** [comment]
Why can't you just do Media Queries?

**Comment by devoncarew** [comment]
We currently have two different html entry-points for the UI, one designed for desktop and one for mobile. The desktop one is built with straight DOM manipulation and the mobile one uses polymer JS. We _may_ eventually unify around polymer, but we're not there yet. As I understand it, media queries would toggle on and off css properties, which I don't think would help here.

**Comment by PaulKinlan** [comment]
With MQ you can control the entire layout of the UI, unless the UI has a
completely different function between form-factors.

**Comment by sethladd** [comment]
Think of it like two different apps. The experience for the mobile user is very different than the experience for the desktop user. It's not just a different layout, we're optimizing for different use cases.

More specifically, on a desktop, the user can edit code, get real-time errors and warnings, run the app, etc. On a mobile, the user can view the code and run the app.

As @devoncarew mentioned, the implementations are different. :)

Given all that, do we use server-side detection of the form-factor and send the appropriate file? And if so, how do we set the Vary header for caching correctly?

**Comment by devoncarew** [comment]
Closing this out in favor of #287. Short term we'll use server detect; longer term we'll refactor the UI to be programmatically responsive for phone / tablet / desktop.
