### ISSUE TITLE
Platform in dart:io fails

### ISSUE THREAD

**Issue by wyattbiker** [dart-lang/dart-pad#1062]
Error happens with all properties it seems. Although it does print the classname.

Uncaught exception:
Unsupported operation: Platform._version

```dart
import 'dart:io';
void main() {
  print(Platform);  // prints 'Platform;
  print(Platform.version);  // prints exception
}
```

**Comment by domesticmouse** [comment]
This is working as intended. The code you enter into dartpad is compiled to Javascript, and as per `dart:io`'s [documentation](https://api.dartlang.org/stable/2.2.0/dart-io/dart-io-library.html): Browser-based applications can't use this library. Only servers, command-line scripts, and Flutter mobile apps can import and use `dart:io`.
