### ISSUE TITLE
DartPad experimental doesn't handle being rate limited on Gists

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1065]
We are hitting rate limits on Gist loading. This leaves us in a state where neither the user code, nor the test code is populated. We error out silently in this case.

We should do a couple of things here:
 1. Log failure to load Gists so we can monitor when we hit rate limits
 1. Handle the situation where there is no code and the user mashes the Run button anyway

In the longer term we are probably going to have to migrate away from unauthenticated Gist loading from the front end as it will continue to cause us to fail randomly. We should probably start by loading gists through `dart-services` so we can cache responses.

**Comment by RedBrogdon** [comment]
Fixed by #1181.

**Comment by Schwusch** [comment]
This should be reopened, I cannot open Gists since I am on a shared IP and am rate limited:
`"API rate limit exceeded for <redacted> (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"`
Perhaps an option to authenticate with Github should be added?

**Comment by RedBrogdon** [comment]
Did you see this on DartPad front page or in an embedded layouts (they normally appear as iframes within other sites)?

You're right about the authentication. We have an open issue for it (#1095), but haven't had the bandwidth this year.

**Comment by Schwusch** [comment]
This is on the [DartPad front page](https://dartpad.dev/40308e0a5f47acba46ba62f4d8be2bf4), trying out one of the samples.

**Comment by greglittlefield-wf** [comment]
I'm also hitting this issue on the DartPad front page, due to being on a shared IP.
