### ISSUE TITLE
New Embed: unexpected latency between the busy indicator and test result

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1067]
There is a delay between the busy UI indicator and showing test results: 

- Clicked the run button
- Saw the busy UI indicator/animation
- The animation was gone but nothing happened
- (Latency time)
- Showed the test results

In the recent UX study, a few participants waited as the in-progress animation was on. When the animation disappeared, there is nothing shown up right away so they clicked on the output tab.

![delayedResult](https://user-images.githubusercontent.com/5102864/57553629-f439f780-7323-11e9-9540-239f66b5fd84.gif)

This issue is related to https://github.com/dart-lang/dart-pad/issues/1033

cc: @RedBrogdon 

--
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise and multi-file functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
