### ISSUE TITLE
Iframe not loading

### ISSUE THREAD

**Issue by messi01** [dart-lang/dart-pad#1078]
Iframes for Dartpad aren't loading and am unable to type code in the boxes. 
![image](https://user-images.githubusercontent.com/49079753/58135641-0c412f00-7be0-11e9-9ada-5b1d7689da73.png)

**Comment by johnpryan** [comment]
Can you try again and paste the output from the javascript console? It's working for me on https://flutter.dev/docs/codelabs/layout-basics and https://dart.dev/codelabs/dart-cheatsheet

**Comment by messi01** [comment]
Definitely! 

Here is the console for flutter.dev: 
![image](https://user-images.githubusercontent.com/49079753/58194264-ec5e4980-7c79-11e9-930c-b7fd871ebc32.png)


Here is the console for dart.dev:
![image](https://user-images.githubusercontent.com/49079753/58194319-09931800-7c7a-11e9-8eb8-19c8a8d8bc83.png)

Seems like I'm getting a syntax error that's failing to load it.

**Comment by RedBrogdon** [comment]
Are you running any extensions that might block the loading of iframes, such as an ad blocker? The ERR_BLOCKED_BY_CLIENT messages look similar to what one would expect in that case.

**Comment by RedBrogdon** [comment]
I'm going to go ahead and close this for now.

**Comment by messi01** [comment]
Apologies I missed this. Yes, you're correct. My extensions were blocking the loading of iframes and works when I disable them. Thank you!

**Comment by RedBrogdon** [comment]
No problem. Glad you were able to get it sorted out!
