### ISSUE TITLE
Functions Doc Sample returning wrong value

### ISSUE THREAD

**Issue by diegolido** [dart-lang/dart-pad#1086]
These two functions are returning diferent values in DartPad, and it was not supose to do.
The first one that is presented in documentation as a function sample, is the wrong one.
I think this can be a problem with recursive functions and should be look, 'cause can be a serious problem in other processes.

void main() {
  
int fibonacci(int n) {
  if (n == 0 || n == 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}
  
 print(fibonacci(10));
  
int fibonacci2(int num){
  
  var a = 1, b = 0, temp;

  while (num >= 0){
    temp = a;
    a = a + b;
    b = temp;
    num--;
  }

  return b;
}
  print(fibonacci2(10));
  
}

![erro_dartpad](https://user-images.githubusercontent.com/6000766/58645323-8311b280-82d9-11e9-9efd-a75f97af7de5.PNG)

**Comment by RedBrogdon** [comment]
I think you'll find that, as written, the second function is looping once too many times because it's testing with `>=` instead of `>`.

See this article for more information on the two techniques:

https://dev.to/khalilsaboor/fibonacci-recursion-vs-iteration--474l

**Comment by domesticmouse** [comment]
Here's a working implementation:

```dart
int fibonacci(int n) {
  if (n == 0 || n == 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

int fibonacci2(int num) {
  var a = 1, b = 0, temp;

  while (num >= 0) {
    temp = b;
    b = a + b;
    a = temp;
    num--;
  }

  return a;
}

void main() {
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach((i) {
    print('fib($i)');
    print(fibonacci(i));
    print(fibonacci2(i));
  });
}
```
