### ISSUE TITLE
New Embed: output tab is not immediately noticeable

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1087]
In the recent UX study, we showed participants an example code (demo mode) that will print content to the output tab. After running the code, a few participants didn’t immediately find the output. One participant suggested to have output on the same page.

We would like to evaluate a proposal in the UX fork: showing the output on the right
![image](https://user-images.githubusercontent.com/5102864/58649213-5ef5a780-82c0-11e9-8570-5b5b9a818ce1.png)

cc: @johnpryan

**Comment by galeyang** [comment]
While the Dart codelab we used in the study doesn't have an UI output, here are proposals with UI output.

![image](https://user-images.githubusercontent.com/5102864/58651228-9024a680-82c5-11e9-8e2c-1cd56fabce8b.png)

![image](https://user-images.githubusercontent.com/5102864/58651241-99157800-82c5-11e9-8456-aef5ebdb69c9.png)

**Comment by johnpryan** [comment]
rough implementation here: https://github.com/galeyang/dart-pad/tree/ux

**Comment by RedBrogdon** [comment]
In order to replace the the current embed UI, we need to replicate these three layout formats:

https://dartpad.dartlang.org/embeddings_demo.html

One of them includes a console-at-the-bottom style, which would give codelab authors a way to specifically request a more visible output window.
