### ISSUE TITLE
Validate compileDDC output on other browsers

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1090]
DDC's output is not currently guaranteed to work on non-Chrome browsers. In addition, the way our execution iframe works is not guaranteed to work with non-Chrome browsers either. Safari, for example, doesn't like the way one of the script nodes is formatted.

We need to test the new embed with a flutter_web gist on all the major browsers and see how far we can get by chasing down any issues that exist in our own code. At that point, if we do need help from the compiler team, we'll have specific test cases and asks.

**Comment by RedBrogdon** [comment]
Assigning to @johnpryan after discussing offline.

**Comment by johnpryan** [comment]
- [x] Chrome 75.0.3770.80 (macOS)
- [x] Firefox 67.0.1 (macOS)
- [ ] Safari 12.1.1 (macOS)
    - DartPad freezes
- [ ] IE Edge (Windows 10) 
    - `SCRIPT50007: Object expected` in `flutter_web.js`

**Comment by johnpryan** [comment]
The Safari issue also happens running  `flutter_web` with DDC locally on macOS

**Comment by vsmenon** [comment]
Flutter gallery is working for me on Safari (12.1.1 (14607.2.6.1.1)) with the latest with `webdev serve --auto restart`.

**Comment by vsmenon** [comment]
It is slow to start though.
