### ISSUE TITLE
Align the design of playground UI with dart.dev/pub.dev

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1092]
Much like the new embed UI, the playground UI needs to be restyled to match the color scheme and typography used in the new Dart sites.

@mit-mit has found some design help for this.

**Comment by RedBrogdon** [comment]
See also #1091.

**Comment by RedBrogdon** [comment]
Assigning this to you, John, since you're already working on it.

**Comment by johnpryan** [comment]
Using https://github.com/dart-lang/dart-pad/issues/1308 to track replacing the home page
