### ISSUE TITLE
Keyboard shortcuts in new embed UI

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1094]
The new embed UI does not support keyboard shortcuts (Cmd-enter to run, for example) as well as the playground UI. It should be brought into alignment.

**Comment by RedBrogdon** [comment]
Via several PRs, the following keyboard shortcuts now work in the new embed UI:

Ctrl-enter, Cmd-enter: Run
Alt-enter: Show quick fixes
Ctrl-space, Cmd-space: Show completions
Ctrl-/, Cmd-/: Comment-out code

FWIW, the first three are done by explicit Dart keybindings, while the last one is done through CodeMirror itself.

**Comment by galeyang** [comment]
Another note for refactoring shortcut to be included: alt+enter

Thanks @johnpryan for sharing this tip.

**Comment by johnpryan** [comment]
related to https://github.com/dart-lang/dart-pad/issues/1134
