### ISSUE TITLE
Advanced sharing from playground UI

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1097]
Once #1095 and #805 are finished, DartPad will have what it needs for a more advanced sharing flow:

- Write something cool in DartPad
- Auth into GitHub (#1095)
- Click a "share to" button
- DartPad prompts you to save your code to a gist (#805)
- Gist is created
- DartPad gives you a bunch of sharing options with pre-formatted, paste-able snippets for:
  - Reddit
  - StackOverflow
  - Twitter

**Comment by marcobraghim** [comment]
I think this is too much needed to help community share its code when ask for help. For while it is too much workful to do it so. I guess it could be even a simpler way to do it than "gist", maybe a temporary link or something...

Waiting for it... Thank you.

**Comment by timmaffett** [comment]
Now that #2227 is now live on dartpad.dev it may be time to consider updating the https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide linked to by the dartpad 'Share' menu item, and additionally extending the 'Share' menu ability to do what you are describing in 

> * DartPad gives you a bunch of sharing options with pre-formatted, paste-able snippets for:
>   
>   * Reddit
>   * StackOverflow
>   * Twitter

I love your idea here of having the ability to easy share your dartpad gist to Reddit/StackOverflow/Twitter (and perhaps others ?)
Would a 'Share on ...' menu with submenus for the various possibilities be nice ? Maybe we actually redirect to the site with the snippet ready to go ?

Would it be useful to create a new issue soliciting ideas about possible approaches and useful features ?   

Making sharing dartpad gists super simple seems like a wonderful way to promote the wonders of flutter and dart.

**Comment by parlough** [comment]
https://github.com/dart-lang/dart-pad/issues/2808 dropped the GitHub authentication and sharing feature, so I'm going to close this as obsolete. If anyone reading this desires more sharing functionality like this from DartPad, please open a new issue for discussion. Thanks!
