### ISSUE TITLE
Slight bump in bottom status bar when analyzer messages appear

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1102]
I'm getting a bit of a bump in the new embed when analyzer messages become available:

![bump](https://user-images.githubusercontent.com/969662/58979082-176c9100-8782-11e9-935f-8b09f76be7a5.gif)

Looks like it's the appearance of the button that's doing it. For a Dart codelab it's not that noticeable, but it's affecting the size and positioning of Flutter output, which would cause a layout/paint cycle and potentially have weird consequences.

**Comment by RedBrogdon** [comment]
@johnpryan Has this been fixed in the latest round of UI updates? If so, take credit and close it. 😄

**Comment by johnpryan** [comment]
This is fixed now - the bottom bar has been replaced with an absolutely positioned label / button
