### ISSUE TITLE
Filter out errors generated by test code

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1106]
We should not expect readers going through a codelab to ever look at the test code in order to figure out something that's gone wrong. It's good that they *can*, but it shouldn't be a requirement.

To that end, we should determine a way to filter out compiler errors generated by the code in the test editor, and substitute something more helpful.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, multi-file support and testing in embeds is no longer supported, so closing this as obsolete. If anyone reading this desires any testing functionality, please open a new issue. Thanks :)
