### ISSUE TITLE
Catch errors caused by expected-but-missing functions in user's code

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1107]
In a typical [exercise gist](https://gist.github.com/RedBrogdon/43f3db47b0632c557200270807696687), the test code anticipates the existence of certain methods or classes in the user's code. If those are removed, the exercise can't run.

We need to communicate that state to the user in a way that's easily understandable. Right now, however, users see a compiler error referencing the call site, which would (from their perspective) be hidden in the test code tab.

It may not be possible to do this with cleverly test code snippets, though we ought to be able to do it with an additional call to the analyzer on the server asking about a particular function or class.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
