### ISSUE TITLE
Get flutter_web running on Safari

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1108]
@johnpryan's research found that running DDC-built flutter_web projects in DartPad was possible, but caused the browser to hang for ~15 seconds during initial loading and parsing.

![image](https://user-images.githubusercontent.com/969662/59135427-b389ca00-8933-11e9-94c5-5ee9037ab3b2.png)

This was also replicated with a local copy of a hello world flutter_web project.

**Comment by RedBrogdon** [comment]
After repeated attempts to refactor the Dart SDK and Flutter for web SDK to work around the delay in Safari, I haven't found a way to solve this issue.

As a result, I created a repo to demonstrate the problem:

https://github.com/RedBrogdon/parsing_speed

And filed a bug with the WebKit team after verifying the issue with their nightly build:

https://bugs.webkit.org/show_bug.cgi?id=199866

One of the engineers on their team has taken a look, and we'll hopefully see some movement toward a fix one way or another.

In the meantime, we'll need to focus on properly messaging the situation to anyone trying to use Flutter in DartPad with Safari.

**Comment by RedBrogdon** [comment]
Still waiting to hear back from the folks at WebKit. In the meanwhile, we need to:

* Display a message in an MDC dialog when someone using Safari gets to either the new embed or the playground in flutter mode.
* Remove this task from our existing project milestones.

I've created #1197 to track the former.

**Comment by RedBrogdon** [comment]
Downgrading this, as we're essentially stuck waiting on a fix from WebKit.

**Comment by RedBrogdon** [comment]
Because Apple and Google often report bugs/feature requests for each other's stuff, there's someone on our end dedicated to managing the process of communicating things and trying to escalate them where appropriate. I'm working with them now, though I still don't have any kind of roadmap for when a fix is inbound.

**Comment by lukepighetti** [comment]
From my little bit of testing over here it sounds like this problem exists even for production `flutter_web` builds. Are there any known workarounds to ship a low-impact product with `flutter_web` that works on Safari?

**Comment by RedBrogdon** [comment]
I've only encountered the issue with builds done with the development compiler, DDC. If you're seeing it with stuff that's been created with dart2js (the minifying, name-mangling release-mode compiler), that's a more serious issue and should be filed as an SDK bug.

Flutter supports the open standards of the web and should work on all the major browsers.

**Comment by lukepighetti** [comment]
Let me fiddle around with it more before escalating, I could be mistaken. Thanks for your time.

**Comment by RedBrogdon** [comment]
The WebKit team got back to us a short while ago with a possible workaround:

https://bugs.webkit.org/show_bug.cgi?id=199866

That change was made to the Dart SDK's development compiler:

https://dart-review.googlesource.com/c/sdk/+/133542

And we are no longer seeing a delay when running DartPad in Safari, either on macOS or iOS. 😄
