### ISSUE TITLE
Get flutter_web running on Edge

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1109]
@johnpryan's research (via browserstack) found that DDC-compiled flutter_web code failed to execute in DartPad.

![image](https://user-images.githubusercontent.com/969662/59136047-3875e300-8936-11e9-812d-fecb16baba8a.png)

This hasn't been replicated locally, so it could be an issue with how our execution iframe is setting things up rather than with the compiled code itself. We need to narrow things down before taking the issue to the compiler team.

**Comment by RedBrogdon** [comment]
I just tried experimenting with Edge on a Windows desktop. I'm getting no error in the JS console, but blank Flutter output and this in the DartPad console:

![image](https://user-images.githubusercontent.com/969662/59142356-fb2f4680-8971-11e9-97a0-df26bdc77a97.png)

That seems to match the message here:

https://github.com/flutter/flutter_web/blob/69acfd97c5a7bf0605e9a01df7749716ceb1707f/packages/flutter_web_ui/lib/src/engine/browser_detection.dart#L37

I'm running Edge 42.17134.1.0, EdgeHTML 17.17134 on patched Windows 10.

**Comment by domesticmouse** [comment]
I believe we can run ms edge on macOS now, so we can poke it from FlutterWeb directly. I suspect repro’ing this outside of DartPad is a good first step, yeah?

https://www.techradar.com/news/you-can-now-install-microsoft-edge-on-macos

**Comment by johnpryan** [comment]
It looks like Edge for macOS (dev channel - a stable version isn't
available yet) is working. I'm not seeing the same error Andrew reported or
the one I was seeing in Browserstack (Windows 10 + Edge)

**Comment by RedBrogdon** [comment]
I'm going to go ahead and close this one. I'm having no trouble running our Flutter codelab with the dev builds of Edge on either Windows or MacOS, both of which are base on Chromium.

We have 4x as many site visitors running Edge as standard IE, and I expect that ratio to only increase.
