### ISSUE TITLE
Consider to show analyzer messages by default

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1110]
Follow up https://github.com/dart-lang/dart-pad/pull/1050 Toggle analysis issues using a button

In the pilot session of the Round 2 study, participant didn't notice the bottom right toggle button and wasn't sure how to check analyzer error messages indicated by the underline. 
![image](https://user-images.githubusercontent.com/5102864/59232186-432fb280-8b98-11e9-88ec-b3b880822e3f.png)

In the UX branch, could we show this popup by default so that it's more discoverable? Users can hide it if they want.

cc: @johnpryan

**Comment by johnpryan** [comment]
done! c188b8c953b880bc588994f54ba36bf16fd222f9

**Comment by galeyang** [comment]
It shows an empty container when it is first loaded.
![image](https://user-images.githubusercontent.com/5102864/59302110-09b68000-8c48-11e9-89d0-a3ee18f11884.png)

**Comment by johnpryan** [comment]
good catch - Just pushed a [fix](3b6f0826cb50b0aafb17dc681153465e90026b46) to the ux branch

**Comment by galeyang** [comment]
The link doesn't work. I checked out the code locally and the UI looks good! Thanks!
