### ISSUE TITLE
Clicking on an issue in the analyzer messages should bring up the user code tab

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1119]
It's possible to be looking at a secondary tabview (solution, test code, etc) while the analyzer messages are up and visible. Clicking on one of the messages highlights the code in the user code editor, but doesn't actually make that editor visible, which it should.

**Comment by patkellydesigns** [comment]
@RedBrogdon i'll dig into this. Not sure this is the right place to write this if so; I apologize the GitHub adventure has just begun. Thanks for the suggestion.

**Comment by RedBrogdon** [comment]
No problem. Feel free to post another comment if you have trouble getting up and running with the codebase or just have a question in general.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, DartPad no longer supports multiple files/source tabs, so I'll close this as obsolete. I also verified that selecting/clicking a specific diagnostic in the single file view, still focuses the effected span :)
