### ISSUE TITLE
Using RPC auto-gen client causes errors in the console

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#112]
Refused to set unsafe header "user-agent"
Refused to set unsafe header "content-length"

@wibling lets chat about what we're going to wrt this.

**Comment by wibling** [comment]
There is a fix out for this at: https://codereview.chromium.org/975683002/

**Comment by wibling** [comment]
Fixed by commit a54a5b3b53a3cf8fedda5b03d1c698f054a913fc
