### ISSUE TITLE
use cursor position info from analyzer refactorings

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1122]
When calling the ‘wrap with widget’ refactoring, we should use the returned info about where to position the cursor.

<img width="266" alt="Screen Shot 2019-06-20 at 11 43 14 AM" src="https://user-images.githubusercontent.com/1269969/59873362-b2ec2d00-9350-11e9-8e47-e31429ccfa7f.png">

<img width="243" alt="Screen Shot 2019-06-20 at 11 43 22 AM" src="https://user-images.githubusercontent.com/1269969/59873368-b7b0e100-9350-11e9-9282-3d266aab3df9.png">

In the above images, the cursor is position after the manipulated widget, but we should instead be selecting the text `widget`, to allow the user to name the newly inserted widget.

**Comment by RedBrogdon** [comment]
Looks like we get either a selection offset or a list of "linked edit groups" which are regions to be selected and edited simultaneously. These look similar to how the `stful` live template in IntelliJ will produce a StatefulWidget and State class, put the cursor where the name for the widget should go, and then update the State object's name as you type the widget's name.

My plan is to expose all possible information in the data returned by dart-services, and then we can update dart-pad incrementally. For a start, it's probably enough just to figure out where to leave the cursor, though CodeMirror does support multiple cursors at once and related fanciness.

**Comment by RedBrogdon** [comment]
We now have a valid cursor position after each assist/fix. DartPad still needs a proper UI for the linked edit groups referenced above. That's now being tracked as #1213.
