### ISSUE TITLE
improve the discoverability of the flutter widget refactorings

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1123]
We should improve the discoverability of the flutter widget refactorings (map them to buttons / icons on the screen?). This would make it easier for new developers to work with flutter code.

**Comment by devoncarew** [comment]
Instead of icons, we could have a ‘quick fix’ menu in-line in the code, when refactorings are available.

**Comment by RedBrogdon** [comment]
An inline indicator sounds promising. IntelliJ has that little yellow lightbulb that pops up when the assists are available. We could probably do something similar.

**Comment by RedBrogdon** [comment]
Wasn't able to get this done in July. Moving back on deck for the time being.

**Comment by parlough** [comment]
Closing this as stale as there hasn't been more interest in the feature since 2019. Please feel free to reopen if you see this as important to surface in DartPad still. Thanks!
