### ISSUE TITLE
Update CodeMirror theme and new Embed UI to new design

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1127]

**Comment by johnpryan** [comment]
Phase 1: https://github.com/dart-lang/dart-pad/pull/1136

**Comment by johnpryan** [comment]
phase 2: https://github.com/dart-lang/dart-pad/pull/1153
phase 3: https://github.com/dart-lang/dart-pad/pull/1158

**Comment by johnpryan** [comment]
Marking as closed, - we can iterate on further design tweaks we need.
