### ISSUE TITLE
DartPad sends incorrect first argument to `main`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#1132]
A program like:
```dart
main(List<String> args) {}
```
fails with the error:
```
Uncaught exception:
TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'
```
The first argument to main *must* be a `List<String>`, so the wrapper code calling the main function here is doing something wrong.

It's not that arguments to main are particularly useful in dartpad, but sometimes you copy-n-paste code which has them, and it's annoying to have to fix the code for this unrelated issue.

**Comment by eernstg** [comment]
May be the same thing as this: https://github.com/dart-lang/sdk/issues/36627.

**Comment by RedBrogdon** [comment]
@lhrn, thanks for filing this and providing extra detail. Since we already have an issue tracking this (#1009), I'm going to close this one.

Please feel free to add additional comments/info there.
