### ISSUE TITLE
Add a UI to embeds to introduce the keyboard shortcuts

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1134]
The keyboard shortcuts are implemented here https://github.com/dart-lang/dart-pad/issues/1094
It would be great to have a place to list out these hotkeys so that they're more discoverable. This is less important in exercises but can be useful in a playground.

Examples:
Kotlin
![image](https://user-images.githubusercontent.com/5102864/60299098-bea39a80-98e0-11e9-933e-44eb59fa7da4.png)

Another transcription service
![image](https://user-images.githubusercontent.com/5102864/60299132-d713b500-98e0-11e9-9a43-d2d75f5e3092.png)

**Comment by RedBrogdon** [comment]
Ideally we should have a keyboard shortcut to display the shortcuts, similar to a number of other editors.

**Comment by jawahars16** [comment]
@RedBrogdon Looks like this is already implemented. I can see a key bindings dialog using the shortcut `shift-ctrl-/`. Is there anything wrong or pending with this functionality?

**Comment by johnpryan** [comment]
@jawahars16 I think this issue was to track adding this dialog to the embeds

**Comment by parlough** [comment]
Thanks for the discussion here! I'm going to close this in favor of a consolidated information menu for the embed form of the UI - https://github.com/dart-lang/dart-pad/issues/3007.
