### ISSUE TITLE
Add a solution link to the test passed message

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1138]
In a recent UX study, at least 5 out 10 participants want to see a solution even after passing the tests. It would be helpful to add a solution link in the test passed message. Click on this link will open the solution tab.

User quotes:
> For coding there's always more than one way for doing something. So just because I got these samples correct, you might actually have a different way to get that answer and it might present a way to me that I might want to start using more often.

> If my code passed but I wasn't super confident with the way that I'd written it and I wanted to see like what the what the suggested correct answer was. 

---------
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise and multi-file functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
