### ISSUE TITLE
Default sample not compile

### ISSUE THREAD

**Issue by robsonataide** [dart-lang/dart-pad#1140]
Error output:
```
Error compiling to JavaScript:
XMLHttpRequest error.
```

**Comment by domesticmouse** [comment]
May I ask which URL you were accessing dartpad on, and what code you were trying to run?

**Comment by robsonataide** [comment]
I did same test again and saw that this problem is related with the browser.

![imagem](https://user-images.githubusercontent.com/793795/60728360-05743e80-9f38-11e9-8281-0927215a4250.png)

**Comment by domesticmouse** [comment]
I'm guessing from the on-screen chrome that you are using a version of FIrefox. I'm testing with Firefox Developer edition, 69.0b2 (64-bit) on macOS, but I'm not seeing anything interesting with the `dart-services` requests and responses. I'm confused.

/cc @johnpryan @RedBrogdon  any ideas?

**Comment by johnpryan** [comment]
Could you try opening up the network tab to see the http response?

**Comment by johnpryan** [comment]
we might need to double check that DartPad.dartlang.org is still included in the [access-control-allow-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) headers. If it’s, not we should be redirecting to dartpad.dev

**Comment by domesticmouse** [comment]
The CORS headers that I'm serving from `dart-services` for the `compile` call are as follows:

```bash
access-control-allow-credentials: true
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-methods: POST, OPTIONS
access-control-allow-origin: *
```

**Comment by domesticmouse** [comment]
I'm closing this out for now as I can't see anything we can change on our end to make this work for the original reporter's environment. If there is something we can do, please comment and I'll happily re-open.

**Comment by robsonataide** [comment]
@domesticmouse and @johnpryan ... the error is my corporate proxy, in my home works! If you want more details about the requests, for future investigation, I´m sending as attachment.

XHR´s:
[Archive 19-07-10 14-07-20.log](https://github.com/dart-lang/dart-pad/files/3377590/Archive.19-07-10.14-07-20.log)
[Archive 19-07-10 14-07-32.log](https://github.com/dart-lang/dart-pad/files/3377591/Archive.19-07-10.14-07-32.log)
