### ISSUE TITLE
Usage guidelines for DartPad embeds

### ISSUE THREAD

**Issue by rohan-jpg** [dart-lang/dart-pad#1142]
I'm interested in using [DartPad embeds](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide) in an introductory tutorial to Dart, so users can interact with the Dart code and complete Dart exercises.

Can you let me know if it's OK to DartPad embeds in tutorials?

Are there any known usage limits on using DartPad embeds?

**Comment by RedBrogdon** [comment]
It's absolutely okay. We'd like to see DartPad used by as many folks as possible!

We haven't yet had to introduce usage limits on embeds. However, if you're loading code into the editor using a GitHub gist, those calls are done using GitHub's unauthenticated API, which has a rate limit of 5k/hr. Most people using a tutorial won't come near that (unless there's a bunch of them tunneling through a single IP address), but it's possible to run into it while writing and testing exercises.

We currently have two embed UIs, BTW. There's a stable version (covered in in the doc you linked) and an experimental version you can see in use at:

* https://dart.dev/codelabs/dart-cheatsheet
* https://flutter.dev/docs/codelabs/layout-basics

The experimental version introduces the ability to use Flutter for web and run tests to see if a user has completed an exercise correctly. At some point in the neat future, we intend to have it replace the older, stable embed UI. I wouldn't recommend basing a public tutorial on it right now (The API isn't completely stable, and the URL may change), but if you'd like to experiment with it, we'd love to know the results.

We already have an issue tracking the need for more documentation on the embeds (#1104), so I'm to close this out as a dupe. Please feel free to add more info on that issue about what you'd like to know about using DartPad. As I said, we'd like it to be a useful tool for as many people as possible.
