### ISSUE TITLE
dartpad.dartlang.org should redirect to dartpad.dev

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1146]
In order to avoid breaking a bunch of embeds, we'll need to maintain the path while changing the domain.

**Comment by domesticmouse** [comment]
More than just the path, you'll need to maintain the #ref, which is never passed to the server.

**Comment by kevmoo** [comment]
See this search – https://www.google.com/search?q=dartpad

At a minimum, we should update the site to have a canonical URL header to send search engines to the right place!

**Comment by natebosch** [comment]
Did this used to redirect and it stopped? A bunch of people are complaining about legacy links that point to `https://dartpad.dartlang.org/` no longer

**Comment by parlough** [comment]
It does seem like it was setup to redirect and then stopped.

I'll close this in favor of the newer https://github.com/dart-lang/dart-pad/issues/2638 issue that is focused on bringing back the redirect. I still think this is something we should bring back.

If anyone has access to the domain configuration, please consider helping out :)
