### ISSUE TITLE
New feature: interactive observation

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1148]
## Feature introduction: interactive observation
Users mouseover an explanation and the relevant code (in the Dartpad) is highlighted. 

Goal: make it easier to reference important code snippets
Use cases: explain the concepts in demo code examples and solutions.

This is the initial prototype. We would like to implement a similar feature in Dartpad
![interative observation](https://user-images.githubusercontent.com/5102864/61248536-1a0ac080-a708-11e9-81a4-1669ef536012.gif)

## Study result
In the UX study, **9 out 10 participants like this feature**. They said this is

>  “handy, pretty useful, easier to go back and forth than having to check line number, bringing focus, haven’t seen this before”. 

This feature also reminded them of classroom experience (teacher pointing on the blackboard while explaining things) or the web inspector.

## Next step
Once this issue is scheduled to be implemented, we would need to further define how to apply this to Dartpad and address the following known usability issues:

- Users may not notice it at first glance when it's out of view
- Users may have to scroll up and down if it's out of view

Feedback welcome!

--------
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
