### ISSUE TITLE
Embed: improve the visual distinction between example and exercise

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1150]
## UX study result
When few participants first saw many visually identical editors (some are examples, while others are exercises) in the Future codelab https://github.com/dart-lang/site-www/pull/1659, they were unsure what they were supposed to do (entering code vs. clicking the Run). 

> Going from code window where you're supposed to write in, to code window where you're not supposed to write in in the same scroll is confusing to me --- the confusion between which ones were supposed to be edited, just like got a glance.

> Sometimes, I wasn't sure like whether I should just to code something or I'm supposed to just run it to see it. 

For short term, @legalcodes has made two changes to the Future codelab 
- use light theme for examples and dark theme for exercises
- add a prominent title (Example or Exercise) above each embed

## Improvements to considered
- Change the tab label to Example or Exercise (or add extra heading, like [W3School](https://www.w3schools.com/js/js_functions.asp))
![image](https://user-images.githubusercontent.com/5102864/61251279-ce0f4a00-a70e-11e9-9ce4-0d777a137db3.png)
- Style the placeholder https://github.com/dart-lang/dart-pad/issues/1156

_Example from Kotlin_
![image](https://user-images.githubusercontent.com/5102864/61251333-f72fda80-a70e-11e9-91c7-7f6b267dfc18.png)
_Matching the our color theme_
![image](https://user-images.githubusercontent.com/5102864/61251386-22b2c500-a70f-11e9-8d62-a77db81c21d0.png)

- Or maybe in the demo mode, hide the format, reset, and analyzer UI unless users start making changes

Feedback welcome!

-----

Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
