### ISSUE TITLE
Users were little confused by the info analyzer message in the exercise

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1152]
Few participants were a little confused when they saw an info message before and/or after they passed the test. They were unsure if they were supposed to fix it in the exercise.

![image](https://user-images.githubusercontent.com/5102864/61252971-47f60200-a714-11e9-8145-7cd422d46f3b.png)

As a short term fix in the Dart Future codelab https://github.com/dart-lang/site-www/pull/1659, @legalcodes added the note below.

![image](https://user-images.githubusercontent.com/5102864/61252717-4ed04500-a713-11e9-87ec-28325cb0db24.png)

To improve exercises in Dartpad, we may want to add an tooltip to info message or add a note if users pass tests with info messages.

Feedback welcome!

**Comment by InMatrix** [comment]
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
