### ISSUE TITLE
Staging environment needed

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1155]
DartPad lacks a proper staging environment. As the project gets larger and more complicated, this will become more and more necessary.

**Comment by domesticmouse** [comment]
I'm curious what problems you are attempting to control that require a staging `dart-services` cluster.

**Comment by domesticmouse** [comment]
Blocked on https://github.com/dart-lang/dart-pad/issues/1506

**Comment by domesticmouse** [comment]
I'm calling this done for now. The `dev` channel is a staging ground for testing out Package support and can be altered as required.
