### ISSUE TITLE
Style the instructional placeholder/comments

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1156]
This is an indicator that guides users where to enter code in exercises.
_// STEP 1: Put constructor here.
// TODO: Put constructor here._

Goal: allow users quickly identify where code should go 

Currently we used comments for this purpose
![image](https://user-images.githubusercontent.com/5102864/61327129-12f9b600-a7cd-11e9-9bd8-620c5d81cdcb.png)

It would be good to further style this placeholder
![image](https://user-images.githubusercontent.com/5102864/61327156-23119580-a7cd-11e9-8d13-a350475c1bd9.png)

![image](https://user-images.githubusercontent.com/5102864/61327024-e180ea80-a7cc-11e9-8abc-c8baee421be7.png)

**Comment by InMatrix** [comment]
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
