### ISSUE TITLE
Remove embed-new.html

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1163]
Now that the websites are updated, experimental/embed-new.html can be removed in favor of `experimental/embed-new-flutter.html`, `experimental/embed-new-html.html`, `experimental/embed-new-inline.html` and `experimental/embed-new-dart.html`

**Comment by RedBrogdon** [comment]
@johnpryan: Should this be closed out?

**Comment by johnpryan** [comment]
yes, this is done now.
