### ISSUE TITLE
Console output is too small in Basic Flutter Layout codelab

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1164]
The console output is slightly too small to be useful:

![Screen Shot 2019-07-18 at 2 35 10 PM](https://user-images.githubusercontent.com/1145719/61493776-45d8b100-a969-11e9-9fb2-2069dffd2b1a.png)

We should allow the console to be larger.

@galeyang We should also consider using a larger height for DartPad itself. The layout-basics codelab uses 400px but maybe we can make it slightly taller assuming we are able to address #1149

**Comment by galeyang** [comment]
I agree that the console is too small in this case. It seems like I can drag to make it larger but there is a limit. Can we make the max height larger?

Re:
> We should also consider using a larger height for DartPad itself. The layout-basics codelab uses 400px but maybe we can make it slightly taller assuming we are able to address #1149

I'm not sure I understand how making it taller help address #1149. @johnpryan Could you share more?

**Comment by johnpryan** [comment]
I think we might be able to DartPad taller than 400px if we also have a solution for #1149, but if we don't, it's best to keep DartPad smaller.
