### ISSUE TITLE
Improve print styles (as in, printing a hard copy)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#1169]
I tried to save my eyes by printing out a codelab, but the print styles don't reflect what I see onscreen.

Here's what prints:
![image](https://user-images.githubusercontent.com/2164483/61754950-43f85e80-ad6a-11e9-8b06-3f6debd399b1.png)

Here's what I expected to see:
![image](https://user-images.githubusercontent.com/2164483/61754960-55416b00-ad6a-11e9-8e9d-a6cf4607b4ba.png)

Just a plain, unadorned code snippet would be fine, too.

**Comment by RedBrogdon** [comment]
TBH, this is likely to sit in the backlog for a while unless people make noise about it. If printing DartPad is important to you, please leave a comment or a reaction below!

**Comment by parlough** [comment]
It is now over 4 years later and there has not been any noise raised, so I'm going to close this issue 😉

Either way, for the embed case in the original issue, I think this is better handled by the site embedding DartPad. They can customize styles for printing that hides the embedded DartPads and instead show the original code snippet.

Thanks for the discussion here!
