### ISSUE TITLE
Hide the Hint button when the gist has no hint

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1171]
Since we improved the discoverability of solution code in https://github.com/dart-lang/dart-pad/issues/1159, can we hide the Hint button when there is no hint file?

Previous context:
https://github.com/dart-lang/dart-pad/issues/1023#issuecomment-485526471
> we found an edge case: The "hint" button needs to be enabled when the gist has a solution, but no hint. We are going to enable the "hint" button in this case and potentially study this as part of the user study.

cc: @johnpryan

**Comment by RedBrogdon** [comment]
This should be happening right now:

https://dartpad.dartlang.org/experimental/embed-new-dart.html?fw=true&id=ed561e99ff358b98b9a659ea70fca7fa

Are you seeing it with a specific gist, and if so, can you add the link here?

**Comment by galeyang** [comment]
The gist you referred to is an example so it doesn't have a hint (or solution).

An example I'm seeing: https://dartpad.dev/experimental/embed-new-flutter.html?id=0c97de625a9aa5c3194f9eecbd73ec1a

![image](https://user-images.githubusercontent.com/5102864/61829097-0d2f5080-ae1d-11e9-83c3-94c649128bdf.png)
