### ISSUE TITLE
Hide the Show tests button for examples (with no tests)

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1173]
When it's an example that has no tests, the Show tests button should be hidden. One participant in the UX study found this empty tests confusing in an example.

![image](https://user-images.githubusercontent.com/5102864/61827801-3e5a5180-ae1a-11e9-8232-a7850f75b760.png)

**Comment by galeyang** [comment]
cc: @johnpryan

**Comment by InMatrix** [comment]
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by kwalrath** [comment]
I just noticed this issue in the dart.dev front page.
