### ISSUE TITLE
Add run query parameters

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1185]
We may need to add query parameters supported by the old version of embed-dart and embed-inline.

- run
- (optional) console ([ref](https://github.com/dart-lang/site-www/pull/1799#discussion_r308978277))

We don't need horizontalRatio and verticalRatio since we have the `split` option.

**Comment by galeyang** [comment]
@johnpryan  What does "run" mean here?

**Comment by johnpryan** [comment]
In the original version, it immediately executes the code instead of waiting for the run button to be clicked

**Comment by RedBrogdon** [comment]
Moving to September milestone as a carryover
