### ISSUE TITLE
Make "console" label take up less space

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1187]
The "Console" label takes up a whole row of output; which could be used to display the output itself:

<img width="503" alt="Screen Shot 2019-07-29 at 3 58 01 PM" src="https://user-images.githubusercontent.com/1145719/62088270-a8f3fe80-b219-11e9-8f62-60277bf6da8f.png">

**Comment by galeyang** [comment]
There is an unexpected scrollbar (at lease for my laptop)
![image](https://user-images.githubusercontent.com/5102864/62167940-25014b80-b2d9-11e9-922f-b3de75f1b6e9.png)


 Also, can we make the entire collapsed row clickable (to expand it)? Currently, we can only click on the tiny arrow on the right.

![image](https://user-images.githubusercontent.com/5102864/62168046-714c8b80-b2d9-11e9-874d-2a663d1a96e0.png)

**Comment by galeyang** [comment]
I found the problem of unexpected scrollbar in my previous screenshot only show up when I use a mouse with a mac laptop.
