### ISSUE TITLE
Improve dark theme contrast

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1192]
We've gotten some feedback that the dark theme may be difficult to read. Below is a screenshot:

![dark mode](https://user-images.githubusercontent.com/1145719/62254085-b7265400-b3ac-11e9-98f1-9fe202436737.png)

we should try to improve the contrast / brightness of certain colors, and consider adjusting the font

**Comment by galeyang** [comment]
Just added another screenshot so that we will remember to check flash messages.
![image](https://user-images.githubusercontent.com/5102864/62387307-100dfd80-b50f-11e9-96bb-710f4f78c2f1.png)

**Comment by galeyang** [comment]
Could we fix the color contrast for the flash messages first? The test result in dark theme is very hard to read. Thank you!
