### ISSUE TITLE
Analyzer messages obscure the "Show solution?" confirmation dialogue

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1194]
I would expect the css z-index (or other things controlling the layers?) of the confirmation dialogue and the mask are higher than the analyzer messages. 

Screenshot:
![image](https://user-images.githubusercontent.com/5102864/62403887-40708e80-b545-11e9-93a2-ac03b92c7ed9.png)

**Comment by RedBrogdon** [comment]
One of our UI invariants should be that the dialog's z-index is higher than everything else. Otherwise it can't work as a proper modal.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality solutions were part of was removed.

If anyone sees similar issues with the new frontend, please open a new issue with reproduction instructions. Thanks so much!
