### ISSUE TITLE
Fix disableable buttons

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1196]
`.disabled` doesn't affect the appearance or behavior of material-design buttons. This is causing inconsistencies, for example the reset button should be disabled if there isn't a gist or snippet.

**Comment by parlough** [comment]
https://github.com/dart-lang/dart-pad/commit/506db28f75a7c19fdb492b241de49eb4a5df07d1 dropped this version of the UI, so closing this as obsolete. Thanks!
