### ISSUE TITLE
Plan changes to playground for integrating Flutter

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1198]
Updating the playground UI for Flutter is a large task that needs to be broken down. We need individual issues for each of the subtasks.

**Comment by RedBrogdon** [comment]
Deliverables here are a set of smaller issues in this repo and a short design doc covering the changes to be made.

**Comment by johnpryan** [comment]
Here's the three major tasks I see:

- https://github.com/dart-lang/dart-pad/issues/1224
- https://github.com/dart-lang/dart-pad/issues/1225
- https://github.com/dart-lang/dart-pad/issues/1226

#1226 can most likely be broken down further, but I imagine we can keep it as one issue for now.
