### ISSUE TITLE
How to use experimental flutter ?

### ISSUE THREAD

**Issue by amadeu01** [dart-lang/dart-pad#1201]
I try to copy code from https://flutter.dev/docs/codelabs/layout-basics
and paste it here http://dartpad.dev/experimental/embed-new-flutter.html

but I couldn't get it working with http://dartpad.dev/experimental/embed-new-flutter.html

Is there any additional setup?

**Comment by johnpryan** [comment]
There shouldn't be any additional setup. Can you paste the snippet you are trying to get working?

**Comment by johnpryan** [comment]
Actually, some of the snippets in that article have test code that is hidden. A full working example (without hidden test code) might look like this:

```
import 'package:flutter_web/material.dart';
import 'package:flutter_web_test/flutter_web_test.dart';
import 'package:flutter_web_ui/ui.dart' as ui;

Future main() async {
  await ui.webOnlyInitializePlatform();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp();

  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(children: [
          BlueBox(),
        ]),
      ),
    );
  }
}

class BlueBox extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 50,
      height: 50,
      decoration: BoxDecoration(
        color: Colors.blue,
        border: Border.all(),
      ),
    );
  }
}
```

A full example for a codelab (with test code) looks like this: https://gist.github.com/RedBrogdon/76e993732820ef908ea8424744b9996d

**Comment by amadeu01** [comment]
@johnpryan thanks, 

when I pasted the `test` snippet, it worked.

this -> `await ui.webOnlyInitializePlatform();` is the step that wasn't clear to me untill now. 

Thanks !!!
