### ISSUE TITLE
DartPad fonts aren't loading properly

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/dart-pad#1203]
We haven't yet narrowed down the circumstances under which this happens, but at least in Windows (running Chrome) the fonts aren't loading: 

![Annotation 2019-08-14 102135](https://user-images.githubusercontent.com/5550175/63042274-7f281200-be7e-11e9-917b-be2cf7db5181.png)

**Comment by RedBrogdon** [comment]
Is this just in the new embed, or have you seen it in the playground/old embed as well?

**Comment by RedBrogdon** [comment]
CC @johnpryan

**Comment by legalcodes** [comment]
Playground looks fine. 
`/embed-html.html` also looks fine.

**Comment by nbros** [comment]
The fonts are too small in the embedded DartPad on https://flutter.dev/docs/codelabs/layout-basics for example, both in Chrome, Firefox and Edge. It looks much better on https://dartpad.dartlang.org

**Comment by leonsenft** [comment]
Just ran into this on https://dart.dev/codelabs/async-await.

Looks like there's a failed request for a font that may be related.

```
Request URL: https://fonts.googleapis.com/css?family=:300,400,400i,500,600,700,700i
Request Method: GET
Status Code: 400
```
