### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1207]
Python 2.7 will hit EoL at the beginning of next year:

https://github.com/python/devguide/pull/344

DartPad's serving setup needs to be updated to Python 3 in between now and then.

**Comment by srawlins** [comment]
dart-pad repo still has `web/main.py` and `build/main.py`??? CC @johnpryan

**Comment by johnpryan** [comment]
`web/main.py` is the important one, `build/main.py` is copied from the `web/` directory when you run the build. (along with `app.yaml` and other files)

**Comment by parlough** [comment]
This update was completed in https://github.com/dart-lang/dart-pad/commit/73a4d1440b74a44f9f9e6f193c1ee38571340b21 and Python/AppEngine usage here was removed in https://github.com/dart-lang/dart-pad/commit/7477326887f8c2149585c0bb1807ecda18964c42.
