### ISSUE TITLE
Allow users to adjust the height of embed Dartpad

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1209]
From a recent UX study, users complained that sometimes the height of an embedded is too small. Since users use various screen size, it's hard to have one exact value that fits for all users. We would like an option that enable users to resize the editor by dragging.

cc: @legalcodes

**Comment by RedBrogdon** [comment]
The size of the iframe is controlled by the page that contains me, so this would need to be a change in flutter.dev/dart.dev rather than one in DartPad. It's a good idea, though.

**Comment by kwalrath** [comment]
@RedBrogdon what's the best way to change it in the embedding page?
