### ISSUE TITLE
Check if DartPad works with Firefox on Ubuntu

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1211]
Page URL: https://dart.dev/codelabs/async-await/
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await/index.md

User feedback from the Future codelab
"The Colab code was not existing. Idk if this was on purpose, but every example code was not there. Browser: Firefox on Ubuntu."

cc: @legalcodes

**Comment by RedBrogdon** [comment]
Do we have any way of getting more information from this user, or was it just an anonymous survey response?

**Comment by galeyang** [comment]
It's from the anonymous survey response so unfortunately I don't have more information from this user.

**Comment by RedBrogdon** [comment]
Got it. I asked a GDE with Ubuntu/Firefox to verify the bug, and he wasn't able to:

https://twitter.com/abraham/status/1164286110333358083

Without more info, I'm inclined to chalk this one up as a one-off. If it pops up again, we can always reopen the issue.

**Comment by galeyang** [comment]
Sounds good to me. Thanks!
