### ISSUE TITLE
Race in dart-services when retrieving fixes/assists

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1212]
To reproduce:

1) Go to https://dartpad.dev/experimental/new_embeddings_demo.html
2) Scroll down to the Flutter Embed and put your cursor on a widget like `Padding`
3) Repeatedly hit Alt-Enter (or Option-Enter) to trigger fixes and assists.
4) Calls return two different sets of results, each about half the time.

You can open inspector and check out the network calls being made to `/fixes` and `/assists`. They go out at the same time, and exactly one always returns empty.

**Comment by RedBrogdon** [comment]
@domesticmouse Can you look into this one?

**Comment by domesticmouse** [comment]
I updated `dart-services` and now everything looks sane. I'm guessing one of the servers in rotation wasn't happy.

**Comment by johnpryan** [comment]
Shall we close this issue?

**Comment by RedBrogdon** [comment]
Do you know how the server started failing, and how we could detect something like this in the future if it occurs again?

I'm glad you were able to fix it so quickly, don't get me wrong, but I'm concerned that this could happen again when one of us wasn't actively testing the site.

**Comment by domesticmouse** [comment]
No, know idea which server was failing, or how it got there. One of the biggest problems in running clusters of servers is monitoring and management, aka log diving.

Splitting apart the server into smaller, simpler, components that can be rolled on a more regular basis would mitigate the issue to a fair degree.
