### ISSUE TITLE
Build UI for linked edit groups

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1213]
The Dart analyzer is capable of producing [LinkedEditGroups](https://pub.dev/documentation/analysis_server_lib/latest/analysis_server_lib/LinkedEditGroup-class.html) to use after implementing assists/fixes. These are post-fix edits in which devs can modify the name of a just-injected widget, new class, etc.

The data for the groups is now retrieved by dart-services and sent down to dart-pad (https://github.com/dart-lang/dart-services/pull/442). We need to update dart-pad to correctly guide users through any linked edit groups associated with a fix they apply, similar to the way IntelliJ puts a border around newly injected code:

![image](https://user-images.githubusercontent.com/969662/63285614-f8eb4180-c26a-11e9-8e79-b7b37b251b2e.png)

**Comment by parlough** [comment]
Closing this due to the [reduced scope](https://github.com/dart-lang/dart-pad/issues/2808) of DartPad's frontend. If anyone would still like to see this implemented, please open a new issue with your use case outlined. Thanks so much!!
