### ISSUE TITLE
Sunflower example to draw onInput

### ISSUE THREAD

**Issue by artu-ole** [dart-lang/dart-pad#1217]
I'm of course nitpicking, however, it got me by surprise that the featured in the readme example would only update [onChange](https://dartpad.dartlang.org/a559420eed617dab7a196b5ea0b64fba) and not [onInput](https://dartpad.dartlang.org/39b382a70ed1ea37237a9c9c8d128934)
As a best practice, handling can be throttled, though in this use case not necessary. 

Also, since screenshot in the [readme](https://github.com/dart-lang/dart-pad/blob/master/README.md) portrays both outdated domain/UI and outdated example gist, would it be a good time to update it as well?

**Comment by RedBrogdon** [comment]
We're in the process of revamping both the DartPad front page and the built-in samples, so both of these concerns will likely be addressed within the next couple of months.

I'll leave this open until that happens.
