### ISSUE TITLE
Remove primer.css/octicons

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1218]
Now that we've moved the new embed UI to MDC, we should remove any vestiges of primer and its icons still in the codebase.

**Comment by johnpryan** [comment]
We still use Octicons for the up/down triangles in the embeds, There might be a similar icon in Material, but I'm going to close this for now.

**Comment by RedBrogdon** [comment]
Discussed offline with @johnpryan. While octicons may remain in use for a while, we should still consider it a goal to replace them with MDC icons and remove that dependency.

**Comment by RedBrogdon** [comment]
🎉
