### ISSUE TITLE
Remove Polymer from the codebase entirely

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1219]
There are still a number of Polymer references in the codebase:

https://github.com/dart-lang/dart-pad/search?q=Polymer&unscoped_q=Polymer

Most are, predictably, in `lib/bower`, but there are others scattered about. Now that we're removing the old embed, these should find their way out the door as well.

**Comment by johnpryan** [comment]
The only remaining references are polymerpatch.js and 2 comments, so I think this can be closed 🎉
