### ISSUE TITLE
Show the forks for a gist

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1228]
This would allow supporting a use-case where viewers of a livestream or classroom are invited to fork a gist and the streamer / teacher can quickly show their changes to the original snippet

**Comment by RedBrogdon** [comment]
Relevant API call:

https://api.github.com/gists/868e7e9bc2a7b8c1f754/forks

**Comment by johnpryan** [comment]
another case where authenticated requests would come in handy :)

**Comment by parlough** [comment]
https://github.com/dart-lang/dart-pad/issues/2808 dropped advanced support for gists. If someone's still interested in functionality similar to this, please open a new issue with more details and the desire use case. Thanks!
