### ISSUE TITLE
My sample doesn't use dart:html but I see "Hello world!" in the output

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#123]
It's a bit weird that "Hello world!" is displayed when all my code does is print("hi"). I never touched HTML or CSS tabs.

I wonder, can we show the output of HTML only if the user intended to do some HTML coding?

**Comment by sethladd** [comment]
@devoncarew says:

* when creating a new, blank, sample, we may choose to not include the sample html snippet
* we could look at detecting when the DOM is mutated in the iframe. this is easy if the html snippet is not empty (they wrote some html code); it's harder if they programmatically mutate the DOM (document.body.children.add(new SpanElement()..text = 'foo')).

**Comment by devoncarew** [comment]
The current blank sample just uses dart now, no html, and we're tracking some UI refactoring here: #289; closing this out.
