### ISSUE TITLE
Include a border in embedded Dartpad by default

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1236]
Could we include a border in embedded Dartpad by default? As we used Dartpad embed in more places (e.g. landing page, codelab, API, etc), I repeatedly bothered PR owners on this (e.g. missing border, inconsistent color). It would be great if we can update this earlier so that we have less places to be updated. 

- Light theme:  `1px solid #cccccc`
- Dart theme: `1px solid #293542`

---
Known places to be updated if this issue is done
- [Dartpad at the bottom of dart.dev](https://dart.dev/#try-dart) and potentially flutter.dev as well
- [Cheatsheet codelab](https://dart.dev/codelabs/dart-cheatsheet)
- [Future codelab](https://dart.dev/codelabs/async-await)
- [Flutter Layout codlab](https://flutter.dev/docs/codelabs/layout-basics)
- [Embedding guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#styling-the-editor)
- API doc?

**Comment by RedBrogdon** [comment]
So far I've fought this idea on the grounds that styling the frame itself should be the responsibility of the containing page. Given that it continues to be a problem, though, I think time has proven Gale right.

If we're going to make a change, it's definitely better to do it sooner rather than later, as well.

**Comment by parlough** [comment]
After dealing with related styles for a while I've found it is best for the embedding site to control this, especially with theming  (dark, light, high contrast, more) becoming more popular by sites. Generally they only need to add the style once for their whole site.

I'm going to close this for now, but if anyone feels there are further changes still needed here, I'm happy to revisit this. Thanks!
