### ISSUE TITLE
Make hints more visually prominent, proactive, and adaptive

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1240]
From previous UX study, many participants didn’t notice the hint button because it’s not obvious or they didn’t need hints to pass the exercises in the Future codelab.

However, 7 participants would be interested in checking out hints when they get stuck. 
To make a better hint, participants suggested to make it prominent, adaptive, and more proactive.

Two specific ideas were brought up. These can be done in multiple PRs.

- Be adaptive: gives hint(s) based on a user’s current code
- Be more proactive: ask users if they need hints when they are stuck. For example, make inline hints, flash the hint button after a few failed attempts.

cc: @johnpryan as you mentioned some inline code idea a while ago

-----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise and multi-file functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
