### ISSUE TITLE
Allow users to restart from their last progress 

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1241]
In the previous UX study, when one participant just completed the code in an exercise (using an experimental/unstable prototype), the browser was frozen. He was forced to refresh the page and rewrite the code from the start.

If unfortunately a similar situation happen, we may consider allowing users restart from their last progress (like using local cache).

-----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
