### ISSUE TITLE
Show "Show solution" link in custom error message when users get stuck

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1244]
From previous UX study, all participants would like to see a solution and some prefer to see that when they get stuck or at the 2nd failing attempt.

We could provide a "Show solution" link in custom error message when users get stuck. With this link, users are less likely to miss the solution and still have an option to decide when to check the solution. 

-----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise and multi-file functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
