### ISSUE TITLE
Confusing analyzer error messages referring the test code

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1246]
From the previous UX study, we found users typed the wrong code in an exercise, however, the analyzer was complaining about the test code. Therefore, the analyzer message was confusing as it referred to the incorrect line number and the correct hidden test code. As far as we know, exercise author also had no ways to fix now this because custom error message only show up after execution.

Concrete examples:

- A test needs to get arguments `foo(a, b)` so as to verify the output value . However, users do not define it in the function `foo()` so the analyzer complains the test code `error: too many positional arguments: 0 expected, but 1 found`
- A test evaluates return strings, however, users incorrectly define the return type as void. The analyzer complains the test code `The expression here has a type of void, and therefore cannot be used - line 88`

cc: @legalcodes 

-----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by galeyang** [comment]
This might be related to "Catch errors caused by expected-but-missing functions in user's code" https://github.com/dart-lang/dart-pad/issues/1107

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
