### ISSUE TITLE
Consider highlighting the line of code mentioned in custom error message (and hints)

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1247]
Consider highlighting the line of code mentioned in custom error message (and hints)
This is one idea that participant brought up from the previous UX study. 

The ability to detect current code and give feedback may be related to the [adaptive hint issue](https://github.com/dart-lang/dart-pad/issues/1240).

-----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
