### ISSUE TITLE
Exercise's progress indicator on the left gutter

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1252]
The proposed progress indicators are visual indicators highlighting the status of exercise's test results in various places. We aim to provide clear feedback on users’ progress in completing an exercise.

This proposal is about showing test results on the left gutter. 

**Initial prototype**
![image](https://user-images.githubusercontent.com/5102864/64561073-b57e7300-d2fe-11e9-95c1-fe7e0238b5a9.png)

**Result**
Participants like this idea because of the following reasons:

- Connects to the code, have the coding context to make error messages more cohesive ; Handy, easy, simple to know the result in the code 
- Target which lines specifically pass and which have failed at granular levels 
- Know what’s wrong via colors without reading detailed text 

**Concerns and improvement**
When we implement this feature, we will need to update the design --- adding symbols to make it color-blindness friendly.

----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
