### ISSUE TITLE
Exercise's progress indicator next to the instructions

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1253]
The proposed progress indicators are visual indicators highlighting the status of exercise's test results in various places. We aim to provide clear feedback on users’ progress in completing an exercise.

This proposal is about having checkboxes on the left of each instruction title indicate the test results. 

**Initial prototype**
![image](https://user-images.githubusercontent.com/5102864/64562669-51f64480-d302-11e9-8cd8-88d8d101f1ac.png)

**Result**
Participants like this idea because of the following reasons:
- Draw learner’s attention back to “Did I follow the directions?” 
- Clear, easy to understand and straightforward
- Visual indicator 
- More visible because the UI is larger 

A few users talked about the concern of scrolling too much. That is tracked using issue https://github.com/dart-lang/dart-pad/issues/1149

One known technical challenge is the interaction between webpage and iframe.

----
Status of this issue is also tracked in https://github.com/orgs/flutter/projects/3.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
