### ISSUE TITLE
Unexpected white space under the console in the embedded Flutter view

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1266]
Followed up this issue https://github.com/dart-lang/dart-pad/issues/1187#issuecomment-516610108, in the latest version I saw an unexpected white space under the console in the embedded Flutter view.

Device: mac pro laptop with a mouse

![image](https://user-images.githubusercontent.com/5102864/64818388-cc240480-d560-11e9-92d1-dd190112a3e4.png)

cc: @johnpryan

**Comment by johnpryan** [comment]
fixed #1304
