### ISSUE TITLE
request to support themes (was: Hard to see the division between panes. Are there themes?)

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#127]
My first thought looking at this is that it's a bit intimidating to know where to type, and it's not even obvious where the division between the different panes are. It's very black on extremely dark grey. I don't love the light text on dark background either, would like to be able to change it.

**Comment by devoncarew** [comment]
Thanks for the feedback!

We're going for subtle and streamlined w/ the UI. That said, we're going to do a redux of the UI, to merge the desktop and mobile UIs w/ using a material design look. We might not be able to keep the dark-on-dark look, as I suspect that the material design shadows won't work well w/ that look.

I'd like to have theming as well, or at least have a light theme and a dark one. It's not a high priority but may be something we get to just for aesthetics. I'll specialize this issue to track that.
