### ISSUE TITLE
Build GCE instance pool backend for dart-services

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1271]
Build a managed GCE instance pool computation backend for Dart Services that wraps up compilation inside of a [gVisor'd Docker sandbox](https://gvisor.dev/).

Replaces https://github.com/dart-lang/dart-pad/issues/1128

**Comment by startupgurukul** [comment]
Hello folks, once this is resolved will https://github.com/dart-lang/dart-pad/issues/901 be automatically resolved or does that need extra effort again after this

**Comment by RedBrogdon** [comment]
There is an extra step to enable package support beyond moving off of AppEngine. We'll first create the ability to use a whitelisted set of packages that we know are trustworthy, then work to determine whether supporting arbitrary packages is feasible.

**Comment by startupgurukul** [comment]
The Google owned firebase and a network library like HTTP  are a good start covering most of the experiments/learning use cases

Hope the recent announcement of verified publishers help fasten the process( although verifying publishers not equal to verifying actual package)
 
https://medium.com/dartlang/verified-publishers

**Comment by domesticmouse** [comment]
Hey @theacodes, are you willing to look into this?

**Comment by theacodes** [comment]
Sure, but I'd likely need a session to have you walk me through how this
actually gets run and stuff. Maybe we can find some time in the next two
weeks?

**Comment by domesticmouse** [comment]
After Interact, if possible 😎

**Comment by theacodes** [comment]
sg

**Comment by startupgurukul** [comment]
Hello folks, any love for this, being able to use packages will be just a beautiful learning, experimenting experience for both Beginners/Experienced DX

**Comment by domesticmouse** [comment]
Hey @startupgurukul, I think you should be tracking #901 as that is the bug that will be closed once we have figured out the proper way to support packages.

**Comment by domesticmouse** [comment]
Closing this out as we went with Cloud Run instead.
