### ISSUE TITLE
[Flutter] Embedded template should be re-sizable window.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1272]
On a large screen, the code + app is very squished. The ratio of code/app can be shifted, but the entire window is static. 

It would be great to be able to resize this window to fill up the existing whitespace.

![G2OcfCEzQQo](https://user-images.githubusercontent.com/4229329/64973492-1cf56f00-d879-11e9-883c-66be68925cdd.png)

**Comment by RedBrogdon** [comment]
Do you mind filing this as an issue at https://github.com/flutter/website/issues? The size of the iframe is determined by the containing page, so it's not something that can be changed within the DartPad codebase.

**Comment by johnsonmh** [comment]
Done: https://github.com/flutter/website/issues/3002

**Comment by RedBrogdon** [comment]
Thanks! I'm going to go ahead and close this.
