### ISSUE TITLE
Upgrade dart-services to Flutter SDK

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1273]
Instead of 

```dart
import 'package:flutter_web/material.dart';
import 'package:flutter_web_ui/ui.dart' as ui;
```

I would like to be able to import 

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
```

And have the widgets render as expected.

**Comment by legalcodes** [comment]
Removing use of `package:flutter_web` will resolve a host of issues related to its current use in DartPad, and we can list those issues in comments here.

**Comment by legalcodes** [comment]
TextField isn't working properly in `package:flutter_web`, see, e.g.:
https://dartpad.dev/embed-flutter.html?id=ac6b3d73b86f584da1f86d1e8574b9ac 

@johnpryan

**Comment by RedBrogdon** [comment]
The move to an unforked compilation strategy for Flutter is tracked at #1282. I don't think there's anything in here (different imports, for example) that won't be covered by that issue, so I'm going to go ahead and close this one.

@legalcodes, we should chat at some point about versioning for the backend in general.
