### ISSUE TITLE
[Flutter] DartPad should store users current app if they are logged in.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1275]
Right now, in traditional dartpad, if a user is logged in, their code will be stored across sessions, so that when they open dartpad again, the code is still there. 

With Flutter, every time I navigate to https://dartpad.dartlang.org/experimental/embed-new-flutter.html?fw=true.

I get an empty page 
![Screen Shot 2019-09-16 at 12 13 45 PM](https://user-images.githubusercontent.com/4229329/64974760-7363ad00-d87b-11e9-82c8-1e0766dab82f.png)

**Comment by johnpryan** [comment]
With Flutter support being added to dart.dev, I don't think this is something we need to support in the embeds. See [this comment](https://github.com/dart-lang/dart-pad/issues/1276#issuecomment-531897599) for more details.

**Comment by johnsonmh** [comment]
Agreed, thanks!
