### ISSUE TITLE
[Flutter] New Flutter DartPad window should include boilerplate.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1276]
Right now when opening the [flutter dartpad link](https://dartpad.dartlang.org/experimental/embed-new-flutter.html?fw=false). I get an empty template. 

![Screen Shot 2019-09-16 at 12 13 45 PM](https://user-images.githubusercontent.com/4229329/64974916-d5241700-d87b-11e9-9c44-7d129ab8d072.png)

Ideally, the page would start with the boilerplate required to have a `flutter_web` app load.

![Screen Shot 2019-09-16 at 12 17 58 PM](https://user-images.githubusercontent.com/4229329/64975005-0997d300-d87c-11e9-9a40-af10dbc723db.png)

Or better yet, the starter app built by `flutter_create`.

![Screen Shot 2019-09-16 at 12 23 28 PM](https://user-images.githubusercontent.com/4229329/64975371-d30e8800-d87c-11e9-9ec5-4f3e1e6bd3e1.png)

**Comment by johnsonmh** [comment]
Note: This can currently be accomplished by linking the DartPad to a specific GitHub Gist.

For example, the gist 

https://gist.github.com/johnsonmh/25107ed39b794e5f3ac645e01a1fa5ea

Can be loaded in to dartpad with:

https://dartpad.dev/embed-flutter.html?id=25107ed39b794e5f3ac645e01a1fa5ea

Things we could do to make this workflow easier:
 1. More discoverability from the dartpad UI. Maybe a "Share", or "Import Gist" button.
 1. When dartpad is loaded _without_ a gist, we should consider loading some bare-bones gist or boilerplate.

**Comment by johnpryan** [comment]
Thanks for filing an issue! This is definitely something we intend to support, but not in the embeds, since they are intended to be used in the context of an article or codelab.

The good news is that there is a new version of `dartpad.dev` with Flutter support, which you can try [here](https://dartpad.dev/new_playground.html). The samples are still only Dart right now, so I would like to re-purpose this issue for supporting Flutter samples there. Let us know what you think!

**Comment by johnsonmh** [comment]
@johnpryan I think that sounds like a good idea! Is there a component where I can file dartpad-flutter bugs too? I filed most of them to this component and I think most of them are not specific to the embedder.

**Comment by johnpryan** [comment]
Go ahead and file them here -  we're using this issue tracker anything DartPad related.

**Comment by johnsonmh** [comment]
Oh I see, this tracker is for all DartPad things, but this particular issue only applies to the embedder, I agree with you, we should not save user input in the embedder. I'll close this issue!

**Comment by ThinkDigitalSoftware** [comment]
> Thanks for filing an issue! This is definitely something we intend to support, but not in the embeds, since they are intended to be used in the context of an article or codelab.
> 
> The good news is that there is a new version of `dartpad.dev` with Flutter support, which you can try [here](https://dartpad.dev/new_playground.html). The samples are still only Dart right now, so I would like to re-purpose this issue for supporting Flutter samples there. Let us know what you think!

Link is now broken. Working link is https://dartpad.dev/flutter, which doesn't work when navigated to directly... I get a 404... It works when navigating from https://dartpad.dev/ and then hitting new pad > Flutter. @johnpryan

**Comment by johnpryan** [comment]
@ThinkDigitalSoftware that sounds like a different issue, so I've created a new issue for that here: https://github.com/dart-lang/dart-pad/issues/1497
