### ISSUE TITLE
[Flutter] Add keyboard shortcuts for "Run" and "Format".

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1277]
These two actions are done a lot when writing Flutter code. It would be nice to have shortcuts for these two things.

On MacOS, I'm instinctively expecting "Command + S" and "Command + Shift + F" respectively, although that might just be my personal instincts.

**Comment by RedBrogdon** [comment]
There are two issues here:

* We don't expose the list of keyboard shortcuts on the embeds as they are on the front page. There actually *is* a shortcut for run: Cmd-Enter.
* We don't have a shortcut for format, which just seems bonkers.

**Comment by galeyang** [comment]
It's related to https://github.com/dart-lang/dart-pad/issues/1134
