### ISSUE TITLE
[Flutter] Add convenient way to view/link to flutter documentation.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1279]
The auto complete is *awesome*, but it's difficult to know what Type a parameter is expecting.

### Current behavior in Flutter DartPad
![giphy-1](https://user-images.githubusercontent.com/4229329/64981642-7e720980-d88a-11e9-82d8-b8e037efd214.gif)

### Android Studio

In Android Studio, we can click through to the param to view the docs/type.

![giphy](https://user-images.githubusercontent.com/4229329/64981694-977aba80-d88a-11e9-8340-6601bd1d04e3.gif)

### Traditional DartPad

Traditional DartPad loads the DartDocs when your cursor is on a specific type. Doing something like this might work really well too.

![XVQu2KFXKb8](https://user-images.githubusercontent.com/4229329/64981846-e9bbdb80-d88a-11e9-9ded-277babd48787.png)

**Comment by RedBrogdon** [comment]
Fair point.

We don't always have room for a documentation pane, so in the embeds we'd need to support a hovering element of some kind.

**Comment by johnsonmh** [comment]
It's worth noting that the non-embedded version _does_ have a documentation window. 

![A5d9bFt5knA-1](https://user-images.githubusercontent.com/4229329/64998006-77f68880-d8b0-11e9-84cc-eb05acaa5642.png)

For the embedded version, it is lower priority. A couple options that might help though:

 1. Include the type in the auto complete suggestion list.
 1. Include some kind of tooltip/hover element with doc info.
 1. Make it "click through" where if you <control>-click on a class, it will open up the api.flutter.dev page.

**Comment by parlough** [comment]
Thanks for the discussion here! The latest DartPad UI does surface the API docs in the playground and embed layouts, but there are some UX issues.

I'll close this issue in favor of continuing that discussion in https://github.com/dart-lang/dart-pad/issues/2999 about the best way to surface API docs in the current DartPad UI.
