### ISSUE TITLE
Be able to import packages, at least a basic set

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#128]
It would be useful to be able to import packages. Even if it were a known hard-coded set of common packages that would be helpful. That's all try.dartlang.org has.

**Comment by lukechurch** [comment]
Thanks @alan-knight for the suggestion, this is definitely a direction we're interested in going in. We've done some initial experiments, but there's a bit more work to go.

**Comment by devoncarew** [comment]
Closing this is favor of the existing https://github.com/dart-lang/dart-services/issues/43; but yes, definitely something we'd like to se..

**Comment by RajatKD** [comment]
I tried to implement this 'package:intl/intl.dart';' package but I'm not able to do that! It will be more helpful if you help with this.
