### ISSUE TITLE
_discoveryapis_commons v0.1.9 breaks us

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1284]
At the moment, we're intentionally using a down-versioned _discoveryapis_commons package. The current latest, 0.1.9, breaks the communication between dart-pad and dart-services by causing dart-services to return its responses without CORS headers.

The changes in between 0.1.8 and 0.1.9 were fairly minimal, and none of _discoveryapis_commons dependencies appear to have been changed, so it should be possible to track this down ourselves.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/dart-pad/commit/dec98cbb2e84a931b46d403ba54acbe8c204080a

**Comment by RedBrogdon** [comment]
Thanks, @parlough. This should have been closed out a while ago.
