### ISSUE TITLE
Any input throws:  Error compiling to JavaScript: XMLHttpRequest error.

### ISSUE THREAD

**Issue by chucksteneck** [dart-lang/dart-pad#1285]
New to dart pad, however even the most basic code throws "
Error compiling to JavaScript:
XMLHttpRequest error."
https://dartpad.dartlang.org/
(just trying default print for example)
Is the site not working properly at the moment, or am I missing something?
Thanks,
Chuck.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue!

I'm not having trouble compiling things right now, but that doesn't mean there's not something weird going on. Can you provide a little more info about the browser and operating system you're using?

Also, do you see anything weird in your browser's JavaScript console or network traffic log?

**Comment by chucksteneck** [comment]
Hi Andrew,

Here's what I'm seeing-
[image: image.png]

Just trying to run:
void main() {
  var = myName('John');
  print(myName);
}

And receiving this:
Error compiling to JavaScript: XMLHttpRequest error.

Using: Chrome  Version 77.0.3865.90 (Official Build) (64-bit)

Also nothing strange on the network call
[image: image.png]

I am at work and behind a firewall [Forcepoint], perhaps that's the reason?

Thank you,
Chuck.

**Comment by chucksteneck** [comment]
Hi Andrew,

Tried it on my phone and works fine, sorry to both you, must be Forcepoint
blocking : (

Thanks,
Chuck.

**Comment by domesticmouse** [comment]
Looks like your image attachments didn't attach. It'd be interesting to understand how your firewall is blocking the content, so we might be able to sniff that at run time and at least fail gracefully.

**Comment by RedBrogdon** [comment]
Likewise. If you have time to save the network traffic generated by loading the site and trying to run something ([ZenDesk has a handy guide](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)), we'd definitely be interested in seeing it.

I'll go ahead and close this one out, though.

**Comment by bentobenack** [comment]
I solve this using a VPN.

**Comment by amiver** [comment]
This @RedBrogdon know nothing.. fire him from flutter team

**Comment by RajatDabral** [comment]
Just turn off your Windows Defender or configure your firewall. That worked for me.
