### ISSUE TITLE
Remove experimental/ directory

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1287]
Once the new playground is finished, the `web/experimental/` and `lib/experimental/` directory can be removed. 

We should double check that dart.dev and flutter.dev reference the newest embeds (`web/embed-flutter.html` and not `web/experimental/*`)

**Comment by RedBrogdon** [comment]
This will be a glorious day for DartPad. 😄

**Comment by johnpryan** [comment]
This is fixed now 🎉
