### ISSUE TITLE
Update embedding guide

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1288]
Now that the new embeds have been released, the embedding guide is slightly out of date: https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide

**Comment by galeyang** [comment]
Related to https://github.com/dart-lang/dart-pad/issues/1227

**Comment by RedBrogdon** [comment]
I can take this one. It should mostly be a deletion of the old stuff.

**Comment by ThinkDigitalSoftware** [comment]
This section links to a 404 page. https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#example

**Comment by johnpryan** [comment]
@ThinkDigitalSoftware good catch, that's fixed now.

I'm going to close this for now, there's nothing else to fix right now AFAICT.
