### ISSUE TITLE
importing external packages like http

### ISSUE THREAD

**Issue by startupgurukul** [dart-lang/dart-pad#1289]
Hello folks, 
So excited to see flutter support.
One more request, can you support adding external packages like http?

I tried this , import 'package:http/http.dart' as http;

but hit an error, 
Unsupported input: package:http/http.dart 

Looking forward to your thoughts if it can be supported. Thanks.

**Comment by willdrach-wk** [comment]
Issue #901 is what you're looking for, I believe

**Comment by startupgurukul** [comment]
Yes, thank you for pointing out. I feel bad for not doing do my due diligence before creating the issue. Closing this
