### ISSUE TITLE
DartPad Not working in microsoft edge

### ISSUE THREAD

**Issue by harshag24** [dart-lang/dart-pad#1296]
It doesn't display the preview and just shoes no issue.

**Comment by domesticmouse** [comment]
Anything interesting in the console? Which version of Edge? What OS revision?

**Comment by harshag24** [comment]
Nothing special in the console , the same code which was written by default.
Version - 44.18362.329.0
Windows 10 ver 1903

**Comment by RedBrogdon** [comment]
Thanks for letting us know!

There are some known issues with using DartPad on the current stable build of Edge. It works very well, though, with the new Chromium-based version that's currently [in preview](https://blogs.windows.com/windowsexperience/2019/08/20/introducing-microsoft-edge-beta-be-one-of-the-first-to-try-it-now/), and we anticipate that continuing once the Chromium builds make it to stable.

I don't know MS's build numbers well enough to determine which version you're using. If you aren't using the beta release though, give it a try and let us know if that fixes the issue.

**Comment by LNFWebsite** [comment]
DartPad still isn't working on Edge Version 98.0.1108.43 (Official build) (64-bit)

**Comment by domesticmouse** [comment]
I've just confirmed that DartPad's Dart and Flutter hello world equivalents work on Edge running on macOS.

<img width="863" alt="Screen Shot 2022-02-10 at 10 16 11 pm" src="https://user-images.githubusercontent.com/30503/153407117-64748369-c5c9-4fe9-b9e6-1e1097dc1cc9.png">

Can you please open a new issue with reproduction details, including operating system version and sample code that is failing? Console logs may also be helpful.
