### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1297]
We should investigate how accessible the new playground is. ([comment](https://github.com/dart-lang/dart-pad/pull/1291#discussion_r329673446)). Tools like [Lighthouse](https://developers.google.com/web/tools/lighthouse) can help identify issues.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/2488 which has some more concrete details to reference. Thanks!
