### ISSUE TITLE
Add ability to fold errors and warnings down

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#130]
When working on a longer file it would be useful to be able to fold the errors and warnings down, so that they only take up one line summarising the state.

This could then be unfolded back up again to see all of the content.

Possibly consider adding a ^ glyph to the RHS of the top error and warning as the trigger for doing this.

**Comment by devoncarew** [comment]
we've changed where they're displayed; should help mitigate this issue
