### ISSUE TITLE
Sunflower sample has dark text

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1311]
It looks like there may have been a regression where the Sunflower sample HTML is not styled to be displayed on a dark background

<img width="661" alt="Screen Shot 2019-10-04 at 8 37 51 AM" src="https://user-images.githubusercontent.com/1145719/66220678-4b00ee80-e682-11e9-8ca4-d3d355363a36.png">

**Comment by paulo9mv** [comment]
Is this open? I didn't understood the exactly problem, but I would like to help here

**Comment by johnpryan** [comment]
Pull requests are welcome! The CSS in web/scripts/frame.html or in the Sunflower sample need to make the text white on the dark background.

**Comment by patkellydesigns** [comment]
I hear the sunflower needs a little pizazz. I'll do it now.

**Comment by johnpryan** [comment]
fixed in https://github.com/dart-lang/dart-pad/pull/1337 and e00da6952cb4d1284ad438a3467264b1e64d7290
