### ISSUE TITLE
Increase horizontal space for API Doc snippets

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1312]
The embedded DartPad on [this API doc page](https://master-api.flutter.dev/flutter/material/TextField/onChanged.html) has only enough horizontal space for 44 character columns. This can make the sample slightly difficult to read. 

For example, the indentation for the Text widgets starts at 20:

<img width="705" alt="Screen Shot 2019-10-04 at 1 51 26 PM" src="https://user-images.githubusercontent.com/1145719/66239213-228ee980-e6ae-11e9-8efb-3b5deba3f452.png">

**Comment by RedBrogdon** [comment]
We've got a bug going on the website repo for this:

https://github.com/flutter/website/issues/3002

**Comment by johnpryan** [comment]
Didn't realize that, closing.
