### ISSUE TITLE
The font size hurts my eyes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#132]
I have to zoom to 67% to get reasonable font size.
Of course just my opinion, but also not less ;-)

**Comment by lukechurch** [comment]
@zoechi Thanks for the observation. It's interesting, I've taken to using Dart Pad at 67% zoom as well.

We wanted it to be a bit more approachable for small programs, but it does feel like perhaps we've gone a bit too far with the font size.

**Comment by kasperpeulen** [comment]
For some reason, I actually love the big fonts of dart pad. I guess it is just aesthetics. Or maybe my bad eyes.

**Comment by zoechi** [comment]
Probably your bad eyes :p 
When hello world hardly fits on the screen I can't see how this can be used for anything serious.

I could have added some more details
- Notebook screen FullHD
- Chrome desktop browser

**Comment by devoncarew** [comment]
We're using 16px for both desktop and mobile. It seems like a good size on mobile; it might be a tad big on the desktop. It definitely depends on the user; lower eyesight users have complained about smaller sizes :)

I'm not sure if there's a perfect size for most users, if we should have a font size preference or toggle, or just rely on the browser's built-in page scaling feature.

**Comment by kasperpeulen** [comment]
I'm not sure if this is screen or os specific, for example, sometimes my retina screens make things smaller. I don't feel I have to little room @zoechi:

![image](https://cloud.githubusercontent.com/assets/1035299/6642720/2d1a1a9c-c9a7-11e4-87fe-b3fa175a7ef1.png)

**Comment by devoncarew** [comment]
I _think_ macos renders fonts smaller than windows; I'm on macos as well.

**Comment by zoechi** [comment]
I'm on Linux and the text is almost twice as big as my in my IDE.
![image](https://cloud.githubusercontent.com/assets/405837/6643098/07a1dc2a-c9aa-11e4-9be8-119cb45f8403.png)

**Comment by zoechi** [comment]
I just checked again and the font size is quite nice now for me too :-)
