### ISSUE TITLE
New playground: formatting code loses scroll position

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1327]
#1039 is open for this issue on the new embed, but it also appears in the new playground (and, to be fair, the old one).

To reproduce, just add more code than fits in the vertical space of the editor. Add some whitespace somewhere, and then use the format button. The editor will scroll immediately to the top of the window.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/dart-pad/pull/2885 🥳
