### ISSUE TITLE
New playground: clicking on top-left logo should lead to https://dartpad.dev/

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1329]
The logo in the top-left corner of the new playground doesn't serve as a link. Personally, I'm a big fan of the "logo in the top left leads to the home page for the site" paradigm, so my vote would be to make it a link to https://dartpad.dev.

FWIW, the old playground does *not* have this behavior, and instead pops up an About dialog. If the decision is to have the new logo point to the home page, we should work in a UI element that pops up something similar (possibly just by adding a link to the SDK version number in the lower right corner).

**Comment by parlough** [comment]
With how the application currently is, at least in the standalone view, I don't see much of a use of it bringing them back to where they already are. I found this issue though by thinking perhaps at least the Dart logo, but not the DartPad text, should lead to https://dart.dev. What do you think about that?

As for the embedded views, some way to access the standalone website may be interesting. As space is limited, perhaps this would be best delegated to the bottom of the expanded menu in the upper right.

**Comment by RedBrogdon** [comment]
I'm actually going to close this. I think I'm the only person using DartPad who even noticed, let alone cared. 😄 

FWIW, redirecting from the embedded layouts to a full DartPad is tricky. You can definitely direct folks to dartpad.dev with a blank editor, but you can't necessarily redirect them there with the same code in place in the editor. The embedded layouts have the ability to include tests that are hidden but meant to be run with their code (silently appended, essentially). The fullscreen UI doesn't have that capability.
