### ISSUE TITLE
Some types are colored yellow some orange

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#133]
![image](https://cloud.githubusercontent.com/assets/1035299/6641678/9e3a6388-c99f-11e4-81cb-298d9f7367cd.png)

I would say that `String` and `List` should have the same color.

I see that codelab and chrome dev editor do those colors in a similar way, I was wondering where this highlighting is defined.

**Comment by lukechurch** [comment]
String is in the same category as 'int' and 'bool'

I think the colouring comes from the code mirror scheme. @devoncarew will know exactly where it's defined.

**Comment by kasperpeulen** [comment]
I think I found it:

![image](https://cloud.githubusercontent.com/assets/1035299/6642013/e040cfcc-c9a1-11e4-8748-e36f1f3e0779.png)

**Comment by kasperpeulen** [comment]
Would it be an idea to add the other classes of [dart:core](https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart:core) to this list ? 

```
BidirectionalIterator Comparable DateTime Duration Function Invocation Iterable Iterator List Map Match Null Object Pattern RegExp RuneIterator Runes Set Sink StackTrace Stopwatch String StringBuffer StringSink Symbol Type Uri bool double int num
```

**Comment by devoncarew** [comment]
We just do syntax highlighting, not semantic. So, we don't know what tokens are types; semantic highlighting, which depends on resolving the tokens into their actual type references, would have this info.

Syntax highlighting is available in many more contexts, and from my perspective solves the 95% use case.

Those builtin types (`int double String ...`) we know are types, so we can highlight them. I'm not sure if it makes sense to highlight all the dart:core types, or just the most frequent ones. The current list of highlighted types roughly corresponds to the list of primitive types from other languages. @lukechurch, thoughts?

**Comment by sethladd** [comment]
GitHub uses the same syntax highlighting script that Sublime uses. I wonder if we can converge on this file?

https://github.com/guillermooo/dart-sublime-bundle/blob/master/Dart.tmLanguage

**Comment by kasperpeulen** [comment]
This file uses the following "types" it seems: `void|bool|num|int|double|dynamic|var|String|List|Map`.

**Comment by devoncarew** [comment]
+1 to having codemirror, ace, and sublime all converge to highlighting the same types :)

**Comment by kasperpeulen** [comment]
Ah I see now that webstorm also doesn't highlight most class names. Actually webstorm highlights less, only the lowercases types it seems: `bool, num, int, double, void, dynamic,var`.

I think I got consufed by having `String` be highlighted, but `List` and `Map` not, for some reason my brain things those are in the same category.

**Comment by kasperpeulen** [comment]
> +1 to having codemirror, ace, and sublime all converge to highlighting the same types :)

Just looking how dartlang and stackoverflow do it, but they do highlight all types in the same way. I guess they just have a list for the lowercase types, and then mark any capitalized word as a type.

**Comment by kasperpeulen** [comment]
Dartlang uses this regex for types it seems:
```javascript
["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,q]
```
together with:

```javascript
// Keywords for types.
[PR['PR_TYPE'], /^\b(?:bool|double|Dynamic|int|num|Object|String|void)\b/i]
```

**Comment by lexaknyazev** [comment]
@sethladd Looks like WebStorm uses AS for highlighting now ([WEB-18698](https://youtrack.jetbrains.com/issue/WEB-18698)) with no such thing as "builtin types". Is it new convergence point for editors now?
