### ISSUE TITLE
New playground: dead space for editor tabs when in Flutter & Dart-only layout

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1330]
![image](https://user-images.githubusercontent.com/969662/67044715-bbc3f400-f0e1-11e9-9fcc-45c39fb7eea6.png)

When in Dart+HTML mode, the new playground has tabs for the individual files, taking up space across the top of the editor container. When in Dart-only or Flutter mode, the tabs disappear, but the space they formerly took up remains, which creates some wasted visual space at the top of the editor.

This could be fixed either by adding back a singe "Dart" tab, which is what the current playground does, or by reworking the HTML/CSS to collapse that space when no tabs are present.

**Comment by RedBrogdon** [comment]
@johnpryan This has been fixed in the latest round of polish, hasn't it?

**Comment by johnpryan** [comment]
yeah this is fixed now, 👍
