### ISSUE TITLE
New embed: dismissing solution modal sometimes leaves solution tab lit

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1333]
Steps to reproduce:

1) Go to https://dartpad.dev/embed-dart.html?id=43f3db47b0632c557200270807696687
2) Click the solution tab
3) See that the "Show solution?" modal pops up.
4) Rather than clicking cancel, click outside the dialog instead.
5) Note that the dialog disappears, the Dart editor stays in view, but the Dart tab does not light up. The tab controller still has "Solution" as the indicated tab.

Clicking cancel causes the correct behavior, so this looks like an unhandled dismiss event from the dialog.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality solutions were related to was removed.

If anyone would like to see similar functionality brought back, please consider opening a new issue. Thanks so much!
