### ISSUE TITLE
Unsupported input: package:encrypt/encrypt.dart

### ISSUE THREAD

**Issue by pundoo** [dart-lang/dart-pad#1334]
Just getting hands on with dart and as a starter I tried to run the following sample code on dart-pad : 

```
import 'package:encrypt/encrypt.dart';

void main() {
  final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
  final key = Key.fromUtf8('my 32 length key................');
  final iv = IV.fromLength(16);

  final encrypter = Encrypter(AES(key));

  final encrypted = encrypter.encrypt(plainText, iv: iv);
  final decrypted = encrypter.decrypt(encrypted, iv: iv);

  print(decrypted); // Lorem ipsum dolor sit amet, consectetur adipiscing elit
  print(encrypted.base64); // R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw==
}
```
but got the error : `Unsupported input: package:encrypt/encrypt.dart`

What's wrong? Am I missing something? Or is `import` not supported on dart-pad?

**Comment by RedBrogdon** [comment]
You're not missing anything. DartPad does not currently importing packages from pub, which is why you're seeing that error.

It's a long standing feature request (#901) which we hope to address soon, but it's not something we can support at the moment.
