### ISSUE TITLE
New Embed: unchecking "show tests" doesn't hide test editor.

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1335]
Steps to reproduce:

1) Load http://localhost:8000/embed-dart.html?split=60&gh_owner=RedBrogdon&gh_repo=dartpad_exercises&gh_path=dart_codelab/01_dart_exercise
2) Use the menu to check "Show tests"
3) Click on the Test tab, making the test editor visible.
4) Open the menu again and uncheck "Show tests"
5) The Test tab disappears, but the test editor is still visible.

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality tests were related to was removed.

If anyone would like to see similar functionality brought back, please consider opening a new issue. Thanks so much!
