### ISSUE TITLE
too much orange, too little color variation

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#134]
I think my main issue at #133 actually is, that dartpad sometimes seems to have a little bit too much orange:

webstorm:
![image](https://cloud.githubusercontent.com/assets/1035299/6644279/e3c997bc-c9b2-11e4-8013-d38a1f952a9f.png)

vs dartpad:
![image](https://cloud.githubusercontent.com/assets/1035299/6644260/bc3f0d94-c9b2-11e4-8abc-919893158bb8.png)

So making all the types look the same is my mind some consistent way of doing it, but as this probably is not practical, an other way to fix the orange overload would be to make variable names or function names another color.

Another example:

webstorm:
![image](https://cloud.githubusercontent.com/assets/1035299/6644363/73c04622-c9b3-11e4-893c-778016a0efe7.png)

vs dartpad:
![image](https://cloud.githubusercontent.com/assets/1035299/6644355/6948eba4-c9b3-11e4-856a-59d38a9f539c.png)

I do think that making all types having the same color and boldness would look nice and feel consistent. But this is probably not practical. Another option would be to make variable names and/or function names look different, to give the eyes some color variation and to help the eyes differentiate different parts of the code.

**Comment by devoncarew** [comment]
We're using the Dart mode for codemirror - demo available here: http://codemirror.net/mode/dart/index.html

Any tweaks to that would make their way downstream to dartpad. It would be nice to have some unification between the dart modes for ace and codemirror (and sublime?).

**Comment by devoncarew** [comment]
But thinking about this, it may be less an issue with the dart mode for codemirror, and more an issue with the particular codemirror theme we've chosen to use (http://codemirror.net/demo/theme.html - zenburn).

**Comment by kasperpeulen** [comment]
I think it is an combination. I've tried to adjust the groovy mode of codemirror, so that it works for dart. It looks like this:

![image](https://cloud.githubusercontent.com/assets/1035299/6649213/eef29d68-c9e5-11e4-8728-b1b1924b4e54.png)

![image](https://cloud.githubusercontent.com/assets/1035299/6649241/4320207c-c9e6-11e4-974c-accf2e58c7b5.png)

I've written it a bit as a hack, but if you like, I could try to clean it up and write a pull request for code mirror and dart-pad:
http://kasperpeulen.github.io/dart-pad/

**Comment by devoncarew** [comment]
![screen shot 2015-03-13 at 10 06 13 pm](https://cloud.githubusercontent.com/assets/1269969/6650408/4915932c-c9cd-11e4-94e1-32ff0ed99782.png)

![screen shot 2015-03-13 at 10 06 44 pm](https://cloud.githubusercontent.com/assets/1269969/6650407/49147b18-c9cd-11e4-8161-ba1b6322d8c0.png)

I like the color for the types better. It looks like some other aspects changed a bit as well (font family?), in your hosted copy of dartpad.

In any case, a tweak to zenburn to show types differently from properties would be great. I'm not sure how open he'll be to changing the theme, but if you can get that accepted to codemirror proper, the next major release would be picked up in the dart wrapper (codemirror.dart), and dartpad would get that pretty soon after.

**Comment by kasperpeulen** [comment]
I was playing around a bit with Inconsolata and Source Code Pro as fonts and different font sizes. According to [Robert Nystrom](http://blog.fogcreek.com/dev-life-interview-with-robert-nystrom/) that are the 2 coding fonts to use :)

Code mirror does have a `property` styling, but by default sunburn styles properties the same as variables. I don't think zenburn would accept different stylings easily indeed, but dart pad could override some stylings maybe ? This is what I use:

```
      .cm-s-zenburn span.cm-builtin {font-weight:500 !important; }
      .cm-s-zenburn span.cm-property {color: #f0dfaf !important;}
      .cm-s-zenburn span.cm-doc {color: #7f9f7f !important; font-weight:500 !important;}
      .cm-s-zenburn span.cm-comment {color:darkgrey !important; }
      .cm-s-zenburn span.cm-number {color: #8eced2 !important;}
      .cm-s-zenburn span.cm-dart-arrow {font-weight:600 !important; letter-spacing: -0.2em !important; padding-right:0.2em !important;}

      .CodeMirror pre {
        font-family:  "Source Code Pro" !important;
        font-size: 14px !important;
}
```

Things like the dart-arrow styling is not really needed, but I thought it look cool :)

But I'll try to create some proper code that code mirror can use, the code I use now is 95% copy pasted from groovy, and I don't really understand what it does, so need to figure that out first.

**Comment by devoncarew** [comment]
Yup, we landed on `Inconsolata` as the one true mono-spaced font, largely on the G+ recommendation of Joel Webber :)

If it's just an issue with zenburn, we can do local overrides, no problem. Here's the best file for that: https://github.com/dart-lang/dart-pad/blob/master/lib/editing/editor_codemirror.css.

But generally, if there's an issue with the Dart styling across many themes, I'd like to upstream a fix for that to codemirror, so that all the properties using codemirror get the fix.

**Comment by kasperpeulen** [comment]
Ok, clear. 

Btw, it seems like dart pad is not using `Inconsolata`, but `Courier`:
![image](https://cloud.githubusercontent.com/assets/1035299/6653300/bec678a6-ca8c-11e4-89a5-8623105fc2f9.png)

**Comment by sethladd** [comment]
+1 for Inconsolata! :)

**Comment by devoncarew** [comment]
Ah, @kasperpeulen, totally right. I think a refactoring caused the css selector specifying Inconsolata in the editing area to stop matching. We'll have it for the next iteration (https://github.com/dart-lang/dart-pad/pull/135).
