### ISSUE TITLE
Migrate from DDC to DDK 

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1341]
Per https://github.com/dart-lang/sdk/issues/38994, we need to remove usage of Analyzer based DDC before upgrading to Dart SDK 2.7.0.

@RedBrogdon if you get a chance, can you do some initial investigation?

**Comment by nshahan** [comment]
Hopefully making this change should be fairly easy. I'm happy to advise so please feel free to reach out with any questions.

The biggest gotcha I can think of is using the wrong version of the SDK after it has been compiled to JS. The version compiled with DDC is not fully compatible with applications compiled with DDK but it works well enough that you might not notice for a while.

**Comment by domesticmouse** [comment]
Thanks for the heads up. I’ll make sure to name the compiled artifacts we serve from GCS have disambiguated names 😁

**Comment by vsmenon** [comment]
@domesticmouse @RedBrogdon - are you comfortable with us removing the old non-kernel version of DDC at this point?  (It's in 2.6.*.)

**Comment by domesticmouse** [comment]
Hey @vsmenon, we believe we are good once we land the unforked flutter web back end. However, just to be sure I would really appreciate a `google/dart:dev` docker image with these changes included so we can test the full functionality of the `dart-services` backend to prevent the fire drill of fixing a broken DartPad during the Dart 2.7 release.

**Comment by nshahan** [comment]
We are trying to find out when it will be safe for us to delete the analyzer version of DDC from the Dart SDK. Just to tease out some of the details here, do you know what the timeframe is for that docker image with the changes to be available?

**Comment by domesticmouse** [comment]
Hey @athomas, I think we need your expertise here. Thanks!

**Comment by RedBrogdon** [comment]
In case anyone's interested, you can see the exact calls we're making to dartdevc in this PR:

https://github.com/dart-lang/dart-services/pull/467

**Comment by RedBrogdon** [comment]
@domesticmouse Any reason this needs to stay open? We're using `-k` on all calls to dartdevc at this point, so I think we're all set.
