### ISSUE TITLE
Disable line wrapping

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1342]
DartPad currently uses line wrapping, but this causes some weird behavior for samples with long lines. For example, an upcoming codelab uses this line:

```
const owl_url =
    'https://raw.githubusercontent.com/flutter/website/master/src/images/owl.jpg';
```

This line of code restricts the size of the Flutter app.

**Comment by johnpryan** [comment]
The second sample at https://dart.dev/tutorials/web/low-level-html/add-elements also demonstrates this issue

**Comment by RedBrogdon** [comment]
@johnpryan Should #1438 be considered a duplicate of this issue?

**Comment by johnpryan** [comment]
Yeah, marked that issue as a dupe. Pasting the gist from that issue for reference: https://dartpad.dartlang.org/cbb4deb6b52b3cb7689d2fb974cf9c58

**Comment by theacodes** [comment]
It's also visible here: https://flutter.dev/docs/codelabs/layout-basics_migrated#image-widget

**Comment by theacodes** [comment]
We should probably put a `min-width` property on the output container as well.

**Comment by marcellodesales** [comment]
Any workarounds here?

**Comment by johnpryan** [comment]
@marcellodesales see https://github.com/dart-lang/dart-pad/pull/1921

**Comment by marcellodesales** [comment]
I came up with a groovy string to generate a variable with the long string value :) 

https://groovyconsole.appspot.com/script/5151226664583168
