### ISSUE TITLE
Show autocompletion as the user types

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1343]
Instead of using the `ctrl+space` shortcut to trigger autocomplete, we should consider showing the completions as the user types in a code block.

**Comment by parlough** [comment]
This is still an issue with the current DartPad frontend alongside some other UX and DX concerns. Closing this issue in favor of addressing them together in https://github.com/dart-lang/dart-pad/issues/3010. Thanks for the discussion here!
