### ISSUE TITLE
New playground: Add load-from-repo functionality

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1346]
The GistLoader used by the new embed to load from a GitHub repo can also be used by the new playground, but isn't yet wired up.

**Comment by pennzht** [comment]
Seconded. This will be a valuable feature.

**Comment by parlough** [comment]
As part of DartPad's [newer, simplified](https://github.com/dart-lang/dart-pad/issues/2808) UI and focused scope, loading from a repo (not gist) is no longer supported. If anyone would like to see this mechanism brought back, please consider opening a new issue with details about your use case. Thanks so much!
