### ISSUE TITLE
New playground: Add load-from-Api-Docs functionality

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1347]
The GistLoader used by the new embed to load from API docs can also be used by the new playground, but isn't yet wired up.

**Comment by pennzht** [comment]
Seconded. This will be a valuable feature.

**Comment by parlough** [comment]
The newest UI shared an implementation for the embed and playground views, and as a result, loading a API docs sample through the `sample_id` query parameter is now supported in both modes.
