### ISSUE TITLE
Test code doesn't work in the playground

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1348]
Snippets with test code only work in the embeds. See [this comment](https://github.com/dart-lang/dart-pad/pull/1344#discussion_r339147193) for more details.

> I'm not sure of the best way to handle this. Some options:
> - Leave it as-is. Folks can just learn that the snippets in exercises with tests will need additional work in order to run.
> - Leave as-is, but add a popup after the user clicks the Open in DartPad button warning them that the test code won't be going with them.
> - Update the playground to concatenate the test code onto main.dart and present the result (possibly throwing in a comment above the test code to explain what's going on).

**Comment by RedBrogdon** [comment]
@johnpryan Did you mean "only work in the embeds" above?

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality tests were related to was removed.

If anyone would like to see similar functionality brought back, please consider opening a new issue. Thanks so much!
