### ISSUE TITLE
"Link to DartPad" feature in embeds should go to playground when appropriate

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1353]
In #913, it was decided that the embedded UI's "open in DartPad" feature should open the same embedded layout in a new window.

This works well for test exercises and codelab demos, but isn't ideal in all cases. For example, once the new saving/sharing UI has been added, someone might use the embed in a blog post and invite readers to create their own modified version. In this case, it'd be better to open the code in the playground (it's unlikely the embedded layout will ever have an option to save to a gist). 

The embedded layout could examine the code it's loaded to see if there's a test, and decide whether to open a new window containing the playground or the same, embedded layout.

**Comment by parlough** [comment]
DartPad no longer has this feature in its current UI, so I'm going to close this as obsolete. If anyone would like to see similar functionality brought back, please open a new issue with information about your use case. Thanks so much!
