### ISSUE TITLE
Smething's wrong with either console or server

### ISSUE THREAD

**Issue by Adolf1970** [dart-lang/dart-pad#1355]
Trying to execute print instruction causes the following error:
Error compiling to JavaScript:
XMLHttpRequest error.

**Comment by Adolf1970** [comment]
> Cycling the servers. New ones will pop up shortly. Please try again in a couple of minutes.

5 mins are over... still the same issue...

**Comment by RedBrogdon** [comment]
I'm not able to replicate this issue at the moment. If you're still seeing it, do you mind passing along some more info? In particular, I'd be interested to know:

* What browser/version are you using?
* What OS are you using?
* On which page did you see the error occur?
