### ISSUE TITLE
Filter 'Script error' messages resulting from flutter_web in DartPad console

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/dart-pad#1357]
To reproduce:
1. Open any DartPad embed, e.g. the first example on https://flutter.dev/docs/codelabs/layout-basics
2. Click the **Run** button
3. Watch for errors in the **Console**. If you don't see any, click **Run** again. 

![Screen Shot 2019-10-31 at 9 22 42 AM](https://user-images.githubusercontent.com/5550175/67965977-44519280-fbc0-11e9-9131-81d7d62c231e.png)

These appear to be intermittently thrown by flutter_web:

![Screen Shot 2019-10-31 at 9 27 24 AM](https://user-images.githubusercontent.com/5550175/67966209-b32eeb80-fbc0-11e9-86fb-d67e6bf97d1d.png)

**Comment by RedBrogdon** [comment]
@johnpryan Should this be closed in favor of #1365?

**Comment by johnpryan** [comment]
Yeah I don't think the `PointerDataPacket` errors are showing up now that we are using the Flutter SDK.  #1365 should cover the error handling improvements we need.
