### ISSUE TITLE
Reusing the compiler

### ISSUE THREAD

**Issue by danschultz** [dart-lang/dart-pad#136]
Is it possible to reuse the compiler that DartPad is using for my project, or componentize it into some package?

I'd like to create a playground for some tutorials that I plan on writing for [Frappe](https://github.com/danschultz/frappe). Something similar to what [Elm](http://elm-lang.org/edit/examples/Intermediate/Mario.elm) or [Bacon](https://baconjs.github.io/index.html) have on their pages.

I think having a way for developers to embed editable Dart scripts into pages that readers can interact with will go a long way to help spreading the word about Dart.

Also, the DartPad compiler doesn't yet handle package imports. Is there any timeframe for when this feature will be added?

**Comment by sethladd** [comment]
this is EXACTLY the kind of request we were hoping to get :)

**Comment by devoncarew** [comment]
Yup, 100% can re-use! We have a services project as a companion to, but separate from, the dartpad ui project: https://github.com/dart-lang/dart-services. It exports a REST API on a known endpoint which third party systems can use on the exact same footing as DartPad. We've talked with the dartlab.org author and he's experimented with using our service to do compilation.

We'll also have some simple embeddable iframes at some point, to make very simple in-line dart snippet use-cases easy.

Re: packages, we don't have a hard-timeline. We want to tackle better sharing first, but package: support will be high up on our list after that. Here's the issue you'll want to track: https://github.com/dart-lang/dart-services/issues/43.

cc'ing @lukechurch

**Comment by danschultz** [comment]
@devoncarew, @sethladd thanks, this is exactly what I wanted to hear! I have a couple questions on how to execute the JS returned by dart-services. I'll ask them there.

**Comment by lukechurch** [comment]
@danschultz I'll be delighted to help you out over at dart-services
