### ISSUE TITLE
embed-new-flutter.html : code entry not showing 

### ISSUE THREAD

**Issue by chonghorizons** [dart-lang/dart-pad#1363]
When I go to https://dartpad.dev/experimental/embed-new-flutter.html, I don't see a place to enter code.
see: [https://imgur.com/a/FBSUKLT]
![image](https://user-images.githubusercontent.com/36284839/68383657-eadeeb80-010a-11ea-86c0-2ccee87f1812.png)

But, when I go to the Flutter section of https://dartpad.dartlang.org/experimental/new_embeddings_demo.html, things do work.
see [https://imgur.com/x63otYO]
![image](https://user-images.githubusercontent.com/36284839/68383619-d8fd4880-010a-11ea-9df7-56d5e0763ec6.png)

Embeds on google codelabs for flutter layout concepts still work.

I verified on two computers: (in Chrome on macOS X and in Chrome on a chromebook)

**Comment by RedBrogdon** [comment]
The `/experimental/embed-new-[format].html` files were used at one point for the embedded DartPads in codelabs, but have been replaced by files in the root web directory (`/embed-[format].html`).

If you're building a page that uses embedded DartPads, switching the URL should do the trick.

**Comment by chonghorizons** [comment]
Perfect. Works!

I.e. NEW & WORKS:  https://dartpad.dartlang.org/embed-flutter.html 

Only note:  866 websites link to the old version 
![image](https://user-images.githubusercontent.com/36284839/69502134-bc6a5a00-0ed9-11ea-9cd9-4bcaf857481a.png)

So, one might want to do a simple, hacky redirect of static webpage that just says, please go to 
https://dartpad.dartlang.org/embed-flutter.html 

Up to you. Love flutter and appreciate your work.

**Comment by domesticmouse** [comment]
@chonghorizons you can save yourself a few bytes by using https://dartpad.dev/embed-flutter.html as the embed URL. =)
