### ISSUE TITLE
Runtime Exceptions aren't displayed in the UI console when using DDC/Flutter

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1365]
Exceptions in DDC are reported to the `window.onerror` callback. Right now, these errors are being reported as "Script error." because the script is being loaded from a different domain. (See [this article](https://blog.sentry.io/2016/05/17/what-is-script-error).) Non-async exceptions are caught by the Flutter framework and printed to the console.

The response headers from the `compileDDC` endpoint already have an `access-control-allow-origin: *` header, so setting the `crossorigin` attribute to `anonymous` *should* solve this problem, but doesn't seem to work for me.

We should investigate different options for capturing and reporting errors. For example, the future returned by a module calling main() can be listened to for errors, but won't catch everything:

```javascript
dartpad_main.main.main().catchError(function (e, st) {
parent.postMessage(
  {'sender': 'frame', 'type': 'stderr', 'message': e + st}, '*');
});
```

Another option is to use zones, but this requires more investigation

related to #1357

**Comment by johnpryan** [comment]
Related to https://github.com/flutter/flutter/issues/41878

**Comment by parlough** [comment]
I'm not sure the full current state of surfacing runtime exceptions, but I'm going to close this in favor of consolidating with the work in https://github.com/dart-lang/dart-pad/issues/3008. Thanks!
