### ISSUE TITLE
Add "UI Output", "Console" and "Docs" labels to playground

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1370]
Similar to embeds:

<img width="157" alt="Screen Shot 2019-11-11 at 4 05 57 PM" src="https://user-images.githubusercontent.com/1145719/68630756-31cb3900-049d-11ea-90c4-24a5020e66f8.png">

**Comment by RedBrogdon** [comment]
@johnpryan Can this one be closed out?

**Comment by johnpryan** [comment]
yep!
