### ISSUE TITLE
Embedding Guide wiki page updates needed: e.g., YAML syntax error

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1373]
Updates are needed to: https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad

1. Quotes are missing from the YAML sample. This

    ```yaml
    js: [{defer: true, url: https://dartpad.dev/experimental/inject_embed.dart.js}]
    ```

    should be

    ```yaml
    js: [{defer: true, url: 'https://dartpad.dev/experimental/inject_embed.dart.js'}]
    ```

2. Code fence language; it should still be possible to specify `dart` as the language. The following currently seems to work:

        ```dart:run-dartpad
        main() => print("Hello, World!");
        ```

**Comment by parlough** [comment]
The embedding guide was updated and no longer contains this content: https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide

Thanks for the report and tracking this originally though!
