### ISSUE TITLE
Issues on mobile: e.g., lose access to buttons

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1374]
When using a DartPad on a mobile device a user faces issues like these:

- Lose access to some buttons.
- The copy-code and, when present, open-in-dartpad buttons obscure the code.

See below for an example. What I might hope to see is something like this:

<img width="343" src="https://user-images.githubusercontent.com/4140793/68895570-8f5ac200-06f7-11ea-9ed6-b58f2a5944bf.png">

cc @galeyang @kwalrath @legalcodes @johnpryan 

---

Consider the [following dart.dev page](https://dart.dev/tutorials/server/get-started) screenshot of a DartPad:

> <img width="483" src="https://user-images.githubusercontent.com/4140793/68894356-270ae100-06f5-11ea-8ce7-c5c1eb5c3962.png">

On mobile, we lose access to buttons and the copy-code button obscures the code:

> <img alt="DartPad on mobile example" src="https://user-images.githubusercontent.com/4140793/68894446-54f02580-06f5-11ea-9bcd-cc5c1b4b48fb.png" width=300>

Solutions might be:
- To drop the text from the Run button and display only the icon.
- Provide access to the other button via a "more actions" dropdown.
- Move copy-code and open-in-dartpad buttons towards the left and up. Also, if we can't move the buttons, then making the buttons only semitransparent can help see the code under the buttons.

These issues should be easy to fix in CSS.

**Comment by parlough** [comment]
With the new frontend, the UI adapts to a special mobile layout when necessary where all buttons are available. It's now live at https://dartpad.dev/.

If you find any specific issues with the new UI in a mobile layout, please open a new issue. Thanks so much!
