### ISSUE TITLE
Run dart-services as dart user

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1376]
The Dockerfile for dart-services currently kicks off the app engine process as root, despite the fact that a non-root account, "dart", is set up to run the Flutter tool.

The Dockerfile (and anything else required) should be refactored so we can run the app as "dart".

**Comment by domesticmouse** [comment]
I believe this was done a while ago due to Flutter not liking to be run as root. Here is the relevent line in `Dockerfile`:

https://github.com/dart-lang/dart-services/blob/master/Dockerfile#L24

**Comment by RedBrogdon** [comment]
Good catch. I should have closed this with #467.
