### ISSUE TITLE
Warning in JS console for dart.dev pages containing DartPads

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1378]
I'm getting the following warning in the JS console for dart.dev pages containing DartPads (like the [Tutorials > Server > Get started page](https://dart.dev/tutorials/server/get-started)):

![image](https://user-images.githubusercontent.com/4140793/68904310-a7d4d780-070b-11ea-9cd3-c31a42acb9d0.png)

Or as text:
> ⚠️ A cookie associated with a cross-site resource at http://dartpad.dev/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/2914 which will be auditing and evaluating our remaining analytics setup.
