### ISSUE TITLE
Add the counter app into the DartPad Samples dropdown

### ISSUE THREAD

**Issue by zoeyfan** [dart-lang/dart-pad#1379]
The counter app is a really nice starter application for folks to learn and play with Flutter. Please add it to the list of samples on the new DartPad. For reference, this is the app I am referring to: https://flutterbyexample.com/dissecting-the-counter-app/

**Comment by zoeyfan** [comment]
@RedBrogdon @johnpryan

**Comment by RedBrogdon** [comment]
@johnpryan Should this be closed?

**Comment by johnpryan** [comment]
Yes, this has been added to the samples dropdown.
