### ISSUE TITLE
Inject_embed: `run-dartpad` info string breaks syntax highlighting

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1380]
From the [Embedding Guide, Converting code blocks to DartPad section](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad):

> ### Step 2: Add a code snippet
>
> In Markdown:
>
>     ```run-dartpad:theme-light:mode-flutter:run-true
>     main() => print("Hello, World!");
>     ```

Using an info string of `run-dartpad` rather than `dart` **breaks syntax highlighting**, **both in the IDE and the generated site** (users will get to see the original code block in cases where DartPad hasn't been injected yet, or hasn't been successfully injected). Users see this:

> <img src="https://user-images.githubusercontent.com/4140793/68905694-1156e500-0710-11ea-8796-5068fd9efa00.png" width=250>

Instead of this:

> <img src="https://user-images.githubusercontent.com/4140793/68905768-4ebb7280-0710-11ea-8645-e3b5810207fd.png" width=250>

Probably shouldn't happen that often, but still. /cc @kwalrath @legalcodes 

---

It would be great if we could:

- Leave the info string as `dart`, and
- Have the option of triggering the injector by attaching classes to a parent element.

For example:

    <div class="run-dartpad:theme-light:mode-flutter:run-true">
    ```dart
    main() => print("Hello, World!");
    ```
    </div>

Or using a Jekyll-specific syntax:

    {:.run-dartpad:theme-light:mode-flutter:run-true}
    ```dart
    main() => print("Hello, World!");
    ```

Jekyll renders this as:

```html
<pre class="run-dartpad">
<code class="language-dart">main() => ...
</code></pre>
```

**Comment by devmil** [comment]
I know this issue is rather old but I also encountered this problem.
Here is how I was able to solve it for my system (highlight.js v 11.5.1)
```
```lang-dart:run-dartpad:theme-light:width-100%:height-500px:mode-inline
enum SomeEnum {
//...
}
 ```
```
Highlight.js picks up the `lang-dart` part and the DartPad injector is happy as well.
