### ISSUE TITLE
Copy and Open buttons cover code

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1381]
![image](https://user-images.githubusercontent.com/1145719/69103680-e4aa1280-0a1a-11ea-96ec-9c33d84b411f.png)

context: https://github.com/dart-lang/site-www/pull/2114#discussion_r347661255

**Comment by chalin** [comment]
Yep, that issue is also mentioned in #1374, FYI. cc @kwalrath

**Comment by johnpryan** [comment]
Yep, this is a dupe.

**Comment by kwalrath** [comment]
Except that my issue wasn't on mobile. Should we expand the scope of the title of #1374?

**Comment by chalin** [comment]
Or it would be fine to just reopen this issue. That way both issues would keep their focus.

**Comment by parlough** [comment]
Based off the discussion in https://github.com/dart-lang/dart-pad/pull/2573, we're fine keeping this state for now considering the intended use cases of DartPad. If anyone would like to see further changes here, please don't hesitate to reopen the issue or open a new one. Thanks!
