### ISSUE TITLE
Add analytics for Playground project types

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1385]
We should add analytics for how often Dart, HTML, and Flutter snippets are executed in the editor.

**Comment by RedBrogdon** [comment]
We can get an idea of the difference between dart/flutter right now by looking at the ratio of the two compilation paths, but this is still a good thing to make sure we've nailed down.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/2914 which will track analytics in the new UI.
