### ISSUE TITLE
[Embedded Flutter] Embedded Flutter code sample doesn't display anything.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1387]
The "AppBar" dartpad snippet (in master) doesn't seem to render anything when you hit "run".

https://master-api.flutter.dev/flutter/material/AppBar-class.html#material.AppBar.1

![Screen Shot 2019-11-20 at 12 00 00 PM](https://user-images.githubusercontent.com/4229329/69260096-51451e80-0b8d-11ea-962d-f7deb03c8d9b.png)

**Comment by johnsonmh** [comment]
This was solved by doing a hard page reload!

**Comment by RedBrogdon** [comment]
For more context: we deployed a change to DartPad on Tuesday that involved an update to how the browser executes compiled Dart code sent from the backend. It looks like some users' browsers are caching a critical part of the execution setup (an HTML file, we think), and it's causing problems.

If anyone else runs into a similar issue, try doing a full reload of the page and see if that fixes the problem. If not, open an issue and let us know what's up.
