### ISSUE TITLE
Support analyzer options

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1389]
Support analyzer options, if only initially to include the analyzer pedantic package options. IMHO, the pedantic analyzer options offer good feedback for folks (esp. beginners) working on (embedded) DartPad exercises. /cc @kwalrath @legalcodes

**Comment by srawlins** [comment]
package:lints and package:flutter_lints are now used by default! @chalin did you have a specific request for any other analysis option?

**Comment by chalin** [comment]
> package:lints and package:flutter_lints are now used by default! @chalin did you have a specific request for any other analysis option?

Woohoo! That's great! No, not that I can recall, thanks.
