### ISSUE TITLE
Allow host pages to call DartPad inject feature, rather than autorun

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#1390]
AFAIK, the DartPad inject feature upon loading, queries a host page looking for code blocks with a `run-dartpad` class and replaces these blocks by DartPad iframes.

The following might be possible already, but it would be nice if the user could invoke the DartPad inject functionality by, say, clicking on a "Open in DartPad" button that would be shown over a code block or tabbed code block as is shown below. This could help reduce the time to load pages with embedded DartPads.

> ![image](https://user-images.githubusercontent.com/4140793/69448434-85a01280-0d26-11ea-8975-a9bfcc4393a3.png)

> ![image](https://user-images.githubusercontent.com/4140793/69448468-96508880-0d26-11ea-80f2-975f95f4cf9b.png)

Of course the button would be an element in the host page. What we need is a point of call for the inject function.

cc @kwalrath @legalcodes

**Comment by parlough** [comment]
Thanks for tracking this. Definitely would be nice to have!

Superseded by https://github.com/dart-lang/dart-pad/issues/2702#issuecomment-1791322473
