### ISSUE TITLE
disable debug banner by default

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1391]
Samples currently have to disable `debugShowCheckedModeBanner` on MaterialApp to hide the banner. We should hide it by default. The API docs are showing it too: https://master-api.flutter.dev/flutter/material/AppBar-class.html

**Comment by RedBrogdon** [comment]
Looks like there's a global flag in the WidgetsApp class:

https://github.com/flutter/flutter/blob/a1c5e3354be7e0c391447d958bc546629bbe148a/packages/flutter/lib/src/widgets/app.dart#L705

We could modify the bootstrap file to flip that bit.

https://github.com/dart-lang/dart-services/blob/aec916c78aeb0c5a915ed48ded09d020cf33d0bd/lib/src/common.dart#L14

**Comment by rajkananirk** [comment]
here the deep guide to you https://laratuto.com/how-to-remove-debug-banner-in-flutter/

**Comment by domesticmouse** [comment]
@RedBrogdon I'm guessing we would need to patch the Flutter SDK before compiling the JS bundles as part of the build process. Does that sound right?

**Comment by TahaTesser** [comment]
This would help fix https://github.com/flutter/flutter/issues/105959

**Comment by parlough** [comment]
I'm going to close this for now as we look to better track what issues care about in relation to the current state of DartPad. Please feel to reopen or open a new issue if you still think this change is important. Thanks all!

However, I think it's likely better to continue surfacing the banner by default as it better clarifies the performance and behavior of the running samples, while causing fewer misunderstandings.
