### ISSUE TITLE
Change layout based on presence of library import

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1394]
Right now the playground will change the layout based on the presence of `package:flutter/` or `dart:html`. This doesn't work if we want to have the following comment in the default snippet:

```dart
// Uncomment the following line to use Flutter:
// import "package:flutter/material.dart"
```

**Comment by Levi-Lesches** [comment]
On another note, it isn't necessarily obvious that the import is _why_ the layout switches in the first place. If there were an option to manually move the layout around, that would solve both issues.

**Comment by parlough** [comment]
Now that DartPad has dropped support for standalone HTML apps, I believe this is no longer a concern. But if you'd like to see other auto-layout adjustments, please open a new issue with more details. Thanks! :D
