### ISSUE TITLE
Improve playground's layout on mobile

### ISSUE THREAD

**Issue by galeyang** [dart-lang/dart-pad#1396]
Current new playground doesn't seem to support mobile device. This layout is not very usable.
![image](https://user-images.githubusercontent.com/5102864/69468431-f5bb9200-0d40-11ea-8a9b-fc31556e5aa5.png)

Related [issue](https://github.com/dart-lang/dart-pad/issues/1374): embed on mobile

cc: @chalin @johnpryan

**Comment by RedBrogdon** [comment]
We have several open issues for mobile that overlap with this one: #876, #1374, etc.

What we really need to do is figure out exactly what we plan to support for mobile, because I don't believe we've ever put that on paper.

There are open questions like:

* Should/can we design an editing experience for mobile phones?
* Should we instead create a readonly mode in which people can just see the code and run it?
* Should we target desktop/tablet only, and rely on website authors to avoid embedding DartPad on mobile devices?

Additional questions/ideas welcome.

**Comment by chalin** [comment]
IMHO, the overall experience on mobile is fine, besides some of the issues raised (such as #1374) need to be addressed on desktop too -- for situations where the browser window is narrow, including the use of embedded DartPads.

I feel that a few simple features could go a long way, e.g.:

- Adjust the main nav to work well in narrow views (this seems like a low-hanging fruit).
- Put secondary panes (i.e., anything other than the text editor pane), either under the text editor pane or collapsed by default or accessible via a separate tab. E.g., analyzer feedback could be made accessible via a [bottom sheet](https://material.io/components/sheets-bottom/#standard-bottom-sheet), possibly collapsed by default, but with an indication, say of the number of errors/issues being reported.

**Comment by mrmcq2u** [comment]
Would love to see the editor transition to using flutter itself as well

**Comment by suragch** [comment]
One reason that DartPad should target mobile devices is for people learning Dart and Flutter without a computer. That's actually quite a large number of people in poorer countries. I've recently started teaching Dart and Flutter in Mongolia and I was surprised at the number of students (CS majors!) who don't have their own computer or even adequate access to public computers. But they all have a phone. I've been telling them to use DartPad on their phone to do the learning assignments, but then I actually tried it myself and discovered that it wasn't possible.

Here are some UI ideas that would make the mobile experience better:
- Have different tabs for editing, output, and errors.
- Include a hidable bar with characters that are commonly used in Dart but not always easily accessible on mobile keyboards. ({}[]\/...)

**Comment by orestesgaolin** [comment]
Maybe as a temporary measure it would be possible to switch between code and preview views so that they are not laid out side by side?

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/2751 which discusses adding a responsive layout for mobile. There have been recent improvements in https://github.com/dart-lang/dart-pad/commit/7375a5442e854bc20965930271e488fa643634f5 and more are planned. If anyone experiences issues or has suggestions relative to the current state, please let us know with a new issue and we're happy to accept PRs too. Thanks! <3
