### ISSUE TITLE
Flutter FloatingActionButton / Scaffold Layout

### ISSUE THREAD

**Issue by brianegan** [dart-lang/dart-pad#1398]
Hey all! I'm starting to update the cookbook recipes using Dartpad where I can, and I came across an issue. Sorry if it's been asked, I didn't see it in the issues!

Here's my iFrame: 

<iframe src="https://dartpad.dev/embed-flutter.html?id=3053b99b35bb98214c962ad931f9d039&amp;theme=dark&amp;split=50" width="100%" height="1000px"></iframe>

Easier, link to the dartpad: https://dartpad.dev/embed-flutter.html?id=3053b99b35bb98214c962ad931f9d039&amp;theme=dark&amp;split=50

When I run that example, you'll notice two problems:

  1. The FloatingActionButton is cut off at the bottom
  2. The Footer saying "no issues" blocks the UI.

I think these might be two separate issues:

  1. It seems like the FloatingActionButton is cutoff because the size of the right "ressult" pane is somehow linked to the left "code" pane. If I remove some code, the floatingActionButton sits at the bottom correctly. Is there a way to change this up?
  2. It might not be a great idea for there to be a footer with a higher z-index sitting above the UI, since it will block interaction with the UI. One suggestion: the "No Issues" / Footer should be moved out of that View.

Thanks for your help!

**Comment by RedBrogdon** [comment]
Thanks for reporting these!

The "no issues" issue is something we've heard about before but haven't had a chance to redesign:

https://github.com/dart-lang/dart-pad/issues/1235

If the cookbook is going to involve several FAB-using examples, though, we should reprioritize.

The cutoff issue is more concerning. Are you using Firefox? I can see the misalignment with that browser, but not with Chrome, which may be how it slipped through the cracks on us.

@johnpryan The alignment/cutoff problem is something we should try to fix before next week. Do you have time to investigate in the next few days? If not, let me know and I'll dig in.

**Comment by brianegan** [comment]
Thanks!

Thanks! Thought I must have missed that. If you are time constrained, I could take a crack at positioning the issues in a different way?

Very interesting feedback regarding the cutoff as well -- I downgraded Chrome from Beta to Stable channel and it's all good now. Hopefully it's just a glitch in the Beta.

<img width="789" alt="Screen Shot 2019-11-26 at 6 11 56 PM" src="https://user-images.githubusercontent.com/126604/69656523-063d7680-1079-11ea-86cb-56a87ac28837.png">

**Comment by brianegan** [comment]
Also, as a heads up, the Markdown support has been a breeze to use!

**Comment by craiglabenz-g** [comment]
An update on what's going on here. On Firefox, notice that in the linked Dartpad snippet, the left pane's console is pushed off screen. If you shrink the vertical footprint of the code enough so that it does not have a vertical scrollbar, it will bring the console back into view, and with it, the bottom of the rendered content as well.

Note that re-rendering is not required to see this fix happen - it seems to be purely a CSS issue.
