### ISSUE TITLE
Update inject script to send virtual pageviews when new code is loaded

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1403]
DartPad editors created by our inject script do not produce analytics data that can be segmented based on the snippet or exercise loaded into the editor. This is because we rely on the URL to separate one exercise from another, and the URL for a DartPad with injected code doesn't change based on what code has been injected (unlike a DartPad loaded from a Gist ID in the URL).

In order to solve this problem, we need to:

* Update new_embed to:
  - accept an analytics id in its "inject code" method.
  - send a [virtual pageview](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews) as if the URL had been changed to include that ID
* Update the inject script to look for this ID in an embedded code exercise's parameters and send that value in its message to the embedded iframe.

**Comment by RedBrogdon** [comment]
@johnpryan, I'm taking the liberty of assigning this to you, since I imagine you'll work on it. If you're bored with the inject script, though, we can talk about it. 😄

**Comment by johnpryan** [comment]
I forgot to close this issue. This was fixed by https://github.com/dart-lang/dart-pad/pull/1459
