### ISSUE TITLE
Default Pad Doesn't auto-run on page reload

### ISSUE THREAD

**Issue by ditman** [dart-lang/dart-pad#1405]
If I hit this: https://20191202t141003-dot-dart-pad.appspot.com, a default pad will be generated and auto-run. 

However, when the page is refreshed (full page reload), the pad will *not* auto-run. 

Other pads from the dropdown (that change the URL) *do* auto-run after a full page reload.

Should the default pad auto-run after a page reload?

**Comment by johnpryan** [comment]
Yeah I think we should be auto-running when the page loads.
