### ISSUE TITLE
HTML samples show a warning

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1409]
The Flutter SDK is producing a warning when `dart:html` is used. We should double check that we are analyzing using the correct SDK in this case.

![image](https://user-images.githubusercontent.com/1145719/70182255-55e2fa00-1698-11ea-895a-663a7902d4e1.png)

**Comment by devoncarew** [comment]
It would only produce that if the analysis server thinks it's analyzing a flutter project - if the pubspec contains a dep on package:flutter.

**Comment by RedBrogdon** [comment]
I may be routing some of the analysis requests to the wrong instance of the server. I'll take this one and get to it as quick as I can.

**Comment by devoncarew** [comment]
If you don't find any routing issues, it is possible to disable this hint via some config on an analysis_options.yaml file.

**Comment by devoncarew** [comment]
For posterity, here's the implementation of that lint:

https://github.com/dart-lang/linter/blob/master/lib/src/rules/avoid_web_libraries_in_flutter.dart#L71

From memory, we'll only fire if:
- the pubspec has a dep on the flutter sdk
- the project is not a flutter web plugin
- the dart file it importing `dart:html` and a few related packages

@pq has context for this lint.

It sounds like somewhere in the pipe, a dart web sample is being analyzed via the dart-services back-end, where it's creating a pubspec file w/ a dep on the flutter sdk.

**Comment by domesticmouse** [comment]
Hey @devoncarew, if you can point me at the correct configuration to disable this warning I'll look at how to add this into the backend's analyzer.

**Comment by devoncarew** [comment]
I think you want to look at fixing this rather than disabling the lint.

If you do disable, you'll want an analysis_options.yaml file, likely similar to this:

```
include: package:flutter/analysis_options_user.yaml

analyzer:
  errors:
    avoid_web_libraries_in_flutter: ignore
```

That analysis options file should only be used for flutter snippits.

If you'd like to work on fixing the issue instead, just set up a VC w/ me - I'll need a bit more context about how things work on the back-end these days.

**Comment by domesticmouse** [comment]
Yeah, i'd definitely prefer to fix this issue. I'm going to hold off on diving into it until after we land https://github.com/dart-lang/dart-services/pull/488 as that will simplify a chunk of the path that sits between our test suite and our analyzer. 

/cc @RedBrogdon context for wanting to create a support branch in dart-services.

**Comment by domesticmouse** [comment]
I just re-tested this issue with a sample lifted from https://dart.dev/tutorials/web/low-level-html/connect-dart-html:

```html
<p id="RipVanWinkle">
  RipVanWinkle paragraph.
</p>
```

```dart
import 'dart:html';
import 'dart:async';

void main() async {
  Timer(Duration(seconds: 2), () {
    querySelector('#RipVanWinkle').text = 'Wake up, sleepy head!';
  });
}
```

And I didn't see the warning about web-only libraries once. Closing out as fixed, but please feel free to re-open with a repro case if it is still happening.
