### ISSUE TITLE
Investigate best practices for using DartPad with the Brave browser

### ISSUE THREAD

**Issue by NathanaelA** [dart-lang/dart-pad#1410]
### Issue:
   Clicking the `+` does nothing; it is totally ignored like you are missing a click handler.

### Browsers: 
- Brave Beta (Version 1.1.13 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)) - Fails
- Brave Release (Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)) - Fails
- Firefox 70.0.1 - Works

### Error in Dart Console:
On some tests, I see a repeating `Script Error.`

### Error in Developer Console :
-Error: Failed to load resource: net::ERR_UNSAFE_REDIRECT  (www.google-analytics.com/analytics.js:1)
- Lots of flutter/dart startup info's in log -- everything looks the same as Firefox.

> dart.developer.registerExtension ext.flutter.disassemble
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.reassemble
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.platformOverride
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.evict
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.timeDilation
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugPaint
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugPaintBaselinesEnabled
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.repaintRainbow
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugCheckElevationsEnabled
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugDumpLayerTree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugDumpRenderTree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugDumpSemanticsTreeInTraversalOrder
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugDumpApp
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.didSendFirstFrameEvent
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.didSendFirstFrameRasterizedEvent
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.profileWidgetBuilds
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugAllowBanner
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.debugWidgetInspector
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.structuredErrors
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.show
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.disposeAllGroups
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.disposeGroup
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.isWidgetTreeReady
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.disposeId
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.setPubRootDirectories
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.setSelectionById
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getParentChain
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getProperties
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getChildren
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getChildrenSummaryTree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getChildrenDetailsSubtree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getRootWidget
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getRootRenderObject
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getRootWidgetSummaryTree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getDetailsSubtree
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getSelectedRenderObject
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getSelectedWidget
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.getSelectedSummaryWidget
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.isWidgetCreationTracked
dart_sdk.js:52835 dart.developer.registerExtension ext.flutter.inspector.screenshot
dart_sdk.js:52828 dart.developer.postEvent Flutter.FrameworkInitialization {}
dart_sdk.js:52828 dart.developer.postEvent Flutter.Navigation {"route":{"description":"MaterialPageRoute<dynamic>(/)","settings":{"name":"/","isInitialRoute":true}}}
b6409e10de32b280b8938aa75364fa7b:18523 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ b6409e10de32b280b8938aa75364fa7b:18523
(anonymous) @ b6409e10de32b280b8938aa75364fa7b:18523
uN @ playground.dart.js:3485
fZ @ playground.dart.js:11616
hk @ playground.dart.js:11591
$1 @ playground.dart.js:11632
$1 @ playground.dart.js:9188
Bc @ playground.dart.js:517
(anonymous) @ playground.dart.js:525
dart_sdk.js:161290 [Violation] 'requestAnimationFrame' handler took 53ms

**Comment by RedBrogdon** [comment]
Thanks for filing this!

The analytics failure I would expect in a browser as locked down as Brave, but that shouldn't cause DartPad itself to fail. We *do* use an (occasionally hidden) iframe to run the compiled Dart code, though, which is something that Brave may prevent.

This isn't something we'll have the bandwidth to look into right away, but I can easily see myself wanting to play with Brave a bit over the holidays.

**Comment by NathanaelA** [comment]
Yeah, I was pretty sure the analytics block wasn't the cause; but as another developer; I understand the importance of having as much info as possible.  :grinning:   

I didn't see any blockage, I played with it for a while -- and the other demos all worked fine.    The framework seems to act like it initialized correctly, including layout the entire application.    So it seems like the click handler that seems to have got messed up, maybe it thinks their is a  positioning issue (as it appears the click handler is global, not on a per item).

**Comment by RedBrogdon** [comment]
Additional info from @NathanaelA's twitter account:

> The other three flutter demo's actually work fine, and and I assume you don't know that Brave uses the same chromium engine that Chrome uses...   My guess it is actually something measurement wise is off so it isn't detecting the click on the `+` button.

On a personal note, this is probably the first time I've ever referenced [a tweet](https://twitter.com/CongoCart/status/1202428831837151232) in a bug report.

**Comment by JosNun** [comment]
For a bit of additional info, it seems to work fine in Brave when you disable the device recognition blocking.

**Comment by RedBrogdon** [comment]
Additional report from #1422:

>I tried different examples but in all these examples the Floating action button does not work on the Brave browser. I can see the FloatingActionButton widget but `onPressed` does not work.

**Comment by RedBrogdon** [comment]
Additional report for @dcedjiayi:

>This the link that has issues for Dartpad:
>
>https://flutter.dev/docs/codelabs/layout-basics
>
>I am using Brave Browser Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
>
>Dartpad is supposed to have like the code area and the UI output divided into half exactly but it isn't the case when it is on Brave Browser. It works on Chrome Browser though.
>
> Chrome Browser Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by hooperdev** [comment]
I found that a temporary fix is just to click the brave icon and turn off protection for the site. Not like flutter runs ads anyways.

**Comment by NathanaelA** [comment]
@hooperdev - Yeah, but some people don't want to be tracked by Google, so disabling it means google analytics loads...

**Comment by parlough** [comment]
Thanks everyone for the report and discussion.

I'm going to close this as stale as the DartPad frontend has changed quite a bit, as have the browsers, but if anyone is still experiencing issues with Brave or other browsers, please comment here or open a new issue. Thanks!
