### ISSUE TITLE
Dart-Pad receives value from a previously run Future.

### ISSUE THREAD

**Issue by jaitjacob** [dart-lang/dart-pad#1411]
I was running a code sample as follows:

```
Future<void> fetchUserOrder() {
  // Imagine that this function is fetching user info from another service or database
  return Future.delayed(Duration(seconds: 3), () => print('Large Latte'));
}

void main() {
  fetchUserOrder();
  print('Fetching user order...');
}
```
What I noticed is that when I tap on 'Run' a couple of times after pasting the code above the output is similar to,
```
Fetching user order...
Large Latte
Large Latte
Large Latte

```
Shouldn't 'Large Latte' be printed only once considering every time I click 'Run' it is equivalent to program restarting?

**Comment by RedBrogdon** [comment]
It should be, and thanks for reporting this.

We've had occasional issues with DartPad producing incorrect output when the Run button is used in quick succession. There's a bug open for it at #644. I'm going to close this as a duplicate for now, but it's good to have a reminder that the problem still exists.
