### ISSUE TITLE
Remove user-select: none from console output

### ISSUE THREAD

**Issue by alanhzhao** [dart-lang/dart-pad#1414]
The `right-output-panel` element inherits the `user-select: none;` style from `section.main-section`. This prevents selecting the text for copying, etc. Please remove the style wherever possible.

**Comment by devoncarew** [comment]
Also reported here: https://github.com/dart-lang/dart-pad/issues/1413 (and from a discussion with @mraleph).

cc @johnpryan @RedBrogdon
