### ISSUE TITLE
Dartpad issue

### ISSUE THREAD

**Issue by crewsp** [dart-lang/dart-pad#1416]
I am using Google chrome. I am following the instructions to ensure successful use of Dartpad.

Googly Regards

**Comment by RedBrogdon** [comment]
It looks like you're having an issue using DartPad. Could you provide a little more information?

* What's not working?
* What browser version and operating system are you using?
* Are any errors displayed in DartPad or the browser's JS console?
* What code is in the editor (if any) when the problem occurs?
