### ISSUE TITLE
[flutter] cant working in IPadOS

### ISSUE THREAD

**Issue by piyan13** [dart-lang/dart-pad#1417]
When open flutter on the chrome ipadOS page/tab is stopped working

**Comment by RedBrogdon** [comment]
Hrmm. That's an edge case we missed. Chrome on ipadOS is still a WebKit browser, but its user agent string probably goes right through our webkit check without triggering a popup.

Thanks for letting us know. We're not going to be able to fix this without help from the WebKit team, but we can at least make sure users see a warning rather than a frozen browser.

**Comment by johnpryan** [comment]
We should test this now that [Safari is working normally](https://github.com/dart-lang/dart-pad/issues/1108#issuecomment-601453068)

**Comment by domesticmouse** [comment]
Testing this on Safari on an iPad running iOS 13.3.1, and I'm seeing errors attempting to run the Counter app. All I get is a small grey toast pop-up saying "Error compiling to JavaScript". So, no, not working as intended. =(

**Comment by RedBrogdon** [comment]
@domesticmouse Do you mind trying this again, assuming you still have an iPad handy? I believe the version @johnpryan published last week resolved the issue.

**Comment by domesticmouse** [comment]
Looks like we have a new issue, the screen sizing is wrong.

Portrait:
![image](https://user-images.githubusercontent.com/30503/78070012-c996d880-73e6-11ea-9ceb-9377b09c6230.png)

Landscape:
![image](https://user-images.githubusercontent.com/30503/78070132-fba83a80-73e6-11ea-9423-de1b35872bf3.png)

**Comment by parlough** [comment]
The latest version of the DartPad UI has better support for mobile-like layouts and it seems to be running successfully for me on iOS and iPadOS.

If anyone is still having issues or has suggestions for improvements, please open a new issue with reproduction instructions.

Thanks again for reporting the issue!
