### ISSUE TITLE
Can't copy from console window

### ISSUE THREAD

**Issue by jwiese-ms** [dart-lang/dart-pad#1420]
Would be extremely helpful to copy from the console window.  Sometimes I like to just use DartPad to do a quick string manipulation or something where I am transforming data and need the output.  If I can't copy the console output then it isn't useful for me to do this and I need to create a project and run it somewhere else :(

**Comment by RedBrogdon** [comment]
We published a new version on Monday containing a fix for this issue. You should be able to copy out of the Dart console now.
