### ISSUE TITLE
Add Hot Reload support in Dartpad for Flutter 

### ISSUE THREAD

**Issue by samrat19** [dart-lang/dart-pad#1421]
As we have hot reload feature in Android

**Comment by RedBrogdon** [comment]
I could have sworn we had an issue to track this, but I'm not able to find it.

Adding support for hot reload is definitely a good idea. Right now, though, hot reload isn't supported for Flutter on the web:

https://flutter.dev/docs/development/platform-integration/web#does-hot-reload-work-with-a-web-app

Once it is, we can add it to DartPad.

**Comment by samrat19** [comment]
Thanks @RedBrogdon  👍

**Comment by softmarshmallow** [comment]
Flutter web is now stable, supports hot reloading.
https://github.com/dart-lang/dart-pad/issues/1670

**Comment by zawawimanja** [comment]
Is there any key to hot reload in the web ? Cause I cannot find it.

**Comment by RedBrogdon** [comment]
Flutter supports hot _restart_ on the web, which DartPad does make use of -- you may notice that the first time you run an app, there's a delay between the Run button lighting up again and the first frame rendered by Flutter, and that the delay is significantly less for subsequent compiles.

Hot reload, on the other hand, is still in progress. There's a tracking issue here: https://github.com/flutter/flutter/issues/53041

**Comment by parlough** [comment]
Thanks for the discussion here. Closing in favor of the flutter/flutter issue https://github.com/flutter/flutter/issues/53041 which this work will depend on.
