### ISSUE TITLE
How to add new sample to dart pad.

### ISSUE THREAD

**Issue by divyanshub024** [dart-lang/dart-pad#1423]
I want to contribute to the dart pad by adding my Tic-Tac-Toe game into samples (https://dartpad.dev/d0cc86ebee39474f97d3c079c7437752).
How can I contribute? I read the CONTRIBUTION.md file but it seems outdated.

**Comment by RedBrogdon** [comment]
First off, your tic-tac-toe sample is great. There's no mystery why it got so much love on Twitter last week. 😄 

The sample dropdown is tricky, though. When we put a sample into it, folks kind of assume that the DartPad maintainers have given that sample some kind of special status, as if we like it more than the others that people have written. In addition, if we decide to rework the list and take *out* a sample, folks may wonder if we no longer think that sample is any good.

This puts us in an awkward position, where we'd like to showcase samples from people all over, but don't want anyone to think we're playing favorites or looking down on anyone's work.

### So, I propose an alternate solution!

There is a very popular repo called [Awesome Flutter](https://github.com/Solido/awesome-flutter) that serves as an index for Flutter samples and other resources. People submit PRs to it with their stuff, and it's a really useful index.

As far as I know, there is no "Awesome DartPad" repo yet. You could set one up, add your tic-tac-toe sample as the first link, and encourage people to add their cool DartPad links there. It could ultimately becomes a big index like Awesome Flutter and serve an important role in the Flutter community.

What do you think? If this appeals to you, I'm happy to help spread the word once it's created.

**Comment by divyanshub024** [comment]
Thanks a lot, @RedBrogdon for praising my sample!! I'm glad you like it. 

To be true I was thinking to do something like that, but I wasn't sure. I think it's great to have something like "Awesome DartPad". I'll start working on it soon.

**Comment by RedBrogdon** [comment]
Glad to hear you like the idea! Let me know when you've got it up on GitHub and I'll do whatever I can to spread the word.

**Comment by divyanshub024** [comment]
Hey @RedBrogdon!! I need a suggestion regarding this. Should I create a Github Repo like https://github.com/Solido/awesome-flutter or should I go with something like https://itsallwidgets.com/ or codepen.io website where people can add their link and description of there dartpad sample?
Thanks!!

**Comment by RedBrogdon** [comment]
If it were me, I would just create a GitHub repo, since it's so much easier. You could always transition to something more sophisticated later on if you have the time.

**Comment by divyanshub024** [comment]
Thanks a lot, @RedBrogdon for your suggestion. I've created the [Awesome DartPad](https://github.com/divyanshub024/awesome-dart-pad) repo and added my Tic-Tac-Toe sample there. For now, I've categorized the dartpad samples into two categories. One is dart samples and the other is Flutter samples. I would love to get your feedback and how can I make this repo better.

**Comment by divyanshub024** [comment]
Hey, @RedBrogdon Is there a way to embed dart pad in Github Readme.md file?

**Comment by RedBrogdon** [comment]
I don't think there's any way to embed an iframe in a GitHub README. If your thought was to embed live DartPad editors for each of the links, once your repo got pretty big you'd probably crash our servers with all the traffic. :)

I think what you have looks really good. There are a couple things I'd suggest, though:

* Consider adding the name of the contributor for each DartPad.
* Consider also adding the date it was added to the list.
* Consider adding a contributor's guide similar to [the one AwesomeFlutter uses](https://github.com/Solido/awesome-flutter/blob/master/contributing.md).
  - That way people will know how to submit pull requests with their own DartPad links for you to approve.

**Comment by divyanshub024** [comment]
Thanks a lot, @RedBrogdon for these suggestions. I've made changes to the repo and created a [Contribution Guide](https://github.com/divyanshub024/awesome-dart-pad/blob/master/Contribution.md).

My next plan is to have as many good DartPad samples in it.
