### ISSUE TITLE
Solution warning dialog mentions Hint button regardless of whether a hint exists

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1425]
<img width="938" alt="Screen Shot 2019-12-16 at 9 10 15 PM" src="https://user-images.githubusercontent.com/969662/70966564-889dd280-2048-11ea-8505-df1434e7c0f8.png">

I think we assumed (without really realizing it was a choice) that any exercise with a solution would also have a hint, but that's not guaranteed to be the case.

**Comment by kwalrath** [comment]
And in fact it's not the case in https://dart.dev/codelabs/async-await#exercise-practice-handling-errors. (I might add a hint file, since it seems a little weird not to have one.)

**Comment by parlough** [comment]
Thanks for the report and screenshot!

Closing as the exercise functionality that hints were apart of has been removed from DartPad.
