### ISSUE TITLE
Error compiling to JavaScript: XMLHttpRequest error.

### ISSUE THREAD

**Issue by lvtie** [dart-lang/dart-pad#1426]
Error compiling to JavaScript:
XMLHttpRequest error.

**Comment by RedBrogdon** [comment]
Thanks for reporting the issue! Could you provide a little more information?

* What's not working?
* What browser version and operating system are you using?
* Are any errors displayed in DartPad or the browser's JS console?
* What code is in the editor (if any) when the problem occurs?

**Comment by amiver** [comment]
@RedBrogdon LOL LOL LOL if you don't know the answer then please don't reply... this error: compiling to javascript xmlhttprequest was from the day google launched dartpad.. and the same i faced today.. thr is no solution to this till date... and you need more info like browser version, OS... cant stop laughing.. people like you are on flutter team... OMG

**Comment by redpixels** [comment]
@amiver I know right.. smh, all they could do is close the ticket. I just tried dartpad website online editor and for f*ck sake it's trash. Guys, do your self a favor, just use https://www.tutorialspoint.com/execute_dart_online.php, it will save you a lot of frustrations.

**Comment by amiver** [comment]
@redpixels I found this 
https://repl.it/languages/dart 
they use dart VM 2.6.0

**Comment by redpixels** [comment]
@amiver perfect, thank you!

**Comment by domesticmouse** [comment]
Hi @amiver,

I'd just like to point out that @RedBrogdon was being quite polite, given the total lack of context in your original question. I personally would have closed the question as overly ambiguous. So, in the future, if you would like help from those of us here on the DartPad engineering team, please be courteous, and actually ask a full question.

thanks!
