### ISSUE TITLE
DetailedApiRequestError, Could not resolve the package 'flutter_web'

### ISSUE THREAD

**Issue by dbjina** [dart-lang/dart-pad#1427]
I ran the flutter examples of [Basic Flutter layout concepts](https://flutter-ko.dev/docs/codelabs/layout-basics) on Chrome browser. But it was not working.

It showed the bellow error message on the console.

---

Error compiling to JavaScript:
DetailedApiRequestError(status: 400, message: Error: Could not resolve the package 'flutter_web' in 'package:flutter_web/material.dart'.
Error: Could not resolve the package 'flutter_web_test' in 'package:flutter_web_test/flutter_web_test.dart'.
Error: Could not resolve the package 'flutter_web_ui' in 'package:flutter_web_ui/ui.dart'.
/tmp/dartpadWDNGRD/main.dart:1:8: Error: Not found: 'package:flutter_web/material.dart'
import 'package:flutter_web/material.dart';
       ^
/tmp/dartpadWDNGRD/main.dart:2:8: Error: Not found: 'package:flutter_web_test/flutter_web_test.dart'
import 'package:flutter_web_test/flutter_web_test.dart';
       ^
/tmp/dartpadWDNGRD/main.dart:3:8: Error: Not found: 'package:flutter_web_ui/ui.dart'
import 'package:flutter_web_ui/ui.dart' as ui;
       ^
/tmp/dartpadWDNGRD/main.dart:5:24: Error: Type 'StatelessWidget' not found.
class MyWidget extends StatelessWidget {
                       ^^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:7:3: Error: Type 'Widget' not found.
  Widget build(BuildContext context) {
  ^^^^^^
/tmp/dartpadWDNGRD/main.dart:7:16: Error: Type 'BuildContext' not found.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:16:21: Error: Type 'StatelessWidget' not found.
class MyApp extends StatelessWidget {
                    ^^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:18:3: Error: Type 'Widget' not found.
  Widget build(BuildContext context) {
  ^^^^^^
/tmp/dartpadWDNGRD/main.dart:18:16: Error: Type 'BuildContext' not found.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:7:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:8:12: Error: The method 'Row' isn't defined for the class 'MyWidget'.
 - 'MyWidget' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Row'.
    return Row(
           ^^^
/tmp/dartpadWDNGRD/main.dart:9:26: Error: The getter 'MainAxisAlignment' isn't defined for the class 'MyWidget'.
 - 'MyWidget' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MainAxisAlignment'.
      mainAxisAlignment: MainAxisAlignment.center,
                         ^^^^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:11:9: Error: The getter 'Image' isn't defined for the class 'MyWidget'.
 - 'MyWidget' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Image'.
        Image.network('https://urlzs.com/RsqCz'),
        ^^^^^
/tmp/dartpadWDNGRD/main.dart:18:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:19:12: Error: The method 'Directionality' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Directionality'.
    return Directionality(
           ^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:20:22: Error: The getter 'TextDirection' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextDirection'.
      textDirection: TextDirection.ltr,
                     ^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:21:14: Error: The method 'Container' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
      child: Container(
             ^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:22:16: Error: The method 'Color' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Color'.
        color: Color(0xffeeeeee),
               ^^^^^
/tmp/dartpadWDNGRD/main.dart:23:16: Error: The method 'Center' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Center'.
        child: Center(
               ^^^^^^
/tmp/dartpadWDNGRD/main.dart:24:18: Error: The method 'Container' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
          child: Container(
                 ^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:26:20: Error: The method 'Color' isn't defined for the class 'MyApp'.
 - 'MyApp' is from '/tmp/dartpadWDNGRD/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Color'.
            color: Color(0xffcccccc),
                   ^^^^^
/tmp/dartpadWDNGRD/main.dart:35:9: Error: Method not found: 'webOnlyInitializePlatform'.
  await ui.webOnlyInitializePlatform();
        ^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:37:3: Error: Method not found: 'runApp'.
  runApp(MyApp());
  ^^^^^^
/tmp/dartpadWDNGRD/main.dart:39:43: Error: Getter not found: 'WidgetsBinding'.
  final controller = LiveWidgetController(WidgetsBinding.instance);
                                          ^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:39:22: Error: Method not found: 'LiveWidgetController'.
  final controller = LiveWidgetController(WidgetsBinding.instance);
                     ^^^^^^^^^^^^^^^^^^^^
/tmp/dartpadWDNGRD/main.dart:41:50: Error: Getter not found: 'Row'.
  final rows = controller.widgetList(find.byType(Row));
                                                 ^^^
/tmp/dartpadWDNGRD/main.dart:41:38: Error: Getter not found: 'find'.
  final rows = controller.widgetList(find.byType(Row));
                                     ^^^^
/tmp/dartpadWDNGRD/main.dart:53:29: Error: 'Row' isn't a type.
  final row = rows.first as Row;
                            ^^^
/tmp/dartpadWDNGRD/main.dart:55:27: Error: Getter not found: 'MainAxisSize'.
  if (row.mainAxisSize != MainAxisSize.max) {
                          ^^^^^^^^^^^^
)

**Comment by techhtml** [comment]
Sorry. I am Flutter Korea Oranizers and the maintainer of flutter-ko.dev .
I will fix this issue.

**Comment by RedBrogdon** [comment]
Thanks for taking a look, @techhtml!

I'm closing this, as it's not a DartPad issue per se, and will be fixed once flutter-ko.dev has been updated.

**Comment by mehetarnabin** [comment]
I am facing issue while running 
Running Gradle task 'assembleDebug'...
Invalid depfile: D:\development\flutter\database_intro\.dart_tool\flutter_build\6482f2549a69e1729e6d4888d6470c00\kernel_snapshot.d
Invalid depfile: D:\development\flutter\database_intro\.dart_tool\flutter_build\6482f2549a69e1729e6d4888d6470c00\kernel_snapshot.d

Compiler message:
Error: Could not resolve the package 'database_intro' in 'package:database_intro/models/user.dart'.
Error: Could not resolve the package 'database_intro' in 'package:database_intro/utils/database_helper.dart'.
lib/main.dart:1:8: Error: Not found: 'package:database_intro/models/user.dart'
import 'package:database_intro/models/user.dart';
       ^
lib/main.dart:2:8: Error: Not found: 'package:database_intro/utils/database_helper.dart'
import 'package:database_intro/utils/database_helper.dart';
       ^
lib/main.dart:9:16: Error: Method not found: 'DatabaseHelper'.
  var db = new DatabaseHelper();
               ^^^^^^^^^^^^^^
lib/main.dart:12:26: Error: Method not found: 'User'.
   await db.saveUser(new User("Genyy", "musician"));
                         ^^^^
lib/main.dart:69:39: Error: The getter 'User' isn't defined for the class 'Home'.
 - 'Home' is from 'package:databaseintro/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'User'.
                      child:  Text("${User.fromMap(_users[position]).username.substring(0, 1)}"),
                                      ^^^^
lib/main.dart:71:46: Error: The getter 'User' isn't defined for the class 'Home'.
 - 'Home' is from 'package:databaseintro/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'User'.
                    title: new Text("User: ${User.fromMap(_users[position]).username}"),
                                             ^^^^
lib/main.dart:72:46: Error: The getter 'User' isn't defined for the class 'Home'.
 - 'Home' is from 'package:databaseintro/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'User'.
                   subtitle: new Text("Id: ${User.fromMap(_users[position]).id}"),
                                             ^^^^
lib/main.dart:74:47: Error: The getter 'User' isn't defined for the class 'Home'.
 - 'Home' is from 'package:databaseintro/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'User'.
                   onTap: () => debugPrint("${User.fromMap(_users[position]).password}"),
                                              ^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-
uri:package%
3Adatabase_intro%2Fmodels%2Fuser.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_s
ystem.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:604:37)
#2      writeDepf
ile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      Fronten
dCompiler.compile (package:frontend_server/frontend_server.dart:472:15)
<asynchronous suspen
sion>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server
.dart:38:22)
#5      starter (package:flutter_frontend_server/server.dart:149:27)
#6
      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_fr
ontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patc
h/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMe
ssage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1
