### ISSUE TITLE
Choosing a sample from the list does not clear analyzer messages

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1428]
Stale analyzer warnings/errors remain present after new code is loaded by selecting a samples from the drop down. They should be cleared.

We can probably just trust our samples to be issue free and zero out the messages locally rather than make an actual call to the server with the new code.

**Comment by parlough** [comment]
I can't reproduce this with the current UI. If anyone is still experiencing this, please open a new issue with reproduction instructions, thanks so much!
