### ISSUE TITLE
Code completion should trigger on "."

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#143]
Once we've worked out the other issues, we should enable auto-triggering code completion on '.' rather than only Ctrl+Space. A simple attempt to do this seemed to result in the UI 'eating' the '.' rather than still inserting it and bringing up completion

**Comment by Emasoft** [comment]
No. Code completition should trigger on ALL keywords associated with a certain syntax snippet, class or member.
For example for assignements:

"myObject.displayMode = "
where displayMode is an enum called "DisplayMode", should trigger a menu with all the DisplayMode enum members.

Also for methods parameters. For example:
"myObject.updateItem("
where the first parameter of the method "updateItem" is an enum, should trigger a menu with all the right enum members.

The same for dictionay List with generic types T, for example:
"carmodel.featuresList["
where the dictionary key is defined as an enum named "Feature", should trigger a menu with all enum members (for example: Feature.ABS, Feature.AirConditioning, Feature.ParkingSensors, Feature.CruiseControl, etc.).

And autocompletition should never wait the user to type anything. The code completition list should appear automatically while I'm typing. (Control-Space on OS X Yosemite is also already assigned to spotlight quick search popup, so it doesn't work, but this is not relevant).

Also Autocompletition should NEVER block the main thread. It should run in a separate thread (synch or asynch, doesn't matter), and never interrupt the typing. ﻿

**Comment by lukechurch** [comment]
@Emasoft I agree, however this task isn't intended as a final design, it's a micro-step in the right direction.

**Comment by devoncarew** [comment]
> Also Autocompletition should NEVER block the main thread. It should run in a separate thread (synch or asynch, doesn't matter), and never interrupt the typing.

Yup, we're in 100% agreement here :)

**Comment by kasperpeulen** [comment]
```javascript
     "'.'": function(cm) { 
       setTimeout(function(){cm.execCommand("autocomplete");}, 100); 
       throw CodeMirror.Pass; // tell CodeMirror we didn't handle the key 
    } 
```

@lukechurch Something like this is suggested by the code mirror author here:
https://groups.google.com/forum/#!msg/codemirror/gaouAF6--6k/4JZ_PXQ3XlcJ

Maybe also interesting:
```haxe
		options.extraKeys = 
		{
			"." : 
				function passAndHint(cm) 
				{
					if (tabManagerInstance.getCurrentDocument().getMode().name == "haxe") 
					{
						var completionActive = editor.state.completionActive;
						var completionType = completionInstance.getCompletionType();
                        
						if ((completionType == CompletionType.REGULAR || completionType == CompletionType.CLASSLIST) && completionActive != null && completionActive.widget != null) 
						{
							completionActive.widget.pick();
						}
					}
					
					return CodeMirrorStatic.Pass;
				},
```

This is how HIDE does it: https://github.com/HaxeIDE/HIDE/blob/fbfcdc7dd664c931af4a21c31dc8dae4caa977ac/src/cm/Editor.hx

I think HIDE is kind of an interesting project, as it is an IDE based on codemirror.

**Comment by kasperpeulen** [comment]
@Emasoft Made a little bit progress of code completion here:
http://kasperpeulen.github.io/dart-pad/
don't expect too much of it, still a lot of work to do :)

**Comment by lukechurch** [comment]
Closing as this has made a lot of progress from the original. It's not yet the perfect ux, but we're moving in the right direction. Will reopen specific targeted bugs
