### ISSUE TITLE
DartPad should show which Flutter version it's using

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1430]
DartPad has had this little guy since forever:

![image](https://user-images.githubusercontent.com/969662/71218623-09421600-2277-11ea-963a-472d00423473.png)

We should add the Flutter version as well. This will require an update to the dart-services `version` call.

**Comment by domesticmouse** [comment]
The `dart-services` part of this enhancement was fixed by https://github.com/dart-lang/dart-services/pull/487

**Comment by orestesgaolin** [comment]
Please take a look at #1593 and let me know if that's good enough to satisfy this issue :)
