### ISSUE TITLE
The Flutter autoformat should have other options

### ISSUE THREAD

**Issue by Likewizedog** [dart-lang/dart-pad#1431]
The autoformat for Flutter takes on this style, that I don't think everyone agrees with.

![1](https://user-images.githubusercontent.com/10816102/71233405-2a017e80-22fe-11ea-8149-51714b85fe23.png)

-------------------------------------------------------------------------------------------------------------

For me, this next style is much easier to read and work with. I'm sure some will agree. So, an alternate 
formatting option would be really awesome. And maybe later on allow us to create custom format
templates.

![2](https://user-images.githubusercontent.com/10816102/71233406-2a017e80-22fe-11ea-83ad-0c2c2667e2ac.png)

**Comment by domesticmouse** [comment]
The code formatter used by DartPad is supplied by the [dart_style](https://pub.dev/packages/dart_style) project. Please raise this in the attached github project. Thanks!

**Comment by Likewizedog** [comment]
Okay.

Thanks dude.
