### ISSUE TITLE
Flutter gist: Error: No 'main' method found.

### ISSUE THREAD

**Issue by JCzz** [dart-lang/dart-pad#1434]
Unable to link to flutter gist, I get:

gist:
https://gist.github.com/JCzz/f9e2ae58b0e987317a66875e95b75fc3

link to dartpad:
https://dartpad.dev/f9e2ae58b0e987317a66875e95b75fc3

Alsop tried adding /flutter/:
https://dartpad.dev/flutter/f9e2ae58b0e987317a66875e95b75fc3

```
Error compiling to JavaScript:
Error: No 'main' method found.
Error: Compilation failed.
```

**Comment by eladcandroid** [comment]
You should have main.dart file in your gist.

> DartPad looks for three files in each gist:
> 
> main.dart
> index.html (optional)
> styles.css (optional)

https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide

**Comment by RedBrogdon** [comment]
+1 to what @eladcandroid said. DartPad expects the Dart code you'd like loaded into the editor to be in a file called `main.dart`. If you rename the file in your gist to have that name, it should work just fine.
