### ISSUE TITLE
Dartpad for creating complete Flutter web applications

### ISSUE THREAD

**Issue by ansarizafar** [dart-lang/dart-pad#1436]
Dartpad can be used to play with flutter but we can't develop a complete flutter web application with multiple folders/flies. 

Flutter cli run command is painfully slow with so many dependencies and complete toolchain is required. It almost impossible to develop flutter web applications on old machines on in a cloud IDE. Flutter runs much faster in Dartpad without a need to install anything on developer's machine. 

I would request you to add support for developing a complete flutter web application with multiple folders/flies in Dartpad .

**Comment by ansarizafar** [comment]
DartPad uses GitHub gists why not use a Github repo for project files/folders. We should be able to open a github repo and run the Flutter for web app in Dartpad. We should also be able to push our changes back to the Github repo. This will make Flutter developer's life so much easy.

**Comment by rrousselGit** [comment]
Gists _are_ repositories. They are just displayed differently on the web

**Comment by kapzam** [comment]
Yeah, that's exactly what we need. Please do it now. Please, please, please...

**Comment by RedBrogdon** [comment]
This is something we've talked about for a while, and we're all in agreement that an online IDE for Flutter would be a great thing. That said, it's *not* something we plan to turn DartPad into. 

This question has come up a few times (and will likely come up more), so I want to be completely clear about the reasons behind the decision:

* First, building a real IDE is an enormous task. We'd have to figure out how to do a *lot* of things:
  - Debugging
  - Testing
  - Storage/display of multiple files
  - Proper asset handling
  - (the list goes on)
* DartPad is primarily maintained by the Flutter and Dart DevRel team's engineers (there are four of us right now).
  - Even if we dropped our other responsibilities and worked solely on DartPad, it would be a while before we had anything worth using.
* DartPad is intended primarily as a playground for learning and quick experimentation, so turning it into an IDE would pull it away from its most important purpose.
* Other teams and companies will probably release online Dart IDEs to fill this need.

The last item is probably the most important. I would wager that even if we did try to turn DartPad into a real IDE, by the time we got done with the first version, someone would already have beaten us to the punch. Gitpod, for instance, already offers some support for Dart and Flutter:

https://github.com/gitpod-io/gitpod/issues/114

I imagine there are at least a few similar products in development from other companies, too.

This is a long way of saying that while I really appreciate that you're eager to use DartPad to help with your Flutter project, a full IDE experience just isn't something we're likely to get onto our roadmap.

Thanks for the feature suggestion, though. Feel free to file additional issues for anything else you'd like to see!
