### ISSUE TITLE
Code editor max width w/ long string

### ISSUE THREAD

**Issue by iapicca** [dart-lang/dart-pad#1438]
Hi Dart team,
I believe this [issue](https://github.com/dart-lang/dart-pad/issues/311) might be again actual,
please try this [sample](https://dartpad.dartlang.org/cbb4deb6b52b3cb7689d2fb974cf9c5)
thank you

**Comment by RedBrogdon** [comment]
I think you were missing a character in that link, so I did a bit of GitHub stalking and found this Gist:

https://dartpad.dartlang.org/cbb4deb6b52b3cb7689d2fb974cf9c58

It definitely creates a problem in our new front end, so that's for reporting it.

**Comment by johnpryan** [comment]
I think this is a duplicate of https://github.com/dart-lang/dart-pad/issues/1342
