### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by theresasogunle** [dart-lang/dart-pad#1440]
Doesnt work on google chrome

**Comment by RedBrogdon** [comment]
Hrmm. Without a little more information, it will be difficult for us to identify the issue and fix it. Can you tell us:

* What operating system and version you're using.
* What version of Chrome you're using.
* Whether there are any extensions installed that might affect traffic to and from DartPad.
* Whether there are any errors or warnings in your browser console.
* Exactly what the failure is?
