### ISSUE TITLE
Discrepancy between DartPad and Flutter

### ISSUE THREAD

**Issue by GIfatahTH** [dart-lang/dart-pad#1441]
why there is a difference between the return of the identical method: 
in DartPad : 
```dart
      final list = [1];
      print(identical(list.toString(), list.toString())); //print true
```

but in flutter 1.13.1 :
```dart
      final list = [1];
      print(identical(list.toString(), list.toString())); //print false
```

Which of them is wrong?

**Comment by domesticmouse** [comment]
Well, going off of the definition of identical, being "Check whether two references are to the same object", I suspect you are hitting an implementation detail, probably in the form of one of the two implementation platforms using an interned empty string to represent the empty list and one isn't. I'd ask why you are using identical to compare strings, as this seems to be far from what you actually want, which is presumably string equality.

**Comment by GIfatahTH** [comment]
I read an article on string comparison. It is said that the strings are immutable and that two strings with the same sequence of characters must have the same hashCode and are identical. 
So using identical is a performance gain over using ==, isn't?

**Comment by domesticmouse** [comment]
Hey @munificent, any ideas which forum I should redirect this question to? I don’t know Dart’s implementation details well enough to know what is going on here.

**Comment by munificent** [comment]
This is working as intended, though maybe not how you expected. :) The Dart language spec only says *constant* strings are identical if their characters sequences are identical:

> c1 and c2 are constant strings and c1 == c2, OR

If you create two strings at runtime that happen to end up with the same set of characters, they are not considered identical:

```dart
main(List<String> args) {
  print(identical("string", "string")); // True.
  print(identical("string", "str" + "ing")); // False.
}
```

The VM, which is what Flutter uses, dutifully implements this behavior. When Dart is compiled to JavaScript, which is what DartPad does, it uses JavaScript's underlying string semantics and (I think), compiles `identical()` to `===`. In JS, two strings are `===` if they have the same characters, regardless of how it was constructed.

There are a few other differences between the VM and the web version of Dart that all basically boil down to the fact that on the web we want to use the built-in JS types for performance reasons but in some minor corners they behave differently than Dart's specified semantics.

**Comment by GIfatahTH** [comment]
Thank you @munificent . 
In the docs, it is said that Strings with the same sequence of code units have the same hash code.
```dart
void main() {
  test('essay', () {
    String str1 = 'string';
    String str2 = 'str' + 'ing';

    print(identical(str1, str2)); //false
    print(str1.hashCode == str2.hashCode); //true
    print(str1 == str2); //true
  });
}
```
So, is it safe to use hashCode to compare strings? and is there any gain in perfermance compared to ==?

**Comment by domesticmouse** [comment]
If string comparisons are going to be a major percentage of your application's runtime, I'd suggest investigating whether you can use [string interning](https://en.wikipedia.org/wiki/String_interning) to make it possible to use `identical` to compare strings in your app.

**Comment by munificent** [comment]
> So, is it safe to use hashCode to compare strings?

Two strings with the same characters will have the same hash code. That implies that if two strings have different hash codes, they must have different characters. However, the converse is not true. Due to the pigeonhole principle, there are many different sequences of characters that will all share the same hash code.

You can use hash code to quickly tell if two strings are different, but not to ensure that they are the same.

> and is there any gain in perfermance compared to ==?

Probably not. The answer to questions like this is always "profile in the context of your application and on the platforms you target and see."
