### ISSUE TITLE
Option to toggle between mobile screen and webpage

### ISSUE THREAD

**Issue by ghost** [dart-lang/dart-pad#1442]
Writing flutter code on https://dartpad.dartlang.org/ provides us with a view of how the UI will look on a webpage. 

An option to toggle between a webpage view (what we currently see) and a mobile view. 

For example, when in Google Chrome, 
Right click -> Inspect Element -> Toggle mobile view to check responsiveness. 

A similar in dartpad will be helpful.
![mobile&WebView](https://user-images.githubusercontent.com/58399691/71864759-b5647780-3126-11ea-9334-14e7d9f9bce8.png)

**Comment by RedBrogdon** [comment]
This is an idea we've kicked around internally for a while, but it hasn't made it high enough on our list of priorities to get implemented yet.

We definitely agree that it'd be a nice thing to have, though, so I'll keep this issue open.

**Comment by parlough** [comment]
Thanks for the suggestion!

However to keep DartPad's UI simple and focused on testing small Dart and Flutter snippets, I don't think this is something we'll have the time to investigate and implement. It's perhaps best left to IDEs and/or DevTools integrations. [Project IDX](https://idx.dev/) has support for editing, running, and viewing Flutter apps directly within the browser with more configuration, so it's perhaps worth looking in to if you're interested in this functionality.
