### ISSUE TITLE
Line numbers in code part

### ISSUE THREAD

**Issue by vadag** [dart-lang/dart-pad#1445]
Is there any way to toggle line numbers in code part of DarPad?

**Comment by galeyang** [comment]
+1 

The analyzer shows line numbers along with the messages. However, there is no line numbers in code part of DarPad.
![image](https://user-images.githubusercontent.com/5102864/72174125-d7abfe80-338d-11ea-83ae-3b0fc0115b10.png)


![image](https://user-images.githubusercontent.com/5102864/72174103-cd8a0000-338d-11ea-9a1c-a01fdd8d6959.png)

**Comment by RedBrogdon** [comment]
We actually have an open feature request for this (#317), but it hasn't bubbled up to the top of our todo list yet.

I'm going to close this issue as a duplicate. Thanks for filing it, though -- knowing how many people care about a given feature helps us prioritize things.
