### ISSUE TITLE
Wrong display of DartPad under Chrome

### ISSUE THREAD

**Issue by tomaszwojciechowski** [dart-lang/dart-pad#1446]
![obraz](https://user-images.githubusercontent.com/25988088/72199312-9e7d9800-343a-11ea-8e9a-257e7cdb80b3.png)
Same page ( https://flutter.dev/docs/codelabs/implicit-animations ) under Firefox works OK. Both browsers are in factory settings.

**Comment by RedBrogdon** [comment]
Thanks for reporting this, Tomasz. We've seen a few bug reports over the last week relating to display in Chrome. 

Do you mind providing a little more information?

* What operating system and version you're using.
* What version of Chrome you're using.
* Whether there are any extensions installed that might affect traffic to and from DartPad.
* Whether there are any errors or warnings in your browser console.
