### ISSUE TITLE
UI output not rendering on Chrome

### ISSUE THREAD

**Issue by neil-dev** [dart-lang/dart-pad#1447]
The UI is not showing even for the default code on creating a new pad for Flutter.
Details:
Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
OS: Windows 10
console error: flutter:1 A cookie associated with a cross-site resource at http://doubleclick.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by RedBrogdon** [comment]
Thanks for providing your OS/browser version information. That's always a huge help.

When you say the UI isn't rendering, do you mean the Flutter UI that should appear when Flutter code is run?

If so, are you using any plugins that might interfere with the loading/display of iframes? Some ad blockers, for example, add restrictions to iframes.

**Comment by neil-dev** [comment]
I disabled the adblocker of my anti-virus and also other extensions but the result is the same. The UI output should be "Hello World" for the default code, but nothing is coming on screen.

**Comment by RedBrogdon** [comment]
Hrmm. I haven't been able to replicate the issue you're seeing on my end, though I haven't tried with a Windows machine yet (they're a little hard to come by in the office). Normally I would expect *some* kind of warning/error to appear in the console or onscreen. The warning about cookies is from Google Analytics, though. It's expected and shouldn't affect DartPad's actual performance.

 I'll try to find a windows machine in the next couple days to see if I can verify the behavior you're seeing. In the meantime, the only thing I can suggest is (assuming you haven't done it already) to clear your browser cache and do a full hard reload of the page to see if any caching issues are screwing things up.

**Comment by neil-dev** [comment]
Tried clearing my cache and restarted my browser but to no avail. 
Here's the warnings and errors coming from the console:
`A cookie associated with a cross-site resource at http://doubleclick.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1449 WebSocket connection to 'wss://gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06BYCeaZE2I3gBpHBR9MuXNNjahTtp5Ss6oYHugWqA4OInYw2WAeWwnykZcHGA1bubwRo5BA_Cq4626ASb-3MnRbw/websocket?url=https%3A%2F%2Fdartpad.dartlang.org%2Fscripts%2Fframe_dark.html&nocache=1579201093655' failed: Error during WebSocket handshake: Unexpected response code: 400
GetWebSocket @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1449
GetWebSocket @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1479
Start @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1595
FindSupportedImpl @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1988
SupportedCallerProvider.FindSupported @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1998
Init @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2004
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2047
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:266
2main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1317 GET https://gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06BYCeaZE2I3gBpHBR9MuXNNjahTtp5Ss6oYHugWqA4OInYw2WAeWwnykZcHGA1bubwRo5BA_Cq4626ASb-3MnRbw/init?url=https%3A%2F%2Fdartpad.dartlang.org%2Fscripts%2Fframe_dark.html&isTopLevel=false&nocache=13ed1 400
AsyncCall @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1317
InitCall @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1411
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2007
FindSupportedImpl.m_current @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1988
Start @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1354
FindSupportedImpl @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1988
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1988
GetWebSocket.webSocket.onerror @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1492
error (async)
GetWebSocket @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1489
Start @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1595
FindSupportedImpl @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1988
SupportedCallerProvider.FindSupported @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:1998
Init @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2004
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2047
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:266
setTimeout (async)
ns.SetTimeout @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:261
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2047
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:2048
(anonymous) @ main.js?attr=Brn06IMD66rVQzBxYRASA552jsaWaZLWpeS4rNEKsvY4raRm5Zycn-9sRDH_yB-EKLliB4R_F8lr-RzdeVLH39qyqeLSzlV9LO3BM6Zg59o:3522
frame_dark.html:1 Access to XMLHttpRequest at 'https://gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06BYCeaZE2I3gBpHBR9MuXNNjahTtp5Ss6oYHugWqA4OInYw2WAeWwnykZcHGA1bubwRo5BA_Cq4626ASb-3MnRbw/init?url=https%3A%2F%2Fdartpad.dartlang.org%2Fscripts%2Fframe_dark.html&isTopLevel=false&nocache=13ed1' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
/scripts/frame_dark.html#/:1 Access to XMLHttpRequest at 'https://dartpad.dartlang.org/scripts/assets/FontManifest.json' from origin 'null' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.
dart_sdk.js:5306 Uncaught (in promise) Error: Failed to load asset at "assets/FontManifest.json" (0)
    at Object.throw_ [as throw] (dart_sdk.js:4021)
    at AssetManager.load (dart_sdk.js:136461)
    at load.throw (<anonymous>)
    at onError (dart_sdk.js:42268)
    at _RootZone.runBinary (dart_sdk.js:42153)
    at _FutureListener.thenAwait.handleError (dart_sdk.js:37923)
    at handleError (dart_sdk.js:38426)
    at Function._propagateToListeners (dart_sdk.js:38449)
    at _Future.new.[_completeError] (dart_sdk.js:38313)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:38345)
    at Object._microtaskLoop (dart_sdk.js:42362)
    at _startMicrotaskLoop (dart_sdk.js:42368)
    at dart_sdk.js:38648`

**Comment by Franklinz98** [comment]
@neil-dev @RedBrogdon I had the same problem, then I tried Dartpad in Opera and it worked fine, and I checked the DartPad source code in Chrome and noticed that I was getting 33 errors, all of them related to CORS policy (cors policy no 'access-control-allow-origin'). So I installed [this](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=es) Chrome extension and it worked!

**Comment by Franklinz98** [comment]
> The above solution works but I guess depending on a third-party application shouldn't be considered as a solution.

Yeah but the problem is related with Chrome having problems with CORS policy so...

**Comment by johnpryan** [comment]
I think this is out of date, feel free to leave a comment if you're still running into this.

**Comment by imyelxx** [comment]
hi, @johnpryan, I encouter this cors policy issue right now
