### ISSUE TITLE
Multiple cursors can be added in DartPad

### ISSUE THREAD

**Issue by Piinks** [dart-lang/dart-pad#1460]
## What happened?

While using DartPad, I realized that if (on Mac) you use cmd-click in the editor, it will add another cursor. You can also type simultaneously with as many cursors as you like! 😝 

## Steps to reproduce problem

1. Open DartPad, here's one: https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b
2. cmd-click on the text editor

### Browser

Browser: Google Chrome

Version: 79.0.3945.130 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
I do not think so.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
None.
```

### Machine

Operating system: macOS Mojave

Version: 10.14.6

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
No failure.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
No output.
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16964204/73090128-9a1a9b80-3e8c-11ea-9fe3-85ef240d8a6b.gif)

**Comment by RedBrogdon** [comment]
It's not well-documented, but this is just CodeMirror being CodeMirror. I don't believe there's any way to disable multi-cursor support, either.

@johnpryan Could we document this somewhere? Our keymap popup would be the likely place, but I don't know that it's set up for anything that involves a mouse click.

**Comment by johnpryan** [comment]
Yeah we could add a link to the CodeMirror docs in the popup - although I'm not sure this documented.

**Comment by RedBrogdon** [comment]
I literally can't find any mention of it in their docs, so I don't know what we'd link to.

@Piinks, unless you object, I'm inclined to just chalk this up as WAI. 😄

**Comment by Piinks** [comment]
SGTM! Thanks for looking into it! I'll close this then. :)
