### ISSUE TITLE
It would be nice if DartPad had line numbers

### ISSUE THREAD

**Issue by Piinks** [dart-lang/dart-pad#1461]
When using DartPad recently, I received an error with a line number referring to the issue. Unfortunately, the editor does not have line numbers so I had to go looking for it another way. 

I've noticed that folks are using DartPad now to report and reproduce bugs in flutter/flutter (yay!), and having line numbers would help with those really large samples that have many many lines of code. :)

![Screen Shot 2020-01-24 at 11 14 42 AM](https://user-images.githubusercontent.com/16964204/73096882-bde4de00-3e9a-11ea-84c8-00160eeff75b.png)

**Comment by RedBrogdon** [comment]
This has been an open request for a while (see #317), but it hasn't gotten up to the top of our list yet.

We're going to have to add an options dialog at some point in the near future, though, at which point it would make sense to add a checkbox for this.

**Comment by RedBrogdon** [comment]
I'm going to close this as a dupe and link to it from the older issue.
