### ISSUE TITLE
Privacy with underscore doesn't work as expected

### ISSUE THREAD

**Issue by marcobraghim** [dart-lang/dart-pad#1464]
Hey, sorry, but we need to talk about the issue #1450 where I ask about the underscore to set as private attributes and methods. The given link to explain how it works says:

"The import and library directives can help you create a modular and shareable code base. Libraries not only provide APIs, but are a unit of privacy: **identifiers that start with an underscore (_) are visible only inside the library. Every Dart app is a library, even if it doesn’t use a library directive**."
https://dart.dev/guides/language/language-tour#libraries-and-visibility

It quotes about **libraries**, not files, but in practice when I have the class in the same file where I'm trying to access the private attribute it is accessible, but when it's over separated files, even with the same library explicity, doesn't work as expected. Even being a tottaly separated dependency too.

To test this concept I created twoo repositories, one with a library *veiculos* where I just have twoo classes separated into twoo files and try to access a private attribute from the other class. It won't work, but would if the classes was into the same file.

The other is a simple start example from Flutter that includes the first repository as a dependency. https://github.com/marcobraghim/flutter_clean_app

I really need to understand exactly how it works, if this is definetelly the expected behavior and there's something wrong with the documentation or I've been missunderstand what is the right way to use.

Thank you very much.

**Comment by RedBrogdon** [comment]
What you're seeing is correct, and the best way to understand it is to know that *by default*, Dart assigns each file to its own library. So when you spread code across two files and don't do anything to link them into a single library, Dart thinks, "Okay, I'll consider these to be separate libraries and enforce privacy restrictions that way." When you put all the code in a single file, though, Dart says, "Great, this is one big library, so I don't really have to enforce any privacy restrictions!"

You can use the `library` and `part` keywords to define multiple files that are all considered part of the same library. In practice, though, most people don't do this. They just group related classes into a single file and let them all be little libraries within a larger package or app. 

There is a guide that speaks more directly to these types of things available:

https://dart.dev/guides/libraries/create-library-packages

If you'd like a small, real-world example of the pattern, I use it in my rebloc package:

https://github.com/RedBrogdon/rebloc
