### ISSUE TITLE
Save DartPad

### ISSUE THREAD

**Issue by nicolasdupere** [dart-lang/dart-pad#1466]
I wish I could save my DartPad code. Create NewPad and have access to them later and share them with my teams!

**Comment by domesticmouse** [comment]
The way we currently author and share content for [DartPad.dev](https://dartpad.dev/) is documented in our [Sharing Guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide). For example, the [Flutter Counter app](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b) is served from [gist.github.com/b6409e10de32b280b8938aa75364fa7b](https://gist.github.com/johnpryan/b6409e10de32b280b8938aa75364fa7b)

**Comment by RedBrogdon** [comment]
For slightly more context, we *do* have an open issue for a signed-in GitHub experience, which would allow for users to save code to a Gist within their account:

https://github.com/dart-lang/dart-pad/issues/805

We just haven't had time to work on it yet.
