### ISSUE TITLE
Update samples in dropdown for Material API changes 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1469]
https://github.com/dart-lang/dart-services/pull/476 updates the Flutter SDK to https://github.com/flutter/flutter/commit/340b193f20e85f2cfbebf84fe315112985a38a13, which will require updating the samples in the dropdown. See https://github.com/dart-lang/dart-services/pull/476#issuecomment-580551087 for details.

**Comment by domesticmouse** [comment]
I believe this task is complete?
