### ISSUE TITLE
Layout Basics Dartpad not showing properly

### ISSUE THREAD

**Issue by dcedjiayi** [dart-lang/dart-pad#1470]
This the link that has issues for Dartpad:

https://flutter.dev/docs/codelabs/layout-basics

I am using Brave Browser Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

Dartpad is supposed to have like the code area and the UI output divided into half exactly but it isn't the case when it is on Brave Browser. It works on Chrome Browser though.

Chrome Browser Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by RedBrogdon** [comment]
Thanks for filing a report.

I'll add this to our existing issue for Brave browser support (#1410).
