### ISSUE TITLE
dart-services doesn't send CORS origin wildcard for OPTIONS request

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1471]
The dart-services backend sends this header in response to POST and GET requests on API methods:

    Access-Control-Allow-Origin: *

This done so websites can hit the API without violating CORS, and it works great.

The backend does *not*, however, send that header in response to OPTIONS requests, which can cause trouble for some browsers and appears to violate the way OPTIONS is meant to be used for CORS:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

We should update dart-services to send the correct headers for each OPTIONS request.

**Comment by domesticmouse** [comment]
The code for populating CORS headers is in lib/src/shelf_cors.dart

There is code in there for populating options response with the appropriate headers, so more debugging is required.

**Comment by domesticmouse** [comment]
I'm happy to take on this ticket, once we have a failing repro case.
