### ISSUE TITLE
Code is only shown in full screen mode

### ISSUE THREAD

**Issue by betsegawlemma** [dart-lang/dart-pad#1473]
The dartpad do not show the code unless it is in full screen mode

**Comment by RedBrogdon** [comment]
Thanks for filing a bug. Can you provide some additional information to help us narrow down what happened?

### Browser
Browser:
Version:
Are you using any extensions/plugins that affect website behavior (particularly those that affect iframes, such as ad blockers)?
Are there any warnings or errors in your browser's JavaScript console?

### Machine
Operating system:
Version:

### Your code
What code was in the editor, if any, when the failure occurred?

### DartPad's output
Did DartPad print anything to the console pane?

### Page
What page were you on when the failure occured? Can you provide a URL?

**Comment by betsegawlemma** [comment]
@RedBrogdon Thanks for your reply. Below are additional info about the issue

- **Browser**: Google Chrome Version 80.0.3987.116 (Official Build) 
- **OS**: Ubuntu 19.10 (eoan) 
- I was on  [this](https://flutter.dev/docs/codelabs/layout-basics) url
- The pad looks like the following
![dart_pad](https://user-images.githubusercontent.com/4020024/75319002-d6bb2780-587c-11ea-824d-c2d48090f794.png)
- It does not show any code and did not allow me to add any
- I have to click the second vertical line (says full screen when I mouse hover to it) shown on the left side to see the code and it works well in full screen mode
- Yes there were few extensions including Ad Blocker. I have removed them all and re-started the browser but the problem is still there
-  Yes there are the following error (repeated several times) on the JavaScript Console
```
Uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at jX.ic (embed_flutter.dart.js:11866)
    at fY.hE (embed_flutter.dart.js:10605)
    at Object.eval (eval at um (embed_flutter.dart.js:590), <anonymous>:3:36)
    at lq.$0 (embed_flutter.dart.js:6077)
    at lp.$1 (embed_flutter.dart.js:6085)
    at pS.f9 (embed_flutter.dart.js:6886)
    at pV.$1 (embed_flutter.dart.js:6923)
    at Object.xF (embed_flutter.dart.js:1417)
    at Object.xG (embed_flutter.dart.js:1411)
    at fY.j4 (embed_flutter.dart.js:10603)
```
- and the following warning (repeated several times) on JavaScript console
```
DevTools failed to parse SourceMap: https://flutter.dev/assets/source-maps/main.js.map
DevTools failed to parse SourceMap: https://flutter.dev/assets/source-maps/main.scss.map
```
- The Dart Pad console is empty

**Comment by anikkcah** [comment]
Update Google Chrome to the latest Official Build(Version 80.0.3987.149).
Reply if it solved your issue.

**Comment by betsegawlemma** [comment]
> Update Google Chrome to the latest Official Build(Version 80.0.3987.149).
> Reply if it solved your issue.

No it did not, still the same

![image](https://user-images.githubusercontent.com/4020024/77317611-93899280-6d1c-11ea-8d2d-3aa7b729a023.png)

**Comment by RedBrogdon** [comment]
I believe we've addressed this particular bug in the past year. If it's still an issue for anyone, though, please let us know.

**Comment by toubiaplc** [comment]
It is working fine now, thanks!

**Comment by betsegawlemma** [comment]
Yes, it is working fine now. Thanks!

**Comment by parlough** [comment]
Looks like this was reopened on accident by the no-response bot. But to confirm, I tested on a few browsers and embeds are showing code now without opening in a full-screen mode.

Thanks all!
