### ISSUE TITLE
A query parameter to open the output console by default.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/dart-pad#1477]
For the Flutter configuration of DartPad, it would be nice to have a query parameter option to open the output window by default so that for samples that do things like print "button pressed" in the console, it's obvious that something is happening in the example.

Otherwise, it just seems like the sample doesn't work.

**Comment by RedBrogdon** [comment]
@johnpryan Do you mind taking a look at this to see whether it's something that could be done quickly? Greg is in the process of converting a bunch of API Doc pages to use DartPad, and this is blocking some of them.

(If it can't be done that easily, don't feel obligated to crunch)
