### ISSUE TITLE
Would be nice to be able to choose the Flutter version

### ISSUE THREAD

**Issue by SebTardif** [dart-lang/dart-pad#1479]
I used a very similar concept for a different UI framework, and it was very popular to report bug again specific version, and we also used a lot the tool to figure out the exact version a regression was introduced, just by changing the version of the runtime.

So it would be nice if we could choose the Flutter version, like a dropdown.

**Comment by RedBrogdon** [comment]
We completely agree. We've had an open feature request for multiple version support for a while now (#774) , but haven't been able to get to it.

I'm closing this as a duplicate, but I'll link back to this issue. Thanks for filing it!
