### ISSUE TITLE
Responsive design is rendering menu items inaccessible

### ISSUE THREAD

**Issue by mvandermade** [dart-lang/dart-pad#1480]
## What happened?
When using the dartpad in half- or quarter-screen the menu items "format" and "new pad" are no longer accessible

## Steps to reproduce problem
Steps to reproduce:
<img width="921" alt="Schermafbeelding 2020-02-11 om 21 05 13" src="https://user-images.githubusercontent.com/33425497/74274713-db2b0080-4d12-11ea-9738-f7ca81f082c1.png">

Now resize the window:
<img width="563" alt="Schermafbeelding 2020-02-11 om 21 05 36" src="https://user-images.githubusercontent.com/33425497/74274727-e41bd200-4d12-11ea-98cd-c5c9d1cbdde6.png">

### Browser

Browser: Safari

Version: Catalina

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
-
```

### Machine

Operating system: OSX Catalina

Version: 10.15.3

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
See screenshot
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
-
```

**Comment by RedBrogdon** [comment]
Thanks for filing this, and for including so much detail!

**Comment by johnpryan** [comment]
Thanks for filing an issue - it sounds like we should add these to the dropdown menu instead of just hiding them.

**Comment by parlough** [comment]
As mentioned above, thanks for the report and the details!

The DartPad frontend has been rewritten and as a result this menu has a different behavior, so I'll close this issue as stale. However, the new UI has been written to be a bit more responsive and seems to keep relevant items accessible.

Please open a new issue with reproduction details if you're experiencing inacessible items with the current UI. Thanks again :)
