### ISSUE TITLE
Chrome Flutter codelab UI Output

### ISSUE THREAD

**Issue by CItyM** [dart-lang/dart-pad#1481]
Pressing the Run button does not seem to load the UI Output

**Comment by RedBrogdon** [comment]
Thanks for filing a bug. Can you provide some additional information to help us narrow down what happened?

### Browser
Browser:
Version:
Are you using any extensions/plugins that affect website behavior (particularly those that affect iframes, such as ad blockers)?
Are there any warnings or errors in your browser's JavaScript console?

### Machine
Operating system:
Version:

### Your code
What code was in the editor, if any, when the failure occurred?

### DartPad's output
Did DartPad print anything to the console pane?

**Comment by CItyM** [comment]
### Browser
Browser: Google Chome
Version: 80.0.3987.87 (Official Build) (64-bit)
I am using 2 ad-block plugins: Adblock Plus and uBlock Origin. Other than that no previous errors have occurred.


### Machine
Operating system: Windows 10 Pro
Version: 1903

### Code
The code is the one provided in the [Basic Flutter layout concepts](https://flutter.dev/docs/codelabs/layout-basics) codelab. The only changes in the code I made are only the ones following the codelab. 

### DartPad's output
DartPad did not output anything. At first, was the default 

> UI output

and after the button was pressed it went to blank without outputting anything.

**Comment by RedBrogdon** [comment]
Thanks for the response. Have you tried disabling your ad blockers? They may be interfering with DartPad's iframes.

Also, are there any errors logged in the browser console?

**Comment by CItyM** [comment]
Just checked now and everything works fine. 

But yes, I tried disabling the ad blockers and other extensions and nothing seemed to have an effect then.  I tried the same code on Mozilla and Edge and it was working properly. Then tried restarting the pc, but no result eighter. 

Do not know what has changed to work now.

**Comment by RedBrogdon** [comment]
Weird. Maybe it as a caching issue or something strange like that. At any rate, I'm glad it's working for you.

Thanks for taking the time to come back and let us know.
