### ISSUE TITLE
Update https://dartpad.dev/example/inject.html so it works again (simple fixes)

### ISSUE THREAD

**Issue by gary-c-chang** [dart-lang/dart-pad#1484]
https://dartpad.dev/example/inject.html currently doesn't run as it has old flutter_web references

Open https://dartpad.dev/example/inject.html in web browser
Dartpad examples have compilation errors - can't find flutter_web etc

## Additional info
Fix is simple - convert flutter_web to flutter eg. new import is:
import 'package:flutter/material.dart';
Remove import for flutter_web_test.dart and ui.dart
Remove the line: await ui.webOnlyInitializePlatform();

### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by domesticmouse** [comment]
Thanks for the bug report @gary-c-chang =)
