### ISSUE TITLE
LinearGradient not Rendering the Flutter Web Page properly - Dart Pad for Flutter

### ISSUE THREAD

**Issue by hasnentai** [dart-lang/dart-pad#1487]
## What happened?
I created a container of 120x120 and I gave box decoration border-radius and Liner Gradient which returns a black screen ( I don't know why).

Then I removed the  Liner Gradient and used color to the container and it worked fine

## Steps to reproduce problem
Just use the gradient property on any container inside BodDecoration and try passing LinearGradient.

### Browser

Browser: Google Chrome

Version: 79.0.3945.130 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
No Errors No Warnings
```

### Machine

Operating system: Windows 10 Pro

Version: 64 Bit Operation System

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
Widget build(BuildContext context) {
    return  Container(
         height:120.0,
         width:120.0,
         decoration:BoxDecoration(
           borderRadius:BorderRadius.circular(200.0),
           color:Colors.grey,
           gradient: LinearGradient(
              begin: Alignment.topRight,
              end: Alignment.bottomLeft,
              colors: [Colors.blue, Colors.red])
          
          )
        );
  }
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
No Errors on Console
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.
![chrome-capture (3)](https://user-images.githubusercontent.com/26821037/74905767-11ccdf00-53d5-11ea-9eb6-0a9bde04e4ff.jpg)

**Comment by abid-shaon-3r** [comment]
I am facing the same issue with LinearGradient on Container. It has no effect on Container

**Comment by domesticmouse** [comment]
I'm attempting to replicate, and I got as far as [building this reproduction case](https://dartpad.dev/68ae1c358ab7dd4e46eb246dacdffb32). Which is working for me. 
Can y'all try this link? 

It might be a network issue, so if you are digging in the console panel go looking in the network traces for a API call to https://dart-services.appspot.com/api/dartservices/v1/compileDDC?alt=json and see if it is failing and why.

Thanks!

**Comment by RedBrogdon** [comment]
I'm also unable to replicate this. 😞 

@hasnentai  and @abid-shaon-3r, can you provide the complete code for an example that isn't working? You can either post the entire thing here or create a gist (see the [sharing guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide) for info on how to do this).

**Comment by hasnentai** [comment]
@domesticmouse Yes you are correct its a network issue.I checked the same thing in my personal network and it worked but when I tried in Office network it din worked so that might be the case.Its not working the proxy network.

Any Workaround for this ? how do I make it work in office network.

Note : I have already set up the PROXY using set_http 

@domesticmouse and @RedBrogdon  Thanks a lot 

**I am closing this issue**

**Comment by domesticmouse** [comment]
@hasnentai debugging network issues from another continent is hard. I'd suggest asking people closer to you, as they will have a better understanding of your local conditions. Sorry!
