### ISSUE TITLE
TextDecorationStyle.double renders a single underline.

### ISSUE THREAD

**Issue by AyushBherwani1998** [dart-lang/dart-pad#1488]
`TextDecorationStyle.double` renders a single underline instead of double. I was just trying to play with the dart pad and I tried adding a `Text` widget inside `MaterialApp`. The `Text` widget rendered with a single underline. The default behavior should be to render double underlines. 

To verify the scenario I explicitly defined `TextDecorationStyle.double` inside `Text` widget but it still rendered the single underline.

![Screenshot (3)](https://user-images.githubusercontent.com/34301187/75154850-b6805100-5734-11ea-833c-a078a17a3977.png)

## Your Code

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
    home: Center(
        child: Text("Hello World",
            style: TextStyle(
                decoration: TextDecoration.underline,
                decorationStyle: TextDecorationStyle.double)))));

```

### Browser

Browser: Firefox

Version: 73.0.1

**Comment by AyushBherwani1998** [comment]
> 
> 
> `TextDecorationStyle.double` renders a single underline instead of double. I was just trying to play with the dart pad and I tried adding a `Text` widget inside `MaterialApp`. The `Text` widget rendered with a single underline. The default behavior should be to render double underlines.
> 
> To verify the scenario I explicitly defined `TextDecorationStyle.double` inside `Text` widget but it still rendered the single underline.
> 
> ![Screenshot (3)](https://user-images.githubusercontent.com/34301187/75154850-b6805100-5734-11ea-833c-a078a17a3977.png)
> ## Your Code
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MaterialApp(
>     home: Center(
>         child: Text("Hello World",
>             style: TextStyle(
>                 decoration: TextDecoration.underline,
>                 decorationStyle: TextDecorationStyle.double)))));
> ```
> 
> ## Additional info
> ### Browser
> 
> Browser: Firefox
> 
> Version: 73.0.1

Update on the issue. I tried the example in Chrome and it shows the proper output. 

Chrome Version: 80.0.3987.122

**Comment by RedBrogdon** [comment]
Thank you for filing this bug, and for providing your browser and version numbers!

After some quick investigation, it appears that this is a problem with the Flutter SDK itself. I've filed a bug on the SDK repo:

https://github.com/flutter/flutter/issues/51506

Once it's fixed there, it will find its way onto DartPad during one of our regular engine rolls, so I'm going to go ahead and close this bug.
