### ISSUE TITLE
Router isn't handling gists of a specific length

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1489]
Gists that are 32 characters long work correctly, but 20 character gists aren't handled correctly:

http://dartpad.dartlang.org/405379bacf30335f3aed
http://dartpad.dev/405379bacf30335f3aed
http://dartpad.dev/3723fcf3915ca935d13393b8a9f86fd5

See: https://github.com/dart-lang/site-www/issues/2280

**Comment by RedBrogdon** [comment]
Fixed in #1490. Not sure why this wasn't auto-closed.
