### ISSUE TITLE
New embed and playground: Add load-from-URL functionality

### ISSUE THREAD

**Issue by pennzht** [dart-lang/dart-pad#1494]
Feature request:
* To be able to open a DartPad instance by giving a URL to a dart source file.
    - Supports arbitrary URLs from any domain.
    - Users may need to configure the server in a certain way.

This feature would make it easier for users to provide DartPad instances with a given dart file, and is easier to automate.

**Comment by RedBrogdon** [comment]
This is a good feature request. 

We'd need to:

* Add a new query param to both the embeds and the playground
* Add code to GistLoader to handle making the request (it'd be the same path as the one we use for API Doc samples.
* Correctly handle and message CORS issues, which will likely be the biggest problem (e.g. Someone tries to load a dart file off of a server that's not expecting to be hit by DartPad, it returns a file with headers allowing for no cross-origin access, and the load fails).
  - Users are going to need to know it's not a "DartPad" problem.

**Comment by parlough** [comment]
As there hasn't been much interest in this, I'm going to close this as not planned to keep the loading as simple as possible.

If anyone has a strong use case for this functionality or similar, please do let us know and/or open a new issue. Thanks!
