### ISSUE TITLE
Please add UI drag and drop 

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/dart-pad#1499]
make a android laypuit editor like app

**Comment by RedBrogdon** [comment]
I'm normally very reluctant to close feature requests of any kind, but a graphical interface builder just isn't in scope for DartPad. Unless the number of engineers working on the project were significantly increased, this just isn't something we could do.

There are some other projects in this space, though, such as [FlutterAppBuilder](https://flutterappbuilder.club/).

**Comment by fisforfaheem** [comment]
Thanks, But all other tools suck
