### ISSUE TITLE
stack trace in spirodraw sample in dartpad

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-pad#150]
I tried running the spirodraw sample on a Nexus 7 and got:

Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-17) is negative.

I suspect it's because of window size.

**Comment by devoncarew** [comment]
OK, thanks for the report.

**Comment by devoncarew** [comment]
fixed in https://gist.github.com/devoncarew/9e42aabfcc15c81a0406
