### ISSUE TITLE
Dart pad not opening 

### ISSUE THREAD

**Issue by AhmedYasirFarooqui** [dart-lang/dart-pad#1500]
Hello.
Below is a screenshot of the issue iv'e been facing for quite a while.
I'm trying to work on dart pad as a part of flutter code labs but every time i reload it says "Dart pad took too long to respond". The same thing happens when i try another browser.Any help would be appreciated...
![image](https://user-images.githubusercontent.com/50533452/76632399-fe8cd980-6564-11ea-80b2-e763b04ce6ac.png)

**Comment by kwalrath** [comment]
What browser(s) are you using?

Do you reload often? If so, you might be running into GitHub rate limiting. If that's the problem, within 60 minutes you should be able to reload. (I haven't seen that particular message, though.)

More info: https://dart.dev/tools/dartpad/troubleshoot

**Comment by AhmedYasirFarooqui** [comment]
@kwalrath i'm using chrome and microsoft edge. I reload it almost 5 to 10 times when it happens but it's no use...
Thanks for the link by the way i'll check for a solution.

**Comment by domesticmouse** [comment]
@AhmedYasirFarooqui is there anything interesting in the Browser's console logs? 

The downside of a distributed application is that some computer you've never heard of can break your whole app...
