### ISSUE TITLE
Non-Flutter code issues a lint against using web libraries

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart-pad#1504]
I am guessing this is not intentional and meant to be isolated to Flutter "pads".

(Is this https://github.com/dart-lang/dart-pad/issues/1216 again?)

Step 1: Create a new blank HTML project

![Screen Shot 2020-03-19 at 10 36 15 AM](https://user-images.githubusercontent.com/168174/77097151-952a2200-69cd-11ea-80fe-f6c2b547fba0.png)

Step 2: Observe a lint

![Screen Shot 2020-03-19 at 10 36 24 AM](https://user-images.githubusercontent.com/168174/77097159-96f3e580-69cd-11ea-80ef-3d595881b7ab.png)

**Comment by RedBrogdon** [comment]
We've got an issue open for this (#1409), but we haven't been able to get it on anyone's plate yet. I'll make a point of changing that.
