### ISSUE TITLE
Large number of columns causes UI issues

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1514]
We currently wrap the code around to the next column, unless you have a line with a really long string. In that case, CodeMirror can't wrap the line and the splitter has to get bumped over. This can make the UI output too small and is generally not a good way to handle long lines of text.

Instead, we should allow horizontal scrolling to prevent these types of issues.

Steps to reproduce:

1. go to https://dartpad.dev/d24a0f99c38edd13de16e009f0ba4a59
2. scroll through the code
3. observe the splitter changes depending on the code that is displayed

**Comment by RedBrogdon** [comment]
Is this a duplicate of #1342?

**Comment by johnpryan** [comment]
Ah, yeah this is the same issue.
