### ISSUE TITLE
Updated Dartpad for null safety tech preview

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-pad#1516]
This is an overall tracking issue for Dartpad and the general Dart null safety tech preview. We believe we need:

- [ ] Roll an updated Dart SDK
- [ ] Support running code
- [ ] If possible, support Flutter code
- [ ] Consider: paste-to-migrate option?

**Comment by franklinyow** [comment]
Ready to close?

**Comment by mit-mit** [comment]
Yes, we launched this, closing

**Comment by RedBrogdon** [comment]
Just so I don't look like a complete slack, I was holding off on closing the issue until the code landed in this repo (it was deployed from a fork). 😄 

It's fine that it's closed now, though.
