### ISSUE TITLE
Allow import of "dart:ui" without a Flutter package

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1518]
It's technically possible to use dart:ui in a Flutter application without actually importing `package:flutter/*.dart`. Because we use the presence of a Flutter package import to determine whether to route code to the Flutter analysis/compilation pipeline, though, we force users to add a Flutter import they don't need in order to get access to dart:ui.

There is a small but valid case to be made for examples that use dart:ui alone, so we should look at adding it to the list of imports that trigger the Flutter pipeline.

**Comment by domesticmouse** [comment]
Backend changes have landed, but now this requires changes to the front end to send code to the right end points. It's about now that I point at https://github.com/dart-lang/dart-pad/issues/1519 as better than the current content sniffing approach.

**Comment by domesticmouse** [comment]
Example code from @dnfield for proving this works:

```dart
import 'dart:ui';

void main() {
  print(window.physicalSize);
}
```

**Comment by HeySreelal** [comment]
Can I use it as of now? Seems like I can't import 'dart:ui' on a pure dart project. Can someone let me know what I might be missing? 

I get the URI doesn't exist error.
```
Target of URI doesn't exist: 'dart:ui'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
```

**Comment by domesticmouse** [comment]
> Can I use it as of now? Seems like I can't import 'dart:ui' on a pure dart project. Can someone let me know what I might be missing? 
> 
> 
> 
> I get the URI doesn't exist error.
> 
> ```
> 
> Target of URI doesn't exist: 'dart:ui'.
> 
> Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
> 
> ```

Can you please raise a new issue with a reproduction case?

**Comment by HeySreelal** [comment]
Sure, I'll do that.

**Comment by domesticmouse** [comment]
> Well, still not available on a local dart project.

What do you mean?

**Comment by dnfield** [comment]
This issue was for dartpad specifically. CLI dart doesn't know about dart:ui.  You can try using flutter test which sort of works.
