### ISSUE TITLE
Extend the API compile and analyze calls to make used packages explicit

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1519]
I'd like to make the packages that a code submission uses explicit, in preparation for supporting packages from pub. While we can imply used packages from import lines (and that's how it is done currently), looking at other online pad services, they tend to allow the user to specify which packages they use.

Thoughts?

**Comment by johnpryan** [comment]
Sounds good to me, it sounds like this would need on a UI component to selecting from a list of packages? 

As an aside, I think we need to keep detecting `package:flutter` and/or `dart:ui` for choosing which layout to use.

**Comment by domesticmouse** [comment]
One option is to make the packages explicit in the API call, and then just do the content sniffing in the front end. That way we have the content sniffing in only one place, not two.

**Comment by RedBrogdon** [comment]
We should also look at extending the /version call to report what packages are available and in which version.

**Comment by domesticmouse** [comment]
Sounds like it's time for me to put together a design doc

**Comment by RedBrogdon** [comment]
@domesticmouse Does it still make sense to have this open? If so, should it be assigned to @srawlins.

**Comment by domesticmouse** [comment]
Assigned

**Comment by srawlins** [comment]
Interesting. This does sound like a design is needed. For example, if you check `firebase_core`, we can either auto-check `flutter` (probably requires a round trip to server), or leave empty and people may be surprised that their code is now Flutter. And I think continued inference from the source would be important; if someone pastes in code which imports flutter or firebase, the settings should automatically flip to use those packages.

**Comment by domesticmouse** [comment]
Given the various DartPad embeds and what not, it probably no longer makes sense to break the current contract of going off of what the imports say. So I'm going to close out this issue.
