### ISSUE TITLE
Source code doesn't show up

### ISSUE THREAD

**Issue by vitorvidaldev** [dart-lang/dart-pad#1520]
I'm using the latest version of Chrome. On the codelab page of "Basic Flutter layout concepts", the source code doesn't show up and the run button displays nothing. Opening dartpad in another tab (with right click) displays the code and I'm able to run it normally.

**Comment by RedBrogdon** [comment]
Thanks for the bug report!

Would you mind providing some additional info to help us narrow down the problem?

### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?

### Machine

Operating system:

Version:

**Comment by vitorvidaldev** [comment]
OS: Windows 10 Home Edition Single Language
Version: 10.0.18363 Build 18363

Plugins: adblock plus, google translate, react dev tools, redux dev tools, octotree.
Turning off adblock does NOT fix it.
It works on Microsoft Edge (updated)

Console warnings:
DevTools failed to parse SourceMap: https://flutter.dev/assets/source-maps/main.js.map
DevTools failed to parse SourceMap: https://flutter.dev/assets/source-maps/main.scss.map
2DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map
DevTools failed to parse SourceMap: https://dartpad.dev/primer.css.map
DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map
2DevTools failed to parse SourceMap: https://dartpad.dev/primer.css.map
2DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map
2DevTools failed to parse SourceMap: https://dartpad.dev/primer.css.map
2DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map
DevTools failed to parse SourceMap: https://dartpad.dev/primer.css.map
2DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map
DevTools failed to parse SourceMap: https://dartpad.dev/primer.css.map
DevTools failed to parse SourceMap: https://dartpad.dev/split.min.js.map

Console errors:
GET https://survey.g.doubleclick.net/async_survey?site=at3ul57xpub2vk3oxt2ytw365i net::ERR_BLOCKED_BY_CLIENT

embed_flutter.dart.js:441 Uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at lc.ip (embed_flutter.dart.js:12392)
    at hA.hO (embed_flutter.dart.js:11143)
    at Object.eval (eval at wy (embed_flutter.dart.js:583), <anonymous>:3:36)
    at mA.$0 (embed_flutter.dart.js:6437)
    at mz.$1 (embed_flutter.dart.js:6445)
    at rE.fj (embed_flutter.dart.js:7055)
    at rH.$1 (embed_flutter.dart.js:7092)
    at Object.AH (embed_flutter.dart.js:1426)
    at Object.AI (embed_flutter.dart.js:1420)
    at hA.jj (embed_flutter.dart.js:11141)
