### ISSUE TITLE
How to come out of infinite loop in Dart pad?

### ISSUE THREAD

**Issue by rawatdev** [dart-lang/dart-pad#1522]
When we stuck in infinite loop in Dartpad it stucks forever. If i close and reopen dartpad it start with the same program and do auto run which makes it stuck forever. Is there a way to come out of this.

Below code is used to recreate the same problem.

**Sample code:**

```
void main() {
while(true);
}
```

**Comment by domesticmouse** [comment]
Short term work around, kill the tab and open up https://dartpad.dev/215ba63265350c02dfbd586dfd30b8c3 to load a stock standard getting started sample. Then play with it for a bit. That should clear your locally stored code. I think.

But I can confirm that the forever loop does indeed lock the tab. Which is amusing.

**Comment by abhi9045** [comment]
Yes, its working this way. But dartpad itself provide someway to solve it.

**Comment by RedBrogdon** [comment]
This is something we might be able to detect and kill in the bootstrap. I'm not sure exactly how, but it's got to be possible given that some other online code editors are able to do it with their JS.

**Comment by azenkwed** [comment]
I have the same issue in chrome. Now I cannot use Dart Pad anymore as every time I close and reopen it runs the code. 
I would suggest the development team to make sure the code is not run automatically on reopening or open.

**Comment by johnpryan** [comment]
#1529 removed the auto-run behavior, so this is probably lower priority now.

**Comment by parlough** [comment]
Thanks for the issue! I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/668 which also discusses adding a way to stop program execution.
