### ISSUE TITLE
Error doesn't show up in Dart pad

### ISSUE THREAD

**Issue by Tinhorn** [dart-lang/dart-pad#1523]
## What happened?
I was trying to reproduce an error in dart-pad to better understand it. I expected an error to show up but I didn't see a runtime exception

## Steps to reproduce problem

I just entered code and it stops responding after it hits the problematic line.

### Browser

Browser:
Firefox

Version:
74.0.1 (64-bit)
Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
uBlock Origin
Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Error: frame_dark.html:340:17
    wrapException https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:340
    throwExpression https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:353
    add$1 https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:968
    main https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:940
    <anonymous> https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:1198
    <anonymous> https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:1182
    dartProgram https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:1193
    <anonymous> https://dartpad.dev/scripts/frame_dark.html#/ line 38 > scriptElement:1200
    replaceJavaScript https://dartpad.dev/scripts/frame_dark.html:38
    messageHandler https://dartpad.dev/scripts/frame_dark.html:54
[paste warnings or errors here]
```

### Machine

Operating system: Windows

Version: 10

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
`void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
    var foo = const <String>[];
    foo.add("bar");
  }
}
`
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by domesticmouse** [comment]
Odd, this is working for me in Chrome. Yay, browser differences...

**Comment by johnpryan** [comment]
I just tried the linked code snippet in Firefox 75.0, and couldn't reproduce the issue. @Tinhorn can you confirm you are still seeing this?

**Comment by Tinhorn** [comment]
I got the following output @johnpryan in 75
hello 1
: Unsupported operation: addError: Unsupported operation: add

Looks like you can close this ticket.
Thanks for looking into it
