### ISSUE TITLE
DartPad does not recognize the return statements

### ISSUE THREAD

**Issue by AGUREX** [dart-lang/dart-pad#1524]
## What happened?

I was doing the "Create a factory" exercise in the "intro to Dart for Java Developers" were has an example of a factory method that returns an instatiations of some classes and it intends to launch an exception catch,  by a try catch method and by a throws response. The problem is that when I modified the code to not throw an exception, and  after i commented the throws response, I got the right output, nevertheless the DartPad kept telling me that there was an issue because there was no return statements in the factory method.

### Browser

Browser: Firefox Developer Edition

Version: 75.0b12 (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
yes
Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
unreachable code after return statement
playground.dart.js:3:46
unreachable code after return statement
playground.dart.js:3:43
unreachable code after return statement
playground.dart.js line 630 > Function:3:46
unreachable code after return statement
playground.dart.js line 625 > Function:3:43
unreachable code after return statement
playground.dart.js:3:51
unreachable code after return statement
playground.dart.js line 630 > Function:3:51
El recurso en “https://www.google-analytics.com/analytics.js” ha sido bloqueado porque está habilitado el bloqueo de contenido.
63e040a3fd682e191af40f6427eaf9ef
Error en el mapeo fuente: Error: request failed with status 404
URL del recurso: https://dartpad.dartlang.org/scripts/playground.dart.js
URL del mapa fuente: playground.dart.js.map
```

### Machine

Operating system: MicroSoft Windows 10

Version: Home Version 10.0.18362.720

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
import 'dart:math';

abstract class Shape {
  factory Shape(String type) {
    if (type == 'circle') return Circle(2);
    if (type == 'square') return Square(2);
   if (type == 'triangle') return Triangle(2);
    // To trigger exception, don't implement a check for 'triangle'.
     //throw 'Can\'t create $type.';
    
  }
  num get area;
}

class Circle implements Shape {
  final num radius;
  Circle(this.radius);
  num get area => pi * pow(radius, 2);
}

class Square implements Shape {
  final num side;
  Square(this.side);
  num get area => pow(side, 2);
}

class Triangle implements Shape {
  final num side;
  Triangle(this.side);
  num get area => pow(side, 2) / 2;
}

main() {
  try {
    print(Shape('circle').area);
    print(Shape('square').area);
    print(Shape('triangle').area);
  } catch (err) {
    print(err);
  }
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
12.566370614359172
4
2
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by eernstg** [comment]
When the statement that throws is commented out, an execution of the body of the factory constructor can reach the end without returning anything. This is well defined (it means returning null), but you get the 'info' message in DartPad because it is likely to be a bug.

So the behavior that you're reporting is as expected.

You could say that the problem isn't that DartPad doesn't recognize the return statements, the problem is that the program does not have a return statement on all the possible paths that execution can take.

If you know that the argument passed to the constructor will always be one of the values that you're testing for then you could do the following:

```dart
abstract class Shape {
  factory Shape(String type) {
    if (type == 'circle') {
      return Circle(2);
    } else if (type == 'square') {
      return Square(2);
    } else {
      assert(type == 'triangle');
      return Triangle(2);
    }
  }
  num get area;
}
```

This variant of the constructor body will always reach a return statement, no matter which path it chooses, and then there is no message about missing returns.

**Comment by AGUREX** [comment]
Thank you so much for your response, it was very helpful.

**Comment by domesticmouse** [comment]
@AGUREX is this now safe to close?

**Comment by RedBrogdon** [comment]
@eernstg, thanks for dropping by! 😄

**Comment by eernstg** [comment]
Thank you! 😃
