### ISSUE TITLE
Tabs Support

### ISSUE THREAD

**Issue by wwmyers** [dart-lang/dart-pad#1534]
Loving Dartpad as a way to learn Dart on the fly :)

My request:
I would like to see tabs support added as an option, so we can practice OOP across multiple files with Dart

Thanks

**Comment by RedBrogdon** [comment]
Glad you're enjoying DartPad!

Multiple tabs is something we've looked at doing, but doesn't really make sense for DartPad's mission to be a simple playground for experimentation. There are some projects in the works from other teams that have more fully featured IDE-like experiences, so those might be an option.

Thanks for the suggestion, though. Don't be shy if there's another feature you'd like to see!
