### ISSUE TITLE
Add Flutter commit to version call

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1535]
It's be nice to be able to ping the /version method on the back end and get the specific commit with which that instance is compiling/analyzing Flutter. That could make it easier for the Flutter web team to debug issues with DartPad or CodePen.

CC: @domesticmouse

**Comment by domesticmouse** [comment]
Alternate suggestion: how about the output from `flutter —version` on a new api endpoint?

**Comment by domesticmouse** [comment]
I'm wondering if this is required now that we are running Flutter on beta releases? I believe the flutter version reported by the API is now sufficient to nail down the git rev.

**Comment by domesticmouse** [comment]
Eep, re-opening

**Comment by domesticmouse** [comment]
I'm guessing this is no longer required, now that we are on `beta` channel.
