### ISSUE TITLE
DartPad does not handle "<" and ">" correct when in-lining code

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/dart-pad#1536]
When embedding DartPad and using inline code examples, DartPad does not correctly interpret Dart syntax that includes pairs of carets: "<" and ">". Dart forces content between carets to become lowercase, thus breaking the build.

The current resolution to this issue is to manually escape carets with "`&lt;`" and "`&gt;`" but this prevents easy copy/pasting of code samples into webpages.

Here is an example:

```
<pre>
  <code class="language-run-dartpad:theme-light:mode-dart:split-60:height-420px">
{$ begin main.dart $}
void main() {
  final list = List<FooBar>();
  print(list);
}
​
class <FooBar> {}
{$ end main.dart $}
  </code>
</pre>
```

Pasting the above code in an HTML file with embedded DartPad results in the following when running the page in the browser:

```dart
void main() {
  final list = List<foobar>();
  print(list);
}
​
class <foobar> {}
```

This problem is not specific to property declarations, it also happens with class definitions, e.g., "`extends State<mywidget>`"

This issue has been observed in Chrome and Safari.

**Comment by matthew-carroll** [comment]
@csells @zoeyfan for visibility WRT use of DartPad for training purposes.

**Comment by RedBrogdon** [comment]
@johnpryan I've taken the liberty of assigning this to you. Let me know if it's not something you have bandwidth for and I'll take a look -- could be a good chance for me to get to know the inject script anyway. 😄

**Comment by johnpryan** [comment]
I can take a look - we might need to investigate if there are ways to tell the browser what's going on (e.g. how does the browser know `var myHtml = '</code>';` isn't closing the opening tag?)

**Comment by matthew-carroll** [comment]
The specific situation of an embedded "</code>" may be difficult to deal with, but also very fringe. The situation now is that apparently any pair of opening and closing "<" and ">" are being processed incorrectly. At least from this side, a quick solution to the general problem would be great, even if it doesn't solve the "</code>" case.

**Comment by johnpryan** [comment]
I don't think this is something DartPad can fix.  Any code inside a `<code>` tag should always be escape HTML characters. I'll update the Embedding Guide to make this clear.

Most static site generators will generally handle this for you. If you're generating the page in Dart you can use [htmlEscape](https://api.dart.dev/stable/2.8.0/dart-convert/HtmlEscape-class.html) from the dart:convert library.

Hope this helps.

**Comment by matthew-carroll** [comment]
I'm not sure this conclusion is accurate. `<` and `>` do not seem to pose issues when used in fat arrows like `=>`, nor comparison operators like `if (this > that)`. I think this should be reconsidered and addressed. The use-case here is copying and pasting code from the IDE into a webpage. This is a major friction for composing educational material.

**Comment by johnpryan** [comment]
I don't think this is an issue with DartPad - putting anything that *looks* like markup in a `<pre>` or `<code>` element won't get parsed correctly. By the time this script runs, the browser has already parsed the contents of the `<code>` or `<pre>` tag. 

For example:

```
<html>
<head>
</head>
<body>
	<pre>
		<code class="foobar">
			var x = '<Foo>text</Foo>';
			var y = '&lt;Foo&gt;text&lt;/Foo&gt;';
		</code>
	</pre>
<script type="text/javascript" defer>
	var el = document.querySelector('.foobar');
	console.log('textContent: ' + el.textContent);
	console.log('innerText: ' + el.innerText);
	console.log('innerHTML: ' + el.innerHTML);
	console.log('outerHTML: ' + el.outerHTML);
</script>
</body>
</html>
```

Loading this page in Chrome will display:

```
var x = 'text';
var y = '<Foo>text</Foo>';
```

The print statements show up as:

```
textContent: 
			var x = 'text';
			var y = '<Foo>text</Foo>';
		
foo.html:14 innerText: 
			var x = 'text';
			var y = '<Foo>text</Foo>';
		
foo.html:15 innerHTML: 
			var x = '<foo>text</foo>';
			var y = '&lt;Foo&gt;text&lt;/Foo&gt;';
		
foo.html:16 outerHTML: <code class="foobar">
			var x = '<foo>text</foo>';
			var y = '&lt;Foo&gt;text&lt;/Foo&gt;';
		</code>
```



I haven't tried it, but this [IDE plugin](https://plugins.jetbrains.com/plugin/2162-string-manipulation) might allow you to easily copy the text as an HTML-escaped string.
