### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [dart-lang/dart-pad#1541]
### Feature Request

- [ ] A GUI editor (like Qt Creator) to manually draw Widgets on a canvas and generate the output Dart code, good for mockups

- [ ] More themes (monokai, one dark pro, synth wave 84', etc.)

- [ ] Improve the intellisense/intelligent typeahead (CTRL + SPACE, auto-complete) speed.

- [ ] Multiple project files (or at least a source folder for multiple dart files, and an assets folder to store assets)

- [ ] pub packages (or including the most used pub packages like http, shared_preferences, provider, etc.)

- [ ] Auto run after modifying the code or hitting Ctrl + S (save)

- [ ] Improve error handling. Sometimes it displays "script errror" and no other info.

- [ ] Customizable skins (Android/iOS) so the output looks like a mobile phone and not a web app

- [ ] Button to save project to Github.

- [ ] In HTML mode, allowing <script> tags to load JS libraries (I tried injecting the HtmlScriptElement and modifying the src property and it didn't work).

**Comment by srawlins** [comment]
All great ideas.

As fart as the suggestions which require back-end changes are concerned ("Assets", "Pub packages", "Button to save in GitHub"), I don't think this issue is useful. It is more effective to request individual features with individual issue requests. I suspect this is true for the front-end requests as well.

**Comment by parlough** [comment]
Thanks so much for the suggestions! As srawlins mentioned, it is better to open individual issues for specific changes. Some of these have been implemented and others already have issues. So I'm going to close this issue in favor of those. If there are other changes you'd like to see implemented, please do open another issue. Thanks again :D
