### ISSUE TITLE
A way to increase font size

### ISSUE THREAD

**Issue by carlaopereirasanca** [dart-lang/dart-pad#1544]
I am following this [guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide) to embed Dartpad in a html page.
Everything is OK, but I would like that the fonts showed within Dartpad to be greater.
If I use control/+ on the browser, going to 150% (for example), I can get the result I want.
But I would like it to define it on the html code.
Is it possible?
Thanks in advance.

**Comment by leecommamichael** [comment]
I am writing an interactive intro to programming using DartPad. I expect only 3-5 lines of code runnable/visible for the early-sections which, **at this font-scale, is hard to read and imbalanced.**

While debugging the issue, and considering hacking the styles..., I noticed that **the rendition at dartpad.dev is actually almost usable. The text looks much clearer than the component rendered by the embed-link.**

![scaling-problem](https://user-images.githubusercontent.com/13748676/100534669-0a91f780-31d7-11eb-8165-3e964d12da78.png)

I am using Chromium Version 86.0.4240.183 (Official Build) Arch Linux (64-bit) on a 32" 4K monitor with no font-scaling in either GNOME or Chrome.

**Comment by parlough** [comment]
Thanks for the suggestion! As mentioned, the DartPad UI does function correctly with the browser zoom functionality and the scaffolding adapts according to the user's browser font size configuration.

As for extra customizability of the editor font size, I think that is better left to be supported by full text editors and IDEs, such as [Project IDX](https://idx.dev/) which has built-in support for Flutter or other environments like [GitHub Codespaces](https://github.com/features/codespaces).

If you mean the font size of the running sample, HTML samples are no longer supported, but font size in Flutter samples can be changed through normal theming functionality.

If you'd still like to see changes here, please feel free to continue the discussion here or open a new issue. Thanks again!
