### ISSUE TITLE
Some actions place cursor at beginning of the document

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1546]
- [x] Wrap with column (fixed in #1559)
- [ ] Format

**Comment by RedBrogdon** [comment]
Formatting code has the same, unfortunate effect. I'm not sure if they're related or not.

**Comment by gazialankus** [comment]
Formatting does not take the cursor to the beginning of the document for me. Formatting simply makes the editor lose focus. Pressing tab a couple of times takes the cursor back to the editor and the cursor appears in the correct place.

**Comment by parlough** [comment]
Preserving cursor position on format was implemented by https://github.com/dart-lang/dart-pad/pull/2885 🚀
