### ISSUE TITLE
[BUG][Flutter] The pop method return void.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/dart-pad#1548]
The pop method of `NavigatorState` return bool in [flutter sdk ](https://api.flutter.dev/flutter/widgets/NavigatorState/pop.html).

And the dart-pad return void.

![image](https://user-images.githubusercontent.com/14145407/80708781-cb0b0c00-8b1e-11ea-9d6f-28c5f3d1dfab.png)

---

Why is there such a difference, any consideration?

**Comment by CaiJingLong** [comment]
If this issue should be posted in flutter issues, please remind me, I will close it and open a new one on the flutter repo.

**Comment by CaiJingLong** [comment]
I know the reason, because dartpad uses master or dev API, and my code is copied from the flutter stable branch.

**Comment by RedBrogdon** [comment]
Yep, that's the reason. We're on the beta branch right now.
