### ISSUE TITLE
Uncaught exceptions are printed twice in Firefox

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart-pad#1549]
## What happened?

In Firefox, uncaught exceptions are printed to the console twice and look confusing.

## Steps to reproduce problem

Run:

```dart
void main() {
  throw Exception('hello');
}
```

In Firefox, the console shows:
```
: Exception: helloError: Exception: hello
```

This is fine in Chrome, however:
```
Uncaught Error: Exception: hello
```

### Browser

Browser: Firefox 75.0 (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No, I verified with a clean profile.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
: Exception: hello frame_dark.html line 38 > scriptElement:340:17
    wrapException https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:340
    main https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:923
    <anonymous> https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:1183
    <anonymous> https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:1167
    dartProgram https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:1178
    <anonymous> https://dartpad.dartlang.org/scripts/frame_dark.html line 38 > scriptElement:1185
    replaceJavaScript https://dartpad.dartlang.org/scripts/frame_dark.html:38
    messageHandler https://dartpad.dartlang.org/scripts/frame_dark.html:54
```

### Machine

Operating system: Linux

**Comment by parlough** [comment]
Thanks for the issue! It seems this is still occurring, but as we are trying to make it easier to identify important and still relevant issues, I'm going to consolidate this issue in to https://github.com/dart-lang/dart-pad/issues/3008. Thanks again :D
