### ISSUE TITLE
null safe dartpad should run with strong checking

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dart-pad#1552]
In the nullsafety version of dartpad:

```dart
void main() {
  print([1, 2, null] is List<int>);
  print([1, 2] is List<int>);
}
```

should print

```
false
true
```

Under weak mode, it'll print `true` twice for backwards compat.

FYI - @leafpetersen @mit-mit @sigmundch 

@nshahan - do you have pointer to how to enable at runtime?  I.e., a JS call before invoking `main` in the HTML?

**Comment by nshahan** [comment]
To set the runtime null safety mode at runtime call the `nullSafety()` method once before invoking `main`. True for "strong mode" false for "weak mode". If you don't call it the app will default to weak mode.

https://github.com/dart-lang/sdk/blob/eb3a42b789289be08988be7b31e34cf7b0ab0709/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart#L20

As some examples here we do it in the 
* [ddc sandbox script](https://github.com/dart-lang/sdk/blob/eb3a42b789289be08988be7b31e34cf7b0ab0709/pkg/dev_compiler/tool/ddb#L272)
* [SDK test runner](https://github.com/dart-lang/sdk/blob/eb3a42b789289be08988be7b31e34cf7b0ab0709/pkg/test_runner/lib/src/browser.dart#L235)

**Comment by RedBrogdon** [comment]
Thanks for the info.

There are a couple places where a "main" is invoked by DartPad. There's a bootstrap file compiled with the user's code by DDC:

https://github.com/dart-lang/dart-services/blob/6b0fe072fd1fa9e5b6c2f58309d5e1bfa51aa455/lib/src/common.dart#L24

And then we have another "bootstrap" moment in which the browser's JS loads the module from the server and executes it:

https://github.com/dart-lang/dart-pad/blob/dec98cbb2e84a931b46d403ba54acbe8c204080a/lib/services/execution_iframe.dart#L179

We can add code at either place. Both your examples show the call being made from JS, though, rather than other Dart code. Is the second of those two links, therefore, the smarter place for us to invoke `nullSafety`?

**Comment by nshahan** [comment]
Sorry my response there wasn't entirely clear. The linked Dart method will be present in the Dart SDK JS module and has to be called from JS before you run the main method for the application. It is defined in an SDK private library so you won't be able to call it from dart code unless you have some SDK hacks to allow a package to import it.

**Comment by vsmenon** [comment]
So, we'd need to add line in the dartpad bootstrap here:

https://github.com/dart-lang/dart-pad/blob/dec98cbb2e84a931b46d403ba54acbe8c204080a/lib/services/execution_iframe.dart#L156

like `dart_sdk.dart.nullSafety(true)`, right?

**Comment by nshahan** [comment]
Exactly.

**Comment by RedBrogdon** [comment]
Got it. I have this and a couple other null safety issues on my plate I'll try to bundle into a release.

**Comment by vsmenon** [comment]
I think this is just another instance of this bug ( @leafpetersen ?), but the following prints `null` instead of a runtime error:

```dart
void printNonNullable(Object x) {
  print(x);
}

void printNullable(Object? x) {
  if (x != null) printNonNullable(x);
}

void main() {
  // Static error
  // printNonNullable(null);
  // Should be runtime error
  printNonNullable(null as dynamic);
}
```

**Comment by vsmenon** [comment]
Interestingly, the Chrome devtools console (not the one on the main screen) shows runtime weak mode warnings when I run the above:

```
dart_sdk.js:4797 Null is not a subtype of Object.
This will become a failure when runtime null safety is enabled.
dart_sdk.js:4797 A null value was passed into a non-nullable parameter x
This will become a failure when runtime null safety is enabled.
```

**Comment by nshahan** [comment]
If you are getting those warnings in the console, then the app is still running in weak mode. Those warnings should be thrown as errors in strong mode.

**Comment by leafpetersen** [comment]
Clarification question based on discussion today.  Do we intend for nullsafety.dartpad.dev to support running both strong and weak mode programs?  That is, I think we can agree that if the user types the following program into nullsafety.dartpad.dev it should run in strong mode:

```dart
void main() {
  if (<int?>[] is List<int>) {
    print("Weak mode! :(");
  }
}
```

But what do we intend to happen if the user types the following?

```dart
// @dart=2.7
void main() {
  if (<int?>[] is List<int>) {
    print("Weak mode! :(");
  }
}
```

- One option is to say that all programs in nullsafety.dartpad.dev are run with strong mode explicitly enabled (that is, the harness passes --sound-null-safety)
  - In this case, this second program is an error
  - In this case, [DDC auto mode detection](https://github.com/dart-lang/sdk/issues/41209) issue is not a blocker for this issue (and hence for TP1)
- Another option is to say that strong mode should be chosen based on entry point status
  - In this case, this second program runs in weak mode
  - In this case, [DDC auto mode detection](https://github.com/dart-lang/sdk/issues/41209) issue is a blocker for this issue (and hence for TP1)

FWIW I'm inclined towards the first option, at least for TP1.  I don't see a lot of benefit to users to letting them play with weak mode in dartpad at this point of the roll out.

cc @mit-mit @franklinyow @vsmenon

**Comment by vsmenon** [comment]
Your first option sounds sensible to me as well.  Regardless, I don't think weak mode support needs to block TP1.

**Comment by sigmundch** [comment]
At our web compilers team sync up this morning we also discussed this and our preference was option 1 as well.

**Comment by mit-mit** [comment]
Definitely option 1 for TP1; actually I'd go further and say that nullsafety.dartpad.dev should always be using *only* sound null safety. 

Even once we launch, and put null safety support in the regular dartpad.dev, I think we might want to limit that to sound only also.

**Comment by franklinyow** [comment]
@RedBrogdon Seems like our team strongly prefer option 1.  WDYT?

**Comment by RedBrogdon** [comment]
SGTM -- I definitely prefer the simpler approach.

I'm in the middle of updating the code for the next version. Right now I'm using the call in the place @vsmenon suggested, and this code:

```dart
void main() {
  if (<int?>[] is List<int>) {
    print("Weak mode! :(");
  } else {
    print('Strong mode, yo!');
  }
}
```

Prints the strong mode message. I need to find the correct way to avoid calling `nullSafety` on each execution (since it throws if called more than once), but even with that, I think this will be ready in the coming week.

**Comment by franklinyow** [comment]
Ready to close?

**Comment by franklinyow** [comment]
Looks like it working at https://nullsafety.dartpad.dev/
Closing
