### ISSUE TITLE
in null safe dartpad, exception messages don't propagate to console

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dart-pad#1553]
This may be a more general issue, but just trying on the null safe version right now:

This:
```dart
void main() {
  late int x;
  
  if (3 > 4) {
    x = 4;
  }
  print(x);
}
```

just triggers:
```
Script error.
```

If I wrap in a try-catch, I can see the underlying error is:

```
LateInitializationError: Local 'x' has not been initialized.
```

Can we propagate that to the console?

**Comment by RedBrogdon** [comment]
Should be something I can do. We've gone back and forth on how to report exceptions and runtime errors in the console. Given that the null safety version is a special case, more info seems better.

**Comment by RedBrogdon** [comment]
This has been fixed in the most recent deployment. Runtime exceptions and errors are now propagated to the console in glorious red text.
