### ISSUE TITLE
Show web content checkbox does not apper

### ISSUE THREAD

**Issue by supermuka** [dart-lang/dart-pad#1562]
For Web pure html/css and AngularDart developers is important to have the web content option.

In previous Dartpad release there was this option. 

See documentation: [Dartpad](https://dart.dev/tools/dartpad)

Please, return this option again!

**Comment by RedBrogdon** [comment]
You're correct that the checkbox for showing web content is not in the current design. You can still create HTML/CSS/Dart examples, though. Just click the "New Pad" link at the top of the page, and when you select "Dart," flip the switch for HTML:

![image](https://user-images.githubusercontent.com/969662/84555968-a1740180-acd4-11ea-9c6c-beba9d9849d5.png)

You'll get the same three-editor experience you're used to.
