### ISSUE TITLE
Is Dart a Stupid Language or I am not getting it properly (Functions as 1st-class objects)

### ISSUE THREAD

**Issue by revenantcoder** [dart-lang/dart-pad#1564]
Hello Everyone,

**Functions as first-class objects**

  ```
void printElements(int x) {
    print(x);
  }
  var mylist = <int>[1, 2, 3];
  print(mylist.runtimeType);
  mylist.forEach(printElements);
```

Output: JSArray`<int>` 1 2 3 
(works perfectly fine (though i dont know why JSArray`<int>` instead of List`<int>`)

**Problem occurs when i change var to List** 
  ```
List mylist = <int>[1, 2, 3];
  print(mylist.runtimeType); //runtimeType is still the same JSArray<int>
  mylist.forEach(printElements); //now this statement is giving Error.
```

**Error**: The function 'printElements' has type 'void Function(int)' that isn't of expected type 'void Function(dynamic)'. This means its parameter or return type doesn't match what is expected 

I don't know why this statement is giving error when the runtimeType is same in both the cases.

Thanks and regards, 
Amit Verma

**Comment by rrousselGit** [comment]
Change:

List mylist = <int>[1, 2, 3];


Into:


List<int> mylist = <int>[1, 2, 3];

**Comment by revenantcoder** [comment]
@rrousselGit Thanks buddy this solves the problem.. but actually what happened behind the scene
by adding List` <int> `  because the runtimeType was same in both the cases.

**Comment by revenantcoder** [comment]
https://github.com/dart-lang/sdk/issues/42032#issuecomment-633074602
