### ISSUE TITLE
Documentation on nullsafety.dartpad.dev contains legacy type signatures

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dart-pad#1569]
The docs that appear in the documentation pane for classes and constructors from the SDK all contain legacy types. 

Repro code:
```dart
var fame = Duration(minutes: 15);
```

Click to place your cursor on the Duration constructor. The documentation pane contains a signature showing all legacy types with the stars. These should all be non-nullable: 

```
(new) Duration* Duration({int* days = 0, int* hours = 0, int* minutes = 0, int* seconds = 0, int* milliseconds = 0, int* microseconds = 0})
Creates a new Duration object whose value is the sum of all individual parts.
```

**Comment by nshahan** [comment]
cc @stereotype441 @pq @jwren 
It sounds like these might be coming from the analysis server?

**Comment by jwren** [comment]
@bwilkerson @scheglov

**Comment by scheglov** [comment]
Analysis Server outside of DartPad shows correct non-nullable signatures.

So, it might be something related to how DartPad configures its analysis context.

Note, that if the analysis context does not have `non-nullable` experiment enabled, then it is considered a legacy library, and all Null Safety elements are converted back into legacy elements when imported into a legacy library.

![image](https://user-images.githubusercontent.com/384794/83559430-6b12d700-a4c9-11ea-8fec-8fcee131ea82.png)
![image](https://user-images.githubusercontent.com/384794/83559524-91d10d80-a4c9-11ea-8df6-724db22e317f.png)

**Comment by RedBrogdon** [comment]
This is the initialization code through which the server is spun up: 

https://github.com/RedBrogdon/dart-services/blob/nnbd/lib/src/analysis_server.dart#L55

It's using the non-nullable experiment flag along with some others.

The SDK path given to the wrapper points to a local install of a custom build of the Dart SDK (you can grab a Linux build [off our Cloud Storage server](https://storage.googleapis.com/nnbd_artifacts/2.9.0-0.0-custom/dartsdk-linux-x64-release.zip)).

I'll keep poking at this, but any advice you can provide, @scheglov, is much appreciated.

**Comment by scheglov** [comment]
Do you have `.dart_tool/package_config.json` in the packages that you analyze with the analysis server? If you do, and it specifies a language version other than `2.9`, then any enabled experiments are discarded.

**Comment by RedBrogdon** [comment]
This has been corrected in today's release! Thanks to those who reported it and/or offered advice on fixing it. 😄
