### ISSUE TITLE
Dartpad type error not pretty

### ISSUE THREAD

**Issue by treeplate** [dart-lang/dart-pad#1571]
The `

In Dartpad, I run this code:
```
class A	{
  final A a = null;
}

void main() {
  var x = new A();
  print(x.a.a);
}
```
Expected result (and what other things do):
```

Unhandled exception:
NoSuchMethodError: The getter 'a' was called on null.
Receiver: null
Tried calling: a
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
dart-lang/sdk#1      main (main.dart:7:13)
dart-lang/sdk#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
dart-lang/sdk#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Command exited with non-zero status 255
```

Actual result:
```
Uncaught TypeError: Cannot read property 'get$a' of nullError: TypeError: Cannot read property 'get$a' of null
```

...which is both less informative and less pretty.

**Comment by domesticmouse** [comment]
Hi @vsmenon,

I'm curious what you would like us to do here, as the above code is successfully compiled by the dart compiler to JS, but the generated JS is broken, unless I miss my guess.

/cc @devoncarew if you have any clues what else we can do

**Comment by vsmenon** [comment]
@domesticmouse - I sent it this way to triage / prioritize.  The stack trace is what I'd expect from dart2js.

Some options:
- Reassess after null safety - the above will fail statically.
- Switch to DDC (which we're using for null safety pad) for better error messages.  It may not run as well on some devices though.
- Show the stack trace / line numbers?

@sigmundch - if Dart2JS, is there any further deobfuscation DartPad could use?

**Comment by sigmundch** [comment]
>...  is there any further deobfuscation DartPad could use?

Yes. Even if the stack trace is not minified, there is value in using it (both to translate error line locations, but also to translate error messages (to replace 'a' for `get$a`).

Happy to provide more pointers if needed.

**Comment by johnpryan** [comment]
This is now printing normally:

```
Error compiling to JavaScript:
Info: Compiling with sound null safety
lib/main.dart:2:15:
Error: The value 'null' can't be assigned to a variable of type 'A' because 'A' is not nullable.
 - 'A' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
  final A a = null;
              ^
Error: Compilation failed.
```
