### ISSUE TITLE
nullsafety.dartpad.dev seems to swallow dynamic errors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart-pad#1573]
## What happened?

The dartpad with null safety seems to swallow dynamic errors. In particular, a run-time error does stop the execution, but (as far as I can see) there is no feedback to the user that anything went wrong. I would have expected something like an error message and a stack trace.

## Steps to reproduce problem 

Consider the following program:

```dart
main() {
  print("Starting!");
  var x = (true as dynamic).isEven;
  print("Done");
}
```

On https://nullsafety.dartpad.dev/ as of June 5th 2020, this produces the following console output:

```
Starting!
```

and nothing else (in the console, documentation, nor at any other UI location).

### Browser

Browser: Chrome

Version: 83.0.4103.61.

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below: N/A

### Machine

Operating system: MacOS

Version: 10.15.5

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
main() {
  print("Starting!");
  var x = (true as dynamic).isEven;
  print("Done");
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
Starting!
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report: N/A.

**Comment by RedBrogdon** [comment]
Thanks for filing this (and for being one of the very few people who provided all the details the template asks for!).

It looks like you might have run into the same issue as #1553.

I just pushed an update to https://nullsafety.dartpad.dev that includes a fix for that issue as well as a few others. The code you included:

```dart
main() {
  print("Starting!");
  var x = (true as dynamic).isEven;
  print("Done");
}
```

Now produces this output in the console:

```
Starting!
Error: NoSuchMethodError: 'isEven'
```

I'm going to close this, but let me know if there's work still to do.
