### ISSUE TITLE
Bad console messages in embedded DartPads

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#1574]
I see an unhelpful message like this when I try to run code — in the embedded version of either regular or null-safe DartPad — that fails static analysis:

```
Error compiling to JavaScript:
Instance of 'minified:fC'
```

Instead, I'd expect the message that I get when I paste the code into https://nullsafety.dartpad.dev:

```
Error compiling to JavaScript:
/tmp/dartpadDDVQMH/main.dart:4:33: Error: Non-nullable variable 'anInt' must be assigned before it can be used.
  print('The value of anInt is $anInt.');
                                ^^^^^
```

To reproduce:

1. Go to https://kw-staging-dartlang-2.firebaseapp.com/null-safety#creating-variables.
2. Scroll down to the first DartPad (just after **analyzer can determine**).
3. Comment out line 3. (You'll see an error appear.)
4. Click **Run**.

I see a similar issue when I change `var` to `int` in line 4 of the example at https://dart.dev/codelabs/async-await#example-incorrectly-using-an-asynchronous-function:

```
Error compiling to JavaScript:
Instance of 'minified:h_'
```

Just to make sure it wasn't somehow associated with inject_embed, I checked the Dart cheatsheet codelab. I still see the problem when I return a `1` from `stringify()` in https://dart.dev/codelabs/dart-cheatsheet#code-example.

**Comment by RedBrogdon** [comment]
We've got several issues like this relating to error messages. We should bundle them up and make a sweep of it.

**Comment by gerardsimons** [comment]
I am having this on this example page with Firefox, Safari and Chrome on Mac OS Big Sur

https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html

**Comment by subzero911** [comment]
Same here:
![image](https://user-images.githubusercontent.com/12999702/110013852-2dcac680-7d33-11eb-8665-fd6550fa1e1c.png)

**Comment by OOTPAppsDotCom** [comment]
New to Dart, trying to learn syntax and this error is occuring for any syntax error on the official Dart cheatsheet codelab's dartpads:
[https://dart.dev/codelabs/dart-cheatsheet](https://dart.dev/codelabs/dart-cheatsheet)

Better error reporting would make my learning experience much more seemless.

**Comment by johnpryan** [comment]
This is fixed, feel free to comment if you are still seeing incorrect messages like  this:

```
Error compiling to JavaScript:
Instance of 'minified:fC'
```
