### ISSUE TITLE
Error in Queue class fails silently

### ISSUE THREAD

**Issue by craiglabenz** [dart-lang/dart-pad#1575]
## What happened?

The following code snippet produces no output of any kind:

```dart
import 'dart:collection';

main() async {
  final queue = Queue<String>.from(null);
  print('**${queue.first}**');
}
```

## Additional info

But the console says:

```
VM108:342 Uncaught TypeError: C.JSNull_methods.get$iterator is not a function
    at Object.ListQueue_ListQueue$from (<anonymous>:2876:36)
    at <anonymous>:3100:25
    at _wrapJsFunctionForAsync_closure.$protected (<anonymous>:2324:15)
    at _wrapJsFunctionForAsync_closure.call$2 (<anonymous>:3492:12)
    at Object._asyncStartSync (<anonymous>:2269:20)
    at Object.main (<anonymous>:3117:16)
    at <anonymous>:4335:9
    at <anonymous>:4319:7
    at dartProgram (<anonymous>:4330:5)
    at <anonymous>:4337:3
```

Ultimately, two possible issues here.

1 - Uncaught errors should maybe trigger a snackbar, or some such alert.
2 - Dart's JavaScript Queue class seems to have a null check issue.

**Comment by RedBrogdon** [comment]
DartPad should trap and report runtime exceptions. At least that's the expectation. :)

This is what I'm seeing in the UI when running that code:

![image](https://user-images.githubusercontent.com/969662/84556426-94a4dd00-acd7-11ea-90aa-05a5dc9da095.png)

Was the righthand console staying blank when you ran the code? Or were you using an embedded layout? Either way, I'd love to know if there were any other errors in the console (and what browser/OS you're on).

**Comment by craiglabenz** [comment]
Apologies - I somehow missed your reply. I am currently seeing the same thing you're seeing, so I'm not sure what my exact experience was back when I filed this. My memory of it is that Dartpad silently failed and I had to dig for the reason why "nothing was happening" - maybe somehow I had collapsed the console?

Either way, seems correct to keep this closed.

**Comment by craiglabenz** [comment]
Undoing the no-response bot's automatic re-open.

**Comment by NANASHI0X74** [comment]
A heads up: I had a similar bug on brave where an exception wasn't printed in the dartpad console but in the javascript console. Reloading and disabling and then reenabling some extensions then fixed the issue. I was in the middle of filing a bug report but then decided against it since I couldn't reproduce the issue :p
