### ISSUE TITLE
Assertion errors print poorly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dart-pad#1580]
The following code:

```dart
class JS {
  final String name;
  const JS([this.name]);
}

void main() {
  print(JS());
}
```

triggers this runtime error on the console:

```
Error: Assertion failed: file:///tmp/dartpadKBZCRA/main.dart:4:18
```

If break in the devtools debugger, it appears that:

(a) the entire error is:

```
Error: Assertion failed: file:///tmp/dartpadKBZCRA/main.dart:4:18
name != null
"A null value was passed into a non-nullable parameter name"
```

(b) there is code is dartpad that truncates everything but the first line:

```
              var msg = error.toString().split("\n")[0];
              console.log(msg);
```

**Comment by johnpryan** [comment]
I'm marking this as a duplicate of https://github.com/dart-lang/dart-pad/issues/1966, where we are tracking issues related to assertion error messages.
