### ISSUE TITLE
Please add dartfmt just as I run

### ISSUE THREAD

**Issue by ride4sun** [dart-lang/dart-pad#1584]
Please add dartfmt just as I run - keeps it simple

**Comment by RedBrogdon** [comment]
I'm not sure this would be a good idea.

While there are definitely people who might appreciate it, there are those who prefer a different coding style than the default and might find it super annoying. It could also be jarring for new developers if they're not expecting their code to be reformatted at that time.

I'll leave this issue open for a bit to see if anyone would like to give it a thumb's up or down, though.
