### ISSUE TITLE
Unhelpful error message in declarations of final and const variables without a value

### ISSUE THREAD

**Issue by jjosenaldo** [dart-lang/dart-pad#1587]
In commands like `final x;`, `const x;`, `final int x;` and `const int x;`, the error message showed is `The final variable ';' must be initialized`. It isn't very helpful for those who are just starting to play with Dart, and even imply that `;` can be used as a variable's name. A better option could be something in the lines of `A const/var variable must have a value`.

**Comment by jjosenaldo** [comment]
Closing it as I realized that that actually has nothing to do with the dart-pad itself, ha

**Comment by domesticmouse** [comment]
Did you re-open this against `dart-lang/language`?

**Comment by jjosenaldo** [comment]
Just did that: dart-lang/language#1069

**Comment by domesticmouse** [comment]
thanks!
