### ISSUE TITLE
Const list element modification causes unhandled error in Dartpad

### ISSUE THREAD

**Issue by ngjuping** [dart-lang/dart-pad#1588]
## What happened?
I tried to run some code to test if I can change the content of a const list, but code stopped running after the line containing code:
``` arr[0] = 3; ```

## Steps to reproduce the problem
Please run the code below in Dartpad 
```
void main()
{
  const List<int> arr = [1,2,3];
  arr[0] = 3;
  
  for (var i=0 ; i<3 ; i++)
  {
      print('hi');
  }
  
}
```
### Browser

Browser: Google Chrome

Version: Version 83.0.4103.116 (Official Build) (64-bit)

### Are you using any extensions/plugins that affect website behavior (particularly those that affect iframes, such as ad blockers)? 
Yes, adblocker used, but I feel like they don't matter on my issue.

### Are there any warnings or errors in your browser's JavaScript console?
Yes.

```
Uncaught Unsupported operation: indexed set
    at Object.wrapException (<anonymous>:324:17)
    at Object.throwExpression (<anonymous>:337:15)
    at Interceptor.$indexSet (<anonymous>:2108:11)
    at Object.main (<anonymous>:2067:25)
    at <anonymous>:2416:9
    at <anonymous>:2400:7
    at dartProgram (<anonymous>:2411:5)
    at <anonymous>:2418:3
    at replaceJavaScript (https://dartpad.dev/scripts/frame_dark.html:38:27)
    at messageHandler (https://dartpad.dev/scripts/frame_dark.html:54:17)
```

### Machine

Operating system: Windows 10 Home Single Language

Version: 1903

### Your code

What code was in the editor, if any, when the failure occurred? 

```
void main()
{
  const List<int> arr = [1,2,3];
  arr[0] = 3;
  
  for (var i=0 ; i<3 ; i++)
  {
      print('hi');
  }
  
}
```

### DartPad's output

Nothing.
```

```

**Comment by domesticmouse** [comment]
When I ran this in DartPad I saw the following in the console output:

<img width="453" alt="Screen Shot 2020-07-11 at 7 30 32 am" src="https://user-images.githubusercontent.com/30503/87204538-723ec780-c348-11ea-884e-810ae478f3cd.png">

For comparison, here is the Dart VM's output:

```
Unhandled exception:
Unsupported operation: Cannot modify an unmodifiable list
#0      UnmodifiableListMixin.[]=  (dart:_internal/list.dart:90:5)
#1      main   bin/issues_1588.dart:3
#2      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by RedBrogdon** [comment]
@ngjuping, I'm seeing the same error as @domesticmouse. Do you mind giving this another try to see if it was a one-time thing or if there's any additional information you could give us?

**Comment by bizz84** [comment]
@RedBrogdon I have tested this and also see the same error as @domesticmouse.

Either way, shouldn't the compiler produce a compile-time error for this kind of situation?

**Comment by domesticmouse** [comment]
@bizz84 discussions around what errors and warnings the compiler should produce would be better handled by raising an issue on https://github.com/dart-lang/language or https://github.com/dart-lang/sdk. 

This issue, AFAICT, is about making sure that DartPad correctly reflects compilation warnings and errors that the compiler produces.

**Comment by rakudrama** [comment]
The behaviour is correct.
```
const List<int> arr = [1,2,3];
```
is very similar to 
```
final arr = const <int>[1,2,3];
```
The `List` object is constant (immutable) and cannot be changed by `[]=`.
The name list (`arr`) in both cases is not assignable, which is what `const` does in JavaScript.
For the program to work, you would need to remove the `const`:
```
final List<int> arr = [1,2,3];
```
`[]=` is just another method on the `List` interface, like `.length` and `.toString()`, so there is no reason for the compiler to forbid calling it via `arr[0] = 3`.

**Comment by ngjuping** [comment]
Update: Sorry for late reply! I am seeing the same error @domesticmouse now, I think the case is considered resolved now. Thanks for everyone's effort on this minor mistake!

**Comment by domesticmouse** [comment]
Closing again, thanks @ngjuping 😁

**Comment by ynlvko** [comment]
Should it give a compile-time error? E.g. Kotlin has "List" and "MutableList" interfaces. Can we make something like this for Dart and check that only the "non-mutable" List can be assigned to a "const"?
