### ISSUE TITLE
Generate a useful error message when compiling incomplete or erroneous dart code.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/dart-pad#1589]
Page URL: https://dart.dev/codelabs/dart-cheatsheet.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/dart-cheatsheet.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

When I click 'run' for example in 'Cascades', I get error 'Error compiling to JavaScript: Instance of 'minified:fD''.

**Comment by johnpryan** [comment]
Duplicate https://github.com/dart-lang/dart-pad/issues/1574
