### ISSUE TITLE
Multiple end points breaks grind serve-custom-backend

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1591]
The code in https://github.com/dart-lang/dart-pad/pull/1581 needs to be updated to take into consideration if we are running under `grind serve-custom-backend`.

**Comment by domesticmouse** [comment]
And/or delete that `grind` target and replace it with a pointer to modifying `lib/services/common.dart`

**Comment by domesticmouse** [comment]
This is an issue in the `dart-lang/dart-pad` codebase, not `dart-lang/dart-services`.

**Comment by parlough** [comment]
This grind task no longer exists and I believe the backend can now be switched to a local version with a `channel=localhost` query parameter.
