### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by nbros** [dart-lang/dart-pad#1592]
## What happened?

I was playing with the "Sunflower" DartPad and got the following "Assertion failed" in the console.

## Steps to reproduce problem

I don't know

### Browser

Firefox 78.0.2

### Machine

Operating system: Windows 10

### DartPad's output

```
Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter/packages/flutter/lib/src/foundation/stack_frame.dart:113:12
match != null
"Expected DartError@https://storage.googleapis.com/compilation_artifacts/2.9.0-14.1.beta/dart_sdk.js:6079:7 to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."Error: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter/packages/flutter/lib/src/foundation/stack_frame.dart:113:12
match != null
"Expected DartError@https://storage.googleapis.com/compilation_artifacts/2.9.0-14.1.beta/dart_sdk.js:6079:7 to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."
```

**Comment by domesticmouse** [comment]
@RedBrogdon is this the result of the name format change in Dart releases tripping up the masking regex?

**Comment by RedBrogdon** [comment]
Yes, this is the "failure to report error messages correctly" issue we've already got on the books (which still needs to be fixed).

See #1574, #1580, and a half-dozen others. Since we don't have the exact code here, I'm going to close this issue as a duplicate.
