### ISSUE TITLE
Typo in last null-safe snippet

### ISSUE THREAD

**Issue by miDeb** [dart-lang/dart-pad#1597]
Sorry if this is not the right place to report this, also I wasn't able to find the source code for the snippets. https://github.com/dart-lang/dart-pad/blob/master/CONTRIBUTING.md mentions https://github.com/dart-lang/dartpad_examples, which is archived. Anyway, in the [`late and lazy` snippet](https://nullsafety.dartpad.dev/88970173429a487e82caf8ccf949157e), the comment says 
```
// .... Initialization
// expressions for `late` fields **can use**
// **able to use** instance methods in their
// initializers.
```

**Comment by RedBrogdon** [comment]
Great catch, @miDeb, and thanks for letting us know! The code for those snippets is currently stored at:

https://gist.github.com/RedBrogdon/88970173429a487e82caf8ccf949157e

I've updated it to fix the typo.
