### ISSUE TITLE
Run the solution when it's selected

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1601]
When the solution tab is selected, clicking the run button runs the Dart code. Instead, we should run solution: https://github.com/dart-lang/site-www/issues/2539

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the exercise functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
