### ISSUE TITLE
keeps failing running on ubuntu bionic

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1603]
```
ubuntu@ip-XXXXXXX:~/dart-pad$ grind serve
grinder running build serve

build
  /usr/lib/dart/bin/pub run build_runner build -r -o web:build
  [INFO] Generating build script...
  [INFO] Generating build script completed, took 600ms
  
  [INFO] Creating build script snapshot......
  [INFO] Creating build script snapshot... completed, took 25m 41s
  
  [SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
  This is likely caused by a misconfigured builder definition.

failed with exit code 78
#0      run (package:grinder/src/run.dart:48:5)
#1      Pub.run (package:grinder/grinder_sdk.dart:241:12)
#2      _PubLocalApp.run (package:grinder/grinder_sdk.dart:593:16)
#3      build (file:///home/ubuntu/dart-pad/tool/grind.dart:132:32)
#4      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1093:36)
#5      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:244:25)
#6      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:77:38)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
#12     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
#13     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#14     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#15     Future.forEach.<anon> (dart:async/future.dart:494:26)
#16     Future.doWhile.<anon> (dart:async/future.dart:536:26)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#18     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1413:26)
#19     Future.doWhile (dart:async/future.dart:551:18)
#20     Future.forEach (dart:async/future.dart:492:12)
#21     Grinder.start (package:grinder/src/grinder.dart:167:21)
#22     runTasks (package:grinder/src/cli.dart:67:38)
#23     grind (package:grinder/grinder.dart:46:12)
#24     main (file:///home/ubuntu/dart-pad/tool/grind.dart:23:28)
```

what do i do? runs well on macos

**Comment by domesticmouse** [comment]
Attempting to run Dart Pad on Ubuntu 18.04 is failing. Any ideas @johnpryan?

**Comment by RedBrogdon** [comment]
What `build_runner`-dependent packages are used in dart-pad? IIRC, there's `shelf_route_generator`, but I thought that was it.

Is it possible a dependency is out of date, and we could fix this with `pub outdated` and some edits?

**Comment by johnpryan** [comment]
Yeah I would like to see if `pub upgrade` fixes it.

**Comment by softmarshmallow** [comment]
@johnpryan  didn't work. though does grinder has internal timeout system for the build time? that running it on aws ec2 micro throws that error, but bumping the instance size to medium, now it works. odd...

**Comment by domesticmouse** [comment]
It's going to require 4 gig of ram for the Dart compiler to work correctly. Without sufficient RAM, things go sideways.

**Comment by softmarshmallow** [comment]
is it by design? then how could dart be used for micro services, etc..? (i know its not the right place to ask but ..)

**Comment by domesticmouse** [comment]
Compilers are memory hungry these days, especially when compiling the Flutter library. 

Back in the bad old days, compilers dealt with low memory situations by doing things like requiring all functions be pre-declared before usage (hello C/C++) and requiring variables to be declared at the top of the function. Pascal was designed to be a single pass compilation to reduce memory pressure. None of these language constraints apply to modern languages, which keep everything in memory while compiling.

So, yeah, it's by design. I'm curious what you are attempting to compile in a microservice?

**Comment by softmarshmallow** [comment]
msa was just an example for making my point. thanks for helping me out!
