### ISSUE TITLE
Uncaught TypeError: self.checkLocalStorage is not a function

### ISSUE THREAD

**Issue by awulkan** [dart-lang/dart-pad#1605]
## What happened?

I tried to open DartPad in Chrome, but an error prevented it from loading properly.
Error is specified below.

## Steps to reproduce problem

1. Go to https://dartpad.dev/
2. Check the console output.
The page is not usable since it doesn't load completely.
This is reproducible.

### Browser

Browser: Chrome

Version: 84.0.4147.105 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

I have tried disabling ad blocker (uBlock Origin), but it didn't help.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Uncaught TypeError: self.checkLocalStorage is not a function
    at kU.jS (playground.dart.js:11839)
    at Object.DB (playground.dart.js:5251)
    at Object.AK (playground.dart.js:5409)
    at playground.dart.js:17417
    at playground.dart.js:17412
    at dartProgram (playground.dart.js:17415)
    at playground.dart.js:17417
```

### Machine

Operating system: Windows 10 Home

Version: 2004

### Your code

No code.

### DartPad's output

None.

**Comment by domesticmouse** [comment]
I suspect this might have something to do with https://github.com/dart-lang/dart-pad/pull/1604 =)

**Comment by johnpryan** [comment]
Might need to do some cache-busting. https://dart-pad.appspot.com/ is working for me.

**Comment by johnpryan** [comment]
Rolling back for now.

**Comment by awulkan** [comment]
Yep, now it works @johnpryan. Should I close the issue?

**Comment by domesticmouse** [comment]
Closing this out, due to roll back

**Comment by johnpryan** [comment]
https://github.com/dart-lang/dart-pad/pull/1606 was also to help mitigate
