### ISSUE TITLE
Runtime errors not printed on console on nullsafety.dartpad.dev

### ISSUE THREAD

**Issue by bizz84** [dart-lang/dart-pad#1607]
## What happened?

This simple program should print an error to the console (on [nullsafety.dartpad.dev](https://nullsafety.dartpad.dev/), using  Dart SDK `2.9.0-edge.2ed302bfbbbad1d10f6c839c504ae3871fc96dc2`):

```dart
void main() {
  int? maybeValue;
  int value = maybeValue!; 
  print(value);
}
```
However, running the program results in an empty console output.

## Steps to reproduce problem

Paste the code above to [nullsafety.dartpad.dev](https://nullsafety.dartpad.dev/) and run the program.

### Browser

Browser: Google Chrome 

Version: 84.0.4147.89 (Official Build) (64-bit)

(same happens on Firefox)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Error: NoSuchMethodError: '<Unexpected Null Value>'
DevTools failed to load SourceMap: Could not load content for https://nullsafety.dartpad.dev/main.dart.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Machine

Operating system: macOS Catalina

Version: 10.15.5

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```dart
void main() {
  int? maybeValue;
  int value = maybeValue!; 
  print(value);
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```

```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by creativecreatorormaybenot** [comment]
It does print a runtime error for me:

```
Error: NoSuchMethodError: '<Unexpected Null Value>'
```

**Comment by bizz84** [comment]
Turns out I had a CORS extension enabled. Removing it from my browser fixed the issue.
