### ISSUE TITLE
Dartpad not displaying output of flutter

### ISSUE THREAD

**Issue by hulcon** [dart-lang/dart-pad#1608]
Hi there. I have been trying to use dartpad and it works fine for dart code. But if i write some flutter code or choose a flutter sample, it simply doesn't display any output. There are no errors either in the browser console or in the dartpad console. I checked network requests and return 200. I am using Lubuntu with Firefox 78.0.2 (latest version). I am also facing similar problem on my Windows 10 machine with both Firefox and Google Chrome latest versions. I have been looking around for solutions but i couldn't find any for days. The problem is that no errors are displayed. After i press the run button, the request is completed but the output stays blank in case of flutter code. Dart code just runs fine. I have already disabled tracking protection etc. of the browsers for dartpad site. I thought maybe that might be causing the problem. But the problem still persists. Can somebody please point out if i am missing something or is this an issue with the dartpad itself? I encountered some questions regarding the same issue but they had some errors printed on the console. But my case is different. No errors are displayed and the network requests are completed gracefully.
![image](https://user-images.githubusercontent.com/28725843/89093683-1cef5680-d3da-11ea-853e-584068d81d03.png)
As far as i know, there are no prerequisites  for dartpad to function properly. So what can possible be wrong or is it a specific dartpad issue?

**Comment by domesticmouse** [comment]
Hey @hulcon,

Can you please help us out here with the sample code that you are asking DartPad to compile, and the console log containing any error messages? The `compileDDC` request/response you have highlighted appears to have succeeded...

brett

**Comment by hulcon** [comment]
Thank you for response @Brett. I am trying to compile the builtin flutter examples (the flutter counter example). There are no error messages in the console. The console is blank and so is the output window.
![image](https://user-images.githubusercontent.com/28725843/89145639-00d0ee00-d56f-11ea-86d0-17310f3ef6ff.png)
But once in a while (if i press the run button consecutively 10 or more times), i get the following error message:
![image](https://user-images.githubusercontent.com/28725843/89145843-8d7bac00-d56f-11ea-8cf3-b814ee2e4d54.png)
Other than that, there are no error messages and the requests are completed successfully. I am puzzled as to what am i missing here. I am using Firefox on Lubuntu. Out of curiosity, i updated (upgraded) the whole system as i suspected some outdated software/library may be the cause but even after doing a full system update the issue persists. Coincidentally, i am facing the exact same issue on my Windows 10 machine also. However, the issue does not exist on my other Windows machine. Surprisingly, if i boot a live image of Lubuntu from a "Live Pendrive" and disable the browser tracking protection, the site works perfectly!! However, disabling browser tracking protection in my installed version of Lubuntu doesn't make any difference. I am completely puzzled!

**Comment by domesticmouse** [comment]
The load timeout for `dart_sdk` and `flutter_web` is concerning, because those are coming off of our blob storage. I'd start debugging your network, it might have some issues somewhere between your computer and the data center in the US of A...

**Comment by hulcon** [comment]
I have now installed Google Chrome browser and i am getting the following in the browser console:
![image](https://user-images.githubusercontent.com/28725843/89157423-215a7180-d58a-11ea-8f62-7491f8e688fc.png)
I am unable to understand why these requests are getting 404. Any suggestions?

**Comment by domesticmouse** [comment]
Sourcemaps aren't loading because we don't include the transforms from the original Dart and the generated JavaScript for the DartPad webapp. This is by design. The issue is the failure to load the `dart_sdk` and the `flutter_web` files. Without them, nothing works.

**Comment by brett** [comment]
@hulcon: @brett is not @domesticmouse.

**Comment by hulcon** [comment]
Sorry, my bad. I meant @domesticmouse

**Comment by domesticmouse** [comment]
@hulcon Have you had any success on debugging your network connection w.r.t. the download of `dart_sdk` and `flutter_web`? I can't debug this error from the serverside.

**Comment by hulcon** [comment]
@domesticmouse I don't exactly know how to do that! Any help regarding that would be appreciated. But i have done some rudimentary digging and found a few things. 
![image](https://user-images.githubusercontent.com/28725843/89256969-e8320800-d642-11ea-95b8-10bfdb4d5397.png)

First and the foremost, i didn't know that the dart_sdk and flutter_web are around some 9MB and 17MB respectively! That makes a difference in my case because the Internet speed in our region (Jammu and Kashmir) is throttled to a maximum of 400kbps. And downloading around 26 MB must be a pain for the browser on a 400kbps connection! I hadn't considered this factor earlier as i didn't know the size of these js files and also because one of my Windows machine was able to do the task on the same network. Now this does make sense. My Windows machine must have cached these files earlier sometime. Coming back to my Linux (Lubuntu) machine, i installed the Google Chrome browser and was facing the same problem. Coincidentally, i kept the browser open for around an hour (after pressing the run button on flutter code in the dartpad) and when i reloaded the page and it worked! It finally displayed Flutter output! That did surprise me and i tried the same thing with Firefox but i repeatedly failed. Till now i hadn't actually looked into the networking tab of developer console. I had been just looking at the console and the requests. Thank you for guiding me to look into network issue. I didn't know where to start from so i decided to take a look at the network tab of the developer console. Now after looking at the network activity, i finally do think i have an idea of what was happening. So the browser was unable to download the required js files which are huge (as far as Internet speed in our region is concerned!). I tried to resend the requests for those files but the requests never completed. I tried reloading and waiting for the requests to complete but every time i get the same amount of download (1.45 and 2.36) for those two js files even when after clearing cache. So somehow, though Google Chrome did manage to download these files over a stretched time frame, Firefox seems to give up on the request after sometime (or maybe the server forces it to do so?). **So is there any way to accommodate slower Internet connections like ours? Is there a way to manually download these files (dart_sdk and flutter_web) and dump these to the browser somehow?** Although i can do my work in Google Chrome now, but i am pursuing this issue so that someone else like me doesn't have to figure this out from scratch.

**Comment by domesticmouse** [comment]
Hey @vsmenon and @devoncarew,

Is it worth revisiting our decision to download the full Dart and Flutter SDK as precompiled JS? Would a full tree shake build be more bandwidth efficient for end users in constrained geographies?

brett

**Comment by vsmenon** [comment]
@sigmundch 

I think a dart2js build for a flutter sample takes ~25s, but produces less than 1MB total or similar.  Each edit would trigger another slightly different 1MB (as opposed to a few K).  The runtime errors would be harder to understand (since it's production code).

So, it'd be more bandwidth efficient on the initial run, but not necessarily after that.

**Comment by devoncarew** [comment]
Short term, I think we should validate that the dart_sdk.js and flutter_web.js are cached long term - stored on urls w/ their versions, and set to cache indefinitely.

Also note, while the compiled JS is large, the size to download should be the gzipped size (perhaps 7-10x smaller?).

**Comment by domesticmouse** [comment]
Looking at my Chrome console it looks like `dart_sdk.js` is 1.5mb and `flutter_web.js` is 2.5mb compressed.

We are picking up a `cache-control: public, max-age=86400,no-transform` header, which means browsers will only cache the files for a day.

**Comment by domesticmouse** [comment]
Thanks for the context @vsmenon, 25s is quite a long time and is probably a deal breaker.

**Comment by vsmenon** [comment]
@devoncarew 's suggestions sound like the best option then.

**Comment by mosesnjoroge19** [comment]
Hey @hulcon I had a similar problem as well. I tried reloading my dart pad page on firefox browser and it worked! I believe a page refresh fixed earlier issues. I hope it works for you and anyone else facing this issue
