### ISSUE TITLE
Missing Row number on dartpad ui

### ISSUE THREAD

**Issue by nu2dev** [dart-lang/dart-pad#1609]
It would be a better Ux with row numbers shown on the dartpad code window. While the errors mention the row number UI is missing the row numbers. shown visually on dartpad
![image](https://user-images.githubusercontent.com/49729758/89301021-aaad9900-d69b-11ea-9a28-529e15000f3f.png)

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @nu2dev! There's actually an outstanding feature request for this: #317.
