### ISSUE TITLE
Adding () to completion of functions and methods and positioning caret

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#161]
I think is common behaviour of IDEs to automatically add () when autocompleting a function or method and then adjusting the caret position.

I tried to see how and if this is possible using codemirror, but there doesn't seem an option to do this easily.

**Comment by devoncarew** [comment]
As in `foo(^)`? Esp. it'll help save users typing, and improve discovery, for methods with non-optional args.

We'll probably out-strip what can be done with the codemirror code completion UI at some point, and have to go fully custom.

**Comment by kasperpeulen** [comment]
Yeah, so when completing a method or a function `foo` with at least one argument it should complete as: `foo(<caret>)`

I'm now thinking that, if there is no argument of the function, we can already easily complete the function as `foo()<caret>`. Shall I add that to my latest pull request ?

**Comment by lukechurch** [comment]
I'd prefer it as a separate PR if you're ok with that, lots of small PRs are easier to review and merge

**Comment by kasperpeulen** [comment]
@lukechurch I understand, the reason I asked is because that pull request would need the parameter getter that I added in my last pull request.

**Comment by lukechurch** [comment]
@kasperpeulen Ah yes, I see.

For this kind of thing you can fork your branch from the branch the PR is issued from. It usually does the right thing, esp if there are only a reasonably low probability of conflict.

Anyhow, looking forwards to the next PR

**Comment by kasperpeulen** [comment]
@lukechurch  see: https://github.com/dart-lang/dart-pad/pull/163

**Comment by kasperpeulen** [comment]
fixed
