### ISSUE TITLE
Report test results to page containing embedded iframe

### ISSUE THREAD

**Issue by nicogenz** [dart-lang/dart-pad#1611]
Hey,

If you have an embedded DartPad injected with a github gist via iframe into your website, is there any way to check if the tests for the main.dart file where successful or erroneous, when the user clicks the run button? So the result can be used to be able to replace the dartpad iframe with something else for example.

Ty in advance

**Comment by domesticmouse** [comment]
I suspect the blocker is going to be that the DartPad generated content is run inside of a [sandbox `iframe`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox), and thus you can't get a notification from that iframe.

**Comment by RoXioTD** [comment]
@domesticmouse Do you have another idea to embed DartPad and get the result of the executed tests?

**Comment by domesticmouse** [comment]
@RoXioTD supporting this use case isn't currently on our roadmap, but I can see how it would be useful. 

/cc @RedBrogdon

**Comment by happyharis** [comment]
Would love to have this feature as currently building a learning platform for flutter/dart!

**Comment by RedBrogdon** [comment]
The execution iframe does send some messages out to the parent -- that's how we report test results to the outer iframe in our embedded layout: 

https://github.com/dart-lang/dart-pad/blob/master/lib/services/execution_iframe.dart#L92

We don't have anything that reports errors out to the page containing *that* iframe, though. As @domesticmouse mentioned, it's unlikely that we'd be able to get that on our roadmap in the near term (though our UXR team has asked for it). If you're interested, though, this is an open source project, and we're happy to take contributions. 😄

**Comment by parlough** [comment]
Thanks for the issue and suggestion!

As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, testing (and multi-file) support was removed.

If anyone would like to see similar functionality, please consider opening a new issue with your use case and goals. Thanks again :)
