### ISSUE TITLE
dartpad: Implement external and abstract variables

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart-pad#1614]
Cf. the [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/implementation-plan.md), the addition of external and abstract variables to Dart may require some updates.

https://github.com/codemirror/CodeMirror/blob/master/mode/dart/dart.js already recognizes `external` and `abstract` as keywords, so this might be working already.

**Comment by devoncarew** [comment]
Note: I believe this is mostly updating the codemirror syntax highlighting. @eernstg, is there some good sample code to test against? The files in https://github.com/dart-lang/sdk/tree/master/tests/language/external_abstract_fields?

**Comment by domesticmouse** [comment]
I tried https://github.com/dart-lang/sdk/blob/master/tests/language/external_abstract_fields/abstract_fields_test.dart and https://github.com/dart-lang/sdk/blob/master/tests/language/external_abstract_fields/external_fields_test.dart in https://dartpad.dev/ and they both appear to be rendering in [CodeMirror](https://codemirror.net/) as I'd expect.

If we need to make a change to CodeMirror's Dart parsing, we need to be aware that CodeMirror has a monthly release cadence (on the 20th, give or take), and I try to keep [codemirror.dart](https://github.com/google/codemirror.dart) updated on a timely basis.

**Comment by devoncarew** [comment]
I believe that if you see `abstract` and `external` highlighting as you'd expect in those files, then we're good w/o any codemirror updates (the VS Code and github grammer - https://github.com/dart-lang/dart-syntax-highlight/tree/master/grammars - did not need updating).

**Comment by domesticmouse** [comment]
Here's the `abstract` sample:

<img width="683" alt="Screen Shot 2020-08-19 at 1 47 52 pm" src="https://user-images.githubusercontent.com/30503/90589968-b6b06380-e222-11ea-815f-71f1fef10e4c.png">

And the `external` sample:

<img width="695" alt="Screen Shot 2020-08-19 at 1 48 35 pm" src="https://user-images.githubusercontent.com/30503/90589974-ba43ea80-e222-11ea-9c0d-0b41bf929cd1.png">

**Comment by eernstg** [comment]
> is there some good sample code to test against? The files in
> https://github.com/dart-lang/sdk/tree/master/tests/language/external_abstract_fields?

Exactly. Looks like it does work already!

**Comment by domesticmouse** [comment]
@eernstg is this safe to close, or do you want to wait on a null safety release with these features included?

**Comment by eernstg** [comment]
Depends on whether there is more dartpad specific work to do: The underlying tools (analyzer and compiler) have their own implementation tasks (https://github.com/dart-lang/sdk/issues/41940, https://github.com/dart-lang/sdk/issues/42718), and they are closed, so it seems likely that the only remaining work for dartpad is syntax highlighting.

**Comment by domesticmouse** [comment]
Assigning this to @RedBrogdon to bundle testing this with the next null safety update.

**Comment by leafpetersen** [comment]
Any updates on this?

**Comment by franklinyow** [comment]
Any update?
Thx

**Comment by franklinyow** [comment]
@RedBrogdon  What is the current status?

**Comment by mit-mit** [comment]
From https://github.com/dart-lang/dart-pad/issues/1614#issuecomment-675835503, it looks like this is already working?

**Comment by RedBrogdon** [comment]
AFAICT, abstract variables are working just fine:

https://nullsafety.dartpad.dev/e5ace6215b5779c9b41ae5a136a9c1fd

External variables are highlighted correctly and cause no analyzer errors, but will not compile. This code, for example:

```dart
external int something;
external String toString();

void main() {
}
```

Produces this error when compiled:

```
Error compiling to JavaScript:
main.dart:1:14:
Error: Only external js-interop functions are supported.
external int something;
             ^
main.dart:2:17:
Error: Only external js-interop functions are supported.
external String toString();
                ^
main.dart:1:14:
Error: Only external js-interop functions are supported.
external int something;
             ^
Error: Compilation failed.
```

**Comment by leafpetersen** [comment]
@RedBrogdon Great, thanks!  The external behavior is WAI I believe.
