### ISSUE TITLE
Error out on import dart:io

### ISSUE THREAD

**Issue by bshlomo** [dart-lang/dart-pad#1615]
import 'dart:async';
import 'dart:io';

myFunc() async {
  print("1");
  sleep(const Duration(seconds: 2));
  print("2");
}

void main() async {
  await myFunc();

  print("done");
}

Based on Flutter 1.20.0 Dart SDK 2.9.1

Console
1
Uncaught Error: Unsupported operation: ProcessUtils._sleep

**Comment by domesticmouse** [comment]
@kevmoo who should we ask about why this fails in the web?

**Comment by rakesh-byte** [comment]
What is the solution for dart:io?

**Comment by domesticmouse** [comment]
Per https://api.flutter.dev/flutter/dart-io/dart-io-library.html, `dart:io` isn't supported on Flutter for web. You need to operate within the confines of the Web browser sandbox.

**Comment by hackertruth** [comment]
whats the alternate solution in place of dart:io ??

**Comment by domesticmouse** [comment]
@hackertruth depends what you are attempting to do. The browser sandbox is a lo more restrictive than running native.

**Comment by jacksontan88** [comment]
whats the alternate solution in place of dart:io ??

**Comment by domesticmouse** [comment]
> whats the alternate solution in place of dart:io ??

See https://github.com/dart-lang/dart-pad/issues/1615#issuecomment-968398332
