### ISSUE TITLE
code completion should show indicate when there are no results

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#162]
When the user explicitly asks for code completion results (ctrl-space), we should indicate when there are none available. Either something like a beep, or flashing some ui element.

**Comment by lukechurch** [comment]
I'll deal with this. I think for a first answer just putting in a box with '---- no completions available -----' should do the job.

I'm a bit puzzled as to what conditions would give no completions though.....

**Comment by devoncarew** [comment]
Trying to complete in `main` will show this behavior:
```
void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}
```

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-lang/dart-pad/pull/196
