### ISSUE TITLE
[Bug] copy is not successful NotAllowedError: Disabled in this document by Feature Policy.

### ISSUE THREAD

**Issue by radeksvarz** [dart-lang/dart-pad#1620]
###  What happened?

Copying by Flutter code is not allowed in Dartpad.

### Flutter code

`Clipboard.setData(ClipboardData(text: someString))` 

### Browser
Browser: Chrome 84

### Machine
Operating system: WIN10

### DartPad's output
```
copy is not successful NotAllowedError: Disabled in this document by Feature Policy.
```

Seems to be related to https://github.com/w3c/webappsec-permissions-policy/issues/322

### Proposal / fix

Set Dartpad's iframe with copy / paste policy.

**Comment by domesticmouse** [comment]
The iframe we run the flutter code inside is sandboxed for security concerns. I'm curious what use cases we are blocking by not granting this iframe copy/paste permissions.

**Comment by radeksvarz** [comment]
@domesticmouse 

ad use case: Dartpad is great for micro-prototyping (i.e. prototype of one screen). In my case certain complicated string on the screen can be copied on button press into the clipboard with the SnackBar confirming that the text is in the clipboard.

There was a lot of confusion, why it does not work on DartPad. And expectation that DartPad would behave the same as if the Flutter code was published onto web.

**Comment by RedBrogdon** [comment]
Fair point. I'll leave this issue open to see if we get any additional support for the request.

So far, our guiding principle has been security first, but if there's consensus that this would help a number of devs, we can look at implementing it.

**Comment by nullskill** [comment]
A have a use case of interactive adjusting TextStyle Shadow arguments with the help of Sliders and SelectableText widget to copy the outcoming code to the clipboard. It would be nice to have the ability to copy the resulting text by pressing a button, but it's not possible due to the permissions policy.
