### ISSUE TITLE
Open dartpad with custom code passed in url

### ISSUE THREAD

**Issue by rrkas** [dart-lang/dart-pad#1621]
Can we open dartpad with our custom code sent in url?
I want to open dartpad where a piece of code will be written. I've seen many websites which accept custom data within the url itself.

Like: 
https://dartpad.dev?code="Container()"

Is it possible in dartpad.dev?

**Comment by RedBrogdon** [comment]
We've looked at adding this feature, but the length limit of URLs would prevent all but the most trivial code examples from being sent that way. As a result, we haven't implemented it.

For the full-screen UI, we just support loading from gists. For the embedded layouts, though, we do have some other options. See this guide for details: https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide
