### ISSUE TITLE
Flutter / Material icons not matched to icon font

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1627]
## What happened?

Using an icon in DartPad shows up as a different icon. This might be because we aren't using the right icon font during compilation.

## Steps to reproduce problem

Go to https://dartpad.dev/d3920cd8130d6e4d42bb4bd16fe512b4 and see that the icons are incorrect

See also https://github.com/flutter/flutter/issues/65582

### Browser

Browser: Chrome

Version: 85

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

no

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

no

### Machine

Operating system: macOS

Version: 10.15.6

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: ColoredBox(
        color: Colors.white,
        child: Column(children: [
          Icon(Icons.play_arrow),
          Icon(Icons.ac_unit),
        ]),
      ),
    ),
  );
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

![image](https://user-images.githubusercontent.com/1145719/92813666-7c943680-f376-11ea-9405-2f3e7fbaa91d.png)

**Comment by johnpryan** [comment]
cc @domesticmouse

**Comment by johnpryan** [comment]
It looks like this is only happening in dart-services. I pulled down https://github.com/flutter/flutter/commit/81a45ec2e5f80fa71d5135f1702ce540558b416d but couldn't reproduce the issue.

**Comment by RedBrogdon** [comment]
We have a hard-coded FontManifest file that hasn't been updated in over a year. That's got to be the issue here:

https://github.com/dart-lang/dart-pad/blob/master/web/scripts/assets/FontManifest.json

Normally it's created as part of the Flutter for web build process (or project init process, one of the two), and we host a fake one in order to make the fonts work out.

**Comment by domesticmouse** [comment]
@johnpryan can you push a new release of the front end with #1631 to verify the fix?

**Comment by johnpryan** [comment]
Deployed to https://20200916t124341-dot-dart-pad.appspot.com/, but it looks like there's still a mismatch:

<img width="438" alt="Screen Shot 2020-09-16 at 12 50 24 PM" src="https://user-images.githubusercontent.com/1145719/93385588-4f82d080-f81b-11ea-9597-28de6ff87584.png">

**Comment by domesticmouse** [comment]
Looking in the network debugging pane of chrome's developer tooling shows that both https://20200916t124341-dot-dart-pad.appspot.com/scripts/assets/fonts/MaterialIcons-Regular.otf and https://20200916t124341-dot-dart-pad.appspot.com/scripts/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf are failing to load.

I'd guess we need to add some additional path handling rules to the python front end. It works fine locally, when running without the python front end script.

/cc @theacodes for insight.
