### ISSUE TITLE
dartpad.dev is not mobile friendly

### ISSUE THREAD

**Issue by riturajshakti** [dart-lang/dart-pad#1630]
This website is not responsive for mobile devices.
It should hide the console and documentation area when not in use. And is should present the entire code editing area when a user writes code at the time of not executing it.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue. We've got a previous filing tracking this request (#1396), so I'm going to close this one as a duplicate. It'll be referenced in the original, though.
