### ISSUE TITLE
Periodic streams are not canceled on reset or run

### ISSUE THREAD

**Issue by cirediew** [dart-lang/dart-pad#1632]
## What happened?

When using a `Stream.periodic` the Reset and Run do not cancel the old streams.
A new stream is started and the old ones continue.
I expect the old streams to be canceled/closed when pressing Reset or Run in the dart-pad.

Even when clicking 'new pad' the stream keeps on going in the new pad.

## Steps to reproduce problem
My code:
```dart
void main() {

  var a = getPeriodicStream();
  a.listen((v) {
    print(v);
  });
}

Stream<String> getPeriodicStream() async* {
  yield* Stream.periodic(
    Duration(seconds: 4),
    (int i) => Future<String>.value('id: ${i +1}'),
  ).asyncMap(
    (value) async => await value,
  );
}
```
The first time after pressing run:
```
id: 1
id: 2
id: 3
```

Press run again:
```
id: 4
id: 1
id: 5
id: 2
```

Press run again:
```
id: 6
id: 3
id: 1
id: 7
id: 4
id: 2
```

### Browser

Browser:

Version: Google Chrome Version 85.0.4183.102

### Machine

Operating system: MacOS

Version: Catalina 10.15.6

**Comment by domesticmouse** [comment]
At a guess we are loading the script into a pre-existing sandbox `div`, instead of inserting a new sandbox `div` on each script load.

**Comment by johnpryan** [comment]
This could also be an issue with how we are loading code compiled with `dart2js`. It looks like this doesn't happen when using the DDC / Flutter compilation path: https://dartpad.dev/edb58d833e0fdd865f588f7e75bee2d6
