### ISSUE TITLE
Is http package supported?

### ISSUE THREAD

**Issue by stevegw** [dart-lang/dart-pad#1635]
Using  import 'package:http/http.dart' as http; Editor says its Unsupported, will it change in the future?

**Comment by RedBrogdon** [comment]
We've had an open request for package support for some time (#901), and just haven't had the engineering bandwidth to get to it.

We're working to move the compilation backend to Cloud Run at the moment, though, and afterwards should have time to consider new feature development. I'd love to be able to use Provider and Firebase, so it's on the top of my feature wish list as well. 😄
