### ISSUE TITLE
should code completion automatically complete when there's just one choice?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#164]
This may save some typing by the user but it's asymmetric behavior with when there's two or more choices.

More importantly, this does not support the discovery case. It'd like to use it for existing code to see the parameter types available; autocompletion in this case doesn't help me.

**Comment by kasperpeulen** [comment]
I think it shouldn't automatically complete when there is just one choice because of the reason you are giving. Most IDEs/editor seem to do the opposite, but it always seems off to me.

**Comment by devoncarew** [comment]
We need to add this to the options we create codemirror with:
```
        'hintOptions': {
          'completeSingle': false
        },
```

**Comment by lukechurch** [comment]
@devoncarew The asymmetry for this breaks muscle memory, the user would have to know whether the completion matched once or not to know what keystrokes they need to type to get their result. That's pretty problematic.

As you say, it also breaks discoverability.

So no, I don't think it should complete automatically.
