### ISSUE TITLE
Line Numbers / Error and Warning Messages.

### ISSUE THREAD

**Issue by wesleydiasmaciel** [dart-lang/dart-pad#1640]
DartPad should show the line numbers. Besides, we should be able to close error and warning messages, because sometimes these messages hides buttons and other widgets we would like to see in the interface.

**Comment by RedBrogdon** [comment]
We have an existing feature request for line numbers (#317), but haven't been able to prioritize them against other features.

For hiding errors from the analyzer, though, I can be more helpful. This is possible in the current interface. See the "hide" link here in the main UI:

![image](https://user-images.githubusercontent.com/969662/95152039-026e8c00-0741-11eb-94d0-f70c9a0920ce.png)

Or the "hide" button here for the embedded UI:

![image](https://user-images.githubusercontent.com/969662/95152068-14502f00-0741-11eb-835b-4b610ce083ab.png)

Thanks for filing an issue!
