### ISSUE TITLE
Null-safety DartPad gives unexpected results

### ISSUE THREAD

**Issue by pennzht** [dart-lang/dart-pad#1641]
## What happened?

`null.toString()` gives unexpected results on the null-safe version of DartPad.

## Steps to reproduce problem

1. Visit https://nullsafety.dartpad.dev/
2. Copy, paste, and run the code below (see the **Your code** section).
3. Read the results.
    - `string == string` should be `true`, but returns `false`;
    - `string == 'null'` should be `true`, but returns `false`;
    - `string[0]` should be `n`, but raises an exception.
4. Run the same code on https://dartpad.dev/ — there are no errors, and all results are expected.

### Browser

Browser:
Chrome 85.0.4183.102

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
As far as I know, no.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:
Yes.

```
DevTools failed to load SourceMap: Could not load content for https://nullsafety.dartpad.dev/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://nullsafety.dartpad.dev/scripts/playground.dart.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM876:2369 Uncaught TypeError: string.$index is not a function
    at Object.main (<anonymous>:2369:22)
    at <anonymous>:2738:9
    at <anonymous>:2722:7
    at dartProgram (<anonymous>:2733:5)
    at <anonymous>:2740:3
    at replaceJavaScript (frame_dark.html:38)
    at messageHandler (frame_dark.html:54)
```

### Machine

Operating system:
macOS

Version:
Catalina 10.15.6

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```dart
void main(){
  final String string = null.toString();
  
  print (string == string); // should be true
  print ('null' == 'null');
  print (string == 'null'); // should be true
  print (string.runes);
  print ('null'.runes);
  print ('${null}' == 'null');
  print (string[0]); // should be 'n'
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
false
true
false
(110, 117, 108, 108)
(110, 117, 108, 108)
true
Uncaught TypeError: string.$index is not a functionError: TypeError: string.$index is not a function
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by RedBrogdon** [comment]
Well that's just plain weird. I would have expected the null-safe DartPad to throw when you tried to call `toString` on a null value.

@nshahan, do you have any advice here?

**Comment by RedBrogdon** [comment]
Convenient links for loading the code:

https://nullsafety.dartpad.dev/7574929e8858b0ff08bc78e0dd43385a
https://dartpad.dev/7574929e8858b0ff08bc78e0dd43385a

**Comment by nshahan** [comment]
> Well that's just plain weird. I would have expected the null-safe DartPad to throw when you tried to call toString on a null value.

You can still call `.toString()` and `.hashCode` on a null value without an error so I'm not surprised there, but all of the other results are confusing. 

I tried this locally with DDC and all of the values print as expected so my first guess is that these bugs have been fixed already. Do you know when the last update to the backend was?

**Comment by RedBrogdon** [comment]
The current output at nullsafe.dartpad.dev is:

```
true
true
true
(110, 117, 108, 108)
(110, 117, 108, 108)
true
n
```

I believe this was fixed simply by updating the SDK to a more recent version. Thanks for filing, @pennzht!
