### ISSUE TITLE
Previously Working Code-Now Producing    Error compiling to JavaScript:

### ISSUE THREAD

**Issue by albertmorrishow** [dart-lang/dart-pad#1642]
https://dart-services.appspot.com/api/darts
playground.dart.js:9634 
POST https://dart-services.appspot.com/api/dartservices/v2/compile 400

  | b6 | @ | playground.dart.js:9634
-- | -- | -- | --
  | CM | @ | playground.dart.js:1784
  | (anonymous) | @ | playground.dart.js:13401
  | (anonymous) | @ | playground.dart.js:1853
  | $2 | @ | playground.dart.js:6992
  | $1 | @ | playground.dart.js:6984
  | fp | @ | playground.dart.js:7793
  | $0 | @ | playground.dart.js:7373
  | fF | @ | playground.dart.js:1945
  | d3 | @ | playground.dart.js:7282
  | $0 | @ | playground.dart.js:7335
  | FP | @ | playground.dart.js:1978
  | FX | @ | playground.dart.js:1980
  | $1 | @ | playground.dart.js:6937
  | GK | @ | playground.dart.js:538
  | (anonymous) | @ | playground.dart.js:546
  | childList (async) |   |  
  | $1 | @ | playground.dart.js:6944
  | Ap | @ | playground.dart.js:1985
  | eK | @ | playground.dart.js:2055
  | B8 | @ | playground.dart.js:1997
  | cV | @ | playground.dart.js:7660
  | m4 | @ | playground.dart.js:7474
  | ef | @ | playground.dart.js:7625
  | ac | @ | playground.dart.js:7606
  | ac | @ | playground.dart.js:7454
  | j_ | @ | playground.dart.js:13462
  | (anonymous) | @ | playground.dart.js:13383
  | (anonymous) | @ | playground.dart.js:1853
  | $2 | @ | playground.dart.js:6992
  | bQ | @ | playground.dart.js:1839
  | b6 | @ | playground.dart.js:13420
  | b6 | @ | playground.dart.js:11868
  | (anonymous) | @ | playground.dart.js:13352
  | (anonymous) | @ | playground.dart.js:1853
  | $2 | @ | playground.dart.js:6992
  | bQ | @ | playground.dart.js:1839
  | m3 | @ | playground.dart.js:13357
  | cq | @ | playground.dart.js:13341
  | (anonymous) | @ | playground.dart.js:12906
  | (anonymous) | @ | playground.dart.js:1853
  | $2 | @ | playground.dart.js:6992
  | bQ | @ | playground.dart.js:1839
  | lZ | @ | playground.dart.js:12918
  | aI | @ | playground.dart.js:12900
  | (anonymous) | @ | playground.dart.js:12180
  | (anonymous) | @ | playground.dart.js:1853
  | $2 | @ | playground.dart.js:6992
  | bQ | @ | playground.dart.js:1839
  | bj | @ | playground.dart.js:12221
  | $1 | @ | playground.dart.js:12406
  | $1 | @ | playground.dart.js:10229
  | GK | @ | playground.dart.js:538
  | (anonymous) | @ | playground.dart.js:546

**Comment by RedBrogdon** [comment]
Thanks for filing an issue! Can you share the code you were attempting to compile when you saw the error?

**Comment by albertmorrishow** [comment]
Thanks for replying to my issue, however, due to the proprietary nature of the code, I am not able to provide it.

I am able to say that, the code continues to be able to be compiled, and continues to run on Visual Studio Code as it previously did on the DartPad.

I hope that the issue will be able to be resolved.

Again, thanks!

**Comment by martin-mayer** [comment]
I have the same problem. I tried with Firefox, Brave and Chrome browsers on Ubuntu 20.04
The code is simply the DartPad Hello World Example. I attach a screenshot
![Bildschirmfoto vom 2020-10-26 00-29-08](https://user-images.githubusercontent.com/11940764/97113024-915c3c00-1722-11eb-8008-14c70a5eddb0.png)

**Comment by RedBrogdon** [comment]
I think there might be two issues here: one with compiling a particular piece of code and one with connecting in general.

@albertmorrishow, if this is still a problem for you and you have a version of the code that you can share, please feel free to reopen this issue.

@martin-mayer, if you're still having trouble compiling code in general, please file an issue with the information that's requested in the issue template. That'll give us the best chance to diagnose the problem.
