### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by elcolie** [dart-lang/dart-pad#1643]
I use white theme on my laptop. DartPad is using `dracula` mode and it blur my eyes when switch between IDE and DartPad

**Comment by sebastianhaberey** [comment]
Yes please!

**Comment by danbrotherston** [comment]
Yes please as well.

**Comment by mykdavies** [comment]
Me too, too. But while we're waiting, here's my .css for fixing this. I use it with Cascadea on Safari. 

Enjoy!

<details>
  <summary>dartpad.css</summary>

```
header, body, footer, .CodeMirror, #issues, .mdc-button, .message, .mdc-tab__text-label {
	background-color: #eee !important;
	color: #000 !important;
}
.CodeMirror-gutter {
	background-color: #ddd !important;
	color: #000 !important;
}
.CodeMirror-selected {
	opacity: 0.3; !important;
}
.CodeMirror-cursor {
    border-left:2px solid #555 !important
}
#run-button {
	background-color: #99c !important;
}
/* Dart code */
.cm-keyword {
	color: #080 !important;
}
.cm-string {
	color: #800 !important;
}
.cm-builtin {
	color: #000 !important;
}
.cm-variable {
	color: #00a !important;
}
.cm-operator {
	color: #08f !important;
}
.cm-number {
	color: #808 !important;
}
.cm-variable-2 {
	color: #644 !important;
}
.mdc-tab-indicator__content--underline {
	border-color:#000 !important;
}
/* html */

.cm-tag {
	color: #242 !important;
}
.cm-attribute {
	color: #224 !important;
}

/* css pane */
.cm-property {
	color: #422 !important;
}
.cm-atom {
	color: #644 !important;
}
/* console */
p {
	color: #000 !important;
}
.normal {
	color: #000 !important;
}
h1 {
	color: #068 !important;
}
em{
	color: #633 !important;
}
a {
	color: #227 !important;
}
.launch-icon {
	background-color: #008 !important;
}
```
</details>

**Comment by henriqueArrazao** [comment]
Yes, only those who have dyslexia know how bad it is, please!

**Comment by myxzlpltk** [comment]
wait.... you guys using light theme????

**Comment by dumazy** [comment]
I would love to have this as well. Even more, to have it synced with the system defaults. I switch between light mode during the daytime, when there's a lot of light in the room and dark mode at night.

**Comment by rontarrant** [comment]
Another vote in favour or a light theme. I can't use it otherwise. It's way too hard on my eyes.

**Comment by ivanzoid** [comment]
Anyone interested, see workaround for light theme in https://github.com/dart-lang/dart-pad/issues/1260#issuecomment-1333580800

**Comment by lwinch2006** [comment]
Voting for this 👍

**Comment by nicolas-mace** [comment]
Whether it's day or night, I've never been able to use dark themes, it always hurts my eyes. So for now, no DartPad for me :(

**Comment by rontarrant** [comment]
> Whether it's day or night, I've never been able to use dark themes, it always hurts my eyes. So for now, no DartPad for me :(

I agree. I find it unfathomable that dark mode is the only option on a growing number of applications. It's like these developers are looking to shrink their user base.

**Comment by parlough** [comment]
The now-live version of [DartPad](https://dartpad.dev) outlined in https://github.com/dart-lang/dart-pad/issues/2808 now has a persistent button to switch between light and dark themes. Thanks for all of the feedback and discussion here!

If you have any feedback around the current light and dark modes, please open an issue with specific feedback. Thanks again :D
