### ISSUE TITLE
double.parse and toDouble() do not seem to work in DartPad

### ISSUE THREAD

**Issue by GrahamDi** [dart-lang/dart-pad#1646]
## What happened?

I am unable to get the expected output when using double.parse or toDouble() to convert integers, either from strings or as literals, in DartPad. The same code works perfectly in Flutter/Dart application in VSCode when debugging.

## Steps to reproduce problem

Paste the code below into DartPad and run.

### Browser

Browser: Google Chrome 

Version: Version 86.0.4240.75 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console? No

### Machine

Operating system: Win 10

Version: Windows 10 Home Insider Preview 2004 Build: 20226.1000

### Your code

```
void main() {
  String selectedLeverage = '1 : 100';
  
  var leverage = double.parse(selectedLeverage.split(" ")[2]);
  print(selectedLeverage.split(" ")[2]);
  print(leverage);
  print(leverage.runtimeType);
  double x = leverage.toDouble();
  var y = (12345).toDouble();
  print(x);
  print(x.runtimeType);
  print(y);
  print(y.runtimeType);
}
```

### Expected output - this from Flutter app in VSCode debug console.

```
 I/flutter (13041): 100
 I/flutter (13041): 100.0
 I/flutter (13041): double
 I/flutter (13041): 100.0
 I/flutter (13041): double
 I/flutter (13041): 12345.0
 I/flutter (13041): double
```

### DartPad's output

```
Console
100
100
int
100
int
12345
int
```

Is this expected behaviour in DartPad?

**Comment by kwalrath** [comment]
This seems like it might be a JS-related issue (see https://github.com/dart-lang/site-www/issues/2565).

**Comment by GrahamDi** [comment]
I assumed that it was the underlying JS. 

The issue is that DartPad is a great tool and is being used by many experienced and new coders that are starting with Dart or just testing things out. If DartPad gives the wrong results, as in this case, without any form of warning or documentation to say that the results could be inaccurate, then damage is being done regarding its abilities. I think this is quite a serious problem.

**Comment by domesticmouse** [comment]
Is this behaviour expected? Yes, DartPad compiles to JavaScript to run inside the browser, which means we are restricted to JS' number semantics. JavaScript doesn't have separate number types for integers and floats.

**Comment by GrahamDi** [comment]
As I said, I assumed that. Where is that stated in the docs?

My point still stands, namely that unless the new user is actively warned of these shortfalls then they get a negative / inaccurate impression of Dart's actual capabilities when they use DartPad.

**Comment by domesticmouse** [comment]
For the where is it documented question, @kwalrath has the open bug she mentioned above https://github.com/dart-lang/site-www/issues/2565 to document JS number semantics.

As for warning people that they are using an environment that is limited to the capabilities of the web browser, while they are using it inside a web browser, is an interesting question. Do developers assume that we run their code on a server and just stream the display output to their web browser? 

There are a bunch of other limitations to DartPad, e.g. [attempting to use `dart:io`](https://api.dart.dev/stable/2.10.2/dart-io/dart-io-library.html) that also requires better error messages.

**Comment by GrahamDi** [comment]
Hi Brett,

Thanks for your views.

I have to say that I am not sure a somewhat esoteric issue raised against the dart language project on GitHub qualifies as documentation (that anyone would read) for DartPad.

I also think that this and other language limitations could be shown as warning messages when editing the code in DartPad, just as syntax and other errors are flagged. I, for one, certainly did not think it was run on a server and the browser was just a window to it.

I did not intend to raise this in a 'complaining' way and,  as I tried to explain, the issue is really about the impression / possible doubts this gives to new users - the overused term 'fake news' applies.

My raising this appears to have caused some defensiveness around DartPad and I therefore apologise if I missed the mark with my intentions. I will continue to use DartPad often.

Closing this based on the above responses.

**Comment by domesticmouse** [comment]
The bug referenced is for updating the main Dart documentation to include information about Dart's limitations when compiled to JavaScript. I can envision adding something to the DartPad UI that links to documentation on the limitations of Dart and Flutter when running on the web.

I'm sorry you felt the need to close this issue based on my responses. I'd suggest reopening as this issue could use some UX research and then potentially some UI redesign to incorporate this feedback.

**Comment by GrahamDi** [comment]
Fair enough.

**Comment by parlough** [comment]
Thanks everyone for the great discussion here! I'm going to close this in favor of a general solution to exposing information about what compiler DartPad is using at a time and its specific limitations.

The relevant document covering number differences has been published since this post was last updated, and can be found at [Numbers in Dart](https://dart.dev/guides/language/numbers).
