### ISSUE TITLE
DartPad Tabs

### ISSUE THREAD

**Issue by bynalab** [dart-lang/dart-pad#1654]
It would be cool if we can have different tabs open on DartPad, because now you have to create new pad which i think will discard your current snippet.
I noticed even if you open another chrome tab, your current snippet will still be there. 
Thanks in advance.

**Comment by RedBrogdon** [comment]
That's an interesting idea. We've had people suggest multiple *file* support before, but I don't think I've seen anyone suggest multiple tabs that would execute individually.

It may be a while before we have time to work on something like this, but I'll keep the issue open.

**Comment by cebulon** [comment]
What is the status with this?
Would be awesome to have different threads to test things out.

**Comment by parlough** [comment]
Thanks for the suggestion!

DartPad is no longer setup to save and resurface the current snippet, so running it in multiple tabs with different snippets works fine.

If/when we revisit storing snippets again (https://github.com/dart-lang/dart-pad/issues/2871), we'll make sure to consider how to support multiple work streams. I'll close this in favor of that issue.
