### ISSUE TITLE
Generate a link for the pad so I can share it with a friend

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#166]
I'd really like to share my pads with other developers. I'd like to get a link that leads my friends directly to my pad.

(Apologies if this is a dupe. I searched for "link")

**Comment by devoncarew** [comment]
started...

**Comment by sethladd** [comment]
:yellow_heart:

**Comment by kasperpeulen** [comment]
cool !

**Comment by devoncarew** [comment]
https://github.com/dart-lang/dart-pad/pull/261
