### ISSUE TITLE
[Feature] Ability to use multiple 'Pads'

### ISSUE THREAD

**Issue by KristofKekesi** [dart-lang/dart-pad#1661]
## Ability to use and save multiple 'Pads'
As I know it uses local storage (cookies) to store the current project, so I think this idea would be feasible.

**Comment by KristofKekesi** [comment]
similar like #1654

**Comment by RedBrogdon** [comment]
I'm going to close this as a duplicate of #1654, since they both relate to the same feature. Thanks for filing the request, @KristofKekesi!
