### ISSUE TITLE
Google Chrome and Microsoft Edge

### ISSUE THREAD

**Issue by kabhay166** [dart-lang/dart-pad#1663]
I am using DartPad in Google chrome and Microsoft edge. But most of the time, the UI section either takes too long to show or does not show at all.

**Comment by domesticmouse** [comment]
Can you please supply an example of code that fails to render, and potentially which resource is failing to load? You should hopefully get some useful information from your Chrome DevTools, or MS Edge equivalent.

Also, it would be helpful to know which versions of Chrome and Edge you are running, and what OS version.

**Comment by kabhay166** [comment]
Thank for the reply. The problem is solved. It was because one of my
software was interfering with my internet connection and so the rendering
of the UI was so slow that I thought it was not working. I uninstalled the
software and now the dartpad works normally.

**Comment by domesticmouse** [comment]
thanks for the update!
