### ISSUE TITLE
Container's color won't show as filled if there is boxshadow.

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1669]
![image](https://user-images.githubusercontent.com/16307013/98498042-1bf77c00-2289-11eb-894f-80120d36d781.png)

As you can see in the image, the container's fill won't be rendered if there is a boxshadow.

```dart
Container(
  child: Container(
    width: 198,
    height: 105,
    decoration: BoxDecoration(
      color: Color(
        0xffffff,
      ),
      border: Border.all(
        width: 1,
      ),
      boxShadow: [
        BoxShadow(
          color: Color(
            0x3f000000,
          ),
          offset: Offset(
            0,
            4,
          ),
          blurRadius: 4,
        ),
      ],
    ),
  ),
  padding: EdgeInsets.only(
    left: 88,
    right: 89,
    top: 121,
    bottom: 122,
  ),
  decoration: BoxDecoration(
    color: Color(
      0xffffff,
    ),
  ),
);
```

But non-white fill shows.... (WIERD!!)

`0xffffff` -> `0xfffcfcfc`

``` dart
Container(
  width: 198,
  height: 105,
  decoration: BoxDecoration(
    color: Color(
      0xfffcfcfc,
    ),
    border: Border.all(
      width: 1,
    ),
    boxShadow: [
      BoxShadow(
        color: Color(
          0x3f000000,
        ),
        offset: Offset(
          0,
          4,
        ),
        blurRadius: 4,
      ),
    ],
  ),
);
```

**Comment by domesticmouse** [comment]
This issue probably belongs on the flutter/flutter issue tracker as I suspect it isn't specific to DartPad. Can you repost it there?

**Comment by softmarshmallow** [comment]
I wasn't sure. So i posted on both side. But i think it's more dart-pad side's issue. I cannot be the first one to report this issue on flutter repo. (Which i was. ..??)

**Comment by domesticmouse** [comment]
Okiday, I'll dig into this more. Thanks for the report!

**Comment by softmarshmallow** [comment]
https://github.com/flutter/flutter/issues/70071#issuecomment-723931310

My bad. It was simply color issue uniquely to white value. (I dont fully understand but this seems to work )
