### ISSUE TITLE
Plans for supporting DartDDC as long-lived connection (serve)

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1670]
current build pipeline uses compileDDC, which is a dev compiler, but always takes few seconds.
Are you guys planning to use `serve` command and make long-lived (socket) connection, and use the benefits of serve command? -- AOT/JIT - hot reloading of flutter application on dartpad

**Comment by RedBrogdon** [comment]
No, this is not something that's currently on our roadmap. A stateless backend is one of the core design choices that was made for DartPad way back when it was first architected, and it would be a major undertaking to change it.

It would certainly be an interesting experiment, though, if you wanted to see how far you could get in a fork.

**Comment by domesticmouse** [comment]
This will require something like Web Sockets support in Cloud Run to enable running an instance of the analyser per active user. This could get quite expensive, however, as the servers will be mostly idle as they wait for the users to type in new code to analyze and compile.
