### ISSUE TITLE
Add consistent Zoom in and zoom out support

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/dart-pad#1671]
currently zooming makes experiences worst,

**Comment by RedBrogdon** [comment]
Can you provide more information about the issue you're seeing? Is it in any particular browser, for example? Can you list steps to reproduce it?

**Comment by fisforfaheem** [comment]
when you zoom in chrome, on dartpad.dev ... it makes everything uglier!
format button goes away! also Ux feels bad

**Comment by parlough** [comment]
Thanks for the report!

Trying this out with the current UI, it supports a few levels of zoom better, and then adapts to the mobile layout before there would be problems with the various buttons.

I'll close this as fixed for now, but there are perhaps further improvements to be made, so please feel free to open new issues with other specific changes that we should explore. Thanks again :)

**Comment by fisforfaheem** [comment]
sure, i like the zoombar extenstion in VSCODE can u try that
