### ISSUE TITLE
Make Dartpad available on windows 10 through Windows 10 store as PWA

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/dart-pad#1673]
it would be more easier and less resources be used

**Comment by domesticmouse** [comment]
Im curious how making DartPad a PWA would effect resource usage.

**Comment by fisforfaheem** [comment]
It would not run a full chrome browser and would feel native app on windows
10

**Comment by AFEEFALISHAN** [comment]
`p3 label pn tue basis `

**Comment by fisforfaheem** [comment]
p3 label pn tue basis ???

**Comment by domesticmouse** [comment]
It actually will run a full chromium browser, it'll be either Chrome or Microsoft Edge depending on the user's browser configuration. I fully support adding PWA support for native look & feel, but it has zero impact on client side resource utilisation.

**Comment by fisforfaheem** [comment]
But still i want dartpad to work as a native app! as you can see it already
works just like an app! and it should have an option to be able to be
installed as PWA! both chrome and edge support installing! also i think if
you upload to windows 10 store it would be so easy

**Comment by parlough** [comment]
Thanks for the suggestion and discussion here!

I don't think we'll upload to any platform store, but you can use a browser that supports it to install the current https://dartpad.dev as a PWA.

Note that DartPad is not meant to be an IDE, just an editor to quickly try out Dart snippets. It also won't work well offline as it relies on requests for analysis and compilation.

If anyone has issues installing or using the website as a PWA, let us know with a new issue and reproduction information. Thanks!

**Comment by fisforfaheem** [comment]
https://flutlab.io/ Found this website as an alternative
