### ISSUE TITLE
Add google Login support( registration) 

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/dart-pad#1674]
in this way many of us can use it without fear of code loss in sudden power loss which happens a lot etc

**Comment by RedBrogdon** [comment]
I'm not sure what you mean. Can you provide a little more information about how Google login support would help during a power loss?

**Comment by fisforfaheem** [comment]
I could help users save their data, small projects without any troubles and
run  the same code on any of their devices

**Comment by domesticmouse** [comment]
This sounds like you are edging towards trying to use DartPad as an IDE. You will probably have a better experience using one of the many VS Code in the cloud solutions to edit Flutter projects. I have used [gitpod.io](https://gitpod.io/), [cdr/code-server](https://github.com/cdr/code-server), and [GitHub's Codespaces](https://github.com/features/codespaces) to edit full Flutter projects in a browser.

**Comment by fisforfaheem** [comment]
i know what you mean! but still i think it is possible to add login as an
optional option..

**Comment by johnpryan** [comment]
Right now we store any edits you make in the browser's localStorage, but this doesn't allow you to switch devices easily. You *can* [create a GitHub Gist to share snippets](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide). 

This is slightly related to https://github.com/dart-lang/dart-pad/issues/1097

**Comment by fisforfaheem** [comment]
i wish i could but  i have no idea about programming stuff

**Comment by Parables** [comment]
I'm a huge fun of Svelte and on their [REPL]( https://svelte.dev/repl/hello-world?version=3.35.0), you can login to GitHub and save your snippets. Very useful for experimenting with ideas and you can go full using it as an editor. The only thing it lacks is auto-completion but aside from that, it makes prototyping very easy and I think we can do the same with DartPad

**Comment by fisforfaheem** [comment]
Cool, I'll check it out.

**Comment by parlough** [comment]
Thanks for the suggestion and discussion here!

The current DartPad UI no longer has support for saving snippets, so I'll close this issue in favor of https://github.com/dart-lang/dart-pad/issues/2871 which discusses bringing that future back. If we do though, it will likely be all local still.

If you'd like to save code to an account or for larger projects, consider using an online IDE like [Project IDX](https://idx.dev/) or [GitHub Codespaces](https://idx.dev/). Thanks again!
