### ISSUE TITLE
Show analysis corrections and "Open Documentation" link

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1676]
Analysis errors now have a [message, correction, and documentation URL](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#type_AnalysisError). We should show these details if they are available.

![image](https://user-images.githubusercontent.com/1145719/99291386-97f74400-27f4-11eb-96f7-d4cd7b9aee0d.png)

DartPad only displays the message:

<img width="391" alt="Screen Shot 2020-11-16 at 10 18 27 AM" src="https://user-images.githubusercontent.com/1145719/99291739-1fdd4e00-27f5-11eb-839a-79b3bdfcfbbd.png">

**Comment by mit-mit** [comment]
Any news about this one?

**Comment by johnpryan** [comment]
I haven't started on this, should I bump up the priority?
