### ISSUE TITLE
Clicking on an analysis warning should scroll to the cursor location

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1677]
Right now, when an analysis warning is clicked, the editor selects the line / column where the error occurred. We should scroll the editor too.

When I was editing a large file, I couldn't see the line with the problem until I scrolled down. We could also show line numbers to make this easier.

**Comment by RedBrogdon** [comment]
Weird. I just checked this to make sure I wasn't crazy, and my editor scrolls to the correct line. The mechanism by which it does so, though, is buried in the Editor/Document/Context classes that I haven't gotten that far into, and I can totally believe that it fails in some cases.

**Comment by johnpryan** [comment]
Interesting, yeah I can't reproduce this anymore. I'll close for now.
