### ISSUE TITLE
Show line numbers

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1678]
Showing line numbers can make it easier to fix errors and warnings:

<img width="405" alt="Screen Shot 2020-11-18 at 4 47 45 PM" src="https://user-images.githubusercontent.com/1145719/99606062-d3913a00-29bd-11eb-8bc4-f428e9410c0f.png">

I wasn't able to find the warning, because we also don't scroll the editor: https://github.com/dart-lang/dart-pad/issues/1677

**Comment by RedBrogdon** [comment]
We've actually got an open issue for this one: #317. FWIW, I totally agree.
