### ISSUE TITLE
Dart-pad UI output doesn't work on Yandex.Browser 20.11.1.86 Windows10

### ISSUE THREAD

**Issue by DVegasa** [dart-lang/dart-pad#1681]
Tried on this page https://flutter.dev/docs/codelabs/layout-basics
It's also doesn't work on another flutter.dev pages

Pressing "Run" button launch progress bar, then it hides and nothing happens.
Adblock/AdGuard disabled.

Yandex.Browser 20.11.1.86
Windows 10 (64-bit) 
![image](https://user-images.githubusercontent.com/28566199/99905777-5da60f00-2cec-11eb-97ac-c1b574a936f1.png)

UPD:
Console output works fine. UI doesn't. (Tried here https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)

**Comment by domesticmouse** [comment]
It looks like Yandex browser, on macOS at least, is based on Blink (aka Chromium). I'm unsure how far it has diverged from Chrome, but Dartpad works for me in Yandex browser on macOS.

**Comment by DVegasa** [comment]
From browser:
```Yandex Browser is based on projects Blink, Chromium, Opera Turbo and other software.```

And given links
https://www.chromium.org/blink?hl=ru
https://www.chromium.org/?hl=ru
https://www.opera.com/browser/turbo/?hl=ru
Other software: list in attached pdf [Credits.pdf](https://github.com/dart-lang/dart-pad/files/5581209/Credits.pdf)

**Comment by domesticmouse** [comment]
Is there anything interesting in the javascript console?
