### ISSUE TITLE
Append build ID to static resources

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1683]
Issues like https://github.com/dart-lang/dart-pad/issues/1605 happen because AppEngine serves the old (cached) HTML, but loads the new version of the javascript / css resources. A common technique is to append a build ID in the HTML:

```
<script src='/static/my-script.js?v=123456'>
```

We could add a grind task that appends does this for all JS and CSS assets.

https://b.corp.google.com/issues/173719137

**Comment by johnpryan** [comment]
Related to https://github.com/dart-lang/dart-pad/issues/766

**Comment by parlough** [comment]
Now that all the relevant resources are now all in compiled JS/WASM code due to the frontend being a Flutter app, I'm not sure this is as a large of a concern anymore. If you still think so, or this pops up again, please feel free to reopen or open a new issue. Thanks!

**Comment by johnpryan** [comment]
We haven't had this issue since switching from App Engine to Firebase. There is a related issue about this in the framework issue tracker: https://github.com/flutter/flutter/issues/63500
