### ISSUE TITLE
Chip path rendering inconsistencies in Dart SDK 2.12.0-51.0.dev

### ISSUE THREAD

**Issue by LOG-TAG** [dart-lang/dart-pad#1684]
## What happened?

While running this Chip example https://dartpad.dev/5454e8bfadf3000179d19b9bc6be9918  
on Dart pad (Based on Flutter 1.23.0-18.1.pre Dart SDK 2.10.4)
Path rendering issue problem found. 

Path width is rendering differently for the lower part and upper part of the StadiumBorder

## Steps to reproduce the problem

run this and copy the code 
https://dartpad.dev/5454e8bfadf3000179d19b9bc6be9918  

and run the same code in https://nullsafety.dartpad.dev/ (Based on Dart SDK 2.12.0-51.0.dev)

**nullsafety.dartpad out put (working as intended):**
<img width="303" alt="Screenshot 2020-11-25 at 2 16 26 AM" src="https://user-images.githubusercontent.com/1190344/100197221-0a1c0700-2f20-11eb-9b39-6b509dd63b27.png">

**dartpad.dev(Path rendering is difference):**

<img width="211" alt="Screenshot 2020-11-25 at 2 14 16 AM" src="https://user-images.githubusercontent.com/1190344/100197400-48b1c180-2f20-11eb-860b-87840c939b66.png">

We can clearly see path rendering inconsistencies.

**Comment by domesticmouse** [comment]
Given the largest difference between the two dartpads from the point of rendering is the version of Flutter, I suspect this problem will be resolved when we can update the version of flutter on the main DartPad.

**Comment by parlough** [comment]
Closing as stale as we now are only running one version of DartPad, with much newer Flutter versions. If anyone is able to reproduce this in DartPad specifically, please open a new issue with reproduction details. Thanks!
