### ISSUE TITLE
Embed "Enable null safety" dropdown isn't selected when null_safety query param is set

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1687]
The dropdown doesn't reflect the null_safety query param. (embeds only)

## Steps to reproduce problem

1. Go to https://dartpad.dev/embed-flutter.html?null_safety=true
2. Observe null safety is enabled
3. open menu
4. observe "enable null safety" isn't checked

**Comment by RedBrogdon** [comment]
Assigning to you, John, since I believe you're already working on it or have it fixed.
