### ISSUE TITLE
خانه خانگی

### ISSUE THREAD

**Issue by Amirnateghi1** [dart-lang/dart-pad#1688]
راهنمایی برای بروزرسانی لطفا چه طوری یا خودکار شروع شود

**Comment by RedBrogdon** [comment]
من مطمئن نیستم که شما چه می پرسید آیا هنگام استفاده از DartPad با مشکل خاصی روبرو می شوید؟

(این متن با استفاده از Google Translate از انگلیسی ترجمه شده است)
