### ISSUE TITLE
Stop dart.io from bring imported

### ISSUE THREAD

**Issue by chidhu07** [dart-lang/dart-pad#1692]
I have import dart.io and used "stdout.write("*");" as well for printing in a horizontal way but i have been displayed with a error "Uncaught Error: Unsupported operation: StdIOUtils._getStdioOutputStream". Kindly look into it. Thanks.

**Comment by woinbo** [comment]
I would like to work on this issue. Is it still open. Can anyone guide me towards this issue, It will be my 1st contribution to open-source

**Comment by domesticmouse** [comment]
Sorrry @woinbo I had a fix sitting on disk, I just hadn't submitted the change. =)
