### ISSUE TITLE
[Help-Wanted] Open in dart-pad

### ISSUE THREAD

**Issue by rish07** [dart-lang/dart-pad#1699]
Hello
I am trying to make a Flutter App that has pieces of flutter code. Right now, I can manually copy the code on clipboard, open dart-pad and then run the code there. I wanted a feature like 'open in dart-pad' on my app. So when I click on this button, it opens a new dart-pad with the code already copy-pasted. 

How should I approach this problem?

**Comment by domesticmouse** [comment]
Please have a look at https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide

If you have questions after reading through the above doc then feel free new bugs so we can add them to the above doc. Thanks!
