### ISSUE TITLE
Move documentation rendering to the server

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#1701]
If we handled the Markdown rendering of the documentation on the server, we'd get a few benefits:

- Reduce client bundle size more
- Again able to get proper MDN links for web APIs when needed
- Perhaps slightly quicker(not sure)

**Comment by domesticmouse** [comment]
@RedBrogdon fyi

**Comment by RedBrogdon** [comment]
We talked this over earlier today, and decided just to remove the MDN links. They only show up in rare instances, and don't provide much additional utility for the user.

When you say "move dartdoc rendering to the server," what do you mean, BTW?

**Comment by domesticmouse** [comment]
I'm curious if markdown parsing and rendering is taking serious time on the client. We have some interesting, like using a wasm markdown engine: https://github.com/rsms/markdown-wasm
