### ISSUE TITLE
Dart 1.0 main.dart 

### ISSUE THREAD

**Issue by JUNKARLOS** [dart-lang/dart-pad#1709]
c) Ejecuta la aplicación
d) Cuál es la función del componente Column?
Es la orden para alinear cada dependencia o color usado
body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          Flexible(
            child: Container(color: Colors.blue, height: 100, width: 100),
          ),
          Flexible(
            child: Container(color: Colors.red, height: 200),
          ),
          Flexible(
            child: Container(color: Colors.amber, height: 100,),
          )
        ],
      ),
e) Cuál es la función del atributo mainAxisAlignment?
Es la estructura del arreglo en el orden que se ubicaran los hijos de la función
crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          Flexible(
            child: Container(color: Colors.blue, height: 100, width: 100),
          ),
          Flexible(
            child: Container(color: Colors.red, height: 200),
          ),
          Flexible(
            child: Container(color: Colors.amber, height: 100,),
f) Cuál es la función del atributo crossAxisAlignment?
Origina la existencia de características de hijos de la función
Cómo se deben colocar los hijos a lo largo del eje transversal.
g) Modifica el valor de MainAxisAlignment.start por MainAxisAlignment.spaceEvenly. Que
ocurre?
Las columnas de colores se despliegan con espacios, ya no están juntos los hijos
h) Modifica el valor de crossAxisAlignment.start por crossAxisAlignment.center. Que ocurre?
El primer hijo (color azul), queda centrado

**Comment by RedBrogdon** [comment]
Not sure what the issue is here. Are you having an issue with DartPad? It looks like these are answers to the following gist's questions:

https://gist.github.com/onory/0e3e7b9b59d7e9cfd4bc44677f7cf0cf
