### ISSUE TITLE
Unnecessary scrollbar appears due to extra space below footer

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#1713]
## What happened?

A vertical scrollbar for just a few extra pixels appears in DartPad for me due to some extra space below the footer.

![image](https://user-images.githubusercontent.com/18372958/103434958-0e49dd00-4bce-11eb-9c16-648dcdd46309.png)

## Steps to reproduce problem

Open the website. See the scrollbar and try scrolling down.

## Additional info

Some CSS issue is causing this but I can't identify it. All I know is deleting the footer entirely from the HTML results in the issue disappearing.

### Environment

**Browser**

Chrome Dev - Version 88.0.4300.0 (Official Build) dev (64-bit)

Firefox - 84.0 (64-bit)

**Machine**

Operating system: Pop!_OS 20.10 - Gnome 3.38.1 - Linux 5.8.0-7630-generic x86_64

**Are you using any extensions/plugins that affect website behavior?**

I'm able to reproduce the issue without any extensions enabled and at multiple window sizes.

**Comment by RedBrogdon** [comment]
@johnpryan, I'm taking the liberty of throwing this to you. Let me know if you've got other stuff on your plate.

**Comment by parlough** [comment]
To add some extra context, I believe this doesn't happen in the embedded pages even when they're ran standalone. It also seems to still occur even after #1707 removing Primer.

**Comment by johnpryan** [comment]
I think adding `overflow: hidden;` for the `body` tag will fix it. This might have been something Primer was doing.

**Comment by johnpryan** [comment]
Fix here: https://github.com/dart-lang/dart-pad/pull/1717

**Comment by parlough** [comment]
@johnpryan Huh, simple enough - I didn't think to try that! Thanks!
