### ISSUE TITLE
use the flutter sdk to power both regular dart snippets as well as flutter snippets

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1714]
We may want to switch to using the Flutter SDK to power analysis and compilation for both Flutter dartpad snippets as well as non-Flutter snippets. This will:

- simplify the code - we won't need to have two types of SDKs (see `PlatformSdk` and `FlutterSdk`)
- reduce the number of SDKs and ways that they're installed (currently, via git for the Flutter SDK, and via docker / the runtime SDK for the platform SDK)

(cc @domesticmouse for thoughts)

**Comment by domesticmouse** [comment]
I like the idea of using the flutter dart sdk, but I'm worried we will lose the ability to handle HTML apps. I don't know how complete the dart sdk is going forward.

**Comment by devoncarew** [comment]
The Dart SDK variant included in the Flutter SDK supports `dart:html`, `dart:js`, and `dart:js_util`. It can compile the other web core libraries (see 'Web' in https://api.dart.dev/stable/2.10.4/index.html), but they won't statically analyze.

I suspect that `dart:html` is the main one that we need to support. We could do something like analyze the existing snippets to see which `dart:*` libraries are typically used.

**Comment by domesticmouse** [comment]
@RedBrogdon do we have a list of actively maintained gists?

**Comment by RedBrogdon** [comment]
The list is essentially the IDs in the samples dropdown at this point. I believe all the codelabs that previously used gists have been migrated to use the inject script. 

How would this affect our ability to serve a particular version of the Dart SDK? If we want to have dev/beta/stable for both SDKs, would that still be possible?

**Comment by devoncarew** [comment]
> How would this affect our ability to serve a particular version of the Dart SDK?

The metadata file would contain something like:

```
version: 1.26.0-2.0
channel: dev
```

And both the version and channel could be changed independently. We could have front-ends served from something like dev.dartpad.dev / beta.dartpad.dev / (stable.)dartpad.dev; those frontends could infer what channel they were on from the subdomain and route their requests to the right backed (or, the backend could take a param for the sdk channel to use).

> If we want to have dev/beta/stable for both SDKs, would that still be possible?

We'd just support a single flavor of SDK - the Flutter SDK - but could have multiple versions of that one.

**Comment by RedBrogdon** [comment]
> We'd just support a single flavor of SDK - the Flutter SDK - but could have multiple versions of that one.

Reducing complexity this way would definitely have some clear wins (needing only one analysis server in memory at a time would be a great one). I don't know that much about the roll/release process for how Dart ends up in the Flutter SDK, though. Is there any chance a feature would land in the Dart SDK dev channel and not be rolled into Flutter SDK for a while?

For something like record types, for example, I can see us being asked to make sure DartPad supports them as soon as they make it into the dev channel of the Dart SDK (similar to the way we needed to support NNBD before it was available in Flutter) so that there's a link to go in the announcement blog post. I'd get heat from Michael if we lose the ability to do that. 😄

**Comment by devoncarew** [comment]
> Reducing complexity this way would definitely have some clear wins (needing only one analysis server in memory at a time would be a great one). I don't know that much about the roll/release process for how Dart ends up in the Flutter SDK, though. Is there any chance a feature would land in the Dart SDK dev channel and not be rolled into Flutter SDK for a while?

This would have been an issue a while ago, but for about a year Dart and Flutter and switched to simultaneous releases (branching at the same time, and syncing dev / beta / stable branches).

> For something like record types, for example, I can see us being asked to make sure DartPad supports them as soon as they make it into the dev channel of the Dart SDK (similar to the way we needed to support NNBD before it was available in Flutter) so that there's a link to go in the announcement blog post. I'd get heat from Michael if we lose the ability to do that. 😄

I think having a consistent url for dev + beta releases would make showcasing new features easier (dev.dartpad, beta.dartpad, ...). We could possibly even extend the version file to enable turning on some language experiments (`experiments: ...`).
