### ISSUE TITLE
switch to installing the Flutter (and Dart) SDK from a version file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1715]
We may want to consider switching to provisioning the Flutter (and Dart - see https://github.com/dart-lang/dart-pad/issues/1714) SDK from a data-driven file. This might be something like `//sdk_version.txt` or other - a simple text file in the root of the repo that indicated what SDK version to use.

We could then download and provision that specific version. The download might look something like a git clone and a `flutter version`, or, downloading a tar of an SDK and then running `flutter version` on that.

This would allow for two things:
- decoupling the version of the SDK that we compile and analyze code with from the Dart SDK runtime version we run the server from
- allowing us to easily serve multiple versions of dartpad running different SDK versions - so one codebase could support hosting a `dev`, `beta`, and `stable` version of the Flutter and Dart SDK

cc @domesticmouse

**Comment by domesticmouse** [comment]
Sounds good to me. Having flutter as a sub repo was a"my attempt at making local development easier but your approach sounds cleaner.

**Comment by devoncarew** [comment]
This has been implemented.
