### ISSUE TITLE
Toggling null safety should update the SDK version label

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1719]
Toggling the null safety switch should make a new call to `/version` and update the label in the bottom right:

<img width="417" alt="Screen Shot 2021-01-05 at 4 40 59 PM" src="https://user-images.githubusercontent.com/1145719/103715182-cda6e680-4f74-11eb-8a53-8c189ad5daa3.png">

**Comment by parlough** [comment]
I think you already reported this here - https://github.com/dart-lang/dart-pad/issues/1679
