### ISSUE TITLE
Dart analyzer doesn't like package:pedantic

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1720]
```bash
$ dart analyze
Analyzing dart-services...             2.7s

warning • The include file package:pedantic/analysis_options.1.9.0.yaml in /Users/brettmorgan/Documents/GitHub/dart-services/analysis_options.yaml cannot be found at analysis_options.yaml:1:11 • (include_file_not_found)
warning • The include file package:pedantic/analysis_options.1.9.0.yaml in /Users/brettmorgan/Documents/GitHub/dart-services/analysis_options.yaml cannot be found at analysis_options.yaml:1:11 • (include_file_not_found)

2 issues found.
```

**Comment by domesticmouse** [comment]
Hey @devoncarew any ideas on how to go about debugging this one?

**Comment by devoncarew** [comment]
Hmm, it's odd that it's mentioned twice.

Things I'd check:
- is there a pubspec dep on pedantic?
- does the dep specify at least pedantic 1.9.0?
- was pub run before analysis?
- was analysis run from the root dir of the repo (it shouldn't make a difference, but worth checking)?

**Comment by domesticmouse** [comment]
Is there a pubspec dep on pedantic, of a least v1.9.0?

```
$ grep pedantic pubspec.yaml 
  pedantic: ^1.9.0
```

Was `pub` run before analysis, and was the `dart analyze` run from root dir of the repo?

```
$ pub get
Resolving dependencies... 
Got dependencies!
$ dart analyze
Analyzing dart-services...             5.1s

warning • The include file package:pedantic/analysis_options.1.9.0.yaml in /Users/brettmorgan/Documents/GitHub/dart-services/analysis_options.yaml cannot be found at analysis_options.yaml:1:11 • (include_file_not_found)
warning • The include file package:pedantic/analysis_options.1.9.0.yaml in /Users/brettmorgan/Documents/GitHub/dart-services/analysis_options.yaml cannot be found at analysis_options.yaml:1:11 • (include_file_not_found)

2 issues found.
```

**Comment by parlough** [comment]
I can't reproduce the issue, but this issue on the SDK repository may prove insightful, but I'm not completely sure:

https://github.com/dart-lang/sdk/issues/42910

Perhaps the `example` folder having an analysis_options and trying to include pedantic as well is causing this issue? If you run `pub get` there as well does the issue persist?

**Comment by JlUgia** [comment]
Suffering from the same issue with github.com/google-pay/flutter-plugin in case this can help shed additional light.
