### ISSUE TITLE
Error compiling to JavaScript: XMLHttpRequest error.

### ISSUE THREAD

**Issue by James-Parsons** [dart-lang/dart-pad#173]
Whenever I try to run my own code or a sample I see :
`Error compiling to JavaScript: XMLHttpRequest error.`

I am on Chrome version 41.0.2272.101 m on a Windows 7 laptop

**Comment by lukechurch** [comment]
Is this still happening? 

I don't see anything in the server logs, could you take a look at the network pane in Chrome Developer console and see if it says anything?

Sorry about this.

**Comment by devoncarew** [comment]
I believe fixed with our latest server version.
