### ISSUE TITLE
Unable to run flutter/bin commands after cloning the repo

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#1734]
## What happened?

I was unable to run the `flutter/bin` commands found in [the dart-services README](https://github.com/dart-lang/dart-services). My top-level `flutter/` directory is empty.

## Steps to reproduce problem

1. git clone git@github.com:dart-lang/dart-services.git
2. cd dart-services
3. pub get
4. pub global activate grinder
5. flutter/bin/flutter doctor

### Machine

Operating system: Mac

Version: Darwin Kernel Version 19.6.0

**Comment by domesticmouse** [comment]
Ugh, need to add to the docs the need to activate the flutter sub module. The trick is, depending which tooling you use to check out the repo, this may be done automatically.
