### ISSUE TITLE
Add ability to share easily

### ISSUE THREAD

**Issue by olfek** [dart-lang/dart-pad#1735]
Maybe something like [sharplab.io](sharplab.io) where the code is base64 encoded and put in the URL

**Comment by domesticmouse** [comment]
You hit limits on the size of URLs pretty quickly.

**Comment by RedBrogdon** [comment]
Thanks for filiing a feature request!

As @domesticmouse noted, there's a hard limit for how long a string you can put in a URL. When we tested how much code we could actually pass that way, it was so little that it didn't make sense to implement.

We do have #805 for a sharing mechanism that would work, based on authed-in GitHub gist creation.
