### ISSUE TITLE
Update language used in several places in the repo

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1738]
An automated scan of the repo has revealed some problematic language in a few places:

```
test/sharing/gist_loader_test.dart 10 "master"
lib/embed.dart                     5  "master"
lib/sharing/gists.dart             4  "master"
.github/workflows/dart.yml         4  "master"
doc/readme.md                      3  "master"
README.md                          3  "master"
doc/ci.md                          2  "master"
CONTRIBUTING.md                    2  "master"
web/styles/layout_mixins.scss      1  "master"
web/scripts/require.js             1  "master"
web/dos.yaml                       1  "blacklist"
web/example/embed.html             1  "hang"
web/scripts/require.js             1  "hit"
```

We should clean these up by renaming where possible. The references to "master" will likely be unremovable without switching to using "main" as the primary branch. Now that it's the GitHub default, though, that's a good idea regardless.

**Comment by parlough** [comment]
I'm going to close this as resolved, as DartPad UI and repository both have switched to using `main` and the remaining references are in code to repositories that haven't migrated or for accounting for the aliasing in the frontend.

If anyone notices any further improvements to language that can be made, please let us know in a new issue or open a PR fixing it. Thanks so much!
