### ISSUE TITLE
Enable Flutter auto renderer

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1740]
This is an umbrella issue to track the work required to enable auto rendering. First step, figure out what is required. I have a https://github.com/dart-lang/dart-services/pull/645 that demonstrates Flutter 1.26 (dev channel) works as expected with `dart-services` using our Bazel based DDC pipeline.

The initial questions I have are:
 - How to make the `dart-services` DDC pipeline generate Flutter code for both HTML and CanvasKit renders? (Dart services does not use `webdev`.)
 - How to configure the code generated in the above step to use a cross origin CanvasKit WASM bundle? (The wasm bundle will probably be hosted alongside the precompiled Flutter and Dart JS binaries that we host in a GCS bucket.)

**Comment by domesticmouse** [comment]
Hey @mariamhas,

I have a version of `dart-services` running Flutter 1.26.0-12.0-pre (aka dev channel) deployed at https://flutter-dev-channel-hdjctvyqtq-uc.a.run.app/ and running a local DartPad against it gives me the following:

<img width="805" alt="Screen Shot 2021-01-27 at 6 07 24 pm" src="https://user-images.githubusercontent.com/30503/105955672-c33ac100-60ca-11eb-8b4e-d24b027ec8e2.png">

I need guidance on what changes we need to make over and above https://github.com/dart-lang/dart-services/pull/645 are required to make auto renderer happen. I have a sneaking suspicion that the auto renderer is not available when compiling with Dart Dev Compiler.

/cc @johnpryan If I remember correctly, you were going to dig into this as well

brett

**Comment by johnpryan** [comment]
> I have a version of dart-services running Flutter 1.26.0-12.0-pre (aka dev channel)

This version should use `auto` by default when using the `flutter run` or `flutter build` commands, but since we're using dartdevc instead of `flutter` to build, we might need to use something like `--dart-define=FLUTTER_WEB_USE_SKIA=true`

cc: @yjbanov do you know if `auto` mode can be set when using `dartdevc` instead of `flutter`? The code we use to compile is [here](https://github.com/dart-lang/dart-services/blob/master/lib/src/compiler.dart#L166).

> I have a sneaking suspicion that the auto renderer is not available when compiling with Dart Dev Compiler.

This should be working - CanvasKit works with DDC.

**Comment by domesticmouse** [comment]
@johnpryan I implemented @ferhatb's suggested change in https://github.com/dart-lang/dart-services/pull/645/commits/35522ceea5934859e09a1352655e98b50dbe66db but I'm still not seeing the auto-renderer. 

If you can see something I'm doing wrong, please feel free to markup the PR. Thanks!

**Comment by johnpryan** [comment]
I'm not sure... It looks like [FLUTTER_WEB_AUTO_DETECT](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L143) is the correct dart-define, but I'm not sure if prefixing it with `-D` is the correct way to set it.

**Comment by domesticmouse** [comment]
I'm digging through https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/bin/dartdevc.dart looking for how dart defines are supposed to be handed to `dartdevc`, but I'm not having a whole lot of luck.

**Comment by ferhatb** [comment]
@domesticmouse: @sigmundch  might be able to help with dartdevc.

**Comment by RedBrogdon** [comment]
@nshahan has also been a great help to me when it comes to dartdevc.

**Comment by sigmundch** [comment]
dartdevc [has support][1] for `-Dx=y` on the command line and I believe it should work when compiling from sources. However, it appears you are using DDC here to compile an SDK from a `.dill` file. I haven't verified this, but my hunch is that DDC may be assuming that all environment definitions are previously provided when the `.dill` file was created. Dart2js, in contrast, can performs constant evaluation a bit lazily to support providing this later, but I don't believe DDC supports it if I recall correctly.

[1]: https://github.com/dart-lang/sdk/blob/0c3696d76a4431e90216fb28453ad4fe693aa83d/pkg/dev_compiler/lib/src/kernel/command.dart#L733

**Comment by sigmundch** [comment]
Another possibility is that we do support this from .dill (there are scenarios where this could work and scenarios where it wont), but the `.dill` file may have been built in a way that forced evaluation of these constants eagerly and as a result we can no longer provide a value for then (constant evaluation replaced them with the default value).

@ferhatb - is this flag always meant to be true whenever using DDC or only in some contexts? If it is always meant to be true, it could be set in the build rules so that the .dill file has the right value?

@domesticmouse - is the .dill file you use built also by dart-services, or is it retrieved from an existing SDK? if it's built locally, we could build it with the flag enabled.

**Comment by domesticmouse** [comment]
@sigmundch Ahh, I think I am holding the tool wrong. I actually added the flag to the step where I generate the dill file: https://github.com/domesticmouse/dart-services/blob/flutter-dev-try-out/tool/grind.dart#L210

```
build-storage-artifacts
  /Users/brettmorgan/Documents/GitHub/dart-services/flutter/bin/flutter pub get
  Running "flutter pub get" in flutter_web_sampleD7d2il...
   1,899ms
  /Users/brettmorgan/Documents/GitHub/dart-services/flutter/bin/flutter precache --web
  /Users/brettmorgan/Documents/GitHub/dart-services/flutter/bin/cache/dart-sdk/bin/dartdevc -s /Users/brettmorgan/Documents/GitHub/dart-services/flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd -DFLUTTER_WEB_AUTO_DETECT=true -o flutter_web.js package:flutter/material.dart package:flutter/foundation.dart package:flutter/widgets.dart package:flutter/gestures.dart package:flutter/painting.dart package:flutter/physics.dart package:flutter/cupertino.dart package:flutter/semantics.dart package:flutter/rendering.dart package:flutter/scheduler.dart package:flutter/animation.dart package:flutter/services.dart package:flutter_test/flutter_test.dart
  copying /Users/brettmorgan/Documents/GitHub/dart-services/flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/amd/dart_sdk.js to artifacts
  copying /var/folders/yx/p5zw_q4x561g718ttqx7bs4c003nrc/T/flutter_web_sampleD7d2il/flutter_web.js to artifacts
  copying /var/folders/yx/p5zw_q4x561g718ttqx7bs4c003nrc/T/flutter_web_sampleD7d2il/flutter_web.dill to artifacts
```

So I should be applying this change to the run time dartdevc run instead or as well as the above change?

**Comment by sigmundch** [comment]
Sorry, I realize now that there are two .dill files at play here. We have one for the sdk  `flutter_ddc_sdk.dill` and one for flutter_web. 

It seems like the code that uses `bool.fromEnvironment('FLUTTER_WEB_AUTO_DETECT')` is in `dart:ui`, which is in the `flutter_ddc_sdk.dill`. 

I believe we need the flag either when that SDK .dill file is created or when the corresponding dart_sdk.js is created.

**Comment by domesticmouse** [comment]
I've now added the flag at both creation of the dill and js files, per https://github.com/dart-lang/dart-services/pull/645/commits/35522ceea5934859e09a1352655e98b50dbe66db, and now also at runtime: https://github.com/dart-lang/dart-services/pull/645/commits/c2d388443e70b1b83ee8b72b99786ff4e9aef52e

And I'm still seeing `html (requested explicitly)` in the html elements tree.

**Comment by sigmundch** [comment]
@domesticmouse - thanks for the update. Sorry for the back and forth while we try to understand your setup. I think we are missing one piece.

So far I see that you added the flag in the following places:
* a step to compile the flutter libraries (generates `flutter_web.js`) - sorry I misunderstood earlier and thought this step was building the sdk itself, but I was mistaken.
* a step to compile the application code (generates `main.dart.js`)

We are missing the step that builds the SDK itself (`dart_sdk.js`), which is the .js file containing the `dart:ui` code that uses this flag. While passing the flag in the two places above doesn't hurt, I believe you only need it when building the `dart_sdk.js` one, so I'd recommend removing the extra unnecessary flags to avoid confusion in the future.

Looking at: https://github.com/dart-lang/dart-services/blob/f23490f80d619496c176cd3820575ef4e9124ddb/tool/grind.dart#L235 it appears that you don't build this in dart-services, but that you copy the file from a prebuilt flutter sdk.

Looking at flutter/engine, it seems like that sdk is built forcing the rendered to be html and not auto nor skia:
https://github.com/flutter/engine/blob/f6d99ea1937e1e8695a000e81110d0c5fca01ed0/web_sdk/BUILD.gn#L185

@ferhatb - could this build step be updated to default to `auto` instead? If not, @domesticmouse - could you build a new copy of the sdk in dart-services that has the right flags? If I understand correctly, I believe flutter-tools builds locally a copy as well (/cc @jonahwilliams to confirm).

**Comment by jonahwilliams** [comment]
There are multiple prebuilt SDKs: web-render mode * null-safety mode, you want the canvaskit-html version. see the directory `bin/cache/flutter_web_sdk/kernel/`:

```
amd				amd-canvaskit-html-sound	flutter_ddc_sdk.dill		legacy-canvaskit		legacy-canvaskit-sound
amd-canvaskit			amd-canvaskit-sound		flutter_ddc_sdk_sound.dill	legacy-canvaskit-html		legacy-sound
amd-canvaskit-html		amd-sound			legacy				legacy-canvaskit-html-sound
```

**Comment by sigmundch** [comment]
Ah, thanks @jonahwilliams! I totally missed that it's already being built!

@domesticmouse, seems like all the bits are in place. Does is start working if you update https://github.com/dart-lang/dart-services/blob/f23490f80d619496c176cd3820575ef4e9124ddb/tool/grind.dart#L235 to point at `bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/amd-canvaskit-html/dart_sdk.js`?

**Comment by domesticmouse** [comment]
With https://github.com/dart-lang/dart-services/pull/645/commits/430c6cee6b902233b690cf2b74eaddafde68a19d it appears that we have a working version. Screenshot of the Sunflower sample:

<img width="609" alt="Screen Shot 2021-02-02 at 2 39 01 pm" src="https://user-images.githubusercontent.com/30503/106549216-9c660a00-6564-11eb-96a9-ab0917eb7f73.png">

And from the Chrome DevTools Elements inspector:

<img width="773" alt="Screen Shot 2021-02-02 at 2 39 42 pm" src="https://user-images.githubusercontent.com/30503/106549238-a982f900-6564-11eb-8532-14bd7870474a.png">

(The displayed Dart version is from

**Comment by domesticmouse** [comment]
DartPad is now serving Flutter 1.26 with auto renderer. Closing out.
