### ISSUE TITLE
flutter.new (dartpad) "hello world" example only renders "Hello" when zoomed != 100%

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/dart-pad#1741]
When going to flutter.new and pressing the "run" button I get this:

![image](https://user-images.githubusercontent.com/20773519/105814644-005f6000-5fb2-11eb-83b3-13531aa23acc.png)

My browser is zoomed to 110%. Zooming to 100% shows the whole "Hello, World!", but 90%, 80%, 125% etc also shows only "Hello".

This is on a Chromebox with Chrome "Version 87.0.4280.142 (Official Build) (64-bit)".
I can't reproduce on my Linux desktop with Chrome "Version 88.0.4324.96 (Official Build) (64-bit)" though.

Note: The above is a verbatim duplicate of https://github.com/flutter/flutter/issues/74704 --- I assume it's a flutter issue, but flutter assumes it's a dart-pad issue and requested that I'd create an issue here.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @jensjoha. I just tried running that code in a "real" Flutter project in Chrome, and was not able to reproduce the issue, so it seems reasonable that it relates to the particular way DartPad executes Flutter code.

I tested the same code in DartPad in my own browser, and did not see it fail until smaller zoom levels (67%), with no failure on higher ones.

**Comment by domesticmouse** [comment]
@RedBrogdon did you attempt replicating using DDC through `webdev` to force HTML renderer?

**Comment by parlough** [comment]
I'm going to close this as stale as DartPad now seems to be showing the full "Hello, World!" for me no matter the zoom level on a few different browsers. Please reopen with new reproduction details if you're still experiencing this issue. Thanks!
