### ISSUE TITLE
Add links to diagnostic message explanations

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-pad#1742]
The analyzer has documents explaining what some diagnostics mean. In our IDE plugins we generate links to these docs. We should also link to these docs from diagnostics in dartpad.

For example: https://dart.dev/tools/diagnostic-messages#unchecked_use_of_nullable_value

**Comment by devoncarew** [comment]
I believe this is a dup of https://github.com/dart-lang/dart-pad/issues/1676.
