### ISSUE TITLE
The "flash"/"hint"/"test results" popup CSS seems to be incorrect

### ISSUE THREAD

**Issue by theacodes** [dart-lang/dart-pad#1754]
## What happened?

This looks weird! 👽 

<img width="646" alt="Screen Shot 2021-02-11 at 3 18 33 PM" src="https://user-images.githubusercontent.com/250995/107695925-476e7600-6c7f-11eb-81d7-ce236df24e88.png">

## Steps to reproduce problem

Head over to https://dart.dev/codelabs/dart-cheatsheet#using-this-in-a-constructor and hit "hint" on any of the embedded Dart Pads. This also appears when you "solve" the challenge and Dart Pad notifies you.

### Browser

I reproduced this in both Chrome (88.0.4324.146) and Safari (Version 14.0.3 (15610.4.3.1.6, 15610)).

### Machine

Operating system: macOS

Version: 10.15.7

**Comment by parlough** [comment]
I believe this was due to my changes moving away from Octicons, I'll take a look. 

Thanks for pointing this out! I thought this situation worked fine...oops

**Comment by theacodes** [comment]
CSS is an ancient evil that lashes out at the slight provocation. No
apologies necessary!

I'm happy to be the reviewer on the change. :)
