### ISSUE TITLE
Improve DartPad's runtime and compile time error reporting

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1762]
This is an epic issue intended to represent [all the others that have been given the "error messaging" label](https://github.com/dart-lang/dart-pad/issues?q=is%3Aissue+is%3Aopen+label%3A%22error+messaging%22). They all relate to how DartPad reports runtime exceptions and compiler errors to the console.

As part of our upcoming work, we should investigate how to make sure every error or exception is correctly reported to the console, and close as many as possible.

**Comment by johnpryan** [comment]
Let's close this issue and keep using the error messaging label to track these.
