### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1764]
Add the ability to import Firebase plugins for Flutter. This will piggyback on #901, but require front-end work to import the JS Firebase SDKs used by the plugins.

Not every Firebase service makes sense for DartPad, but at the very least, Core, Auth, and Cloud Firestore/RTDB would be candidates.

Because the Firebase initialization block can be a pain to type out, some UI sugar should probably be added (a button to inject the code or paste it to the clipboard, an additional "Firebase on/off" checkbox when creating a new Flutter pad).

**Comment by devoncarew** [comment]
@RedBrogdon - should this be a P0? I don't know what that really means wrt an enhancement issue.

**Comment by RedBrogdon** [comment]
I'm using p0 and p1 here as if they exist only for this project, rather than as things that need to be calibrated with other dart-lang repos.

Is there a reference for how levels are normally assigned team-wide? If so, I'll align this project with it.

**Comment by srawlins** [comment]
Woohoo! Calling this done. Please open new issues for any bugs.
