### ISSUE TITLE
Switching from non-null-safe mode to null-safe causes Flutter execution failure

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1765]
## What happened?

Switching back and forth between null safety and non-non safety caused a Flutter snippet to fail to execute.

## Steps to reproduce problem

1) Load dartpad.dev, turn null safety off.
2) Use the sample selector to load a Flutter sample
3) Run sample.
4) Switch null safety on.
5) Use sample selector to load a different Flutter sample
6) Hit run button
7) Code compiles, but fails to execute.

### Browser

Browser: Chrome 88.0.4324.150 (Official Build) (x86_64)

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Uncaught Error: Assertion failed: "The null safety mode of the Dart SDK module (unsound) does not match the null safety mode of this module (sound)."
    at Object.throw_ [as throw] (dart_sdk.js:5331)
    at Object._checkModuleNullSafetyMode (dart_sdk.js:5273)
    at load__dartpad_main (<anonymous>:63:8)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.enable (require.js:1176)
    at Object.enable (require.js:1557)
    at Module.<anonymous> (require.js:1161)
    at require.js:134
    at each (require.js:59)
    at Module.enable (require.js:1113)
    at Module.init (require.js:788)
    at require.js:1460
```

### Machine

Operating system: macOS

Version: 10.15.7 (Build 19H114)

### Your code

What code was in the editor, if any, when the failure occurred? I used the Draggable and implicit animations samples.

### DartPad's output

When the bug manifested, there was no output other than the console saying "Script error."

**Comment by RedBrogdon** [comment]
This does not occur with Dart code.

My guess is that our use of hot restart with DDC is keeping the non-null safe version of the Dart SDK in memory and attempting to run the user's opted-in code with it, causing the failure. We need a mechanism to force a complete reload when the switch is flipped.

**Comment by domesticmouse** [comment]
Shouldn't the front end switch to the null safe backend when the user toggles the null safe switch? 

I'm pretty sure I've seen the sample selector still vend non null safe samples after selecting null safe mode. Reloading the page fixed things for me tho.

**Comment by RedBrogdon** [comment]
> Shouldn't the front end switch to the null safe backend when the user toggles the null safe switch?

It does, but I don't believe it completely clears the state of the injection iframe, which would then attempt to hot restart opted-in code into a non-opted-in version of the SDK (or vice versa):

https://github.com/dart-lang/dart-pad/blob/master/lib/services/execution_iframe.dart#L149

This is just a theory, I should mention, since I haven't had time to dig in.

**Comment by srawlins** [comment]
pre-null safe support has gone the way of the dinosaurs.
