### ISSUE TITLE
Load code from GitHub repo (into playground)

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1769]
Embeds currently can load snippets from a GitHub repo, but in some cases it might be valuable to load snippets into the main dart.dev page. 

Related issues:

- https://github.com/flutter/gallery/issues/264
- https://github.com/dart-lang/dart-pad/issues/1763

**Comment by RedBrogdon** [comment]
The main page also isn't able to load from the API Doc server, though the embeds are. Consider adding that to the playground as well, to give them parity.

**Comment by parlough** [comment]
Closing this in favor of https://github.com/dart-lang/dart-pad/issues/2702#issuecomment-1791322473 which tracks a lighter weight embedding mechanism that supports an "Open in DartPad" feature.
