### ISSUE TITLE
Null safe version of sunflower example needs to be updated to address lints

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#1771]
The null safe version of the Sunflower example currently has a lot of lints triggered.

![image](https://user-images.githubusercontent.com/18372958/108546604-f974f600-72ae-11eb-910b-1c0a5b2de9f0.png)

@johnpryan Updated the non-null safe version to solve these at https://gist.github.com/johnpryan/b3ccb26497ac84895540185935ed5825/revisions

@RedBrogdon Could you update your null safe version here: https://gist.github.com/RedBrogdon/e0a2e942e85fde2cd39b2741ff0c49e5

**Comment by devoncarew** [comment]
@parlough - where is this referenced from? @RedBrogdon - can you update your gist? Or perhaps, @johnpryan, we can point the example reference to your updated gist.

**Comment by parlough** [comment]
@devoncarew This occurs when the user has null safety toggled and selects the "Sunflower" example. It's included as a `Sample` here: https://github.com/dart-lang/dart-pad/blob/master/lib/playground.dart#L292

**Comment by RedBrogdon** [comment]
I've updated the gist to remove the offending code.

**Comment by parlough** [comment]
Thanks!
