### ISSUE TITLE
Async/await library.loadLibrary() does not work as expected.

### ISSUE THREAD

**Issue by Jmsil** [dart-lang/dart-pad#1773]
The code below works if compiled for web from Android Studio (flutter run --release):

import 'dart:math' deferred as math;
void main() async {
  await math.loadLibrary();
  print(math.log10e);
}

DartPad console output:

Uncaught Error: DeferredLoadException: 'Loading main.dart.js_1.part.js failed: [object Event]
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from main.dart.js_1.part.js
 - download failed: main.dart.js_1.part.js (context: js-failure-wrapper)
'

Browser: Microsoft Edge.

**Comment by domesticmouse** [comment]
Mmm something else to add to the list of dart features that DartPad doesn't support.

@devoncarew is there a decent way to sniff this and report an error from the compiler backend?

**Comment by devoncarew** [comment]
Yeah, I would add to our docs as things that aren't supported by dartpad.

For better reporting, we might intercept the compile request, do a spot check of the snippet, and report an error before we pass to the compiler. There is already code to parse the imports using the analyzer; I imagine that could be augmented to see if an import was using deferred.

**Comment by parlough** [comment]
This seems to be working fine now :D 

However, I wouldn't rely on this as supported behavior in DartPad, which is best for trying out simple snippets.

Thanks for the report and reproduction snippet! If you're still seeing this or other issues, please let us know with reproduction details.
