### ISSUE TITLE
allow sharing via github repositories

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/dart-pad#1779]
at the moment, to share the dart pad we need to create a gist for it

i propose that we could also host a dart pad from any other git resourse, for example i have a repository which contains examples and reproducibles for all kinds of issues i need, to not clutter my github account

i would like to be able to specify a url to github ref (for example https://github.com/nt4f04unds-archive/issues/tree/flutter_71342) and host the pad like that

**Comment by RedBrogdon** [comment]
Thanks for the feature request, @nt4f04uNd.

For embedded DartPad iframes, it's possible to switch between themes [via query string params](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#query-parameters). This feature has not yet been implemented for the main DartPad UI.

We're currently tracking this feature request at #1260, so I'm going to close this one as a duplicate.

Thanks!
