### ISSUE TITLE
Documentation shouldn't update during selection

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#178]
@kasperpeulen to consider:

Documentation during navigation is great.
Documentation during selection is more distracting than useful

If you click on a point and Shift-navigate, then the documentation panel jumps around. It's unlikely during a selection operation that the user is engaging in exploration.

Can we try turning off navigation updates during selection activities?

**Comment by kasperpeulen** [comment]
@lukechurch sounds reasonable, maybe adding the extra condition `editor.document.doc.getSelection(context.dartSource).length == 0` ?

So that we have:

```dart
if (_isCompletionActive || [KeyCode.LEFT, KeyCode.RIGHT, KeyCode.UP, KeyCode.DOWN].contains(e.keyCode)) {
  if (editor.document.doc.getSelection(context.dartSource).length == 0) {
    _handleHelp();
  }
}
```

**Comment by kasperpeulen** [comment]
would be fixed with this PR: https://github.com/dart-lang/dart-pad/pull/199
