### ISSUE TITLE
print(DateTime.now()); displaying error

### ISSUE THREAD

**Issue by kamleshwebtech** [dart-lang/dart-pad#1780]
print(DateTime.now()); is displaying below error in right column: 

Error compiling to JavaScript:
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
lib/main.dart:1:19:
Error: Expected an identifier, but got '('.
print(DateTime.now());
                  ^
lib/main.dart:1:22:
Error: Expected a function body or '=>'.
print(DateTime.now());
                     ^
lib/main.dart:1:7:
Error: Type 'DateTime.now' not found.
print(DateTime.now());
      ^^^^^^^^^^^^
lib/main.dart:1:7:
Error: 'DateTime.now' can't be used as a type because 'DateTime' doesn't refer to an import prefix.
print(DateTime.now());
      ^^^^^^^^^^^^
Error: No 'main' method found.
Error: Compilation failed.

Any suggestion, what is the issue. Thanks.

**Comment by parlough** [comment]
Dart programs need a main method to know what and where to start execution as indicated by the "Error: No 'main' method found" part of the error you provided.

If you embed your print statement in a main method, your code should work:

```dart
void main() {
  print(DateTime.now());
}
```

You can find a working example of this on DartPad here: https://dartpad.dev/3314dbe63563b3cb1b9be3cc9ad05f4e?null_safety=true
