### ISSUE TITLE
Add "late" and "required" to syntax highlighter

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1781]
We should add new null-safety keywords to CodeMirror's Dart language mode: https://github.com/codemirror/CodeMirror/blob/master/mode/dart/dart.js

**Comment by parlough** [comment]
I believe @srawlins already did this in https://github.com/codemirror/CodeMirror/commit/8e260c23bcf3f222430f9fae0d22bd0b9fe272e0 and we should already be using a version of CodeMirror with those changes. Are you seeing any problems in particular?

**Comment by johnpryan** [comment]
Ah, good catch. Closing.
