### ISSUE TITLE
Show current URL

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1782]
For samples involving routing, it would be handy to be able to show the current URL somewhere in DartPad.

**Comment by parlough** [comment]
This is an interesting idea, I can definitely see the use cases.

I'm assuming you just want to show the path, query, parameters, etc? (So everything after tld and port)

There's not a lot of space, especially in embedded scenarios, so some sort of button would be nice. Likely defaulting to off, but controllable with a query parameter, as I'm assuming routes aren't a summer common use case.

**Comment by lulupointu** [comment]
This would be great! If you could include back/forward button as well this would be awesome 👌

**Comment by parlough** [comment]
I'm not sure we'll be able to invest the time to implement this, especially with our goal to keep the DartPad UI similar. It's perhaps something interesting to explore for a DevTools extension or IDE plugin though.

If someone would still like to see this though, please feel free to reopen and/or continue the discussion. Thanks!
