### ISSUE TITLE
Null Unsafe analyzer for Dart on stable/v1?

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#1784]
I was working on a  PR to switch to defaulting to null safe code but I realized the switch doesn't do anything anymore and only supports null safety but only for **Dart**. It seems the v1 API endpoint is also serving a null safe SDK. Is this intentional and should we remove the null safety toggles and queries altogether?

**Read @domesticmouse's post below for more context.**

**Comment by domesticmouse** [comment]
Ugh, it's more complex than that. It looks like we accidentally configured the analyzer for dart code on v1 to enforce null safety semantics. The analyzer for Flutter is still null unsafe, as is the Dart2JS compiler that pure Dart code uses to compile. Likewise, DDC on v1 is also null unsafe.

**Comment by parlough** [comment]
@domesticmouse Thanks for the thorough investigation there. I didn't think to test beyond Dart support.

**Comment by domesticmouse** [comment]
Dart Services is a complex beast, it only looks simple from the outside =)
