### ISSUE TITLE
DartPad has no visual affordance for insert/overtype toggle

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart-pad#1792]
Currently DartPad seems to recognize the Insert key and toggles between insertion and overtype modes.  However, there are no visual affordances indicating which mode it's currently in.  It frequently drives me crazy when I expect to insert text and accidentally overwrite text instead.

### Browser

Browser: Firefox 86.0.1 (64-bit)

### Machine

Operating system: Linux

Version: Company-customized distribution based on Debian 5.7.17

**Comment by RedBrogdon** [comment]
Looks like this can be styled by adding CSS to the containing page:

```html
<style>
    div.CodeMirror-overwrite div.CodeMirror-cursor {border: 1px solid red;}
</style>
```

That produces a red cursor, rather than a white one. I'm not sure if we can easily do better than that, but experiments could be done.

**Comment by jamesderlin** [comment]
Looks like this was fixed by https://github.com/dart-lang/dart-pad/pull/2186.
