### ISSUE TITLE
Add the ability to set the target platform

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1793]
The Flutter framework changes its behavior depending the target platform. Drag-to-scroll will likely be disabled on the web, but some snippets may depend on it (See [#71322](https://github.com/flutter/flutter/issues/71322) or [#75729](https://github.com/flutter/flutter/pull/75728))

DartPad could have a dropdown menu item to change the `defaultTargetPlatform` for samples that depend on platform-specific behavior.

**Comment by parlough** [comment]
I'm going to close this as there hasn't been too much interest and we'd rather avoid adding too much configuration to the UI.

I think this is best left to developers through `ThemeData.platform` and/or `debugDefaultTargetPlatformOverride`.

If anyone still feels this is important though, please reopen the issue. Thanks!
