### ISSUE TITLE
Error compiling to JavaScript: unsupported import: dart:io

### ISSUE THREAD

**Issue by aditya305** [dart-lang/dart-pad#1795]
Error compiling to JavaScript:
unsupported import: dart:io

**Comment by parlough** [comment]
Unfortunately [`dart:io`](https://dart.dev/guides/libraries/library-tour#dartio) is not supported on DartPad as it does not support the web platform. Other VM only libraries like `mirrors`, `ffi`, and `isolate` also do not work on DartPad for similar reasons.

You'll have to remove code relying on `dart:io` to get DartPad to work.

We're tracking improvements to this and other errors in a few issues such as: https://github.com/dart-lang/dart-pad/issues/1762, https://github.com/dart-lang/dart-pad/issues/1615, https://github.com/dart-lang/dart-pad/issues/1000

**Comment by patelkrish-27** [comment]
please correct it becasue i started learning flutter but my pc dosen't allow me to run android studio so i thought dartpad will help me but ..

**Comment by ahmadzafar848** [comment]
Use Flutlab.io or zapp.run instead of dartpad
