### ISSUE TITLE
Migrate to null safe Redis client

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1798]
We need a null safe dart Redis client that supports transactions.

`dartis` null safety bug: https://github.com/jcmellado/dartis/issues/34
`resp_client` transaction support: https://github.com/Blimster/resp_client/issues/12

**Comment by CaseyHillers** [comment]
Is the plan to move neat_cache off of dartis to resp_client?

**Comment by domesticmouse** [comment]
I'll migrate `dart-services` to whichever Redis client is both null safe and we can get the test suite to pass with. I've yet to find a package with both attributes.

**Comment by domesticmouse** [comment]
@CaseyHillers Actually, now that I've read your question correctly, I haven't modified `neat_cache`. Dart Services was implemented in terms of `dartis`, but now is implemented in terms of `resp_client` as of https://github.com/dart-lang/dart-services/pull/734
