### ISSUE TITLE
What, No white th----!!

### ISSUE THREAD

**Issue by SulabhShrestha** [dart-lang/dart-pad#1803]
I really don't like black theme. I would love to see "enable white theme" feature.

**Comment by RedBrogdon** [comment]
Thanks for the feature request, @SulabhShrestha .

For embedded DartPad iframes, it's possible to switch between themes [via query string params](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#query-parameters). This feature has not yet been implemented for the main DartPad UI.

We're currently tracking this feature request at #1260, so I'm going to close this one as a duplicate.

Thanks!
