### ISSUE TITLE
Option to hide "null safety " option for embedded dartpads

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#1806]
There's some confusion about what the "null safety" option from the three dot menu does in DartPads embedded in Flutter's API docs. Some people seem to think that toggling that option will change the sample code shown in the dartpad between code that is null safe and code that isn't. This is obviously not true and since our sample code uses null safety features turning off null safety just leads to confusing errors/warnings shown in dartpad.

Can we have an option to hide the null safety toggle for embedded dartpads?

**Comment by RedBrogdon** [comment]
I'm sure we could find a way to hide the switch, though there might be alternatives that make the UX more consistent.

* We could add an option to lock that choice, disallowing users from changing it if the embedder so chooses.
* We could change the label to better indicate what it does ("Use null safety" or "Null safe compilation").
* Possibly something else.

@johnpryan and @zoeyfan, do either of y'all have thoughts on this?

**Comment by johnpryan** [comment]
Option 1 is probably best, but a little heavy-handed. We could also show dialog with more information

**Comment by johnpryan** [comment]
There's probably a few use-cases where a reader would want to mess around with null safety, but I can't think of one.  

We might also want to fix https://github.com/dart-lang/dart-pad/issues/1353, which would give users an "open in DartPad" button, so they can mess around with null safety there instead.

**Comment by zoeyfan** [comment]
I am also leaning towards option 1 (locking the option to be null-safe only) instead of hiding the UX.

**Comment by natebosch** [comment]
Support for non-null safe Dart has been removed entirely. https://github.com/dart-lang/dart-pad/issues/2042
