### ISSUE TITLE
How can we convert string value  into  variable name vice versa? 

### ISSUE THREAD

**Issue by Mehrankhan-METRA-RGB** [dart-lang/dart-pad#1808]
I did this in JavaScript and Python but how to do this in Dart?

**Comment by domesticmouse** [comment]
I'm guessing you used `eval` or equivalent?

**Comment by RedBrogdon** [comment]
While there are [some tricks](https://stackoverflow.com/questions/13585082/how-do-i-execute-dynamically-like-eval-in-dart) to do things like `eval` in Dart, I don't believe this is possible or advisable for DartPad.

**Comment by Mehrankhan-METRA-RGB** [comment]
Ok thanks for the reference RedBrogdon
