### ISSUE TITLE
Implementation work for "Pub packages" / Firebase

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#1813]
I'm starting to get into the "pub package" support for Firebase. So this would be work _towards_ https://github.com/dart-lang/dart-pad/issues/901 but obviously not encompassing that feature request.

**Comment by srawlins** [comment]
I think we want to start with fixed versions for the firebase packages (`firebase_auth`, `firebase_core`, etc) and all of their dependencies (`async`, `intl`, `meta`, `path`, etc).

Currently the `pubspec.yaml` files are generated during the `buildProjectTemplates` task and the `buildStorageArtifacts` task (which depends on the former), but I think we want to control those generated files more closely, as in check into source control the versions of all of the packages, not unlike Flutter's version pinning.

I think the easiest way to do this would be to add a grinder task:

1. New task `updatePubspecTemplates` writes a temporary pubspec.yaml file with dependencies like `firebase_core: any`, runs `pub get` against that temporary file, reads in the resulting `pubspec.lock` file, teasing out the constraint-solved versions of each dependency, and then writing out to a source-controlled pubspec template file.
2. Developer runs this task to update this file (something like `tool/pubspec_template.yaml`).
3. Developer spot checks versions (what does this mean?).
4. Developer checks in changes to `tool/pubspec_template.yaml`.
5. The existing `buildProjectTemplates` grinder task uses `tool/pubspec_template.yaml` instead of the inline String it currently uses.

The versions are then at least known at deploy time and live. We have control over when they bump. We can downgrade a package if desired.

**Comment by domesticmouse** [comment]
Please note, as of https://github.com/dart-lang/dart-services/pull/689 there are four `pubspec.yaml`s. I am supportive of pinning these.

**Comment by parlough** [comment]
If we're pinning versions we should add an API endpoint to get all current package versions. Then we can display them perhaps in a popup when a user clicks the version string in the lower right.

**Comment by domesticmouse** [comment]
@parlough Feel free to raise a PR against me with a sketch of what the API should return. I'm guessing a JSON map keyed by `flutter` and `dart` for the two different targets, and then the packages lifted from the deps section?
