### ISSUE TITLE
Turn down nullsafety.dartpad.dev in Q3 2021

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1821]

**Comment by domesticmouse** [comment]
@RedBrogdon any reason we shouldn't move forward with deleting this instance? It's serving `Dart SDK 2.12.0-51.0.dev`

**Comment by parlough** [comment]
Definitely should switch to redirecting this to the main site I think(conserving query parameters). Almost all code running in 2.12 dev with null safety enabled should run fine on 2.14. The primary exception is code using VM only libraries which are not supported here anyway.

**Comment by domesticmouse** [comment]
@RedBrogdon what do you think of the additional scope to create an argument preserving redirector vs just turning this old service off?

**Comment by domesticmouse** [comment]
Steps:

- [ ] Remove `nullsafety.dartpad.dev` DNS record
- [ ] Turn off Null Safety front end (GAE project?)
- [ ] Turn off backend (Serving from dart-services-beta-0.appspot.com)

**Comment by RedBrogdon** [comment]
Weird. It looks like I can shut it down whenever you'd like. The DartPad engineering alias is listed as an owner, though, you should also have full access.

**Comment by domesticmouse** [comment]
I've shutdown the `dart-services-beta-0.appspot.com` project. Does this also shutter the null safety front end?

**Comment by parlough** [comment]
Since the project was turned down, the only potentially still relevant concern is redirecting from `nullsafety.dartpad.dev` to `dartpad.dev`, but at this point, it's likely barely referenced. Either way, I'll close this as fixed and consolidate the redirect issue as part of https://github.com/dart-lang/dart-pad/issues/2638. Thanks all!
