### ISSUE TITLE
Add UI output parameter to embedded DartPad

### ISSUE THREAD

**Issue by mzdm** [dart-lang/dart-pad#1830]
### Usecase
Sometimes a user knows what is he executing so we want to only show the output without showing the code as it can make it cluttered (for example when running [dynamic code snippets](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad)). To view the code there could be some menu option to turn it back like with null safety,

### Proposal
Add a new option to [query parameters](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#options) for embedded DartPads.

for example an enum `ui_output` with available values: `default`, `console`, `ui`, `code`

... or just `show_code` true/false

**Comment by johnpryan** [comment]
Which embed layout are you using? The `embed-dart` layout shows the console by default.

**Comment by mzdm** [comment]
> Which embed layout are you using? The `embed-dart` layout shows the console by default.

According to [wiki](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#embed-darthtml), it shows both code and console by default?

In my case I'm mostly using injected DartPad inside a web page with mode `flutter`:
`<script type="text/javascript" src="https://dartpad.dev/inject_embed.dart.js" defer></script>`

```
<code class="language-run-dartpad:mode-flutter:run-true:split-50:null_safety-true">
   some code ...
</code>
```

When using this approach there [does not seem to be a way to specify](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#options) the UI output. And `split` only does not work with values 0 or 100

**Comment by johnpryan** [comment]
Does changing `mode-flutter` to `mode-dart` do what you need? Or are you trying to show console output for a snippet that uses `package:flutter`?

**Comment by mzdm** [comment]
> Does changing `mode-flutter` to `mode-dart` do what you need? Or are you trying to show console output for a snippet that uses `package:flutter`?

yup, need this specifically for snippets that use `package:flutter`

Just noticed that there's already an issue for that https://github.com/dart-lang/dart-pad/issues/1234
