### ISSUE TITLE
DartPad is not printing anything

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart-pad#1841]
I went to https://dartpad.dartlang.org/, entered:

```dart
void main() {
  print('hello');
}
```
clicked Run, and nothing happened.  This happens regardless of the Null Safety toggle.  I tried this with Firefox 88.0 and with Chrome Version 90.0.4430.85 (Official Build) (64-bit) on Linux.

**Comment by parlough** [comment]
@srawlins Do you think your change here https://github.com/dart-lang/dart-pad/commit/41b1caecf78559efd34fb678652d938c79d31a64 could have caused this?

**Comment by tamoyal** [comment]
same issue here

**Comment by augustkimo** [comment]
It isn't printing for me either ~ seems to be down.

**Comment by jamesderlin** [comment]
To reduce comment spam, please thumbs up instead of adding "Me too"-like comments.

**Comment by iLoveDocs** [comment]
@jamesderlin Mine is working (with and without null-safety)

![image](https://user-images.githubusercontent.com/65380329/116465288-51ab1400-a86d-11eb-8fd9-8895a8062e1d.png)

**Comment by johnpryan** [comment]
I've rolled this back and will be testing #1842 before re-deploying. Thanks for filing an issue.

**Comment by srawlins** [comment]
Ooh good catch. Apologies!
