### ISSUE TITLE
Show Flutter/Dart version used for embedded dartpad

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#1846]
Standalone dartpad shows the Flutter/Dart version used in the bottom right corner. That information may also be useful to display for the embedded dartpad.

See also https://github.com/flutter/flutter/issues/81507.

**Comment by parlough** [comment]
Thanks for the suggestion! I'm going to consolidate this issue in to https://github.com/dart-lang/dart-pad/issues/3007 which proposes a general information button for channel, SDK versions, etc.
