### ISSUE TITLE
import Dart:io is not working

### ISSUE THREAD

**Issue by rakesh-byte** [dart-lang/dart-pad#1848]
I was just doing simple input output from user and I Imported dart:io but it specified **_Unsupported import._** 
And when I Compiled the code **_"Error compiling the java code"_**.

Can anybody tell me what are the alternatives of dart:io for I/O?

**Comment by domesticmouse** [comment]
I'm curious to understand where you got the *Error compiling the java code error* message from. There is no Java involved in DartPad. Maybe *Error compiling the JavaScript code*?

**Comment by domesticmouse** [comment]
As to `dart:io`, it is not supported by Flutter Web. See https://api.flutter.dev/flutter/dart-io/dart-io-library.html
