### ISSUE TITLE
Is there no way to load font dynamically on runtime?

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1849]
Currently dartpad includes font file, but let's say, in a higher order js app, dartpadd app emmits used fonts event, and loads the font from js app. Is this a theoretically possible scenario?

**Comment by domesticmouse** [comment]
The font asset that we are currently loading is bundled into the DartPad web app. 

So, to load a font dynamically would require flutter for web to understand how to load fonts outside of the assets folder. 

I'd suggest raising a request on the flutter/flutter issue tracker.

**Comment by softmarshmallow** [comment]
Yeah i'm building flutter web executor (clone of dart-pad) with this feature.
Here me if i sound stupid.


1. Pre inspect the dart source and find the font being used.
2. Load the font on web app
3. Re load dart pad app

Cause as i understand dart pad is simply running in a html iframe, if only html is capable of loads the font, then isn't it possible to do so?

**Comment by domesticmouse** [comment]
If only it were that simple

**Comment by RedBrogdon** [comment]
It may be possible once package support lands to enable support for the [google_fonts](https://pub.dev/packages?q=google_fonts) package, which would allow for downloading Google fonts on the fly.

While we could theoretically modify the manifest file used by DartPad, it would not be feasible (IMHO, anyway) to add enough individual fonts to really satisfy anyone, nor could we allow for the list to be modified on on a per-user basis.

I'm going to close this issue for now, but when we launch package support, we'll make sure google_fonts is considered for the list of supported packages.
