### ISSUE TITLE
Error "undefined is not a function" shouldn't happen in Dart code

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#186]
Hi,

Please see screenshot. Is there anything we can do to hide JavaScript errors like this?

![screen shot 2015-03-28 at 3 04 23 pm](https://cloud.githubusercontent.com/assets/5479/6883111/d5071ed4-d55b-11e4-8845-6e713bcc4477.png)

**Comment by devoncarew** [comment]
This is coming from the dart2js compiled output. I'm not sure that dartpad should really do any post-processing of the errors. Adding @floitschG

**Comment by sethladd** [comment]
The error, as is, is really misleading and confusing. Dartpad should give the users actionable feedback at all times. It's our job to turn the opaque error into something useful :)

Couple of thoughts:

Can we make it more obvious that the error is a JS error from Chrome, not an error "from Dart" ?

Can we use the source maps file to link back to the line in the source?

**Comment by lukechurch** [comment]
I'd like to use the inference backends to do some post-processing of the errors to test various ways of making them more actionable. But that does need to be an entirely separable component and we don't quite have the data we need yet to make it work properly. Getting there....

**Comment by sethladd** [comment]
@lukechurch sure, that's a great long-term plan. In the meantime, can we use source maps to connect the error back to the source line? Also, can we add some context to the error message? (e.g. "Error from JavaScript: ...")

**Comment by rakudrama** [comment]
I suspect the problem is that there is no inYears getter on Duration.
The first time the Dart runtime sees this kind of error is at the catch
clause of a try-catch clause.
Only at teh catch is the JS TypeError converted into a Dart
NoSuchMethodError.
If you rename main to _main and use

main() {
  try {
    _main();
  catch (e) {
    throw e;
  }
}

does the problem become more understandable?

**Comment by devoncarew** [comment]
@sethladd, we do have the info and building blocks of the code to reverse dart2js compiled stack traces. Can you file a tracking issue for that, or re-task this one? It'll require some work; I think other chunks of functionality are ahead of it in the queue.

**Comment by devoncarew** [comment]
And if we do add `Error from JavaScript:` as a prefix, that'll show for all errors (say, there are more than one in the output). Will that add value or just noise?

**Comment by sethladd** [comment]
If dart2js could give me a more useful error, that would be awesome.

Here's the error I get from the VM:

```
sethladd@sethladd-macbookair ~/tmp/asyncawait $ dart error.dart 
Unhandled exception:
Class 'Duration' has no instance getter 'inYears'.

NoSuchMethodError: method not found: 'inYears'
Receiver: Instance of 'Duration'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Person.age (file:///Users/sethladd/tmp/asyncawait/error.dart:4:59)
#3      main (file:///Users/sethladd/tmp/asyncawait/error.dart:10:11)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:255)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

That's a lot easier to understand.

Here's an idea: can we use dart2js checked mode? When I compile this script with checked mode, I get this error:

![screen shot 2015-03-29 at 7 19 58 am](https://cloud.githubusercontent.com/assets/5479/6886014/16157a96-d5e4-11e4-8ecb-4e519f6e6bcf.png)

That's more useful than "undefined is not a function"

**Comment by devoncarew** [comment]
I filed an issue here: https://github.com/dart-lang/dart-services/issues/103. Should be sending an additional flag into dart2js.

**Comment by rakudrama** [comment]
Hey guys, please try what I suggested and report the results.
Using --checked is a red herring.  It is reporting a different error for a
different problem.
It does not solve the problem of translating the JavaScript TypeError into
a Dart NoSuchMethodError.
(It is not "more useful" in any useful sense -  uf you change 'Date' to
'var', you will be back to the first problem.)
Can you verify that catching and rethrowing the exception does the trick?
If so, perhaps the solution is to make dartpad call main from a
try-catch-rethrow.

--Stephen (sra)

**Comment by devoncarew** [comment]
@rakudrama, I'll re-test w/ what you're suggesting. You might want to add your name info here: https://github.com/settings/profile, so people will know who you are :)

**Comment by devoncarew** [comment]
https://dartpad.dartlang.org/b1e42f1923ece0eabeff

The error changes to `Uncaught NoSuchMethodError: undefined is not a function` (from `Uncaught TypeError: undefined is not a function`).

**Comment by devoncarew** [comment]
And this guy:

https://dartpad.dartlang.org/58cbd0407b325990390e

produces this error:

```
Warning: 'inYears' is used reflectively but not in MirrorsUsed. This will break minified code.
Uncaught NoSuchMethodError : method not found: 'Symbol("inYears")'
Receiver: Instance of 'Duration'
Arguments: []
```

using a `noSuchMethod` trick from @rakudrama

**Comment by devoncarew** [comment]
For the above:
- we'll want a flag in dart2js which can force the NSM behavior (force the noSuchMethod stubs)
- we don't want the mirrorsused warning
- it probably shouldn't say `'Symbol("inYears")'`

**Comment by kasperpeulen** [comment]
Not a real solution to the problem, but something to consider.

I think dart programming and dart debugging in "real life" rarely involves looking at javascript errors. We already got quality errors and warnings even before running the code, maybe we should also make it more obvious that this is first to look at if you want to debug the program. For example, maybe we could show all the dart analysis issues and warning in the console before the javascript errors.

Something like:
```
Dart errors:
[warning, line 2]: Undefined class 'Date'
[warning, line 4]: The getter 'inYears' is not defined for the class 'Duration'

Javascript errors:
Warning: 'inYears' is used reflectively but not in MirrorsUsed. This will break minified code.
Uncaught NoSuchMethodError : method not found: 'Symbol("inYears")'
Receiver: Instance of 'Duration'
Arguments: []
```

**Comment by floitschG** [comment]
As rakudrama states: the checked-mode error is completely unrelated.
Dart2js does not add all nsm handlers if it can avoid it. We don't intend to add a new flag to force them when they are not needed.
The `undefined is not a function` message is not just a JS error. It is an error in your program.

Unfortunately the error-message that v8 produces regressed at some point, but was recently fixed:
https://code.google.com/p/chromium/issues/detail?id=259443
https://twitter.com/addyosmani/status/569157136137134081
https://codereview.chromium.org/920133002
