### ISSUE TITLE
Canvaskit files are reloaded after every run

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1860]
Each time the user re-compiles their code, the app makes unnecessary requests to fetch `canvaskit.js` and `canvaskit.wasm`:

<img width="295" alt="Screen Shot 2021-05-05 at 4 58 39 PM" src="https://user-images.githubusercontent.com/1145719/117223750-325b3c00-adc3-11eb-8fb2-5b11fd30acb8.png">

[Latest master](https://20210505t165113-dot-dart-pad.appspot.com/) also reloads the fonts and icons:

<img width="299" alt="Screen Shot 2021-05-05 at 4 56 51 PM" src="https://user-images.githubusercontent.com/1145719/117223623-e6a89280-adc2-11eb-902f-37e9691f40bf.png">

This might be because we are replacing the HTML (https://github.com/dart-lang/dart-pad/pull/1838)

**Comment by srawlins** [comment]
Hi @johnpryan can you expand on this? I'm not seeing canvaskit anywhere in our codebase:

```none
dart-pad$ git grep -i canvaskit
dart-pad$
```

**Comment by srawlins** [comment]
Oops you assigned to yourself, likely nevermind!

**Comment by johnpryan** [comment]
Flutter web apps request CanvasKit at startup. @hterkelsen is there a way to disable this so we can load these files once?

@srawlins when we reload the iframe, does that trigger another request to fetch the Firebase JavaScript files?

**Comment by hterkelsen** [comment]
Yes, we can detect if there is an already-initialized CanvasKit object and use that rather than loading CanvasKit again. Can you tell me a little more about how you use Flutter web in DartPad? If I set e.g. `window._flutterCanvasKit = ...` will that value still be there in the next run?

**Comment by johnpryan** [comment]
We usually keep the same `<iframe>` element (https://github.com/dart-lang/dart-pad/issues/1817) and send it messages with the new javascript, html, and css from the parent document. Then we have a script, [frame.js](https://github.com/dart-lang/dart-pad/blob/master/web/scripts/frame.js), running in the iframe that listens to those messages and updates script tag containing the app's compiles javascript. When the new script runs, a new `<script>` tag for `canvaskit.js` is added to the page, so we end up getting duplicates. JavaScript variables are kept around across runs, since it's the same iframe.
