### ISSUE TITLE
Dartpad Issue - Unsupported Import

### ISSUE THREAD

**Issue by ChillyChaos** [dart-lang/dart-pad#1862]
error is as appears:

line 1 - Unsupported import(s):
(package:flutter_test/flutter_test.dart)

**Comment by Jstuff36** [comment]
+1, seeing the same thing for the layout basics codelab on Chrome for mac version 90.0.4430.93 (Official Build) (x86_64)

**Comment by RedBrogdon** [comment]
Thanks for reporting this.

@srawlins it looks like one of the recent changes for imports may have excluded `package:flutter_test/flutter_test.dart`, which some of our Flutter codelabs rely on for their exercise completion checks.

Example: https://flutter.dev/docs/codelabs/layout-basics

**Comment by srawlins** [comment]
I'm on it. Apologies for the breakage.

**Comment by srawlins** [comment]
I would think that the culprit of this breakage is https://github.com/dart-lang/dart-services/commit/3cf859547c5276e638ccc8af1357c294c07fabfb but I don't think that change is deployed yet. Possibly https://github.com/dart-lang/dart-services/commit/f5f24c52a12e1cc764634dc9581cd8cc7a94b958 but I don't see how that caused the problem. I've uploaded two PRs which should help but may not necessarily solve. Still investigating.

**Comment by domesticmouse** [comment]
Actually, it has auto-deployed on the null safety endpoint. Look at https://pantheon.corp.google.com/run/detail/us-central1/dart-service-cloud-run-null-safety/revisions?project=dart-services

The non null-safe version is still running on the prior version: https://pantheon.corp.google.com/run/detail/us-central1/dart-service-cloud-run/revisions?project=dart-services

We can roll back the null-safe end point to dart-service-cloud-run-null-safety-00014-nac to revert

**Comment by srawlins** [comment]
I see, thanks @domesticmouse! I also just landed #1868 .

**Comment by srawlins** [comment]
When I paste that codelab into local DartPad with my fixes, seems to work (though I see a very strange "line 3 • Unused import: 'package:flutter_flutter_test.dart'." analysis error)

**Comment by domesticmouse** [comment]
I believe that there is a test script added to the end of the code that is submitted for compilation. I guess this code is not added for analysis. 

Worth raising a bug.

/cc @RedBrogdon as he probably remembers more of this than I do.

**Comment by domesticmouse** [comment]
This should now be fixed with https://github.com/dart-lang/dart-services/pull/701 deployed to production. 

Please comment if this isn't the case so we can continue figuring out what isn't happy.

Thanks all!

**Comment by ChillyChaos** [comment]
Thank you for the fix!

**Comment by domesticmouse** [comment]
Thanks for raising the bug @ChillyChaos!

**Comment by RedBrogdon** [comment]
> I believe that there is a test script added to the end of the code that is submitted for compilation. I guess this code is not added for analysis.

@srawlins, in each exercise in that codelab, there's a test files that's concatenated with the user's code and used to verify whether they've completed the exercise. If you click the "Show tests" menu choice, in the iframe, you'll get access to it as a separate editor tab:

![image](https://user-images.githubusercontent.com/969662/117515698-da037600-af4b-11eb-80a2-409d71c8e3c4.png)

If you paste the main editor's code + the test code into the playground editor, you'll have what the embedded layout sends to the backend for that particular exercise.

In the meantime, I can see the codelab's working again. Great job getting this turned around so quickly.
