### ISSUE TITLE
Keep indentation when copy-pasting code

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1863]
Pasting a snippet without indentation into an indented line should indent the following lines. For example, copy and pasting this snippet:

```dart
var x = 10;
print(x / 2);
```

into a DartPad with this code:

```dart
void main() {
  // paste here:
  
}
```

doesn't indent the `print` statement:

```dart
void main() {
  // paste here:
  var x = 10;
print(x / 2);
}
```

**Comment by parlough** [comment]
Closing this as there hasn't been any further interest in this change and is likely best left to eventually switching to a differently underlying text editor. Feel free to reopen if you think differently or would still like to see this implemented. Thanks!
