### ISSUE TITLE
Add hidden code to DartPad workshops

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1865]
Workshops sometimes have boilerplate code at the bottom of the editor that are unrelated to the content of the workshop. We could add support for a `hidden.dart` or `tests.dart` file along with a `has_tests` option in the metadata file. This code would be hidden from the user and concatenated to the end of the `snippet.dart` and `solution.dart` files when running or analyzing the code.

All editors now have a `fullCode` getter that can be overridden (https://github.com/dart-lang/dart-pad/pull/1856) so the `WorkshopsUi` class could override this method.

FYI @Piinks @chunhtai @RedBrogdon what do you think?

**Comment by chunhtai** [comment]
I think that is a good idea, but we should give user the ability to see the the hidden code.

Another thing i found that hard to use is the cmd+f code search. In mac chrome browser the cmd+f can only find the first occurrence of the key word

**Comment by johnpryan** [comment]
Interesting, when I use cmd+f each occurrence is highlighted, but I need to hit cmd+f and enter again to select the next occurrence. Maybe there should be some UI to select to the next/previous occurrence. I created a separate issue to track: https://github.com/dart-lang/dart-pad/issues/1866

**Comment by RedBrogdon** [comment]
Unless this is particularly urgent, I'd wait until we're through the first round of workshops before deciding to invest in this. 

That's not to say I don't think it's a good idea, just that doing something similar for the embedded layouts for test code introduced a number of complexities, and it'd be good to make this decision when we're not under any kind of time pressure.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires a feature similar to this in DartPad or a new form of workshops, please discuss that in a new issue. Thanks!
