### ISSUE TITLE
Error compiling to JavaScript: Instance of 'minified:fR' in dartpad 

### ISSUE THREAD

**Issue by yashkumarkalyan** [dart-lang/dart-pad#1867]
### Stuck Here Help me Out!!!

![Screenshot 2021-05-07 011140 (1)](https://user-images.githubusercontent.com/82755153/117357253-55284600-aed2-11eb-98ca-5cf6fd7602c2.jpg)

I was on flutter.dev
 website learning flutter and 
it was working right but suddenly shows error .

_Error compiling to JavaScript: Instance of 'minified:fR'._ 

Which is **different from XHTML request error** and help me out because I am unable run even on https://flutter.dev/docs/codelabs/layout-basics page where it is pre-written code. Problem is in Chrome latest version as well in Edge.

**Comment by RedBrogdon** [comment]
Thanks for filing @yashkumarkalyan. This is a recent issue that's popped up and is currently tracked at #1862. I'm going to close this one as a duplicate, but you can expect a fix soon.
