### ISSUE TITLE
Change the visual state or the run button on errors or warnings (was: Can we make the Run button red if there's an error)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#187]
Should I be able to run my app if there's an error? Probably, but we should hint to the user there is an error.

Suggestion:

Make the Run button Red if there's an error in the code.

Make the Run button Yellow if there's a warning in the code.

Make the Run button Green if everything is good to go.

Make the Run button Gray if we're compiling or analyzing.

**Comment by devoncarew** [comment]
I currently does become disabled (w/ some visual indicator) when compiling. Not sure about the UI for the rest of it. Perhaps putting an small icon badge in one corner if there's an error or warning?

**Comment by kasperpeulen** [comment]
@sethladd Something like this ?
![](http://g.recordit.co/yiWcwLrTXl.gif)

**Comment by kasperpeulen** [comment]
Another try, it now disables the button while analyzing:

![](http://g.recordit.co/IesZGFoZKU.gif)

**Comment by sethladd** [comment]
Thanks! Personally, I'm fine with the colors changing. If my program has an
error, I probably don't want to run it. :)

**Comment by lukechurch** [comment]
@sethladd @devoncarew 

The overall idea of providing feedback whether running is likely to work is good.

In terms of specifics, Red is too visually salient. It will actually draw attention to the run button if there is an error, rather than suggesting to the user that it won't work.

We could go for something like a very dark red that is similar to the 'disabled whilst I'm working' level of intensity with a mouse over saying 'there are 3 errors' or something similar.

**Comment by sethladd** [comment]
@lukechurch very dark red works for me. Can we try that now?

I don't think a mouse over will work well. When I'm coding, I'm moving
fast. I'll probably use keyboard shortcuts to run my app. If dartpad is
going to give me feedback, I'd want is visible, with an option to provide
more context for feedback if needed.

**Comment by lukechurch** [comment]
@sethladd 

Sure - we can try red and see what if feels like.

mouse over was really intended to handle a user who was wondering 'why is my run button this colou?r' - not someone who was familiar with the system and coding away. It certainly isn't a suggest to replace the normal error display.

**Comment by sethladd** [comment]
@kasperpeulen could you create a version that uses a dark red and a dark yellow and a dark green?

**Comment by kasperpeulen** [comment]
@sethladd here are some ideas:
https://dartpad.dartlang.org/1a4d74f1b3164e8bf025

here is the gist: 
https://gist.github.com/kasperpeulen/1a4d74f1b3164e8bf025

**Comment by devoncarew** [comment]
fixed: https://github.com/dart-lang/dart-pad/pull/192
