### ISSUE TITLE
Images are not working

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1872]
Images aren't being displayed in the workshop instructions panel. For example The [slivers codelab](https://dartpad.dev/workshops.html?webserver=https://dartpad-workshops-io2021.web.app/getting_started_with_slivers) uses an image on step 2.

The `<a>` tag in the instructions panel doesn't contain an `href` attribute. We are currently using the [markdownToHtml](https://pub.dev/documentation/markdown/latest/markdown/markdownToHtml.html) function from `package:markdown` to generate

**Comment by Piinks** [comment]
Has this been deployed?

**Comment by johnpryan** [comment]
yes, this should be deployed now. Are you still seeing this?
