### ISSUE TITLE
Add grind task for `build_runner serve`

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1873]
https://github.com/dart-lang/dart-pad/pull/1828 changes the way the backend URL is configured to use  `PRE_NULL_SAFETY_SERVER_URL` and `NULL_SAFETY_SERVER_URL` environment variables. When using `pub run build_runner serve` these aren't defined and the `preNullSafetyServerUrl` and `nullSafetyServerUrl` are empty.

**Comment by srawlins** [comment]
:( that's a bummer that they're not kept from the build.yaml: https://github.com/dart-lang/dart-pad/blob/master/build.yaml#L19

Would this be different from `grind serve` or `grind serve-local-backend`? I might just need to add the same ConstTaskArgs to `grind serve`.

**Comment by johnpryan** [comment]
`grind serve` does a full dart2js build, so it doesn't use DDC. I wonder if there's a way to configure build.yaml to use these defaults for DDC too?

**Comment by srawlins** [comment]
Yeah the [build_web_compilers](https://pub.dev/packages/build_web_compilers) talks a lot about that, and I believe it is very complicated 😛 but I'll see if I can get it working.

**Comment by johnpryan** [comment]
It's possible to work around this by setting `preNullSafetyServerUrl` manually in `common.dart`, so this is a lower priority right now.
