### ISSUE TITLE
Use pkg:lints and pkg:flutter_lints when analyzing code

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#1881]
To promote good coding practices and for a consistent experience across the dart ecosystem, dartpad should use the analyzer options defined in the new [`flutter_lints`](https://pub.dev/packages/flutter_lints/versions/1.0.0-dev.0) and [`lints`](https://pub.dev/packages/lints/versions/1.0.0-dev.0) packages when analyzing Flutter code or pure Dart code, respectively.

/cc @mit-mit @pq @devoncarew

**Comment by goderbauer** [comment]
For non-Flutter code I would vote for using [`recommended.yaml`](https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml) over [`core.yaml`](https://github.com/dart-lang/lints/blob/main/lib/core.yaml).

**Comment by goderbauer** [comment]
There's also a discussion here regarding recommended vs core: https://github.com/dart-lang/lints/pull/18#discussion_r630140138

**Comment by mit-mit** [comment]
For Dart code please also use `recommended.yaml` (`dart create` has been updated).

**Comment by mit-mit** [comment]
Being worked on in https://github.com/dart-lang/dart-services/pull/722
