### ISSUE TITLE
Markdown tables are not rendered properly

### ISSUE THREAD

**Issue by Piinks** [dart-lang/dart-pad#1883]
This:
```md
| Box Widget | Sliver Widget |
|---|---|
| ListView  | SliverList |
| GridView | SliverGrid |
| Padding | SliverPadding |
| AnimatedList | SliverAnimatedList |
| FadeTransition | SliverFadeTransition |
| IgnorePointer | SliverIgnorePointer |
```

Usually yields this:

| Box Widget | Sliver Widget |
|---|---|
| ListView  | SliverList |
| GridView | SliverGrid |
| Padding | SliverPadding |
| AnimatedList | SliverAnimatedList |
| FadeTransition | SliverFadeTransition |
| IgnorePointer | SliverIgnorePointer |

But in the dartpad instructions pane looks like this:

![Screen Shot 2021-05-12 at 12 01 49 PM](https://user-images.githubusercontent.com/16964204/118015404-da1fbf00-b319-11eb-9f77-f3dddbb85bc1.png)

Maybe similar to #1872 
FYI @johnpryan

**Comment by johnpryan** [comment]
Fixed by https://github.com/dart-lang/dart-pad/pull/1892
