### ISSUE TITLE
Code highlight should use Courier New font

### ISSUE THREAD

**Issue by chunhtai** [dart-lang/dart-pad#1888]
As the style guide suggest, single quote code highlight should use Courier New font

**Comment by chunhtai** [comment]
cc @johnpryan

**Comment by johnpryan** [comment]
What style guide are you referring to? Are there other style guidelines we need to follow?

**Comment by chunhtai** [comment]
@johnpryan I got this from the tech writer feedback, I pined you in the doc

**Comment by johnpryan** [comment]
Fixed in #1890

**Comment by johnpryan** [comment]
![Uploading Screen Shot 2021-05-14 at 11.19.18 AM.png…]()

**Comment by johnpryan** [comment]
https://github.com/flutter/codelabs/pull/125
