### ISSUE TITLE
FlutterFire Auth

### ISSUE THREAD

**Issue by PaulTR** [dart-lang/dart-pad#1896]
## What happened?

Looks like auth.currentUser might be breaking. I'd expect the currentUser to return null in my sample code so I can show a snackbar about the user not being logged in, but instead the app just stalls. Replacing auth.currentUser on line 48 with final auth.User? user = null moves me along the expected path.

## Steps to reproduce problem

Run the code in dartpad

### Browser

Browser: Chrome 

Version: 90.0.4430.93 (Official Build) (x86_64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? Not that I know of

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below: Nothing related to the issue, but:

```
info
line 41 • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre.. (view docs)
Try replacing the use of the deprecated member with the replacement.
info
line 70 • TODO: UI widgets will go here.
```

### Machine

Operating system: OSX

Version: 11.3.1

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
import 'package:flutter/material.dart';

import 'package:firebase_auth/firebase_auth.dart' as auth;

final auth.FirebaseAuth _auth = auth.FirebaseAuth.instance;

void main() {
  runApp(MyApp());
}

//3
class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Auth Demo',
      home: MyHomePage(title: 'Firebase Auth Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  
//4
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          Builder(builder: (BuildContext context) {
//5
            return FlatButton(
              child: const Text('Nothing to see here'),
              textColor: Theme
                  .of(context)
                  .buttonColor,
              onPressed: () async {
                print("button pressed");
                final auth.User? user = _auth.currentUser;
                if( user != null ) {
                  print("user was not null");
                  await _auth.signOut();
                  final String uid = user.uid;
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                    content: Text(uid + ' has successfully signed out.'),
                  ));
                } else {
                  print("user was null");
                }
              },
            );
          })
        ],
      ),
      body: Builder(builder: (BuildContext context) {
//7
        return ListView(
          scrollDirection: Axis.vertical,
          padding: const EdgeInsets.all(16),
          children: <Widget>[
            //TODO: UI widgets will go here.
          ],
        );
      }),
    );
  }
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:
No

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by parlough** [comment]
Thanks for the report and extensive details. As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, support for Firebase was removed, so I'm going to go ahead and close this issue as stale.

If anyone reading this would like to see Firebase support or similar added back, please consider starting that discussion in a new issue. Thanks :)
