### ISSUE TITLE
stdin.readLineSync() doesnt work in dartpad.dev

### ISSUE THREAD

**Issue by pro-sports** [dart-lang/dart-pad#1898]
stdin.readLineSync() doesnt work in dartpad.dev but works in all other IDEs. You cant use import:io in dartpad.dev and hence cant use the input methods? What is this? Its so so so annoying. Cant find a way around it.

**Comment by RedBrogdon** [comment]
As I mentioned in #1853, when code is running in a browser, there really isn't a [`stdin`](https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)) for Dart to connect to.

If you're interested in processing input from the user, there are other options, though. You could use dart:html to connect to HTML elements like `textarea`s and read their values, or put your Dart code into a Flutter snippet that includes input elements.

The team maintains a sample showing how to use Flutter forms for input at:

https://github.com/flutter/samples/tree/master/form_app
