### ISSUE TITLE
Documentation for keywords

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#190]
Currently, there doesn't show up any documentation for keywords like, `class`, `for`, `void` etc. This is probably logical, as there doesn't exist documentation inside of the dart language for those keywords. I do think it would be cool to actually kind of show some information there. 

The general idea being, that if someone new to dart try to understand some example at dartpad, then it could learn a lot from the information in dartpad itself without leaving dartpad to read tutorials or google information. I don't think this information has to be really technical and informal, maybe we could use the text of: https://www.dartlang.org/docs/dart-up-and-running/ch02.html

Otherwise, we could make it technical, and then link to the little more informal explanation in https://www.dartlang.org/docs/dart-up-and-running/ch02.html

Thoughts ?

![image](https://cloud.githubusercontent.com/assets/1035299/6886298/57261640-d638-11e4-8c13-eb830a3a3cc3.png)

**Comment by kaendfinger** [comment]
+1 for this. People who are new to Dart could easily benefit from this.

**Comment by kasperpeulen** [comment]
Maybe also documentation for the main function. I think that is one of the things that could confuse people coming from javascript in the beginning.

**Comment by lukechurch** [comment]
Let's move this issue to the Dart services repo, and put it into the document command

**Comment by kasperpeulen** [comment]
would be awesome ! @lukechurch
