### ISSUE TITLE
Update pubspec minimum SDK to 2.13.0 for null safe code

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1901]
There's a new type aliases feature for Dart that rolled out in 2.13.0, and it isn't available in DartPad. The likely reason is that our pubspec isn't opting into 2.13.0:

https://github.com/dart-lang/dart-services/blob/7e48f25bf58273f1a48522786f9c00d34636c3f3/tool/grind.dart#L419

Bumping the version for null-safe projects to 2.13.0 should enable the feature.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/dart-services/pull/711
