### ISSUE TITLE
Move to the new Dart Docker image

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-pad#1902]
https://hub.docker.com/_/dart

It's official and everything! 😄 

CC @mit-mit

**Comment by kevmoo** [comment]
👍

**Comment by domesticmouse** [comment]
Re-opening: https://github.com/dart-lang/dart-services/pull/717

**Comment by domesticmouse** [comment]
The official Dart image doesn't play well with the Cloud Build pipeline.

**Comment by kevmoo** [comment]
CC @mit-mit – we should figure out why!
