### ISSUE TITLE
Would like the ability to copy error messages

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart-pad#1907]
## What happened?

Analysis errors from DartPad can be selected, but once the mouse button is released, the selected text becomes deselected, preventing people from easily copying and pasting the error message.  This hinders searching for specific error messages on StackOverflow, and it encourages some StackOverflow users to use non-searchable screenshots of error messages.

## Steps to reproduce problem

1. Enter some code that triggers an analysis complaint.  For example:
    ```dart
    void main() {
      String s = 4;
    }
    ```
2. Observe that DartPad shows an analysis error in a pop-up in the bottom-right corner.
3. Select the text from the error message.

Result: The selection is lost once the mouse button is released.

### Browser

* Firefox 88.0.1 (64-bit) on Linux
* Chrome 91.0.4472.77 (Official Build) (64-bit) on Linux

**Comment by rahulv4667** [comment]
Hello dartpad team. I would like to contribute to this issue. I am thinking of adding a clipboard button to the analysis widget. I believe the main file to be changed is [analysis_results_controller.dart](https://github.com/dart-lang/dart-pad/blob/master/lib/elements/analysis_results_controller.dart).

Please let me know if I am on the right track and can contribute this.

**Comment by RedBrogdon** [comment]
This seems like a good feature to add, though I'll defer to @johnpryan, since he takes the lead on DartPad's front-end.

@rahulv4667, one way to start would just be mocking up the change to the UI. Try adding the HTML/CSS (without worrying about actually wiring it up to events and Dart code), and then paste a screenshot into this issue so we can talk it over.

**Comment by rahulv4667** [comment]
> Try adding the HTML/CSS (without worrying about actually wiring it up to events and Dart code), and then paste a screenshot into this issue so we can talk it over.

Sure. Will do.

**Comment by rahulv4667** [comment]
@RedBrogdon @johnpryan Please have a look at following screenshots and let me know what you think.

![dart_pad](https://user-images.githubusercontent.com/37624076/122515941-c6a7f800-d02b-11eb-9d3e-1d9657b457c8.PNG)
![dart_pad2](https://user-images.githubusercontent.com/37624076/122516166-0a026680-d02c-11eb-85cd-9926d3068c50.PNG)

**Comment by RedBrogdon** [comment]
Interesting! I had imagined a single copy button that would get all the error messages.

With this approach, though, I'd probably recommend moving the copy icon out of the tag and either placing it before the tag or adding it as almost an extra character at the end of the message.

@rahulv4667, @johnpryan: WDYT?

**Comment by rahulv4667** [comment]
**Suggestion1:**
![dart_pad4](https://user-images.githubusercontent.com/37624076/123579599-d70f5e00-d7f5-11eb-8ae2-33ca34a911ee.PNG)

**Suggestion2:**
![dart_pad5](https://user-images.githubusercontent.com/37624076/123579635-e7273d80-d7f5-11eb-9524-824ee9669473.PNG)

Personally, I find the previous one(suggestion zero) better. In suggestions 1 and 2, the icon color and text color are same. So, it might be a bit hard to differentiate between icon and text in some cases for beginners. We could avoid that by coloring the icon gray or blue(docs link color).  But then again, I still feel it appears cluttered. Suggestion 2 has another problem of the icon's purpose not being clear with `view docs` link adjacent to it. The above suggestion of icon along with the label feels a lot cleaner.

Your thoughts? @RedBrogdon @johnpryan

**Comment by johnpryan** [comment]
Suggestion 1 looks good to me. We might want to add some padding so it's visually separated from the text.

Most of the time these buttons give the user some feedback after they click it - like showing a snackbar ("Copied to clipboard") There's already some code for snackbars that we use when a new snippet is created.

It might also be useful to add a copy button to the console panel for runtime errors.

**Comment by rahulv4667** [comment]
Cool. Will add the padding and snackbar.

About adding copy button to console panel, should it be similar to above where each error gets its own copy button or should it have a single copy button at the top right corner?

If it is a single button, should it take into account all errors when copying or the last element?

**Comment by rahulv4667** [comment]
Hello, I added the copy button and the snackbar. You can view the demo [here](https://youtu.be/G4aV5YeNpjE). You can check the code change [here](https://github.com/rahulv4667/dart-pad/commit/798e0ca6ae16f79cd538c40cb8c119d7fac81dbc). I have tried three approaches. 

1. Creating a clipboard event and dispatching it.
2. Adding text to `window`'s `Selection`.
3. Using `window`'s `navigator`.

Third approach was the simplest and the only one working. Please let me know what you think of the change and also about how to add the copy button for console panel(what information should it copy and all, as asked above). 

I had a couple of questions while working on this:

1. **Does the project, or dart web in general, have hot reload capability?** I had to stop the server and restart it after every change. As a result, it took at least a minute for to see my changes.
2. **Was there any change in `build` in recent commits?** Initially, I made changes on the commit that was there 10 days ago. It worked fine without requiring anything else except dart sdk. But today, when I fetched the new changes and merged, `generate-protos` stopped working. I had to install protobuf-compiler and run. So, if there are any changes in how to build the project, is it documented anywhere?

**Comment by rahulv4667** [comment]
Also, shall we append the string `'dart'` to the error message so that search engine shows results related to dart instead of other languages?

**Comment by RedBrogdon** [comment]
The clipboard API seems like it has broad support for the use case we're talking about here (copying to the clipboard, rather than reading from it):

https://caniuse.com/?search=clipboard

Interestingly, we're using an older, deprecated API elsewhere:

https://github.com/dart-lang/dart-pad/blob/master/lib/embed.dart#L737

To answer your questions:

1. It was at one point possible to use [`webdev`](https://dart.dev/tools/webdev) with DartPad, but I don't know for a fact whether that's still the case.
2. @johnpryan or @domesticmouse would be the best resources there.

At this point, I think you can go ahead and put together a pull request with your changes. You've made some great progress.

**Comment by johnpryan** [comment]
1. You can use `webdev serve`. Flutter compilation doesn't work with `webdev`, though.
2. Can you check that you're using the latest version of [protoc_plugin](https://pub.dev/packages/protoc_plugin) (`pub global activate protoc_plugin`)?

**Comment by rahulv4667** [comment]
> 2. Can you check that you're using the latest version of [protoc_plugin](https://pub.dev/packages/protoc_plugin) (`pub global activate protoc_plugin`)?

Yes. That seems to have been the problem. 

Thank you, @johnpryan @RedBrogdon .
