### ISSUE TITLE
Running locally with "grind serve" hangs during build

### ISSUE THREAD

**Issue by nickmeinhold** [dart-lang/dart-pad#1908]
## What happened?

I cloned dart-pad a few weeks ago and have run locally without any problems until recently when it started hanging when I enter `grind serve`, with output:

```sh
grinder running build serve

build
  .../flutter/bin/cache/dart-sdk/bin/pub run build_runner build -r -o web:build --delete-conflicting-outputs
```

I've left it for up to half an hour and it never gets past this point.  This is new behaviour, previously running `grind serve` has resulted in (from memory) some build output and "listening on 8080" or something similar. 

## Steps to reproduce problem

```sh
git clone git@github.com:dart-lang/dart-pad.git
cd dart-pad 
dart pub get 
grind serve 
```

I have cloned a new version just now and tried on a few different computers and I get the same result. 

### Machine

Operating system: macOS 

Version: 11.3.1 

<details><summary>flutter & dart</summary>
<p>

    • Flutter version 2.3.0-12.1.pre at /Users/nick/SDKs/flutter

    • Upstream repository https://github.com/flutter/flutter.git

    • Framework revision f9c825981c (9 days ago), 2021-05-18 14:07:52 -0700

    • Engine revision 26e217e6c3

    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

</p>
</details>

### Steps taken 

In case it's useful, I tried running the first line of grind's build() command:

`dart run build_runner build -r -o web:build --delete-conflicting-outputs` 

and got the following 

<details><summary>output</summary>
<p>

[INFO] Generating build script completed, took 421ms
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot... completed, took 12.3s
[INFO] Building new asset graph completed, took 1.6s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] json_serializable:json_serializable on lib/workshops/src/github.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.14.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.14.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on lib/workshops/src/github.dart:

Bad state: Unexpected diagnostics:
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/Users/nick/SDKs/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[WARNING] No actions completed for 15.1s, waiting on:
  - json_serializable:json_serializable on lib/workshops/src/fetcher.dart
  - json_serializable:json_serializable on lib/workshops/src/meta.dart
  - json_serializable:json_serializable on lib/workshops/src/fetcher_impl.dart
  - json_serializable:json_serializable on lib/workshops/src/web_server.dart
  - json_serializable:json_serializable on lib/workshops/src/exceptions.dart
  .. and 11 more

[WARNING] No actions completed for 15.1s, waiting on:
  - json_serializable:json_serializable on lib/workshops/src/fetcher.dart
  - json_serializable:json_serializable on lib/workshops/src/meta.dart
  - json_serializable:json_serializable on lib/workshops/src/fetcher_impl.dart
  - json_serializable:json_serializable on lib/workshops/src/web_server.dart
  - json_serializable:json_serializable on lib/workshops/src/exceptions.dart
  .. and 11 more

[WARNING] No actions completed for 15.0s, waiting on:
  - json_serializable:json_serializable on lib/workshops/src/fetcher.dart
  - json_serializable:json_serializable on lib/workshops/src/meta.dart
  - json_serializable:json_serializable on lib/workshops/src/fetcher_impl.dart
  - json_serializable:json_serializable on lib/workshops/src/web_server.dart
  - json_serializable:json_serializable on lib/workshops/src/exceptions.dart
  .. and 11 more

[INFO] 55.3s elapsed, 1/17 actions completed.

</p>
</details>

Thanks! 🙂

**Comment by nickmeinhold** [comment]
Woohoo!  Switching to flutter stable channel did the trick... sorry for the noise! 🔉

**Comment by domesticmouse** [comment]
I'm guessing this is related to https://github.com/google/dart-neats/issues/132

Just to confirm, you were running on Dart 2.14 or newer?

**Comment by nickmeinhold** [comment]
Hey @domesticmouse!  

> Just to confirm, you were running on Dart 2.14 or newer? 

Correct!  2.14.0 

Thanks 🙂
