### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#191]
Write a tabbed component class, and refactor the dart/html/css and console/documentation tabbed area to use that. It'll probably live here: https://github.com/dart-lang/dart-pad/blob/master/lib/elements/elements.dart.

The `Tabbed` object should contains `Tab`s, and you should be able to get and get the selected tab, and listen for selected tab changes.

**Comment by kasperpeulen** [comment]
@devoncarew Can I try this one ?

**Comment by devoncarew** [comment]
sgtm!
