### ISSUE TITLE
Dart Pad and Dart on Console gives different output

### ISSUE THREAD

**Issue by abhijeetckar** [dart-lang/dart-pad#1910]
## What happened?

Dart Pad and Dart on Console gives different output
 
## Steps to reproduce problem

Run the below sample code taken from Dart Docs

### Browser

Browser:
Google Chrome
Version:
Version 91.0.4472.77 (Official Build) (arm64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
```
None
```
Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
None
```

### Machine

Operating system:
mac OS Big Sur
Version:
11.4
### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
void main() {

  num age = 13;

  print(age is Object);
  print(age is int);
  print(age is double);
}

/*
When on Dart Pad I get 
  print(age is double); as true

While running the same on console 
  print(age is double); is false
*/

```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
true
true
true
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.
<img width="375" alt="Screenshot 2021-06-01 at 5 55 20 PM" src="https://user-images.githubusercontent.com/36094506/120322945-99a4d700-c302-11eb-8e67-b2058d6e9729.png">

**Comment by vendz** [comment]
by console do you mean that when you run the code on your system it shows `false`

**Comment by vendz** [comment]
by `console` do you mean that when you run the code on your system it shows false

**Comment by vendz** [comment]
by `console` do you mean that when you run the code on your system it shows `false`

**Comment by eernstg** [comment]
@abhijeetckar, take a look at this one: https://dart.dev/guides/language/numbers.
