### ISSUE TITLE
Need icon ("information" with a circle?) for versions dialog box

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#1914]
Right now you can just click on the version numbers in the bottom right to see the various package version numbers. There should be an icon on the left or right of that text which is clickable.

**Comment by srawlins** [comment]
@johnpryan I saw the other icons (like the keyboard) are SVG files and wasn't sure where to acquire the right file for the "information" icon.

**Comment by johnpryan** [comment]
I think you can use the `material-icons` class to display an icon:

```
<i class="material-icons" aria-hidden="true">bookmark</i>
```

We might need to apply some additional styles to match the text, though.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/dart-pad/pull/1915
