### ISSUE TITLE
"grind" command not working

### ISSUE THREAD

**Issue by TDM-dev2** [dart-lang/dart-pad#1918]
01. Firstly I run the " dart pub global activate grinder" command and install the grinder for my local computer.
02. grinder is default installed in "C:\Users\TDM\AppData\Local\Pub\Cache\bin" location.  So I added a new user environment for this new location.

But still, cmd/ bash says "grinder command not found" when I run "grind deploy"

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @TDM-dev2. Do you mind pasting in the complete error that you're seeing?

**Comment by parlough** [comment]
As some extra information, if you didn't get it to work: Since `grinder` is included with the package as a `dev_dependency`, you should be able to just run the project's local version:

```terminal
$ dart pub get
$ dart run grinder deploy
```
