### ISSUE TITLE
Link to dart.dev is missing `//dart.dev/go/`

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#1920]
## What happened?

The code has an intentional error, so I expected to see a link to http://dart.dev/go/non-promo-property. Instead, I see a link to `http:non-promo-property`. The error message displays correctly in WebStorm.

More details: https://github.com/dart-lang/site-www/pull/3253#discussion_r644407337

## Steps to reproduce problem

Go to https://dartpad.dev/d076253e8b4f7ae4d450a13a8aad96c5?null_safety=true.

**Comment by parlough** [comment]
As a reference, this is caused by replacement done by `util.stripFilePaths` called on this line:https://github.com/dart-lang/dart-services/blob/master/lib/src/analysis_server.dart#L292

**Comment by RedBrogdon** [comment]
Confirming what @parlough just said, the JSON sent down from the server is missing the full URL syntax:

```json
{
 "issues": [
  {
   "kind": "error",
   "line": 5,
   "message": "The property 'isEven' can't be unconditionally accessed because the receiver can be 'null'.",
   "sourceName": "main.dart",
   "hasFixes": false,
   "charStart": 96,
   "charLength": 6,
   "url": "https://dart.dev/tools/diagnostic-messages#unchecked_use_of_nullable_value",
   "diagnosticMessages": [
    {
     "message": "'i' refers to a property so it couldn't be promoted.  See http:non-promo-property",
     "line": 2,
     "charStart": 17,
     "charLength": 1
    }
   ],
   "correction": "Try making the access conditional (using '?.') or adding a null check to the target ('!')."
  }
 ]
}
```

@srawlins, I'm routing this your way since it's a backend issue.

**Comment by srawlins** [comment]
I'll tidy up this utility.
