### ISSUE TITLE
Return metadata about imports in compilation responses

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1926]
Essentially:

* Update the protos for CompileDDCResponse and CompileResponse to include optional information about imports in the source file.
* Update the backend to fill these fields on compile calls.

A few open questions:

* Should we return just the package, or package + path/filename?
* Should analyze calls do the same thing? Any benefit there?
* How should the front-end be modified to use this information?

**Comment by srawlins** [comment]
I've forgotten what this original request is.

> Update the protos for CompileDDCResponse and CompileResponse to include optional information about imports in the source file.

What information?

**Comment by srawlins** [comment]
Closing as stale.
