### ISSUE TITLE
Code completion UI shouldn't disappear on noncompleted string

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#193]
![image](https://cloud.githubusercontent.com/assets/2978182/6887538/9939c7f8-d65a-11e4-88b2-6f84edeea466.png)

If you type 'z' the completion dialog disappears. This is bad - it makes it difficult to use the UI for exploration as it disappears if the thing that the user is looking for doesn't exist.

**Comment by lukechurch** [comment]
(this should show an empty list)

**Comment by kasperpeulen** [comment]
![](http://g.recordit.co/89Db2ExwJ9.gif)

like this ?
