### ISSUE TITLE
Show when Dartpad is building code

### ISSUE THREAD

**Issue by ranjithrd** [dart-lang/dart-pad#1930]
Hello, I'd like to know if it's possible to know if Dartpad is building a Flutter app for example, or executing code. This would help improve UX and let the user know something's happening and the browser hasn't suddenly crashed, for example.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue @ranjithrd. We have an older, related issue (#1033) that I believe captures what you're talking about here, so I've updated that one.

 I'm closing this as a duplicate, so feel free to continue the conversation on the other issue!
