### ISSUE TITLE
Selections in the documentation aren't stable

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#194]
If you select some text in the documentation - and pause for a moment the selection in the documentation text changes. 

Let me know if you can't repo.

**Comment by kasperpeulen** [comment]
see https://github.com/dart-lang/dart-pad/pull/199

**Comment by devoncarew** [comment]
@kasperpeulen - one github tip. If you mention an issue in a PR - `fix #194` - it'll automatically close the issue when the PR is merged. It's a nice time-saver.
