### ISSUE TITLE
Cannot import dart:io in  dartpad

### ISSUE THREAD

**Issue by Stephin-T** [dart-lang/dart-pad#1950]
### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by Stephin-T** [comment]
Error compiling to JavaScript:
unsupported import: dart:io

**Comment by domesticmouse** [comment]
Yup, that's because `dart:io` is not supported in the dart to JavaScript compiler, which you can see explained in the [`dart:io` documentation](https://api.dart.dev/stable/2.13.4/dart-io/dart-io-library.html).
