### ISSUE TITLE
Incomplete instructions on "Troubleshooting DartPad" page

### ISSUE THREAD

**Issue by deydaniel** [dart-lang/dart-pad#1951]
Hi, Embedded DartPads were not working on Google Chrome and the DartPad displayed this error message -

DartPad requires localStorage to be enabled. For more information, visit dart.dev/tools/dartpad/troubleshoot.'

Upon opening "Troubleshooting DartPad" page, I found this instruction -

Check whether you’ve disabled third-party tracking cookies (Chrome instructions). If you’ve disabled cookies, change your settings to allow cookies for dartpad.dev.

So I went to settings of chrome and as I didn't wanted to enable third party cookies for all websites, so I enabled it for dartpad.dev by adding [*.]dartpad.dev in "Sites that can always use cookies" in "Cookies and other site data" page of chrome settings.

But my embedded dartpads were still not working. I after struggling with the issue, I finally added [*.]flutter.dev and [*.]dart.dev to allow cookies. Which solved the problem.

I request that the "Troubleshooting DartPad" page instruction - "Check whether you’ve disabled third-party tracking cookies (Chrome instructions). If you’ve disabled cookies, change your settings to allow cookies for dartpad.dev." should be updated to include flutter.dev and dart.dev as well. 

(This is my first time creating an issue so I apologise if this was not the right place to give this feedback)

Thank You.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue!

 Were you using DartPad directly (via [dartpad.dev](https://dartpad.dev)), or were you using the embedded version via another site (such as this [codelab](https://dart.dev/codelabs/null-safety))?

**Comment by deydaniel** [comment]
I was using embedded DartPad via flutter.dev (more specifically https://flutter.dev/docs/development/ui/layout/constraints)

The problem solved upon allowing third party cookies on flutter.dev in addition to dartpad.dev 

The trouble shooting page only asks to allow third party cookies on dartpad.dev (which should be updated to include flutter.dev and dart.dev as well)

**Comment by RedBrogdon** [comment]
Got it. I've created a PR to update the instructions:

https://github.com/dart-lang/site-www/pull/3384

Feel free to comment there if you have anything more to add, and thanks again for bringing this to our attention. 😄
