### ISSUE TITLE
Linux Mint Firefox / Chromium "Run" button

### ISSUE THREAD

**Issue by danieljallen86** [dart-lang/dart-pad#1953]
When exploring the Basic Flutter layout concepts (https://flutter.dev/docs/codelabs/layout-basics), there is a reference to a run button, but all that is present in the Dart Pad is the copy button. Is this a missing button, old copy referring to a button that is no longer incorporated, or just an issue with those of us on a Linux system?

**Comment by RedBrogdon** [comment]
Thanks for filing an issue.

Normally there's a "Run" button in the upper-righthand corner of the iframe:

![image](https://user-images.githubusercontent.com/969662/125146173-66135480-e0d9-11eb-84a7-f922ad07b888.png)

Are you able to see it when looking at the codelab?

If not, can you provide a screenshot and the version info for your OS/browser?
