### ISSUE TITLE
Analytics drop for execution events

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1960]
Since the last release of the front-end (either 7/7 or 7/8), there's been a significant drop in our analytics for executions, both the `main.run` event and the `execution.initiated` event.

It appears to be affecting the embedded layout, but not the playground.

**Comment by johnpryan** [comment]
I think we were using an older version that did not include the fix from https://github.com/dart-lang/dart-pad/pull/1955
