### ISSUE TITLE
Error message in console while using embedded layout.

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1961]
## What happened?

Currently seeing errors in the browser console when using DartPad's embedded layout.

## Steps to reproduce problem

The codelabs are the easiest place. Both the [layout basics codelab](https://flutter.dev/docs/codelabs/layout-basics) and [Dart cheatsheet](https://dart.dev/codelabs/dart-cheatsheet) are triggering the error on pageload.

### Browser

Google Chrome | 91.0.4472.114 (Official Build) (x86_64)
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)
JavaScript | V8 9.1.269.36

### Error

```
Uncaught TypeError: Cannot read property 'gag' of null
    at hh.eb (embed_dart.dart.js:12694)
    at hh.ik (embed_dart.dart.js:12673)
    at os.$1 (embed_dart.dart.js:13062)
    at F4 (embed_dart.dart.js:517)
    at embed_dart.dart.js:525
```

**Comment by johnpryan** [comment]
I think this was fixed by #1955
