### ISSUE TITLE
Editor not working after clicking on text field in firefox browser

### ISSUE THREAD

**Issue by binary-ibex** [dart-lang/dart-pad#1963]
## What happened?

   While using the dartpad to run the flutter example, which consist of simple "TextField"  my editor stop working, I'm unable to edit anything after clicking on the text field. Whatever I type in editor field is show in the UI text field. This happen in firefox browser. In chrome it does not show this type of behaviour.

## Steps to reproduce problem

- Open dartpad in firefox browser
- write simple flutter program with TextField in it.
- Run code 
- Enter something in textfield and the click on editor try to edit code.

### Browser

Browser: Firefox

Version: 90.0

I use UBlock origin extension

Javascript console error

```
- unreachable code after return statement

- Source map error: Error: request failed with status 404
Resource URL: https://dartpad.dev/scripts/playground.dart.js
Source Map URL: playground.dart.js.ma

- Source map error: Error: request failed with status 404
Resource URL: https://storage.googleapis.com/nnbd_artifacts/2.13.4/flutter_web.js
Source Map URL: flutter_web.js.map

```

### Machine

Operating system: Ubuntu 20.04

Version: 20.04

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
    child: TextField()
    );
  }
}

```

**Comment by RedBrogdon** [comment]
Thanks for filing an issue. I just tried the same code in DartPad, and wasn't able to replicate the issue.

You mentioned using an ad blocker in your report. They sometimes cause issues with DartPad usage of iframes -- have you tried disabling that plugin and reloading DartPad?

**Comment by binary-ibex** [comment]
Thanks for reply Andrew; to be sure I again tested the dartpad on the Firefox browser, but this time on live bootable usb so that I get the clean environment without any addon or extra  software, but dartpad still show same behaviour in Firefox browser. I also tested it on Chrome and Brave browser, on it Dartpad work without any problem on both of them. 
At first I thought, there might be something wrong with Ubuntu OS, but I tested it on window OS, I get same behaviour by dartpad when I tested it on Firefox browser.

I record the video in the Firefox Developer browser version 90 with no addon install in my computer  Ubuntu 20.04 OS, 


https://user-images.githubusercontent.com/70746835/126805956-dd3c90e5-3b15-49b3-975e-9ee64df02b25.mp4

**Comment by RedBrogdon** [comment]
Got it. Thanks for the video -- I was able to replicate the behavior. 

@mdebbar or @yjbanov, do y'all mind taking a quick look at this and telling me whether looks like a DartPad problem or a Flutter problem?

Steps to reproduce some odd focus-related behavior in Chrome:

1) In Chrome, navigate to https://dartpad.dev/?id=9cfb3b3fa0b8f6b09167d3770f565fa2&null_safety=true
2) Run the code.
3) Click in the TextField and type some characters.
4) Click in the code editor.
5) Type some characters, and see that they appear in the code editor.
6) Click on the TextField in the Flutter pane one or more times.
7) Type some characters, and see that they still appear in the code editor.
8) Click somewhere in the Flutter pane that's not the actual TextField.
9) Type some characters, and see that they now appear in the TextField.

Steps to reproduce some odd focus-related behavior in Firefox:

1) In Firefox, navigate to https://dartpad.dev/?id=9cfb3b3fa0b8f6b09167d3770f565fa2&null_safety=true
2) Run the code.
3) Click in the TextField and type some characters.
4) Click in the code editor.
5) Notice that a cursor appears in the code editor, but then disappears.
6) Type some characters, and see that they appear in the TextField. 
7) There appears to be no way to return focus to the editor other than running the code again.

**Comment by parlough** [comment]
Thanks so much for the issue report and thorough reproduction information, it's extremely appreciated.

I just tried this with the latest Firefox and the newer DartPad frontend and I can't seem to reproduce this behavior. There are however some other new focus related issues that we are tracking in other issues.

If you're still seeing this or other issues in Firefox or otherwise, please open a new issue with reproduction details. Thanks again :)
