### ISSUE TITLE
run-true not working with injected DartPad

### ISSUE THREAD

**Issue by m0nac0** [dart-lang/dart-pad#1965]
## What happened?

I want to inject a DartPad for code snippets as described here [https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad). 
Everything works, except for `run-true`. 
I can manually run the snippet, but it does not automatically run. 
When I inspect the network traffic, I also initially don't see any calls to the compile-endpoint.

## Steps to reproduce problem

Inject a DartPad for code snippets as described here [https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#converting-code-blocks-to-dartpad) and use the `run-true` option in the info-string.

## Additional info
I'm also seeing the issue described in #1961 .

### Browser

Browser: Firefox, Chrome

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

Similar as in #1961

### Machine

Operating system: Windows 

Version: 10

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

Occurs with any code, e.g.
```
void main(){print('hi');}
```

This issue also occurs with the official demo linked in the wiki: [https://dartpad.dev/example/inject.html](https://dartpad.dev/example/inject.html).
### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

No.

**Comment by johnpryan** [comment]
Fixed by #1955
