### ISSUE TITLE
assert() shows opaque error

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1966]
When an `assert()` statement fails, "Script error." appears in the console.

We should investigate if `assert` statements should be enabled in DartPad, and how to display a more helpful error.

Related issues:
- https://github.com/dart-lang/dart-pad/issues/1580
- https://github.com/dart-lang/dart-pad/issues/1649
- https://github.com/dart-lang/dart-pad/issues/1650
- https://github.com/dart-lang/dart-pad/issues/1925
- https://github.com/dart-lang/dart-pad/issues/2514

**Comment by parlough** [comment]
Consolidating issue in to https://github.com/dart-lang/dart-pad/issues/3008 alongside other error surfacing improvements. Thanks for the discussion and investigation here!
