### ISSUE TITLE
Code completion not working on a mobile device

### ISSUE THREAD

**Issue by flutternoob** [dart-lang/dart-pad#1968]
Code completion does not work when using dartpad.dev and embedded dartpad on a mobile device. I am using Chrome

**Comment by flutternoob** [comment]
Code completion is still not working on mobile devices. Could you please tell me when it will be resolved? Thanks

**Comment by flutternoob** [comment]
When will code completion be resolved on mobile devices?

**Comment by domesticmouse** [comment]
I'm curious which mobile device you are using? We haven't designed the UI for usage on a phone, for instance.

**Comment by flutternoob** [comment]
I'm using a Samsung A20. Code completion used to work before I created this issue. In fact, before i got my laptop, i learnt the basics of the Dart programming language on my phone using dartpad.dev. Couldn't have done it without code completion.

**Comment by parlough** [comment]
This is still an issue with the current DartPad UI, as there's no clear way to open the autocomplete menu on mobile. I'll close this in favor of https://github.com/dart-lang/dart-pad/issues/3010 which covers related work, including autocomplete as users type, which we hopefully could design in a way that works for mobile users of DartPad too.

Thanks for reporting this issue and advocating for this improvement!
