### ISSUE TITLE
New lines not printed in Edge and Chrome browsers

### ISSUE THREAD

**Issue by jwparsons** [dart-lang/dart-pad#1979]
I'm following a basic Dart tutorial on YouTube and the new line character \n is not being printed to the Console window.

![image](https://user-images.githubusercontent.com/9601620/127820188-05bd71ce-4c95-4c03-9638-9e9ac116fcdf.png)

Based on Flutter 2.2.3 Dart SDK 2.13.4

Microsoft Edge
Version 94.0.968.0 (Official build) canary (64-bit)

**Comment by domesticmouse** [comment]
Hey @parlough, I have a vague recollection that you were making changes in this general area. Any ideas?

**Comment by johnpryan** [comment]
This was fixed by https://github.com/dart-lang/dart-pad/pull/1969 I think. I'll deploy this today.

**Comment by jwparsons** [comment]
Sorry for the dup! 👍
