### ISSUE TITLE
Remove older Dart examples

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-pad#2002]
I suggest we remove these two older Dart examples. They are both specific to language features, and I think if we wanted to exemplify those, we'd need to include a much larger set. I think we can just remove them instead.

- Int to double
- Mixins

**Comment by domesticmouse** [comment]
I feel we should also re-order the samples to prioritise the Flutter samples.

**Comment by srawlins** [comment]
Both of these requests are now fulfilled.
