### ISSUE TITLE
When I try to re-write my code after making an error the cursor erases everything coming in front of it. It is the most annoying thing that could possibly happen to this dummy code editor!

### ISSUE THREAD

**Issue by HaseebKahn365** [dart-lang/dart-pad#2004]
### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by domesticmouse** [comment]
Can you try replicating this issue on [CodeMirror.net](https://codemirror.net/)? This is the editor component that DartPad uses.

**Comment by HaseebKahn365** [comment]
I am really sorry! I just figured out the problem. Turns out, I had pressed
the ins button on the keyboard which activated the over-type mode. Now that
I pressed it again, the insert mode for activated and the problem is fixed
now! 👍☺️
