### ISSUE TITLE
Update package list

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2007]
The following packages should be made importable:

* bloc
* cloud_firestore
* collection
* firebase
* firebase_auth
* firebase_core
* flutter_bloc
* google_fonts
* http
* intl
* js
* meta
* provider
* riverpod
* url_launcher

These would be in addition to the `package:flutter` and `dart:*` imports DartPad currently allows.

**Comment by rakudrama** [comment]
Should we include https://pub.dev/packages/characters ?
It might be re-exported by flutter but it is not a flutter-specific package.

**Comment by srawlins** [comment]
https://github.com/dart-lang/dart-services/pull/747 handled all of these except `flutter_bloc`.

**Comment by puf** [comment]
FlutterFire just added support for Realtime Database on the web. 🎉

When I add
```
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_database/ui/firebase_animated_list.dart';
```
to Dartpad, I get:

> Unsupported import(s): (package:firebase_database/firebase_database.dart, package:firebase_database/ui/firebase_animated_list.dart)

Any chance you add these @srawlins , so I can continue testing?

**Comment by srawlins** [comment]
Will do!

**Comment by TimWhiting** [comment]
`riverpod` is actually the pure dart version of `riverpod` (no flutter support). I don't know what criteria you have for adding to this list, but could `flutter_riverpod`, `hooks_riverpod`, and `flutter_hooks` be added to the list?

**Comment by srawlins** [comment]
@zoeyfan WDYT about `flutter_riverpod`, `hooks_riverpod`, and `flutter_hooks`?

**Comment by srawlins** [comment]
Moved to https://github.com/dart-lang/dart-pad/issues/2024
