### ISSUE TITLE
url_launcher plugin complains of missing web plugin implementation

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2010]
This gist prints an error message relating to a missing plugin implementation:

https://dartpad.dev/?id=5d148dd65b73f85d09bfceac78cf4683&null_safety=true

It's possible, given DartPad's unusual mechanism for compiling apps, that the code from the underlying url_launcher_web isn't being properly included with the user's compiled Dart code.

**Comment by RedBrogdon** [comment]
FWIW, our iframe sandboxing will probably keep this from working even when the above issue is fixed, but that's also something we can address.

**Comment by srawlins** [comment]
Yegor showed me that `flutter packages get` will generate this `lib/generated_plugin_registrant.dart` file [here](https://github.com/flutter/flutter/blob/fa0782b696dbaa141936d29332ce9d3807dc9acd/packages/flutter_tools/lib/src/build_system/targets/web.dart#L132).

I _think_ all we need to do is change `flutter pub get` to `flutter packages get`, in grind.dart.
