### ISSUE TITLE
Back-ends for beta, dev, old, appear to be serving pre-null safety

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2013]
We'd like them to serve null safety, exclusively.

E.g.

http://localhost:8000/?null_safety=true&channel=old

**Comment by srawlins** [comment]
CC @domesticmouse

**Comment by domesticmouse** [comment]
I've updated the build configuration for dev, beta, and old to run null-safety.

For various reasons, old is currently running Flutter 2.5.1 (primarily, I blame `google_fonts` which requires a version of `meta` that is too new for Flutter 2.2.3).
