### ISSUE TITLE
How to use word-wrap feature in dart pad?

### ISSUE THREAD

**Issue by kamleshwebtech** [dart-lang/dart-pad#2021]
Kindly suggest how to use word-wrap feature in dart pad? BTW do we have such feature in dart-pad online in the browser? Kindly confirm. Thanks a lot.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @kamieshwebtech!

We've actually disabled line-wrapping in DartPad for the time being. It used to be on by default, but caused large strings (that couldn't be broken) to break our UI.
