### ISSUE TITLE
10.0 erroneously becomes int

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/dart-pad#2023]
## What happened?
`10.0` erroneously becomes `int`. 

## Steps to reproduce problem

https://dartpad.dev/?id=4198b74bc13f19fc6e9600fe72d2d8c4&null_safety=true

### Browser

Browser: Google Chrome

Version: 94.0.4606.61（Official Build） （64bit)

### Machine

Operating system: Ubuntu

Version: 20.04.3 LTS

### Your code

```dart
void main() {
  num a = 10.1;
  print(a.runtimeType); // double

  num b = 10.0;
  print(b.runtimeType); // int but not double

  num c = 10;
  print(c.runtimeType); // int
}
```

### DartPad's output

```
double
int
int
```

**Comment by eernstg** [comment]
This is working as intended. In particular, every number `n` in Dart on a web platform is represented as a JavaScript number, and we have `n is double` in every case, and `n is int` if the number does not have a non-zero decimal part (that is, it represents a whole number). The `runtimeType` is consistent with this and reports that `10.0` in an `int`, but if you test it you will also see that it `is double`. Please take a look at https://dart.dev/guides/language/numbers for more details.

**Comment by Cat-sushi** [comment]
>  every number n in Dart on a web platform is represented as a JavaScript number
Yes, I knew.
But I didn't know there are no information of types in Dart.

**Comment by eernstg** [comment]
A heap object carries information about its run-time type, also for Dart programs compiled to JavaScript.

As a very special case, with a Dart program compiled to JS, numbers are not heap objects. They are represented directly as JavaScript numbers. A JavaScript number can be stored in a CPU register, and it does not carry information about its run-time type which will allow Dart programs (running as JS code) to determine whether a given number whose fractional part is zero was obtained as a `double` or as an `int`.

So Dart code compiled to JS will rely on the actual value of the number to make the choice. This means that 10.0 will be an `int`, even though it could have been obtained as `10.5 - 0.5`; but it will yield true when tested by `is int` and when tested by `is double`.

So this is definitely an exceptional part of the semantics of Dart programs compiled to JS. However, the alternative (which would probably require every `int` to be a heap allocated object) is simply not practical, it is to costly in terms of time and space.
