### ISSUE TITLE
dart_service's test/flutter_analysis_server_test.dart is flaky

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2027]
We thought it started flaking in https://github.com/dart-lang/dart-services/commit/040821acf3782b07d00617e739ba4d0a57d0a561 but if you check out earlier commits, like https://github.com/dart-lang/dart-services/commit/ef2b4140333e4db17e3cf57054ab7fcd724127c7, you can still get a flake with `pub get ; pub run test test/flutter_analysis_server_test.dart`.

The only test case that seems to fail is "Flutter SDK analysis_server with analysis servers Trigger lint with Flutter code" (both the null safe and the null unsafe versions).

**Comment by srawlins** [comment]
I thought it might be the package version of `analyzer`, but even at analyzer 2.0.0, I can get the test to fail.

**Comment by parlough** [comment]
Closing this as stale as these tests no longer exist in this form. Thanks!
