### ISSUE TITLE
Highlight in the completion dialog where the text matches

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#203]
@kasperpeulen 

As per https://github.com/dart-lang/dart-pad/issues/202 the matching text can occur at multiple different points in the code. Because of this, the place where the code does match should be highlighted in the completion dialog.

e.g. Str

should render as something like to<em>Str</em>ing in the completion dialog

**Comment by kasperpeulen** [comment]
![image](https://cloud.githubusercontent.com/assets/1035299/6949881/475df12a-d8b7-11e4-9254-4e03a7cf4d2a.png)

I think this one can only be done in a kind of hackish way, as codemirror doesn't seem to allow html here.

**Comment by kasperpeulen** [comment]
Yeah I got something working thanks to the awesome marijn of codemirror:
![image](https://cloud.githubusercontent.com/assets/1035299/6952135/1a0c41fa-d8c0-11e4-9a68-217ad45539db.png)
