### ISSUE TITLE
Combine dart-pad and dart-services repos?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2035]
I'd like to consider combining the dart-pad and dart-services repos.

I think these were separate repos before the mono-repo was a common concept (used in dart-lang/test, dart-lang/build, google/protobuf.dart, etc.), but I think it would be a valid layout for these two repos. We already combine the issue trackers into this one.

Benefits:

* Shared proto definitions
* Simple `grind` target which launches back-end and front-end.
* Simpler workspace for me, not requiring multiple terminals :D (not necessarily true, but maybe...)

Costs:

* Possibly more complex to maintain the "beta", "dev", and "old" branches?
* Possibly trickier grind commands, as the command-space is combined. But I think grinder has command namespaces, no? Can we write commands for `grind be serve` and `grind fe serve` so that back-end and front-end commands are namespaced?

**Comment by RedBrogdon** [comment]
We've been talking about this since 2019. 😄 

https://github.com/dart-lang/dart-pad/issues/1350
