### ISSUE TITLE
New channel mechanism for dart-services

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2036]
Since implementing the channel switcher, and adding package support, it appears that we need a new mechanism for maintaining (and deploying) the different channels.

I think this shouldn't be too hard, but I'm excited to be proven wrong 😂 :

1. Update [`flutter-sdk-version.yaml`](https://github.com/dart-lang/dart-services/blob/master/flutter-sdk-version.yaml) to list each version of Flutter in play:

```yaml
flutter_sdk:
  stable_version: 2.5.2
  beta_version: 2.6.0-beta
  dev_version: 2.6.0-dev
  old_version: 2.4.9
```

Or a variation of that schema.

2. Update `flutter-sdk/` directory to (*cringe*) a parent directory, `flutter-sdks/`, with 4 child directories, `stable/`, etc.
3. Update DownloadingSdkManager to account for these changes. Various API, like `getSdkConfigInfo`, and `createFromConfigFile`, can take a `channel` parameter.
4. Grinder tasks like `setupFlutterSdk` should also take a parameter.
5. `tool/update_sdk.dart` should also take a parameter.

As for deployment... I'm a little fuzzy but:

1. `cloud_run.Dockerfile` references `FROM dart:2.14.3`; does this mean we'll need to break this into 4x Dockerfiles? ☹️ . Hopefully there is a lot of room for reuse.
2. ... OK I'm very fuzzy.

**Comment by domesticmouse** [comment]
> 1. Update [`flutter-sdk-version.yaml`](https://github.com/dart-lang/dart-services/blob/master/flutter-sdk-version.yaml) to list each version of Flutter in play

I'd use specific version for `beta_version` and `dev_version` as well, as this enables me to have a PR to force a rebuild in Cloud Build when the versions change.

> `cloud_run.Dockerfile` references `FROM dart:2.14.3`; does this mean we'll need to break this into 4x Dockerfiles? ☹️ . Hopefully there is a lot of room for reuse.

My preference, akin to null safety, is to have a run time flag to `dart-services` that tells it which SDK to use. This is the reason we have a null safe, and a null unsafe Docker file. So yes, we will need 4 docker files, such that we can build the four different images. On the upside, this will mean the deployable images will only have one SDK.

I'll see if I can find a way to split out a common Dockerfile that the four re-use.
