### ISSUE TITLE
Flutter plugins should not be importable in pure Dart code

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2037]
This code:

```dart
import 'package:url_launcher/url_launcher.dart';

main() {
  launch("https://dartpad.dev");
}
```

Will not produce analysis errors, but will fail to compile:

```
Error compiling to JavaScript:
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
Error: Couldn't resolve the package 'url_launcher' in 'package:url_launcher/url_launcher.dart'.
lib/main.dart:1:8:
Error: Not found: 'package:url_launcher/url_launcher.dart'
import 'package:url_launcher/url_launcher.dart';
       ^
lib/main.dart:4:3:
Error: Method not found: 'launch'.
  launch("https://dartpad.dev");
  ^^^^^^
Error: Compilation failed.
```

It's correct to fail, since url_launcher is a Flutter plugin that can't work without the Flutter SDK. It would be good to have an earlier warning produced by the analyzer, though.

**NOTE:** This is a definite edge case, since most devs would understand that url_launcher is a Flutter thing. In the long term, though, we should try to provide a message that makes sense.

**Comment by RedBrogdon** [comment]
This is an edge case, so I imagine the lowest-effort-but-still-clean approach is probably the best use of time.

Updating `getUnsupportedImports` so that it's smart enough to disallow Flutter plugins when no Flutter SDK packages are included is probably enough to correctly produce an error. The annoying bit is that @srawlins would need to maintain separate lists of "packages" and "plugins."

**Comment by RedBrogdon** [comment]
I'm always in favor of doing less work, so if this can be fixed in the SDK, that's great. 😄

**Comment by johnpryan** [comment]
Fixed by https://github.com/dart-lang/dart-pad/issues/1826
