### ISSUE TITLE
Error compiling to JavaScript: XMLHttpRequest error.

### ISSUE THREAD

**Issue by renntbenrennt** [dart-lang/dart-pad#2040]
## What happened?

As stated in the title, compile failed.

## Steps to reproduce problem

I tried to run the example demo in this [article](https://medium.com/flutter/building-performant-flutter-widgets-3b2558aa08fa), which demonstrated in this [DartPad](https://dartpad.dev/?id=e41ed2678b9b9d7347880c20ec49f3f2&null_safety=true)

And it failed to compile... I even copy and paste the code to run it in a new DartPad, opening in the new page, it also not working...

## Additional info

I have read the similar issue in this post: https://github.com/dart-lang/dart-pad/issues/1554

But from that issue it seems it's about the something wrong about the server... and it's supposed to be fixed after that...

### Browser

Browser:

Chrome

Version:

Version 94.0.4606.81 (Official Build) (x86_64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Yes, but I have turned it off for investigation.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
DevTools failed to load source map: Could not load content for https://dartpad.dev/packages/split/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://dartpad.dev/scripts/playground.dart.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
dartpad.dev/:1 Access to XMLHttpRequest at 'https://nullsafety.api.dartpad.dev/api/dartservices/v2/compileDDC' from origin 'https://dartpad.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
playground.dart.js:9988 POST https://nullsafety.api.dartpad.dev/api/dartservices/v2/compileDDC net::ERR_FAILED 500
```

### Machine

MacBook Pro 16inch 2019

Operating system:

macOS 

Version:

11.6

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

<details><summary>Code</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: PerformanceMediumDemo(),
      ),
    );
  }
}

class _ListItem extends StatefulWidget {
  final int index;

  _ListItem({required this.index}) {
    print('creating list item $index');
  }

  @override
  _ListItemState createState() {
    // print('creating list item state $index');
    return _ListItemState();
  }
}

class _ListItemState extends State<_ListItem> {
  @override
  Widget build(BuildContext context) {
    print('building list item ${widget.index}');
    return Container(height: 500, child: Center(child: Text(widget.index.toString())));
  }
}

class PerformanceMediumDemo extends StatefulWidget {
  @override
  _PerformanceMediumDemoState createState() => _PerformanceMediumDemoState();
}

class _PerformanceMediumDemoState extends State<PerformanceMediumDemo> {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        _ListItem(index: 0),
        _ListItem(index: 1),
        _ListItem(index: 2),
        _ListItem(index: 3),
        _ListItem(index: 4),
        _ListItem(index: 5),
        _ListItem(index: 6),
        _ListItem(index: 7),
      ],
    );
  }
}
```

</details>

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
Error compiling to JavaScript:
XMLHttpRequest error.
```

### update
This issue is not happen all the time. 

I can actually run the program in DartPad after a while, but only once, meaning I went to try to build the program after like an hour, and it worked but I tried run it again, it will produce this `compilation error` again.

**Comment by SeasonLeee** [comment]
why closed...

That dartpad is producing another kind of weird error now:
<img width="1792" alt="Screen Shot 2021-10-19 at 11 52 36 AM" src="https://user-images.githubusercontent.com/13610283/137841206-3c3f4493-a47b-4b62-bcd4-194bf66388a9.png">

As you can see in the screeshot, the code is not showing up anymore😅 wtf??

@RedBrogdon @domesticmouse
