### ISSUE TITLE
Make doc icons consistent with the code completion icons

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#205]
@kasperpeulen 

Currently code completion has icons, but the doc comments don't. It would be nice if we could make the display of these two things consistent with each other.

Could we include the icons from code completion into the docs?

**Comment by kasperpeulen** [comment]
I've got this allmost done now, except for one issue, which is that the dartdoc and completion api give different information about what kind of type the element is.

If some element has a both a getter and a setter, dartdoc seems to mark it as field.
Where the completion api makes a difference between regular fields and setters which is also a getter (or the other way around :P)

**Comment by devoncarew** [comment]
> If some element has a both a getter and a setter, dartdoc seems to mark it as field.

I actually don't think this is a bug, but an artifact of how setters and getters are defined.

**Comment by kasperpeulen** [comment]
@devoncarew Not totally sure what you mean, but I do think it makes sense to treat something which is both a getter and a setter, as a field. 

Anyway, I guess we should have the completion UI icons and the dartdoc ions look the same. Thoughts ? @devoncarew

**Comment by kasperpeulen** [comment]
fixed by https://github.com/dart-lang/dart-pad/pull/221
