### ISSUE TITLE
Transitive packages

### ISSUE THREAD

**Issue by timsneath** [dart-lang/dart-pad#2055]
For packages that are transitive, can we include a one liner under the heading that says something like, "these are not available to be imported"? That would be a great explanation of the difference between the top and the bottom list...

**Comment by RedBrogdon** [comment]
@srawlins, what do you think? A little extra messaging on the popup of package version may save us a bunch of complaints from newer devs. 😄

**Comment by srawlins** [comment]
Sounds good
