### ISSUE TITLE
grind serve exits?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2062]
In my dart-pad repo, `grind serve` (or `grind serve --debug`) now exit immediately after serving. 🤔

**Comment by srawlins** [comment]
@johnpryan have you experienced this?

**Comment by johnpryan** [comment]
No, not yet...

**Comment by srawlins** [comment]
I still can't get past this... my grinder version is 0.9.0. I'm playing with pub dependencies...

**Comment by johnpryan** [comment]
It's working for me with Dart 2.14.1

**Comment by srawlins** [comment]
Ah, I've figured it out. Something is already holding onto port 8000. Preparing a PR that prints stderr.
