### ISSUE TITLE
Support new FlutterFire "pure Dart" Firebase packages

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2068]
This is by and large blocked by https://github.com/FirebaseExtended/flutterfire/issues/3962.

We don't include a JS preamble with the app configuration, so we hit the above issue. Are there ways around this?

CC @puf, @RedBrogdon

**Comment by srawlins** [comment]
@puf it turns out I cannot put a dummy JS configuration in; it needs to have functional values. :(

**Comment by puf** [comment]
For allowing us to test, can you use the values from https://dartpad.dev/?null_safety=true&id=c21e00325f9269f0730a28df473f841c?

Firestore in that project is pretty well locked down with security rules anyway.

**Comment by Salakar** [comment]
Hey @srawlins, @puf - with the FlutterFire release that's just shipped this should no longer be blocked: web Dart implementation across all FlutterFire plugins has been refactored to lazy initialize and default Firebase App initialization from Dart is also now supported. Let me know if any other issues come up, thanks.

https://github.com/FirebaseExtended/flutterfire/blob/master/CHANGELOG.md#2021-11-06

**Comment by srawlins** [comment]
Thanks so much! I'll try out the new packages ASAP

**Comment by srawlins** [comment]
Confirmed this is working great now!
