### ISSUE TITLE
Channel-specific backends need channel-specific pubspecs

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2074]
Right now the various dart-services endpoints are running different version of the Dart/Flutter SDK, but are all using the same pubspec, which means the newer channels aren't opted into new language features like constructor tearoffs.

We should figure out a way to have each endpoint use a channel-specific pubspec for its usercode project, allowing them to demonstrate new Dart features as they arrive in those channels.

**Comment by srawlins** [comment]
I've almost got this one completed. Will mail tonight.

**Comment by srawlins** [comment]
Oops, the Dart Language version is not what we want; you cannot set an SDK constraint of `>=2.15.0 <3.0.0` yet because... \*drumroll\* there is no 2.15.0.

What we want is enabled experiments...

**Comment by domesticmouse** [comment]
Can't we use Dart 2.15.0-0 or similar?

**Comment by srawlins** [comment]
This seems to work!
