### ISSUE TITLE
Ability to maximize code frame/window on phones (small screens)

### ISSUE THREAD

**Issue by paultallard** [dart-lang/dart-pad#2076]
Issue:  Errors and warnings cover up code on smaller screens to the point where the code can no longer be accessed. See attached screenshot.  In this screenshot, a single squiggly bracket '{' obliterates the code making it hard to find and fix the issue. There is no code here so I believe it does not violate your contributing guidelines.

Proposal:  have a button of other mechanism to temporarily hide the error, warning, and linter messages.  

Motivation:  Dartpad can allow some development on small screens (phones) when away from a laptop.  I use it to do research, try out code and build solutions for my office work.  Not being able to see and fix the code is a show stopper.  I believe this simple change would open up Dartpad to much wider use.  

![dartpad screenshot](https://user-images.githubusercontent.com/22717488/141186125-9d3edc7e-f592-49ba-836b-49e1c884ddbf.jpg)

**Comment by parlough** [comment]
Thanks for the issue and detailed information!

With a rewritten version of the frontend, DartPad now has some handling to reduce the scaffolding around the UI on mobile devices and even more so in embed mode.

If you'd like to see further or more specific improvements to the new UI, please open a new issue with details. Thanks again!

**Comment by paultallard** [comment]
Thanks for addressing this and for notifying me of your resolution.  It appears to work well.

Paul Allard
206-679-6315
________________________________
