### ISSUE TITLE
Dart Pad Theme to VS-Code and IntelliJ Themes

### ISSUE THREAD

**Issue by SakhileMamba** [dart-lang/dart-pad#2083]
Please kindly create official VS-code and IntelliJ themes similar to the one you use in Dartpad. Dartpad has an amazing theme and I think these will take off significantly.

**Comment by johnpryan** [comment]
I don't know if we'll have time to do this, but most of the colors are defined in this file: https://github.com/dart-lang/dart-pad/blob/master/lib/scss/colors.scss

**Comment by SakhileMamba** [comment]
@johnpryan  I really hope you will find the time. I'll also have a look at the file and see if I can figure it out on my own.

**Comment by parlough** [comment]
Thanks for the suggestion! Unfortunately we'll likely not have time to create and maintain these themes, but anyone is welcome to use DartPad's colors/theme to create one. You can find some of the colors from DartPad's current UI in https://github.com/dart-lang/dart-pad/blob/main/pkgs/dartpad_ui/lib/theme.dart.
