### ISSUE TITLE
Add support for `rxdart` package

### ISSUE THREAD

**Issue by hoc081098** [dart-lang/dart-pad#2087]
Hi,
Could you add support for [`rxdart`](https://pub.dev/packages/rxdart) package? Since it is a Flutter Favorite package.
- 1504 LIKES
- 125/ 130 PUB POINTS
- 100% POPULARITY.
 
Thanks.

**Comment by RedBrogdon** [comment]
Assigning this to Brett so he can get it into the staging backend.

**Comment by domesticmouse** [comment]
Added to `dev` in https://github.com/dart-lang/dart-services/pull/827
