### ISSUE TITLE
Where is the document, please. I want to know how dartpad displays the back-end results to the web page

### ISSUE THREAD

**Issue by lycstar** [dart-lang/dart-pad#2093]
Thanks.

![image](https://user-images.githubusercontent.com/37872392/143667866-d13cecdd-69b7-4384-a349-5804c5f4910e.png)

**Comment by domesticmouse** [comment]
The backend is a Cloud Run hosted Dart compilation tool. See https://github.com/dart-lang/dart-services for more detail.
