### ISSUE TITLE
Have option to put editor on top, and output on bottom.

### ISSUE THREAD

**Issue by CalidumCanis** [dart-lang/dart-pad#2094]
When I am working split screen in dartpad it is very hard to see the code when the editor is so thin, so please add the option to switch orientation from horizontal to vertical also.
Something like the image below:
![dartpad](https://user-images.githubusercontent.com/74233464/144048484-131b4d07-62b5-4c66-97ad-6e9f70a0eb9b.png)
Thanks.

**Comment by Aspireve** [comment]
Hey Hi @RedBrogdon 
Could I work on this issue as it seems to be just a change in the direction of the display boxes?

**Comment by parlough** [comment]
Thanks for the suggestion!

We've explored an alternative direction where in narrow environments the editor and output are different tabs, preventing one or the other from being too thin or too short.

If anyone would like to see further adjustments or this capability still though, please feel free to continue the discussion here or open a new issue. Thanks :D
