### ISSUE TITLE
It's good that extended to cloud ide like flutlab.io

### ISSUE THREAD

**Issue by garawaa** [dart-lang/dart-pad#2104]
New feature suggestion.

**Comment by domesticmouse** [comment]
DartPad isn't attempting to become a full Flutter IDE, it is more aimed at initial investigation and lightweight ideation. I have had success using [GitHub Codespaces](https://github.com/features/codespaces) as a Flutter development environment by installing the [Flutter VSCode extension](https://docs.flutter.dev/development/tools/vs-code) and [installing Flutter manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually).

I'm sure other environements like [Gitpod.io](https://www.gitpod.io/) and Google [Cloud Shell](https://cloud.google.com/shell) could be used similarly.
