### ISSUE TITLE
Add support for the english_words package

### ISSUE THREAD

**Issue by rasmusmaagaard** [dart-lang/dart-pad#2105]
To be able to complete the [Write your first Flutter app](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1) tutorial from the flutter team, DartPad should support the [english_words](https://pub.dartlang.org/packages/english_words) package.

**Comment by RedBrogdon** [comment]
Assigning this to Brett so he can get it into the staging backend.

**Comment by domesticmouse** [comment]
`english_words` is already included in the `dev` branch.
