### ISSUE TITLE
completion sorting

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#211]
We're now getting the sorting from the server, and doing the filtering in the client. When I type `.text` on a DivElement:

![screen shot 2015-03-30 at 3 01 20 pm](https://cloud.githubusercontent.com/assets/1269969/6907903/138c50b8-d6ef-11e4-9a2b-8ea2173ac03a.png)

I get `contextMenu` showing up first, when there's a direct match for `text`. This issue started showing up when we started matching on `contains` in the string; `startsWith` didn't have this issue. I think short-term we should move back to using startsWith, and long term have all filtering and sorting down on the server.

@lukechurch @kasperpeulen

**Comment by devoncarew** [comment]
This is esp. annoying to the user, as they will type in `e.text`, hit return, and have `e.contextMenu` entered in :(

**Comment by kasperpeulen** [comment]
Agree, this is really annoying. What is going on with those arrows icons btw, shouldn't those be circled p's ?

**Comment by lukechurch** [comment]
>I think short-term we should move back to using startsWith, and long term have all filtering and sorting down on the server. 

I think this makes sense. I hadn't forseen this feature interaction :(

**Comment by devoncarew** [comment]
I was experimenting with representing getters and setters with left and right arrows. The arrows are different lengths though (the right arrow is shorter than the left) in our current font, so it didn't look good as I had it -

**Comment by devoncarew** [comment]
We moved back to filtering using `startsWith`.

**Comment by kasperpeulen** [comment]
@devoncarew @lukechurch 
I added some filtering logic to this PR https://github.com/dart-lang/dart-pad/pull/218
which moves a 100% match on top 

Maybe we can change back to contains if we add this filtering ?

**Comment by devoncarew** [comment]
we have a workaround
