### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by rahulbhai9** [dart-lang/dart-pad#2110]
I am trying to use dartpad on my Android phone with screen reader (Android accessibility suite).
"More samples" menu is completely inaccessible and cannot be navigated using swiping gestures.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue. DartPad is primarily intended to work in desktop browsers. We just haven't had the staffing to design UI for mobile devices. 

That said, we're tracking Android-related issues in #876. I'm going to close this as a duplicate, but it'll be referenced from that issue.
