### ISSUE TITLE
Remove dev channel support from DartPad

### ISSUE THREAD

**Issue by khyati82** [dart-lang/dart-pad#2111]
This is mirror of bug  [#94974](https://github.com/flutter/flutter/issues/94974)
This issue is related to removing dev channel from Flutter builds. Remove dev channel from DartPad
The work for removing dev channel is tracked as part of this master issue - [#94962](https://github.com/flutter/flutter/issues/94962)

@domesticmouse - DartPad (the front end) has already removed dev as an option before shipping the feature. I'm keeping dev as a backend option as we are thinking about exposing the version that google3 is currently running with as a replacement for dev.

**Comment by domesticmouse** [comment]
@devoncarew where are we at on deciding if we want to expose the google3 version of flutter and dart on DartPad?

**Comment by devoncarew** [comment]
I think we should remove support for the dev channel from DartPad for now. If some future channel exists - which represents the bits that have successfully rolled into google3 - we could then consider supporting that channel. I don't expect that channel to exist in the near term, but have not been in recent conversations about it.

**Comment by RedBrogdon** [comment]
Dev channel has been removed in the latest deployment.
