### ISSUE TITLE
 Weird behaviour on use of int & double data type

### ISSUE THREAD

**Issue by codeilm** [dart-lang/dart-pad#2113]
```
void main(){
  double a = 1.0;
  int b = 1;
  print(a.runtimeType);
  a = 1;
  print(a.runtimeType);
  print(b.runtimeType);
}

/// Output on DartPad :
// int
// int
// int
/// Output when using VS Code
// double
// double
// int 

```

**Comment by parlough** [comment]
Dart has some difference in number semantics and implementation across platforms, particularly on web where it has some larger differences to fit into the JavaScript model. 

I recommend reading this section on [Types and type checking](https://dart.dev/guides/language/numbers#types-and-type-checking) from the Numbers in Dart article for a more detailed explanation. The whole article is a good read for more information about numerical platform differences as well.

**Comment by codeilm** [comment]
Ok, thanks.

**Comment by codeilm** [comment]
int and double behaves differently in Dartpad due to javascript behind the scene. So, when learning data types in deep, then just install the Dart SDK and practice locally on your machine.
