### ISSUE TITLE
GOOGLE! DON'T RECOMMEND TOYS LIKE THIS UNLESS

### ISSUE THREAD

**Issue by garawaa** [dart-lang/dart-pad#2117]
GOOGLE! DON'T RECOMMEND TOYS LIKE THIS UNLESS IT DOES NOT SUPPORT PUBSPEC.YAML AND ASSETS

**Comment by domesticmouse** [comment]
DartPad is not intended as a full app development environment. It is intended as an environment to help people experiment while getting started. Adding the capability to support any package, including code generation, as well as asset uploads, is problematic on both cost and security review fronts.
