### ISSUE TITLE
dart-services, Route not found

### ISSUE THREAD

**Issue by mafreud** [dart-lang/dart-pad#2127]
Hi!
I have deployed dart-services to cloud run (port 8082), but it shows Route not found.
The same message is displayed in all the following URLs.
Does anyone have a solution?

- https://dart-services-test-aqoi5bfw7a-uc.a.run.app/
- https://dart-services-test-aqoi5bfw7a-uc.a.run.app/api/
- https://dart-services-test-aqoi5bfw7a-uc.a.run.app/api/dartservices/
- https://dart-services-test-aqoi5bfw7a-uc.a.run.app/api/dartservices/v2/
- https://dart-services-test-aqoi5bfw7a-uc.a.run.app/api/dartservices/v2/analyze

**Comment by domesticmouse** [comment]
You'll see the same thing on https://stable.api.dartpad.dev/

Have a look at https://github.com/dart-lang/dart-services/tree/master/example for a sample web app that talks to `dart-services`

**Comment by mafreud** [comment]
@domesticmouse Thank you fr your quick reply!
I will check it out 😄

**Comment by mafreud** [comment]
@domesticmouse 
If I remember correctly, I think I could open [index.html](https://github.com/dart-lang/dart-services/blob/master/example/web/index.html), could you tell me how to access it?
