### ISSUE TITLE
Repurpose dev endpoint as a staging environment

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2131]
We've used one-off staging deployments for a while as a means to test new features. With the addition of package support, though, we'll need a staging environment that's longer-lived and more easily accessed so that multiple people can test whether certain packages/plugins truly work and then write sample gists for them.

The current plan is to repurpose the dev channel endpoint, which is no longer needed now that Flutter has dropped its dev channel to focus on beta releases. Tasks for that approach:

- [x]  Get the dart-services dev channel endpoint building with the stable channel and its own configuration of packages/plugins.
- [ ]  Update dart-pad's query parameter code and service URL setup so that we can construct URLs that will cause DartPad to hit the dev endpoint.

**Comment by domesticmouse** [comment]
Bug for step 2: https://github.com/dart-lang/dart-pad/issues/2159

**Comment by parlough** [comment]
Closing for now as there hasn't been continued desire for this, as we can always test changes locally. If anyone would still like to see this though, please reopen the issue or open a new one with more use case information. Thanks!
