### ISSUE TITLE
Flutter 2.10 beta triggers lint warning in Sunflower sample

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#2147]
[Repro case](https://dartpad.dev/?channel=beta&id=5c0e154dd50af4a9ac856908061291bc)

<img width="1099" alt="Screen Shot 2022-01-21 at 8 59 12 pm" src="https://user-images.githubusercontent.com/30503/150516223-d481cf9c-3d99-4fe2-83ba-1523a1b242df.png">

**Comment by RedBrogdon** [comment]
Source gist has been fixed.
