### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2149]
If a Gist contains multiple`.dart` files, display them in the UI and include them when dart-services compiles JS. Show tabs at the top, similar to the tabs used in [Svelte REPL](https://svelte.dev/repl/hello-world).

## Example

**main.dart**
```dart
import 'library.dart';

void main() {
  print(calculate());
}
```

**library.dart**
```dart
int calculate() => 42;
```

### Related issues
- https://github.com/dart-lang/dart-pad/issues/1654
- https://github.com/dart-lang/dart-pad/issues/1290
- https://github.com/dart-lang/dart-pad/issues/1388
- https://github.com/dart-lang/dart-pad/issues/562

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, it was decided to not support the multi-file use case to focus on what DartPad does best. If anyone is still interested in this, please open a new issue for discussion, thanks!
