### ISSUE TITLE
Add UI for notes, warnings, and tips

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2153]
Workshops often need to tell the user to take an action:

<img width="508" alt="Screen Shot 2022-01-25 at 11 07 11 AM" src="https://user-images.githubusercontent.com/1145719/151042615-ff032917-ab7b-449d-8c66-023d7cc94906.png">

It could be helpful to add some special syntax for this:

<img width="446" alt="Screen Shot 2022-01-25 at 11 06 44 AM" src="https://user-images.githubusercontent.com/1145719/151042544-b5db58eb-76f3-4908-9387-f21b2a8f7642.png">

<img width="289" alt="Screen Shot 2022-01-25 at 11 08 19 AM" src="https://user-images.githubusercontent.com/1145719/151042785-2ba93c5b-6dda-4f1f-a706-674470d17609.png">

 We could add some special CSS classes, and authors could add some HTML to their markdown files:

```html
<div class="dartpad-workshop-note">
Note goes _here_.
</div>
```

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires a feature similar to this in DartPad or a new form of workshops, please discuss that in a new issue. Thanks!
