### ISSUE TITLE
Encourage formatting

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2155]
Flutter snippets are more understandable when formatted. We should encourage workshop users to format code, especially if they are copy/pasting.

Some ideas: 
- Highlight the Format button if the user runs unformatted code
- Auto format on paste?
- Add a help screen for the UI and introduce dartfmt there?

**Comment by parlough** [comment]
As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, the workshop functionality this was related to was removed.

If anyone would like to see similar functionality brought back, please check out https://github.com/dart-lang/dart-pad/issues/2702 or open a new issue. Thanks so much!
