### ISSUE TITLE
Don't expose filesystem of the machine that deploys dart-services

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2157]
The JS console reveals filesystem details:

```
errors.dart:202 Uncaught Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/widgets/framework.dart:2577:20
_debugCurrentBuildTarget == context
is not true
    at Object.throw_ [as throw] (errors.dart:251)
    at Object.assertFailed (errors.dart:29)
    at framework.dart:2577
    at framework.BuildOwner.new.buildScope (framework.dart:2580)
    at RenderObjectToWidgetAdapter.new.attachToRenderTree (binding.dart:1111)
    at binding$.WidgetsFlutterBinding.new.attachRootWidget (binding.dart:943)
    at binding.dart:924
    at internalCallback (isolate_helper.dart:48)
```

See https://github.com/dart-lang/dart-pad/issues/1966 for steps to reproduce

**Comment by domesticmouse** [comment]
@srawlins Any ideas on if this is even possible?

**Comment by srawlins** [comment]
When compiling DDC on the dev's workstation, we could first `cd` to a temp directory with a known suffix (say `_foo/`), then remove that text from errors (`s#file:///.*_foo/##`).

**Comment by johnpryan** [comment]
Related to https://github.com/dart-lang/dart-pad/issues/1365

**Comment by parlough** [comment]
I'm going to consolidate this issue in to https://github.com/dart-lang/dart-pad/issues/3008 alongside other exception surfacing changes. Thanks for the report!
