### ISSUE TITLE
Allow lints to be customized

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2158]
Certain lints like `prefer_const_constructors` might not be desirable for codelabs aimed at beginners. See [this discussion](https://github.com/flutter/codelabs/pull/272#discussion_r793939016) for more context.

It would be great if authors could include an `analysis_options.yaml` file in their Gist or workshop, rather than using `// ignore_for_file:` syntax.

**Comment by domesticmouse** [comment]
Given that customised lints would require stopping and re-starting the analysis server, this change would balloon the required number of servers by the number of seconds the restart takes (we usually serve most requests in under a second). 

I suspect this will fall into the DartPad isn't an IDE bucket.

**Comment by parlough** [comment]
I was thinking about this and another solution to solve part of the issue would be to somehow allow for pad creators to somehow specify and hide a header to the file(s). This way they could optionally [ignore](https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file) specific rules or all lint rules.

**Comment by parlough** [comment]
Closing this in line with Brett's "I suspect this will fall into the DartPad isn't an IDE bucket."

We have reduced DartPad to only using the `core` set of lints rather than the larger `recommended` or `flutter` sets that brought in the `prefer_const_constructors` lint mentioned as an example.
