### ISSUE TITLE
Question for hosting dart pad on the dynamic web 

### ISSUE THREAD

**Issue by hanmo2000110** [dart-lang/dart-pad#2160]
I want to host the **dart-pad** on the dynamic web.
So, I hosted custom dart pad and dart service by firebase Hosting and Google Cloud Run.
Is this the right way?

**Comment by domesticmouse** [comment]
I'm curious what the dynamic web is...

**Comment by hanmo2000110** [comment]
It means that the web contents can be changed.

**Comment by hanmo2000110** [comment]
sorry for my bad explanation.
I wanted to ask about firebase hosting and network 

1. I saw that firebase hosting supports dynamic contents by Cloud Function and Cloud Run. but our custom dart-pad works dynamically without them. So, I did some research about dart-pad. And I concluded that the dart files are converted to Js file when we build a dart-pad web and deploy it. and Js files are worked dynamically.

The first question is, is my conclusion correct?

2. this is about dart-pad network question
dart-pad guide suggest to use app engine to host dart-pad.
but I didn't use app engine for some reasons. So, I used firebase hosting. 
I was worried if the dart pad was connected to the App Engine. therefore, I checked the network tap in the developer tool.
And I didn't find any connection with App Engine. 

The second question is, if I used Firebase hosting, is there no connection with App Engine or other Google services?

**Comment by domesticmouse** [comment]
DartPad is a two part system. [DartPad](https://github.com/dart-lang/dart-pad) is a website written in Dart and compiled to JavaScript, which makes API calls to [dart-services](https://github.com/dart-lang/dart-services) which is a CloudRun hosted Dart compiler API. The `dart-services` API is responsible for taking Dart code and either running the Analyzer over it, or alternatively, compiling the code to JS, which the DartPad front end injects into a [sandbox iFrame](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).
