### ISSUE TITLE
what is the best way to host custom dart pad

### ISSUE THREAD

**Issue by hanmo2000110** [dart-lang/dart-pad#2164]
we are trying to embed dart-pad in our flutter website.
we hosted dart-pad using firebase hosting. and dart-service by Cloud Run of GCP.
we created save button in our dart-pad. when user clicks it, user's code is saved in Github by using Github REST API.
we use cloud run to add more custom packages in dart-services.

my questions are
- Is there anything unnecessary in the above process?
- Is there a better way than the above process?
- Can I use firebase hosting instead of the app engine?
- Do you have any plans to support multiple files?

**Comment by johnpryan** [comment]
https://github.com/dart-lang/dart-pad/issues/2149 is the meta-issue for multiple file support. You can embed DartPad on any site by following the https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide - you don't necessarily need to run dart-services yourself unless you need custom packages.
