### ISSUE TITLE
WE NEED A LIGHT THEME !!!

### ISSUE THREAD

**Issue by repo-2017** [dart-lang/dart-pad#2166]
### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by repo-2017** [comment]
I open a dartpad and light theme is not the default state - that's a serious defect, making it unusable.

**Comment by parlough** [comment]
Thanks for the feature request @repo-2017!

For embedded DartPad iframes, it is possible to switch between light and dark themes [through query parameters](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#query-parameters). This feature has not yet been implemented for the main DartPad playground though.

This feature request is currently being tracked at https://github.com/dart-lang/dart-pad/issues/1260 where you've commented as well, so I'm going to close this one as a duplicate.

Thanks again :)
