### ISSUE TITLE
Again : add a LIGHT theme !

### ISSUE THREAD

**Issue by repo-2017** [dart-lang/dart-pad#2167]
How crazy it is to skip on the light theme support ...

**Comment by parlough** [comment]
Thanks for the feature request @repo-2017! As I mentioned in the other issue:

For embedded DartPad iframes, it is possible to switch between light and dark themes [through query parameters](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#query-parameters). This feature has not yet been implemented for the main DartPad playground though.

This feature request is currently being tracked at https://github.com/dart-lang/dart-pad/issues/1260 where you've commented as well, so I'm going to close this one as a duplicate.

Thanks again :)
