### ISSUE TITLE
dartpad output error 

### ISSUE THREAD

**Issue by sibhatmeq** [dart-lang/dart-pad#2172]
### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```
void main() { 
  
  List<String> myList =[
    
    'Angela',
    'James',
    'katie', 
    'Jack',
    
  ];
  
  print( myList[3]);
  print(myList.indexOf('Katie'));
  
  myList.add('Ben');
  
  print(myList);
  
}  
### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

Jack
-1   
[Angela, James, katie, Jack, Ben]
```
[paste console output here]
```
-1 output is the wrong output it must be 2 
![Screenshot (21)](https://user-images.githubusercontent.com/58430376/154999963-e237d0f8-083d-4baf-92f9-34d9c6d39f01.png)

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by parlough** [comment]
Hi @sibhatmeq, thanks for opening an issue. It looks like your list includes `'katie'` with a lower case “k” while your `indexOf` checks for `'Katie'` with an uppercase “K”. 

If you update them to match then you should get the expected result of 2. Let me know if that doesn’t make sense or you have any other issues. Thanks again!

**Comment by sibhatmeq** [comment]
hii parker lougheed, it is not upper case and lower case issue i have been
tried today the i got the same result -1

**Comment by parlough** [comment]
Are you able to send your updated code?

I tried to create a minimal example where both the list and the indexOf contain `'Katie'` with an uppercase "K" and it seems to be working as expected:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/18372958/155185661-3e24d10a-cfea-4170-82d8-33cfd7b7750a.png">
