### ISSUE TITLE
Add support for `riverpod_navigator`

### ISSUE THREAD

**Issue by PavelPZ** [dart-lang/dart-pad#2174]

**Comment by johnpryan** [comment]
Closed in #995

**Comment by domesticmouse** [comment]
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.
