### ISSUE TITLE
Add support for `html` package

### ISSUE THREAD

**Issue by ZubairDastan** [dart-lang/dart-pad#2179]

**Comment by ZubairDastan** [comment]
Unsupported import(s): (package:html/parser.dart)

**Comment by domesticmouse** [comment]
Just to confirm, you are referring to https://pub.dev/packages/html correct?

**Comment by ZubairDastan** [comment]
Yes

**Comment by domesticmouse** [comment]
@srawlins can you please explain why you gave this package a downvote? Is it known bad inside a web browser? Should we close this request outright?

**Comment by srawlins** [comment]
It is a soft-abandoned, soft-deprecated package. It is very old and we just haven't funded any replacement. ☹️ .

I think there is also nothing in package:html that can't be done with dart:html... maybe something like parsing a document fragment.

I would +1 to close the request.
