### ISSUE TITLE
Display the compiled js from Dart/Flutter in chrome

### ISSUE THREAD

**Issue by mafreud** [dart-lang/dart-pad#2181]
I am currently learning about the dart-pad system, dart-services, trying to build custom dartpad. 
I can POST to https://stable.api.dartpad.dev/ and compile the dart(Flutter) code to js with DDC. 
However, how does DartPad display this compiled js in chrome?

**Comment by johnpryan** [comment]
DartPad uses an [iframe](https://github.com/dart-lang/dart-pad/blob/master/web/scripts/frame.html) with a [script](https://github.com/dart-lang/dart-pad/blob/master/web/scripts/frame.js) that bootstraps the flutter app.
