### ISSUE TITLE
DartPad on dev channel is analyzing using Stable API

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#2185]
## What happened?

Using the dev channel to test new packages shows missing package analysis warning:

<img width="429" alt="Screen Shot 2022-03-04 at 9 46 49 am" src="https://user-images.githubusercontent.com/30503/156672186-c38fbc85-7f27-4b79-97a2-292feefbc84f.png">

## Steps to reproduce problem

  - Navigate to https://dartpad.dev/?channel=dev&id=2ce7a8494c58dcf8d7fe6499f5047844
  - Pop open the network console
  - Notice Analysis requests going to https://stable.api.dartpad.dev/api/dartservices/v2/analyze
  - Should be https://dev.api.dartpad.dev/api/dartservices/v2/analyze

**Comment by johnpryan** [comment]
It looks like we make an `/analyze` request before the query parameters read. The first one goes to `stable.api` and the other two go to `dev.api`.

<img width="656" alt="Screen Shot 2022-03-04 at 9 51 09 AM" src="https://user-images.githubusercontent.com/1145719/156815751-1b88e7a7-f47b-4d9c-be8a-9c785e614011.png">
