### ISSUE TITLE
DartPad site doesn't open without the "www" subdomain

### ISSUE THREAD

**Issue by definite-d** [dart-lang/dart-pad#2194]
## What happened?
Upon navigating to https://dartpad.dev , I either get a timeout error in my browser, or the site keeps loading for eternity. 

![Screenshot_20220316-105950](https://user-images.githubusercontent.com/38317208/158566938-de1df8a7-7045-4fed-8200-b98224dae065.png)

https://www.dartpad.dev opens properly though. 
![Screenshot_20220316-110030](https://user-images.githubusercontent.com/38317208/158567046-d8f66c8c-2b6d-48c8-a692-67640070231d.png)

I expected both URLs to redirect to the same webpage.

## Steps to reproduce problem

Just navigate to https://dartpad.dev
### Browser

Browser: Microsoft Edge on Windows 10, Mozilla Firefox on Android 7

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system: Android

Version: 7

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by parlough** [comment]
Seems both links are working for me. Did you close this as it is working for you now?

**Comment by definite-d** [comment]
Yes, I did. They're working now, thank you.
