### ISSUE TITLE
Suggested package pairing: `yaml` and `yaml_edit`

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2195]
They're both small and I think DartPad would be the perfect environment for playing with parsing and editing YAML.

**Comment by srawlins** [comment]
Quick update, the priority for `yaml_edit` for me personally has dropped a lot. But still, small. And I still think `package:yaml` would be a great addition.

**Comment by domesticmouse** [comment]
Actually, `yaml_edit` looks like a really good fit for a project i'm working on. thanks for the pointer @srawlins!

**Comment by domesticmouse** [comment]
This is now available in production DartPad
