### ISSUE TITLE
Embeds don't call analyze() during initialization

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2197]
Embeds don't run analyze right away. For example, see this [invalid Dart snippet](https://dartpad.dev/embed-flutter.html?id=be111bbae41dd57399e558835e2ad345). This is because we tell it not to:

https://github.com/dart-lang/dart-pad/blob/36192896815f9d6d175a858f238d526bad191f55/lib/embed.dart#L489

@RedBrogdon is this a design choice or just an oversight?

**Comment by parlough** [comment]
This relevant code and special embed functionality no longer exists, so closing this issue as stale. If anyone is experiencing similar issues, please open a new issue with reproduction information. Thanks so much!
