### ISSUE TITLE
Add Support for `video_player` Package

### ISSUE THREAD

**Issue by searchy2** [dart-lang/dart-pad#2202]
`video_player` has 100% popularity and is very commonly used!

Any layout that needs to play video will most likely use `video_player`.

**Comment by domesticmouse** [comment]
Pub package: https://pub.dev/packages/video_player

**Comment by johnpryan** [comment]
Closed in #995

**Comment by domesticmouse** [comment]
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.
