### ISSUE TITLE
Disassembly

### ISSUE THREAD

**Issue by mikerreed** [dart-lang/dart-pad#2205]
Can it output 'anything' that might tell us what sort of native instruction would get produced?

Not looking for exact answer, but any form of annotated ASM-like commands would tell us things about our code's efficiency...

- did Dart inline this small getter?
- did Dart pull this common expression out of the loop?
- did Dart have to convert between int/double/etc.?
- etc.

Perhaps there is another tool somewhere that already provides this. If so, point me there and perhaps dartpad need not also provide that...

thanks,

**Comment by johnpryan** [comment]
You can use DevTool's [App Size tool](https://docs.flutter.dev/development/tools/devtools/app-size)
