### ISSUE TITLE
Connecting to Firebase Realtime Database throws cross-origin error

### ISSUE THREAD

**Issue by puf** [dart-lang/dart-pad#2215]
## What happened?

Connecting to the Firebase Realtime Database in Dartpad (dev channel at the moment) raises

> Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.

And:

> Sandbox access violation: Blocked a frame at "https://dartpad.dev" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.

## Steps to reproduce problem

https://dartpad.dev/?channel=dev&id=ea50f75646c5fb0c4433a4b82cfb5fea

### Browser

Browser: Chrome

Version: Version 99.0.4844.83 (Official Build) (x86_64)

Errors in JavaScript console: 

```
Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
```
And:
```
Sandbox access violation: Blocked a frame at "https://dartpad.dev" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.
```

### Machine

Operating system: macOS

Version:

### Your code

See Dartpad that I linked in Steps-to-reproduce :)

**Comment by domesticmouse** [comment]
To drop the Sandbox constraints we need to go back through Security Review for Dart Services. I'd really prefer not to have to go through Security Review again =)

**Comment by parlough** [comment]
Thanks for the report and extensive details. As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, support for Firebase was removed for now, so I'm going to go ahead and close this issue as stale.

If anyone reading this would like to see Firebase support or similar added back, please consider starting that discussion in a new issue. Thanks :)
