### ISSUE TITLE
Add support for relative image paths in workshops

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2216]
It might be possible to configure our markdown generator to support relative paths for image URLs. This is a pain point for authors who develop on a local machine on `localhost` and would like to also make the image requests to `localhost` too.

**Comment by johnpryan** [comment]
We might be able to provide a custom [`imageLinkResolver`](https://pub.dev/documentation/markdown/latest/markdown/markdownToHtml.html) that can handle relative links correctly.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires a feature similar to this in DartPad or a new form of workshops, please discuss that in a new issue. Thanks!
