### ISSUE TITLE
Requests are still made to stable.api with dev channel

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2224]
Steps to reproduce:

- open Chrome DevTools
- go to https://dartpad.dev/?channel=dev&id=ea50f75646c5fb0c4433a4b82cfb5fea
- observe that there are a few requests to `/analyze` made to `stable.api`

Eventually we make a request to `dev.api` so any diagnostics that come from the stable channel aren't shown to the user, but we should probably clean this up anyway.

**Comment by parlough** [comment]
Trying this out with the new frontend, it appears the first analyze request does get routed to the correct channel. Please feel free to reopen or open a new issue if you're still seeing analyze requests routed incorrectly. Thanks!
