### ISSUE TITLE
Using Google Analytics for Firebase raises error "IndexedDB unavailable or restricted in this environment."

### ISSUE THREAD

**Issue by puf** [dart-lang/dart-pad#2228]
## What happened?

When trying to use Google Analytics for Firebase in Dartpad I get "IndexedDB unavailable or restricted in this environment". Full error message below.

## Steps to reproduce problem

https://dartpad.dev/?channel=dev&id=3d14bd0ee70e385b7eaa29c7ee6e9621

## Additional info

Error message in the browser's JavaScript console
```
@firebase/analytics: Analytics: IndexedDB unavailable or restricted in this environment. Wrap initialization of analytics in analytics.isSupported() to prevent initialization in unsupported environments. Details: SecurityError: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context. (analytics/indexeddb-unavailable).
```

A compatibility issue with IndexedDB was fixed in the v9 version of the Firebase JavaScript SDKs recently, but as the error message said the code should check whether the environment support analytics before logging events and `analytics.isSupported()` is not wrapped in FlutterFire.

**Comment by johnpryan** [comment]
Is this still an issue?

**Comment by puf** [comment]
When I run the attached Dartpad, it says:

> defaults.ts:93 Uncaught (in promise) DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

**Comment by johnpryan** [comment]
Thanks for the update - keeping this a P1

**Comment by domesticmouse** [comment]
> The document is sandboxed and lacks the 'allow-same-origin' flag.

This is intentional, and I have no intention of walking back the security first stance.

**Comment by johnpryan** [comment]
Shall we close this as not planned?
