### ISSUE TITLE
Save via DartPad-owned Gist

### ISSUE THREAD

**Issue by Deleplace** [dart-lang/dart-pad#2239]
Hi, I've read related issues #1735, #806, #805, #2169, and the [Sharing guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide).

I acknowledge that several options for a seamless "save" button have already been discussed, and that offering storage would lead to many problems.

Can we discuss the following option, which seems to be what the [Rust Playground](https://play.rust-lang.org/) is doing:
- create a DartPad bot GitHub account,
- on "Share", let the bot use its GitHub account to create a Gist.

The main obvious challenge is: what to do if users create a lot of garbage in the bot's GitHub account.

**Comment by Deleplace** [comment]
@timmaffett it works for me and is very smooth, thank you!!

I just used it to quickly create a target URL for the "Demo" link in [this page](https://programming-idioms.org/idiom/55/convert-integer-to-string/577/dart).

A few thoughts in my next comment below.

**Comment by Deleplace** [comment]
_Adding feedback here and also copying it to #2227_

The "Login to Github" workflow is asking for "read and write access" to "all of my public and secret gists".

<img width="350" alt="image" src="https://user-images.githubusercontent.com/13508141/177121852-ec3e0299-fa4e-4a59-9d80-48fcbb1a7850.png">

This is more privilege than needed for my use case, as I only want to create public DartPad entries using public gists. When I started the auth workflow, I wasn't really expecting to give full access to my secret gists to a 3rd party. I have not checked yet if GitHub offers a less privileged option, giving RW access only to my public gists.

I acknowledge that using "Private Gists" (secret gists) is now a feature in DartPad

<img width="250" alt="image" src="https://user-images.githubusercontent.com/13508141/177122674-ca982666-de16-4907-bc1d-cd1686d54878.png">

However, there is a cognitive burden in making sure that users understand the subtle privacy model:
- [Secret gists aren't private](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists#about-gists), as documented by GitHub,
- Anyone knowing the ID of a gist can access (read) the gist content,
- Transitively, DartPad uses the Gist ID in snippet URLs, which means that anyone knowing the URL of a DartPad snippet can access (read) the gist content, and all of its future versions.

**Comment by johnpryan** [comment]
Read and write access is required for this feature - the tradeoff here is to accept GitHub Gist's privacy semantics (gists are always public, even secret gists) to avoid maintaining a custom server to store snippets and authenticate users.

This isn't something we plan to change soon, so I'm going to close this issue. Feel free to comment or file another issue if you would like to change how GitHub integration works.
