### ISSUE TITLE
No suggestions box shown to often

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#224]
I think no suggestions popup should only be shown if 

1. there was already a popup with suggestions
2. the popup is specifically invoked with Ctrl+enter

point 1 is not to hard to fix, we could just add the extra condition `(ed.completionActive)` 

point 2 is a bit more though, any suggestions how to differentiate between an automatically invoked popup and a specifically invoked popup ?

**Comment by devoncarew** [comment]
+1 to the 2nd point, we should only show 'no suggestions' if the completion was explicitly requested by the user.

**Comment by kasperpeulen** [comment]
see https://github.com/dart-lang/dart-pad/issues/234
