### ISSUE TITLE
Unhandled exceptions are sometimes not surfaced

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-pad#2240]
## What happened?

Sometimes unhandled async exceptions don't show up in the Console output area.

## Steps to reproduce problem

The problem does not reproduce reliably. Refreshing the page seems to result in either having exceptions work, or not work. When they don't work they will be consistently suppressed on every run until the page is reloaded.

### Browser

Browser: Chrome

Version: 100.0.4896.75

### Machine

Operating system: macOS Monterey

Version: 12.3.1

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```dart
void main() {
  throw 'sad';
}
```

### DartPad's output

There is sometimes no output at all, or there is the expected output:

```
Uncaught Error: sad
```

In either case, the browser JS debugger console does show the error

```
Uncaught sad
    at Object.wrapException (<anonymous>:356:17)
    at <anonymous>:3101:23
    at _wrapJsFunctionForAsync_closure.$protected (<anonymous>:2549:15)
    at _wrapJsFunctionForAsync_closure.call$2 (<anonymous>:3484:12)
    at Object._asyncStartSync (<anonymous>:2493:20)
    at main (<anonymous>:3106:16)
    at <anonymous>:4255:7
    at <anonymous>:4238:7
    at dartProgram (<anonymous>:4249:5)
    at <anonymous>:4257:3
```

**Comment by parlough** [comment]
I'm going to consolidate this issue in to https://github.com/dart-lang/dart-pad/issues/3008 alongside other exception surfacing improvements. Thanks for the details!
