### ISSUE TITLE
Support for change of font-size

### ISSUE THREAD

**Issue by himanshubanerji** [dart-lang/dart-pad#2241]
Button to change font size without the need to zoom all the way in

**Comment by johnpryan** [comment]
@himanshubanerji can you help me understand the use-case? It seems like `ctrl +` to zoom is working, but might not be ideal...

**Comment by parlough** [comment]
Thanks for the suggestion! The DartPad UI does function correctly with the browser zoom functionality and the scaffolding adapts according to the user's browser font size configuration.

As for extra customizability of the editor font size, I think that is better left to be supported by full text editors and IDEs. If you'd like to develop Flutter apps on the web, consider [Project IDX](https://idx.dev/) which has built-in support for Flutter or other environments like [GitHub Codespaces](https://github.com/features/codespaces).

If you'd still like to see changes here, please feel free to continue the discussion or open a new issue. Thanks again!
