### ISSUE TITLE
linux issue

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#225]
@zoechi showed me that at linux chrome latest version there is some very strange issue with the footer:

![](https://lh3.googleusercontent.com/-7wt8VOaAOgA/VRr3Yq6VsvI/AAAAAAAAEkg/cHd1gFRkaQ8/w1988-h1288-no/gitbacklog2.png)

if you resize the bar above console, documentation, then it doesn't resize that, but the footer underneath

(also happens at dartpad.dartlang.org)

**Comment by lukechurch** [comment]
Bounce rate on Linux is 8x higher than OS X and Windows. I think we need to do something about this. @devoncarew lets chat about it

**Comment by zoechi** [comment]
This works in Dartium Version 39.0.2171.0 (64-bit) but not in Chrome Version 41.0.2272.118 (64-bit)

**Comment by devoncarew** [comment]
fixed?

**Comment by zoechi** [comment]
Yup, works in Version 43.0.2357.81 (64-bit)
