### ISSUE TITLE
Dartpad: Heading3 (h3) font too small

### ISSUE THREAD

**Issue by brianegan** [dart-lang/dart-pad#2250]
- h3 Font is too small (1em, or 14px)
  - body font is explicitly 16px, larger than h3. This makes it hard to scan the document for headings.
  - h2 font is 1.5 em, or 21px.
  - Suggestion: h3 font should be set to 18px or 1.25em.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires any feature similar to workshops, please discuss that in a new issue. Thanks!
