### ISSUE TITLE
Dartpad Workshops: Keep code I've written moving from one step to the next

### ISSUE THREAD

**Issue by brianegan** [dart-lang/dart-pad#2251]
Problem statement:

  - As a workshop taker
  - when I've worked on a step for a bit and like my solution
  - Then I move to the next step
  - All of the code I've written in the previous step is now gone. 

I cannot navigate back to the step to see my solution, the code is always replaced with the contents of `snippet.dart`. This is quite a bummer in many workshops, where you may want to go back and forth to build upon the code you've written before.

Possible Solution: Start with snippet.dart, then keep contents in localstorage when moving away from step. Display contents kept in localstorage when returning to the step. This would also handle the case of needing to reload at some point.

**Comment by timmaffett** [comment]
I have created a PR (#2260) as an example of a possible solution to the problem you have detailed..  

The change adds localstorage memory for any changes the user makes for each of the steps of the workshop.  
Other details:
  - once the user edits a steps snippet a 'revert' icon is added next to the run button that allows going back to the original snippet
  - if the user does revert to the original snippet the revert icon changes to a 'restore last edit' icon allowing you to go back to source as you last edited it (in case the user presses revert button in error they can still get it back, or they can review original snippet and return to their code)
  - there is a 'Reset' button in the top left that allows the user to clear all saved step code at once - allowing them to start the workshop from scratch.
  - User can move back and forth thru steps and their code is saved - but they can revert any step as they wish 

An example of this can be found here:
https://timmaffett.github.io/worksave/workshops.html?webserver=https://raw.githubusercontent.com/flutter/codelabs/master/dartpad_codelabs/src/example_dart

@brianegan I would be interested if this addresses your problem statement in a satisfactory way ?  Are there any changes that you (or anyone else) would suggest ?

**Comment by brianegan** [comment]
Heya @timmaffett -- this looks great! Thanks so much for the help.

After testing it, it's working almost exactly as I hoped! 

After working with it, I realized I failed to specify one use case: some ability to Show & then hide the Solution code. Or, show the Solution code, then restore the code the user has written. I could see it working something like this:

  - as a workshop taker
  - when I finish my work
  - and I want to compare to the proper solution
  - I should be able to go back and update my code

That would cover all possible use cases for the user: The ability to see both the original snippet, the correct solution, and ability to go back to their code in either case.

Please let me know if that feels out of scope for this work, I'd be happy to create a separate issue if so. I wouldn't want to block what you have b/c it's great!

**Comment by timmaffett** [comment]
Thanks for taking a look @brianegan !

I have added the ability to show the solution and return to your code.
When the user presses show solution they are no longer presented with a dialog (as losing your code no longer applies).
When the solution is showing they have the icons available to revert to original snippet or revert to their last edit.
When they return to their last edit there is now a lightbulb icon that is available to quickly toggle back to the solution.  This allows the user to toggle back and forth between solution and their code.

Tell me if you hate the secondary lightbulb/show solution icon.   I am torn but it did seem nice to be able to click back and forth without having to move the mouse all the way to the primary show solution button.

[example using your simple workshop](https://timmaffett.github.io/worksave/workshops.html?webserver=https://raw.githubusercontent.com/flutter/codelabs/master/dartpad_codelabs/src/example_dart)

Here is a more link with a more complicated workshop:

https://timmaffett.github.io/worksave/workshops.html?webserver=https://dartpad-workshops-io2021.web.app/getting_started_with_slivers

**Comment by timmaffett** [comment]
Good find - It is because they haven't edited yet and I am not handling that correctly.  I will fix this by tomorrow.

**Comment by timmaffett** [comment]
Ok @brianegan , I have fixed that case and any case where they view the solution before editing (or resetting to the snippet with no changes).
I would love it for you to give that a try when you can and let me know if it does indeed fix the problem for you.

thanks!

**Comment by brianegan** [comment]
Thanks again, @timmaffett :)

When I click on "Show Solution" before typing any code, the button "Go to last edit" pops up. That totally wors, but I was surprised it wasn't the "Revert to Original" button instead.

A small detail, functionally everything is working well at this point! Really appreciate it.
