### ISSUE TITLE
Github OAuth2 and Multi-File Editor

### ISSUE THREAD

**Issue by nodexninja** [dart-lang/dart-pad#2258]
### GitHub OAuth2
DartPad is an amazing IDE for programming in Dart and Flutter, but a major issue with [DartPad](https://dartpad.dev) is the inability to save or import code efficiently. My suggestion would be to add a GitHub integration for DartPad so users can log in and import their repositories into DartPad. It would also be **extremely helpful** if users could commit to their repositories as well. 

### Full Editor
I have noticed that DartPad only has `main.dart` and no other files for the user to import and edit. It would be nice if we could get multiple file editing into DartPad along with the **GitHub** integration. I understand that this creates new issues such as handling other `.yaml` or `.json` files, but DartPad community's expectations end at being able to edit `dart` files.

**Comment by nohe427** [comment]
The GitHub integration works for me, however, I would like to second the suggestion for multi file support. Gists support multiple files, so it would be nice to see additional files within the editor.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, it was decided to not support the multi-file use case to focus on what DartPad does best.

For multi-file support consider using an in-browser IDE like [Project IDX](https://idx.dev/) which has first class support for Dart and Flutter, or others like GitHub Codespaces. 

However, if you are still interested in this, consider opening a new issue with details about your use case for discussion, thanks!
