### ISSUE TITLE
Use flutter.js API

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2261]
Once the [flutter.js](https://docs.flutter.dev/development/platform-integration/web/initialization) API lands in the stable and old channels, we can start using this API for DartPad.

This would allow us to load the engine once

**Comment by mosuem** [comment]
@johnpryan is this still a P1 issue?

**Comment by johnpryan** [comment]
Yes, here's the pull request: https://github.com/dart-lang/dart-pad/pull/2792
