### ISSUE TITLE
Re-bump CodeMirror

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#2264]
The last bump of CodeMirror introduced a break in the system. We'll need to figure out why and get ourselves back up to date.

**Comment by domesticmouse** [comment]
Context: https://github.com/dart-lang/dart-pad/pull/2263

**Comment by parlough** [comment]
This was bumped again in https://github.com/dart-lang/dart-pad/pull/2285, many months ago, and seems to be working fine.
