### ISSUE TITLE
Configuration should allow using the beta channel by default instead of stable.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/dart-pad#2278]
For the [Flutter master API docs site](https://master-api.flutter.dev), it would be nice if we could configure things on a server-wide basis so that dartpad defaults to using the beta channel instead of the stable channel, since that's often much closer to master, and fewer examples would be broken for a shorter period of time when a breaking Dart or Flutter change occurs in master.

I know we can supply a URL parameter, but it would be good if we didn't have to do that in this case, so that we don't need to republish the docs to remove that parameter for the stable site.

cc @RedBrogdon

**Comment by domesticmouse** [comment]
@gspencergoog are you asking for the selected channel to be sticky? We don't have a concept of a logged in user, so setting client side state is about as close as we can get on this front at this point.

**Comment by awh6al** [comment]
what about HTTP cookies?

**Comment by gspencergoog** [comment]
@domesticmouse I guess it's enough to have the URL parameters, and we'll just republish for stable.  I think we have to do that anyhow for the stamp at the bottom of the page. Is there a URL parameter for the branch to use?

**Comment by domesticmouse** [comment]
Try using https://dartpad.dev/?channel=beta as a starting point. We don't have a master channel, however.

**Comment by gspencergoog** [comment]
Oh, I understand that (and why), but beta is at least a lot closer than stable. Thanks, I think that's all we need.
