### ISSUE TITLE
Documentation doesn't activate on first '.'

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#228]
@kasperpeulen 

![image](https://cloud.githubusercontent.com/assets/2978182/6930080/0133c0f4-d7f8-11e4-83f0-c1331daf7192.png)

With an arrow up or down the documentation updates correctly, but it doesn't update until a keyboard action occurs.

**Comment by lukechurch** [comment]
This also occurs when returning form "no suggestions" -> a suggestion list. it continues to show "No documentation found"

**Comment by kasperpeulen** [comment]
I think this happens everytime a new popup comes, as it takes some time for the popup to arrive it is hard to determine when to trigger handleHelp in playground.

We could do `new Timer(const Duration(milliseconds:500), _handleHelp);` or we could try to catch the codemirror event that the completion popup is shown.

**Comment by kasperpeulen** [comment]
Just verified that this is still an issue.
