### ISSUE TITLE
Collapsed code blocks appear to automatically expand

### ISSUE THREAD

**Issue by johnwiese-ms** [dart-lang/dart-pad#2294]
## What happened?

Every so often (seems like when the background syntax checking happens) the code blocks I've collapsed will automatically expand again.  I would expect that when I collapse a code block it stays collapsed unless I un-collapse it, or during debugging I am placed into that code.

## Steps to reproduce problem

1. Create a new Dartpad -> Dart.  
2. Add this method

void someFunction(){
    print('Test1');
    print('Test2');
    print('Test3');
    print('Test4');
}
3.  collapse the method you just added by clicking the collapse arrow on the left of the first line
4. Select all the code in Main and hit delete/backspace
5. add a call to your new method someFunction();

either at step 4 completion or step 5 the syntax checker will kick in and the method will be expanded automatically.

### Browser

Browser: Edge

Version: 102.0.1245.30 (Official build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? None I am aware of

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below: NONE

```

```

### Machine

Operating system: Windows 11

Version: 22H2 (OS Build 22621.1)

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```

```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by timmaffett** [comment]
This is being caused by all of the codemirror markers getting cleared in `setAnnotations()`, within `editor_codemirror,dart`.  It should be fairly straightforward to only remove our info/error annotation markers and leave all of the users alone (preliminary testing has shown me this works).   I will get a PR in ASAP - it will probably require a change to `codemirror.dart` as well to make `TextMarker` less opaque.

**Comment by timmaffett** [comment]
This has been fixed in PR #2301 and should be available soon.  Thanks again @johnwiese-ms
