### ISSUE TITLE
Padracing sample is now non-functional and contains errors

### ISSUE THREAD

**Issue by timmaffett** [dart-lang/dart-pad#2300]
The new Padracing sample now contains errors caused by missing code.  The backing gist seems to have been changed is missing a base class `ContactCallback` as well as some other methods.

https://dartpad.dev/index.html?id=ecabed4a17a3aad8bee7c6327e472fc8

Or just go to dartpad.dev and select the `Padracing` sample (which is the link above)

**Comment by domesticmouse** [comment]
Hey @spydon, I'm guessing Flame 1.2.0 broke your game. Any chance of guidance on how to fix it?

**Comment by spydon** [comment]
Oh, right. Here is the updated version:
https://gist.github.com/spydon/3e52ca7b51ba15f989ad880b8b3314a2

**Comment by domesticmouse** [comment]
Ruh-roh, that doesn't compile on DartPad for some reason. See https://dartpad.dev/?id=3e52ca7b51ba15f989ad880b8b3314a2's log:

```console
Error compiling to JavaScript:
TimeoutException after 0:01:00.000000: Future not completed
```

**Comment by domesticmouse** [comment]
I can't replicate locally. Ugh.

**Comment by spydon** [comment]
Are you sure you don't have an old cached version? Because that is the same gist id as I've used previously.

**Comment by parlough** [comment]
Yeah it seems to be working for me: https://dartpad.dev/?id=3e52ca7b51ba15f989ad880b8b3314a2

**Comment by timmaffett** [comment]
It is working for me also now.

**Comment by spydon** [comment]
This should be possible to close
