### ISSUE TITLE
maybe go_router not up-to-date

### ISSUE THREAD

**Issue by iapicca** [dart-lang/dart-pad#2306]
## What happened?

<img width="430" alt="image" src="https://user-images.githubusercontent.com/45637986/174807113-3a2b1e26-bbe2-4596-b530-47f9750c0353.png">

## Steps to reproduce problem

run [this](https://dartpad.dartlang.org/?id=3ca67a732b00f383161d96dbe878891b)

### Browser

Browser: Chrome

Version: Version 102.0.5005.115 (Official Build) (arm64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

NO

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Error compiling to JavaScript:
/tmp/dartpadHZEOOP/lib/main.dart:58:40: Error: The getter 'routeInformationProvider' isn't defined for the class 'GoRouter'.
 - 'GoRouter' is from 'package:go_router/src/go_router.dart' ('local_pub_cache/hosted/pub.dartlang.org/go_router-3.1.1/lib/src/go_router.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'routeInformationProvider'.
      routeInformationProvider: router.routeInformationProvider,
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by domesticmouse** [comment]
Try again in about five minutes, I just pushed https://github.com/dart-lang/dart-services/pull/888 to prod.

**Comment by iapicca** [comment]
@domesticmouse that was really quick 
the code sample works :) thanks
