### ISSUE TITLE
Console errors on each keystroke in the editor

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart-pad#2310]
## What happened?

I am getting the following errors in the console whenever I type in DartPad:

```
playground.dart.js:455 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at fi.eS (playground.dart.js:15470:3)
    at Object.Go (playground.dart.js:3930:21)
    at mz.mF (playground.dart.js:12589:16)
    at tear_off.<anonymous> (playground.dart.js:577:65)
    at mA.dC (playground.dart.js:8162:21)
    at fO.c_ (playground.dart.js:7955:5)
    at fO.bv (playground.dart.js:7928:11)
    at fO.bv (playground.dart.js:8110:6)
    at db.iu (playground.dart.js:8144:10)
    at fO.mz (playground.dart.js:8120:14)
```

## Steps to reproduce problem

Open up dartpad and the javascript console for the page, then type anything in the editor.

**Comment by timmaffett** [comment]
@jakemac53  Could I ask you to please provide more detail? I am unable to reproduce by doing:

1) going to dartpad.dev
2) open javascript console for page
3) click New Pad, (choose html or non html)
4) typing and modifying the program, running, typing and modifying more, etc.  I am not seeing any messages to the console.
(including adding `window.console.log("Here is a message");` to verify that I can write the console)

**Comment by jakemac53** [comment]
Hmm, that is exactly what I am doing.

https://user-images.githubusercontent.com/984921/176756016-0882c94c-027d-481e-a0a7-4b15c9d6e376.mp4

However I did notice that this was not happening for me in the local dev environment... only on prod. Possibly it was already fixed by something else?

**Comment by timmaffett** [comment]
Weird.  One other difference I see when I duplicate the steps in your video is that I don't see the `Devtools failed to load source map...` error, but that is may be triggered by the exception itself.

I will keep my eye out for this and try to reproduce on other machines as well.

**Comment by jakemac53** [comment]
> Weird. One other difference I see when I duplicate the steps in your video is that I don't see the `Devtools failed to load source map...` error, but that is may be triggered by the exception itself.

This is I think related to a chrome extension I have installed.

**Comment by johnpryan** [comment]
I can't reproduce this. Feel free to reopen if you're still seeing this.
