### ISSUE TITLE
Stale analysis errors in the editor not going away

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart-pad#2311]
## What happened?

After fixing errors in the program, the red line in the editor does not disappear, the following should have no red underline since I added the field to fix the error:

![image](https://user-images.githubusercontent.com/984921/176718791-ea8654bc-50b2-44e6-a654-23070a14094e.png)

Note that the list of diagnostics in the bottom right does go away, but the red lines under the code that had an error does not disappear.

## Steps to reproduce problem

Create a class with a constructor that initializes a field that does not yet exist:

```dart
class A {
  A(this.value);
}
```

Then fix the issue by adding a `value` field:

```dart
class A {
  final Object value;
  
  A(this.value);
}
```

The error should disappear, but does not.

### Browser

Browser: Chrome

Version: 102.0.5005.125

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

See https://github.com/dart-lang/dart-pad/issues/2310

### Machine

Operating system: Chrome OS

Version: 102.0.5005.125

**Comment by domesticmouse** [comment]
@johnpryan can you please roll a release?

**Comment by johnpryan** [comment]
Done
