### ISSUE TITLE
Question regarding the dev setup

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart-pad#2314]
Hi! I recently checkout out this repo to work on a quick bug fix, and I was wondering a bit about the dev setup. In particular, the `grind serve` task does not support re-building when you make edits to the code.

It does appear however that just running `dart run build_runner serve` works perfectly fine, so I was wondering if there is a reason that `grind serve` doesn't just use that server, which would give it automatic incremental rebuilds? Or should the contributing.md file possibly mention just running `dart run build_runner serve` for local development?

**Comment by parlough** [comment]
Closing as stale, because the web-based frontend has been removed from the repo, now you can use `flutter run` albeit with some custom headers depending on the development task at hand.
