### ISSUE TITLE
DartPad error

### ISSUE THREAD

**Issue by mbawhitefield** [dart-lang/dart-pad#2328]
Error compiling to JavaScript:
XMLHttpRequest error
![Screenshot (7)](https://user-images.githubusercontent.com/75375423/178623591-63504f92-3fab-4a48-8758-8d3b8dcde921.png)
.

**Comment by domesticmouse** [comment]
From your screenshot it looks like the front end has yet to connect to a backend. There is no Flutter version info in the bottom right hand corner, and the channel selector isn't showing stable.

If you reload and wait does it come good, or is there something in the browser console logs that hint at network errors?

**Comment by ibrahim1520** [comment]
can I help you?

**Comment by domesticmouse** [comment]
Please show the content of the javascript console

**Comment by johnpryan** [comment]
Closing until we can get more info from the JS console.

Related to https://github.com/dart-lang/dart-pad/issues/1365
