### ISSUE TITLE
Use scss (and compass) 

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#233]
One guy at dartisan asked to make it possible to let the user choose different styling for the editor, for example one with a clear background.

I think it may be good to switch to scss and maybe compass if we want to implement such af eature one day. Having scss variables is of course always usefull, but also something like the lighten function of compass would be really handy.

**Comment by devoncarew** [comment]
Cool, let's keep this in mind. Once we're done with some immediate work, we'll probably switch to a material design framework, and I expect we'll pick up scss from them.
