### ISSUE TITLE
Error compiling Javascript

### ISSUE THREAD

**Issue by playerpxx** [dart-lang/dart-pad#2333]
I use chrome, and when I clicked RUN button following error occurs.

![image](https://user-images.githubusercontent.com/100674977/180934334-a50aeffe-9a64-42bc-a40f-42d1b09332d6.png)

**Comment by parlough** [comment]
Hi @playerpxx, since Flutter 1.9, [Flutter Web](https://flutter.dev/multi-platform/web) is included as part of the normal Flutter SDK/package, so you just use the normal `package:flutter` imports.

If you still have issues once adjusting to those imports, let us know :)
