### ISSUE TITLE
in chrome the text in the icons of the completion popup are not vertically centered

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#236]
In chrome the text in the icons of the completion popup are not vertically centered.

In chromium, safari and firefox it seems fine, only in chrome it seems off.

chrome:
![image](https://cloud.githubusercontent.com/assets/1035299/6945756/378d39ec-d89c-11e4-9b5c-60a626945313.png)

safari/chromium:
![image](https://cloud.githubusercontent.com/assets/1035299/6945777/5b59e21c-d89c-11e4-8393-650dcb68d6e7.png)

shall I make a custom style for chrome ?

**Comment by lukechurch** [comment]
@devoncarew This one needs your input. I'm out of my depth.
