### ISSUE TITLE
Support records experimental feature

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2365]
I forget how we enable experiments in dartpad, but we should soon-isssh start supporting the 'records' experiment. The command-line flag should be something like `--enable-experiment=records`.

We should _not_ start _now_; things are too early. I think static support is largely complete, but the web support is not there yet, for when the user clicks "Run."

Additionally, there is likely a big change to the syntax coming. https://github.com/dart-lang/language/issues/2469.

Just putting this on the radar. Maybe we can enable this in a few weeks on one channel or another.

**Comment by domesticmouse** [comment]
I'd guess the `master` channel will be the best place to do it, as that'll have the most up to date version of Dart

**Comment by SuporteSysrs01** [comment]
I would really like to test the records feature in DartPad. Is there a way for me to enable it manually in the master channel or do I have to wait for it to be enabled by default?

**Comment by srawlins** [comment]
No, it is not implemented yet. It will be some months.

**Comment by domesticmouse** [comment]
Records is now supported in stable. Closing.
