### ISSUE TITLE
Make it easier to add packages to dartpad

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/dart-pad#2366]
During the research sessions at Flutter Vikings, package authors and consumers mentioned that embedding examples for their package using dartpad either on their own docs sites or within pub.dev would be useful. However, when they develop a new package it can be difficult to get it added to dartpad. So ideally there would be a way for authors to add their package on their own.

**Comment by domesticmouse** [comment]
Due to security concerns we can't go down this path.
