### ISSUE TITLE
Run button not consistent in Microsoft Edge

### ISSUE THREAD

**Issue by chris-netizen** [dart-lang/dart-pad#2367]
I need to click the run button multiple times before the code runs. Although this doesn't happen all the time, it happens quite often.

**Comment by domesticmouse** [comment]
I've seen this delay on multiple browsers, so it isn't MS Edge specific. I'm curious if pre-loading the Skia WASM bundle would help...

**Comment by dprimon** [comment]
@chris-netizen I also have the same issue. I'm using Brave browser on Debian bullseye on AMD Phenom

**Comment by domesticmouse** [comment]
We probably need to give the user feedback that the request to the server is in flight. It can take multipe seconds to compile a sample and respond, especially if a new compilation server needs to be spawned.
