### ISSUE TITLE
Large hexadecimal values are not properly converted to integers

### ISSUE THREAD

**Issue by killermonk** [dart-lang/dart-pad#2372]
## What happened?

I tried to use the following code to determine the decimal value of the given hexadecimal value:

```dart
void main() {
  print(0xDCBA9876543210);
}
```

Expected output (output generated by CLI):
62129658859368976

Actual output (off by +4):
62129658859368980

## Steps to reproduce problem

Run the above code in dartpad. It gives the wrong output 100% of the time.

### Browser

Browser: Chrome

Version: 106.0.5249.61 (Official Build) (x86_64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Yes, an ad blocker.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

No

### Machine

Operating system: MacOS Monterey

Version: 12.6

### Your code

```
void main() {
  print(0xDCBA9876543210);
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
62129658859368980
```

**Comment by domesticmouse** [comment]
I believe you are hitting a difference in behaviour between DartVM and Dart on the web. Please have a look at https://dart.dev/guides/language/numbers for more detail.

**Comment by killermonk** [comment]
@domesticmouse you are correct. I hadn't realized that web integers lost precision past 53 bits. Thanks for the docs link!
