### ISSUE TITLE
ErrorWidget class example doesn't work in dartpad

### ISSUE THREAD

**Issue by gh-pap** [dart-lang/dart-pad#2381]
## What happened?
Running the dartpad embedded at the top of this page https://api.flutter.dev/flutter/widgets/ErrorWidget-class.html failes with 'Script error.'. This same script works fine if I run it on my local machine (web platform).

## Steps to reproduce problem
Run the dartpad embedded at the top of this page https://api.flutter.dev/flutter/widgets/ErrorWidget-class.html and click the button "Error Prone".

## Additional info
See https://github.com/flutter/flutter/issues/112688

### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by domesticmouse** [comment]
I suspect our error mapping regexes are trapping the `ErrorWidget` somehow
