### ISSUE TITLE
import "" doesn't work on dartpad

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/dart-pad#2384]
`import "" as foo` allows you to refer to the current library through an identifier. Its not ... exactly a useful feature. On DartPad, this currently fails to compile with the text "unsupported import"

Example:

```dart
import "" as foo;

int bar = 2;

void main() {
  print(foo.bar); // prints 2
}
```

From local testing, dart compile js (dart2js) and flutter run -d chrome (dartdevc) both seem to handle this code fine. Unclear if this is due to a particular configuration on DartPad .

**Comment by jonahwilliams** [comment]
It occurs to me that Dartpad likely has some form of import allowlist, and this would need to be added to it.

**Comment by domesticmouse** [comment]
> It occurs to me that Dartpad likely has some form of import allowlist, and this would need to be added to it.

I think https://github.com/dart-lang/dart-services/blob/master/lib/src/project.dart#L192 is where the fix would be required.
