### ISSUE TITLE
Improve UX around "Show solution" button in workshops

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2389]
See [this comment](https://github.com/dart-lang/dart-pad/issues/2251#issuecomment-1274373713) for context.

cc: @brianegan

**Comment by Spyy004** [comment]
I would like to work on this enhancement. Can someone please assign me this?

**Comment by Spyy004** [comment]
Hey, someone please assign me this task. I am happy to contribute to the project by working on this

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires any feature similar to workshops, please discuss that in a new issue. Thanks!
