### ISSUE TITLE
Make it a real REPL (interactive shell) instead of full-restart every time, with https://github.com/fzyzcjy/dart_interactive?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/dart-pad#2392]
Hi, I have recently made https://github.com/fzyzcjy/dart_interactive, a REPL for Dart. So, maybe DartPad can utilize it to create a real REPL?

**Comment by domesticmouse** [comment]
Anything short of adopting zap.run style client side compilation would have too high a server side compute cost. We can't afford to tie up servers waiting for developers to type things in.

**Comment by fzyzcjy** [comment]
@domesticmouse The REPL seems to run in *browser*, instead of in *server* IMHO.

Btw I googled "zap.run style" without finding anything...

**Comment by fzyzcjy** [comment]
seems Dart supports compile to web and run locally without a need for server.

**Comment by domesticmouse** [comment]
Have a look at https://zapp.run/

It runs the analyzer and compiler inside the browser. Which is very impressive.
