### ISSUE TITLE
Error compiling to JavaScript

### ISSUE THREAD

**Issue by wotrans** [dart-lang/dart-pad#2394]
When i create a new flutter code and test it dartpad.dev it doesnt work. Dartpad gives the "Error compiling to JavaScript" . How can i fix it? 
I used chrome and close all the adblockers.

**Comment by domesticmouse** [comment]
Please supply the Dart code that is failing to compile

**Comment by wotrans** [comment]
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: "İlkel Blog Uygulaması", home: AnaEkran());
  }
}

class AnaEkran extends StatelessWidget {
  const AnaEkran({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Blog Uygulaması"),
      ),
      body: Container(
        margin: EdgeInsets.all(50),
        child: Center(
          child: Text("merhaba ")
          ),
      ),
    );
  }
}

**Comment by wotrans** [comment]
I think my internet connection was the problem i fix it now . Thank you so much.
