### ISSUE TITLE
How change default in Dartpad to Dart from Java.

### ISSUE THREAD

**Issue by wgerstmann** [dart-lang/dart-pad#2398]
How change default in Dartpad to Dart from Java.

**Comment by domesticmouse** [comment]
What do you mean by "Dart from Java"?

**Comment by wgerstmann** [comment]
I am doing the Flutter tutorial and the execution defaults to Javascript.  I have run https://dartpad.dartlang.org/ in Chrome and Firefox with the same result.  Dart has a Type called list and Javascript does not have list. 
Others have posted the same issue with resolution.

**Comment by domesticmouse** [comment]
Can you link the other issues and resolution?
