### ISSUE TITLE
Can I add instructions for local development, startup and compilation

### ISSUE THREAD

**Issue by mstestlp** [dart-lang/dart-pad#2399]
Can I add instructions for local development, startup and compilation

**Comment by domesticmouse** [comment]
The README file on this repo and `dart-lang/dart-services` should contain everything required for local development.

What are we missing?

**Comment by mstestlp** [comment]
> 

Thanks, I understand it as a flutter project

**Comment by mstestlp** [comment]
> The README file on this repo and `dart-lang/dart-services` should contain everything required for local development.
> 
> What are we missing?

![image](https://user-images.githubusercontent.com/10651998/198929354-3ddbf197-64d4-44bf-8c89-d40255a894e5.png)
How to generate a build? Thank you

**Comment by domesticmouse** [comment]
Windows is not a supported platform. I had a go at adding support a while back, I don't remember what issue I hit tho.
