### ISSUE TITLE
Add an 'open in new tab' button to the documentation panel

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#241]
An icon like the rectangle with an arrow emerging from it, at the top right hand side of the doc panel that enabled you to open the current documentation in a new tab, potentially via a link to api.dartlang.org

@kasperpeulen

**Comment by lukechurch** [comment]
This could potentially also be done with a 'open in API docs' link at the bottom of the docs page.

**Comment by kasperpeulen** [comment]
Not sure if I always get enough information of the backend to construct the link.
For example if I have `int i; i.isEven` then the documenation will be:
```
{name: isEven, description: get isEven → bool, kind: getter, parameters: [], libraryName: dart.core, dartdoc: Returns true if and only if this integer is even., staticType: bool, propagatedType: bool}
```

To generate the link I think I also need to know the classname of the property:

`https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart:core.int#id_isEven`

**Comment by lukechurch** [comment]
Please feel free to file bugs (or code) to the dart-services project to improve it

**Comment by kasperpeulen** [comment]
Would you appreciate a PR there ?

2015-04-01 23:32 GMT+02:00 Luke Church <notifications@github.com>:

> Please feel free to file bugs (or code) to the dart-services project to
> improve it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-pad/issues/241#issuecomment-88637060>.
>



-- 
Kasper

**Comment by lukechurch** [comment]
Absolutely!

**Comment by kasperpeulen** [comment]
![image](https://cloud.githubusercontent.com/assets/1035299/6971077/3c1e8946-d97a-11e4-9ca4-871a00dba9eb.png)

vs

![image](https://cloud.githubusercontent.com/assets/1035299/6971092/60e44126-d97a-11e4-9c07-51532f50654f.png)

I prefer this last one. In some sense it will link to the library, but at a specific point in the library, in this example it would link to:
https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core#id_print

**Comment by lukechurch** [comment]
@kasperpeulen In general less redundant chrome is better. So yeah, lets go with the last one.

If it turns out not to be discoverable we may need a glyph next to it
