### ISSUE TITLE
english_words package doesn't work in DartPad

### ISSUE THREAD

**Issue by KyleFin** [dart-lang/dart-pad#2410]
## What happened?

english_words is listed in `Directly importable packages`, but when I import it, I get `Error: Couldn't resolve the package 'english_words' in 'package:english_words/english_words.dart'.`

I confirmed I was able to import and use a different package as expected (bloc).

## Steps to reproduce problem

Example code from https://pub.dev/packages/english_words:

(Printing the top 50 most used nouns in the English language)

```
import 'package:english_words/english_words.dart';

main() {
  nouns.take(50).forEach(print);
}
```

### Browser

Browser:

Chrome, MacOS

Version:

Version 106.0.5249.119 (Official Build) (arm64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Error compiling to JavaScript:
Info: Compiling with sound null safety
Error: Couldn't resolve the package 'english_words' in 'package:english_words/english_words.dart'.
lib/main.dart:1:8:
Error: Not found: 'package:english_words/english_words.dart'
import 'package:english_words/english_words.dart';
       ^
lib/main.dart:4:3:
Error: Undefined name 'nouns'.
  nouns.take(50).forEach(print);
  ^^^^^
Error: Compilation failed.
```

**Comment by domesticmouse** [comment]
That'd be due to the fact that it is currently listed as a Flutter package, not a Dart package. Fix in flight.

**Comment by KyleFin** [comment]
Confirmed it's working for me now. Thanks for the quick fix!
