### ISSUE TITLE
Unable to use the GitHub login feature: `Route not found`

### ISSUE THREAD

**Issue by nilsreichardt** [dart-lang/dart-pad#2416]
## What happened?

I tried to use the GitHub login feature:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/24459435/203115238-f958ad4d-eb19-4097-8834-f678ae9c99c6.png">

However, I landed on this site:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/24459435/203115314-bd10b93c-4de0-4d38-bdee-67fb3550c5c3.png">

## Steps to reproduce problem

1. Go to dartpad.dev
2. Click on the GitHub icon
3. Click "Login"

https://user-images.githubusercontent.com/24459435/203115690-c4597e83-1d9a-4db7-9918-bf68336d242f.mov

### Browser

Browser: Chrome
Version: Version 107.0.5304.110 (Official Build) (arm64)

### Machine

Operating system: MacBook M1

Version: macOS 12

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: const [
              // This does not work :(
              MouseRegion(
                cursor: SystemMouseCursors.click,
                child: Chip(
                  label: Text("Flutter"),
                ),
              ),
              SizedBox(height: 12),
              // This works :)
              MouseRegion(
                cursor: SystemMouseCursors.click,
                child: Text("Flutter"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
GET https://master.api.dartpad.dev/github_oauth_initiate/DGWvxB2SOAbUFyyojSPzFNnOGlqFfSnGy1UpSoKS 404
```

<img width="594" alt="image" src="https://user-images.githubusercontent.com/24459435/203116234-a70ce7ea-79fb-4165-8281-437cdced6d7b.png">

**Comment by domesticmouse** [comment]
@timmaffett Any ideas on what I've forgotten to configure for the Master channel?

**Comment by timmaffett** [comment]
Hi @domesticmouse , sorry for the delay in getting back to you, my father has been in the hospital for coviid and I have been away. Thankfully he is doing better.

 The route for `github_oauth_initiate` is added in `github_oauth_handler.dart` 's  `addRoutes()` method.  This is always called, but routes will not be added if `initializationEndedInErrorState` is set.   This will be set if either of the private environment variables `PK_GITHUB_OAUTH_CLIENT_ID` or `PK_GITHUB_OAUTH_CLIENT_SECRET` were *not* set.

I would check that first - there would also be a `GitHub OAuth Handler DISABLED - Ensure all required environmental variables are set and re-run.` message in the logs if this was detected.   There should be messages about the values of all the environmental variables values there as well, and errors if any specific ones were missing.

I will look through the code more thoroughly and see if I can find anything else that might potentially cause this.

**Comment by nilsreichardt** [comment]
I wish your father all the best, @timmaffett! <3

**Comment by timmaffett** [comment]
Thank you for your kind words @nilsreichardt 

@domesticmouse I looked through the code closer and it really looks like one/or both of those environmental variables must be missing.  (They are secrets in your google run instance so it could also be something like missing `Secret Manager Secret Accessor` role also)

There should also be specific errors in the logs about the missing `PK_GITHUB_OAUTH_xxx` variables.

**Comment by domesticmouse** [comment]
I believe this issue is now fixed. =)

**Comment by nilsreichardt** [comment]
Yes, I can confirm this. Thanks for the quick fix ❤️
