### ISSUE TITLE
Add `flutter_adaptive_scaffold` package

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2425]
The [Adaptive Scaffold](https://github.com/flutter/packages/tree/main/packages/flutter_adaptive_scaffold) (flutter_adaptive_scaffold) package is a collection adaptive widgets from the Material team.

**Comment by johnpryan** [comment]
Closed in #995

**Comment by domesticmouse** [comment]
Actually, this isn't shipped to production, so I'm re-opening this issue. This package has been shipped to our hidden testing instance https://dartpad.dev/?channel=dev

Please exercise your suggested package on this instance and confirm here that it works as intended. If you do confirm this as working I'll ship it to `stable`, `beta`, `master`, and `old` channels on dartpad.dev. If you don't confirm, I won't ship it.
