### ISSUE TITLE
using firebase in dartpad is not working

### ISSUE THREAD

**Issue by hanmo2000110** [dart-lang/dart-pad#2426]
I want to use firebase in dartpad
but in initialize step the error occured

```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: "my apikey",
      authDomain: "my project-id.firebaseapp.com",
      projectId: "my project-id",
      storageBucket: "my project-id.appspot.com",
      messagingSenderId: "01012345678",
      appId: "my project-id",
    ),
  );
}
```

and the error was like that
<img width="477" alt="image" src="https://user-images.githubusercontent.com/74346222/206652871-06e4603f-0c20-49d5-839b-fd3a3bbae49c.png">

what is the problem?

**Comment by domesticmouse** [comment]
DartPad runs the compiler JS inside a sandbox, per the error message. There are security considerations regarding executing user submitted code

**Comment by hanmo2000110** [comment]
How we can use firebase in Dartpad 
Now we can't use it

**Comment by swpark15** [comment]
hi, i'm having the same error in dartpad.dev
Are there no other ways to use Firebase.initializeApp or any other firebase services in dartpad?
How can we test firebase packages in dartpad.dev?

**Comment by swpark15** [comment]
Hi~ I'm curious about how the updates are going on this issue~!~!
and I recently found the same error appearing when running the dartpad sample "Firebase Nanochat" as well~

I'm currently working on a project that uses dartpad as an educational tool for learning flutter
and with this error I'm kinda stuck in the middle of developing educational contents~

I appreciate your efforts and I would really like to see this error get fixed soon~!

**Comment by domesticmouse** [comment]
Hey @Puf, any idea why Nanochat used to work, but doesn't now? It's not like we changed the rules on how the sandbox works. I'm guessing FirebaseJS now has additional requirements?

**Comment by swpark15** [comment]
Hi~ thanks for the reply ~!
I've checked the nanochat in dartpad.dev and it's working fine now ~!
and the above issue no longer shows as well when using firebase.initializeApp
wonder what the problems was? I also used regular dartpad.dev and didn't work before
But thanks ~!! and I guess the problem is solved now then?

**Comment by domesticmouse** [comment]
We have made no significant changes on the server side since the bug report, so I'm unsure what has changed.

**Comment by domesticmouse** [comment]
Closing, as this isn't currently an issue. Please comment if the issue reappears.

**Comment by hongsw** [comment]
https://dartpad.dev/?id=d57c6c898dabb8c6fb41018588b8cf73 and I get an error. 
It worked fine in March 2023, but when I went in today and tried to show a demo, I got an error. Thanks.

```
Error compiling to JavaScript:
local_pub_cache/hosted/pub.dev/cloud_firestore-4.8.5/lib/src/firestore.dart:50:46: Error: Required named parameter 'databaseURL' must be provided.
        FirebaseFirestorePlatform.instanceFor(app: app);
                                             ^
local_pub_cache/hosted/pub.dev/cloud_firestore_platform_interface-5.16.0/lib/src/platform_interface/platform_interface_firestore.dart:40:11: Context: Found this candidate, but the arguments don't match.
  factory FirebaseFirestorePlatform.instanceFor({
          ^^^^^^^^^^^

```
