### ISSUE TITLE
Group samples in sample dropdown

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2427]
Some samples in the dropdown are focused on teaching flutter (Counter) , and others are demos that showcase Flutter / Dart features (Padracing).

We could group these into two dropdowns, one for tutorials and one for demos. We could also look into cascading menus.

**Comment by parlough** [comment]
I'm going to close this as a duplicate of https://github.com/dart-lang/dart-pad/issues/2322 which also discusses the same problem and potential solutions. Thanks!
