### ISSUE TITLE
New master channel is confusing

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-pad#2428]
The new master channel in DartPad was created to enable experimentation with Dart experimental features (currently behind [experiment flags](). This may cause confusion as code that works in master channel DartPad (e.g. `(int a, int b) getAB() => (42, 0);`) won't work with a local master channel build unless experiment flags are passed.

I suggest we:

* Update the name of the channel to something like: 
    ```
    Master channel + Dart 3 preview
    ```
* Update the build description in the subtext to something like:
    ```
    Use Flutter version 3.6.0-213.pre and Dart version 3.0.0-dev.21
    + Dart experiments: --enable-experiment=records,patterns
    ```

**Comment by johnpryan** [comment]
@domesticmouse can we add an "extra" field to the version response so that this doesn't need to be hardcoded in the frontend?

**Comment by mit-mit** [comment]
Thanks @johnpryan !
