### ISSUE TITLE
No short-cut key for console

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#243]
Maybe F2? Or even maybe F1 to cycle through the contents of that panel area?

**Comment by kasperpeulen** [comment]
If we do F2 I feel like we should switch the order of the documentation and console tab.

**Comment by lukechurch** [comment]
Yeah, I agree, that's why I didn't really like F2. It's very strange to have them backwards.

Lets try having F1 cycle, and see how that feels?

**Comment by kasperpeulen** [comment]
Maybe we could give all tabs a shotcut, from left to right.
DART ctrl-1
HTML ctrl-2
CSS ctrl-3
CONSOLE ctrl-4
DOC ctrl-5 / F1

**Comment by lukechurch** [comment]
How about

DART ctrl-1
HTML ctrl-2
CSS ctrl-3

CONSOLE ctrl-9
DOC ctrl-0 / F1

Leaving us a bit of room to grow in the middle?

**Comment by kasperpeulen** [comment]
ah yeah, smart, will do that

2015-04-01 23:45 GMT+02:00 Luke Church <notifications@github.com>:

> How about
>
> DART ctrl-1
> HTML ctrl-2
> CSS ctrl-3
>
> CONSOLE ctrl-9
> DOC ctrl-0 / F1
>
> Leaving us a bit of room to grow in the middle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-pad/issues/243#issuecomment-88641175>.
>



-- 
Kasper

**Comment by devoncarew** [comment]
I think we're good with our current keyboard shortcuts.
