### ISSUE TITLE
<esc> is not working on vim mode

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [dart-lang/dart-pad#2430]
I issued dartpad's escape key problem before. it seems fixed by using ctrl + c. but i'm curious why escape key still not roll back to esc?

Browser:
firefox
Version:
108.0.1

**Comment by parlough** [comment]
Thanks for opening an issue. It looks like the deployed DartPad doesn't include the latest fixes yet.

\cc @johnpryan

**Comment by johnpryan** [comment]
This should be deployed now. Please leave a comment if you're still running into issues.

**Comment by JUNGHUNKIM-7** [comment]
Thanks for quick applying, works smoothly&very well. i'm happy to back to dart pad!
