### ISSUE TITLE
Master channel returns 500

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2433]
Calling the `/analyze ` endpoint at `master.api.dartpad.dev` returns a 500:

<img width="752" alt="Screenshot 2022-12-19 at 1 36 39 PM" src="https://user-images.githubusercontent.com/1145719/208528855-5c85d586-67ef-44ec-b7fc-be4528cd0376.png">

cc: @domesticmouse

**Comment by domesticmouse** [comment]
Here's the network trace for `master` using the Counter sample.

<img width="1362" alt="Screenshot 2022-12-20 at 7 57 01 am" src="https://user-images.githubusercontent.com/30503/208532624-7ee3b742-d48f-416a-8978-565a2fae40f2.png">

What code are you feeding to the analyzer?

**Comment by johnpryan** [comment]
It looks like I found a way to crash the analyzer:
```dart
```
I'll investigate and file an issue there.

**Comment by johnpryan** [comment]
This seems like it's fixed already - I can't reproduce using `3.0.0-35.0.dev (dev)`.

**Comment by domesticmouse** [comment]
Probably just a borked server. The master channel is only running a server or two, so if one goes bad it tends to paint everything red until Cloud Run replaces it with another server. The stable channel is usually running at least 50 servers so 1 bad server isn't nearly as obvious.
