### ISSUE TITLE
DartPad fails: Error compiling to JavaScript:Method not found: 'FallThroughError'. #117546

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/dart-pad#2434]
This Dartpad example which targets the master channel worked about a week ago: https://dartpad.dev/?id=34adb8b46d34c933751bf8b21d06686f&channel=master. Now it fails with:

```
Error compiling to JavaScript:
local_pub_cache/hosted/pub.dev/cloud_firestore_web-3.1.1/lib/src/utils/web_utils.dart:71:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
```

**Comment by domesticmouse** [comment]
I'm seeing that on both my Dart Services integration as well as Flutter Samples. Reading the log entry, it looks like the `cloud_firestore_web` package is broken on the latest Dart version. 

/cc @mit-mit @puf

**Comment by puf** [comment]
From what I see, use of that FallThroughError class was removed in version 5.9.2 on December 19: https://github.com/firebase/flutterfire/blob/814405800831a1ad900fc20e110eb0da81e1e962/packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md#592

Can you test with that version?

**Comment by domesticmouse** [comment]
We are already running DartPad master on that version: https://github.com/dart-lang/dart-services/blob/master/tool/pub_dependencies_master.json#L12

I'm rolling a PR that will bump it to version 5.10.0

**Comment by puf** [comment]
OK. If that doesn't fix it, can you file an issue on the FlutterFire repo
for it? Since they were just making changes to it, I suspect they're
dealing with something around that exception too.

**Comment by domesticmouse** [comment]
Actually, I'm failing to reproduce the error on DartPad. @HansMuller can you confirm? I click on your DartPad link, press play, and open the console tab. I see the sample running, and the console remains empty.

**Comment by HansMuller** [comment]
Yes, I can no longer reproduce the error. And the holiday break begins in minutes!

**Comment by domesticmouse** [comment]
Timing +)

PR mentioned above: https://github.com/dart-lang/dart-services/pull/988
