### ISSUE TITLE
Official Flutter tutorial's dart pad is not working

### ISSUE THREAD

**Issue by Lucas-Meowtel** [dart-lang/dart-pad#2435]
## What happened?

I tried to see [the dart pad attached](https://dartpad.dev/workshops.html?webserver=https://fdr-shrinkwrap-slivers.web.app) in [this AWESOME explanation from the Flutter Team](https://www.youtube.com/watch?v=LUqDNnv_dh0) but it's not working.

The tutorial is magnificent, it would be great to be able to see the speed performance with the dart pad.

## Steps to reproduce problem

1. Open [the dart pad](https://dartpad.dev/workshops.html?webserver=https://fdr-shrinkwrap-slivers.web.app)
2. Try to click either on "Run" or "Show solution"
3. Nothing will happen

### Browser

Browser: Google Chrome

Version: 108.0.5359.124 (Official Build) (x86_64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

![image](https://user-images.githubusercontent.com/86300889/209557116-dbea8fbf-cbe9-4ea7-b8d6-3b0efee17f1d.png)

### Machine

Operating system: Mac OS

Version: 12.6

**Comment by MrDodojo** [comment]
The same behaviour happens with [this dartpad](http://flutter.dev/go/sliver-workshop) from [Building scrolling experiences in Flutter | Workshop](https://www.youtube.com/watch?v=YY-_yrZdjGc) too.

**Comment by dhikshith12** [comment]
same issume for me

**Comment by sfshaza2** [comment]
Yup, me too. Please fix!

**Comment by sfshaza2** [comment]
It works now! Thanks, @domesticmouse!
