### ISSUE TITLE
i18n and l10n support

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2443]
This is a tracking issue to see if we can support running code that implements [internationalization](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) and localization in DartPad. The [`intl`](https://pub.dev/documentation/intl/latest/) and [`flutter_localizations`](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations) packages use code generation, so dart-services would probably need to support building and compiling the ARB files.

**Comment by parlough** [comment]
I'm going to those issue as not planned for now, considering DartPad's reduced scope and the planned changes to Dart and Flutter's internationalization packages. We can always revisit in the future once that work is closer to being finalized.
