### ISSUE TITLE
completed

### ISSUE THREAD

**Issue by Wjxfi** [dart-lang/dart-pad#2445]
‘

**Comment by domesticmouse** [comment]
What errors are showing in the console! What breakages are you experiencing?

**Comment by domesticmouse** [comment]
Try the following Dart code instead:

```dart
void main() {
  String a = "Hello";
  print(a);
}
```

**Comment by parlough** [comment]
Does your browser or an extension you have block custom fonts?

DartPad uses Material Icons as a font from fonts.google.com, and the weird text you see is those failing to load.
