### ISSUE TITLE
Flutter unable to trim trailing zero when Dartpad is eable to trim zero. Why?

### ISSUE THREAD

**Issue by Yashvan-Gurutechnolabs** [dart-lang/dart-pad#2448]
### On Dartpad  Based on Flutter 3.3.10 Dart SDK 2.18.6
why flutter unable to trim trailing zero when Dartpad is eable to trim zero?

```
void main() {
  double x1 = 1200.0;
  double x2 = 12.50;
  String s1 = x1.toString().trim();
  String s2 = x2.toString().trim();

  print('s1 is $s1 and s2 is $s2');
}
```
output on Dartpad 2.18.6 is

> s1 is 1200 and s2 is 12.5

output on Flutter 3.3.10 is

> s1 is 1200.0 and s2 is 12.5

**Comment by domesticmouse** [comment]
The short answer is DartPad executes Dart by converting it to JavaScript, which means we get the JavaScript numeric tower. See https://dart.dev/guides/language/numbers for more detail.
