### ISSUE TITLE
Please add Parker Lougheed to maintainers.

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#2464]
Please @parlough to the mainters list for `dart-lang/dart-pad` and `dart-lang/dart-services`.

**Comment by devoncarew** [comment]
@parlough - you should be able to manage issues and review and merge PRs in both this repo and https://github.com/dart-lang/dart-services. Cheers!

**Comment by parlough** [comment]
Thanks @devoncarew!

**Comment by domesticmouse** [comment]
Thanks @devoncarew!
