### ISSUE TITLE
WebKit 

### ISSUE THREAD

**Issue by Stephon4** [dart-lang/dart-pad#2465]
{

### python 

Browser: chrome 

Version:canary

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by parlough** [comment]
Hi @Stephon4, thanks for opening an issue.

Could you provide some more context on the issue you're facing?

In my testing, it seems DartPad is working on both the latest versions of Chrome Canary and WebKit based browsers.
