### ISSUE TITLE
Error formatting needs some work

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#247]
Error compiling to JavaScript:
DetailedApiRequestError(status: 400, message: Compilation of 0c234b396d2dae804ff7557f97573fead01e37f6 failed with errors: [error, line 12] Expected an expression, but got '}'.)

There are lots of things wrong here, @kasperpeulen do you fancy working some magic?

Things to do:

-> The 'DetailedApiRequestError' is internal technical data from how we did the API request. It shouldn't be exposed to the user.

-> The status number should only be exposed if it is a 5xx series, which indicates that something went wrong with the server, and request the user to file an issue with the contents of their source.

-> The '0c234b396d2dae804ff7557f97573fead01e37f6' is a random name generated by the compilation process and shouldn't be shown.

The only bit that needs to be explained to the user is [error, line 12] Expected an expression, but got '}'.

Reformat this so the bit after the ], but before the . is in white to make it stand out a bit more.

I think that will be a decent set of improvements to start with. Thanks!

**Comment by kasperpeulen** [comment]
@lukechurch It feels a bit to me that those javascript erros are allmost never useful. Most of the time the errors from the analyzer seems to be better, and if the analyser doesn't catch an error, the  it doesn't seem to me that the javascript error makes it any better.

For example, today I tried this code at dartpad:
```
import 'dart:html';

main() async {
  var url = 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/autofocus';
  var response = await HttpRequest.getString(url);
}
```

The error I got was:
```
Uncaught Uncaught Error: Instance of 'Event'
```

The dartium error would be:
```
GET https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/autofocus 404 (NOT FOUND)
Exception: Uncaught Error: Instance of '_XMLHttpRequestProgressEvent'
```

Sometimes I wonder if it would be somehow possible to show dartium errors instead of javascript errors. I think we give the people wrong impression what dart debugging feels like if we let people debug javascript errors.

**Comment by sethladd** [comment]
I totally agree that the errors from the compiled JS code are usually not helpful, and will probably scare off new Dart developers.

We could host Dartium in the cloud, of course :)

See also https://github.com/dart-lang/dart-pad/issues/186

**Comment by kasperpeulen** [comment]
> We could host Dartium in the cloud, of course :)

I have no idea how that would work, but if that is somehow possible, then I think we should go for that. So maybe something like, if there are javacscript errors, then load the file in dartium instead, and show the console errors that dartium produces.

Something else I was thinking about, maybe consider a version of dartpad that can run in dartium and doesn't need to compile to JS to show the result. I think this would be a nice option for larger files that otherwise take an extremely long time to load in dartpad.

**Comment by sethladd** [comment]
I think the sustainable approach is to work on better errors from the compiled JS code, so that our system works great no matter what browser you are using.

**Comment by lukechurch** [comment]
I agree with the long term solution of having better errors from our compiled JS. Hosting Dartium would be a lot of work - completely disproportionate for the benefit, and as @sethladd suggests doesn't solve the problem for users of Firefox.

@kasperpeulen If something takes a long time to load in Dart Pad, that's a bug. Please file it.

What I'd like to do here is to do a small amount of reformatting work to help the user separate whether it is a problem with their code (err 4xx) or a problem with the server (err 5xx).

**Comment by kasperpeulen** [comment]
> I agree with the long term solution of having better errors from our compiled JS. Hosting Dartium would be a lot of work - completely disproportionate for the benefit, and as @sethladd suggests doesn't solve the problem for users of Firefox.

Huh? If you host dartium on the server side, and ask for the console log of dartium on the server side, it doesn't matter which browser you use on the client side, right ?

But if it such a huge work, we probably shouldn't do it, but I do think that having quality errors is a huge benefit. If there wouldn't exist something like dartium, I don't think I would be attracted to dart. If you are going to debug javascript, it feels like you are better off learning (and writing) javascript in the first place. 

Now when I use dartpad, and I get unreadable javascript errors, I go back to webstorm and load the file in dartium. I think this is a step that I shouldn't have to do.

> What I'd like to do here is to do a small amount of reformatting work to help the user separate whether it is a problem with their code (err 4xx) or a problem with the server (err 5xx).

In the example I posted:

```
import 'dart:html';

main() async {
  var url = 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/autofocus';
  var response = await HttpRequest.getString(url);
}
```

The error I get is, not `err4xx`, or `err5xx`, but just:
`Uncaught Uncaught Error: Instance of 'Event'`
nothing more.

**Comment by devoncarew** [comment]
Right now uncaught exceptions bubble out to an JS exception handler in our iframe:
```
window.onerror = function(message, url, lineNumber) {
  parent.postMessage(
    {'sender': 'frame', 'type': 'stderr', 'message': message.toString()}, '*');
};
```
It's _possible_ - I'm not sure - that the error text could get better if we run the user's app in a zone, install an exception handler for that zone, and pipe those errors back to dartpad proper. It would require post-processing the user's dart source before we compile it, which could be error-prone.

**Comment by devoncarew** [comment]
Errors are better now -
