### ISSUE TITLE
Support for more experiments.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/dart-pad#2479]
As a user of Dart, I'd like to be able to quickly try out dart language experiments on DartPad (i.e. run, analyze and compile code with certain experimental flags being enabled).

Currently, only records and patterns are supported on a separate channel.

I think that It would be really great if DartPad had support for choosing which experiments are enabled and which are not.

**Comment by domesticmouse** [comment]
DartPad's backend compilation service is specifically constructed to enable re-use of servers between users. Enabling and disabling experiments on a per call basis would eliminate the potential for this required optimisation.

**Comment by modulovalue** [comment]
> DartPad's backend compilation service is specifically constructed to enable re-use of servers between users.

I see, thank you for the explanation.

**Comment by eernstg** [comment]
Oh, one thing just came to mind: Would it hurt anyone if that 'master' channel were changed to enable all current experiments? Seems like a good opportunity to enable all kinds of bleeding edge exploration, and at the same time perhaps discover some bugs.

**Comment by domesticmouse** [comment]
> Oh, one thing just came to mind: Would it hurt anyone if that 'master' channel were changed to enable all current experiments? Seems like a good opportunity to enable all kinds of bleeding edge exploration, and at the same time perhaps discover some bugs.

I'm happy to turn on experiments, but the more the `master` channel configuration diverges from `beta` and `stable` the less warning I get about inbound breakages that I have to sort out before it becomes a stable launch blocking issue.

It's worth remembering that DartPad uses the underlying dart compilation tool chains in ways that are quite unlike the usual developer experience leading to unique bugs that aren't an issue for everyone else.

**Comment by domesticmouse** [comment]
> In short, there will be too much non-release related noise. True?

That's my nagging concern. It hasn't surfaced yet, with the experimental flags we currently have enabled, and I'm unsure if it really is an issue. I'm more than happy to turn on a bunch of flags on the proviso that I may need to turn them off again in the future if an issue arises.

Please feel free to raise a new issue with the set of flags you'd like to see enabled, and we can try turning them on. I suspect it may break the UI in entertaining ways tho.

/cc @johnpryan FYI

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/dart-pad/issues/2480.
