### ISSUE TITLE
Enable more experiments in the dart-pad master channel

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart-pad#2480]
Cf. https://github.com/dart-lang/dart-pad/issues/2479, where @modulovalue expressed similar ideas.

In order to offer convenient access to upcoming Dart features in dart-pad, we could consider enabling a larger set of experiments in the master channel, or we might add a new channel (perhaps "bleeding_edge") where every experiment that has an experiment flag is enabled (or at least every experiment which isn't considered too incomplete or too unstable to be a useful foundation for exploration).

The point is that this allows developers who are interested in the evolution of Dart to try out various small experiments in Dart-with-X for any experiment X which is included. The same thing could be done using command line tools in a suitable version with `--enable-experiment=X`, but dart-pad is a very convenient place for trying out small exploratory programs.

Another benefit could be that upcoming experiments are thus being tested more intensively, all enabled at the same time, and this could help detecting bugs that arise because of conflicts between the code enabled for one experiment and that for a different experiment.

Here are some example experiments that may fit the bill: `records`, `patterns`, `sealed-class`, `class-modifiers`, `inline-class`, `variance`, `unnamed-libraries`.

(`macros` would certainly be interesting to have, too, but I don't know if that feature would satisfy the constraints imposed by running a program in dart-pad.)

**Comment by mit-mit** [comment]
We need a bit more time to finalize this (i.e. get past the branching point), but from what I currently know, I think the only flag we want for I/O is `inline-class`

**Comment by domesticmouse** [comment]
> We need a bit more time to finalize this (i.e. get past the branching point), but from what I currently know, I think the only flag we want for I/O is `inline-class`

Ping me when you are ready to modify the experiment flags in `master`. Thanks!

**Comment by parlough** [comment]
Now that `master` has branched to 3.1, should we enable `inline-class`?

**Comment by mit-mit** [comment]
Yes, that would be fine

**Comment by domesticmouse** [comment]
> Now that `master` has branched to 3.1, should DartPad enable `inline-class`?

Put this into a PR after landing https://github.com/dart-lang/dart-services/pull/1058 as the dart versions on each channel are now explicit

**Comment by parlough** [comment]
`inline-class` is now enabled on the `master` channel: https://dartpad.dev/?channel=master&id=2b6e078305c37f0cf0599a116501a655

**Comment by domesticmouse** [comment]
Proof of life:

<img width="544" alt="Screenshot 2023-04-26 at 12 52 26 pm" src="https://user-images.githubusercontent.com/30503/234454542-b62bcaa8-437d-427f-80a6-56c6c57b5f48.png">
