### ISSUE TITLE
Feature Request Giti & Terminal intergration

### ISSUE THREAD

**Issue by come219** [dart-lang/dart-pad#2481]
Terminal integration to create directories & git integration to directly pull a project.

**Comment by domesticmouse** [comment]
This request is heading in the direction of a full web editor environment, which is not the intent of DartPad. It would require a complete rearchitecture to implement these requirements, and honestly, it would become a very different product. The intent of DartPad is to be a sketch pad for Dart and Flutter sketches, not full Flutter project development.
