### ISSUE TITLE
Flutter embeds (docs.flutter.dev and api.flutter.dev) are broken 

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2494]
In https://github.com/dart-lang/dart-pad/commit/ad5bdb71c00253792f4a22d3826fd2fc9f02897a, the method used to initialize `version`, wasn't previously called in embeds, but `version` is used in shared code, causing the breakage.

```
Error compiling to JavaScript:
LateInitializationError: Field 'version' has not been initialized.
```

**Comment by johnpryan** [comment]
Ah, the `Embed` class extends `EditorUi` but doesn't call  `updateVersions()`. I think we should probably do that in `_init()`.

**Comment by parlough** [comment]
@johnpryan Yep. I prepared a potential fix in https://github.com/dart-lang/dart-pad/pull/2495 doing just that.

**Comment by johnpryan** [comment]
On it!

**Comment by johnpryan** [comment]
This should be deployed now.

**Comment by parlough** [comment]
Thanks so much!
