### ISSUE TITLE
Printing "Hello World" outputs this error: Error compiling to JavaScript: XMLHttpRequest error

### ISSUE THREAD

**Issue by tokamohamedQC** [dart-lang/dart-pad#2503]
So I'm Trying to print "Hello World" using dartpad, but error is displayed: Error compiling to JavaScript:
XMLHttpRequest error.

Browser: Chrome
OS: windows

**Comment by parlough** [comment]
Thanks for opening an issue!

Could you provide us with the full code you are using?

I just tried:

```dart
void main() {
  print('Hello world!');
}
```

and it worked as expected: https://dartpad.dev/?id=571b1f6e6611e62fa55fe04f04b527bc

**Comment by TokaMohamed-QC** [comment]
void main() {
  
  print('Hello');
}

**Comment by TokaMohamed-QC** [comment]
I tried your code and I got same error

**Comment by parlough** [comment]
Thanks for the information. 

Could you try opening the [Chrome DevTools Console](https://developer.chrome.com/docs/devtools/console/) and letting us know what shows up when you try running the code? 

It could be your network blocking access. Consider trying at https://dartpad.cn and seeing if that works.

**Comment by TokaMohamed-QC** [comment]
Here's a screenshot of network: https://prnt.sc/xCWnjC11LPpH
and I tried other link and worked perfectly
Thanks

**Comment by domesticmouse** [comment]
This is working for me, so it doesn't appear to be a server-side issue. That leaves one of the thirty of so middleboxes between your browser and our server, and that's a hard issue to debug from here.

I'd suggest trying alternate networks to see if you can find one that works.

**Comment by parlough** [comment]
If you are in Egypt, this seems to have been a recurring issue with some Egypt ISPs for many sites.

For now, try other networks as domesticmouse mentioned or use https://dartpad.cn if those don't work. You can also [Get Dart](https://dart.dev/get-dart) or [Get Flutter](https://docs.flutter.dev/get-started/install) to run code on your own machine too :D

**Comment by parlough** [comment]
Thanks again for the report! I'm going to close this issue as stale, as it is likely a local network setup issue or an ISP level problem.

If someone is still experiencing similar issues, please open a new issue with reproduction details and network information. Thanks again :)
