### ISSUE TITLE
Update GoRouter sample for go_router 7.0.0

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2509]
dart-services was updated to use go_router 7.0.0 in https://github.com/dart-lang/dart-services/pull/1068.

The [GoRouter sample](https://dartpad.dev/?id=4a546fc44db8aca351bfe791e251acc2) found at https://gist.github.com/flutterdevrelgists/4a546fc44db8aca351bfe791e251acc2 will need to be updated for the breaking changes in the go_router release.

**Comment by johnpryan** [comment]
Yep, I can update the gist.

**Comment by johnpryan** [comment]
This should be working now. Maybe someday DartPad will support `dart fix` 🤔

**Comment by parlough** [comment]
Thanks!

Maybe someday https://github.com/dart-lang/dart-pad/issues/2449 :)
