### ISSUE TITLE
Renaming the `master` branch to `main`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2515]
FYI that I intend to rename the `master` branch here to `main`. That'll be done following this process:

https://github.com/dart-lang/ecosystem/wiki/Renaming-master-branches-to-main

I'll close this issue once it's done. The github UI will prompt people w/ how to update local clones of the repo; but for completeness, those steps are:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by parlough** [comment]
Cool, thanks for handling this!
