### ISSUE TITLE
Completion isn't doing sorting on flat ordering

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#252]
In cases where there isn't a decent ordering being provided, e.g. everything is flat at priority 1000, the order is essentially random.

The completion display should do a two phase sort, once by priority, second lexically within items of equal priority.

This explains some of the extremely strange sorting we're seeing at the moment.

**Comment by lukechurch** [comment]
In hind-sight, I'll probably just fix this on the server side.

**Comment by devoncarew** [comment]
Luke, I think I saw a PR go by for this on the server?

**Comment by lukechurch** [comment]
Yeah, this is done.
