### ISSUE TITLE
reduce the number of dependabot PRs

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2530]
We might look into reducing the number of dependabot PRs we get into this repo - specifically the pub related dependabot PRs.

We see a lot because we have pub packages configured in the .github/dependabot.yaml file, and, have checked in a lock file for this repo. We could reduce the number of PRs by either removing the pub config from the dependabot file, or, no longer checking in the lock file (and just making sure that our package deps were clearly specified in the pubspec.yaml file).

I'd be in favor of the 2nd option - deleting the lock file.

**Comment by domesticmouse** [comment]
Having the lock file checked in means that the deployed version of DartPad is known and repeatable. 

I'd suggest implementing an email filter rule as a way of reducing the noise from this repository

**Comment by 10Haider** [comment]
vfdxztsgtedgsdfhbdfhngn

**Comment by 10Haider** [comment]
s;hjfdgdfhjsdgfwdflel;wfl

**Comment by 10Haider** [comment]
umair bhai zindabad

**Comment by 10Haider** [comment]
umair software house kholo jaldi

**Comment by johnpryan** [comment]
I'm going to close this since [dependabot.yaml](https://github.com/dart-lang/dart-pad/blob/main/.github/dependabot.yaml#L8) is configured to be monthly.
