### ISSUE TITLE
Padracing demo needs to be updated

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2547]
The demo is linked to from the **Samples** menu and from https://flutter.dev/games.

Looks like the `package:flame/experimental.dart` import needs to be replaced with one to `package:flame/camera.dart`.

Gist: https://gist.github.com/flutterdevrelgists/ecabed4a17a3aad8bee7c6327e472fc8

**Comment by johnpryan** [comment]
Good catch, updated.

I also think we should have some automated tests: https://github.com/dart-lang/dart-pad/issues/2548
