### ISSUE TITLE
Consider enabling the sound variance experiment.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/dart-pad#2555]
@domesticmouse If possible, could the [sound variance](https://github.com/dart-lang/language/issues/524#issuecomment-1594035366) experiment be enabled on the master channel? (https://github.com/dart-lang/dart-pad/issues/2480#issuecomment-1476323291)

**Comment by mit-mit** [comment]
I think we should have DartPad mirror the standard configuration of the SDK; it not it seems like it might get really confusing what the default developer experience is?

**Comment by modulovalue** [comment]
> [...] like it might get really confusing what the default developer experience is?

It looks to me like most people will be using the stable channel on DartPad because that is the default. It could be confusing to some people, but we already have enabled inline-classes as an experiment and it doesn't seem like that has lead to any issues so far. Furthermore, the channel selector is pretty explicit that there are experiments enabled.

---

The master channel + experiment flags are really convenient for discovering issues with the experiments.

An alternative would be (which Erik proposed [here](https://github.com/dart-lang/dart-pad/issues/2480#issue-1632162876)) to have a "bleeding_edge" channel:

[Quote](https://github.com/dart-lang/dart-pad/issues/2480#issue-1632162876):

> [...] or we might add a new channel (perhaps "bleeding_edge") where every experiment that has an experiment flag is enabled (or at least every experiment which isn't considered too incomplete or too unstable to be a useful foundation for exploration).

> The point is that this allows developers who are interested in the evolution of Dart to try out various small experiments in Dart-with-X for any experiment X which is included. The same thing could be done using command line tools in a suitable version with --enable-experiment=X, but dart-pad is a very convenient place for trying out small exploratory programs.

> Another benefit could be that upcoming experiments are thus being tested more intensively, all enabled at the same time, and this could help detecting bugs that arise because of conflicts between the code enabled for one experiment and that for a different experiment.

**Comment by modulovalue** [comment]
For example, the following issues were discovered because the master channel on DartPad enables inline-classes: https://github.com/dart-lang/sdk/issues/52667 & https://github.com/dart-lang/sdk/issues/52674

I'm trying to see if the sound variance experiment is far enough to deal with the following issue: https://github.com/dart-lang/language/issues/3156.

**Comment by mateusfccp** [comment]
This experiment exist in years, and enabling it will maybe give the idea that it will be a default feature in the master branch (and thus, released in the next stable version).

Instead, we should have a way of enabling/disabling for all experiments in the DartPad menu.

**Comment by parlough** [comment]
Thanks for the suggestion and discussion here.

For now, we'd like to avoid too much client side configuration in the DartPad UI, especially if it requires changes to the analysis configuration and context due to the setup of the backend.

As for the sound variance experiment, we'll likely stick to only enabling experiments that are more likely to land in upcoming stable releases, and even then, only in the `main` channel.

Perhaps we can revisit this in the future, but giving DartPad's current goals and support levels, I think this is the best way forward for now. Please feel free to continue the discussion though!
