### ISSUE TITLE
Resolve the relative links in the dartdoc

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#256]
There are lots of relative links in the dartdoc. I'm a bit puzzled how to resolve them, there seem to be some magic going on. For example:

```
{name: identityHashCode, description: identityHashCode(Object object) → int, kind: function, parameters: [Object object], libraryName: dart.core, dartdoc: Returns the identity hash code of `object`.

Returns the same value as `object.hashCode` if [object] has not overridden
[Object.hashCode]. Returns the value that [Object.hashCode] would return
on this object, even if `hashCode` has been overridden.

This hash code is compatible with [identical].}
```

Now the links are resolved in this way at api.dartlang.org, where the `baselink` is `https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer`

```
[object] => [object](${baselink}/dart:core#id_identityHashCode,object)
[Object.hasCode] => [hasCode](${baselink}/dart:core.Object.hashCode)
[identical] => [identical](${baselink}/dart:core.identical
```

**Comment by devoncarew** [comment]
The square braces in the dartdoc are resolved using the imports. They might resolve to symbols in that file, ones in `dart:` libraries, or ones in `package:` references.

What we'd probably need to do is to augment the dartdoc command on the server. When returning dartdoc text, it should try and replace any relative references (`[Foo.bar]`) with something that we can link to reliably on the client (`[Foo.bar](foolib/Foo#bar)`). Or a direct url link. But in any case, we'll need more processing on the server to create reliable links on the client.

**Comment by devoncarew** [comment]
And, if we can't resolve a particular link on the client or server, we should render that reference as if it had just used back-ticks - a markdown 'code' style rather than a markdown link.
