### ISSUE TITLE
Using ternjs dom documentation together with MDN

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#258]
I have made a PR that tries to add a link to the MDN documentation when the dart dom documentation is empty. This looks like this:

![image](https://cloud.githubusercontent.com/assets/1035299/6985771/246fa6f0-da37-11e4-9517-6be6415e94c1.png)

I found this json file at ternjs that gives a very short summarty to MDN articles:

https://github.com/marijnh/tern/blob/master/defs/browser.json

I think it would nice to not only show the MDN link, but also show a short summary if it exists in this json file. Thoughts @devoncarew @lukechurch  ?

**Comment by devoncarew** [comment]
@sethladd, can you weigh in re: poly-filling the dart:html API docs with references to the MDN docs, when we can match up a dart reference to the corresponding MDN one?

**Comment by devoncarew** [comment]
@kasperpeulen, thinking about this a bit more:

- this really needs to be solved at the dart:html level
- putting an external link to MDN in dartpad _is_ useful to users
- doing anything more than that is probably not desirable, given point 1 :)

So, lets look at landing you current 'external resource' link PR, but not try and parse and provide improved html docs ourselves. Make sense?

**Comment by kasperpeulen** [comment]
Yeah, seems reasonable :)

2015-04-07 22:00 GMT+02:00 Devon Carew <notifications@github.com>:

> @kasperpeulen <https://github.com/kasperpeulen>, thinking about this a
> bit more:
>
>    - this really needs to be solved at the dart:html level
>    - putting an external link to MDN in dartpad *is* useful to users
>    - doing anything more than that is probably not desirable, given point
>    1 :)
>
> So, lets look at landing you current 'external resource' link PR, but not
> try and parse and provide improved html docs ourselves. Make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-pad/issues/258#issuecomment-90714507>.
>



-- 
Kasper
