### ISSUE TITLE
VS Code Theme Based On Dartpad

### ISSUE THREAD

**Issue by SakhileMamba** [dart-lang/dart-pad#2586]
The Dartpad theme is great. I think a VS Code copy would be a great hit. There are some knockoffs on the VS Code market place but they aren't quite the same.

Please make this happen.

**Comment by johnpryan** [comment]
Hi @SakhileMamba, all of the colors are available in these two files:
- [cm-dartpad-dark.scss](https://github.com/dart-lang/dart-pad/blob/ae401b27bb35946fba3358a583ddba72ded6b407/pkgs/dart_pad/web/styles/cm-dartpad-dark.scss)
- [cm-dartpad-light.scss](https://github.com/dart-lang/dart-pad/blob/ae401b27bb35946fba3358a583ddba72ded6b407/pkgs/dart_pad/web/styles/cm-dartpad-light.scss)

You should be able to make a VSCode theme based on these colors.
