### ISSUE TITLE
Don't move the text whilst the user is typing

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#259]
if you fix an error/warning, pause for a moment, then the analysis errors go away - that's great.

However if you're at the bottom of a long file, this causes the text to move down as you're typing. That's distracting. In this case it would be better to pad the bottom with some empty lines.

**Comment by lukechurch** [comment]
The counter part problem to this - where we may have to move the users code if if they're typing at the end of the file the errors and warnings appear over the code the user is writing. That's more frustrating than the previous.

**Comment by devoncarew** [comment]
fixed
