### ISSUE TITLE
Discovery of keyboard shortcuts

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#26]
We need a mechanism to help users discover keyboard shortcuts for e.g. the Run button.

The easiest would be hover tooltips, a bit better would be that every time you used the mouse to perform an action there was an indicator in e.g. the bottom right of the screen what the shortcut would be.

**Comment by devoncarew** [comment]
Can add a UI for this. @lukechurch, which keys should we call out? Currently, we use
- command-return for run
- command-s ==> noop (which we could change)
- various keystrokes inherited from codemirror (are there any here worth calling out?)

I'll probably use an icon like the `keyboard` one from this [page](https://www.polymer-project.org/components/core-icons/demo.html) and have it pop up an overlay.

**Comment by kasperpeulen** [comment]
seems to be implemented, could be done maybe a bit nicer though

**Comment by devoncarew** [comment]
Related to #295. We show an overlay on cmd-shift-/ (cmd-?). We should probably add a little keyboard icon on the bottom row in order to aid discovery.

**Comment by devoncarew** [comment]
Last bit done by #359.
