### ISSUE TITLE
Implement quick-fixes UI

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#260]
I'm trying to think of how a quick fix UI could look like. What about something like this ?

![](http://i.imgur.com/Gje52UB.png)

**Comment by lukechurch** [comment]
@kasperpeulen 

Looks like a great start. I'd also like these to appear as links on the warnings in the view.

Ideally for we could show a preview of what the code would look like after the transformation in the documentation view, with the changes highlighted!

**Comment by kasperpeulen** [comment]
I'm now implementing this by using the completion UI (using hintApplier etc.). It works pretty sweet that way:

![](http://i.imgur.com/zCYmE9O.gif)

**Comment by lukechurch** [comment]
@kasperpeulen awesome, I'll get busy getting you the data!

**Comment by lukechurch** [comment]
Here's a sample piece of data: 

{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"...","offset":32,"length":1,"startLine":4,"startColumn":1},"message":"Expected to find ';'"},"fixes":[{"message":"Insert ';'","edits":[{"file":"...","fileStamp":1428100333014,"edits":[{"offset":33,"length":0,"replacement":";"}]}],"linkedEditGroups":[]}]}]}

The format may not be _exactly_ the same, but it'll be something like this.

This was a fix for

void main() {
  int i = 0;
  i.
}

At pos 32 (i.e. after the i.)

**Comment by kasperpeulen** [comment]
What about this?

![image](https://cloud.githubusercontent.com/assets/1035299/6990332/649e2354-da6a-11e4-91d5-b6743f393055.png)

**Comment by devoncarew** [comment]
@lukechurch, @kasperpeulen, largely done, or still in progress?

**Comment by kasperpeulen** [comment]
I would say largely done, allthough it would probably be nice to have this
fixed: https://github.com/dart-lang/dart-services/issues/143

Maybe it would be better to not show a wrench at all (for now), until we
get this really fixed.

**Comment by lukechurch** [comment]
I would say that I'd like to have all of the UI implementation in but behind a flag.

I've fixed up most of the core stability issues in dart-services, but there still some cases where the heurestic isn't accurate. I'm chasing those down, once they're fixed, we're good to remove the flag.

Make sense?

**Comment by lukechurch** [comment]
I've found and fixed the core issue here on the services side. I think we're good to go for now, and just need to keep refining going forwards
