### ISSUE TITLE
Dartpad certificate fails with ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/dart-pad#2604]
## What happened?

When visiting `https://dartpad.dev` I get a certificate related error.

```
NET::ERR_CERT_COMMON_NAME_INVALID
```

### Browser

Browser: Brave

Version: 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):1540
```

### Machine

Operating system: Windows 10

Version: Windows 10, version 22H2

**Comment by gaetangr** [comment]
Can reproduce in Safari IOS

**Comment by navaronbracke** [comment]
It seems to have been resolved by now. I no longer get the certificate error.

**Comment by johnpryan** [comment]
Thanks for filing an issue @navaronbracke, we recently switched hosting providers, so dartpad.dev was unavailable for a few hours.
