### ISSUE TITLE
Upload latest DDC JS artifacts for `master` channel

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2617]
The lack of them is causing the `master` deployment to fail (https://github.com/dart-lang/dart-pad/runs/15882541518) as well as the related analysis (https://github.com/dart-lang/dart-pad/actions/runs/5870035887/job/15916260464).

**Comment by johnpryan** [comment]
I'd like to make step part of the Cloud Build deployment, will take a look.

**Comment by parlough** [comment]
That'd be fantastic!

**Comment by parlough** [comment]
I'm going to marked this fix by https://github.com/dart-lang/dart-pad/commit/f87b67c7726508889aa0d4f38a74041c8aa44436 and https://github.com/dart-lang/dart-pad/commit/fcf8566ba5f645df2fac2fdd1ad9ba80548e4eba since the `main` channel is now up to date.
