### ISSUE TITLE
TextField and TextFormField don't work anymore in MS Edge

### ISSUE THREAD

**Issue by tporcham** [dart-lang/dart-pad#2626]
## What happened?

The classes TextField and TextFormField don't work anymore in MS Edge.
When I run code that includes a TextField (e.g. second example on the page https://api.flutter.dev/flutter/material/TextField-class.html) I can click into the field, a blinking cursor is shown. When I enter a character the field empties and shows no text - the field stays empty when I enter more text.

## Steps to reproduce problem
 Open https://api.flutter.dev/flutter/material/TextField-class.html and run the second example.

### Browser

Browser:
MS Edge

Version:
Microsoft Edge | 115.0.1901.203 (Offizielles Build) (64-Bit)
Revision | a5a2b1779bcfe71f081bc9104cca968d420a89ac
Chromium-Version | 115.0.5790.171
Betriebssystem | Windows 10 Version 22H2 (Build 19045.3208)
JavaScript | V8 11.5.17.12

Are you using any extensions/plugins that affect website behavior
No.

Are there any warnings or errors in your browser's JavaScript console?
General warnings about usage of deprecated functions are shown.

### Machine

Operating system:
Windows

Version:
10

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:
see https://api.flutter.dev/flutter/material/TextField-class.html example 2.

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

No output on console.

![image](https://github.com/dart-lang/dart-pad/assets/8996358/5c4e5f7a-eaba-4d40-845d-fc21134e129c)

**Comment by tporcham** [comment]
Version infro from the footer of https://api.flutter.dev/flutter/material/TextField-class.html
Flutter 3.13.0 • 2023-08-16 10:19 • efbf63d9c6 • stable

**Comment by parlough** [comment]
Thanks for opening an issue!

Does this happen in a full version of DartPad like: https://dartpad.dev/?id=387be773179a32f3698dcbd982e1bda7

Could you also try the text fields in a standalone web example like https://flutter.github.io/samples/web/material_3_demo/?

**Comment by tporcham** [comment]
> Thanks for opening an issue!
> 
> Does this happen in a full version of DartPad like: https://dartpad.dev/?id=387be773179a32f3698dcbd982e1bda7

Yes it happens in te full version as well. Attached is a screencast of what it looks like (changed the background color to grey).
You cannot see the text while entering. Though characters are "accepted" by the field

> 
> Could you also try the text fields in a standalone web example like https://flutter.github.io/samples/web/material_3_demo/?

Happens here as well, same behaviour of the fields in the Text Inputs section.

[Bildschirmaufnahme.webm](https://github.com/dart-lang/dart-pad/assets/8996358/44dd4d8d-f59e-48d4-b2b2-bd3bf383ba31)

**Comment by parlough** [comment]
Thanks for verifying, it's appreciated! Since it occurred with non-DartPad Material 3 demo, it looks like this is potentially a general issue with Flutter web on Edge and not with DartPad itself.

Generally Flutter issues are tracked at https://github.com/flutter/flutter/issues. Would you mind opening an issue on that repository with the same information you provided here? They'll be able to triage the issue and perhaps know of a solution.

I'll look to see if there's an existing issue though and will mention it here if I can find one. Thank you!

**Comment by tporcham** [comment]
Not a problem. I created https://github.com/flutter/flutter/issues/133232

**Comment by parlough** [comment]
Thanks for that! I see you identified the root issue there, so I'll close this one :)
