### ISSUE TITLE
consider re-implementing the services protocol in grpc

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2635]
We should consider re-implementing the services protocol in grpc. Given that the client runs in a browser, this would mean grpc-web.

**Comment by devoncarew** [comment]
@domesticmouse - I see from https://github.com/dart-lang/dart-pad/issues/1129 that you moved from our initial, older protocol to using Protobuf3 JSON over HTTP.  I'm curious why you went with that instead of grpc (or json over http, ...).

cc @mosuem for fyi about possibly consuming grpc-web here

**Comment by domesticmouse** [comment]
At the time of this work we considered moving to pure gRPC, but we had a DRE on the team from Cloud who was quite negative on gRPC's startup costs, and pushed for JSON over RPC instead.

So I implemented a straight mapping of the then current RPC into Protobufs, but encoded them as JSON on the wire. This had the added advantage that the other clients of the Dart Services API didn't see any change in the API surface and could continue using the new back end without any migration requirement.

The open question here is, do you still want to support the other users of Dart Services API? If you don't then the migration concerns of moving to grpc-web is a potential path. If you do want to continue supporting the current external users, I'd venture that migrating to grpc-web would probably be a hill to far for them.
