### ISSUE TITLE
www.dartpad.dev results in 404 Not Found

### ISSUE THREAD

**Issue by miDeb** [dart-lang/dart-pad#2646]
## What happened?

https://www.dartpad.dev/ no longer opens.

## Steps to reproduce problem

Open https://www.dartpad.dev/ in a browser.

## Additional info

This must have worked at some point, the `www.` subdomain is in my browser history multiple times.

### Browser

Browser: Firefox/117, Chrome/116

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system: Windows 11

**Comment by devoncarew** [comment]
Thanks for the report! Marking this as a dup of https://github.com/dart-lang/dart-pad/issues/2638.
