### ISSUE TITLE
cloud_firestore package doesn't work

### ISSUE THREAD

**Issue by SWF-DEV2** [dart-lang/dart-pad#2653]
## What happened?

I use cloud_firestore package in dartpad. But, it has error.
`
Error compiling to JavaScript:
local_pub_cache/hosted/pub.dev/cloud_firestore-4.8.5/lib/src/firestore.dart:50:46: Error: Required named parameter 'databaseURL' must be provided.
        FirebaseFirestorePlatform.instanceFor(app: app);
                                             ^
local_pub_cache/hosted/pub.dev/cloud_firestore_platform_interface-5.16.0/lib/src/platform_interface/platform_interface_firestore.dart:40:11: Context: Found this candidate, but the arguments don't match.
  factory FirebaseFirestorePlatform.instanceFor({
          ^^^^^^^^^^^
`

## Steps to reproduce problem

Just use cloud_firestore in dartpad.

I expect versions of cloud_firestore and platform_interface_firestore are not match.
cloud_firestore: 4.8.5
platform_interface_firestore: 5.16.0

**Comment by parlough** [comment]
Thanks for the report and extensive details. As part of the [new, simplified version](https://github.com/dart-lang/dart-pad/issues/2808) of the DartPad frontend, support for Firebase (and therefore Cloud Firestore) was removed, so I'm going to go ahead and close this issue as stale.

If anyone reading this would like to see Firebase support or similar added back, please consider starting that discussion in a new issue. Thanks :)
