### ISSUE TITLE
dartpad links to github are broken

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-pad#2660]
From the [sharing guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide), dartpad sharing links take the form `https://dartpad.dev/[github gist id]`. These however no longer work (e.g. [this one](https://dartpad.dev/debbac58c124bb65c5a4df148ae28141) is broken). 

It does look like `https://dartpad.dev/?id=[github gist id]` works (e.g. [this one](https://dartpad.dev/?id=49bde0c1ed780decc902f3d4d06d8f0c)), but that is 

1. not what the sharing guide says, and 
2. a breaking change to existing functionality. 

This issue caused several DartPad links to be broken during F3 presentations this week.

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by filiph** [comment]
More context in my dupe issue over at #2661.

**Comment by parlough** [comment]
Thanks! Closing in favor of https://github.com/dart-lang/dart-pad/issues/2661.
