### ISSUE TITLE
Sharing URLs doesn't work

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#2661]
## What happened?

At one point in time, it was possible (and expected) to share dartpads with a link like this:

> https://dartpad.dev/debbac58c124bb65c5a4df148ae28141

That is to say, `https://dartpad.dev/<GIST_ID>`. But this stopped working. When you use such a link now, it will just show whatever you had open in DartPad before.

Instead, you have to use something like:

> https://dartpad.dev/?id=debbac58c124bb65c5a4df148ae28141

## Steps to reproduce problem

Follow the official sharing instructions (click three dots on the top right of DartPad, then click "Share", then follow [the document's instructions](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide)).

OR

1. Create a new gist at https://gist.github.com/
2. Note the ID of the new gist
3. Open `https://dartpad.dev/<THE_GIST_ID>`

Instead of the code from the gist, DartPad is just populated with the latest code you had on DartPad.

Note that this "latest code" behavior makes it confusing when you're creating a new DartPad and checking. You check the new link, and the code you want there is there (because, normally, you just finished creating the DartPad sample in another DartPad window). So you assume it works. You share the link, but when the recipients open it, all they see is whatever _they_ had open last on DartPad.

### Browser

Browser: Firefox, Chrome

Warnings: 

* No warning in Developer Console

### Machine

Operating system: macOS

**Comment by filiph** [comment]
This is a dupe of #2660, with slightly more context.

**Comment by johnpryan** [comment]
It looks like we didn't update the redirect when we switched to firebase hosting. I think this is something we can change in [firebase.json](https://github.com/dart-lang/dart-pad/blob/main/pkgs/dart_pad/firebase.json)

**Comment by Deleplace** [comment]
programming-idioms.org has:
- a) 27 links like `dartpad.dartlang.org/123`
- b) 25 links like `dartpad.dev/123`
- c) 57 links like `dartpad.dev/?id=123`

The 52 links of (a) and (b) are currently broken.

**Comment by johnpryan** [comment]
@Deleplace marking as a P0, thanks!
