### ISSUE TITLE
Misleading gist instructions in Wiki?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart-pad#2671]
Looking at https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide, I tried to create a shareable dart-pad example based on https://gist.github.com/eernstg/ffa608c63f62ebb8f8fc1caf6b3569af. However, the description on the 'Sharing Guide' page tells me to use a link which is derived from the gist link as follows:

> Direct DartPad to the gist ID. For example, to view https://gist.github.com/49bde0c1ed780decc902f3d4d06d8f0c in DartPad, use the URL https://dartpad.dev/49bde0c1ed780decc902f3d4d06d8f0c.

So I assumed that https://gist.github.com/eernstg/ffa608c63f62ebb8f8fc1caf6b3569af could be accessed via dart-pad by using the link https://dartpad.dev/eernstg/ffa608c63f62ebb8f8fc1caf6b3569af, but that link does not bring up anything useful (just a page that seems to be broken because there is no CSS, or something like that).

I also tried the variant https://gist.github.com/ffa608c63f62ebb8f8fc1caf6b3569af, but that just brings up an empty dart-pad (this one is a working dart-pad, though).

So the wiki page seems to need an update: Do I need to do something extra in order to obtain a gist page whose URI is of the form `https://gist.github.com/ffa608c63f62ebb8f8fc1caf6b3569af` (getting rid of the username)? Or do I need to transform the gist URI to a DartPad URI in a different way than the two I mentioned above?

**Comment by parlough** [comment]
That style of link worked until recently (with just the gist ID), but is currently broken (https://github.com/dart-lang/dart-pad/issues/2661).

For now, you can instead specify the gist ID with the the `id` query parameter:

https://dartpad.dev/?id=ffa608c63f62ebb8f8fc1caf6b3569af

I edited the wiki guide to use the query parameter instead, and will track fixing the old link in https://github.com/dart-lang/dart-pad/issues/2661.
