### ISSUE TITLE
Update padracing example for flame 1.9 and 1.10 or remove from dropdown

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2684]
The [padracing sample](https://dartpad.dev/?id=ecabed4a17a3aad8bee7c6327e472fc8) found at https://gist.github.com/flutterdevrelgists/ecabed4a17a3aad8bee7c6327e472fc8 is broken with the latest packages update due to breaking changes in v1.9.0.

**Comment by devoncarew** [comment]
@johnpryan, thoughts? (I wouldn't have any concerns with removing the sample)

**Comment by johnpryan** [comment]
Let's remove it for now: https://github.com/dart-lang/dart-pad/pull/2706
