### ISSUE TITLE
Allow injected embeds to specify titles and surface titles on embedded views

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2694]
Primary goals:
- Add parsing to embed injection functionality to retrieve a title argument
  - Use the title argument to add title to created iframe for accessibility
  - Fallback to text about being an embedded DartPad or similar

Secondary goals to consider:
- Surface injected title or gist titles somewhere in embed UI

**Comment by devoncarew** [comment]
> Add parsing to embed injection functionality

Are you thinking as a url parameter? Or as some property of the script - via a dartdoc comment or something like markdown front matter?

**Comment by parlough** [comment]
I didn't give much thought to the how yet since I haven't looked at the injection code in a long time, but I was hoping to make it not too different from how we specify Google analytics ID and theme, which [currently parses](https://github.com/dart-lang/dart-pad/blob/d091008d51ff586059b018d1fdd388955972d164/pkgs/dart_pad/lib/inject/inject_parser.dart#L83) classes on the `<code>` element and [passes them in](https://github.com/dart-lang/dart-pad/blob/d091008d51ff586059b018d1fdd388955972d164/pkgs/dart_pad/lib/inject/inject_embed.dart#L190) as query parameters.

I was preliminarily thinking allowing a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) on the `<code>` element, like `data-title="Exercise showcasing Dart string interpolation"`, then adding that to the created iframe element. We could use the existing class parsing mechanism, but since spaces are allowed in titles, that would get a bit messy.

I don't really need to surface the title in the actual embed for this work, but if it's something that's valuable, it could be pulled from the iframe, passed as a query parameter, or included in the initialization message.

What do you think? I think how we inject/embed DartPads needs to be rethought in the future anyway, so I'm not looking for a perfect solution.
