### ISSUE TITLE
Dynamic adding a plugin

### ISSUE THREAD

**Issue by rekire** [dart-lang/dart-pad#2697]
At first I'm aware about [Package and plugin support](https://github.com/dart-lang/dart-pad/wiki/Package-and-plugin-support). I'm wondering if I can use dart-pad as a live preview of my plugin I'm planning to publish soon.

It seems that this is not possible out of the box, but is there a trick I could use? (By side to put all my classes into the sample code)

**Comment by johnpryan** [comment]
DartPad doesn't support arbitrary packages right now, you can learn more about how package support works on this page: https://github.com/dart-lang/dart-pad/wiki/Package-and-plugin-support

**Comment by Levi-Lesches** [comment]
I think they were asking about hosting a DartPad box on their own site, pre-loaded with their own package. So not adding to the official DartPad site or for all DartPad users, but it could be useful on sites like https://riverpod.dev/ to be able to add any, eg, Riverpod packages to the DartPads on their site for readers to play around with, without petitioning for official approval.

**Comment by johnpryan** [comment]
Right now, DartPad compiles user code on the server, which uses a Dart/Flutter project with a `pubspec.yaml` file with all of the supported packages listed in the `dependencies` section. So this issue sounds to me like it's asking for any package on `pub.dev` to be supported, but I might be missing something here.

There are already packages that have forked this repo and hosted their own version (For example, https://docs.hivedb.dev) , but we don't maintain instructions since it's a somewhat involved process.

**Comment by Levi-Lesches** [comment]
Again, could be wrong, but I believe they mean by providing the _source_ of the code itself, not just "any package on Pub". It can probably be implemented as "include this package's Dart files to be compiled, but hide it from the UI's `main.dart` and allow the user's code to import it". Importing this package can then be done using a pubspec `dependency_override` path dependency. There's the problem of what packages can _that_ package import... probably keep it to any package already allowed on DartPad today. 

If that's a security concern that makes sense, but in principle it's just like the user entering all that code by hand, or all the code being at the bottom of `main.dart`.

**Comment by rekire** [comment]
My intent was just to let the developer play with my plugin with setting up a new project locally. DartPad looks like perfect for that use case. On the other hand as I wrote initially in my feature request I am aware for the normal process and I don't think that it is necessary to become one of that exclusive packages.

Also the point from Levi was already in my mind I could put everything in my `main.dart`, but that feels like a very dirty hack which I would like to avoid. Right now I'm thinking that I compile simply my example app for web and embedded it via `<iframe>`.
