### ISSUE TITLE
Consider displaying proper error messages and not just status codes.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/dart-pad#2731]
If we try to run, e.g., an empty dartpad, we get the following error:

<img width="618" alt="Screenshot 2023-11-29 at 03 53 13" src="https://github.com/dart-lang/dart-pad/assets/24444584/7e725123-569e-4c64-8682-c22aa22c69af">

It doesn't seem to me that this is very helpful and, in this case, it feels like DartPad is broken. I think it would be useful if the error messages that the compiler emits would be shown.

---

If we make the analyzer fail (crash?) with, e.g., the following program:

```dart
void main() {
  List<int> c = [var j] = [var j] = [var j] = [12];
  print(c);
  print(j);
  final a = (final f) => 33;
  final b = (final g, final ) = 55;
  final c = (final h) async => 77;
  final d = throw 99;
}
```

we get the following error message:

<img width="443" alt="Screenshot 2023-11-29 at 03 54 27" src="https://github.com/dart-lang/dart-pad/assets/24444584/102b8b32-501d-4e07-8b08-1648ea034c0c">

This also seems confusing to me. It doesn't give users any opportunity to understand what might have went wrong and how they can prevent that from ever happening again (such as by filing an issue).

**Comment by devoncarew** [comment]
Thanks for the report! This looks like a regression.

**Comment by lrhn** [comment]
It's highly annoying to not get the error messages from the compiler when there is something wrong.

While the analyzer warnings and errors are often useful, I sometimes use DartPad to look for *differences* between the CFE and the analyzer. When the compiler just says 
```
Error compiling to JavaScript:
compile: 400: 
```
for every possible problem, including forgetting to write a `main` function (which the analyzer doesn't warn about), then it's not useful.

**Comment by devoncarew** [comment]
There are two things going on here; the front-end crash, and a regression in how we show error messages. The 2nd item is due to a recent re-write of the dart-pad backend. It should be straightforward to restore the previous behavior here.

**Comment by modulovalue** [comment]
Thank you @devoncarew for the quick fix! Compiler error messages are being shown now.

<img width="595" alt="Screenshot 2023-11-30 at 19 45 24" src="https://github.com/dart-lang/dart-pad/assets/24444584/3e8dc161-9082-468e-8c47-1eb7cf282a92">

---

The following message is being displayed for the analysis failure due to an exception:

<img width="447" alt="Screenshot 2023-11-30 at 19 45 33" src="https://github.com/dart-lang/dart-pad/assets/24444584/90851f58-1fd7-48af-b7f1-c62bb840748e">

I think it would be helpful if users had the opportunity to report an issue instead of having to understand what "No name provided" means, but this might be a use-case not worth optimizing for? I'm not sure.

**Comment by devoncarew** [comment]
Thanks for the report! It was very detailed and timely.

> but this might be a use-case not worth optimizing for? I'm not sure.

This particular issue should be very rare; this is a failure in our tools - a crash - and not normal static analysis results (i.e., you should see static analysis results for your snippet, and not a crash).

**Comment by modulovalue** [comment]
Got it. @devoncarew feel free to close this issue if you think that it has been resolved. To me it was mostly about the lack of error messages, which is fixed now.

**Comment by devoncarew** [comment]
Great; the other portions - the crash - are covered in some other issues.
