### ISSUE TITLE
[UX] Warnings take precedence over errors.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/dart-pad#2741]
Consider: 

```dart
external const foo1;

external const foo2 = 0;
```

Which leads to the following screen:

<img width="1150" alt="Screenshot 2023-12-03 at 00 15 20" src="https://github.com/dart-lang/dart-pad/assets/24444584/da9bfd29-fd9f-4bf9-a191-b672f173a58d">

Notice how the analyzer reports an error for foo1, but the editor UI only displays a warning by underlining the foo1 identifier with a blue line and not a red one.

It appears that warnings take precedence over errors when multiple spans overlap, but I think that it would make more sense for errors to take precedence over warnings because they are critical to getting a program to compile, whereas warnings are not.

**Comment by devoncarew** [comment]
(looks like a dup of https://github.com/dart-lang/dart-pad/issues/2581)

**Comment by modulovalue** [comment]
Closing as duplicate of https://github.com/dart-lang/dart-pad/issues/2581
