### ISSUE TITLE
All exceptions seem to become a "Script Error."

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/dart-pad#2742]
Consider the following example:

```dart
void main() {
  throw 0;
}
```

If we use Safari to run it on DartPad we get:

```
Script error.
```

<img width="1118" alt="Screenshot 2023-12-04 at 02 37 26" src="https://github.com/dart-lang/dart-pad/assets/24444584/b9ad5554-b137-4400-889e-42e90f76d384">

If we use chrome we get the actual error:

<img width="939" alt="Screenshot 2023-12-04 at 02 39 01" src="https://github.com/dart-lang/dart-pad/assets/24444584/4b0a6d63-9a44-4523-9863-4cc155ca88e0">

I think it would be very helpful if DartPad could show the actual error when running in Safari the way that it does when running in Chrome.

**Comment by modulovalue** [comment]
This appears to longer be the case in the flutter rewrite of DartPad.

**Comment by modulovalue** [comment]
<img width="827" alt="Screenshot 2024-02-18 at 15 18 43" src="https://github.com/dart-lang/dart-pad/assets/24444584/ad475429-2ca0-4ab1-a3ae-418080538ec5">

Well, now Chrome is also showing a Script error.

**Comment by parlough** [comment]
I'm going to consolidate this issue in to https://github.com/dart-lang/dart-pad/issues/3008 alongside other exception surfacing improvements. Thanks for the report and the details!
