### ISSUE TITLE
Update Riverpod sample to promote best practices

### ISSUE THREAD

**Issue by KyleFin** [dart-lang/dart-pad#2762]
See https://github.com/rrousselGit/riverpod/issues/3226

(I'm not sure who has access to update these gists. Sorry if it was unhelpful to file an issue here and in Riverpod!)

**Comment by parlough** [comment]
Thanks for noticing and reporting this :) 

I'm not familiar with Riverpod myself so any improvements sound great to me.

\cc @domesticmouse If you have a chance, could you update https://gist.github.com/flutterdevrelgists/ef06ab3ce0b822e6cc5db0575248e6e2 with @KyleFin's code at https://github.com/rrousselGit/riverpod/issues/3226#issue-2049260050 if it looks good to you?

**Comment by domesticmouse** [comment]
I only have a day left before I'm out for Xmas holidays, so I'm handing this off to @johnpryan to update.

**Comment by johnpryan** [comment]
Thanks for filing an issue!
