### ISSUE TITLE
Work around dart2wasm `Expando` limitations in SketchPad 

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2763]
SketchPad builds, but has some runtime issues when building with just `--wasm`.

You can find SketchPad's source at https://github.com/dart-lang/dart-pad/tree/main/pkgs/sketch_pad

Staged site to see errors in console: https://parlough-dart-dev.web.app/

Tested on:

- Flutter: https://github.com/flutter/flutter/commit/62d699961f5a9c7e56a61c5acfcc86518458756f
- Dart: https://github.com/dart-lang/sdk/commit/4c59838945d9fb2b3056525532e1789a0bf920a7

**Comment by parlough** [comment]
Both cases seem to occur when the controllers of each `HtmlElementView` we create call the `onPlatformViewCreated` callback we pass in:

- https://github.com/dart-lang/dart-pad/blob/ed1c9d1c6eb87a18667c39fd5fa8a430f62b76f2/pkgs/sketch_pad/lib/editor/editor.dart#L181
- https://github.com/dart-lang/dart-pad/blob/ed1c9d1c6eb87a18667c39fd5fa8a430f62b76f2/pkgs/sketch_pad/lib/execution/execution.dart#L80

**Comment by parlough** [comment]
I need to look closer, but initially it seems like these errors happen when our `HtmlElementView` `onPlatformViewCreated` callbacks get called and we try to access properties earlier expanded onto JS-interop elements accessed through the platform view registry. 

This seems to be because the JS-interop types have an identity with `dart2js` but not with `dart2wasm`?

The callbacks:

- https://github.com/dart-lang/dart-pad/blob/ed1c9d1c6eb87a18667c39fd5fa8a430f62b76f2/pkgs/sketch_pad/lib/editor/editor.dart#L181
- https://github.com/dart-lang/dart-pad/blob/ed1c9d1c6eb87a18667c39fd5fa8a430f62b76f2/pkgs/sketch_pad/lib/execution/execution.dart#L80

**Comment by parlough** [comment]
We can implement this differently, but is this difference in behavior expected? Or perhaps using a static interop type like this isn't supported?

\cc @srujzs Sorry to keep pinging you, but I'm trying to identify what's an actual issue versus what's us trying to do something in a way that's explicitly unsupported (and therefore should be documented to help others avoid it).

**Comment by srujzs** [comment]
Sorry for the late response! It looks like `Expando`s use `identical`, which unfortunately won't work in this case for dart2wasm. Here's a simple test:

```dart
import 'dart:js_interop';

import 'package:expect/minitest.dart';

@JS()
@staticInterop
class Window {}

@JS()
external Window get window;

void main() {
  const String _viewType = 'dartpad-execution';
  final Expando _expando = Expando(_viewType);

  _expando[window] = 10;
  expect(_expando[window], 10);
}
```

When we get external values, we introduce a box around that value in dart2wasm (`JSValue`). We do not do the same on the JS backends as they don't need to be boxed. So, we get a new value in dart2wasm, and the same value on the JS backends. We should definitely document that. Note that `==` should be the same on all backends as it is overridden to use the underlying JS equality.

A workaround might be to use a `Map` as an intermediary to the `Expando`.

**Comment by parlough** [comment]
Thanks for the investigation and explanation @srujzs! That all makes sense.

I didn't write the original code, but I'll try a few ways to restructure this, and see what turns of best. I'm all for avoiding `Expando` anyway :) 

It seems the `Expando` docs do outline some specific types they won't work on, so might be worth mentioning `dart:js_interop` types (even if it will on some backends).

**Comment by srujzs** [comment]
It looks like we might be able to support this! I thought `Expando`s used `identical` under the hood, but it doesn't look like that's the case on the web compilers, and so we may be able to unbox to check for equality. I added a comment in that documentation request.

**Comment by devoncarew** [comment]
Seeing this issue a little late; we're using expandos here to pass some information around during web plugin initialization. I'm sure there are equally effective non-expando ways we could accomplish the same thing.

**Comment by parlough** [comment]
@devoncarew Would you be able to handle this update since you're familiar with the initialization? No need to prioritize it, just want to make sure we don't duplicate work. Let me know. Thanks! :D
