### ISSUE TITLE
Fix issue with package:web and CORS

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2765]
After https://github.com/dart-lang/dart-pad/pull/2755 was deployed it produced a CORS error when running snippets. 

cc: @parlough

**Comment by parlough** [comment]
I should have thought to try staging on Firebase with the current config, sorry about that.

Happy to review any changes here.

**Comment by parlough** [comment]
Also consider redeploying the previous version until we have a chance to fix this.

**Comment by johnpryan** [comment]
I rolled back to a working version for now - you're right we'll need to deploy this somewhere to debug since it doesn't happen locally.
