### ISSUE TITLE
Codemirror is not handling scroll wheel events

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2782]
If you create a large enough file in the preview.dartpad.dev editor, you are unable to use the scroll wheel to scroll.

**Comment by parlough** [comment]
@johnpryan @devoncarew I'm thinking this might be a blocker for any switch to the new UI.

I can scroll with my trackpad in Chrome, but scrolling doesn't work at all in Firefox.

I probably won't have time to look at this until late Thursday, but could come back to this after that.

**Comment by devoncarew** [comment]
Can you run a quick test - can you remove the Flutter elements that are positioned above codemirror (the items in the `Stack` - like the run button and such)?

**Comment by parlough** [comment]
Yeah, I'm still unable to scroll with the other elements of the `Stack` removed, same if I remove the other menus as well.

**Comment by parlough** [comment]
Confirmed on Chrome and Firefox as fixed by https://github.com/dart-lang/dart-pad/commit/2c9ab2b285317034f2c5df08ef241616bd5be8c2. Thanks David!
