### ISSUE TITLE
What to do with ultra long param popups ?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#279]
What shall I do with this ?

![image](https://cloud.githubusercontent.com/assets/1035299/7023442/791ff2d0-dd35-11e4-8c64-8b4fa7865f5d.png)

**Comment by lukechurch** [comment]
Multiple lines pls.

**Comment by kasperpeulen** [comment]
Shall I also set a max-width ?

2015-04-07 15:01 GMT+02:00 Luke Church <notifications@github.com>:

> Multiple lines pls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-pad/issues/279#issuecomment-90540518>.
>



-- 
Kasper

**Comment by kasperpeulen** [comment]
![](http://g.recordit.co/u3i477CVWK.gif)

I think it becomes a bit distracting when I have 3,4 lines of parameters
floating in a popup. What about just making the width equal to the
editpanel width, and then letting the user being able to scroll through it
if it really wants ?

**Comment by kasperpeulen** [comment]
![](http://i.imgur.com/Pys3vg8.gif)

**Comment by lukechurch** [comment]
I'd don't much like L-R scrolling tool tips. How do you pause them when you're thinking? How do you go back? How do they work on mobile?

We might be able to get away with a relatively short box if the completion automatically moves as the user adds new content.

E.g. If you have a 20 params method, as the user enters one after the other as well as going bold/white, the displays text should left align on the param being entered. (probably actually 1 to the left of the one being entered to help with the user maintaining context)

**Comment by lukechurch** [comment]
Funny - I've just run into this in Editor.

![image](https://cloud.githubusercontent.com/assets/2978182/7024534/80b0d622-dd35-11e4-911d-4c13fb1525c0.png)

Are multiple lines really that bad? If you've prototyped it could you post a screenshot? I can't imagine wanting to scroll though this.

**Comment by kasperpeulen** [comment]
what about this:

![](http://i.imgur.com/F3x3Oot.gif)


2015-04-07 15:52 GMT+02:00 Luke Church <notifications@github.com>:

> Funny - I've just run into this in Editor.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2978182/7024534/80b0d622-dd35-11e4-911d-4c13fb1525c0.png>
>
> Are multiple lines really that bad? If you've prototyped it could you post
> a screenshot? I can't imagine wanting to scroll though this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-pad/issues/279#issuecomment-90560468>.
>



-- 
Kasper

**Comment by lukechurch** [comment]
I like this much better
