### ISSUE TITLE
Handle old UI routes or redirect

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2794]
The old UI has a variety of entry points, and on the preview UI, they end up on a "Page not found" route. For these old routes, we should add special handling for them, so embeds and other references to them don't break. For example, the Flutter API docs use https://dartpad.dev/embed-flutter.html

We could handle this in the UI or with a redirect in Firebase.

- `embed-dart.html`
- `embed-flutter.html`
- `embed-html.html`
- `embed-inline.html`
- `embed-flutter_showcase.html` (Less important as never fully supported)
- `workshops.html` - Should maybe redirect to explanation about workshop removal?

This handling for the embed entry points should consider adding the `embed=true` query parameter.

While not necessary, an improved 404/"Page not found" route might be worthwhile :)

**Comment by parlough** [comment]
\cc @johnpryan For your thoughts, as this will be necessary so DartPad embeds in previous versions of the Flutter API docs continue to work.

**Comment by johnpryan** [comment]
Let's see if we can configure this in our Firebase Hosting file, but a GoRouter redirect would probably work too.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/dart-pad/commit/d645c1c17ab18746926504c468746cf7b037a721

Thanks!
