### ISSUE TITLE
Returns wrong hexadecimal using toRadixString(16).

### ISSUE THREAD

**Issue by maykonds** [dart-lang/dart-pad#2795]
## What happened?

When parse string "80666512367470025" to hexadecimal, returns the "11e95c3feeec5**d0**" hexadecimal that is wrong. The correct hexadecimal should be "11e95c3feeec5**c9**".

![image](https://github.com/dart-lang/dart-pad/assets/56980020/6008501b-ff92-44ba-9121-c784277a8c4a)

In Flutter, returns the correct hexadecimal:

![image](https://github.com/dart-lang/dart-pad/assets/56980020/9b3c4630-a970-40b9-a774-395fc2126573)

## Steps to reproduce problem

Run the code in the dartpad.dev:

```dart
var hex = int.parse('80666512367470025').toRadixString(16);
print(hex);
```

### Browser

Browser: Sidekick

Version: 118.56.1.37228

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

- Yes the native Ad Blocker from Sidekick.

Are there any warnings or errors in your browser's JavaScript console?

- No errors or warnings.

### Machine

Operating system: Linux Mint 
Version: 21.2 x86_64
Kernel: 5.15.0-91-generic

**Comment by maykonds** [comment]
Searching, I was able to find the reason:

"If the number is large enough, it may exceed the default precision of JavaScript for integers. In JavaScript, numbers are represented as 64-bit double-precision floating-point numbers, and this can lead to loss of precision in very large numbers."

Using the ```'dart:typed_data'``` library, my problem was solved with the code:
```dart
BigInt.parse('80666512367470025').toRadixString(16);
```

**Comment by parlough** [comment]
Thanks for the issue and for the update!

You're correct that numbers do have a unique behavior on the web.

There is a full document on this, [Numbers in Dart](https://dart.dev/guides/language/numbers), if you're interested in learning more about how behavior is different between native platforms and the web(JS) :)
