### ISSUE TITLE
Try out the next version of DartPad!

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2808]
A new version of DartPad is available to try at [preview.dartpad.dev](http://preview.dartpad.dev/)! This is a fully new client built using Flutter, and it will replace the current very soon, and we'd love to get your feedback.

In order to reduce the cost of maintaining DartPad we're removing a few features that you may be using:
- **Workshops** - DartPad workshops are a way to write step-by-step instructional content in DartPad. This feature will be unsupported in the new DartPad client. To migrate your DartPad workshops, we recommend using embedded DartPads with Gists by following the [Embedding Guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide).
- **GitHub authentication** - You won't be able to log in to GitHub from DartPad in the new version. To share Dart snippets you can continue using GitHub Gists by following the [Sharing Guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide).
- **Firebase support** - We are no longer supporting snippets that import Firebase libraries such as firebase_core or firebase_auth.
- **Test / Solution features** - If you are using embedded DartPads with test / solution features you will need to migrate your Gists to be a single main.dart file.
- **HTML / CSS support** - Gists that use  index.html and styles.css will no longer be supported, Dart snippets and Flutter snippets are the only two types of snippets that will be supported going forward.

We're excited to share the next iteration of DartPad with you, so go ahead and give it a try and let us know what you think by commenting on this issue or [filing a new issue](https://github.com/dart-lang/dart-pad/issues). Thanks!

**Comment by miyoyo** [comment]
Why is it flutter web?

**Comment by parlough** [comment]
@yjbanov Wasn't there an issue with some browsers having upside down rendering? Was it solved by checking the browser vendor? If so, could the detection being off be the of cause of [this](https://github.com/dart-lang/dart-pad/issues/2808#issuecomment-1944141873)?

**Comment by johnpryan** [comment]
We've officially launched the new UI, so I'm closing this issue now. Please file a new issue if you are experiencing problems with DartPad!

**Comment by sebastianhaberey** [comment]
Great news! Cheers for the new UI and its light mode 🎉 🎉 🎉
