### ISSUE TITLE
Reload clears editor

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#2817]
When editing in the new DartPad, if you press `ctrl R` (which I did at least once hoping it would run the program),
it reloads the page. 
This clears the editor and loses the content. 
There is no undo, no "back" navigation, generally no way to restore the content, it's just gone.

The old DartPad keeps the content when you reload (and when you open a new DartPad tab).
That's a better, and safer, user experience.

## Steps to reproduce problem

Write code. Press Ctrl+R.

### Browser

Google Chrome
Version 121.0.6167.161 (Official Build) (64-bit)

**Comment by parlough** [comment]
Support for saving the most recent edit wasn't transitioned over. I think it's valuable though, especially considering reloading or other issues or mistakes.

Thanks for noting this and how fixing this would result in a safer user experience!

I'll close this in favor of https://github.com/dart-lang/dart-pad/issues/2871 which tracks implementing support for some form of snippet saving. Thanks!
