### ISSUE TITLE
www.dartpad.dev gives Error: Page not found

### ISSUE THREAD

**Issue by julemand101** [dart-lang/dart-pad#2823]
## What happened?

Visiting https://www.dartpad.dev/ gives the following error page:
```lang-none
Error: Page not found
The requested URL was not found on this server.
```

## Steps to reproduce problem

Go to: [https://www.dartpad.dev/](https://www.dartpad.dev/)

## Additional info

If using [https://dartpad.dev](https://dartpad.dev) it works fine.

**Comment by parlough** [comment]
Closing in favor of tracking alongside https://github.com/dart-lang/dart-pad/issues/2638
