### ISSUE TITLE
Fix lint warnings on go_router example

### ISSUE THREAD

**Issue by kelvinwieth** [dart-lang/dart-pad#2827]
The [go_router example](https://dartpad.dev/?id=4a546fc44db8aca351bfe791e251acc2) from the drop down menu, found at https://gist.github.com/flutterdevrelgists/4a546fc44db8aca351bfe791e251acc2, comes with a bunch of lint warnings.

## Screenshot

<img width="1723" alt="image" src="https://github.com/dart-lang/dart-pad/assets/79933699/7d16d7fc-cfb2-4675-8d28-544cb87d6dc9">

**Comment by parlough** [comment]
Thanks for the report! We've decided to retire the current `package:go_router` sample for now, but will look to bring back a new sample that showcases its features in the future. If you have any ideas, please let us know! Thanks again :)
