### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by moonasoltanieh** [dart-lang/dart-pad#2833]
when i try to output i get the following error

Error compiling to JavaScript:
ClientException: XMLHttpRequest error., uri=https://stable.api.dartpad.dev/api/v3/compile

**Comment by devoncarew** [comment]
It looks like the client is not able to reach the backend. Can you check the devtools log to see if there are any exceptions? Or, try hitting the https://stable.api.dartpad.dev/api/v3/version url yourself directly?
