### ISSUE TITLE
add more right padding to the 'run' button

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2840]
With the updates to the codemirror scrollbars, we should add slightly more right padding to the run button:

<img width="231" alt="Screenshot 2024-02-15 at 11 18 32 AM" src="https://github.com/dart-lang/dart-pad/assets/1269969/3fed3594-d8c7-440e-8e65-e1615b71aa9e">

**Comment by RishiMaersk** [comment]
Hi can I work on this issue ?

**Comment by devoncarew** [comment]
For sure! I suspect we already have some padding around the container for the run and format button, so this issue is probably about adding enough additional padding on the right so the buttons look good in relation to the new scrollbar position.

**Comment by RishiMaersk** [comment]
how do we reproduce this issue ?

**Comment by devoncarew** [comment]
You can run the UI locally using this instructions: https://github.com/dart-lang/dart-pad/tree/main/pkgs/sketch_pad#how-to-run
