### ISSUE TITLE
No discoverable keyboard shortcut to "Auto-format"

### ISSUE THREAD

**Issue by nullskill** [dart-lang/dart-pad#2848]
There was a certain shortcut for autoformatting the code in the code pane of Dartpad. But there's no in the current updated Dartpad. It would be nice to get it back. Thanks!

**Comment by devoncarew** [comment]
It's an action button next to the run button:

<img width="233" alt="Screenshot 2024-02-16 at 8 48 22 AM" src="https://github.com/dart-lang/dart-pad/assets/1269969/8705ac23-65d5-426b-a900-7a373b79b14e">

Please let us know if that is not showing up for you.
