### ISSUE TITLE
Previous Features Not Working

### ISSUE THREAD

**Issue by thulotechnology** [dart-lang/dart-pad#2851]
I'm incorporating DartPad on my website, https://dart-tutorial.com/, to provide an option for running code online.

Here's a direct link to my website where I'm using DartPad: https://dart-tutorial.com/introduction-and-basics/basic-dart-program/.

Until yesterday, accessing DartPad through this link https://dartpad.dev/?id=8f1ff637d97741a51fd5e069d86cc50b was functioning correctly. However, it stopped working today, presumably due to an update to DartPad.

With over 130,000 monthly visitors to my site, it's crucial to resolve this issue promptly. Any assistance to fix this as soon as possible would be greatly appreciated.

**Comment by devoncarew** [comment]
From looking at one of your gists it looks like the file in it is titled `'nullsafe0.dart'`. It may have been an unintentional feature of dartpad to support files w/ any name. The format we expect for gists is to use `'main.dart'` for the dart source name (see https://github.com/dart-lang/dart-pad/blob/main/pkgs/sketch_pad/lib/gists.dart#L84).
