### ISSUE TITLE
codemirror contents not initially displaying when the dartpad UI is created off-screen

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2854]
I see this consistently with embedded dartpads when the dartpad are created off-screen (below the fold). See for example https://api.flutter.dev/flutter/material/AppBar-class.html.

I suspect that the codemirror instance is not getting sized correctly - that it may have something like a zero-height. The first interaction with the codemirror instance - like clicking in the editor - will the show the editor content.

Here's a screen shot showing a blank editor (and a very short scroll-bar for the content):

<img width="221" alt="Screenshot 2024-02-16 at 11 24 12 AM" src="https://github.com/dart-lang/dart-pad/assets/1269969/33ceec85-4528-4123-b786-40373e11d3bf">

**Comment by ditman** [comment]
+1 Maybe related?

* https://stackoverflow.com/questions/8349571/codemirror-editor-is-not-loading-content-until-clicked
