### ISSUE TITLE
Running sample fails if starting in mobile layout

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2859]
Visit a page like https://api.flutter.dev/flutter/material/ActionChip-class.html in a narrow browser window and notice an error in the console. You can also see the same error by running manually.

If you open the "UI output" tab and rerun, it does work.

**Comment by devoncarew** [comment]
I believe that the execution iframe isn't being created until the 'UI Output' tab has been visited. Perhaps we need to create the tabs eagerly (or otherwise just always create the execution iframe).

```
main.dart.js:5107 Uncaught TypeError: Cannot read properties of null (reading 'postMessage')
    at Object.aK1 (main.dart.js:27836:9)
    at main.dart.js:87170:3
    ...
```
