### ISSUE TITLE
No "Documentation" window when clicking on functions/methods

### ISSUE THREAD

**Issue by rubenferreira97** [dart-lang/dart-pad#2860]
Previous DartPad version had this extremely useful functionality.

Got and old image from Google showing the documentation window when clicking on the `print` function.

![image](https://github.com/dart-lang/dart-pad/assets/43851289/bc578a68-a8eb-4d85-81c9-f32e3bb851a6)

**Comment by chemsou00** [comment]
Yeh please return it

**Comment by devoncarew** [comment]
Addressed in https://github.com/dart-lang/dart-pad/pull/2929.
