### ISSUE TITLE
Focus must be moved manually to try the Flame sample game

### ISSUE THREAD

**Issue by osaxma** [dart-lang/dart-pad#2864]
When running the flame game example, the arrows do not work unless I click on the game to move the focus there.

To reproduce:
- Head to dartpad.dev
- Select flame sample
- Run the app
- Try using the arrows to play

I think the focus should move automatically to the app window after hitting Run.

**Comment by johnpryan** [comment]
This would lose focus on the editor, which is probably not what most users want. I'm going to close this unless there's a strong reason to change the current behavior. Thanks for filing an issue though!
