### ISSUE TITLE
Console output at the top cannot be selected/automatically scrolls down when output requires a scrollbar

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/dart-pad#2867]
## What happened?

I want to select something from the top of the console, but as soon as I click in the console view it scrolls down to the bottom making it impossible to copy/paste from the console output.

![dartpad_scroll](https://github.com/dart-lang/dart-pad/assets/1937607/03f5ec4e-c2b7-40fb-8ca8-5b653bb81a02)

## Steps to reproduce problem

Run

```dart
void main() {
  for (var i = 0; i < 200; i++) {
    print('Hello World $i');
  }
}
```

and try to copy the first few lines of the output.

### Browser

* Firefox 123.0 (64-bit) and 
* Chrome 122.0.6261.58 (Official Build) (64-bit)

**Comment by parlough** [comment]
Thanks for the report and trying in different browsers. I can reproduce the issue still as well.

Closing in favor of https://github.com/dart-lang/dart-pad/issues/2931 which also discusses the issue.
