### ISSUE TITLE
Code assistance context menu is missing

### ISSUE THREAD

**Issue by math1man** [dart-lang/dart-pad#2868]
## What happened?

DartPad appears to have been updated in a major way. I noticed that following the update, the code assistance context menu for Flutter (with commands like "Wrap in SizedBox", "Remove widget", "Swap with parent", etc) is no longer accessible.

## Steps to reproduce problem

Open DartPad, switch to a Flutter sample, position the cursor on a widget constructor and press Opt-Enter (for Mac, may vary by OS).

### Browser

Browser: Chrome

Version: 121.0.6167.160

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console? No

### Machine

Operating system: MacOS

Version: Sonoma 14.3.1

**Comment by math1man** [comment]
It works similarly in [VS Code](https://docs.flutter.dev/tools/vs-code#editing-tips-for-flutter-code) and [AndroidStudio](https://docs.flutter.dev/tools/android-studio#editing-tips-for-flutter-code) when using the Flutter plugins.

**Comment by devoncarew** [comment]
I think the issue is that keybinding changed - it's now `command-.` (visible from the keybindings shortcut action in the bottom left).

<img width="248" alt="Screenshot 2024-02-21 at 12 15 51 PM" src="https://github.com/dart-lang/dart-pad/assets/1269969/38a092bf-07f1-42f8-8d5c-4c93b075592d">

It may be that we should alias the keyboard shortcut?

**Comment by math1man** [comment]
Oh interesting. I guess this changed from the AndroidStudio key binding to the VS Code keybinding. It would be much appreciated if you could support both!

**Comment by mit-mit** [comment]
> It works similarly in [VS Code](https://docs.flutter.dev/tools/vs-code#editing-tips-for-flutter-code) and [AndroidStudio](https://docs.flutter.dev/tools/android-studio#editing-tips-for-flutter-code) when using the Flutter plugins.

Right, but one big difference is that they show a small UI element (in code it's a lightbulb) to let the user know that this menu exists. I've love to see something similar in DartPad.

**Comment by math1man** [comment]
That's true.
