### ISSUE TITLE
DartPad no longer retains state when closing and reopening it.

### ISSUE THREAD

**Issue by math1man** [dart-lang/dart-pad#2869]
## What happened?

DartPad used to remember the most recent code snippet I had entered, even when closing and reopening the tab. It has stopped doing this, which is minorly inconvenient.

## Steps to reproduce problem

1. Open Dartpad
2. Enter some custom script
3. Close Dartpad tab/window
4. Open a new Dartpad tab/window

### Browser

Browser: Chrome

Version: 121.0.6167.160

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? No

Are there any warnings or errors in your browser's JavaScript console? No

### Machine

Operating system: MacOS

Version: Sonoma 14.3.1

**Comment by parlough** [comment]
Thanks for opening an issue about this! It seems to be one of the most commonly raised differences, and I agree that it is a bit inconvenient. As Lasse noted in https://github.com/dart-lang/dart-pad/issues/2817, there are some other user experience concerns that arise from the missing functionality.

I'll close this in favor of https://github.com/dart-lang/dart-pad/issues/2871 which tracks implementing support for some form of automatic-snippet saving. Thanks again :)
