### ISSUE TITLE
server device detect

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#287]
We need to look at doing server detect and routing. So, when a page (say `dartpad.dartlang.org/1234567890abcdef`) is requested by a mobile device, we should serve back `/mobile.html`. When requested by a desktop device, we should serve back `/index.html`. Currently we always route to `/index.html` regardless of the device.

**Comment by devoncarew** [comment]
Implemented.

@lukechurch, do you know if we have the ability to discriminate between smaller tablets and larger ones? With phones and small tablets, we definitely want the mobile UI. I think with large tablets, we'd be better off using the desktop UI.

Not a critical thing to address though; tablets are currently just slightly less than 5% of our traffic.

**Comment by lukechurch** [comment]
@devoncarew I think we do have that capability. I tested it a bit on a Nexus 9 and in landscape mode the desktop UI still felt pretty poor due to the keyboard.

I suggest we revisit after the UI redux?

**Comment by devoncarew** [comment]
sounds good
