### ISSUE TITLE
multiplication in double

### ISSUE THREAD

**Issue by R2D77** [dart-lang/dart-pad#2872]
```
void main() {
  double a = 71.1;
  print(a);
  
  double b = a * 100;
  print(b);
}

```

result:

```
71.1
7109.999999999999
```

why??

**Comment by osaxma** [comment]
This isn't an issue with Dart/DartPad -- this is normal behavior with double-precision floating point numbers in most languages that adheres to IEEE 745 specifications which includes Dart.  You can try it in python, java, or javascript and you'd get the same result.

See this SO answer if you're interested in more details: https://stackoverflow.com/a/588014/10976714
