### ISSUE TITLE
Errors are not reported properly to the console

### ISSUE THREAD

**Issue by LewisHolliday** [dart-lang/dart-pad#2876]
https://dartpad.dev/

This does not print anything to the console on chrome or firefox:
```dart
void main() async {
  throw 'test';
}
```
---
This prints 'Script error.' on chrome, and on firefox prints 'Error: test, error: Error: test':
```dart
void main() {
  throw 'test';
}
```
Related issue: https://github.com/dart-lang/dart-pad/issues/2742

**Comment by parlough** [comment]
Thanks for the report and details!

I'm going to close this in favor of tracking this and other similar exception/error surfacing issues in https://github.com/dart-lang/dart-pad/issues/3008. Thanks again :)
