### ISSUE TITLE
Allow all the official SDK companion packages.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#2882]
The allowed packages does not contain all the Dart-team owned SDK companion packages for the core platform libraries. It's missing:
* `package:async`
* `package:convert`
* `package:typed_data`

(The `package:collection` package is allowed, so that's good.)

I think DartPad should allow these packages. The features they contain are the recommended solution to some problems, and it's nice to be able to link to an example in DartPad.

(Even if `package:typed_data` isn't used as much as the other two, I think it would still be a good idea to include it.)

**Comment by parlough** [comment]
Makes sense! They're already included transitively anyway - https://github.com/dart-lang/dart-pad/pull/2883 :)
