### ISSUE TITLE
Before this version of the dart sdk it used to work like a charm now totally sucks

### ISSUE THREAD

**Issue by Vaibhav77e** [dart-lang/dart-pad#2889]

**Comment by devoncarew** [comment]
@Vaibhav77e, this comment is a violation of our [code of conduct](https://dart.dev/community/code-of-conduct). We expect all communications to be kind, courteous, and welcoming. If you have specific feedback, you can open new issues.

**Comment by Vaibhav77e** [comment]
Am really sorry for my manner what I have did before . I unknowingly broke
your code of conduct am really sorry for that. Hope you understand and
forgive me. I really love dart pad and flutter.

Thank you
