### ISSUE TITLE
swap the position of the iframe and the console output

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#289]
So, console/documentation on top, and the iframe on the bottom? This will make the starting sample (just dart code, no dom) make a bit more sense. Also, having the docs on the top seems more natural when coding and referring to them a lot.

**Comment by kasperpeulen** [comment]
I would say that if there is no dom, we may want to have the doc on top and the console in the bottom (and no iframe). 

I have no strong opinion about where to place it if there is a dom.

**Comment by devoncarew** [comment]
+1 to some sort of reconfiguring, possibly dynamic based on the content in the gist.

We may want to wait to do that until we have a component wrapper for tabs / a tab control. It'll let the code be more maintainable.

**Comment by sethladd** [comment]
I would love docs on the bottom, console output on the top. Unless we see that the majority of users go for pads + HTML, optimizing for the default case makes sense.

**Comment by lukechurch** [comment]
I agree with Seth here - I'd really like that I think. I find having to switch between the documentation and the output somewhat frustrating.

Could we have:

Console + HTML as two tabs in the top area
Docs in the bottom area

And we can do the dynamic thing further down the line when the code will be easier to maintain?

**Comment by devoncarew** [comment]
I think we will have to automatically switch between output types (DOM vs console) when the user hits run when we do this refactor, otherwise the user might have no idea that there was any DOM output.

Possibly also change the `Console` and `Results (DOM)` tab title's from disabled-looking to a normal font, when the tab's contents go from empty to non-empty. So the `Console` tab title starts as muted/gray. If the app write to the console, the tab title will change its appearance to indicate that the tab now has contents.

**Comment by devoncarew** [comment]
@kasperpeulen, is this something you could take a look at? Brainstorming on this:

Sounds like we'll want "Console / Html Results" on the top, and "Documentation" on the bottom. We'll need to try and auto-show the right tab (either console or 'html results'). This may best be done by inferring that the user will want dom output if the html file is not empty (has a non-ws char). Also, it seems like documentation will always be active. Not sure how that'll play out wrt performance; I want to make sure we don't send too many http requests to the backend. As in, we'd want to very that just typing chars doesn't send a blizzard of documentation requests.

**Comment by devoncarew** [comment]
@kasperpeulen @lukechurch @sethladd 

I pushed Kasper's changes to http://dev.dart-pad.appspot.com/ - this puts the `Results` and the `Console` in the same tab area and the documentation below. Please give it a test drive.

**Comment by sethladd** [comment]
Wow, looks great!

**Comment by devoncarew** [comment]
Done - thanks @kasperpeulen!
