### ISSUE TITLE
DartPad inject script sometimes fails

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2893]
When I was testing https://github.com/dart-lang/site-www/pull/5627#event-12042417555 I noticed that some of the DartPad embeds are displaying the default snippet. We might need to listen for these events right away, instead of when the `Editor` widget is created (https://github.com/dart-lang/dart-pad/pull/2858/)

**Comment by parlough** [comment]
Taking a look at this, I think it's perhaps not listening to the event too late, but not distinguishing between the embeds on the page for which sent the "reader" message. I'll investigate adding a way to distinguish between them.
