### ISSUE TITLE
In dart pad, operator '/' works differently with Dart document

### ISSUE THREAD

**Issue by hoogom88** [dart-lang/dart-pad#2894]
According to [Dart document](https://api.dart.dev/stable/3.3.0/dart-core/int-class.html), **return type of int operator '/' is double**.
And I was able to check the actual return type and value through the IDE which is same as document.
```dart
void main() {
  int ten = 10;
  int three = 3;
  int two = 2;
  var result1 = ten / two;
  var result2 = ten / three;
  print("type: ${result1.runtimeType}, value: ${result1}");
  print("type: ${result2.runtimeType}, value: ${result2}");
}
// output
// type: double, value: 5.0
// type: double, value: 3.3333333333333335
```
Actually, It is not allowed to assign result of operator '/' in int.
 `int result = 10 / 2;` => Error: A value of type 'double' can't be assigned to a variable of type 'int'

However, dart pad **return int rather than double** when operator's result is divided exactly without the rest

![image](https://github.com/dart-lang/dart-pad/assets/67893559/65c86e4d-5e0f-4ba8-997d-b4da0a7b20f6)

Is there any other reason for this, or am i miss something?

**Comment by eernstg** [comment]
Please check out this page: https://dart.dev/guides/language/numbers.

The main point is that Dart uses js numbers when running in a configuration where the source code is translated to a JavaScript program (that is, on the web except dart2wasm). With js numbers, every whole number has the type `int` (and every number whatsoever has the type `double`). So you get true if you test whether `(10 / 2) is double` and also whether `(10 / 2) is int`.

**Comment by parlough** [comment]
Thanks for the issue and discussion here!

I'm going to close this issue as it is expected. https://dart.dev/guides/language/numbers is definitely the best resource here, but let us on know at https://github.com/dart-lang/site-www/issues if there's any confusion on the page.

Thanks again :D
