### ISSUE TITLE
Cannot repeat key by holding down

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dart-pad#2896]
Instead a "letter variant" pop-up shows up.
This feels very unexpected.

Maybe a setting in the app that has to switch from mobile behavior to web behavior.

Screenshot:
<img width="628" alt="image" src="https://github.com/dart-lang/dart-pad/assets/8613953/c7c59c08-902b-4f18-ac97-139884be62e0">

**Comment by parlough** [comment]
I think this is just a behavior of macOS rather than something we're configuring or implementing. Are you seeing different behavior on different websites or editors?

**Comment by sigurdm** [comment]
Ah - sorry no - 🤦 - never noticed this before. Thought it was a flutter thing
