### ISSUE TITLE
add sass_api to supported package list

### ISSUE THREAD

**Issue by Goodwine** [dart-lang/dart-pad#2898]
The `csslib` package used in DartPad is unmaintained. I propose replacing it with the actively supported `sass` and `sass_api` packages. These alternatives provide modern CSS parsing with the additional benefit of supporting Sass.

**Comment by parlough** [comment]
We don't support use of `package:csslib` in DartPad. Did you see somewhere that says so or where it is used?

As for the sass packages, do you have any particular use in mind for them?

**Comment by parlough** [comment]
I'm going to close this as stale as it's not clear this package will be of large use to the simple Dart and Flutter snippets that DartPad is focused on supporting.

Thanks for the suggestion though! And if you still see the sass related packages as worth supporting, please let us know with some more details about the intended use case.
