### ISSUE TITLE
Pressing Tab binds Space key to bring up a submenu

### ISSUE THREAD

**Issue by thumbert** [dart-lang/dart-pad#2899]
## What happened?
DartPad editor becomes unusable

## Steps to reproduce problem
Go to [https://dartpad.dev/?null_safety=true](https://dartpad.dev/?null_safety=true) press Tab key anywhere in the editor.  
After that, the Spacebar key will trigger a submenu instead of typing a space.  It becomes totally impossible to 
edit anything.  

### Browser

Browser:  Chrome Version 122.0.6261.128 (Official Build) (64-bit)

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?
No

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:
No

**Comment by parlough** [comment]
Sorry about this current issue and thanks for reporting it!

I'm going to close this issue in favor of https://github.com/dart-lang/dart-pad/issues/2852 where we're tracking the problem.
