### ISSUE TITLE
Find not implemented

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dart-pad#2905]
To reproduce: Press Ctrl+F/Cmd+F in the text pane.

<img width="706" alt="image" src="https://github.com/dart-lang/dart-pad/assets/8613953/0efa3da8-fbb1-42ce-bd08-d1c3ceefab23">

**Comment by parlough** [comment]
Thanks for the issue. Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/2904 :)
