### ISSUE TITLE
implement new platforms for DartPad (windows, linux and macos)

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/dart-pad#2906]
I recently read the announcement on [Twitter](https://x.com/FlutterDev/status/1769800942361149869?s=20) that dartpad was migrated to flutter and I want to congratulate the flutter team for the excellent work they are doing.

Now that the most difficult work has been done, I propose to incorporate the Linux, Mac and Windows desktop platforms. This is now possible since DartPad was migrated to Flutter.

After the new platforms are developed, the next thing is to publish DartPad in the Microsoft Store, in the App Store and the Snap Store so that DartPad is usable by more people.

Why is doing this important, you might ask? The idea is to demonstrate that Flutter is a reliable technology, since Google has its own product made with Flutter and deployed on multiple platforms. As a business consultant, I can use DartPad as an example to convince companies to invest in new products using Dart and Flutter because if Google has products in production made with Flutter on multiple platforms, that is the basis for trust.

The other important thing is the development process that will be carried out, in this process there will surely be challenges to solve, but it is the perfect opportunity to find the weak points of the technology, then we will be able to know where we need to improve so that we can move on from the utopia of the multiplatform to a real thing with products made in flutter deployed in production in multiple application stores

DartPad is the perfect product to use as an experiment, to polish products deployed in production in multiple app stores

**Comment by parlough** [comment]
Thanks for the suggestion and the congratulations!

For now, we're unlikely to publish DartPad on other platforms. We still rely on a JS package (CodeMirror) for the underlying text editor. If that changes in the future, perhaps we'll revisit this.

If you'd like to develop Flutter apps online consider an online IDE like [Project IDX](https://idx.dev/) which has first-class support for Flutter or other environments like [GitHub Codespaces](https://github.com/features/codespaces).

Thanks again!
