### ISSUE TITLE
Keyboard Spacewave Problem on Android Phone

### ISSUE THREAD

**Issue by applr0327** [dart-lang/dart-pad#2911]
There's no problem with the Android phone, but if you connect the Kibo and press Spacewave, it won't be released

**Comment by parlough** [comment]
Hi @applr0327, thanks for opening an issue!

Could you provide some more details on what "Kibo" and "Spacewave" are and how they relate to [DartPad](https://dartpad.dev/). That will help us determine if/how we can resolve the issue. Thanks again :D
