### ISSUE TITLE
Integration with VsCode & Polyglot

### ISSUE THREAD

**Issue by JCzz** [dart-lang/dart-pad#2928]
Hi there

Any chance this could be integrated into VsCode Polyglot: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode

Regards
Christian

**Comment by parlough** [comment]
Thanks for the issue! However, I'm not sure this is the best repository for the request. This repository is for the [DartPad online Dart playground](https://dartpad.dev/). 

I'm not sure what the requirements are for supporting Polyglot Notebooks as I'm not familiar with the project, but it seems like .NET Interactive needs to implement or use (Jupyter?) sub kernels for the various languages. I'm not sure what that looks like, so your best bet is likely to visit their [issue tracker](https://github.com/dotnet/interactive/issues) with your request.

But, do let us know if you think there is more Dart or DartPad need to do here. Thanks again!
