### ISSUE TITLE
completion sometimes get sooner closed than it is visible

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#293]
Okay this some major annoyance I have when I enable "auto" autocompletion. This is I think best illustrated with a gif:

![](http://g.recordit.co/ubRdTxuBDe.gif)

It seems like that the codemirror close action is fired earlier then that the popup is actually visible. I guess  that is what causing this. This example may seem a bit synthetic, but if you type fast, this happens quite too often.

Any suggestions how I could solve this ? @devoncarew

**Comment by kasperpeulen** [comment]
This seems to be really an codemirror issue, I can fix this in the js file. Shall I try to get a fix upstream ?

**Comment by devoncarew** [comment]
Fixing it upstream would be great. We may be seeing more issues with code completion than other languages; our hints provider has some latency (round trip to the server); I think the other integrations are largely in process, and working on a fairly small set of available tokens.

**Comment by kasperpeulen** [comment]
@devoncarew This would be solved with this patch https://github.com/codemirror/CodeMirror/commit/0a83a4ba43fd1191a48fec1507c3db6d18570de6

**Comment by devoncarew** [comment]
@kasperpeulen, can you verify that the new version of codemirror.dart fixes this issue? Thanks!

**Comment by kasperpeulen** [comment]
yup, seems to be fixed now :)
