### ISSUE TITLE
Can't copy from compiler error output

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#2931]
## What happened?

I wrote a program with compilation errors.
I tried to copy one of the errors.
The moment I clicked in the lower-right area where compilation errors are printed, the text area scrolled to the bottom.
I got the selection start placed, so I tried to at least move the cursor back up to where I wanted the selection to end,
but the text are kept scrolling to the bottom.

## Steps to reproduce problem

Have program with multiple errors. Fx:
```dart
void main() {
  int x = "a";
  int y = "b";
  int z = "c";
}
```

Try to select and copy the first error message in the compiler output:
```
main.dart:2:11: Error: A value of type 'String' can't be assigned to a variable of type 'int'.
  int x = "a";
          ^
```
Good luck!

Please do not auto-move a text area that has focus. The user might want to be looking at the point they're at, or select from it.

### Browser

Browser:  Google Chrome	

Version:  123.0.6312.122 (Official Build) (64-bit) 

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No. (Corp Linux laptop, no unusual extensions).

Are there any warnings or errors in your browser's JavaScript console?

Nothing related to the issue, which is UI/UX.
(The failure to compile was reported as a bad POST message.)

### Machine

Operating system: Linux

Version: Debian 6.6.15-2rodete2 (2024-03-19)

### Your code

```dart
void main() {
  int x = "a";
  int y = "b";
  int z = "c";
}
```

### DartPad's output

Did DartPad print anything to the console pane? 
No

**Comment by eernstg** [comment]
Good catch! I've seen similar things, but didn't get around to report it. Workaround for now: Select the pane by clicking anywhere inside that area, 'Select All' (⌘-A, Control-A), paste the resulting text, delete anything which is not needed.

**Comment by lrhn** [comment]
Yep. That was how I got the error message to paste into this issue. After trying ... several other things.
