### ISSUE TITLE
Requesting option for switching to Legacy DartPad

### ISSUE THREAD

**Issue by s4nk37** [dart-lang/dart-pad#2932]
I'm experiencing performance issues with Sketch_pad. It feels slow and unresponsive when I use it.

**Comment by parlough** [comment]
Thanks for opening an issue @s4nk37. Would you mind opening specific issues for the issues you're seeing with the new frontend, including system and browser details? That way we can address the performance issues if possible. In terms of the old UI, refer to https://github.com/dart-lang/dart-pad/issues/2892. Thanks again!
