### ISSUE TITLE
Doesn't show response

### ISSUE THREAD

**Issue by mohadel92** [dart-lang/dart-pad#2939]
The  latest version of dart pad doesn't show any output only if i try to run any simple code multiple times

to reproduce:
1- type any simple code
2- click run
3- it loads but doesn't show any result

Browser
Chrome for mac Version 124.0.6367.79 (Official Build) (x86_64)

Operating system:
Mac OS X Monterey 12.7.2

**Comment by johnpryan** [comment]
Thanks for filing an issue! I can't reproduce this, could you open up the JS console and see if there are any console or network exceptions?
