### ISSUE TITLE
Discovery overlay for keyboard shortcuts and settings

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#295]
I'd like an overlay that appears over the application with short-cuts, 'cheat codes', and settings in them so we can expand the UI features without adding more chrome to the basic model.

A little similar in spirit to ? in Gmail/Chromebook.

Lets start by when you press Ctrl + ? you get an overlay over the both 85% of the window with a list of the currently supported keyboard shortcuts.

Long term, it would be nice to have the overlay have the potential of interaction, so lets not choose anything that blocks that.

@kasperpeulen

**Comment by devoncarew** [comment]
Done by @kasperpeulen.
