### ISSUE TITLE
Dartpad stops redrawing on Chrome <=110

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dart-pad#2958]
I'm not able to transfer issues from flutter/flutter here, but someone filed this: https://github.com/flutter/flutter/issues/146431.

There's nothing obvious in the console, and other Flutter Web apps render fine in Chrome 110, so "moving" the issue here for investigation by the Dartpad team, if Chrome <=110 is important.

**Comment by johnpryan** [comment]
We don't have plans to support old versions of Chrome, so I'm going to close this for now.
