### ISSUE TITLE
Dartpad is sigificantly slowed for latest update. 

### ISSUE THREAD

**Issue by garawaa** [dart-lang/dart-pad#2979]
I tried same code with latest update of dartpad. but it seems slower than oldest version. It is tooooooooooooooooooooo slow. Still did not fix this problem!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by garawaa** [comment]
some browser gives exception like:
Error: Load timeout for modules: flutter_web
https://requirejs.org/docs/errors.html#timeout, error: Error: Load timeout for modules: flutter_web
https://requirejs.org/docs/errors.html#timeout

**Comment by johnpryan** [comment]
Can you share any errors or timing information you are seeing in the developer console? Are you running in Chrome?
