### ISSUE TITLE
refactor dartdoc panel location and behavior

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#2999]
From user feedback, the current behavior of the dartdoc panel can interfere with editing the snippet:

- on a click from a user on a symbol, the panel appears below the editing area; this re-sizes the editor and text locations can appear to jump for users
- clicking on blank space will hide the dartdoc panel; this also resizes the editor

Here are some possible refactorings of the UI:

**have the dartdoc panel appear in a fixed location, floating over the editing area**
- this might dock on the bottom of the editor, indented ~20 px left, bottom, and right
- the editor would not resize
- the dartdoc panel might obscure some content

**have the dartdoc panel only show when double clicking a symbol**
- there would be less unintentional invocations of the dartdoc panel
- there would be less discovery of how to show docs

**have a 'toggle doc' button on the bottom status bar**
- a user would hit the toggle to show the dartdoc area
- single clicking on symbols would update the contents of the panel
- clicking again on the 'toggle docs' button would hide the panel

**Comment by johnpryan** [comment]
Giving more control to the user is probably a good guiding principle here, so I'm leaning toward option 3   We could also try to see if option 1 is an improvement, but that could be done separately. Option 2 seems a little hard for the average person to intuit, but maybe we could make alt-clicking on a symbol enable the panel.
