### ISSUE TITLE
docs link to element instead of the library

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#300]
When hitting F1 for the `print` function, I see this:

![screen shot 2015-04-09 at 8 58 51 am](https://cloud.githubusercontent.com/assets/1269969/7070887/afe7b138-de96-11e4-88b3-451f9e2584c0.png)

The last link says "Library `dart:core`"; the hyperlink itself actually points to `dart:core print`. I think we should point to the library and not the element as that's what the label indicates it does.

**Comment by kasperpeulen** [comment]
@devoncarew 
see this issue at the bottom:
https://github.com/dart-lang/dart-pad/issues/241

I was not sure how to do this, origanally I did it like this:
![](https://cloud.githubusercontent.com/assets/1035299/6971077/3c1e8946-d97a-11e4-9ca4-871a00dba9eb.png)

We could also maybe go for the orginal intend of lukechurch:

> An icon like the rectangle with an arrow emerging from it, at the top right hand side of the doc panel that enabled you to open the current documentation

**Comment by devoncarew** [comment]
Resolution is to change the link to "Open external docs ->" with the polymer 'launch' icon.
