### ISSUE TITLE
On error loading Gist should go to a new file

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#301]
Currently if there's an error you end up in a blank context - lets consider going to the equivalent of a new blank gist instead?

**Comment by devoncarew** [comment]
Will this be misleading? Will it appear as if the gists' contents were that new blank gist template?

**Comment by lukechurch** [comment]
Yeah, maybe, we just need some indication that the system is in error state and not broken, and something that is a bit more permanent than the toast.

Maybe replacing the code area with a "error loading gist ..., click _here_ to start a new pad"

**Comment by devoncarew** [comment]
+1
