### ISSUE TITLE
Toast after Share isn't clickable

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#303]
I clicked Share, and then I clicked "OK" in the popup. I saw the Toast telling me a gist was created. Yay!

I tried clicking on the text in the Gist, to go to it.

Expected: To open a new tab to view the gist.

Actual: The text in the toast is not clickable.

**Comment by lukechurch** [comment]
Maybe @kasperpeulen  might want to take a look at this one?

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/dart-pad/pull/306
