### ISSUE TITLE
windows monospace font has no unicode arrow

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#305]
![](http://i.imgur.com/HaLeB2G.png?1) 

oh, oh

**Comment by kasperpeulen** [comment]
Actually, mac monospace (I think both mac and windows use Courier New for this) also hasn't this unicode arrow, but for mac, it falls back to the apple symbols font.

**Comment by kasperpeulen** [comment]
This is still an issue on windows. This doesn't look very professional.

**Comment by devoncarew** [comment]
Perhaps there's an arrow symbol common to these fonts?

**Comment by RedBrogdon** [comment]
@filiph Would you mind checking on your Windows machine if this is still an issue?

**Comment by filiph** [comment]
I can see the arrow on my Windows 10 machine. Closing.
