### ISSUE TITLE
Add route for creating a new Flutter app

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#3050]
The flutter.new domain redirects to dartpad.dev/flutter, which currently shows a screen that says `GoException`. We should add support for this route or show a more user-friendly error message.

**Comment by IldySilva** [comment]
@johnpryan can you share what is the purpose of the flutter.new?

**Comment by johnpryan** [comment]
See [this thread](https://x.com/TahaTesser/status/1831734785158398448) for context.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/dart-pad/pull/3055
