### ISSUE TITLE
Compilation error when running dartpad_ui: Error: The method 'withValues' isn't defined for the class 'Color'.

### ISSUE THREAD

**Issue by bartoszone** [dart-lang/dart-pad#3061]
## What happened?
Compilation error when running dartpad_ui: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.

What is this method? I don't recognize it from flutter SDK, is it custom extension?
<img width="592" alt="image" src="https://github.com/user-attachments/assets/9d8f008f-dc89-4494-b343-cc064cef7d41">

## Steps to reproduce problem

Checkout the code from main, run dart pub get
Try running using flutter run -d chrome --web-browser-flag "--disable-web-security"

## Additional info
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-PL)
    • Flutter version 3.24.3 on channel stable at /Users/bartoszkraszewski/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (11 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

### Machine

Operating system:
OSX
Version:
Sonoma 14.6.1

**Comment by devoncarew** [comment]
This is likely due to https://github.com/dart-lang/dart-pad/pull/3056. I'm not sure when `color.withValues` was introduced; perhaps we now have a dep on a beta channel sdk.

**Comment by csells** [comment]
yeah. `dartpad_ui` depends on `sdk: ^3.6.0-0` instead of `sdk: ^3.5.4` which is the latest released version of Dart according to [the archive page](https://dart.dev/get-dart/archive).

**Comment by csells** [comment]
well, crap. it looks like from https://github.com/dart-lang/dart-pad/pull/3065 that the beta build of 3.6 is required, so no fix for 3.5.4 would be valid.

**Comment by devoncarew** [comment]
I think we generally develop against `beta`, and would at least need the most recent stable. We do build + deploy the frontend using the `main` channel currently; I believe changed since we needed the latest latest in order to build w/ WASM.

https://github.com/dart-lang/dart-pad/blob/main/.cloud_build/dart_pad.yaml#L2

We should probably relax that to the beta channel once that's feasible.

**Comment by richanshah** [comment]
I am facing same issue with flutter latest version 3.27.0, where I was getting warnings to update to withValues but after i build for ios it is showing completion error.

**Comment by patelneel9080** [comment]
when i create new project from android studio it sees this error Error: The method 'withValues' isn't defined for the class 'Color'. - 'Color' is from 'dart:ui'. Try correcting the name to the name of an existing method, or defining a method named 'withValues'. borderPaint..color = Colors.grey.shade300.withValues(alpha: 0.5));

**Comment by VarunReddyT** [comment]
Yes. Changing withValues to withOpacity is working fine.
Note : withValues(alpha : 0.5) must be changed  to withOpacity(0.5)  --> Directly mention the parameter without alpha.

**Comment by OptisolSivaG** [comment]
> Yes. Changing withValues to withOpacity is working fine. Note : withValues(alpha : 0.5) must be changed to withOpacity(0.5) --> Directly mention the parameter without alpha.

but, for compile time on local machine it is ok to handle like this. but, when other Dev's try to run the code, they also facing the issue ? what is the common solution ?

**Comment by VarunReddyT** [comment]
Yes for now, we need to manually change all the occurrences of the method I guess. I hope it will solved.

**Comment by dev-hbox** [comment]
> yeah. `dartpad_ui` depends on `sdk: ^3.6.0-0` instead of `sdk: ^3.5.4` which is the latest released version of Dart according to [the archive page](https://dart.dev/get-dart/archive).

Thanks for the help buddy. I was really confused in that

**Comment by dev-hbox** [comment]
> Yes. Changing withValues to withOpacity is working fine. Note : withValues(alpha : 0.5) must be changed to withOpacity(0.5) --> Directly mention the parameter without alpha.

thanks for the help @VarunReddyT
