### ISSUE TITLE
Dart Pad Isn't Showing My Github Profile

### ISSUE THREAD

**Issue by Menula-De-Silva** [dart-lang/dart-pad#3073]
![Screenshot 2024-10-04 155749](https://github.com/user-attachments/assets/14e2d819-99c2-498c-b963-a1b0d8542299)

**Comment by parlough** [comment]
Hey @Menula-De-Silva, thanks for opening an issue!

DartPad [dropped support](https://github.com/dart-lang/dart-pad/issues/2808) for GitHub authentication to reduce the maintenance cost of the site and help focus on the core "playground" experience of DartPad.

**Comment by Menula-De-Silva** [comment]
Hmm ... Ok
