### ISSUE TITLE
GoException (no routes for location) when loading a gist

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#3088]
## What happened?

I'm trying to open gist here https://gist.github.com/Stargator/ee2aa77274a28caf2447505bc4661784.

I thought the way to do it is to just append the hash to `dartpad.dev/` url. Maybe I'm misremembering? Like so:
https://dartpad.dev/ee2aa77274a28caf2447505bc4661784

Currently, I get an error.

## Steps to reproduce problem

Visit https://dartpad.dev/ee2aa77274a28caf2447505bc4661784

### Browser

Browser: Firefox

Version: 131.0.3 (aarch64)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

uBlock Origin

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
No
```

### Machine

Operating system: macOS

Version: 14.7

### DartPad's output

GoException: no routes for location: /ee2aa77274a28caf2447505bc4661784

![Screenshot 2024-11-08 at 15 24 08](https://github.com/user-attachments/assets/791f32be-b730-42aa-a4c3-3f20ed99a28b)

**Comment by S-Cesc** [comment]
DartPad stopped to work DateFormat localization. Example:

`import 'package:intl/intl.dart';
import 'package:intl/date_symbol_data_file.dart';

void main() {
  initializeDateFormatting("es");
  print(DateFormat("yMMMd", "es").format(DateTime.now()));
}`

**Comment by cheymos** [comment]
@filiph Hi! It seems you are using the wrong url to open gist. The correct url would be - https://dartpad.dev/?id=ee2aa77274a28caf2447505bc4661784

**Comment by johnpryan** [comment]
The `id` query parameter works, but since these links used to be supported, I'm thinking we should add a route to the GoRouter configuration [here](https://github.com/dart-lang/dart-pad/blob/main/pkgs/dartpad_ui/lib/main.dart#L55) and handle this using a URL parameter (`/:gistId`). This will cause a conflict with the current`/flutter` route, but I'm not sure if that URL is being used.
