### ISSUE TITLE
I miss dartformat

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#312]
I would love to be able to invoke dartformat on the code

**Comment by kasperpeulen** [comment]
:+1: would be awesome

**Comment by devoncarew** [comment]
Added an issue here: https://github.com/dart-lang/dart-services/issues/131

**Comment by alan-knight** [comment]
+1
And I note the referenced issue is closed.

**Comment by lukechurch** [comment]
@alan-knight It's implemented in services, we just haven't surfaced it in the UI yet. Soon.

**Comment by lukechurch** [comment]
It was implemented in the UI a little while back
