### ISSUE TITLE
Samples: Clock

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/dart-pad#313]
The Clock sample uses requestAnimationFrame, however the documentation which accompanies this function specifically says that unless cancelAnimationFrame is required, the preferred Dart idiom is to use animationFrame (which returns a future).

Consider converting this sample to use animationFrame instead.

**Comment by devoncarew** [comment]
https://gist.github.com/anonymous/83caa2b65236f8ebd703

**Comment by devoncarew** [comment]
Clock has been removed...
