### ISSUE TITLE
Line numbers would be great

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#317]
To be able to easily refer specific lines it would be great to have line numbers shown.

**Comment by kwalrath** [comment]
I'd like this, too.

**Comment by KOGI** [comment]
+1

**Comment by srawlins** [comment]
Still valid.

**Comment by RedBrogdon** [comment]
The new embed UI features line numbers, though the playground does not. Adding them shouldn't be terribly difficult, though some means to turn them on and off might be a good idea.

**Comment by RedBrogdon** [comment]
Another +1 for this request came in from Kate:

>When using DartPad recently, I received an error with a line number referring to the issue. Unfortunately, the editor does not have line numbers so I had to go looking for it another way.

>I've noticed that folks are using DartPad now to report and reproduce bugs in flutter/flutter (yay!), and having line numbers would help with those really large samples that have many many lines of code. :)

**Comment by Ahmadre** [comment]
+1 Yes please line numbers and the ability (maybe new PR?) to collapse/uncollapse functions/methods ❤️

**Comment by happyharis** [comment]
This feature will be really good for beginners or people want to have a taste of flutter to learn errors and debug without installing flutter/dart.

**Comment by dphaine** [comment]
Yes it's a pain that DartPad refers to errors by line number, but the editor doesn't actually show those numbers!

**Comment by RedBrogdon** [comment]
This has been implemented for the embedded UI, but hasn't been done for the playground (full-screen) version.

**Comment by Fugazi56** [comment]
+1

**Comment by madranet** [comment]
+1

Issue opened April 2015.  C'mon folks. Five years and counting, just to add line numbers to an editor window!

**Comment by HowCoolIsThat** [comment]
YES YES YES -- we need line numbers
This is a great tool and it reports errors on line numbers yet has no line numbers. Please raise the priority a few notches and make this tool more usable for those people who are trying to learn Dart and Flutter.

**Comment by prateek-aher** [comment]
+1 Line numbers needed in Dartpad.

**Comment by larskuerten** [comment]
+1 to line numbers
