### ISSUE TITLE
Menu on LHS on mobile is not displayed correctly

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#329]
This may be the same as #117 

When I view the LHS menu on a mobile I get this:

![image](https://cloud.githubusercontent.com/assets/2978182/7149884/293183c0-e30b-11e4-9878-4664496fad7f.png)

(From Chrome's mobile emulation, but it's pretty much what I see on the Nexus 6 as well).

**Comment by devoncarew** [comment]
It is; it sucks. I'd hoped that a rev of the polymer component to 0.8 would help address this, but there's no eta on the 0.8 polymer components.

Let's bump the priority and fix before we go 1.0.

**Comment by devoncarew** [comment]
Will track in #117.
