### ISSUE TITLE
"no documentation found" is a bit misleading message, when I didn't ask for docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#334]
When I put my cursor at the last line of my pad, I see "no documentation found". It's unclear what documentation we tried to go find. In this context, I wasn't expecting to display any docs.

Should we _not_ display "no documentation found" if there's no context for docs?

**Comment by kasperpeulen** [comment]
@sethladd good point, that message seems a bit off. Maybe we could change the standard message to something like "Click on a dart element to look up documentation."

**Comment by sethladd** [comment]
That's a good start :)

**Comment by devoncarew** [comment]
They'll probably discover on their own that click around will show docs; perhaps just an empty message if there are no associated docs?

**Comment by lukechurch** [comment]
+1. It's just noise, and I like uis to be as clean as possible

**Comment by sethladd** [comment]
For the record, the auto-docs thing is AWESOME.

**Comment by kasperpeulen** [comment]
@sethladd thanks :)

We could also just do nothing if there is no documentation found. If we do that, the latest matching documentation will be shown.

**Comment by sethladd** [comment]
Displaying nothing if no docs works for me.

**Comment by lukechurch** [comment]
This also appears in HTML etc, which seems to be causing a bit of confusion.
