### ISSUE TITLE
Gist does not include a link back to Dart Pad, also bold Untitled is uninspiring

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#338]
When I shared a pad to Gist, it worked, but when I viewed the gist, I didn't see any clickable link back to Dart Pad.

Can we close the loop and link back to Dart Pad? Will also make it easier to track our adoption and spread the love.

Also, the big bold "Untitled" is a bit scary/weird.

**Comment by sethladd** [comment]
Gist: https://gist.github.com/anonymous/480d5333f5eb765728ec

![screen shot 2015-04-15 at 3 50 21 pm](https://cloud.githubusercontent.com/assets/5479/7170905/1368f1be-e387-11e4-9379-156a6a594be4.png)

Can we:

* Change the title, away from Untitled
* Make dartpad.dartlang.org a real link so that it's clickable

?

**Comment by sethladd** [comment]
May I suggest:

* If no good title, don't use a title
* Created with <3 with https://dartpad.dartlang.org

**Comment by kasperpeulen** [comment]
@sethladd  So I guess, only use this haikunator then if the user hasn't defined a title hisself in the dartpad ?

Or maybe we could just ask the user to give the dartpad a title before he shares it ?

**Comment by sethladd** [comment]
Instead of defaulting to Untitled, default to something more interesting.

I don't want to ask the user to create a title in order to share it. That's too much work :)
