### ISSUE TITLE
More sophisticated default sample

### ISSUE THREAD

**Issue by tosh** [dart-lang/dart-pad#339]
I'd love to see a _default_ sample that is a bit more sophisticated than the current for loop.
Ideally it would show off Dart and DartPad's power a bit better.

I'm not sure what would make a great sample but I guess something between the complexity of `html hello world` or `fibonacci`  and `sunflower` might work well (not too minimal and not too big, perhaps defining and using 2-3 functions?).

(btw I love how smooth and powerful doc browsing is by now, same for autocompletion)

**Comment by devoncarew** [comment]
Perhaps, paste a few different samples in here (or some dartpad links!), and see what people think?

I would be worried if the starting sample was longer than a page - I wouldn't want any of the code to be below the fold.

**Comment by kasperpeulen** [comment]
Maybe we can make a dartisan contest ? 

"Contest: Create a short but inspiring dart code. Winner will be featured at the starting page of dartpad :)"

**Comment by devoncarew** [comment]
For reference here is the current (uninspiring) sample: https://gist.github.com/a4737ecb94ac262b7be1.
