### ISSUE TITLE
Gists should have more contextual information in their README

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#340]
Let's include more helpful info in the readme.md that we generate for a gist. Let's help ensure that anyone looking at the code knows: if it's any good, will it work, when it was created.

* Does this have any warnings or errors?
  * Answers "is this code expected to work?"
  * If there are warnings or errors, where are they?
* What version of Dart was this validated against?

**Comment by sethladd** [comment]
Basically, I want to ensure that if someone is looking at the gist, they know if it's "good", where good is defined as "no warnings or errors, probably no hints".

What's our "this code checks out" signal?

**Comment by sethladd** [comment]
@lukechurch might have opinions about what is the bar for "this code checks out"... is it anything other than:

* This code is formatted
* This code makes the analyzer smile

**Comment by lukechurch** [comment]
@Georgehe4 This is now done I think? :)

**Comment by Georgehe4** [comment]
Now done. If code does not compile, summaries will note this. Warnings will also be noted together with errors - though they will not be explicitly written. Specific numbers of each are not provided.
