### ISSUE TITLE
Html and CSS should have documentation support

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#342]
I'm not quite sure where we could source this from, but it'd be nice to have.

**Comment by sethladd** [comment]
MDN perhaps

**Comment by sethladd** [comment]
I assume you mean "docs for HTML tags and CSS syntax" ?

**Comment by lukechurch** [comment]
@sethladd  Yeah, that's what I meant.

**Comment by kasperpeulen** [comment]
Linking to mdn wouldn't be too difficult, we could do something similar as what we use for generating the mdn links for dart:html elements.

I think extracting html out of mdn to use at dartpad would be a lot more difficult. Mdn articles are often long, so we should have some algorithm that determines which information to display, and which not.

**Comment by kasperpeulen** [comment]
[brackets](https://github.com/adobe/brackets) editor has documentation support for html and css

I found this json file:
https://raw.githubusercontent.com/adobe/brackets/57dcc1a43b5646907a4948146591fdc8c7b6fda6/src/extensions/default/WebPlatformDocs/css.json

Maybe we can use that ?

**Comment by kasperpeulen** [comment]
@lukechurch @devoncarew @sethladd 

What do you guys think about using webplatform for generating css documentaiton ?

https://dartpad.dartlang.org/f1eeb2b1f6b4cf7703e0

Looks like this:
![image](https://cloud.githubusercontent.com/assets/1035299/7192273/4acece68-e494-11e4-927a-6ee424cf13c2.png)

**Comment by sethladd** [comment]
Works for me! Thanks for giving it a shot.

**Comment by kasperpeulen** [comment]
Okay, finally a working version in dartpad:
![](http://i.imgur.com/IUGV9hD.gif)

you can test it here: 
http://kasperpeulen.github.io/dart-pad/

There are still some markdown issues, will try to get a working PR this weekend.

**Comment by sethladd** [comment]
OMG YOU ROCK
