### ISSUE TITLE
caret position is wrong if title is empty

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#347]
to reproduce, remove the title (make it empty), then the caret will move to the left

**Comment by devoncarew** [comment]
Odd. Perhaps we shouldn't be using a `contenteditable`...

**Comment by kasperpeulen** [comment]
@devoncarew I think it is a chrome bug, with ::before and contenteditable. In firefox it works normal. And if I remove the before pseudo element, there is no problem in chrome as well.

A workaround (if we want to use contenteditable) could be something like:
if (titleEditable.text.isEmpty) {
  titleEditable.element.innerHtml = "&#8203;";
}

where &#8203; is a zero width space
