### ISSUE TITLE
Displayed signature in docs is over-specific

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#348]
Consider this code:

`Future doThing() => new Future.value(42);`

The docs will show:

`doThing() --> Future<dynamic>`

Ideally, we would not display `<dynamic>` here.

**Comment by sethladd** [comment]
cc @kasperpeulen

**Comment by lukechurch** [comment]
@sethladd would you mind moving this over to dart-services?

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-lang/dart-services/issues/140
