### ISSUE TITLE
If a gist has an error, don't auto-run it

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#350]
I'm starting to use sharing to explain errors to people, to report bugs etc. The code often contains syntax errors, so it really isn't going to execute.

When I'm editing it, it doesn't do anything - good. However, when people open the link that I shared, it runs, fails to compile and gives an ugly error.

I think that if gists have errors - they probably shouldn't execute on first open.

**Comment by devoncarew** [comment]
+1, but we won't know if the code has errors before we analyze it. Currently, when a gist is loaded, we kick off the compile _and_ the analyze in parallel. We could do them in series - analyze, and if no errors, then compile, then run. Or, we could do them in parallel, and ignore the compile results if the analyze returns w/ errors.

**Comment by lukechurch** [comment]
yeah, lets just serialise them, I don't think the perf cost will be that high.

**Comment by lukechurch** [comment]
I kinda like doing it parallel and only applying if there are no errors. It's a bit more complicated, but it keeps the 'time to first run' to a minimum.

**Comment by devoncarew** [comment]
kk. fire off both, but only apply the compilation results of the analysis returns w/o errors.
