### ISSUE TITLE
Seems to hang on this example

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#354]
I tried pasting in the code from http://stackoverflow.com/questions/29711573/incorrect-comparing-of-two-keycode-in-async-function-dart2js and it just went away. Not sure if it's the async or the waiting for keyboard input, but it just said it was waiting for the site forever.

**Comment by devoncarew** [comment]
Hmm, is the behavior consistent? I can create a pad here:

    https://dartpad.dartlang.org/530bcd4d2974f1582afe

and see the output:

```
e.keyCode : 75
e.keyCode.hashCode : 75
KeyCode.ENTER : 13
KeyCode.ENTER.hashCode : 13
e.keyCode.runtimeType : int
KeyCode.ENTER.runtimeType : int
e.keyCode == KeyCode.ENTER false
e.keyCode != KeyCode.ENTER true
a = 75
b = 13
a.hashCode = 75
b.hashCode = 13
a == b false
a == 13 false
b == 13 true
DART: a != b
```

You have to click on the 'results' area, hit a key, and then switch over to the console area to see the output -

**Comment by devoncarew** [comment]
Slightly tweaked: https://dartpad.dartlang.org/e369dd8186ade5f0ec47

**Comment by alan-knight** [comment]
Yeah, not consistent, and it seems to work if I give it some amount of HTML to work with.
