### ISSUE TITLE
Long printed output looks – weird

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-pad#364]
https://dartpad.dartlang.org/aea61603008fd5c99de5

![screen shot 2015-04-22 at 8 55 13 am](https://cloud.githubusercontent.com/assets/17034/7278933/4eaee9ae-e8cd-11e4-8fe8-49790f0d44b8.png)

**Comment by devoncarew** [comment]
Thanks for the report! Can confirm, it does look weird.

**Comment by devoncarew** [comment]
http://dev.dart-pad.appspot.com/aea61603008fd5c99de5

**Comment by kevmoo** [comment]
That looks better :smile:
