### ISSUE TITLE
Why this project is not 100% Dart? Please rewrite the python scripts in Dart.

### ISSUE THREAD

**Issue by Emasoft** [dart-lang/dart-pad#372]
Why this project is not 100% Dart? There are some python scripts, like:

dart-pad/web/main.py
dart-pad/third_party/mdetect/mdetect.py

I don't use Python, and Dart should be able to replace those script languages both client and server side, granting a consistent programming environment. Those scripts in Python force us to revert to a mixed-languages development environment. Can you rewrite all the python scripts in Dart, please? A pure Dart implementation of this awesome editor would be truly useful for didactic purposes.

**Comment by kasperpeulen** [comment]
As far as I know this main.py is just to get this to work on app engine. If you would want to deploy this editor on for example gh pages, you don't need this one.

The other one is to make sure the mobile users get routed to the mobile version, I would also find it interesting how someone could do this using only dart.

**Comment by lukechurch** [comment]
Hey folks,

Yeah, @kasperpeulen - you're right, the Python is a tiny little mini-server that just does a bit of URL directing for Gist support and simple server-side device detection based on the headers. We're just being pragmatic here. If you don't want either of these - then you can just deploy the result of the build scripts to a static web-server, and you don't need these. We may well move from server-side detection to client detection anyway.

The server side heavy lifting that this project uses for analysis, compilation, completion etc. Is all in pure Dart over at https://github.com/dart-lang/dart-services

Even so, we could rewrite this tiny bit of Python so it was also Dart on Managed Virtual Machines, it wouldn't be a huge amount of work, so if you feel passionately about that, please send a PR!

If you're interested in doing some other development work on the server that is being blocked by the Python, I'd love to hear more details about that...
