### ISSUE TITLE
Embed support for DartPad

### ISSUE THREAD

**Issue by tosh** [dart-lang/dart-pad#381]
It would be awesome if we could embed DartPad examples into any website.
For example if you write a longer form blog post and want to not only share code
but also want to allow people to execute & play around with it.

(searched for 'embed' but didn't see a ticket yet, apologies if duplicate)

**Comment by Sfshaza** [comment]
Yes! We want to embed DartPad into dartlang.org. First, to provide the entire "DartPad experience", but also  to use it where you might use a <pre> tag.

CC @kwalrath

**Comment by devoncarew** [comment]
Also adding @Georgehe4

**Comment by sethladd** [comment]
This is done?

**Comment by mit-mit** [comment]
@Georgehe4, is this done?

**Comment by lukechurch** [comment]
It's basically done, we're still working through cross-browser edge caseds

**Comment by mit-mit** [comment]
OK. This is mentioned in the list of things we are doing in 1.12 (or in this case the 1.12 time frame), so going to tag is with that for now. If it looks like it won't be fully done in the next two weeks please let me know.

**Comment by sethladd** [comment]
This is half-done-ish. We still need an easy "export to iframe snippet", but looks like the underlying tech is there, because we have demos of it embedded on other websites.

To be fair, this isn't tied directly to the 1.12 release... but it's a nice win to have.

**Comment by sethladd** [comment]
@devoncarew what's the plan here?

**Comment by Georgehe4** [comment]
We'll have this landed at latest by the end of next week.
Right now on DartPad, once you share a snippet, you will be able to get the
iframe code to embed into a webpage.
We're working on finishing touches right now.

**Comment by devoncarew** [comment]
Yup, +1 to what @Georgehe4 said. This is 99% done. We should work on making sure it has the right level of discoverability from dartpad, and perhaps blog about it in the coming week.

**Comment by Georgehe4** [comment]
Closing http://news.dartlang.org/2015/08/a-new-way-to-share-with-dartpad.html.

**Comment by mit-mit** [comment]
Excellent, thanks
