### ISSUE TITLE
Come up with a way to break out of an infinite loop

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/dart-pad#384]
I tried Dartpad and wrote a lambda-calculus interpreter, as one does.  Then I asked it to evaluate a term that diverges (an infinite loop), as one does.

After a while, the browser's hang monitor came up and gave me an opportunity to kill the tab.  When I reloaded the tab after killing it or even loaded Dartpad in a new tab, I got the same source code and it was run automatically.  While running, I cannot seem to interact with the Dartpad.

Presumably the same thing would happen with a while (true) loop.

(1) Maybe the code should not run automatically (otherwise I could Rickroll my friends by sharing my infinite loop with them).
(2) Maybe there should be a way to break out of the running program.
(3) Maybe there should be a way to clear the Dartpad.

**Comment by lukechurch** [comment]
I think that we should statically analyse the program to determine whether it will halt.

**Comment by lukechurch** [comment]
@devoncarew given our current work flow I don't really see much way out of this, other than removing the immediate run :(

In the longer term, can we move the JS to run in a web worker, or will that break too much of the execution model?

**Comment by devoncarew** [comment]
> (2) Maybe there should be a way to break out of the running program.

I think the runaway program will mean that none of our JS code will get a chance to run. So we can't actively detected an infinite loop or offer the user a stop button.

I think the best solution would be to prevent auto-run under some circumstances.  We auto-save code (into local storage) as the user types, so we could prevent auto-run when loading user code from local storage. I'm not sure what to do about gists that contains non-halting code. Auto-run is a nice feature some some room for abuse. It would be nice to keep it for the well-behaved gists.
