### ISSUE TITLE
support package: imports

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#39]

**Comment by devoncarew** [comment]
Related to https://github.com/dart-lang/dartpad_server/issues/43.

**Comment by devoncarew** [comment]
It would also hopefully enable dart pad to support something like: http://code.makery.ch/library/hello-dart/de/

**Comment by xxgreg** [comment]
Would it be possible in the meantime to have white list of packages which can be made available? A good place to start would be libraries such package:collection.

**Comment by zoechi** [comment]
or polymer, core-elements, paper-elements. They also need a transformer :-/

**Comment by devoncarew** [comment]
It's about as much work to support whitelisted packages as arbitrary packages :(

We're concentrating on getting the gist sharing work plumbed in, then will probably address packages.

packages or workflows that actually require associated html (like polymer) would be more work, and be a follow-on task - not be part of the initial packages support. We wouldn't be able to get a running app just by compiled dart code on a server; we'd also need to concatenate a bunch of html.

**Comment by devoncarew** [comment]
closing - tracking this here: dart-lang/dart-services#43.
