### ISSUE TITLE
Snippet that works in dart2js fails in Dartpad

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#394]
https://dartpad.dartlang.org/234fd0351f92c58e7786

which has just

     var element = new DivElement();
     print(element);
     var event = Element.mouseWheelEvent;
     print(event);

fails with a "Uncaught TypeError: Cannot read property 'prototype' of undefined". It's fine in WebStorm. 

The failure appears to be in the setup code in dartpad.
      (anonymous function) (VM570067:140)
      finishClass (VM570067:184)
      finishClass (VM570067:187)
      finishClass (VM570067:187)
      finishClasses (VM570067:220)
      parseReflectionData (VM570067:407)
      (anonymous function) (VM570067:1545)
      (anonymous function) (VM570067:1924)
      replaceJavaScript (frame.html:27)
      (anonymous function) (frame.html:48)
      setTimeout (async)
      messageHandler (frame.html:47)

**Comment by lukechurch** [comment]
Thanks @alan-knight I'll look into it.

Can you confirm which version of the SDK you're using in WebStorm?

**Comment by alan-knight** [comment]
Oh yeah, bleeding edge from Friday :-) . But I wouldn't expect that to be a likely issue for these things, they haven't changed recently.
