### ISSUE TITLE
Edit my pad, but the share link doesn't reflect it

### ISSUE THREAD

**Issue by davenotik** [dart-lang/dart-pad#395]
It's a bit odd: I shared my pad (sounds weird), and then kept playing in it, only to then realize that this means my shared link reflects the changes I'm making. This itself is odd as I have shared it at a point in time where I want people to see it. It's more like a gist than a Google Doc. Further, somehow the changes I'm making now aren't reflected, and it's in a broken state: https://dartpad.dartlang.org/6036b7f888128b310a78

**Comment by devoncarew** [comment]
Sharing currently shares the snapshot of the pad contents as they were when you shared them. It's a read-only copy (backed by anonymous gists). Editing it in dartpad, and re-sharing it, will create an entirely new, unrelated pad.

We have plans to make the original pad modifiable by the owner, so you could update any pad that you yourself created. We're not there yet; the anonymous gists implementation is a stepping stone to the full, github authenticated version.
