### ISSUE TITLE
Text "RESULTS" isn't clear...

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#396]
@lukechurch and I showed off DartPad to a new user today. One of their first questions: "What does RESULTS mean?"

What do we think about:

* hiding RESULTS unless you have HTML/CSS content
* renaming RESULTS to UI or something else

**Comment by devoncarew** [comment]
`HTML Output`? That might be a bit verbose, but pretty clear.

![screen shot 2015-05-13 at 2 57 45 pm](https://cloud.githubusercontent.com/assets/1269969/7622046/7ed50154-f980-11e4-93ea-8831104718bd.png)

**Comment by sethladd** [comment]
Clearer for sure. lgtm!

**Comment by devoncarew** [comment]
https://github.com/dart-lang/dart-pad/commit/f7fdbf27dcd26735a1825ca4577a0e3e0c5cf0a0
