### ISSUE TITLE
"run" it twice to execute it once!

### ISSUE THREAD

**Issue by mayureshkathe** [dart-lang/dart-pad#404]
I wrote a code snippet using DartPad; https://dartpad.dartlang.org/28291051278222094618
Everytime I need to execute the snippet, I have to hit the "run" button twice.
This is the first time I'm trying out DartPad, so pardon my ignorance if this is the way it actually works.

**Comment by lukechurch** [comment]
@mayureshkathe - that certainly shouldn't be needed. I can't reproduce this though. 

Could you let me know what browser you're using?

If Chrome, could you open Dev Tools (Menu -> More Tools -> Developer Tools) and send a screenshot of what it looks like for the network tab after loading?

Do you see anything in the console?

**Comment by mayureshkathe** [comment]
![screenshot 2015-05-07 at 9 46 33 pm](https://cloud.githubusercontent.com/assets/11299563/7520226/ce38dda6-f502-11e4-976c-fcce36396192.png)

**Comment by lukechurch** [comment]
Could you click on "Network" on the top of that?

Then reload, click run, and screen shot again.

**Comment by lukechurch** [comment]
Should look something like this: 
![image](https://cloud.githubusercontent.com/assets/2978182/7520288/72055cca-f49a-11e4-92f6-e93e2e44f92b.png)

**Comment by mayureshkathe** [comment]
Okay, I think I got an inkling, I believe it's related to the UI.
The "Run" button should be disabled while the Pad is saving the changes.
I have been hitting Run as it was saving, and it showed no results, so I hit it again and got the results.

**Comment by mayureshkathe** [comment]
![screenshot 2015-05-07 at 9 55 47 pm](https://cloud.githubusercontent.com/assets/11299563/7520376/e01da654-f503-11e4-928d-77a3bfcf951c.png)

**Comment by lukechurch** [comment]
When you say saving - do you mean a dot next to the run button?

**Comment by mayureshkathe** [comment]
Yes, I have noticed that dot next to the "Run" button while the process I call 'saving' is being carried out.
