### ISSUE TITLE
Gist routing is interfering with caching

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#407]
Our Gist redirector is meaning that we're not serving our static content as static. This means that we're currently preventing any of it being cached - and we don't get the benefit of CDN provision for any of our assets.

Lets consider strategies for fixing this.

**Comment by devoncarew** [comment]
We should set up some regexs in our web/app.yaml so that real files get served directly - only things which are (or look like) gist redirects should get served by the python code.
