### ISSUE TITLE
Stack traces would be nice

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#419]
I run my code and get "Uncaught Invalid argument(s): (2, 4, 6)"

Invalid arguments to what, I wonder?

A debugger would be even nicer, but I can see how that would be tricky. I can get devtools, but when it's paused I can't e.g. scroll my code.

**Comment by devoncarew** [comment]
`Uncaught Invalid argument(s): (2, 4, 6)` was printed to the console output area?

We do intend to get the JS stack trace, and reverse it to show the dart lines using the source map.

**Comment by devoncarew** [comment]
We may have to run all the user code in zones: https://dartpad.dartlang.org/858a2f33033b0493399d

**Comment by mindplay-dk** [comment]
If the point of DartPad is to give users a chance to try out Dart before installing it, it's not much use without this feature.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/2668 which is also about better surfacing stack traces. Thanks all!
