### ISSUE TITLE
Allow imports from pub

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/dart-pad#420]
It doesnt seem to be possible to import libraries from pub, which pretty much rules out all practical uses.

Will this become possible in the future?

**Comment by lukechurch** [comment]
We're working on it - too early to be absolutely confident - but hopefully yes and hopefully fairly soon.

**Comment by devoncarew** [comment]
Thanks for the feedback! Tracked here: https://github.com/dart-lang/dart-services/issues/43

**Comment by sebnozzi** [comment]
So... is this supported or not? And if yes, how?

**Comment by kasperpeulen** [comment]
The issue is still open, see: dart-lang/dart-services#43 @sebnozzi

**Comment by sebnozzi** [comment]
Thanks @kasperpeulen . And sorry - had not understood the relationship with the "dart-services" project.
