### ISSUE TITLE
DartPad allows you to lock yourself out.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#423]
DartPad runs code immediately when loading the page.
If that code runs forever, like `main(){for(;;);}` then the page stays unresponsive and you can't change the code. Opening DartPad in a new tab lads the same code again, making you stuck.

Please make some way to get out of this loop.

**Comment by lukechurch** [comment]
@lrhn yeah - thanks, we've fixed this, the next push of the UI server will stop it re-running the same code again when the page reloads.

In the meantime, there is a work around, you can clear the local storage associated with DartPad. If you're using chrome navigate to this url 'chrome://settings/cookies#cont' filter for DartPad and clear all the local content.

Sorry for the inconvenience.

**Comment by lrhn** [comment]
It would still be great if running Dart code didn't block the UI, but I guess that's not easy when it can access the DOM.

**Comment by lukechurch** [comment]
I agree, but as you say doing that with the DOM is really complicated
