### ISSUE TITLE
serve the iframe content from a different domain

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#427]
If we serve the iframe content from a different domain, we'll be able to relax the iframe sandbox a little bit for the pads, allowing people to use more html apis (like localStorage).

See this wiki (https://github.com/jsbin/jsbin/wiki/Best-practices-for-building-your-own-live-paste-bin) for more details.

**Comment by Sfshaza** [comment]
cc @Sfshaza  @kwalrath

**Comment by kwalrath** [comment]
@Sfshaza would you like this reopened? Or are the restrictions on dart:html APIs not as much of a concern now?

**Comment by devoncarew** [comment]
Yup, please reopen if this impacts you. I'm busy closing out older issues.
