### ISSUE TITLE
add an `export project` button

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#428]
`Export project` or `Download project`. This would export the pad as a valid Dart project, with a pubspec and directories. It might also create IntelliJ metadata files (`.idea/`)?

**Comment by Sfshaza** [comment]
cc @Sfshaza  @kwalrath

**Comment by seaneagan** [comment]
an alternative path for this would be cloning the gist repo, and then pushing to a separate remote:http://stackoverflow.com/questions/13671328/transfer-gist-repo-to-github
