### ISSUE TITLE
Pasted code into DartPad needs manual formatting

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#430]
If I copy correctly formatted code and paste it into DartPad, I have to manually re-format the code.

**Comment by devoncarew** [comment]
We have access to the formatter on the back-end, but haven't exposed it in the UI.

I'd like a subtle way to do this, so that it's not necessarily always available. Or perhaps the dart tab should always have a format button visible, next to the run button?

**Comment by Sfshaza** [comment]
A format button is fine, but why not make it automatic, similar to Dart
Editor?

**Comment by lukechurch** [comment]
This almost isn't the a case of the formatter, it's more 'when you paste stuff into it, normalise the whitespace etc'

In terms of UX for formatting what I'd like to do is to anytime there is an analysis run the formatter and see if the result is different from the code currently in the pad. If it is then push a quick fix for 'format code'. That way we get the UI only when it's relevant and without adding any more chrome.

We might also add a a 'format before sharing' checkbox into the share workflow.

**Comment by kwalrath** [comment]
I'd love to see the formatter automatically run on the code when you paste it in. But anything's better than losing all your spacing.

**Comment by lukechurch** [comment]
As we now have a format button I'm going to close this. I agree there are other better options for integrating into the sharing workflow, but they're not planned for now.
