### ISSUE TITLE
Add a reset button

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#431]
I have a DartPad instance which is pre-loaded with some code. I'd like to be able to reset to my initial state.

**Comment by devoncarew** [comment]
You can hit `New Pad...` to do this. Perhaps this is a discovery / usability issue?

**Comment by Sfshaza** [comment]
No, "New Pad" starts a new instance pre-loaded with Hello World. I want to
reset to the pre-loaded code that I started with when I created the
instance.

**Comment by devoncarew** [comment]
Ah! Yeah, we don't have that. We should. It was a question of covering a lot of use cases and minimizing the amount of UI.

We only have one pad (the last edited one) that we auto-save. Sadly enough, here are the work-around steps:
- go to a new pad (an existing one or a new one)
- make an edit
- go back to the pad you were working on

It'll be loaded from gist.github.com, but will not apply any unsaved edits.

**Comment by Sfshaza** [comment]
What about re-loading the browser page? If I close the window and re-open
the page, I'd like it to reset to the initial state, but it saves the last
seen state.

**Comment by devoncarew** [comment]
This will interact poorly with auto-save; restoring people's work when they accidently hit the back arrow or close the tab. That's something we added after some hard lessons :)

We might want to fade in a `reset` button when it's relevant. When you're on a pad backed by a gist and you've made edits to it.

**Comment by devoncarew** [comment]
@lukechurch for UX advice -

**Comment by kwalrath** [comment]
I want a reset button, too.

Kind of related: It was surprising to me that when I'd edited a sample, I couldn't get back to its original form unless I did New Pad and then selected the sample again. (I expected that selecting the sample again would reset it; my next guess was to reload the page; I finally tried using New Pad.) It felt weird to write "If you might have already edited Hello World HTML, click New Pad to reset your files."

**Comment by lukechurch** [comment]
I think we could do this as a drop down icon on the share or new pad button. Clicking the button stays the same, but clicking a down arrow on the RHS causes a menu to appear with more advanced pad management options

I agree that it's useful, but I'd prefer not to spend default chrome on it, unless it becomes clear from analytics that it's being used a lot.

**Comment by Sfshaza** [comment]
Hi gang,

You can see the latest version of the pirate code lab here:
https://github.com/dart-lang/dart-pad/issues/431

I am hoping we can add a reset button soon, as writing the steps to get back to the original code felt ...not good.

**Comment by devoncarew** [comment]
I think @lukechurch was going to take a look. We may be this as a drop down menu item off an existing button, or just a new top-level button. Hope for this to make our next release (end-of-week?).

**Comment by kwalrath** [comment]
:+1:
