### ISSUE TITLE
undo doesn't work with the `Edit > Undo` browser menu item (was: Undo is broken)

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#432]
Something weird is going on with the Undo buffer.

If I, say, type in several lines of garbage text, and then move the cursor, and THEN click Undo, it does nothing. After clicking Undo numerous times, a $ is printed (but not immediately) for each click of Undo. See attached screen shot.

![screen shot 2015-05-19 at 4 17 08 pm](https://cloud.githubusercontent.com/assets/6293442/7716044/d5408c04-fe42-11e4-95d7-7cd081b2fb08.png)

If I don't move the cursor before selecting Undo, the Undo does remove the last line, but that is all. Is the Undo buffer only one element deep?

**Comment by devoncarew** [comment]
CodeMirror has a default undo depth of 200 edits. I'd say that either it's buggy or our use of codemirror is. We should try to repo to see if there are conditions where this does / doesn't happen.

**Comment by Sfshaza** [comment]
Here's a link to my instance, which shows this error:
https://dartpad.dartlang.org/48c51101261818c66083

**Comment by devoncarew** [comment]
Just to help nail this down:

> If I, say, type in several lines of garbage text

What browser and version are you using?

> and then move the cursor

Using the mouse or cursor keys?

> and THEN click Undo

I assume you mean hitting ctrl/command-Z?

**Comment by Sfshaza** [comment]
Chrome:  Version 42.0.2311.152 (64-bit)

I'm using the mouse.

I'm selecting Undo from the menu (not using the shortcut).

**Comment by devoncarew** [comment]
> I'm selecting Undo from the menu (not using the shortcut).

I think this is the issue. command-z should work. I don't think codemirror works with the `Edit > Undo` menu item. That's controlled by the browser, not codemirror, and will just operate on the last `input` element. codemirror has a hidden input element for the current line; probably why undo works for you once.

I'm not sure there's anything we can do to address this issue; I'll update the title now that we have a better idea of what's going on.
