### ISSUE TITLE
Run javascript from the html tab

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart-pad#435]
See https://dartpad.dartlang.org/35f2e56ec0f618617572, I would expect to see 'here' at least in the actual dev tools, if not also in the `console` tab, but I don't see either.

**Comment by jakemac53** [comment]
fwiw, this is specifically so that you can do js-interop examples

**Comment by devoncarew** [comment]
Hmm, playing with that for a bit, I don't know where the console.log output is going. We route calls to Dart's `print()` function to the parent page via postmessage. We should be able to do the same thing for JS console output as well -

https://dartpad.dartlang.org/eccf2154ff489e7c15a7

**Comment by jakemac53** [comment]
I am pretty sure the js code does not execute at all using the console was just the easiest way to try and confirm that. What I really want is the ability to use js interop to mess with js code I define there, see http://dartbug.com/23539 for reference.

**Comment by devoncarew** [comment]
Ah, thanks for clarifying. This probably has to do with the way that we're injecting the html into the embedded iframe (https://github.com/dart-lang/dart-pad/blob/master/web/frame.html#L50). We can look at other ways to to do this that would let any user JS scripts execute.

**Comment by jakemac53** [comment]
Ya it seems like just appending an inline script tag to the page does not cause it to run. I know you can append a remote script to the page though and that will run. Maybe what is really needed is a `JS` tab which creates a separate file and then you inject a script tag pointing to that?

**Comment by skybrian** [comment]
Ran into this as well. It's confusing because according to "view source", the script tag is there (it wasn't stripped out), but for some reason it doesn't run. Perhaps it's an iframe thing?

**Comment by skybrian** [comment]
By the way, calling JavaScript's eval does work:

https://dartpad.dartlang.org/4591731190873bcefa49

**Comment by devoncarew** [comment]
@jakemac53, I'd prefer to avoid having a JS tab. It'd be nice for user JS scripts to run, but I don't want to use any UI area to do it - we want to stay focused on dart :)

I think just re-triggering the scripts after the document's body is created will do the trick. Both your and @skybrian's gists work with the above PR.

**Comment by jakemac53** [comment]
sure, sounds good to me
