### ISSUE TITLE
Code Summarization Thoughts

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#446]
@sethladd @lukechurch @devoncarew 

Currently working on creating a summary for users.  Ideally, these summaries will provide useful information and help developers to share insightful snippets of code. I am thinking of providing feedback for:
- Code size
- Whether code compiles
- Number of warnings or errors
- Unique libraries/imports used

For an example input from the tutorial:
```
import 'dart:html';
import 'dart:math' show Random;
import 'dart:convert' show JSON;

final String TREASURE_KEY = 'pirateName';

ButtonElement genButton;
SpanElement badgeNameElement;

main() async {
  InputElement inputField = querySelector('#inputName');
  inputField.onInput.listen(updateBadge);
  genButton = querySelector('#generateButton');
  genButton.onClick.listen(generateBadge);
  
  badgeNameElement = querySelector('#badgeName');

  try {
    await PirateName.readyThePirates();
    inputField.disabled = false; //enable
    genButton.disabled = false;  //enable
    setBadgeName(getBadgeNameFromStorage());
  } catch(arrr) {
    print('Error initializing pirate names: $arrr');
    badgeNameElement.text = 'Arrr! No names.';
  }
}

void updateBadge(Event e) {
  String inputName = (e.target as InputElement).value;
  
  setBadgeName(new PirateName(firstName: inputName));
  if (inputName.trim().isEmpty) {
    genButton..disabled = false
             ..text = 'Aye! Gimme a name!';
  } else {
    genButton..disabled = true
             ..text = 'Arrr! Write yer name!';
  }
}

void generateBadge(Event e) {
  setBadgeName(new PirateName());
}

void setBadgeName(PirateName newName) {
  if (newName == null) {
    return;
  }
  badgeNameElement.text = newName.pirateName;
  window.localStorage[TREASURE_KEY] = newName.jsonString;
}

PirateName getBadgeNameFromStorage() {
  String storedName = window.localStorage[TREASURE_KEY];
  if (storedName != null) {
    return new PirateName.fromJSON(storedName);
  } else {
    return null;
  }
}

class PirateName {
  
  static final Random indexGen = new Random();

  static List<String> names = [];
  static List<String> appellations = [];

  String _firstName;
  String _appellation;
  
  PirateName({String firstName, String appellation}) {
    
    if (firstName == null) {
      _firstName = names[indexGen.nextInt(names.length)];
    } else {
      _firstName = firstName;
    }
    if (appellation == null) {
      _appellation = appellations[indexGen.nextInt(appellations.length)];
    } else {
      _appellation = appellation;
    }
  }

  PirateName.fromJSON(String jsonString) {
    Map storedName = JSON.decode(jsonString);
    _firstName = storedName['f'];
    _appellation = storedName['a'];
  }

  String toString() => pirateName;

  String get jsonString => JSON.encode({"f": _firstName, "a": _appellation});

  String get pirateName => _firstName.isEmpty ? '' : '$_firstName the $_appellation';

  static readyThePirates() async {
    String path = 'piratenames.json';
    String jsonString = await HttpRequest.getString(path);
    _parsePirateNamesFromJSON(jsonString);
  }
  
  static _parsePirateNamesFromJSON(String jsonString) {
    Map pirateNames = JSON.decode(jsonString);
    names = pirateNames['names'];
    appellations = pirateNames['appellations'];
  }
}
```

Should ideally output a summary similar to:

- *This immense pad contains a void of errors and warnings. It makes use of 'dart:html', 'dart:math', and 'dart:convert' packages.*

More metadata and raw data can be attached to these summaries to make them more useful for searching and concise breakdown, but we should get the basic summary done first.

Let me know your thoughts about any additions/changes to the summaries that could help users.

**Comment by kasperpeulen** [comment]
Sounds good, have you thought about letting the user be also add some (custom) summary ?

Not sure how that would look UI wise though...

**Comment by devoncarew** [comment]
You could also key off the presence of html and css code: `...and has associated html and css code`.

You might omit talking about errors and warnings if there are none - hopefully most pads will analyze cleanly. 

Another phrase that might help:

`... demonstrates the use of async / await`

**Comment by devoncarew** [comment]
Detect very specific keywords? Like: `Also, mentions pirates.`

**Comment by sethladd** [comment]
If the objective is to help the SEO for snippets, we might want to add "human" words to the description. Instead of just "dart:convert", maybe "JSON parsing".

I can imagine someone saying "how do I parse JSON and add it to a web page?" and I would imagine they should find this snippet somehow.

**Comment by lukechurch** [comment]
Try not to use words that have one meaning in a context of another. E.g. ``` a void of errors and warnings ``` will cause confusion between void, the big empty space and void the type.

I like @sethladd's suggest of mapping package names to English equivalents.

I like the idea of putting in a few easter egg surprises based on specific keywords. Pirates, hummingbirds and cute but deadly frogs? 

Could we also put the date and time when it was created? Possibly in Shakesperian English style?

**Comment by Georgehe4** [comment]
[Excel spreadsheet](https://docs.google.com/a/google.com/spreadsheets/d/1Pi4lF1PpcRabkic7F1VUMqeYUp_FxjJgSFb40TFk-Ws/edit?usp=sharing) for anyone who has suggestions for keywords you would like to see.

**Comment by kwalrath** [comment]
I added a few items and notes to the spreadsheet.

**Comment by devoncarew** [comment]
Closing this as the code summarization feature is about to go live :)
