### ISSUE TITLE
Using gitter for dartpad communication?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#448]
What do you guys think about using gitter for code related communications (that doesn't really fit an issue). I've used gitter in a coding project in the summer, and I kinda loved it. 

The angular team also uses gitter for example:https://gitter.im/angular/angular. I think gitter is great for communications that don't really fit an issue. I could also chat/email you guys about that, but I think gitter is more effective, as it is basicly designed specifically for that.

Thoughts ?

**Comment by devoncarew** [comment]
We could try it. I know other projects use it successfully. Does it keep a record of conversations? What I like about github issues and PRs is that they're linked together and persist.

I'm a bit worried about having more sources of info to check -

**Comment by kasperpeulen** [comment]
> Does it keep a record of conversations? 

Gitter has unlimited chat history.

> What I like about github issues and PRs is that they're linked together and persist.

I agree, I would just think to use gitter for things that don't really fit in a issue. More like what is the general direciton now? Where everybody is working on? (so that I don't work on something that somebody else is already working on) 

Maybe some small code specifc things, for example, I was wondering if we could maybe move the `jumpTo` method in playground to a method from the abstract editor. It feels a bit off to make a whole issue about that.

**Comment by devoncarew** [comment]
Cool. Let's give it a shot. It'll be good to be more familiar with gitter. I am still worried about having more sources of info to check and more things notifying me of messages :)

But we can try it and see how it works out.

**Comment by devoncarew** [comment]
OK, there's a room set up here: https://gitter.im/dart-lang/dart-pad. Don't know the best way to make people aware of it - I can't `@` notify the watchers -
