### ISSUE TITLE
toast for issues in mobile UI looks a bit off imo

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#459]
What do you guys think, I feel using a toast here is a bit off, for some reason:

![image](https://cloud.githubusercontent.com/assets/1035299/7974056/5c9af38a-0a5d-11e5-8f0b-b802ab1d588a.png)

I think we it would look better if we use what we have for the deskopt also on mobile:

![image](https://cloud.githubusercontent.com/assets/1035299/7974093/b6ef6794-0a5d-11e5-8303-c48e47a4ff04.png)

this feels more elegant to me

thoughts ? @lukechurch @devoncarew @Georgehe4 @sethladd

**Comment by devoncarew** [comment]
+1, using a toast for the errors and warnings was expedient :) Happy to have the UI re-done -
