### ISSUE TITLE
Why is the mobile ui all generated by scripts?

### ISSUE THREAD

**Issue by jgw96** [dart-lang/dart-pad#460]
It seems very unperformant to me to generate the entire mobile polymer ui from script? What is the reason we are doing this?

**Comment by kasperpeulen** [comment]
in the polymer branch we are building the mobile UI with polymer 1.0 and there I actually rebuilded it so that it is not entirely build from scripts, see:
https://github.com/dart-lang/dart-pad/blob/polymer/web/mobile.html

**Comment by jgw96** [comment]
Awesome, have you had many bugs with polymer 1.0 so far? ive been having alot of issues using it in one of my personal projects. The paper-fab is broken for me, and paper-header-panel has been having issues for me too.

**Comment by kasperpeulen** [comment]
I have had a couple of headaches for finding out how to go from 0.5 to 1.0 but in the end everything seemed to work out. Here is a quick summary of the new layout classes, if that may help you:
http://plnkr.co/edit/xIARqr?p=preview

and here a more complex example of a layout (copying the dartpad UI):
http://plnkr.co/edit/LMWJZ5?p=preview

The only real issue I found was with the on-tap not always working as expected, but a quick fix was using: `e.stopPropagation();` which sjmiles pointed out to me (from the polymer team), see:
https://github.com/dart-lang/dart-pad/pull/458/files#diff-be39108aa992e594d7f84cedea214eb7R195
