### ISSUE TITLE
Polymer ui for desktop?

### ISSUE THREAD

**Issue by jgw96** [dart-lang/dart-pad#461]
Why arent we using Polymer to build the desktop version of dartpad? Or is this in the works?

**Comment by kasperpeulen** [comment]
I think the plan is to use also the paper elements from polymer 1.0 for the desktop UI indeed.

**Comment by jgw96** [comment]
I would really like to help on this in my spare time. I'm really busy with
a big project at work right now, but I would love to put spare time towards
it!

**Comment by kasperpeulen** [comment]
awesome :) can't wait too see a PR ! ^^

Maybe a good first step would be to first porting the feature we have for the desktop UI to the mobile UI, like the code completion and quick fixes, and then kind of forking the mobile UI at some point to make the desktop UI ? 

Thoughts @devoncarew @lukechurch ? btw, we have a chat at https://gitter.im/dart-lang/dart-pad if you want some direction maybe

**Comment by jgw96** [comment]
Sounds good! Sorry been busy at work, I'm a junior software engineer for
DataLocker by day haha. I'll mess around tonight and see what I can come up
with.

**Comment by lukechurch** [comment]
Hey @jgw96 @kasperpeulen,

Awesome to see your enthusiasm on this. 

At the moment, we'd like to stabilise the desktop UI for a bit, especially as we prove out what it will feel like when we embed this into other sites such as the docs, and the dartlang site. This is not to say we won't be transition the desktop UI, but it won't be happening immediately.

If you want to explore substantial changes to the UI technology stack, the mobile site is probably the best place to start, or you can use the services backend and start a new front end project.

If you want to write UI code, something like this: https://github.com/dart-lang/dart-pad/issues/374 would be a fantastic addition.

@jgw96 If you're just starting with contributing to the project, I'd encourage you to start off with a couple of our smaller issues to get a feel for the workflows and code review cycles. Looking forwards to seeing them!

Hope this helps give you a bit more info on where we're going, keep up the great work.

Luke
