### ISSUE TITLE
implement the polymer 1.0 behaviours as mixins

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#464]
@devoncarew I made a little bit a mess of the polymer wrapper when updating to 1.0. That is mainly because polymer 1.0 no longer supports extending elements, but now uses mixins (behaviours). I'm now thinking of rewriting it more faithfully to polymerjs 1.0. I have a made a small start, but befor I proceed, I would like to know if you think it is a good idea:

```dart
class PolymerBase {

  HtmlElement element;

  JsObject _proxy;

  PolymerBase(String tag) {
    element = new Element.tag(tag);
  }
  PolymerBase.fromSelector(String selector) {
    element = querySelector(selector);
  }

  dynamic call(String methodName, [List args]) {
    if (_proxy == null) _proxy = new JsObject.fromBrowserObject(element);
    return _proxy.callMethod(methodName, args);
  }

  dynamic property(String name) {
    if (_proxy == null) _proxy = new JsObject.fromBrowserObject(element);
    return _proxy[name];
  }

  void setProperty(String name, String value) {
    if (_proxy == null) _proxy = new JsObject.fromBrowserObject(element);
    _proxy[property] = value;
  }

}

abstract class IronSelectableBehavior {

  dynamic property(String name);

  dynamic call(String methodName, [List args]);

  /// Gets or sets the selected element. The default is to use the index of the item.
  /// @notify
  String get selected => property("selected");

  /// Gets or sets the selected element. The default is to use the index of the item.
  /// @notify
  set selected(String value) => setProperty("selected", value);

  /// The attribute to set on elements when selected.
  String get selectedAttribute => property("selectedAttribute");

}

abstract class IronResizableBehavior {

  dynamic property(String name);

  dynamic call(String methodName, [List args]);

  /// Used to assign the closest resizable ancestor to this resizable if the
  /// ancestor detects a request for notifications.
  assignParentResizable(parentResizable) => call("parentResizable");

  /// Can be called to manually notify a resizable and its descendant resizables
  /// of a resize change.
  void notifyResize() => call("notifyResize");

  /// Used to remove a resizable descendant from the list of descendants that
  /// should be notified of a resize change.
  void stopResizeNotificationsFor(target)
      => call("stopResizeNotificationsFor",[target]);

}

class IronPages extends PolymerBase with IronSelectableBehavior, IronResizableBehavior {

  IronPages.fromSelector(String selector) : super.fromSelector("iron-pages");

}
```

**Comment by kasperpeulen** [comment]
oh, it seems like this proposal would make this much more straight foward:
https://github.com/gbracha/lessRestrictedMixins/blob/master/proposal.md

**Comment by devoncarew** [comment]
+1, it looks like mixins would more closely map to what polymer's doing, and would lead to less code duplication for us.

**Comment by kasperpeulen** [comment]
@devoncarew 
I'm not used to writing test, but I'm trying to learn that now when porting the polymer 1.0 behaviours. It's more fun than I actually thought. 

I first made this in an other repo, just to have some kind of clean base. But when I tried to port it to dartpad, I get some problems now as I just used the latest version of the `test` package and `grinder` where at dartpad we don't use the latest version I see now.

Maybe upgrade dartpad to the latest version of `test` and `grinder` ? Anyway, I thought I could better give you an update about what I'm doing, before I found out that you had pictured it an other way, so here you can find what I have now:
https://github.com/kasperpeulen/polymerjs_wrapper/blob/master/lib/polymer.dart

**Comment by devoncarew** [comment]
> upgrade dartpad to the latest version of test and grinder

We definitely should; I filed an issue to track it here: https://github.com/dart-lang/dart-pad/issues/486.

Re: the https://github.com/kasperpeulen/polymerjs_wrapper repo - how much further are you thinking of taking it? It looks similar to the JS wrapper we have in https://github.com/dart-lang/dart-pad/tree/master/lib/polymer. If you think it's something you're going to finish up and carry forward, we could look at switching dartpad over to using that library and removing our polymer wrappers.

**Comment by kasperpeulen** [comment]
@devoncarew I actually planned to just make it for dartpad, so that we can use all the behaviours of the iron and paper elements we use. You mean I could make it like a pub package and porting all the iron and paper elements? (Not only the one that we use)

**Comment by devoncarew** [comment]
> You mean I could make it like a pub package and porting all the iron and paper elements? (Not only the one that we use)

Yup, if it's something that you wanted to carry forward, we could change dartpad over to using that library for the polymer element wrappers. If you just intended it to be a scratchpad to work on the mixins support before merging it back into the dartpad repo, then that sounds good too :)

**Comment by kasperpeulen** [comment]
@devoncarew 

I've actually changed my mind, and I'm trying to get the wrapper kind of "complete" now. Which means at least adding all Polymer.Base methods. And probably also all the paper and iron behaviours/elements.

Out of curiousity I tried out how difficult it would be to make custom polymer element, using a very thin dart wrapper, which looks like this:

```html
<dom-module id="dom-element">
  <template>
    <p>I'm a DOM element. This is my local DOM!</p>
  </template>

  <script type="application/dart">
    import "package:polymerjs/polymer.dart";

    @initMethod
    main() => polymer({
      "is": "dom-element"
    });
  </script>

</dom-module>
```

I've been testing this on 4 different browsers, and it seems to actually work pretty predictable. I guess for dartpad the paper and iron elements are more interesting, I'm working on those as well.

**Comment by devoncarew** [comment]
Interesting! You must be compiling the in-line dart code somewhere?

For dartpad, we're interested in wrappers around the existing material design components, and probably lightweight custom components - mostly html and css - with possibly a little bit of JS for behavior.

Most of the rest of the app would then be defined in Dart.

**Comment by kasperpeulen** [comment]
@devoncarew 
I've been using this transformer:
https://github.com/dart-lang/web-components

Maybe it is a bit of an overkill for what I need, but it seems to do some magic which makes everything work, even if I write it inline. It seems also to do some kind of vulcanise automatically.

I've been trying to see how far I can push the custom elements with this kind of jsinterop. I've been trying many examples of the dev guide, and most work now. For example, I just ported this example with gesture events:
http://plnkr.co/edit/DbSyjd?p=preview

which then would look like this:
https://github.com/kasperpeulen/polymerjs.dart/blob/master/polymerjs_examples/web/5.Events/3.drag-me.html

> For dartpad, we're interested in wrappers around the existing material design components, and probably lightweight custom components - mostly html and css - with possibly a little bit of JS for behavior.

I think using JS for a bit of behavior is also not a bad strategy. Keeps it kind of simpler, you don't have to use any transformer, and if you would do it with this very light JS interop, it is allmost the same code anyway.

**Comment by kasperpeulen** [comment]
@devoncarew I've been working on a custom element api generator. In this PR you could see how that would look like:

https://github.com/kasperpeulen/polymerjs-dart/pull/25/files

I need to test this a little bit more though, I'm sure there are some stupid bugs in the generator/library

**Comment by devoncarew** [comment]
Very cool!

I see you're doing the code gen with lists of strings. I've written some very light-weight generator classes in the past when doing things like this, to handle stuff like indentation automatically. Here's an example: https://github.com/dart-gde/chrome.dart/blob/master/tool/src/src_gen.dart. That class probably does more than you need here - and your output already looks great - so you might not see a great benefit with a generation helper class.

How mature is this package? I see you've published it - https://pub.dartlang.org/packages/polymerjs. Is it at approx. feature parity with the hand-written wrappers in dartpad?
