### ISSUE TITLE
editing after sharing a link is confusing

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-pad#478]
To reproduce:
- create a pad
- share it
- click on the shared link
- edit it some more
- close window.
- click on the shared link again.
- open the same link in an incognito window.

What I'd expect:
- When you click on a shared link, you should see what you shared. It shouldn't matter whether you use an incognito window or not.
  What I got:
- If you use an incognito window, you see what you shared. If you don't, you see the edits that came after you shared.

Possible fix:
If you open a shared link and start typing, DartPad should automatically change the URL somehow to indicate that it's _not_ the original shared link. Going to the new URL in another window (or after closing and reopening) should show your edits. Going to the original URL that you shared shouldn't show them.

For comparison, if you start typing into a shared link in the Go playground, it removes the unique ID so it's just play.golang.org.

**Comment by skybrian** [comment]
Verified that the bug is still valid.

**Comment by parlough** [comment]
We no longer support these sharing or persistence mechanisms on the current DartPad UI. If anyone is experiencing new issues or would like to make a feature request for the newer UI, please open a new issue. Thanks all!
