### ISSUE TITLE
make it hard to lose your work

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#48]
Even without sharing, should we do something like persist the code to local storage periodically?

**Comment by lukechurch** [comment]
I've just lost the work I was doing by accidentally navigating back - and now when I return to the page the content is gone.

I think we should look at persisting the 'last created' code locally.

**Comment by sethladd** [comment]
Maybe I don't know what P2 and P1 means, but I'd really like to see a way for me to save my work... somehow... even if it's a bookmark.

**Comment by sethladd** [comment]
Friendly bump. Any news on this one?

**Comment by sethladd** [comment]
IndexedDB to the rescue!

**Comment by devoncarew** [comment]
I'm just using localStorage right now - it seems to be working well.

**Comment by sethladd** [comment]
Totally works. Max size of 5MB if I recall, but it's very cross browser.

**Comment by sethladd** [comment]
Added to M3 if that's OK.

**Comment by sethladd** [comment]
Just want to say thanks for this feature. I wrote a pad, returned to it later, and it was still there. AWESOME.
