### ISSUE TITLE
Enter doesn't accept default command in dialog

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#483]
Create a pad
Click reset
Press enter - Bizarrely the code area just gets darker, nothing else happens.

**Comment by lukechurch** [comment]
It's actually worse than this, if you press enter with a dialog open, the UI is broken until you reload the page.

**Comment by devoncarew** [comment]
perhaps it's opening a second dialog?

**Comment by Georgehe4** [comment]
This is a bug with "New Pad" as well.

**Comment by Georgehe4** [comment]
I can't pinpoint what exactly is causing the document to un-focus from the front pop-up for both of these cases. Will continue working.

**Comment by devoncarew** [comment]
Is the default button focused when the dialog opens? I suspect that for some reason the button the user clicked on - the `Reset` or `New Pad` is still focused, and it gets the enter key event, which then opens a 2nd copy of the dialog.

**Comment by Georgehe4** [comment]
Yep, that seems to be the case.

**Comment by Georgehe4** [comment]
Addressed.
