### ISSUE TITLE
Code completion shouldn't appear on comments

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#485]
Consider e.g. the following code

```
    // yield emits the next value and then
    // returns out of this method.
```

I'm getting code completion on method.

**Comment by devoncarew** [comment]
a dartpad or analysis server issue?

**Comment by lukechurch** [comment]
This is a good question. I think the answer is both. DartPad shouldn't be asking and Analysis Server shouldn't be answering.
