### ISSUE TITLE
Requests are not making it to dart-services

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#490]
During testing today I've seen a number of occasions of requests to AppEngine timing out, however the server logs do not contain any indications of the problem.

This is a tracking bug as we investigate further.

**Comment by devoncarew** [comment]
Analysis for a small file w/ no imports seems slow:

![screen shot 2015-06-11 at 12 12 42 pm](https://cloud.githubusercontent.com/assets/1269969/8115856/422ce5cc-1033-11e5-9b9f-ebaa7dccb156.png)

It should be in the range ~300ms including round-trip time.

**Comment by lukechurch** [comment]
This should now be resolved
