### ISSUE TITLE
Large console output is not handled reliably

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#491]
If you print a lot of output to the console (e.g. by printing the mouse cursor location) in Dartpad, a lot of things seem to go wrong:

1. Printing the output slows down dramatically over time

2. If you press Run, if the network operation succeeds the compilation completes but the results aren't applied to the IFrame until the output from the previous execution has all completed. However the run button remains grayed out, so it appears like Dartpad is hung

3. Changes to the Pad don't get saved until the output has completed. If the user isn't aware of what is happening this can cause data loss

4. Observatory reports spinning on DBusyLight.__reconcile (elements.dart)

**Comment by devoncarew** [comment]
I think the issue is that we're creating a lot of DOM nodes. For large text areas, you want to virtualize what you're seeing.

We can either use codemirror for the text output or start removing lines from the beginning on the console output when we have say more than 100 lines.

**Comment by devoncarew** [comment]
@lukechurch, can you send over a pad demonstrating this issue?

**Comment by devoncarew** [comment]
https://dartpad.dartlang.org/3c17538928376d125c31
