### ISSUE TITLE
Not obeying API rate limits on GitHub

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#501]
Heavily used gists from a single location are being rejected with HTTP 403. We are not respecting the back-off requests being sent.

Two changes:

- Add some front end caching for GitHub so we absorb the traffic spike for a popular Gist
- Add code to handle and do the right thing with the backoff requests

**Comment by lukechurch** [comment]
We also need some better UX around reporting what is going on to users, at the moment there's just a failing network request.

**Comment by devoncarew** [comment]
So, to be clear ,the client was requesting a gist in order to display it, we would get a 403 back instead, and weren't handling these situations well in the UI?

If you had a lot of people, all in the same location, making requests from gist.github.com, that may have triggered the rate limiting.

**Comment by lukechurch** [comment]
yes, we would get a lot of people requesting gists all appearing at the same IP, this is something we'll see a bunch of in training conditions. We don't handle the UX very well, and we don't use any of the workarounds available to us.

Some detail:

https://developer.github.com/v3/#rate-limiting
The restriction for unauth is 60 requests in an hour per IP. We had plenty more than that today.

At this point, when we have authentication we should just ask the user to log in, to move into the 5k requests per hour. That should be plenty.

The second problem is that we don't back off when we get rate exceeded requests, and we don't check. So the user retries etc. This doesn't follow: https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-rate-limits

It's difficult for us to handle the state associated with this. If we put in better UX here (e.g. we can ask GitHub what our remaining request budget is), that might stop us repeating failing requests.

Other options that would help a lot include that we could add in some caching in our front end server and/or look at something around OAuthing the application. Either of these would allow us to deal with the 60 rq/hr limit.

Lets talk offline if you need more detail.
