### ISSUE TITLE
Would like #new or #reset URLs to create/reset the pad

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#503]
I find myself writing text like this:
1. Go to <a href="https://dartpad.dartlang.org" target="_blank">DartPad</a>.
2. Click the **Reset** button to undo any changes you might have made
   the last time you visited DartPad.

Instead, I'd like to be able to _know_ that they're getting a brand new DartPad. Maybe a URL like https://dartpad.dartlang.org#new.

Something like this would also be useful for examples based on gists. E.g. if you want to make sure they start from scratch, use a URL like https://dartpad.dartlang.org/f4fdb4ac33f25fd81fee#reset or https://dartpad.dartlang.org/f4fdb4ac33f25fd81fee#new.

**Comment by kwalrath** [comment]
I'd still like this.

**Comment by devoncarew** [comment]
sgtm

**Comment by srawlins** [comment]
Ditto. Still would be good feature.

**Comment by parlough** [comment]
I still think this would be useful!

Closing in favor of https://github.com/dart-lang/dart-pad/issues/2805 which incorporates a few related issues together. Thanks all for the discussion here.
