### ISSUE TITLE
clarify behavior of opening a new tab

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-pad#527]
While working on a program in dartpad, I wanted to create a second dartpad for an experiment. I duplicated the tab, and it showed the same program as before, with the same name at the top. So I thought it was another view of the same buffer.

This isn't the case; if you edit the second tab, it's actually independent of the first. This is what I wanted, but reusing the same name (steep-band-6287) makes it look like they're the same.

Perhaps this name should be changed when opening a new tab, if they're actually independent? It's unclear what this name is for.

**Comment by kwalrath** [comment]
This seems like a very reasonable usability request.

**Comment by skybrian** [comment]
Verified that the behavior is still as described.

**Comment by RedBrogdon** [comment]
Still an issue. Adding to backlog.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/2871 as the current UI doesn't support saving/loading anymore. If anyone would like us to bring that, please upvote that issue. Thanks so much!
