### ISSUE TITLE
Embed views take too long to load

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#531]
Need to cut down from ~450ms to ~100ms.

**Comment by devoncarew** [comment]
Currently ~4,500ms :)

The target would be a few hundred milliseconds. We should look at making it physically faster as well as improving the perceived speed. A splash screen that looked resembled the final UI would mitigate slow startup times.

**Comment by devoncarew** [comment]
@Georgehe4's PR (https://github.com/dart-lang/dart-pad/pull/546) got the time down to ~1000ms. We'll still want to look at shaving some time off that.

**Comment by devoncarew** [comment]
fixed
