### ISSUE TITLE
Programmatically specify a splitview's divider

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#544]
When using the embedded version of DartPad on dartlang.org, the line length of the code area is quite narrow (due to dartlang's styling). It's hard to create code examples that won't wrap. It would be helpful if, for the embedded version of DartPad, we could specify the location of the horizontal divider that separates the code from the output. There are cases where the output could be narrower, giving us more room for code.

**Comment by devoncarew** [comment]
~related to https://github.com/dart-lang/dart-pad/issues/537.

**Comment by Georgehe4** [comment]
Resolved. Specify using horizontalRatio and verticalRatio in query parameters:
embed-html.html?horizontalRatio=0.2
Accurate to nearest 10%.
