### ISSUE TITLE
Needs better error reporting

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#545]
I wrote some code that had a bug, but I received no indication that there was a bug. (I'm surprised that the analyzer didn't catch it.)

When you run the code, click the button and you see a rather unhelpful "TypeError" error message in the console.

https://dartpad.dartlang.org/3b9bc56c6e4fec6c41b3

(For the record, I forgot to specify an argument in the clickCount method signature.)

**Comment by devoncarew** [comment]
Re: the analysis issue, if you add a type annotation to `myButton` you will see an analysis warning (https://dartpad.dartlang.org/777ae389b0bd53ddba82). `var`s don't give the analyzer a lot to go on; you will see your issues at runtime :(

Re: the runtime error message, agree that it's not great. It's what dart2js can give us.

```
Uncaught TypeError: this._captured_closure_1.call$1 is not a function
```

We could improve it on our side by also providing a dart stack trace. To do this we'd need to get the JS stack trace and run that through a source map provided by dart2js. Pinpointing where the error is occurring would help the user figure out what's going on, even w/ obscure error messages.
