### ISSUE TITLE
Bootstrap demo no longer working properly

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#555]
http://dev.dart-pad.appspot.com/b51ea7c04322042b582a
The console has an error message now, while the live version of DartPad does not.

![screen shot 2015-06-29 at 11 39 58 am](https://cloud.githubusercontent.com/assets/3150228/8415438/a4e8f3da-1e53-11e5-9d28-db499b17e72a.png)

@devoncarew @lukechurch

**Comment by devoncarew** [comment]
I think this is because we're now running javascript scripts defined in the html tab. We could either add a reference to jquery in the sample, or remove the bootstrap js reference.

I changed the gist to remove the bootstrap js reference - this gist is fine just showing the bootstrap css.
