### ISSUE TITLE
Export broken for certain files

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#557]
http://dev.dart-pad.appspot.com/embed-dart.html?id=72d83fe97bfc8e735607
The solar sample (and a few others) do not export correctly.

http://dev.dart-pad.appspot.com/index.html?dart=%2F%2F+Copyright+2012+the+Dart+project+authors.+All+rights+reserved.%0A%2F%2F+Use+of+this+source+code+is+governed+by+a+BSD-style+license%0A%2F%2F+that+can+be+found+in+the+LICENSE+file.%0A%0Alibrary+solar%3B%0A%0Aimport+%27dart%3Ahtml%27%3B%0Aimport+%27dart%3Amath%27%3B%0A%0Avoid+main%28%29+%7B%0A++CanvasElement+canvas+%3D+querySelector%28%22%23area%22%29%3B%0A++new+SolarSystem%28canvas%29.start%28%29%3B%0A%7D%0A%0AElement+_notes+%3D+querySelector%28%22%23fps%22%29%3B%0Anum+_fpsAverage%3B%0A%0A%2F%2F%2F+Display+the+animation%27s+FPS+in+a+div.%0Avoid+showFps%28num+fps%29+%7B%0A++if+%28_fpsAverage+%3D%3D+null%29+_fpsAverage+%3D+fps%3B%0A++_fpsAverage+%3D+fps+%2A+0.05+%2B+_fpsAverage+%2A+0.95%3B%0A++_notes.text+%3D+%22%24%7B_fpsAverage.round%28%29%7D+fps%22%3B%0A%7D%0A%0A%2F%2A%2A%0A+%2A+A+representation+of+the+solar+system.%0A+%2A%0A+%2A+This+class+maintains+a+list+of+planetary+bodies%2C+knows+how+to%0A+%2A+draw+its+background+and+the+planets%2C+and+requests+that+it+be%0A+%2A+redraw+at+appropriate+intervals+using+the%0A+%2A+%5BWindow.requestAnimationFrame%5D+method.%0A+%2A%2F%0Aclass+SolarSystem+%7B%0A++CanvasElement+canvas%3B%0A%0A++num+width%3B%0A++num+height%3B%0A%0A++PlanetaryBody+sun%3B%0A%0A++num+renderTime%3B%0A%0A++SolarSystem%28this.canvas%29%3B%0A%0A++%2F%2F+Initialize+the+planets+and+start+the+simulation.%0A++start%28%29+%7B%0A++++%2F%2F+Measure+the+canvas+element.%0A++++Rectangle+rect+%3D+canvas.parent.client%3B%0A++++width+%3D+rect.width%3B%0A++++height+%3D+rect.height%3B%0A++++canvas.width+%3D+width%3B%0A%0A++++%2F%2F+Create+sun.%0A++++final+mercury+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22orange%22%2C+0.382%2C+0.387%2C+0.241%29%3B%0A++++final+venus+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22green%22%2C+0.949%2C+0.723%2C+0.615%29%3B%0A++++final+earth+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22%2333f%22%2C+1.0%2C+1.0%2C+1.0%29%3B%0A++++final+moon+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+0.2%2C+0.14%2C+0.075%29%3B%0A++++earth.addPlanet%28moon%29%3B%0A%0A++++final+mars+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22red%22%2C+0.532%2C+1.524%2C+1.88%29%3B%0A%0A++++final+f+%3D+0.1%3B%0A++++final+h+%3D+1+%2F+1500.0%3B%0A++++final+g+%3D+1+%2F+72.0%3B%0A%0A++++final+jupiter+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+4.0%2C+5.203%2C+11.86%29%3B%0A++++final+io+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+3.6%2Af%2C+421%2Ah%2C+1.769%2Ag%29%3B%0A++++final+europa+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+3.1%2Af%2C+671%2Ah%2C+3.551%2Ag%29%3B%0A++++final+ganymede+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+5.3%2Af%2C+1070%2Ah%2C+7.154%2Ag%29%3B%0A++++final+callisto+%3D+new+PlanetaryBody%28%0A++++++++this%2C+%22gray%22%2C+4.8%2Af%2C+1882%2Ah%2C+16.689%2Ag%29%3B%0A++++jupiter%0A++++++++..addPlanet%28io%29%0A++++++++..addPlanet%28europa%29%0A++++++++..addPlanet%28ganymede%29%0A++++++++..addPlanet%28callisto%29%3B%0A%0A++++sun+%3D+new+PlanetaryBody%28this%2C+%22%23ff2%22%2C+14.0%29%0A++++++++..addPlanet%28mercury%29%0A++++++++..addPlanet%28venus%29%0A++++++++..addPlanet%28earth%29%0A++++++++..addPlanet%28mars%29%0A++++++++..addPlanet%28jupiter%29%3B%0A%0A++++addAsteroidBelt%28sun%2C+150%29%3B%0A%0A++++requestRedraw%28%29%3B%0A++%7D%0A%0A++void+draw%28%5B_%5D%29+%7B%0A++++num+time+%3D+new+DateTime.now%28%29.millisecondsSinceEpoch%3B%0A++++if+%28renderTime+%21%3D+null%29+showFps%281000+%2F+%28time+-+renderTime%29%29%3B%0A++++renderTime+%3D+time%3B%0A%0A++++var+context+%3D+canvas.context2D%3B%0A++++drawBackground%28context%29%3B%0A++++drawPlanets%28context%29%3B%0A++++requestRedraw%28%29%3B%0A++%7D%0A%0A++void+drawBackground%28CanvasRenderingContext2D+context%29+%7B%0A++++context.clearRect%280%2C+0%2C+width%2C+height%29%3B%0A++%7D%0A%0A++void+drawPlanets%28CanvasRenderingContext2D+context%29+%7B%0A++++sun.draw%28context%2C+new+Point%28width+%2F+2%2C+height+%2F+2%29%29%3B%0A++%7D%0A%0A++void+requestRedraw%28%29+%7B%0A++++window.requestAnimationFrame%28draw%29%3B%0A++%7D%0A%0A++void+addAsteroidBelt%28PlanetaryBody+body%2C+int+count%29+%7B%0A++++Random+random+%3D+new+Random%28%29%3B%0A%0A++++%2F%2F+Asteroids+are+generally+between+2.06+and+3.27+AUs.%0A++++for+%28int+i+%3D+0%3B+i+%3C+count%3B+i%2B%2B%29+%7B%0A++++++var+radius+%3D+2.06+%2B+random.nextDouble%28%29+%2A+%283.27+-+2.06%29%3B%0A++++++body.addPlanet%28%0A++++++++++new+PlanetaryBody%28this%2C+%22%23777%22%2C%0A++++++++++++++0.1+%2A+random.nextDouble%28%29%2C+radius%2C+radius+%2A+2%29%29%3B%0A++++%7D%0A++%7D%0A%0A++num+normalizeOrbitRadius%28num+r%29+%3D%3E+r+%2A+%28width+%2F+11.0%29%3B%0A%0A++num+normalizePlanetSize%28num+r%29+%3D%3E+log%28r+%2B+1%29+%2A+%28width+%2F+110.0%29%3B%0A%7D%0A%0A%2F%2A%2A%0A+%2A+A+representation+of+a+plantetary+body.%0A+%2A%0A+%2A+This+class+can+calculate+its+position+for+a+given+time+index%2C%0A+%2A+and+draw+itself+and+any+child+planets.%0A+%2A%2F%0Aclass+PlanetaryBody+%7B%0A++final+String+color%3B%0A++final+num+orbitPeriod%3B%0A++final+SolarSystem+solarSystem%3B%0A%0A++num+bodySize%3B%0A++num+orbitRadius%3B%0A++num+orbitSpeed%3B%0A%0A++final+List%3CPlanetaryBody%3E+planets+%3D+%3CPlanetaryBody%3E%5B%5D%3B%0A%0A++PlanetaryBody%28this.solarSystem%2C+this.color%2C+this.bodySize%2C%0A++++++%5Bthis.orbitRadius+%3D+0.0%2C+this.orbitPeriod+%3D+0.0%5D%29+%7B%0A++++bodySize+%3D+solarSystem.normalizePlanetSize%28bodySize%29%3B%0A++++orbitRadius+%3D+solarSystem.normalizeOrbitRadius%28orbitRadius%29%3B%0A++++orbitSpeed+%3D+calculateSpeed%28orbitPeriod%29%3B%0A++%7D%0A%0A++void+addPlanet%28PlanetaryBody+planet%29+%7B%0A++++planets.add%28planet%29%3B%0A++%7D%0A%0A++void+draw%28CanvasRenderingContext2D+context%2C+Point+p%29+%7B%0A++++Point+pos+%3D+calculatePos%28p%29%3B%0A++++drawSelf%28context%2C+pos%29%3B%0A++++drawChildren%28context%2C+pos%29%3B%0A++%7D%0A%0A++void+drawSelf%28CanvasRenderingContext2D+context%2C+Point+p%29+%7B%0A++++%2F%2F+Check+for+clipping.%0A++++if+%28p.x+%2B+bodySize+%3C+0+%7C%7C+%0A++++++++p.x+-+bodySize+%3E%3D+context.canvas.width%29+%7B%0A++++++return%3B%0A++++%7D%0A++++if+%28p.y+%2B+bodySize+%3C+0+%7C%7C+%0A++++++++p.y+-+bodySize+%3E%3D+context.canvas.height%29+%7B%0A++++++return%3B%0A++++%7D%0A%0A++++%2F%2F+Draw+the+figure.%0A++++context%0A++++++++..lineWidth+%3D+0.5%0A++++++++..fillStyle+%3D+color%0A++++++++..strokeStyle+%3D+color%3B%0A%0A++++if+%28bodySize+%3E%3D+2.0%29+%7B%0A++++++context%0A++++++++++..shadowOffsetX+%3D+2%0A++++++++++..shadowOffsetY+%3D+2%0A++++++++++..shadowBlur+%3D+2%0A++++++++++..shadowColor+%3D+%22%23222%22%3B%0A++++%7D%0A%0A++++context%0A++++++++..beginPath%28%29%0A++++++++..arc%28p.x%2C+p.y%2C+bodySize%2C+0%2C+PI+%2A+2%2C+false%29%0A++++++++..fill%28%29%0A++++++++..closePath%28%29%3B%0A%0A++++context%0A++++++++..shadowOffsetX+%3D+0%0A++++++++..shadowOffsetY+%3D+0%0A++++++++..shadowBlur+%3D+0%3B%0A%0A++++context%0A++++++++..beginPath%28%29%0A++++++++..arc%28p.x%2C+p.y%2C+bodySize%2C+0%2C+PI+%2A+2%2C+false%29%0A++++++++..fill%28%29%0A++++++++..closePath%28%29%0A++++++++..stroke%28%29%3B%0A++%7D%0A%0A++void+drawChildren%28CanvasRenderingContext2D+context%2C+Point+p%29+%7B%0A++++for+%28var+planet+in+planets%29+%7B%0A++++++planet.draw%28context%2C+p%29%3B%0A++++%7D%0A++%7D%0A%0A++num+calculateSpeed%28num+period%29+%3D%3E%0A++++++period+%3D%3D+0.0+%3F+0.0+%3A+1+%2F+%2860.0+%2A+24.0+%2A+2+%2A+period%29%3B%0A%0A++Point+calculatePos%28Point+p%29+%7B%0A++++if+%28orbitSpeed+%3D%3D+0.0%29+return+p%3B%0A++++num+angle+%3D+solarSystem.renderTime+%2A+orbitSpeed%3B%0A++++return+new+Point%28%0A++++++++orbitRadius+%2A+cos%28angle%29+%2B+p.x%2C+%0A++++++++orbitRadius+%2A+sin%28angle%29+%2B+p.y%29%3B%0A++%7D%0A%7D%0A&html=%3C%21--+Copyright+2011+the+Dart+project+authors.+All+rights+reserved.%0A+++++Use+of+this+source+code+is+governed+by+a+BSD-style+license%0A+++++that+can+be+found+in+the+LICENSE+file.+--%3E%0A%0A%3Ch2%3ESolar+System%3C%2Fh2%3E%0A%0A%3Cdiv+id%3D%22container%22%3E%0A++%3Ccanvas+id%3D%22area%22+height%3D%22300px%22%3E%3C%2Fcanvas%3E%0A%3C%2Fdiv%3E%0A%0A%3Cfooter%3E%0A++%3Cp+id%3D%22fps%22%3E%3C%2Fp%3E%0A%3C%2Ffooter%3E%0A&css=%2F%2A+Copyright+2012+the+Dart+project+authors.+All+rights+reserved.+%2A%2F%0A%2F%2A+Use+of+this+source+code+is+governed+by+a+BSD-style+license+%2A%2F%0A%2F%2A+that+can+be+found+in+the+LICENSE+file.+%2A%2F%0A%0A%23container+%7B%0A++left%3A+0%3B%0A++right%3A+0%3B%0A++height%3A+300px%3B%0A%7D%0A%0A%23fps+%7B%0A++float%3A+right%3B%0A++margin-bottom%3A+0%3B%0A%7D%0A%0A%23area+%7B%0A++left%3A+0%3B%0A++right%3A+0%3B%0A%7D%0A

**Comment by devoncarew** [comment]
I suspect we are hitting url length limits, on the server (appengine) or in the client.

**Comment by Georgehe4** [comment]
It is a url length limit.

**Comment by Georgehe4** [comment]
We'll have to find a work-around.

**Comment by Georgehe4** [comment]
Addressed.
