### ISSUE TITLE
mobile UI punch list

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#558]
Punch list to re-release the mobile UI:

- we need to restore animations (transitions) between pages - when transitioning to the execution results page and back again
- in the execution results page, we need more padding on the left hand side of the toolbar
- the foreground color of the FAB button can regress in some circumstances

**Comment by Georgehe4** [comment]
Vulcanization seems to affect how certain buttons interact. The menu button in the top right doesn't function correctly in chrome anymore.

**Comment by Georgehe4** [comment]
Can you screenshot what you're seeing with the execution results page needing more padding?

**Comment by devoncarew** [comment]
![screen shot 2015-07-01 at 10 10 44 am](https://cloud.githubusercontent.com/assets/1269969/8460453/93d19c5a-1fd9-11e5-8abe-654ae1197459.png)

The back button on the far left. But I think the toolbar on both screens needs left and right padding - the other buttons look too close to the edges once you click on them (and see the ink press).

**Comment by Georgehe4** [comment]
#561 #564
