### ISSUE TITLE
Printing a page that contains embedded DartPad

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#559]
... leaves a lot to be desired.  (See attached image.)

![dartpad](https://cloud.githubusercontent.com/assets/6293442/8437765/1d37e716-1f16-11e5-80f3-d04be238dc78.png)

**Comment by Georgehe4** [comment]
![screen shot 2015-06-30 at 3 13 38 pm](https://cloud.githubusercontent.com/assets/3150228/8443338/a2d52860-1f3a-11e5-8022-d51501c1b078.png)
The under-development embed page seems to handle printing a lot better.

**Comment by kwalrath** [comment]
Yes, it does. That's good!
