### ISSUE TITLE
Embed Splitter

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#569]
Need to allow users to move the embed splitters - either by finding the correct polymer component or by creating our own component.

**Comment by devoncarew** [comment]
I suspect that polymer 1.0 won't have this control, as I don't see anything about it in the material design spec. We could look at using our hand-coded in in dart, and just attach the code to the polymer `horizontal-splitter` and `vertical-splitter` components we've defined.

**Comment by Georgehe4** [comment]
Addressed.
Note that vertical & horizontal splitter ratios can still be controlled using query parameters.
