### ISSUE TITLE
Code completion not appearing in embedded UI?

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#570]
Trying to edit the same code in the main ui and the embedded ui

```
void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
    i.
  }
}
```

Code completion on the . is working in the main ui, but not showing in the embedded UI.

**Comment by Georgehe4** [comment]
It was not brought over in the transition. I'll work on enabling it after exporting is finished up (hopefully) tomorrow.
