### ISSUE TITLE
Code Completion Bug

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#575]
<img width="780" alt="screen shot 2015-07-13 at 1 58 12 pm" src="https://cloud.githubusercontent.com/assets/3150228/8660678/44fbeee0-2967-11e5-82f2-135c9b45bf24.png">

Should be selecting without using prefix.

**Comment by devoncarew** [comment]
Hard to see, but here the cursor is between `i.` and `ceil()`.

**Comment by Georgehe4** [comment]
@lukechurch Bug mentioned on Monday.

**Comment by RedBrogdon** [comment]
@devoncarew Should this be closed? I don't understand the original issue, though the current playground UI produces a completion window that looks identical.

**Comment by devoncarew** [comment]
Let's close. I think we should audit the completion UI in any case, so can open any necessary bugs as we hit them.
