### ISSUE TITLE
need better progress display when we're running

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#58]
We need a better progress display when we're running / compiling. Also, a way to cancel the task?

**Comment by lukechurch** [comment]
Does this need a mock? In the past I've used a 'train-line' like motif for this. A line with blobs or ticks representing each stage that we have passed through. If you want to stop it going to the stage you can put a 'break point' in it.

**Comment by sethladd** [comment]
Dart Pad doesn't seem to run anything automatically for me. I need to click 'Run'. Is that by design?

**Comment by devoncarew** [comment]
Yup, we don't auto-run currently. The html and css _does_ get copied over to the iframe automatically; the dart isn't compiled and injected into the iframe w/o an explicit 'run' action.

**Comment by sethladd** [comment]
Hm, maybe that was part of the confusion. If only part of the output is automatically updated, but not the other part, the user is left wondering and waiting for the other part to complete.

Can we disable the auto-update of the html/css?
