### ISSUE TITLE
Need to click run twice on the first embedded DP for the page

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#585]
Often, when I first load a page, I have to click the run button twice to see the app running. But usually just the one time for the whole page, even if it has multiple embedded DP instances.

behavior:
On first clicking the run button, the green progress bar cycles, but when it finishes moving, the output area remains blank. I click a second time and it repeats the process, but this time I see the output.

**Comment by Georgehe4** [comment]
Caused by slow load of Google Analytics.
Most recent push should have addressed this issue (at least for the first load) - please reopen if this comes up again.
