### ISSUE TITLE
Embed load unreliable

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#598]
Embed will occasionally break.
#594 
<img width="1411" alt="screen shot 2015-07-27 at 3 37 09 pm" src="https://cloud.githubusercontent.com/assets/3150228/8914726/b7d7a56c-3498-11e5-94b7-566d19f2a10d.png">
<img width="594" alt="screen shot 2015-07-27 at 3 37 20 pm" src="https://cloud.githubusercontent.com/assets/3150228/8914725/b7d61e54-3498-11e5-8fb5-d8168830895c.png">

**Comment by Georgehe4** [comment]
<img width="1414" alt="screen shot 2015-07-27 at 9 21 08 pm" src="https://cloud.githubusercontent.com/assets/3150228/8916745/848a11b0-34a5-11e5-82ac-17a62fdd8796.png">
<img width="1414" alt="screen shot 2015-07-27 at 9 21 28 pm" src="https://cloud.githubusercontent.com/assets/3150228/8916746/848b979c-34a5-11e5-9780-f6118d23fc2d.png">
Flagged versions.

**Comment by lukechurch** [comment]
Every time codemirror.js completes after embed.js has completed, the page is broken.

**Comment by Georgehe4** [comment]
Fixed #599
