### ISSUE TITLE
Cannot load embed as a iframe

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#607]
Errors if dartpad attempts to load embedded iframes.

**Comment by Georgehe4** [comment]
Suspect: #599 causing occasional load fails.

**Comment by RedBrogdon** [comment]
I'm not sure we'd want to support this even if we could. 

@devoncarew @domesticmouse Opinions?

**Comment by domesticmouse** [comment]
The fact that we are running the generated code in a sandboxed iframe is going to break a lot of user expectations. I’d vote no on trying to make this work.
