### ISSUE TITLE
Can't drag splitter

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#610]
As of today, I can't drag the splitter in any of my embedded DartPad instances.

**Comment by kwalrath** [comment]
Being able to drag the splitter might help (a bit) in the carousel problem I was seeing. At least, I'd be able to confirm that the example was working.

**Comment by devoncarew** [comment]
We're preparing to push the fix for that (the splitters) now :)

**Comment by Georgehe4** [comment]
Addressed #597
