### ISSUE TITLE
Mouse over code completion doesn't show docs

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#612]
When the mouse is moved over the completion dialog, the documentation panel should show doc results.

Currently it only occurs on keyboard interactions.

**Comment by RedBrogdon** [comment]
Still an issue in the current UI. Using the arrows keys causes the docs pane to update, while hovering with the mouse does not.

I'm not sure if we want to make this change, however. IntelliJ, for example, uses the same behavior we do (hovering does not move the selection within the completion popup).

**Comment by parlough** [comment]
The code completion functionality has changed a bit since this issue was made, but has some remaining UX and DX concerns. Closing this issue in favor of addressing them together in https://github.com/dart-lang/dart-pad/issues/3010.
