### ISSUE TITLE
Code visibility in many lines code fragements

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#620]
Users must scroll to get to a desired point in the code. 
Approaching suggestions of highlighting/code hiding suggested to improve dartlang by @Sfshaza and @kwalrath - file to address soon.

**Comment by lukechurch** [comment]
Scrolling is only part of the problem. Users also aren't realising they _can_ scroll.  A marker indicating to the user that there is more code off the bottom would help.

**Comment by kwalrath** [comment]
I'd really love to be able to excerpt code. An example is staged here:

https://ch02-gist-dot-dart-lang.appspot.com/docs/dart-up-and-running/ch02.html#assert

(That example happens to show assert(), and thus would be better in checked mode: #310.)

**Comment by devoncarew** [comment]
@kwalrath, George and I talked a bit about this today. We think we have a workable solution for this. There are some showstoppers we're working on this week (for IE and others), but we think this is something we can tackle next week. Thanks for the use case!

**Comment by kwalrath** [comment]
Great! Let me know how else I can help. I can't wait to try this.

**Comment by Georgehe4** [comment]
#677

**Comment by RedBrogdon** [comment]
@kwalrath, Did the query parameter solve this problem for you, or is there additional work to be done?

**Comment by kwalrath** [comment]
I don't think I followed up on this. I'll do that.

**Comment by kwalrath** [comment]
I'm going to close this as obsolete.
