### ISSUE TITLE
after code completing the caret is not always placed at the right offset

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#639]
After code completion, the caret is not always at the right offset. For example after code completing `for ()<caret>` or completing `import '' show ;<caret>`. The caret shoudn't be placed at the end.

I heard that the dart analysis server provides the information where the caret should be.

**Comment by RedBrogdon** [comment]
I don't see the cursor jumping to the end on completions in the current release. If this is still occurring, please reopen.
