### ISSUE TITLE
syntax highlighting: ' closes ''' in dart-pad editor

### ISSUE THREAD

**Issue by bdelv** [dart-lang/dart-pad#667]
The character ' closes the multi-line string opened by ''' in dart-pad editor (syntax highlighting)
Note: 
- It is correctly interpreted when run.
- It is valid for dart-pad but correctly displayed in Webstorm

https://dartpad.dartlang.org/a8dd81cbea2796f56c2e

**Comment by Georgehe4** [comment]
@lukechurch

**Comment by devoncarew** [comment]
I think this is an issue with the codemirror dart mode - we'd need to fix it there.

**Comment by kasperpeulen** [comment]
@devoncarew would it be somehow possible to use syntax highlighting from the dart analysis server ? I believe the atom plugin also uses syntax highlighting from the das right ? 

At some point, I have tried to improve the codemirror dart mode highlighting, but it was kind of hard to get it perfect. And it also seems a bit of waste of time, if the dart analyzer can provide the information.
