### ISSUE TITLE
Add a way to stop execution after running your app

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/dart-pad#668]
```
import 'dart:async';

void main() {
  new Timer.periodic(const Duration(), (timer) {
    print("hello");
  });
  new Timer.periodic(const Duration(), (timer) {
    print("hello2");
  });
}
```

gets annoying after a while :)

**Comment by jcollins-g** [comment]
Related to #704

**Comment by RedBrogdon** [comment]
Still an issue AFAICT. We could certainly add a stop button somewhere that would reach into the iframe and replace the script node.

**Comment by RedBrogdon** [comment]
Just discovered that hitting the reset button in the playground UI does not stop whatever's executing in the iframe. That should be addressed as part of this bug as well.

**Comment by Psychosynthesis** [comment]
Yes it still there (just another example):

```
import "dart:async";
void main() {
  var count = 0;
  Future timerCreator() {

    Future timer = Future.delayed(
      const Duration(seconds: 1),
	    () => ++count,
    );

    timer.then((newCount) { 
      print(newCount);
      timer = timerCreator();
    });
    
    return timer;
  }

  timerCreator();
}
```

_I'm just learning Dart, so don't mind if the code is clumsy, anyway it illustrates what I want to show._

After pressing Run, the user no longer has the opportunity to start execution again from an empty context (I don’t know how to say it correctly), but it can be seen that when the start button is pressed again, the old timer continues to work, while the new one starts working. This is obviously not what the user expects.

Secondly - if the timer falls into some kind of fierce recursion, the only way to stop it is to reload the page. It's VERY annoying.

**Comment by BlackHC** [comment]
If this bug was a person, it would be in primary school now 😅

**Comment by johnpryan** [comment]
This is working correctly in the latest DartPad UI
