### ISSUE TITLE
autocomplete in switch case

### ISSUE THREAD

**Issue by demensky** [dart-lang/dart-pad#678]
AutoComplete does not work in block "switch case".

``` dart
import 'dart:html';

void main() {
  DivElement testNode = new DivElement();

  switch(1) {
    case 1:
      tes // No hint
      break;
  }
}
```

**Comment by lukechurch** [comment]
@danrubel I believe this is probably a limitation with Analysis Server. Shall we move this over to the SDK repo -- if you think that it isn't and then we can move it to dart-services and I can look more closely?

**Comment by demenskiy** [comment]
->![alt text](/link/to/img)<-

**Comment by lukechurch** [comment]
Hi @demenskiy, may I ask why you closed this? I very much appreciate the report, just trying to route it to the right place to be fixed.

**Comment by lukechurch** [comment]
Oh, you've re-opened. Never mind. :)

**Comment by demenskiy** [comment]
Sorry but I bad speak English

**Comment by lukechurch** [comment]
@demenskiy  -- No problem. Thank you for the report. We're working on it.

Thank you.

**Comment by demenskiy** [comment]
And only recently started using git.
Thank you too.

**Comment by danrubel** [comment]
@lukechurch I believe that this is fixed in current analysis server.
Please reassign to me if that is not the case.

**Comment by lukechurch** [comment]
@danrubel This does not seem fixed as of the Analysis server that ships with 1.15? We now load it from the SDK.

![image](https://cloud.githubusercontent.com/assets/2978182/14590917/6d7c0346-04fe-11e6-8f8a-cbb3370e498b.png)

**Comment by RedBrogdon** [comment]
No longer reproducible. Hitting Ctrl-Enter at that spot in the code now causes `testNode` to be suggested.
