### ISSUE TITLE
"Error compiling to JavaScript: Future not completed" when try to run snippet

### ISSUE THREAD

**Issue by RoadRoller** [dart-lang/dart-pad#685]
When trying to run any snippet I see the following error in console after 20 sec:
Error compiling to JavaScript:
TimeoutException after 0:00:20.000000: Future not completed
Browser: Chrome 44.0.2403.157 m

**Comment by devoncarew** [comment]
Is it intermittent? If you run the snippet again does it work or do you always see this error?

**Comment by RoadRoller** [comment]
It's reproduced for me most of times, only few times I got the execution results.

**Comment by lukechurch** [comment]
Do you happen to have a shared pad of the code that was failing?

**Comment by lukechurch** [comment]
Sorry just seen you said it was any code. Ignore the above

**Comment by RoadRoller** [comment]
I realize that problem was in my browser, maybe the resason in simultaneously running Chrome and Dartium. After system reboot DartPad start work fine.

**Comment by hijiangtao** [comment]
I got the same problem, no matter what I code in the pad. I open the console and found it's a network problem (blocked by my Internet provider), maybe we can put some friendly hint in the interface, or people like me may get confused at the beginning.

> POST https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json net::ERR_CONNECTION_REFUSED
