### ISSUE TITLE
Analyzer warnings/hints cover the entire screen on mobile

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#686]
On my Nexus 6 I had 3 warnings after I deleted one character and after that I wasn't able to do anything useful because the warnings were show over the entire screen. I had to change to "request desktop site" in order to be able to use the editor again.
I guess for mobile there should only be an icon with the number of hints/warnings which are only shown after tapping on the icon.
Alternatively it should be an area with a splitter to limit its size.

**Comment by devoncarew** [comment]
Perhaps just having a `max-height` on the problem area and ensure that it's scrollable?

**Comment by zoechi** [comment]
Sure, that would be a start. Can always be improved later ;-)

**Comment by devoncarew** [comment]
Fixed in https://github.com/dart-lang/dart-pad/pull/699/.
