### ISSUE TITLE
Code completion isn't ranked well

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#688]
The first result is both incorrect and deprecated.

![screen shot 2015-09-12 at 9 21 34 am](https://cloud.githubusercontent.com/assets/5479/9832439/bf7a4462-592f-11e5-9c41-a023b73ec416.png)

**Comment by lukechurch** [comment]
Thanks for the report.

This is serving from a very old and somewhat broken ordering model. I need to get a few changes into Analysis Server, and will then replace with a much more accurate one.

I'll retest with the same code before landing the update.

**Comment by lukechurch** [comment]
https://github.com/dart-lang/sdk/issues/24339
