### ISSUE TITLE
DartPad can't work with dartjs?

### ISSUE THREAD

**Issue by ko11ega** [dart-lang/dart-pad#690]
http://stackoverflow.com/questions/32699324/dartpad-cannot-import-dartjs?noredirect=1#comment53249330_32699324

**Comment by devoncarew** [comment]
Yes, part of `dart:js` is implemented in javascript files, which we're not able to load. You can see error messages to this effect in the devtools console.

You could try hosting those javascript files on a CDN, and referencing them from your html file - that might work.
