### ISSUE TITLE
Clock demo has broken images

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#695]
https://dartpad.dartlang.org/0dfeb25a33be007e1d0f

(The Clock Sample)

The images are all broken.

**Comment by kwalrath** [comment]
Seth removed a bunch of old samples, and it looks like this was one of them.

For the record, here's the whole list that he was considering:

https://github.com/dart-lang/sample-google-maps
https://github.com/dart-lang/sample-searchable-list
https://github.com/dart-lang/sample-gauge
https://github.com/dart-lang/sample-solar
https://github.com/dart-lang/sample-clock
https://github.com/dart-lang/sample-sunflower
https://github.com/dart-lang/sample-spirodraw
https://github.com/dart-lang/sample-dartiverse-search
https://github.com/dart-lang/sample-swipe
https://github.com/dart-lang/sample-multi-touch
https://github.com/dart-lang/sample-tracker
https://github.com/dart-lang/sample-jsonp
https://github.com/dart-lang/sample-dgrep
https://github.com/dart-lang/sample-dcat
https://github.com/dart-lang/sample-polymer-intl

**Comment by devoncarew** [comment]
Clock has been lightly maintained; I think it's safe to remove from our list of samples.

**Comment by kwalrath** [comment]
Note that solar, spirodraw, and sunflower were also removed, although they'll continue to work in DartPad as long as their gists survive...
