### ISSUE TITLE
for-in supported over Strings but should not be according to spec

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#697]
The following code generates no warnings and runs fine in **DartPad**, e.g. see [here](https://dartpad.dartlang.org/cec567ab77bc0cc83fc0):

``` dart
for(var c in 'Dart') { ... }
```

but, according to the [spec](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex), only types with an `iterator` getter should be supported. The VM and dart2js are consistent with the spec. (Now one might argue that the spec should be updated, but that is another story.)

---

To quote the [language specification](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex) as of Oct 2015

> A for statement of the form
> `for` (_finalConstVarOrType_? _id_ `in` _e_) _s_
> is equivalent to the following code: 
> 
> ``` dart
> var n0 = e.iterator;
> while (n0.moveNext()) {
>    finalConstVarOrType? id = n0.current;
>    s
> }
> ```

I.e., _e_ must have an `.iterator`

**Comment by lukechurch** [comment]
@chalin Thanks for the report.

@danrubel @bwilkerson I think this is an issue with analyser? Shall I migrate this over to the SDK issue tracker?

**Comment by lukechurch** [comment]
It now does give a warning
