### ISSUE TITLE
Add some way to keep the console open

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/dart-pad#704]
I mostly use Dartpad to test simple stuff, for instance that a DOM operation behaves in a certain way etc.. This means that my pad contains some HTML, maybe CSS and the Dart code but I just want to do a query and log the result. However the pad always switched back to the HTML view when I run it which is really frustrating. 

It would be super nice if you could either show both HTML and Console side by side, or retain the previous selection when running the pad instead of switching to the HTML output.

**Comment by devoncarew** [comment]
Makes sense! Thanks for the feedback.

**Comment by RedBrogdon** [comment]
Behavior is still present in the current release.

Possible solution:

* Stop switching to HTML output immediately on running code
* Switch to HTML output when "show web output" checkbox is checked
* Switch to HTML output when a gist with HTML content is loaded.

This would automatically switch to the HTML output view *once*, but allow the user to choose the console and stick with it after that.

**Comment by parlough** [comment]
Thanks for the feedback! The newer UI nows allows you to view both the visual output and the console output at the same time in the case of a Flutter app.
