### ISSUE TITLE
WebStorm & DartPad disagree on valid const string

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#706]
The following code (from an example I'm creating for the language tour) runs in WebStorm but not [in DartPad](https://dartpad.dartlang.org/e9c0a860fc21e4adee7f):

```
// These work in a const string.
const aConstNull = null;
const aConstNum = 0;
const aConstBool = true;
const aConstString = 'a constant string';

// These do NOT work in a const string.
var aNull = null;
var aNum = 0;
var aBool = true;
var aString = 'a string';
const aConstList = const [1, 2, 3];

const validConstString = '$aConstNull $aConstNum $aConstBool $aConstString';
// const invalidConstString = '$aNull $aNum $aBool $aString $aConstList';
print(validConstString);
```

In WebStorm (using Dart SDK version 1.12.1) I see the following output:

```
null 0 true a constant string
```

In DartPad, I get the following errors:

```
Error compiling to JavaScript:
[error on line 15] Not a compile-time constant.
[error on line 15] Not a compile-time constant.
```

There are no line numbers, making this extra fun, but line 15 appears to be the declaration of `const validConstString`.

**Comment by devoncarew** [comment]
I suspect that this might be a case of the command-line VM and dart2js disagreeing. If you try running a file like this from the command-line (`dart foo.dart`), does it work? It look like (from dartpad) that the file does analyze correctly. Since it looks like dartpad fails when compiling it (using dart2js), it's possibly a dart2js bug w/ constant expressions.

**Comment by kwalrath** [comment]
I think you're right. I put the code in a web app in WebStorm 11 (with is now using 1.13.0-dev.7.9), and it fails with this message:

```
[Info from Dart2JS]:
Compiling const_test|web/main.dart...
[Error from Dart2JS]:
web/main.dart:20:30:
Not a compile-time constant.
  const validConstString = '$aConstNull $aConstNum $aConstBool $aConstString';
                             ^^^^^^^^^^
[Error from Dart2JS]:
web/main.dart:20:30:
Not a compile-time constant.
  const validConstString = '$aConstNull $aConstNum $aConstBool $aConstString';
                             ^^^^^^^^^^
```

(I confirmed that the non-web form of the app works both in WebStorm and at the command line, using `dart string_literals.dart`.

**Comment by kwalrath** [comment]
Doing a little more testing, if I delete `$aConstNull `, the app works. So I'll just change the example and make sure there's a dart2js bug.
