### ISSUE TITLE
Change async modifier to defer in Dart scripts

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#707]
An async script executes before the whole page is available (in chrome), but defer waits until the page has loaded. In cases where you want to make sure that all the DOM on the initial page is available from within your main function, you should use defer instead of async.

```<script defer src="index.dart" type="application/dart"></script>```
```<script defer src="packages/browser/dart.js"></script>```

Pull requests welcome.

**Comment by lukechurch** [comment]
I think this is now fixed
