### ISSUE TITLE
Analyzer not reporting a warning / error when using ".."

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/dart-pad#710]
Encountered this while copy / pasting too quickly:

    var dur = const Duration(seconds: 5);
    dur..inSeconds = const Duration(seconds: 10);
    print(dur);

There are no warnings or errors shown in dartpad. When run throws a typeerror:
Uncaught TypeError: C.Duration_5000000.set$inSeconds is not a function

Interesting error, but I would expect: Illegal assignment to non-assignable expression

**Comment by devoncarew** [comment]
I think this is correct. Here's a gist of the original:

https://dartpad.dartlang.org/9a312cd3be014079f5ea

and one where the var is replaced by a type (`Duration dur = ...`):

https://dartpad.dartlang.org/35244023f934c9cf9f4e

That does show analysis issues, with the assignment to the getter `inSeconds`. If you think inference should show errors, can you open an issue on the sdk repo?

**Comment by jtmcdole** [comment]
Yeah, I'll open one up on the SDK.  I just used the "leave feedback" option at the bottom of dartpad which lead me here.
