### ISSUE TITLE
Export links feature is causing confusion

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#713]
Some users are sharing the transitory links that you get when you click export, rather than the perma-links that you get after sharing the code.

This is resulting in people with links to blank pads and errors on the server trying to fetch temporary links that don't exist.

**Comment by lukechurch** [comment]
As a short term expedient, wiping the url bar back to plain https://dartpad.dartlang.org/ would at least help manage the expectation that the URL is sharable.

The user also was concerned that going from the dart-lang home page to a shared pad is a lot of clicking. We might look again at smoothing that workflow.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/dart-pad/pull/718
