### ISSUE TITLE
Embedded - Polymer Styling Broken

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#717]
<img width="312" alt="screen shot 2016-02-18 at 3 18 05 pm" src="https://cloud.githubusercontent.com/assets/3150228/13161482/d5804662-d652-11e5-9854-734c864419ea.png">

Styling and certain buttons no longer work for embedded views.

**Comment by devoncarew** [comment]
Hey @Georgehe4, thanks for the report! I have a fix for this specific issue out. I see that we have some other layout issues, mostly to do with the run and export button positions. Note sure if this also translates to the mobile UI as well.

**Comment by devoncarew** [comment]
For mobile, it looks like the colors have regressed, but the layout looks good.
