### ISSUE TITLE
we're using some deprecated polymer layout classes

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#719]
This shows up in the console output:

```
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`
```

And the embeddings UIs don't layout out things like the buttons correctly.

**Comment by devoncarew** [comment]
<img width="566" alt="screen shot 2016-02-28 at 11 37 06 am" src="https://cloud.githubusercontent.com/assets/1269969/13381386/a3cab214-de0f-11e5-84e5-7142450f205f.png">

**Comment by devoncarew** [comment]
We won't be able to push a new (front-end) version w/o fixing this.

**Comment by devoncarew** [comment]
This is less critical as we're now versioning the bower resources (lib/bower/) explicitly in git.

**Comment by kwalrath** [comment]
We're seeing Chrome warnings in the developer console (dart-lang/site-www#422). Is that related to this?

**Comment by RedBrogdon** [comment]
Closing this as a duplicate of #892.
