### ISSUE TITLE
Code completion with named param doesn't show type

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#722]
![screen shot 2016-03-10 at 2 59 07 pm](https://cloud.githubusercontent.com/assets/5479/13687547/b9641a74-e6d0-11e5-9c1a-0929b09e2034.png)

```
class Foo {
  String name;
  Foo({this.name});
}

main() {
  var f = new Foo();
}
```

Would expect that when it shows `name:` (which is great that it shows that!) that it also shows me that it should be a String.

Thanks!

**Comment by RedBrogdon** [comment]
Still an issue in the current release.

**Comment by parlough** [comment]
This is still an issue with the current DartPad frontend alongside some other UX and DX concerns. Closing this issue in favor of addressing them together in https://github.com/dart-lang/dart-pad/issues/3010. Thanks for the discussion here!
