### ISSUE TITLE
Add option to use Analyzer in Strong mode

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#723]
and perhaps even default to Strong? I think people experimenting with Dart will have a better experience if they get more warnings about their code.

Possibly depends on #694 being completed?

**Comment by devoncarew** [comment]
I think independent from #694 (though that would be nice too). I think @lukechurch has done some investigating for adding strong mode support to the backend (dart-services). Most of the work would happen there. The front-end may or may not get a toggle or a mode, depending on how we expose it.

**Comment by lukechurch** [comment]
Yeah, I'm looking into this as we speak (Tracking issue: https://github.com/dart-lang/dart-services/issues/265). The stress tests are finding a few issues as soon as I've chased those down it should be a fairly easy land.

**Comment by lukechurch** [comment]
https://github.com/dart-lang/dart-pad/pull/731

**Comment by srawlins** [comment]
Wow that is so cool! This is a huge feature, and an awesome way to help people learn Strong Mode. Thanks!
