### ISSUE TITLE
Show Dart version used in DartPad

### ISSUE THREAD

**Issue by Zectbumo** [dart-lang/dart-pad#725]
Make it clear what Dart version that is being used on the deployed DartPad. I am trying to use new features that the DartPad on dartpad.dartlang.org does not allow but the latest availbale Dart version does but I don't know what version I should be coding for.

**Comment by devoncarew** [comment]
If you click on the 'DartPad' title in the upper-left we show the SDK version it's using. We are currently behind in reving to the latest; you can track that here: https://github.com/dart-lang/dart-services/issues/267.
