### ISSUE TITLE
Share links stopped working

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#726]
Steps to reproduce:

1. Open dartpad
2. Rewrite the default code snippet ('hello ${i + 1}')
3. Save and run
4. Click share
5. Confirm
6. Copy the first link
7. Paste the link into a new window address bar

Expected: I open see my code snippet
Actual: I open the default code snippet

The gist gets created, and the link from the gist works:
https://dartpad.dartlang.org/?source=b81b98ab-4db5-409e-af94-6b3fdd0ef1e0

But on arrival, it gets rewritten to:
https://dartpad.dartlang.org/bdd72a7680c7151840366808d1e0ece8

Which again only shows the default code snippet.

**Comment by devoncarew** [comment]
Thanks - investigating...
