### ISSUE TITLE
vulcanize --strip-comments --inline-css --inline-scripts scripts/imports.html

### ISSUE THREAD

**Issue by mihongkun** [dart-lang/dart-pad#732]
H:\develop\dart-pad>dart tool/grind.dart buildbot
grinder running [analyze] [test-cli] [coverage] [build] [buildbot]

[analyze]
  pub.bat global activate tuneup
  Resolving dependencies...
- analyzer 0.27.3-alpha.5 (0.27.3 available)
- args 0.13.4
- async 1.10.0
- charcode 1.1.0
- cli_util 0.0.1+2
- collection 1.5.1
- convert 1.0.1
- crypto 0.9.2+1 (1.1.0 available)
- csslib 0.12.2
- glob 1.1.2
- html 0.12.2+1
- logging 0.11.2
- matcher 0.12.0+2
- package_config 0.1.3
- path 1.3.9
- plugin 0.1.0
- quiver 0.21.4
- source_span 1.2.2
- string_scanner 0.1.4+1
- tuneup 0.2.1
- typed_data 1.1.2
- utf 0.9.0+3
- watcher 0.9.7
- when 0.2.0
- which 0.1.3
- yaml 2.1.8
  Downloading tuneup 0.2.1...
  Downloading quiver 0.21.4...
  Downloading analyzer 0.27.3-alpha.5...
  Precompiling executables...
  Loading source assets...
  Precompiled tuneup:tuneup.
  Activated tuneup 0.2.1.
  Installed executable tuneup.
  Warning: Pub installs executables into C:\Users\mihon\AppData\Roaming\Pub\Cache\bin, which is not on your path.
  You can fix that by adding that directory to your system's "Path" environment variable.
  A web search for "configure windows path" will show you how.
  pub.bat global run tuneup check
  Checking project dart_pad...
  No issues found; analyzed 57 source files in 11.2s.

[test-cli]
  pub.bat run test:test --reporter=expanded --platform=vm
  00:00 +0: test\core\dependencies_test.dart: dependencies retrieve dependency
  00:00 +1: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +2: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +3: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +4: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +5: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +6: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +7: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +8: test\core\event_bus_test.dart: event_bus fire one event
  00:00 +9: test\elements\bind_test.dart: bind target properties
  00:00 +10: test\core\event_bus_test.dart: event_bus fire two events
  00:00 +11: test\elements\bind_test.dart: bind can cancel
  00:00 +12: test\core\event_bus_test.dart: event_bus receive all events
  00:00 +13: All tests passed!

[coverage]
  env var 'COVERAGE_TOKEN' not found

[build]
  pub.bat build web
  Loading source assets...
  Loading dart_to_js_script_rewriter transformers...
  Building dart_pad...
  [Info from Dart2JS]:
  Compiling dart_pad|web/scripts/embed.dart...
  [Info from Dart2JS on dart_pad|web/scripts/embed.dart]:
  packages\http\src\io.dart:9:1:
  Import of 'dart:mirrors'.
  import 'dart:mirrors';
  ^^^^^^^^^^^^^^^^^^^^^^
  [Info from Dart2JS]:
  Took 0:00:12.076879 to compile dart_pad|web/scripts/embed.dart.
  [Info from Dart2JS]:
  Compiling dart_pad|web/scripts/main.dart...
  [Info from Dart2JS on dart_pad|web/scripts/main.dart]:
  packages\http\src\io.dart:9:1:
  Import of 'dart:mirrors'.
  import 'dart:mirrors';
  ^^^^^^^^^^^^^^^^^^^^^^
  [Info from Dart2JS]:
  Took 0:00:07.137561 to compile dart_pad|web/scripts/main.dart.
  [Info from Dart2JS]:
  Compiling dart_pad|web/scripts/mobile.dart...
  [Info from Dart2JS on dart_pad|web/scripts/mobile.dart]:
  packages\http\src\io.dart:9:1:
  Import of 'dart:mirrors'.
  import 'dart:mirrors';
  ^^^^^^^^^^^^^^^^^^^^^^
  [Info from Dart2JS]:
  Took 0:00:04.878011 to compile dart_pad|web/scripts/mobile.dart.
  Built 779 files to "build".
  [Warning from Dart2JS on dart_pad|web/scripts/embed.dart]:
  3 hint(s) suppressed in package:http.
  [Dart2JS on dart_pad|web/scripts/embed.dart]:
  11 warning(s) suppressed in package:crypto.
  [Warning from Dart2JS]:
  web\scripts\embed.dart:
  1 methods retained for use by dart:mirrors out of 2640 total methods (0%).
  [Warning from Dart2JS on dart_pad|web/scripts/main.dart]:
  3 hint(s) suppressed in package:http.
  [Dart2JS on dart_pad|web/scripts/main.dart]:
  11 warning(s) suppressed in package:crypto.
  [Warning from Dart2JS]:
  web\scripts\main.dart:
  1 methods retained for use by dart:mirrors out of 3069 total methods (0%).
  [Warning from Dart2JS on dart_pad|web/scripts/mobile.dart]:
  3 hint(s) suppressed in package:http.
  [Dart2JS on dart_pad|web/scripts/mobile.dart]:
  11 warning(s) suppressed in package:crypto.
  [Warning from Dart2JS]:
  web\scripts\mobile.dart:
  1 methods retained for use by dart:mirrors out of 2107 total methods (0%).
  build\web\scripts\main.dart.js compiled to 491k
  build\web\scripts\mobile.dart.js compiled to 343k
  build\web\scripts\main.dart.js compiled to 427k
  deleting build\web\packages
  cp -R -L packages build/web/packages
  Removed 809 Dart files
  build\web\scripts\imports.html original: 2k

ProcessException: 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?

  Command: vulcanize --strip-comments --inline-css --inline-scripts scripts/imports.html

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:449)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:603)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      vulcanizeNoExclusion (file:///H:/develop/dart-pad/tool/grind.dart:139:34)
```

**Comment by devoncarew** [comment]
Is this a bug report? It looks like you don't have the `vulcanize` tool installed.
