### ISSUE TITLE
The default script has compile-time error

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#734]
Current script when you open https://dartpad.dartlang.org/:

```
import 'dart:html';

class Student {
  String fullName, firstName, middleInitial, lastName;
  Student(this.firstName, this.middleInitial,
          this.lastName) : fullName = "$firstName $middleInitial $lastName" {
    fullName = "$firstName $middleInitial $lastName";
  }
}

abstract class Person {
  String firstName, lastName;
}

greeter(Person person) {
  return "Hello, ${person.firstName} ${person.lastName}";
}

main() {
  var user = new Student("Jane", "M.", "User");

  document.body.innerHtml = greeter(user);
}
```

Errors:

```
[error on line 6] 'firstName' is only available in instance methods.
[error on line 6] 'middleInitial' is only available in instance methods.
[error on line 6] 'lastName' is only available in instance methods.
```

Also, since `Student` doesn't extend `Person`, we get "The argument type 'Student' cannot be assigned to the parameter type 'Person'." (info normally, warning in strong mode)

Consider moving to another, more interesting example.

[Here](https://dartpad.dartlang.org/4a2ec1e5736e69802205adeec990ad07)'s one I'm wrote for the dartlang.org homepage.

**Comment by devoncarew** [comment]
Dartpad saves whatever you last wrote (from that browser) in case you hit the back button or inadvertently left the page. You can reset it with the reset button or the 'new pad...' button. (/cc @lukechurch)

**Comment by filiph** [comment]
*facepalm*

Yes, sorry.

**Comment by filiph** [comment]
I filed issue #735 for the possibly confusing behaviour. Consider it low priority.

**Comment by devoncarew** [comment]
Cool, thanks for the report in any case :)
