### ISSUE TITLE
Make it apparent when a saved pad is reloaded

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#735]
Especially when the pad was saved many weeks/months ago, it's confusing that the (by then long forgotten) code from the past seems to be the default code in DartPad ([example](https://github.com/dart-lang/dart-pad/issues/734)). 

Showing a dialog or toast that says `"You are editing a saved pad from $month $day, $year. Click 'New Pad' to start from scratch."` would make this behaviour explicit.

**Comment by RedBrogdon** [comment]
Once the GitHub integration has been restored/enhanced, we may want to get rid of the "load whatever happens to be sitting in localStorage" behavior in general. I'm adding this to the GH-releated project, so we can figure out the best approach.

**Comment by parlough** [comment]
The new UI doesn't support this save mechanism anymore. If we revisit saving, a solution can be incorporated in that design.
