### ISSUE TITLE
Save strong mode option state in url

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#736]
I'm hoping to share quite a few Dart examples and some of them would really benefit from having the strong mode checkbox enabled when user arrives on DartPad.

**Comment by Sfshaza** [comment]
This is also highly desired as we share strong-mode compliant code.

@filiph @kevmoo @lukechurch

**Comment by Tomucha** [comment]
As one wise man said a long time before me:

> I'm hoping to share quite a few Dart examples and some of them would really benefit from having the strong mode checkbox enabled when user arrives on DartPad.

... and he was right! Let's plug in more Dart advocates (welcome @wmleler) to build up a pressure :-)

**Comment by Tomucha** [comment]
For example this one:
https://dartpad.dartlang.org/c162b1c0eaa37142eeedf3226b47200d

... is not very impressive without strong mode.

**Comment by kasperpeulen** [comment]
maybe just enable strong mode by default?

**Comment by Sfshaza** [comment]
Yes, please! +1

**Comment by srawlins** [comment]
Strong mode is now the only mode.
