### ISSUE TITLE
Should be able to specify <head> contents in HTML tab

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dart-pad#738]
I would like the HTML tab to support adding script fragments in the `<head>`.
Example: this would 'fix' https://github.com/dart-lang/sdk/issues/26850 if added to the raw `.html` file for an app:

``` html
<head>
  <script>
    (dartNativeDispatchHooksTransformer =
      window.dartNativeDispatchHooksTransformer || []).push(function (hooks) {
      var getTag = hooks.getTag;
      hooks.getTag = function (obj) {
        var tag = getTag(obj);
        if (tag == 'ANGLE_instanced_arrays') return 'ANGLEInstancedArrays';
        return tag;
      };
      return hooks;
    });
  </script>
</head>
...
```

It does not work in DartPad since the whole text, including the `<head>`, is injected into the body of the generated `index.html` (see https://gist.github.com/anonymous/69b97d18e0a2ccff8548c0b0c2a42e08)

It appears that this is not trivial since the user provided `<head>` contents would have to be merged and unmerged with the generated `index.html` contents which contains several scripts.
The simplest place to put user `<head>` html would be immediately before the script tag for `main.dart`.

**Comment by kevmoo** [comment]
Interesting idea, but not planned.
