### ISSUE TITLE
Error initializing pirate names: Instance of 'Event'

### ISSUE THREAD

**Issue by marcelmfa** [dart-lang/dart-pad#739]
I was following [code-labs](https://webdev.dartlang.org/codelabs/darrrt#step-five) then i was receiving error that is in subject in my DartPad, then i tried check out your [DartPad](https://dartpad.dartlang.org/eb2a7982598793c8d984) and received same error. I put some print messages on my [DartPad](https://dartpad.dartlang.org/18a6b4dd59c0b37ee97a5b411e3794f8) and the error is trying get JSON file. Am i doing anything wrong?

**Comment by kwalrath** [comment]
This is related to https://github.com/dart-lang/site-webdev/issues/28, which I thought was fixed. @Sfshaza?

**Comment by kevmoo** [comment]
The pirate codelab has been deprecated. Closing out...
