### ISSUE TITLE
Update to 1.22 (or latest)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#743]
I'd love to test Strong Mode, but looks like DartPad is at 1.16.0 and the latest Dart as of the time of this issue is  1.19.1. Thanks!

**Comment by lukechurch** [comment]
We're now upgraded to 1.19.0 - hope that works for you until we roll to 1.20?

**Comment by kwalrath** [comment]
How about 1.21? We have a DartPad that should use the new `=` syntax for setting the default value of a named parameter, but it can't.

**Comment by devoncarew** [comment]
It's in progress :) @lukechurch landed some of the pre-work for that here: https://github.com/dart-lang/compiler_unsupported/pull/43

**Comment by srawlins** [comment]
Bump. Covariant doesn't work.

**Comment by sethladd** [comment]
DartPad is up to 1.21 now. But, Dart is at 1.22 now.

**Comment by mit-mit** [comment]
@lukechurch can we roll again?

**Comment by lukechurch** [comment]
@mit-mit As discussed, this is currently blocked on https://github.com/dart-lang/dart-services/issues/286

We're working on it.

**Comment by devoncarew** [comment]
Dartpad is at 1.23 - there are some PRs in progress to make rolls much easier.
