### ISSUE TITLE
bad error message when calling String.fromEnvironment() as a non-const constructor

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-pad#744]
```
main() {
  print(new String.fromEnvironment("asdf"));
}
```

Results in "Uncaught".

**Comment by skybrian** [comment]
Although the above code works in the Dart VM, the correct code for dart2js is:
```
main() {
  print(const String.fromEnvironment("asdf"));
}
```

And this works in dartpad. So the problem is really that it's a bad error message.

**Comment by zoechi** [comment]
I run into this error as well and saw it mentioned in discussions but other causes.

**Comment by RedBrogdon** [comment]
DartPad currently reports the error with this message:

```
Uncaught exception:
Unsupported operation: String.fromEnvironment can only be used as a const constructor
```

So it looks like this was fixed at some point.
