### ISSUE TITLE
Using lineLength (sic) as a constant name does not work

### ISSUE THREAD

**Issue by enyo** [dart-lang/dart-pad#745]
This fails with the error `Default values of an optional parameter must be constant` in dartpad:

``` dart
const String lineLength = '120';

foo({x: lineLength}) async {
  print(x);
}

main() => foo();
```

Renaming `lineLength` to anything else (eg: `lineLengthX`) works.
This also works in the VM.

I'm not quite sure if this is a dart-pad or a dart-sdk issue.

**Comment by lrhn** [comment]
This example runs correctly for me now.
