### ISSUE TITLE
When strong mode is enabled, we should compile with DDC, not dart2js

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart-pad#746]
... i.e., we should show the _sound_ Dart version of:

http://www.typescriptlang.org/play/#src=var%20ages%3A%20Array%3Cnumber%3E%20%3D%20%5B%5D%0D%0A%0D%0Afunction%20init(whatever%3A%20Array%3CObject%3E)%20%7B%0D%0A%20%20%20%20whatever.push('hello')%3B%0D%0A%20%20%20%20whatever.push('world')%3B%0D%0A%7D%0D%0A%0D%0Ainit(ages)%3B%0D%0Aalert(ages%5B0%5D%20%2B%20ages%5B1%5D)%3B%0D%0A

**Comment by srawlins** [comment]
Dartpad now uses dart2js with Dart 2 semantics, including strong mode. DDC would not provide a _sound_ benefit over dart2js anymore.
