### ISSUE TITLE
Poor error behavior with extended characters

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#748]
Here's a valid program.

void main()
{
  var foo = '𐅆𐅇.';
  print(foo.length);
  print(foo.codeUnits.length);
}

remove the leading quote, and what you get is four question marks in diamonds and errors 
Illegal character 55296
Illegal character 56646
Illegal character 55296
Illegal character 56647
Expected an identifier
Expected an identifier

The program isn't valid,  as we don't allow unicode identifiers, but it would be good if it didn't mutate the source display alarmingly.

**Comment by RedBrogdon** [comment]
I'm no longer seeing this in the current release.
