### ISSUE TITLE
Full web based ide based on dartpad

### ISSUE THREAD

**Issue by gedw99** [dart-lang/dart-pad#749]
This is a little crazy, but using dart pad and code mirror as the basis of a full web based ide makes sense for me.

Code mirror has great support for others gauge like golang too and there is a new agreed start date for code ide service es out this last week with many languages supported.

But why bother ?
I and my tea.s work with lots of mi roservices with lots of data. Coding in the cloud is easier
Ba dwidth usage is really small if the web client part of the ide is done as a SPA, which it is.

We often need to build desktop and mobile GUI's too. With cloud desktops and cloud virtualized mobiles ( saucelabs , etc ) I can easily boot and run them all. 

My teams can have the same dev environment.

But there are strong could get arguments still ....
 GUI developers that rely on fat desktop tools for doing their development will be out of luck. I often need to run code and android studio to write a little bit of code for mobile GUI.

This leads to the question of Why not just run KVM in the cloud with desktop in the cloud per developer in the team ?

Has anyone found a nice way to do this.
Docker is ubiquitous now and easy with docker swarm a d all the nice tracing this.
But what about booting desktops as easily as we boot dockers ?

**Comment by matanlurey** [comment]
I think might be a little too ambitious given other active projects, though I admit nice idea.

Potentially something better than re-writing an IDE would be adding support for [Eclipse Che](https://eclipse.org/che/), which supports the Microsoft [language server protocol](https://github.com/Microsoft/language-server-protocol). It would probably be straightforward to write an adapter around the [Dart analysis server](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server) that supports this protocol.

I don't think anyone on the Dart team can directly work on this, but I imagine would be very supportive of anyone in the community that would like to hack on something.

/cc @devoncarew @yjbanov

**Comment by gedw99** [comment]
thats a good idea.

i understand you cant do everything. I will have a look at it.

**Comment by lukechurch** [comment]
Please let us know if there is anything specific you need help with here. I'd love to see this happen.

I'm going to close this issue to help us keep the issue tracker focussed.
