### ISSUE TITLE
add strong mode enabled check box to embedded DP

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart-pad#750]
I am writing a sound Dart guide and the only way to have the user turn strong mode on/off is by opening the full window version. I would much prefer being able to embed a DP instance.

**Comment by Sfshaza** [comment]
Also, I would like the ability to embed a DP instance with strong mode pre-enabled.

**Comment by matanlurey** [comment]
+1

**Comment by Georgehe4** [comment]
Working on it 👍

**Comment by Sfshaza** [comment]
So good to hear from you, @Georgehe4!
