### ISSUE TITLE
Error reporting when a main method is missing is poor

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#755]
![image](https://cloud.githubusercontent.com/assets/2978182/22228014/554c0f78-e1c6-11e6-8001-a4b948e4afc4.png)

The error should appear in the console rather than 'Uncaught', which results in users thinking the compiler has failed, e.g. in https://github.com/dart-lang/dart-pad/issues/754

**Comment by jcollins-g** [comment]
Fixed in #826.
