### ISSUE TITLE
DartPad is still 1.21.0 :-/

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart-pad#757]

**Comment by lukechurch** [comment]
This is currently blocked on https://github.com/dart-lang/dart-services/issues/286

We're working on both fixing it, and the underlying infrastructure problem that means these upgrades are sometimes challenging.

Sorry for the delay

**Comment by Sfshaza** [comment]
How can I confirm which Dart version DartPad is using?  As we approach Google I/O, can we make sure it's updated to the latest? (Or mostly latest?)

@kevmoo  @filiph  @devoncarew  @lukechurch

**Comment by devoncarew** [comment]
Thanks to @lukechurch and @danrubel, we're back up to stable:

<img width="179" alt="screen shot 2017-04-26 at 3 14 39 pm" src="https://cloud.githubusercontent.com/assets/1269969/25459440/21d747b4-2a93-11e7-86c9-26b30f851dd4.png">

**Comment by devoncarew** [comment]
@Sfshaza, to see the dartpad version, click on the 'Dartpad' name on the upper left.
