### ISSUE TITLE
Fullscreen (or new window?) button in embedded dartpad doesn't work

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/dart-pad#758]
See:
https://dartlang.cz/
or:
https://www.dartlang.org/guides/get-started

"New window" button next to the "Play" button doesn't work.

**Comment by Georgehe4** [comment]
It looks like chrome updates broke some web animations a while back. 
The build will need to upgrade web-animations-js.
Reference: http://stackoverflow.com/questions/40272695/polymer-animate-function-no-longer-working-in-chrome

**Comment by filiph** [comment]
Hi, any way I can help with this bug? Happy to hack on it but I'll need some pointers first.

Here's what's shown in console when I click the "New window" button on https://www.dartlang.org/guides/get-started.

```
imports.html:3201 Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing
    at Object.b.newUnderlyingAnimationForKeyframeEffect (imports.html:14867)
    at b.Animation._rebuildUnderlyingAnimation (imports.html:14866)
    at new b.Animation (imports.html:14866)
    at b.AnimationTimeline._play (imports.html:14866)
    at Object.b.newUnderlyingAnimationForGroup (imports.html:14867)
    at b.Animation._rebuildUnderlyingAnimation (imports.html:14866)
    at new b.Animation (imports.html:14866)
    at b.AnimationTimeline._play (imports.html:14866)
    at b.AnimationTimeline.play (imports.html:14866)
    at HTMLElement._runAnimationEffects (imports.html:15087)
b.newUnderlyingAnimationForKeyframeEffect @ imports.html:14867
_rebuildUnderlyingAnimation @ imports.html:14866
b.Animation @ imports.html:14866
_play @ imports.html:14866
b.newUnderlyingAnimationForGroup @ imports.html:14867
_rebuildUnderlyingAnimation @ imports.html:14866
b.Animation @ imports.html:14866
_play @ imports.html:14866
play @ imports.html:14866
_runAnimationEffects @ imports.html:15087
playAnimation @ imports.html:15112
_renderOpened @ imports.html:16335
(anonymous) @ imports.html:15823
_atEndOfMicrotask @ imports.html:3195
characterData (async)
run @ imports.html:3171
async @ imports.html:3315
_openedChanged @ imports.html:15817
_observerEffect @ imports.html:3556
(anonymous) @ imports.html:3410
_effectEffects @ imports.html:3407
_propertySetter @ imports.html:3392
setter @ imports.html:3468
open @ imports.html:15760
D @ embed.dart.js:9954
$2 @ embed.dart.js:11755
$1 @ embed.dart.js:11756
$0 @ embed.dart.js:11518
dart.wK.$1 @ embed.dart.js:11751
dart.xw.$1 @ embed.dart.js:9368
$0 @ embed.dart.js:2473
d9 @ embed.dart.js:1404
dF @ embed.dart.js:1211
dart.AY @ embed.dart.js:1967
(anonymous) @ embed.dart.js:1975
```

**Comment by devoncarew** [comment]
@filiph, I think this failure (and @Georgehe4's comment) means that we need to update the polymer libraries we're using.

Polymer uses bower for it's package management (although, I think they have or will soon switch to npm). To get the new libs, we'll need to unpin and upgrade one or more packages here: https://github.com/dart-lang/dart-pad/blob/master/bower.json, rebuild, and test to see if things still look good.

Our build script is here: https://github.com/dart-lang/dart-pad/blob/master/tool/grind.dart. The default task will rebuild the front-end (`pub global activate grinder`, and then, `grind`).

@lukechurch, it sounds like the embedding view does have issues. We should probably look to fix it, or remove the `New window` button.

**Comment by Georgehe4** [comment]
I'll send in a PR soon to update polymer.

**Comment by filiph** [comment]
Thanks @Georgehe4!

I see the fix is in. Does that mean it's live? The problem persists at https://www.dartlang.org/guides/get-started
