### ISSUE TITLE
make DartPad use strong mode by default

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#759]
We should toggle DartPad to use strong mode by default.

(somewhat related to https://github.com/dart-lang/dart-pad/issues/736)

@lukechurch

**Comment by lukechurch** [comment]
@devoncarew I've agreed a plan for this with @mit-mit. it's currently awaiting fixes to some regressions in the analyzer that @danrubel is working on (https://github.com/dart-lang/dart-services/issues/286). 

As soon as those fixes go in and we can upgrade the sequence of components that we need to support this.

I'm talking with @danrubel today, I'll see how close we are to being able to upgrade analyzer.

**Comment by lukechurch** [comment]
Now we have bug fixes landed, and the format button in, this is next up.

**Comment by mit-mit** [comment]
Any update?

**Comment by lukechurch** [comment]
@mit-mit When we discussed this last in PDX, there was a desire to synchronise the default bit changing with all the other aspects of the tooling. I'll catch up with you when I'm back from travels in a couple of days.

**Comment by kwalrath** [comment]
We should do this ASAP. People coming to https://www.dartlang.org/guides/get-started see a DartPad with strong mode disabled. That's not good.

**Comment by Georgehe4** [comment]
FYI @kwalrath embedded views can load strong mode on by default by adding the url variable "strong=true" 
[guide]((https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide))

**Comment by Georgehe4** [comment]
Closing.
