### ISSUE TITLE
Caching is disrupting UI rolls

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#766]
We have seen a circumstance twice in recent rolls where the HTML and JS propagate at different rates. For example a button added in HTML appears in the UI, but isn't wired up to the corresponding JS. 

Something is probably wrong on the cache expiry settings of the various resources.

**Comment by Georgehe4** [comment]
Static contents are set to expire every 3 hours through our app.yaml - these can be set to a lower threshold but there are trade-offs to consider.

Ref: https://cloud.google.com/appengine/docs/standard/python/config/appref#static_cache_expiration

**Comment by RedBrogdon** [comment]
I haven't seen this in our recent releases, but it's possible I'm just hard-reloading everything without thinking about it.

@domesticmouse, do you mind checking our cache settings?

**Comment by domesticmouse** [comment]
Given the original description, I’d suspect the issue is actually the delay between rendering the HTML & JS, which is a fairly standard issue for web apps.
