### ISSUE TITLE
React better when an endless loop occurs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#767]
I typed in this program, formatted it (yay!), and ran it:

```
void main() {
  for (int i = 0; i < 5; i++) {
    for (int j = 0; i < 2; j++) {
      print('${j + 1}: hello ${i + 1}');
    }
  }
}
```

Obviously, there's a typo in the inner loop: `i < 2` should be `j < 2`. Oops. The problem is that DartPad completely froze, making me think it was a bug in DartPad (perhaps in the new formatting code) rather than my code. I got no printing at all, and no hint that anything was amiss, other than the UI staying exactly the same, ignoring clicks.

Eventually the browser noticed that the page was unresponsive and let me kill it. When I reloaded the page, I found the problem in the code.

It would be nice if DartPad somehow let me know there was a problem. I don't know HOW it could, but perhaps there could be feedback that it had compiled the code and was running it? A status line/image?

https://dartpad.dartlang.org/4387d88dde41d69776b2b2bd78b6801f has the fixed version of the code.

**Comment by devoncarew** [comment]
This is the same issue as https://github.com/dart-lang/dart-pad/issues/384. It's a tricky one to solve. The change we applied was not auto-running saved gists, which is our current best solution. It's not clear that we'll get a better one -
