### ISSUE TITLE
"What's this?" should link to official docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#772]
![image](https://cloud.githubusercontent.com/assets/2164483/26800745/4084713e-49ef-11e7-8194-6793a55ca461.png)

The "What's this?" link after the Strong mode checkbox links to https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md. Instead it should probably link to something on www.dartlang.org, such as https://www.dartlang.org/guides/language/sound-faq#what-is-strong-mode.

**Comment by lukechurch** [comment]
Ah, excellent, thanks @kwalrath I'll update
