### ISSUE TITLE
DartPad should display the version of Dart being used.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#773]

**Comment by devoncarew** [comment]
You can see it if you click on the `DartPad` text on the upper-left:

<img width="622" alt="screen shot 2017-06-08 at 1 49 51 pm" src="https://user-images.githubusercontent.com/1269969/26950127-77737172-4c51-11e7-81bc-2a7b1f682ee5.png">

**Comment by srawlins** [comment]
Ah ha! I never knew! Good enough for me.

**Comment by devoncarew** [comment]
Yup, useful for a check version check, We print out a bit more info to the devtools console when you open that dialog (a longer version string - which may be the same as the short version, and the codemirror version in use).
