### ISSUE TITLE
DartPad back-end should support multiple versions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#774]
Something like [Rust's](https://play.rust-lang.org/) or [Kotlin's](https://try.kotlinlang.org/#/Examples/Hello,%20world!/Simplest%20version/Simplest%20version.kt).

Even if it's just:

* latest stable
* latest dev
* latest stable - 1

**Comment by matanlurey** [comment]
I'd like to see "nightly" or "latest", but that's a stretch/bonus.

**Comment by jacehensley-wf** [comment]
Would be awesome to at least Dart 2 for now, so we can test stuff out in Dart 2 :)

**Comment by jacehensley-wf** [comment]
Would also be great if we could see the Dart version that is currently being run on dartpad :)

**Comment by devoncarew** [comment]
@jacehensley-wf, it's not well publicized, but you can click on the `DartPad` text on the page to see the current sdk version its based on.

**Comment by srawlins** [comment]
Definitely still +1

**Comment by kwalrath** [comment]
+1

**Comment by filiph** [comment]
This is a feature I'd really love to see, especially now that Dart, as a language, is moving much faster than before, with cool features added several times a year.

It would be super cool to have a separate DartPad (bleeding.dartpad.dev ?) with bleeding edge Dart. This would be where people go try new Dart versions before they are stable & released, without going through the hoops of installing it on their own machine (a dangerous proposition, and a lot of work on Windows in particular).

For example, I'd love to let people play with NNBD and extension methods before they land in stable, so that the first thing they do with these features _isn't_ migrating their huge codebase. Instead, I want people to have fun with these features first.

This would not only have to live on a separate domain (bleeding.dartlang.dev), but it would have to be visually different as well (red banner on top, black and white "under construction" stripes, etc.). I imagine it would also have much lower "SLA" than dartpad proper.

Not only does this give people a sandbox to try new stuff without polluting their dev boxes, it's also a great tool for speakers (GDEs, DevRel).

**Comment by filiph** [comment]
I forgot to say: I think this can be scoped down to much less than was originally asked for:

* Current stable on `dartpad.dev`
* Bleeding edge (dev or nightly) on `bleeding.dartpad.dev`.

**Comment by domesticmouse** [comment]
Running latest dev release on the backend is easy to do, I usually do it leading up to a full release. 

I’d like different versions to be available using a version drop down on DartPad.dev. Easier to find that way 😎

**Comment by RedBrogdon** [comment]
Another request for this came in:

>I used a very similar concept for a different UI framework, and it was very popular to report bug again specific version, and we also used a lot the tool to figure out the exact version a regression was introduced, just by changing the version of the runtime.

>So it would be nice if we could choose the Flutter version, like a dropdown.

**Comment by domesticmouse** [comment]
@srawlins I'm curious about the request for flutter stable -1. What is the use case you are trying to cater for?

**Comment by srawlins** [comment]
I think not Flutter stable -1; More specifically Dart stable -1, I think so that people can check behavior of a recently released stable version with a not-so-recently released stable version.

Like if you've been running on Dart 2.10 for a few months, and after 2.12 is released and you decide to look into upgrading, but see new bugs or different behavior.

**Comment by domesticmouse** [comment]
The current release is the oldest version I can run on Cloud Run as this is the version that contains the fixes required to run sanely on Cloud Run. After the next release I'm happy to keep the current Dart 2.10 around as say `old.api.dartpad.dev` alongside `stable.api.dartpad.dev` running Dart 2.12, `beta.api.dartpad.dev` running Dart 2.13.pre and `dev.api.dartpad.dev` running whatever dev is running.

Sound reasonable?

**Comment by srawlins** [comment]
This sounds excellent to me! @matanlurey had said "nightly" would be amazing, and I think "dev" is more-or-less that? We cut a dev release every ~2 days I think?

Thanks so much, I'm excited!

**Comment by domesticmouse** [comment]
Rolling servers is a manual process, so expect some lag on updates. I try to update beta and stable day of release, but dev may turn into a once a week maintenance task.

**Comment by parlough** [comment]
To be honest I'm not sure how much use dev has over beta, especially with a manual update process.

**Comment by domesticmouse** [comment]
Dev can get up to three weeks ahead of beta, so it is useful for understanding if bugs found in beta have been fixed after the last beta cut. 

It's useful for us, and the manual work is ~10 minutes to author and push a PR to github. The rest of the rollout is automated by Cloud Build and Cloud Run.

**Comment by srawlins** [comment]
I think we'll go with three channels to start:

* Flutter stable
* Flutter beta
* Flutter dev

But these can be presented so that they're friendly for non-Flutter use cases too. [Rust's playground](https://play.rust-lang.org/) has a nice version switcher which describes each option in 3 lines of text. We could do something simpler, like:

> **Flutter stable**
> Flutter 2.2.3 and Dart 2.13.4

@domesticmouse also has a "previous stable" which we could launch as well. "Flutter previous" or something. The name isn't super important because the version numbers will be written right there.

I think this switcher should live right next to the null safety toggle.

**Comment by domesticmouse** [comment]
I just checked, and Flutter old (aka "previous stable") is [currently running Flutter 2.0](https://github.com/dart-lang/dart-services/blob/flutter-old-branch/flutter-sdk-version.yaml). I suspect it is worth including in the mix for when we roll stable forward and people want to check if code if code that is broken in the new stable was working in the previous stable.

**Comment by srawlins** [comment]
Closing my own feature request 4 years later. 🚀
