### ISSUE TITLE
Change the "What's this?" link for strong mode

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#779]
It currently links to https://github.com/dart-archive/dev_compiler/blob/master/STRONG_MODE.md.

It should link instead to https://www.dartlang.org/guides/language/sound-dart.

**Comment by devoncarew** [comment]
This has been done, but we haven't pushed an updated version of the front end.

@lukechurch

**Comment by lukechurch** [comment]
New front end is serving. Thanks @kwalrath

**Comment by kwalrath** [comment]
Thanks, @lukechurch!
