### ISSUE TITLE
Can't share new pads

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart-pad#784]
When I click share I get this uri: https://dartpad.dartlang.org/null

**Comment by devoncarew** [comment]
Is it reproable? I can share a pad: https://dartpad.dartlang.org/903b75ffb3797fdedd26c977b3a1d9dc

/cc @lukechurch

**Comment by jakemac53** [comment]
It was for a few minutes, but its working for me now. Maybe just a github gist outage?

**Comment by devoncarew** [comment]
Likely, but we should make sure that those error messages are surfaced.
