### ISSUE TITLE
Cannot start dartpad, depends on window size

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/dart-pad#785]
I encountered a strange error. I wasn't able to start Dart pad. Only part of UI appeared and in console I found:

Uncaught Error: FormatException: 950,406

I'm running Chrome: 61.0.3163.100.

It depended on window size - small window: no error, wide window:
Uncaught Error: FormatException: 922,797

Also it probably depended on local storage state, error didn't occurre in anonymous window.

Today the error is gone, and I cannot reproduce it.

**Comment by RedBrogdon** [comment]
Closing as unreproducible.
