### ISSUE TITLE
DartPad production release

### ISSUE THREAD

**Issue by Georgehe4** [dart-lang/dart-pad#789]
As resolved in #758, the embedding views for DartPad has been fixed and should be released to production when possible. 

Besides release to production, the release scripts and guide will need to be updated as well.

**Comment by devoncarew** [comment]
My memory of how to do the front-end roll is somewhat hazy, and likely out of date as well; @lukechurch would be your best resource here :)

**Comment by Georgehe4** [comment]
Update: Production release is planned for 11/13.

**Comment by Georgehe4** [comment]
Release is now live. Closing issue.
