### ISSUE TITLE
Console warnings in pages with embedded DartPads

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#791]
dart-lang/site-www#422 reports 3 Chrome console warnings in at least 4 pages, all of which have embedded DartPads. (No warnings appear in other, non-DartPad-containing pages that I've spot checked, such as www.dartlang.org and www.dartlang.org/dart-2.0.)

I also see console warnings in those pages (but 2, not 3). For example, here are the warnings for https://www.dartlang.org/guides/get-started:

* [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
* [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

I'm using Chrome Canary: Version 64.0.3261.0 (Official Build) canary (64-bit).

**Comment by Georgehe4** [comment]
The polymer components are out of date and will need to be updated in the near future.

**Comment by kwalrath** [comment]
Thanks, @Georgehe4!

@devoncarew please let us know when the changes go live, so I can close this issue.

**Comment by Georgehe4** [comment]
The changes should be live now. There will still be warnings but there will
be no impact on anything the users see in their browser.
Hopefully polymer will update their build process to remove the warnings
soon.

**Comment by kwalrath** [comment]
Ah, OK, I'll leave this open then. I currently see 4 browser warnings in https://www.dartlang.org/guides/get-started:

```
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M67, around May 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
imports.html:11890 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
imports.html:12193 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
```

**Comment by chalin** [comment]
The deprecation notice deadline is approaching:

> planned to be removed in M67, around May 2018

Any update on this. Btw, this impacts both https://www.dartlang.org and https://webdev.dartlang.org.

**Comment by Georgehe4** [comment]
Hey @chalin, the deprecation notices will be present until https://github.com/Polymer/polymer/issues/4679 is addressed. The site will still function after the /deep/ combinator is removed.

**Comment by jcollins-g** [comment]
Compilation failed warnings seem to be the result of some kind of initialization timing race.  It's reproducible locally in the embedder_demo.html that loads Hello World, and results in the program not being correctly auto-run by the embedder.

**Comment by jcollins-g** [comment]
The Uncaught Errors on page load are caused by attempting to compile a gist that hasn't loaded yet, here:

https://github.com/dart-lang/dart-pad/blob/4f3c839eeee93e6812690a803b32e42510f8acba/lib/embed/embed.dart#L102

**Comment by RedBrogdon** [comment]
The polymer warnings will persist until the new embed UI replaces the current embed UI. I'm not seeing any CodeMirror-related warnings at this point.

**Comment by chalin** [comment]
Is this issue still relevant -- are the original warnings still being issued?

**Comment by RedBrogdon** [comment]
@johnpryan swapped the new embed UI for the old one a while back, so there should no longer be any polymer code loading into anyone's browser. This should be closed at this point.
