### ISSUE TITLE
Make Strong mode sticky rather than enabled by default

### ISSUE THREAD

**Issue by marianamarasoiu** [dart-lang/dart-pad#793]
I work with Dartpad quite a bit at the moment (prototyping UIs and saving them as gists for future reference) and the recent change to have Strong mode enabled by default doesn't really work for me, as it's showing new errors in almost all of my gists (errors which will actually never cause errors when running the code).

I can see how it's useful to have Strong mode for some type of coding, but I'm using it for quickly prototyping interactions (which I don't think it's that unusual?). This means that I don't want my code to be too bureaucratic, and I feel Strong mode is encouraging that a little.

For example, this works fine without strong mode:

```
import 'dart:html';

void main() {
  querySelectorAll('td').forEach((TableCellElement cell) {
    print('${cell.cellIndex}');
  });
}
```

But with strong mode I get the following error:
`The argument type '(TableCellElement) → Null' can't be assigned to the parameter type '(Element) → void'.`

What I would have to write instead is:
```
import 'dart:html';

void main() {
  querySelectorAll('td').forEach((Element element) {
    TableCellElement cell = element;
    print('${cell.cellIndex}');
  });
}
```

I know the difference is basically a single line, but it feels like I shouldn't need to basically declare the element twice in order to get working code completion and no errors.

I don't know if this was the case before, but I feel like a better compromise would be to have Strong mode sticky rather than enabled by default (either once enabled for a user it stays enabled, or once enabled for a gist it stays enabled for that gist).

Thanks for considering this!

**Comment by Georgehe4** [comment]
Hi Mariana,

Thanks for filing this bug!

Right now, you can disable/enable strong mode on load by changing the query options in the URL.
[example](https://dartpad.dartlang.org/72d83fe97bfc8e735607?strong=false)

**Comment by marianamarasoiu** [comment]
Hi George,

Thanks for the suggestion, I think I will be making use of it :)

However, I still see as problematic the Strong mode behaviour that I highlighted above, though perhaps this is more a language problem rather than a Dartpad problem.

**Comment by matanlurey** [comment]
Hi @marianamarasoiu 

Strong-mode will be required in Dart2, so I'm not sure it is too valuable to make it easier to accidentally not use it. I'm closing this for now.
