### ISSUE TITLE
LinkedHashMap not on classpath

### ISSUE THREAD

**Issue by branflake2267** [dart-lang/dart-pad#808]
Is the LinkedHashMap not loaded on the classpath? 

![screen shot 2018-04-12 at 8 19 00 pm](https://user-images.githubusercontent.com/1326504/38715232-ca913ee0-3e8e-11e8-8351-42388f2924c2.png)

And map.update doesn't seem to exist either, so which version of Dart is being used? Could the Dart version be listed on the footer?

**Comment by devoncarew** [comment]
It's based on 1.25 (with plans to update). If you click on the `DatPad` title in the page, it'll show the about box w/ the current version:

<img width="187" alt="screen shot 2018-04-12 at 8 42 37 pm" src="https://user-images.githubusercontent.com/1269969/38715791-28ba2560-3e92-11e8-8fd1-3f4b9a6a4df6.png">

**Comment by devoncarew** [comment]
see also https://github.com/dart-lang/dart-services/issues/334

**Comment by branflake2267** [comment]
ah ha, so you can click on the DartPad title to get that. Thanks that helps me understand what the options are. Looks like this is a duplicate.
