### ISSUE TITLE
Certain Code Causes Chrome to Start Gradually Consuming Ram

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [dart-lang/dart-pad#809]
Here's the link to my innocent code. [Digital Dice Practice Code](https://dartpad.dartlang.org/202345d1888a0cd139f6ec2adf246834)

**Comment by RedBrogdon** [comment]
Closing this for now as unreproducible, as I'm not seeing an increase in RAM usage with that code in the editor. If the problem still persists for you, just re-open the bug.
