### ISSUE TITLE
Is it possible to switch to angular-dart?

### ISSUE THREAD

**Issue by xiongxin** [dart-lang/dart-pad#810]
In Future,Is it possible to switch to angular-dart?

**Comment by devoncarew** [comment]
@xiongxin, can you provide more details? Do you mean to host angular-dart samples in DartPad?

**Comment by xiongxin** [comment]
@devoncarew i mean is use angular-dart rewrite DartPad

**Comment by devoncarew** [comment]
The specific tech the UI is written in isn't super important to DartPad's actual function, and given that it's already written, a re-write that just changed tech stacks would have to provide a lot of value to be worth the cost.

Thanks for the inquiry!
