### ISSUE TITLE
Update favicon to use new Dart logo

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#811]
cc @kwalrath @JekCharlsonYu

**Comment by chalin** [comment]
Let me know which resolutions you'd like in that .ico and I can create one for you. That one was created using:

    convert dart/logo/default.png -define icon:auto-resize=128,64,48,32,16 dart/favicon.ico

You might not need that many sizes.

**Comment by chalin** [comment]
(If there is a general agreement on which sizes are needed, I can change the main favicon.ico file too.)

**Comment by devoncarew** [comment]
We should likely have a single one we can apply to all dart web properties. From some very casual browsing, we should be good with just 16x16 and 32x32.

I don't know how efficient `convert` is in terms of the size of the file it produces (I don't know that it isn't either, but we may want to check on it).

**Comment by devoncarew** [comment]
> If there is a general agreement on which sizes are needed, I can change the main favicon.ico file too

Sounds great! I'm happy to use whatever we end up using for dartlang.org.

**Comment by chalin** [comment]
flutter.io uses a single 64x64 PNG. I'm inclined to do the same for darglang.org. Does that work for you?

**Comment by devoncarew** [comment]
👍

**Comment by chalin** [comment]
Done: you can pick up assets from, e.g., https://github.com/dart-lang/site-www/pull/835/files.

**Comment by devoncarew** [comment]
Thanks!
