### ISSUE TITLE
push a new version of the front end

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#813]
We should push a new version of the front end in order to capture the change to the favicon (see https://github.com/dart-lang/dart-pad/pull/812).

@Georgehe4, are you available to do the push? You'll need to build the front end with `2.0.0-dev.35.0` of the sdk (due to the removal of pub build/serve from later SDKs).

**Comment by Georgehe4** [comment]
The new version is up and running, icon has been updated!
