### ISSUE TITLE
websocket example constructor for WebSocketTest references the global, not the passed in URL

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/dart-pad#828]
It should look like this (verified working):

```
  WebSocketTest(this.url) {
    print("Connecting to ${url}…");
    _socket = new WebSocket(url);
    _startListening();
  }
```

**Comment by devoncarew** [comment]
Thanks for the report! FYI, that sample is backed by https://gist.github.com/devoncarew/479ecba5a56fd706b648.

**Comment by devoncarew** [comment]
fixed in https://gist.github.com/devoncarew/479ecba5a56fd706b648/revisions#diff-4eb8e8f3607973b6331abc75de81c06a
