### ISSUE TITLE
Uncaught errors aren't printed anymore

### ISSUE THREAD

**Issue by alanrussian** [dart-lang/dart-pad#830]
They used to be but aren't any longer.

**Comment by jcollins-g** [comment]
@alanrussian Do you have an example where this is the case?  Uncaught errors seem to work in the cases I've tried.

**Comment by jcollins-g** [comment]
Maybe this is another instance of #836?

**Comment by jcollins-g** [comment]
Closing, please reopen if you have an example.

**Comment by alanrussian** [comment]
Sorry for not replying. I'm not noticing this now. I'll reopen if I notice it again. Thanks!
