### ISSUE TITLE
Upgrade to Dart 2.0.0

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#845]
cc @kevmoo @kwalrath

**Comment by jcollins-g** [comment]
Problems in the bowels of our dependencies to sort through.
```
~/dart/dart-services
$ pub get
Resolving dependencies... (1.5s)
The current Dart SDK version is 2.0.0.

Because no versions of rpc match >0.6.0-dev.1 and rpc 0.6.0-dev.1 depends on gcloud >=0.2.0+12 <0.6.0, rpc >=0.6.0-dev.1 requires gcloud >=0.2.0+12
  <0.6.0.
So, because gcloud >=0.1.0 <=0.6.0 requires SDK version >=1.5.0 <2.0.0 or >=2.0.0-dev.54.0 <2.0.0 and dart_services depends on rpc >=0.6.0-dev.1,
  version solving failed.
```

**Comment by jcollins-g** [comment]
@kevmoo helped with that one in dart-lang/rpc#131 but there's more to knock out.

```
~/dart/dart-services
$ pub get
Resolving dependencies... (1.5s)
The current Dart SDK version is 2.0.0.

Because appengine >=0.4.4+1 depends on gcloud ^0.5.0 and appengine >=0.2.0
  <=0.4.4 requires SDK version >=1.5.0 <2.0.0, appengine >=0.2.0 requires gcloud
  ^0.5.0.
Because gcloud 0.5.0 requires SDK version >=2.0.0-dev.54.0 <2.0.0 and no
  versions of gcloud match >0.5.0 <0.6.0, gcloud ^0.5.0 is forbidden.
Thus, appengine >=0.2.0 is forbidden.
So, because dart_services depends on appengine >=0.4.0, version solving
  failed.
```

**Comment by kevmoo** [comment]
We likely need to get Martin Kusterman involved w/ reviews to pkg:appengine
– but you could get a PR going

**Comment by jcollins-g** [comment]
yeah.  it's not going to be completely trivial.  gcloud breaking changes impact this

**Comment by kevmoo** [comment]
:-/

**Comment by jcollins-g** [comment]
another package protobuf has problems that are fixed, but not published.  https://github.com/dart-lang/protobuf/pull/117

**Comment by jcollins-g** [comment]
The appengine package also has problems, but I'm part-way through a fix.  https://github.com/dart-lang/appengine/issues/80

**Comment by jcollins-g** [comment]
Protobuf problems are fixed and published.  Appengine has a fix (dart-lang/appengine#81), and I've got test versions of dart-services and dart-pad that work with 2.0 now.

**Comment by jcollins-g** [comment]
#846 for the front-end

**Comment by jcollins-g** [comment]
Remaining blockers are gone with the recent appengine publish; when the backend change at dart-lang/dart-services#350 lands and is deployed we can close this out.  Hoping to do this Monday.

**Comment by chalin** [comment]
Great! Can you let us know once it is live?

**Comment by jcollins-g** [comment]
will do.

**Comment by jcollins-g** [comment]
2.0.0 stable is now live, will monitor closely for a while for problems in case we need to revert.  But if you hear nothing else back on this issue, you can assume we're good.
