### ISSUE TITLE
Cursor/selection issues in embedded DartPad

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#847]
This might be a Chrome bug or a embedded DartPad bug. Here's how I found it:

1. I went to https://kw-www-dartlang-1.firebaseapp.com/tutorials/language/futures#async-and-await in Chrome Canary 70.0.3517.0 (Mac). 
2. I tried to insert a type before `printDailyNewsDigest`. The display jumped, and the cursor looked like it was 2 lines above (before `import`).
3. I tried double-clicking `printDailyNewsDigest`. The display jumped, and the selection was in `print` (2 lines below).
4. I tried using the arrow key to move the cursor, with similar issues.

This feels familiar, like I've seen it elsewhere recently, but I can't recall where. The run and "open in its own window" buttons work fine, and DartPad works fine when it's in its own window.

**Comment by chalin** [comment]
I can see similar behavior under Chrome, but only when the display is narrow enough that the type information on the right wraps:

<img width="780" alt="screen shot 2018-08-14 at 13 02 44" src="https://user-images.githubusercontent.com/4140793/44106345-66d2e918-9fc2-11e8-8dd2-91711b324368.png">

In the view above, I positioned my cursor just before `printDailyNewsDigest` and it eventually landed here (at the ^): `import '^dart:async';`

**Comment by kwalrath** [comment]
@devoncarew and @jcollins-g, this is a pretty serious bug. I'm working on this page right now and seriously considering removing the embedded DartPad.

**Comment by devoncarew** [comment]
I see this in canary (v70), but not in chrome stable. I wonder if this is an issue in canary that will be fixed before it moves to stable, or whether it's changed expectations in Chrome, and we'll need to rev to a newer version of codemirror to get the fix.

**Comment by devoncarew** [comment]
Actually, I do see it in stable now when (as @chalin says), the doc view on the left is narrow enough.

**Comment by devoncarew** [comment]
@kwalrath, I haven't done a lot of digging here, but suspect this is some layout interaction with web components and codemirror.

To work around this, you could switch from referencing the embedding that displays documentation (`embed-dart.html`) to the embedding without - `embed-inline.html`.

**Comment by kwalrath** [comment]
Thanks, Devon, I'll try that.

**Comment by kwalrath** [comment]
That workaround works (and also looks better).

**Comment by RedBrogdon** [comment]
I'm adding this to the list of Q1/Q2 changes, mainly so I'll remember to double-check that this problem is not replicated in the new embedding UI.
