### ISSUE TITLE
dartlang.org embedded dartpad errors

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#848]
Visiting this page https://www.dartlang.org/guides/language/language-tour, results in these errors in the console:

```
html_dart2js.dart:17312 GET https://api.github.com/gists/589bc5c… 403 (Forbidden)
js_primitives.dart:28 Error loading gist 589bc5c95318696cefe5.
Instance of 'bd'
html_dart2js.dart:17700 POST https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json 400 ()
js_helper.dart:1763 Uncaught Error: DetailedApiRequestError(status: 400, message: main.dart:
Error: No 'main' method found.

Error: Compilation failed.
)
    at Object.c (js_helper.dart:1763)
    at xi.dart.xi.$1 (clients.dart:881)
    at vy.eg (zone.dart:1379)
    at uN.$0 (future_impl.dart:129)
    at Object.cV (future_impl.dart:671)
    at N.b2 (future_impl.dart:476)
    at Object.wW (stream_pipe.dart:63)
    at tb.dart.tb.$1 (stream.dart:1145)
    at vy.cg (zone.dart:1314)
    at vI.aH (stream_impl.dart:336)
html_dart2js.dart:17700 POST https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json 400 ()
```

I believe that this is due to DartPad issues. I don't think that it is because of the code shown in the DartPad, but I could be wrong.

cc @kwalrath @kevmoo

**Comment by kwalrath** [comment]
I'm not seeing that in Version 70.0.3530.0 (Official Build) canary. What version are you using?

**Comment by chalin** [comment]
I'm not seeing it anymore. Maybe it was just a temporary (server refresh / unavailable) glitch. Closing for now.

**Comment by chalin** [comment]
It's happening again now. So I'll leave this open.

**Comment by RedBrogdon** [comment]
Just tried and failed to replicate this. Currently running Chrome 71.0.3578.98 (Official Build) (64-bit).

**Comment by RedBrogdon** [comment]
Still can't replicate. Closing for now, but people are more than welcome to reopen.
