### ISSUE TITLE
add support for the new super mixins

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#850]
This has two parts:

- [x] updating the backend with analysis and compile support, when the implementations are ready
- [ ] updating the front-end with the new syntax highlighting; this depends on a new publish of codemirror.dart, which itself needs a new release of the codemirror library (the change to codemirror JS is already in, and releases can be tracked here: https://github.com/codemirror/CodeMirror/releases)

**Comment by devoncarew** [comment]
Overall feature tracking issue here: https://github.com/dart-lang/language/issues/12

**Comment by jcollins-g** [comment]
mixin keyword will not be highlighted until this gets done.

**Comment by jcollins-g** [comment]
Backend is working, and even without this the supermixin support is probably enough for day one, so not a blocking bug.

**Comment by devoncarew** [comment]
done?

**Comment by jcollins-g** [comment]
@devoncarew I thought there was some syntax highlighting that we wanted, even if it wasn't completely blocking

**Comment by devoncarew** [comment]
Hmm, yes, I forgot. We need to update (https://github.com/google/codemirror.dart/blob/master/updating_codemirror.md) codemirror.dart to the latest, and then publish that package.

> let me know and I can try and chase it down

If you'd like to do it, sounds great; I'm having some issues running (and updating) bower on my machine

**Comment by RedBrogdon** [comment]
CodeMirror was updated as a side-effect of our work on the new embed UI. It looks like this is working to me.

Just tested with:

```
class blah with Musical {}

mixin Musical {
  bool canPlayPiano = false;
  bool canCompose = false;
  bool canConduct = false;

  void entertainMe() {
    if (canPlayPiano) {
      print('Playing piano');
    } else if (canConduct) {
      print('Waving hands');
    } else {
      print('Humming to self');
    }
  }
}

void main() {
  final b = blah();
  b.entertainMe();
}
```

I'm seeing correct highlighting for the mixin keyword, and no weird warnings/errors.
