### ISSUE TITLE
Redirect Chinese IPs to dartpad.cn

### ISSUE THREAD

**Issue by taylorren** [dart-lang/dart-pad#851]
I am in China. `dartlang.org` is accessible but `dartpad.dartlang.org` is not (and requires a VPN connection).

Today, I found out that:

1. Using VPN hosted in my US VPS (tr@rsywx): can't access dartpad, even not able to `lynx https://dartpad.dartlang.org` in a SSH session. The IP is in range 104.224.X.X
2. Using VPN hosted in my Germany VPS (tr@btqun): can access and can `lynx` to the site. The IP is in range 172.104.X.X. 

Please see below screenshot for a quick reference. 

![ashampoo_snap_2018 9 9 _07h54m17s_002_](https://user-images.githubusercontent.com/3853711/45259752-6f9a8080-b406-11e8-8405-2c5c751d25e7.png)

Is it an IP blockade specifically to my IP? Please help!

**Comment by kwalrath** [comment]
@taylorren could you please try https://dartpad.cn/?

**Comment by kevmoo** [comment]
Could/should we redirect here? Or provide a link in the UI?

AppEngine gives us headers we can use to detect source country...

**Comment by RedBrogdon** [comment]
@domesticmouse How feasible/advisable is it to add redirects to dartpad.cn?

**Comment by domesticmouse** [comment]
The usual issue with firewalls is that we never see the packets, due to said firewall, so there is nowhere for us to send a redirect from. This isn’t something we can fix inside of DartPad.
