### ISSUE TITLE
PI should be rewritten with pi in gist at Sharing Guide

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/dart-pad#852]
The Instruction "[Sharing Guide · dart-lang/dart-pad Wiki · GitHub](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide "Sharing Guide · dart-lang/dart-pad Wiki · GitHub")" links to a runnbale DartPad of Solar System, but currently it fails to compile because of old math constants PI.

**Comment by Cat-sushi** [comment]
Sunflower fails as well.

**Comment by kwalrath** [comment]
@devoncarew, these gists need to be updated (or removed from the wiki page):

https://gist.github.com/72d83fe97bfc8e735607
https://gist.github.com/devoncarew/9d2dd2ce17981ecacadd

**Comment by devoncarew** [comment]
I think the solar one needs to be removed, and sunflower updated to point to the latest gist id.

**Comment by kwalrath** [comment]
I can do it, if you like.

**Comment by devoncarew** [comment]
Sounds great, that would be appreciated :)

**Comment by kwalrath** [comment]
Done. Thanks for the report, @Cat-sushi!
