### ISSUE TITLE
move privacy notice to dartlang.org

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dart-pad#853]
Move the wiki here:  https://github.com/dart-lang/dart-pad/wiki/Privacy-Policy to somewhere on dartlang.org.  Rename it to "privacy notice", and consider rewriting the section on source code retention (those are no longer retained beyond the HTTP log rotation times AFAICT).

**Comment by kwalrath** [comment]
The page is up on dartlang.org: https://www.dartlang.org/tools/dartpad/privacy
