### ISSUE TITLE
Embed support on Medium

### ISSUE THREAD

**Issue by letsar** [dart-lang/dart-pad#854]
Thanks for this great tool 👍 !

It would be great to be able to embed the DartPad editor on [Medium](https://medium.com/).

From the [Medium help center](https://help.medium.com/hc/en-us/articles/214981378-Embeds):

> Embeds on Medium are handled through [Embed.ly](http://embed.ly/), a dedicated embedding service.

> There is no cost to becoming a supported provider on Embedly—and if you do, your embedded content should also work on Medium.

At this time, DartPad don't seem to be a supported embed provider, and in order to be supported it must meet the following requirements:

> - The embed needs to be novel, in that it provides some functionality to the end user. i.e play a video, scroll through a Behance portfolio or view a slideshow.
> - Your URLs and pages must be crawlable server side.
> - The embed must be responsive and, at minimum, work between 280 and 800 pixels.
> - The embed must work over HTTPS.
> - If the embed is a video or audio embed, it must support [Player.js](http://playerjs.io/) and pass all [tests](http://playerjs.io/test.html).
> - Your site needs to support oEmbed as way for Embedly to reliable match a URL to a piece of content. Please test with our [oEmbed validator](https://embed.ly/providers/validate/oembed) before submitting, this will ensure you pass the basic requirement tests.
> - If your embed is an IFrame, you must accept a "referrer" parameter as part of the source. This allows Embedly to pass along the actual page your embed is on.
> - We do not accept script tag embeds. These embeds do not work via client side API requests and most of our customers will not accept them. Please use an iframe embed instead.
> - If your embed is not responsive by height or have a predictable height, you may optionally implement [height control](http://docs.embed.ly/v1.0/docs/provider-height-resizing). Note: this will only work on sites that use Embedly javascript integration.
> - After your site is added as an Embedly provider you will write a short announcement to your users that your content is available through Embedly.

I don't know if DartPad meets them, but if it does, can you consider to add it as a supported provider?

For more information on the registration process: https://embed.ly/providers/new

**Comment by RedBrogdon** [comment]
> The embed must be responsive and, at minimum, work between 280 and 800 pixels.

That could be a dealbreaker for an embedded editor. Still, it would be nice to enable embeds on Medium.

**Comment by Anirudhk07** [comment]
It would be easy for developers to showcase their projects step by step if dart pad is enabled on Medium.
Much Awaited Feature !!!

**Comment by kwalrath** [comment]
A workaround is to use CodePen's support to embed a Pen. For an example, see the embedded Pen near the bottom of the [Flutter CodePen challenge announcement](https://medium.com/flutter/flutter-codepen-challenge-689beedf6ce6).

**Comment by johnpryan** [comment]
This is not something we can support right now, Medium [uses a third-party embedder](https://help.medium.com/hc/en-us/articles/214981378-Using-embeds) that is limited to card-like UI. This could be something that a lighter-weight editor (https://github.com/dart-lang/dart-pad/issues/2) might help solve, but right now isn't actionable.
