### ISSUE TITLE
Update service Dart 2.1

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-pad#861]
Necessary to support 2.1 samples

**Comment by jcollins-g** [comment]
@kevmoo  Test version available at: https://jcollins-210dev71-test-dot-dart-pad.appspot.com/

**Comment by kevmoo** [comment]
We're not going to roll the site until 2.1 is officially launched. ETA Nov 5

**Comment by jcollins-g** [comment]
@kevmoo : We're not going to roll the site until 2.1 is officially launched.

**Comment by jcollins-g** [comment]
OK.  To be ready to launch, we need to get your 2.1 samples into gists and
add them to the sample lists in a PR like
https://github.com/dart-lang/dart-pad/pull/865.

Janice

**Comment by jcollins-g** [comment]
OK.  To be ready to launch, we need to get your 2.1 samples into gists and
add them to the sample lists in a PR like
#865.

**Comment by jcollins-g** [comment]
@kevmoo would you like me to prep your samples in gists?

**Comment by kevmoo** [comment]
On it...

**Comment by jcollins-g** [comment]
Currently at least partially blocked by https://github.com/dart-lang/sdk/issues/35009  and https://github.com/dart-lang/rpc/issues/133.  I may have a workaround (it looks like the bug might not impact the actually used-by-dartdoc portions of the dart-services API) but I have to check to be sure.

**Comment by jcollins-g** [comment]
Closing -- not planning any further Dart 2.1 launch related deployments.
