### ISSUE TITLE
Update to the latest versions of the polymer components

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#870]
We should update to the latest versions of the polymer components (and ensure that the embedded UIs continue to work).

**Comment by jcollins-g** [comment]
dart-pad is on a 1.x polymer and the current is 3.x.  Considering the best way to do this; might be to update to Polymer 2.x first.

**Comment by jcollins-g** [comment]
Some experimentation suggests this is indeed a good strategy.  The update from 1.x to 2.x is well documented but tedious, and the 2.x to 3.x update will have us remove the use of bower, switch fully to npm, and has some automated support.

**Comment by jcollins-g** [comment]
Since the motivation for this is to clear out a list of specific problems I'm moving away from this as a strategy to address that list.

**Comment by jcollins-g** [comment]
Moved versions of all in use code up to resolve some alerts, and identified the remaining alerts as not being applicable since the code from dev dependencies in our dependencies is not used.

**Comment by jcollins-g** [comment]
Yes, we don't need this issue any longer, closing.
