### ISSUE TITLE
Update WIKI emebedding srction

### ISSUE THREAD

**Issue by pezi** [dart-lang/dart-pad#874]
...
A sample URL would be https://dartpad.dartlang.org/embed-html.html?id=72d83fe97bfc8e735607&verticalRatio=80
...
Solar example does not compile. Uses PI instead pi as const.

**Comment by kwalrath** [comment]
Let's use one of the dartlang.org URLs, since we're actually testing them.

**Comment by kwalrath** [comment]
How about this one:
https://dartpad.dartlang.org/embed-inline.html?id=5d70bc1889d055c7a18d35d77874af88&verticalRatio=60

It's in the https://www.dartlang.org/guides/language/language-tour#anonymous-functions section.

**Comment by RedBrogdon** [comment]
Updated!
