### ISSUE TITLE
Not working well with Android

### ISSUE THREAD

**Issue by prateeksingla** [dart-lang/dart-pad#876]
Dartpad does not work on Android based mobile.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/2751 which discusses adding a responsive layout for mobile. There have been recent improvements in https://github.com/dart-lang/dart-pad/commit/7375a5442e854bc20965930271e488fa643634f5 and more are planned. If you experiences issue or have suggestion relative to the current state, please let us know with a new issue and we're happy to accept PRs too. Thanks! <3
