### ISSUE TITLE
Incorrect code on flutter.io docs

### ISSUE THREAD

**Issue by mirkancal** [dart-lang/dart-pad#880]
https://flutter.io/docs/get-started/flutter-for/react-native-devs#futures

In Flutter for React Native document, on the Futures part. Probably due to updates on dartlang.

The code on dartpad
```
import 'dart:convert';
import 'dart:async';
import 'dart:html';


void main(){
_getIPAddress() {
  final url = 'https://httpbin.org/ip';
  Future<HttpRequest> request = HttpRequest.request(url);
  request.then((value) {
      print(JSON.decode(value.responseText)['origin']);
  }).catchError((error) => print(error));
}
  _getIPAddress();
}
```

And throwing errors. I'm new in dart and flutter but should be that:

```
import 'dart:convert' as JSON;
import 'dart:async';
import 'dart:html';


void main(){
_getIPAddress() {
  final url = 'https://httpbin.org/ip';
  Future<HttpRequest> request = HttpRequest.request(url);
  request.then((value) {
      print(JSON.jsonDecode(value.responseText)['origin']);
  }).catchError((error) => print(error));
}
  _getIPAddress();
}
```

**Comment by olliebennett** [comment]
Yep - also came across this problem; I fixed by changing `JSON` to `json` (which is how the text snippet appears on the page).

The problematic DartPad link is https://dartpad.dartlang.org/96e845a844d8f8d91c6f5b826ef38951

**Comment by olliebennett** [comment]
Since this isn't a DartPad issue itself, I think [this issue on the flutter website repo](https://github.com/flutter/website/issues/1880) is a more appropriate place for this feedback; let's move discussion there.

**Comment by kwalrath** [comment]
Agreed. Closing in favor of flutter/website#1880.
