### ISSUE TITLE
`.hashCode` strange behavior on DartPad

### ISSUE THREAD

**Issue by amirh** [dart-lang/dart-pad#881]
The following snippet throws when running on DartPad:

```dart
void main() {
  String v = null;
  print('${v.hashCode}');
}
```

It throws:
```
Uncaught exception:
Cannot read property '$identityHash' of null
```

Note that running the exact same snippet locally (Dart VM version: 2.1.0-dev.9.4.flutter-f9ebf21297) works.

**Comment by johnniwinther** [comment]
It's the filtering by static types that got a bit to aggressive; i.e. Null is potential target of subtypes of String. A fix is in the pipeline:  https://dart.googlesource.com/sdk/+/b5d2400d821ea00cd53a7b44269576b6da17f9fc

**Comment by jcollins-g** [comment]
Closing -- fix will be in the next stable release of Dart/Dart-pad.
