### ISSUE TITLE
Grind Task does not exist

### ISSUE THREAD

**Issue by amadeu01** [dart-lang/dart-pad#883]
In the [guide](https://github.com/dart-lang/dart-pad/blob/master/CONTRIBUTING.md)

We can find 

```bash
cd ..
git clone git@github.com:dart-lang/dart-services.git
cd dart-services
pub get
# Change the SDK version dart-services serves to the one you currently have installed
grind update-docker-version
# Begin serving the backend locally on port 8002.
grind serve &

cd ../dart-pad
# Begin serving the front-end locally on port 8000, with the given backend
export DARTPAD_BACKEND=http://localhost:8002 
grind serve-custom-backend
```

However, when I try `grind update-docker-version`

```bash
➜ grind update-docker-version
Error, no task found: 'update-docker-version'.
```

Is there other task that replaces `grind update-docker-version` ?

**Comment by jcollins-g** [comment]
This seems to work for me (grind update-docker-version).  Are you sure you have changed the working directory as in the instructions?

**Comment by amadeu01** [comment]
@jcollins-g I'll try it again.

**Comment by RedBrogdon** [comment]
Closing this for now, as it's been three months with no additional information. If the problem persists, please reopen.
