### ISSUE TITLE
list.add not running

### ISSUE THREAD

**Issue by joardar-aditya** [dart-lang/dart-pad#885]
i have tried to use .add with my list object but it is showing uncaught exception

**Comment by julemand101** [comment]
Can you give an example of the code your are trying to run but gives you an exception?

**Comment by RedBrogdon** [comment]
Just tested with this code:

```
void main() {
  final list = [1, 2, 3];
  list.add(4);
  print(list);
}
```

DartPad produced the expected [1, 2, 3, 4] as output.

If you can still reproduce this, please reopen and include the code that's giving you trouble.
