### ISSUE TITLE
add pub package support to dart-pad

### ISSUE THREAD

**Issue by baltringer** [dart-lang/dart-pad#886]
This library isn't working? Can this be added for testing?

import 'package:intl/intl.dart';

https://pub.dartlang.org/documentation/intl/latest/intl/DateFormat-class.html

**Comment by jcollins-g** [comment]
Pub packages are not supported on dart-pad.

**Comment by rakudrama** [comment]
I just wanted to do this!

**Comment by RedBrogdon** [comment]
It's on our radar, but we haven't had time to add it yet. Out of curiosity, which package did you want to import?

**Comment by rakudrama** [comment]
I wanted to use collection and intl.

**Comment by palexs** [comment]
@RedBrogdon I'd use `rxdart`.

**Comment by Chudesnov** [comment]
@RedBrogdon I would really like to test JS interop with `package:js`

**Comment by RollyPeres** [comment]
Tbh, `rxdart` is a must. Should be available by default.

**Comment by Xgamefactory** [comment]
yes without package support dartpad look incomplete

**Comment by domesticmouse** [comment]
De-duping this into https://github.com/dart-lang/dart-pad/issues/901

**Comment by CodeAlexx** [comment]
dartpad really useless without this

**Comment by santhonydo** [comment]
any way to parse xml w/out using xml pubpackage? i agree we need pub packages in dartpad

**Comment by rafaparada** [comment]
import 'package:http/http.dart' as http;
.
.
Unsupported input: package:http/http.dart

**Comment by lukepighetti** [comment]
Would like to be able to access `crypto` package

**Comment by DenisBarzanov** [comment]
I want http

**Comment by camillo777** [comment]
What about vector_math ????

**Comment by domesticmouse** [comment]
I hear you on wanting all the packages. Please track #901 for status updates. Thanks!
