### ISSUE TITLE
ProcessException: ol.get. Problem with memcache on backend

### ISSUE THREAD

**Issue by romikzo** [dart-lang/dart-pad#890]
When i trying to execute this code, i get an error https://pastebin.com/25pRdSJb.
```dart
void main() {
  List<String> a = ['Banana', 'Apple'];
  List<String> b = a;
  b[0] = 'Mango';
  print(a);
  print(b);
}
```
Sometimes code is working, sometimes i get another error:
```
Error compiling to JavaScript:
ProcessException: 
  Command: /usr/lib/dart/bin/dart2js --suppress-hints --terse --preview-dart-2 --enable-asserts --no-source-maps -omain.dart.js main.dart
```

**Comment by jcollins-g** [comment]
This is coming in from multiple sources.  We are having memcache errors on the backend for anything that is a cache miss, started at 7:30am PST

**Comment by jcollins-g** [comment]
It seems reasonable that whatever is going on, https://github.com/dart-lang/dart-services/pull/360 would likely fix it.  Trying a deploy with that first to see if it is true.

**Comment by jcollins-g** [comment]
New version deployed.  Waiting and watching graphs to see if problem is resolved.

**Comment by romikzo** [comment]
I can no longer get this error. Most likely the problem is solved

**Comment by jcollins-g** [comment]
15 minutes of logs on the new version, no more 500s.  Closing, but will continue to keep an eye out the rest of the afternoon.
