### ISSUE TITLE
Add end-to-end tests that drive the wrapper code

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#897]
See e.g. https://github.com/dart-lang/dart-services/pull/313

Our strong mode tests operate at one layer further in so didn't catch this. We should add a set of end-to-end tests as well that also drive the wrapper code.

**Comment by srawlins** [comment]
@domesticmouse this may be super outdated? Close as we have new tests?

**Comment by parlough** [comment]
I'm going to close this as dart_services has evolved a lot since this point. If anyone would like to see further testing here, please open a new issue with more details, thanks!
