### ISSUE TITLE
/fixes api requires a source offset but it's optional in the discovery protocol and ignored

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#898]
See: http://stackoverflow.com/questions/41942921/dart-services-api-how-to-access-the-fixes-through-the-api-service

**Comment by RedBrogdon** [comment]
@devoncarew Is this one still an issue? If so, what needs to be done here?

**Comment by devoncarew** [comment]
I don't have context here, but if the arg is not used in the dart-services implementation, we should likely remove from the protocol spec.

**Comment by domesticmouse** [comment]
Attempting to drop the `offset` argument to the `fixes` call winds up with a failing test, so I don't think this is actually ignored.

For context, here's the `fixes` call that is made to the analysis server, which does indeed reference a cursor location.

```
  /// Return the set of fixes that are available for the errors at a given
  /// offset in a given file.
  Future<FixesResult> getFixes(String file, int offset) {
    final Map m = {'file': file, 'offset': offset};
    return _call('edit.getFixes', m).then(FixesResult.parse);
  }
```
