### ISSUE TITLE
Support the new language-server-protocol ?

### ISSUE THREAD

**Issue by joeblew99** [dart-lang/dart-pad#899]
Raising this as a suggestion
https://github.com/Microsoft/language-server-protocol

A standard for language servers has been announced and is being used already.
This means that you can use VSCODE or cloud based IDE and they all use the same mechanism for integrating your language into the IDE.

In terms of LOE, this really makes things much more DRY for the dart-services team. One API to support for all IDE's !! 

This is a a cloud IDE that support the language server protocol
https://dzone.com/articles/eclipse-che-50-announced-at-checonf-2016

Google Cloud shell currently users the older Eclipse Orion.

**Comment by RedBrogdon** [comment]
Closing this one, as it sounds like an SDK issue rather than anything specific to dart-services. It may well be obsolete, since VS Code has a Dart/Flutter plugin now.
