### ISSUE TITLE
Replace plural() with the pluralize() function from the 'inflection' package.

### ISSUE THREAD

**Issue by gmosx** [dart-lang/dart-pad#90]
What about replacing the plural() function in 

lib/src/util.dart

with the pluralize() function in the 'inflection' package?

**Comment by devoncarew** [comment]
Sounds good to me; PR's welcome.

From digging though, it looks like the call-site for that method was the victim of some refactoring. We had been displaying the error count in the UI - `4 errors` - but we're no longer doing that.

**Comment by gmosx** [comment]
Well I could prepare a PR but since it's no longer used...

**Comment by devoncarew** [comment]
Yeah, but something to keep in mind for the future.
