### ISSUE TITLE
Add actionable feedback to errors and warnings

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#900]
We could help developers by giving them actionable feedback in warnings and errors, instead of just saying what is wrong.

For example, consider this code:

`new SolarSystem(canvas).star();`

![screen shot 2015-05-05 at 2 06 48 pm](https://cloud.githubusercontent.com/assets/5479/7482972/1ca85996-f330-11e4-942c-04fd70533873.png)

Expected:

The method 'star' is not defined for the class 'SolarSystem'. Did you mean 'start'?

Actual:

The method 'star' is not defined for the class 'SolarSystem'

**Comment by RedBrogdon** [comment]
Closing, since this is something the analyzer would need to do.
