### ISSUE TITLE
Link out to full DartPad from new embed UI

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#913]
The new embed UI should have a button or other control to launch a new browser window containing the full DartPad playground with the current snippet already loaded.

**Comment by RedBrogdon** [comment]
Removing this from the Q1 milestone. It's easy enough to do, but I'm not sure what value it adds for our first codelab. I'd like to hear from UXR before throwing another icon or button into the UI for it, basically.

**Comment by galeyang** [comment]
UXR feedback:

We discussed the detached editor in https://github.com/dart-lang/dart-pad/issues/1149 trying to reduce the issue of scrolling too much. The examples in that issue are detaching the editor but in the same webpage. I think this issue (Link out to full DartPad) can be another (potential easier) way to do it. It's not optimal to resolve this scrolling problem but an alternative.

Also, we did see one use case (https://github.com/dart-lang/dart-pad/issues/1201) that a user tried to copy the embed code to full dartpad.

**Comment by galeyang** [comment]
Offline discussion: what we need here is linking to a full-screen version of an embed with the current snippet already loaded. We will not have exercises in playground (at least for now). Exercises may need a different layout to show the instructions or context. The current and new playground focus on the purpose of trying out the code.

**Comment by RedBrogdon** [comment]
Moving this to the September milestone as a carryover.

**Comment by RedBrogdon** [comment]
After some offline discussion, it's been decided that the embedded layouts should link not to the front page of DartPad but to themselves in a new window. This will preserve the ability to run tests and see results.
