### ISSUE TITLE
Monte Carlo DartPad is unusable in Chrome Canary (74.0)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#914]
When I go to https://dartpad.dartlang.org/fae22cffa7b184b4d27cd96dd633a5af (Version 74.0.3694.0 (Official Build) canary (64-bit)), I see the DartPad top matter and running output (calculating pi). Then the window scrolls up, and I can't get it to scroll back.

DartPad works fine in Version 72.0.3626.81 (Official Build) (64-bit) and Version 72.0.3626.81 (Official Build) (64-bit).

I see no console warnings in either version. The front page of dartlang.org links to this DartPad, so it's important that it work correctly.

**Comment by devoncarew** [comment]
I don't this this issue - I'm using `74.0.3694.0 (Official Build) canary (64-bit)` (on a mac).

Can you attach a screenshot? The main portion of the window scrolls? Perhaps somehow the iframe's div height is increased.

**Comment by kwalrath** [comment]
Oh interesting... When I use an incognito window, it's fine. I wonder if it's something to do with one of my extensions.

**Comment by kwalrath** [comment]
![image](https://user-images.githubusercontent.com/2164483/52513065-2caf2580-2bbd-11e9-9ba1-43068916aafc.png)

**Comment by kwalrath** [comment]
Sometimes (not always) I can scroll up by selecting text. But I still don't get the DartPad controls.

I _do_ get the DartPad controls if I make the window really tall. They stay onscreen (often even at smaller window sizes) until I run the app again, at which time they scroll offscreen (like before) if there isn't a lot of space below the example code.

Maybe we should do a VC so you can see what I see?

**Comment by RedBrogdon** [comment]
@kwalrath Is this still an issue for you?

**Comment by kwalrath** [comment]
Yes, it still is. I'm using Version 76.0.3771.0 (Official Build) canary (64-bit).

**Comment by kwalrath** [comment]
Just to update this... I still see this in Canary (80.0.3968.0). I don't see it in Stable (78.0.3904.97).

Which makes me wonder if it's somehow connected to my work profile.

**Comment by kwalrath** [comment]
I'm not seeing it today. OK to close?

**Comment by domesticmouse** [comment]
Closing, thanks!
