### ISSUE TITLE
Share link overwrites github tab

### ISSUE THREAD

**Issue by alanhzhao** [dart-lang/dart-pad#917]
1. Press "Share..." button from DartPad
2. In the new "[Sharing Guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide)" tab, navigate away from the page to another github.com page (for example, click the https://gist.github.com/ link)
3. Press "Share..." button from DartPad again

Expect to open a new tab with "Sharing Guide". Instead, I am switched to the previous tab. And if I am at another github.com page, that page is replaced by "Sharing Guide". This is undesirable because it can cause me to lose the current state of the tab.

The only time that switching to the previous "Sharing Guide" tab is welcome is if I am still at that exact page. It also a bit inconvenient that this button isn't a link, so I can't right-click to copy the link address.

**Comment by parlough** [comment]
Thanks for reporting the issue! I can't reproduce this anymore with the newest DartPad frontend. If anyone else is still experiencing this, please open a new issue. Thanks so much!
