### ISSUE TITLE
How to use DateTime class? Can't import intl package

### ISSUE THREAD

**Issue by temirfe** [dart-lang/dart-pad#918]
I see that `DateTime` class is `dart:core` but dartpad doesn't recognize it. In flutter it's part of `Intl` package, but how can I use it in dartpad?

**Comment by kwalrath** [comment]
It works for me. I tried this code:

```
void main() {
  print(DateTime.now());
}
```

The output looks right:

```
2019-02-19 17:42:19.671
```

**Comment by domesticmouse** [comment]
@temirfe can you supply the code that wasn’t working, so we can debug? Thanks!

**Comment by temirfe** [comment]
@domesticmouse sorry, DateTime is working, I confused DateTime with `DateFormat` (Flutter's Intl package)

**Comment by domesticmouse** [comment]
Thanks for the clarification @temirfe, much appreciated!
