### ISSUE TITLE
automatic reconnection to memorystore doesn't work for some instances

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dart-pad#923]
Had a minor incident today where the backend lost connectivity to memorystore temporarily.  Most instances reconnected fine, but two did not.

[log entry for instance 1](https://console.cloud.google.com/logs/viewer?project=dart-services&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20190220t133251&minLogLevel=0&expandAll=false&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22dart-services%22%0Aresource.labels.version_id%3D%2220190220t133251%22%0Aresource.labels.module_id%3D%22default%22%0Atimestamp%3D%222019-02-26T02%3A08%3A14.000000000Z%22%0AinsertId%3D%22df0nbkhud36bgtb5p%22&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&timestamp=2019-02-26T02%3A37%3A50.372000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2019-02-25T20%3A37%3A50.625Z&dateRangeEnd=2019-02-26T02%3A37%3A50.625Z&interval=PT6H&scrollTimestamp=2019-02-26T02%3A08%3A14.000000000Z)

and

[log entry for instance 2](https://console.cloud.google.com/logs/viewer?project=dart-services&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20190220t133251&minLogLevel=0&expandAll=false&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22dart-services%22%0Aresource.labels.version_id%3D%2220190220t133251%22%0Aresource.labels.module_id%3D%22default%22%0Atimestamp%3D%222019-02-26T02%3A07%3A51.000000000Z%22%0AinsertId%3D%229i036nzxmi4xu5kbv%22&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fdart-services%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&timestamp=2019-02-26T02%3A37%3A50.372000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2019-02-25T20%3A37%3A50.625Z&dateRangeEnd=2019-02-26T02%3A37%3A50.625Z&interval=PT6H&scrollTimestamp=2019-02-26T02%3A07%3A57.599000000Z)

Marking as P2 since this causes no noticeable user errors other than somewhat slower performance and reduced scalability.

**Comment by domesticmouse** [comment]
The linked logs are long gone, and I haven't seen this re-occur. I'm closing this, and I'll open a new issue if and when it happens again.
