### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dart-pad#95]
When I go through the samples in order: Clock -> Some other sample, I get this error in console. For example for Clock -> Fibonacci:

Uncaught TypeError: Cannot set property 'textContent' of null
fibonacci(20) = 6765

**Comment by devoncarew** [comment]
Yes, we have a race condition :( I haven't tracked it down yet.

**Comment by devoncarew** [comment]
Fixed and re-deployed. @Janamou, thanks for the report!
