### ISSUE TITLE
Redis cache experiencing unavailability

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#950]
We're currently seeing alerts that the Redis cache used by dart-services is frequently unavailable. This affects the performance of the dart-services backend and needs to be investigated/fixed.

**Comment by domesticmouse** [comment]
Actually this is a different bug to the one I thought I was owning. I haven't seen this error in a while. Should we just assume that Cloud eng sorted it?

**Comment by RedBrogdon** [comment]
I no longer see evidence of this in the logs. Closing.
