### ISSUE TITLE
Make analysis/test results collapsible

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#976]
Both the flash containers in the new embed UI can become large and cover the editor. This is especially annoying for analysis, as there's currently no way to keep the flash closed (it pops open again as soon as you resume typing).

Ideally, these would be some kind of expanding UI element that appears with a summary (e.g. "Analyzer found six issues"), and then expand to the full list with a click.

**Comment by RedBrogdon** [comment]
Moving this out of M3, since we've solved the issue for now, but want to continue refining the solution.

**Comment by galeyang** [comment]
+1 to this issue. 

In the recent study, participants expressed their concerns that the flash pop-ups might obscure the code. One participant found it useful when he first saw it, but he dismissed the messages few times while he focused on coding.

**Comment by johnpryan** [comment]
#1050 should fix this
