### ISSUE TITLE
Feedback on dartpad2 tutorial

### ISSUE THREAD

**Issue by kf6gpe** [dart-lang/dart-pad#992]
Generally very clear and very few questions. Here's what I did observe, though:

1.  Errors compiling the following (I may just be missing something obvious)
```
String foo = 'a string';
String bar = null;

// Which operator assigns 'a string' to baz?
String baz = bar ?? foo;

// Which operator causes both of these fields to be 'a string'?
bar ??= 'a string';
foo ??= 'another string';
```

I _think_ this code is correct. This returned:
```
Error compiling to JavaScript:
DetailedApiRequestError(status: 400, message: main.dart:8:1:
Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
bar ??= 'a string';
^^^
main.dart:8:1:
Error: Expected ';' after this.
bar ??= 'a string';
^^^
main.dart:8:1:
Error: 'bar' is already declared in this scope.
bar ??= 'a string';
^^^
main.dart:2:8:
Info: Previous declaration of 'bar'.
String bar = null;
       ^^^
main.dart:8:5:
Error: Expected a declaration, but got '??='.
bar ??= 'a string';
    ^^^
main.dart:8:9:
Error: Expected a declaration, but got ''a string''.
bar ??= 'a string';
        ^^^^^^^^^^
main.dart:8:19:
Error: Unexpected token ';'.
bar ??= 'a string';
                  ^
main.dart:9:1:
Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
foo ??= 'another string';
^^^
main.dart:9:1:
Error: Expected ';' after this.
foo ??= 'another string';
^^^
main.dart:9:1:
Error: 'foo' is already declared in this scope.
foo ??= 'another string';
^^^
main.dart:1:8:
Info: Previous declaration of 'foo'.
String foo = 'a string';
       ^^^
main.dart:9:5:
Error: Expected a declaration, but got '??='.
foo ??= 'another string';
    ^^^
main.dart:9:9:
Error: Expected a declaration, but got ''another string''.
foo ??= 'another string';
        ^^^^^^^^^^^^^^^^
main.dart:9:25:
Error: Unexpected token ';'.
foo ??= 'another string';
                        ^
main.dart:5:21:
Error: Can't use 'foo' because it is declared more than once.
String baz = bar ?? foo;
                    ^
main.dart:5:14:
Error: Can't use 'bar' because it is declared more than once.
String baz = bar ?? foo;
             ^
main.dart:12:7:
Error: Can't use 'foo' because it is declared more than once.
  if (foo != 'a string') {
      ^
main.dart:14:14:
Error: Can't use 'bar' because it is declared more than once.
  } else if (bar != 'a string') {
             ^
Error: Compilation failed.
)
```

Note that “Check code” failed on the initial example as well, which is not surprising. I may have missed something stupid in the Dart, however.

1.   Arrow notation: the return value of the last assignment isn’t quite clear. Maybe “returns a string with each item in the array separated by commas”?

1.  Exception handling. The following code appears correct, but returns a test failure on execution:
```
typedef VoidFunction = void Function();

class ExceptionWithMessage {
  final String message;
  const ExceptionWithMessage(this.message);
}

// Call logException to log an exception, and doneLogging when finished.
abstract class Logger {
  void logException(Type t, [String msg]);
  void doneLogging();
}

void tryFunction(VoidFunction untrustworthy, Logger logger) {
  // Invoking this method might cause an exception. Catch and handle
  // them using try-on-catch-finally.
  try {
   untrustworthy(); 
  } on ExceptionWithMessage catch(e) {
    logger.logException(e.runtimeType, e.message);
  } on Exception catch(e) {
    logger.logException(e.runtimeType);
  } finally {
    logger.doneLogging();
  }
}
``` 

This returns the error `Untrustworthy threw an Exception, but a different close type was logged: _Exception.`

1. The InitalizersList example already has a definition of the `FirstTwoLetters` class in its test case.

**Comment by RedBrogdon** [comment]
> 1. Errors compiling the following (I may just be missing something obvious)

You're totally correct. I was attempting to do something illegal in the code snippet. I fixed it by wrapping the third assignment in a function, and simplified the exercise at the same time.

> 2. Arrow notation: the return value of the last assignment isn’t quite clear. Maybe “returns a string with each item in the array separated by commas”?

Nice catch. I updated the comment.

> 3. Exception handling. The following code appears correct, but returns a test failure on execution:

Again, great catch. The runtime type of my variable ended up being _Exception rather than Exception, which was throwing off the test. Also, you reinforced the need to change the close button on the analysis pane to something other than "close," since it blends too well with the text.

> 4. The InitalizersList example already has a definition of the FirstTwoLetters class in its test case.

&lt;facepalm&gt;
The _result function was still doubled up in there as well. It's fixed now.
