### ISSUE TITLE
P0: Writing overwrites following characters

### ISSUE THREAD

**Issue by jld3103** [dart-lang/dart-pad#996]
Today I used the Dartpad once again and I realized that the Dartpad is broken ;)
# Example
Click in the middle of the example string and write something. You will see that writing overwrites the following characters.

**Comment by jld3103** [comment]
I was using Firefox and had the default example loaded.
Typing overwrote the following characters.
An example:
```
aabb[cursor here]ccdd
```
Typing "eeff":
```
aabbeeff[cursor here]
```

**Comment by RedBrogdon** [comment]
Strange. I just downloaded Firefox 66.0.2, and I'm unable to replicate the behavior you're describing.

Do you have any Firefox addons installed that might be interfering with the site? Do you see the same behavior in Chrome/Safari/IE?

**Comment by jld3103** [comment]
It was my schools Firefox. It doesn't get updated very often. I can lookup the version on Thursday. There are no addons installed.

**Comment by jld3103** [comment]
At home I can't replicate the issue, too.

**Comment by RedBrogdon** [comment]
Got it. Based on the fact that this is only happening in one location and we're not seeing an army of people arrive and report the same issue, I'm going to chalk this one up to something weird with that particular browser/computer setup and close the issue.

Let us know the version number on Thursday just in case, though.
